Salesforce/main/default/main/default/objects/Area_Plantada__c/Area_Plantada__c.object-meta.xml
<CustomObject>
    <label>Área Plantada</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Código Area Plantada</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Áreas Plantadas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/Categoria__c/Categoria__c.object-meta.xml
<CustomObject>
    <description>Categorías</description>
    <label>Categoria</label>
    <nameField>
        <label>Nombre de Categoría</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categorias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/objects/OpportunityLineItem/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Ha. Autorizados</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/main/default/objects/OpportunityLineItem/fields/Area_Plantada__c.field-meta.xml
<CustomField>
    <fullName>Area_Plantada__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Algunas veces la cantidad de hectares qué autorizamos para nuestros clientes, ellos sembra menos. Por ejemplo, la Brasmax autoriza 100 hectares para sembrar, pero lo cliente sembra solamente 50 ha. Entonces, ese campo es “Ha Plantado”.</description>
    <inlineHelpText>Algunas veces la cantidad de hectares qué autorizamos para nuestros clientes, ellos sembra menos. Por ejemplo, la Brasmax autoriza 100 hectares para sembrar, pero lo cliente sembra solamente 50 ha. Entonces, ese campo es “Ha Plantado”.</inlineHelpText>
    <label>Ha. Plantados</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/objects/OpportunityLineItem/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Categoria a ser licenciada</description>
    <inlineHelpText>Categoria a ser licenciada</inlineHelpText>
    <label>Categoria</label>
    <referenceTo>Categoria__c</referenceTo>
    <relationshipLabel>Producto de oportunidad</relationshipLabel>
    <relationshipName>Producto_de_oportunidad</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/OpportunityLineItem/fields/Descarte__c.field-meta.xml
<CustomField>
    <fullName>Descarte__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Descarte(Sacas)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/main/default/objects/OpportunityLineItem/fields/Semente_bruta__c.field-meta.xml
<CustomField>
    <fullName>Semente_bruta__c</fullName>
    <label>Sem. Bruta (Sacas)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/main/default/objects/OpportunityLineItem/fields/Variedad_de_Produto__c.field-meta.xml
<CustomField>
    <fullName>Variedad_de_Produto__c</fullName>
    <formula>PricebookEntry.Product2.Variedade__r.Nombre_de_Registro__c</formula>
    <label>Registro Cultivar</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/OpportunityLineItem/fields/Variedade_Prod__c.field-meta.xml
<CustomField>
    <fullName>Variedade_Prod__c</fullName>
    <formula>PricebookEntry.Product2.Variedade__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Nome Comercial</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/Product2/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <label>Categoria</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BREEDER</fullName>
            </value>
            <value>
                <fullName>FUNDADORA</fullName>
            </value>
            <value>
                <fullName>Genetica</fullName>
            </value>
            <value>
                <fullName>Pre Basica</fullName>
            </value>
            <value>
                <fullName>BASICA</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>C1</fullName>
            </value>
            <value>
                <fullName>C2</fullName>
            </value>
            <value>
                <fullName>R</fullName>
            </value>
            <value>
                <fullName>S1</fullName>
            </value>
            <value>
                <fullName>S2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Product2/fields/Variedade__c.field-meta.xml
<CustomField>
    <fullName>Variedade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Variedade</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Variedad__c.Licenciada__c</field>
            <operation>equals</operation>
            <valueField>$Source.Licenciada__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Variedad__c</referenceTo>
    <relationshipLabel>Productos</relationshipLabel>
    <relationshipName>Productos</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/classes/ProductsA2API.cls
@RestResource(urlMapping='/ProductsA2API/*')
global with sharing class ProductsA2API {

    /**
     *  SUBCLASS:       Response
     *  CONSTRUCTORS:   - 
     *  DESCRIPTION:    wrapper class for Products A2 API response. Created for US #12696 
     *  AUTHOR:         irina.benitez@cloudgaia.com (16-sept-21)
     **/ 
    public class Response {
        public Boolean status;
        public String message;
        public String epoca;
        public List<aAppendix.myOppItem> productsA2 = new List<aAppendix.myOppItem>();
    }

     /**
     *  METHOD:         getProductsAppendix2 
     *  PARAMETERS:     accountId: Id of an Account record 
     *                  safra  
     *                  marca 
     *  RETURN:         message: displays 'success' or error message  
     *                  status: boolean shows if operation was succesfull
     *                  productsA2: list of records to return
     *  DESCRIPTION:    Return list of products for Anexo II. Created for US #12696 
     *  AUTHOR:         irina.benitez@cloudgaia.com (13-sept-21)
     **/ 
    @HttpGet
    global static void getProductsAppendix2() {

        String accountId = RestContext.request.params.get('accountId');
        String safra = RestContext.request.params.get('safra');
        String marca = RestContext.request.params.get('marca');

        RestResponse response = RestContext.response;
        response.statusCode = 404;

        Response result = new Response();
        result.status = false;
        result.message = Label.Anexo_II_Val_Existe_Anexo_I;
        
        try {
            result.epoca = aAppManager.getEpocaPlantioToA2(accountId, safra, marca);
            List<OpportunityLineItem> tmpOppItems = aAppManager.getAnexosItemsToA2(accountId, safra, marca, result.epoca);
            tmpOppItems = aAppManager.valAnexos2_A(tmpOppItems);
            result.productsA2 = oppLineItemJSONConverter(tmpOppItems, result.epoca);
        } catch (Exception exc) {
            response.statusCode = 400;
            result.message = exc.getMessage();
        }
                
        if(result.productsA2 != null && !result.productsA2.isEmpty()) {
            result.status = true;
            result.message = Label.ProductsA2API_Success_Message;
            response.statusCode = 200;
        }

        response.responseBody = Blob.valueOf(JSON.serialize(result));
        response.headers.put('Content-Type', 'application/json');
        response.headers.put('Content-Length', RestContext.response.responseBody.size()+'');
    }


    /**
     *  METHOD:         oppLineItemJSONConverter 
     *  PARAMETERS:     oppLineItems: List of OpportunityLineItems in sObject format 
     *  RETURN:         List<aAppendix.myOppItem>: list of records in JSON format to return
     *  DESCRIPTION:    Helper method converts opportunityLineItem sObject in aAppendix.myOppItem JSON wrapper. Created for US #12696 
     *  AUTHOR:         irina.benitez@cloudgaia.com (20-sept-21)
     **/ 
    public static List<aAppendix.myOppItem> oppLineItemJSONConverter(List<OpportunityLineItem> oppLineItems, String epocaDePlantio) {

        List<aAppendix.myOppItem> result = new List<aAppendix.myOppItem>();

        if(oppLineItems != null && oppLineItems.size() > 0) {
            Map<String, OpportunityLineItem> mapOppApp = new Map<String, OpportunityLineItem>();

            for(OpportunityLineItem oppLineItem : oppLineItems){
                if(!mapOppApp.containsKey(oppLineItem.Categoria__r.Name + oppLineItem.Variedade_Prod__c)){                           
                    mapOppApp.put(oppLineItem.Categoria__r.Name + oppLineItem.Variedade_Prod__c, oppLineItem);
                }
            }
        
            for(OpportunityLineItem oppLineItem : oppLineItems){
                aAppendix.myOppItem oli = new aAppendix.myOppItem();
                oli.variedad = oppLineItem.PricebookEntry.Product2.Variedade__c;
                oli.variedad_nombre = oppLineItem.Variedade_Prod__c;
                oli.variedad_registro = oppLineItem.Variedad_de_Produto__c;
                oli.categoria = oppLineItem.Categoria__r.Name;
                oli.categoria_id = oppLineItem.Categoria__c;
                oli.area_autorizada = String.valueOf(oppLineItem.area__c);
                if(mapOppApp.containsKey(oppLineItem.Categoria__r.Name + oppLineItem.Variedade_Prod__c)){
                    OpportunityLineItem i = mapOppApp.get(oppLineItem.Categoria__r.Name + oppLineItem.Variedade_Prod__c);
                    oli.area_autorizada = String.valueOf(i.area__c);
                }

                oli.area_plantada = String.valueOf(oppLineItem.Area_plantada__c);
                oli.sem_bruta = String.valueOf(oppLineItem.Semente_bruta__c);                
                oli.descarte = String.valueOf(oppLineItem.Descarte__c);
                oli.epocaPlantio = epocaDePlantio;

                result.add(oli);
            }
        }

        return result;
    }

}