Salesforce/main/default/main/default/objects/Area_Plantada__c/Area_Plantada__c.object-meta.xml
<CustomObject>
    <label>Área Plantada</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Código Area Plantada</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Áreas Plantadas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/objects/CRM_Calendario_de_Eventos__c/CRM_Calendario_de_Eventos__c.object-meta.xml
<CustomObject>
    <description>Registro de eventos programados pelo Multiplicador</description>
    <label>CRM Evento</label>
    <nameField>
        <label>Nome de CRM Evento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Eventos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/CRM_Calendario_de_Eventos__c/fields/Produtividade__c.field-meta.xml
<CustomField>
    <fullName>Produtividade__c</fullName>
    <description>Produtividade em kg/ha</description>
    <inlineHelpText>Informar em kg/ha</inlineHelpText>
    <label>Produtividade</label>
    <summarizedField>CRM_Detalle_Calendario_de_eventos__c.Produtividade__c</summarizedField>
    <summaryForeignKey>CRM_Detalle_Calendario_de_eventos__c.CRM_Calendario_de_eventos__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

Salesforce/main/default/objects/CRM_Detalle_Calendario_de_eventos__c/CRM_Detalle_Calendario_de_eventos__c.object-meta.xml
<CustomObject>
    <label>CRM Detalle Calendário de eventos</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Nombre de CRM Detalle Calendário de even</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CRM Detalles Calendário de eventos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/CRM_Detalle_Calendario_de_eventos__c/fields/Area_Colhida__c.field-meta.xml
<CustomField>
    <fullName>Area_Colhida__c</fullName>
    <label>Área Colhida (Ha)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/main/default/objects/CRM_Detalle_Calendario_de_eventos__c/fields/Area_plantada__c.field-meta.xml
<CustomField>
    <fullName>Area_plantada__c</fullName>
    <label>Área Plantada (Ha)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/objects/CRM_Detalle_Calendario_de_eventos__c/fields/CRM_Calendario_de_eventos__c.field-meta.xml
<CustomField>
    <fullName>CRM_Calendario_de_eventos__c</fullName>
    <label>CRM Calendário de eventos</label>
    <referenceTo>CRM_Calendario_de_Eventos__c</referenceTo>
    <relationshipLabel>Itens</relationshipLabel>
    <relationshipName>CRM_Detalles_Calend_rio_de_eventos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Salesforce/main/default/objects/CRM_Detalle_Calendario_de_eventos__c/fields/Cultura_antecessora__c.field-meta.xml
<CustomField>
    <fullName>Cultura_antecessora__c</fullName>
    <label>Cultura antecessora</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Algodão</fullName>
            </value>
            <value>
                <fullName>Amendoim</fullName>
            </value>
            <value>
                <fullName>Arroz</fullName>
            </value>
            <value>
                <fullName>Aveia</fullName>
            </value>
            <value>
                <fullName>Azevem</fullName>
            </value>
            <value>
                <fullName>Batata</fullName>
            </value>
            <value>
                <fullName>Brachiaria</fullName>
            </value>
            <value>
                <fullName>Canola</fullName>
            </value>
            <value>
                <fullName>Centeio</fullName>
            </value>
            <value>
                <fullName>Cevada</fullName>
            </value>
            <value>
                <fullName>Ervilhaca</fullName>
            </value>
            <value>
                <fullName>Feijão</fullName>
            </value>
            <value>
                <fullName>Girassol</fullName>
            </value>
            <value>
                <fullName>MIL. + BRA</fullName>
            </value>
            <value>
                <fullName>Milheto</fullName>
            </value>
            <value>
                <fullName>Milho</fullName>
            </value>
            <value>
                <fullName>Pasto</fullName>
            </value>
            <value>
                <fullName>Pousio</fullName>
            </value>
            <value>
                <fullName>Soja</fullName>
            </value>
            <value>
                <fullName>Sorgo</fullName>
            </value>
            <value>
                <fullName>Trigo</fullName>
            </value>
            <value>
                <fullName>Triticale</fullName>
            </value>
            <value>
                <fullName>Outro</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/CRM_Detalle_Calendario_de_eventos__c/fields/Data_de_colheita__c.field-meta.xml
<CustomField>
    <fullName>Data_de_colheita__c</fullName>
    <label>Data de colheita</label>
    <type>Date</type>
</CustomField>

Salesforce/main/default/objects/CRM_Detalle_Calendario_de_eventos__c/fields/Data_de_plantio__c.field-meta.xml
<CustomField>
    <fullName>Data_de_plantio__c</fullName>
    <label>Data de plantio</label>
    <type>Date</type>
</CustomField>

Salesforce/main/default/main/default/objects/CRM_Detalle_Calendario_de_eventos__c/fields/Espacamento__c.field-meta.xml
<CustomField>
    <fullName>Espacamento__c</fullName>
    <label>Espaçamento (cm)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/main/default/objects/CRM_Detalle_Calendario_de_eventos__c/fields/Populacao_de_plantas__c.field-meta.xml
<CustomField>
    <fullName>Populacao_de_plantas__c</fullName>
    <label>População de plantas (Plantas/metro)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/objects/CRM_Detalle_Calendario_de_eventos__c/fields/Produtividade__c.field-meta.xml
<CustomField>
    <fullName>Produtividade__c</fullName>
    <label>Produtividade (Kg/ha)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/objects/CRM_Detalle_Calendario_de_eventos__c/fields/Produto_Principal__c.field-meta.xml
<CustomField>
    <fullName>Produto_Principal__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Produto Principal</label>
    <type>Checkbox</type>
</CustomField>

Salesforce/main/default/main/default/objects/CRM_Detalle_Calendario_de_eventos__c/fields/Volume_Doado__c.field-meta.xml
<CustomField>
    <fullName>Volume_Doado__c</fullName>
    <label>Volume Doado (Kg)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/main/default/classes/approvalButtonCRMEventoController.cls
public with sharing class approvalButtonCRMEventoController {

    @AuraEnabled
    public static List<CRM_Detalle_Calendario_de_eventos__c> getItems(Id recordId) {
        return [
            SELECT Id, Name, Produto_Principal__c, Area_plantada__c, Area_Colhida__c, Data_de_plantio__c, Data_de_colheita__c,
                Produtividade__c, Volume_Doado__c, Populacao_de_plantas__c, Espacamento__c, Cultura_antecessora__c
            FROM CRM_Detalle_Calendario_de_eventos__c
            WHERE CRM_Calendario_de_eventos__c = :recordId
        ];
    }

    @AuraEnabled
    public static AggregateResult countNumberOfDocuments(Id recordId) {
        return [SELECT COUNT(Id) Total FROM ContentDocumentLink WHERE LinkedEntityId = :recordId];
    }

    @AuraEnabled
    public static Boolean sendApprovalRequest(Id recordId, Id ownerId) {
        Approval.ProcessSubmitRequest request = new Approval.ProcessSubmitRequest();    
        request.setObjectId(recordId);
        request.setNextApproverIds(new Id[]{ownerId});

        Boolean result = false;

        try {
            Approval.ProcessResult pResult = Approval.process(request);
            result = pResult.isSuccess();
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }

        return result;
    }
}