Salesforce/main/default/main/default/objects/Area_Plantada__c/Area_Plantada__c.object-meta.xml
<CustomObject>
    <label>Área Plantada</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Código Area Plantada</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Áreas Plantadas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/Categoria__c/Categoria__c.object-meta.xml
<CustomObject>
    <description>Categorías</description>
    <label>Categoria</label>
    <nameField>
        <label>Nombre de Categoría</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categorias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/Opportunity/fields/Estado_Anexos_Portal_Miltiplicadores__c.field-meta.xml
<CustomField>
    <fullName>Estado_Anexos_Portal_Miltiplicadores__c</fullName>
    <formula>CASE(StageName, &quot;Edición&quot;, &quot;Edição&quot;, &quot;Edición post Vencimiento&quot;, &quot;Edición&quot;, &quot;Edición Vencida&quot;, &quot;Edición&quot;, &quot;Pendiente de Análisis&quot;, &quot;Bloqueado&quot;, &quot;Pendiente de Aprobación&quot;, &quot;Bloqueado&quot;, &quot;Desaprobado x Gerente&quot;, &quot;Rechazado&quot;, &quot;Rechazada Supervisor&quot;, &quot;Rechazado&quot;, &quot;Aprobada&quot;, &quot;Aprovado&quot;, &quot;AN - Anulada&quot;, &quot;Anulado&quot;, &quot;&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Fase</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/Opportunity/fields/Estado_de_Comercializacion__c.field-meta.xml
<CustomField>
    <fullName>Estado_de_Comercializacion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Utilizado para el Anexo I</description>
    <inlineHelpText>Utilizado para el Anexo I</inlineHelpText>
    <label>Estado de Comercializacion</label>
    <referenceTo>Estado__c</referenceTo>
    <relationshipLabel>Oportunidades (Estado de Comercializacion)</relationshipLabel>
    <relationshipName>Oportunidades1</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/Opportunity/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <description>Identifica la marca para las Oportunidades del Circuito de Anexos. Se selecciona la lista de precios en función de este campo</description>
    <inlineHelpText>Identificar a marca de Oportunidades Circuito Anexos. Você seleciona a lista de preços com base neste campo</inlineHelpText>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BRMX</fullName>
            </value>
            <value>
                <fullName>DSEM</fullName>
            </value>
            <value>
                <fullName>NEOG</fullName>
            </value>
            <value>
                <fullName>DAGMA</fullName>
            </value>
            <value>
                <fullName>LICENÇAS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Opportunity/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <description>Safra o Campania agricola</description>
    <label>Safra</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>06/07</fullName>
            </value>
            <value>
                <fullName>07/08</fullName>
            </value>
            <value>
                <fullName>08/09</fullName>
            </value>
            <value>
                <fullName>09/10</fullName>
            </value>
            <value>
                <fullName>09/09</fullName>
            </value>
            <value>
                <fullName>10/10</fullName>
            </value>
            <value>
                <fullName>10/11</fullName>
            </value>
            <value>
                <fullName>11/11</fullName>
            </value>
            <value>
                <fullName>11/12</fullName>
            </value>
            <value>
                <fullName>12/12</fullName>
            </value>
            <value>
                <fullName>12/13</fullName>
            </value>
            <value>
                <fullName>13/14</fullName>
            </value>
            <value>
                <fullName>14/15</fullName>
            </value>
            <value>
                <fullName>15/16</fullName>
            </value>
            <value>
                <fullName>16/17</fullName>
            </value>
            <value>
                <fullName>17/18</fullName>
            </value>
            <value>
                <fullName>18/19</fullName>
            </value>
            <value>
                <fullName>19/20</fullName>
            </value>
            <value>
                <fullName>20/21</fullName>
            </value>
            <value>
                <fullName>21/22</fullName>
                <default>true</default>
                <label>21/22</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Opportunity/recordTypes/Anexo_III.recordType-meta.xml
<RecordType>
    <fullName>Anexo_III</fullName>
    <active>true</active>
    <businessProcess>Circuito de Anexos</businessProcess>
    <label>Anexo III</label>
</RecordType>

Salesforce/main/default/objects/Opportunity/recordTypes/Anexo_IV.recordType-meta.xml
<RecordType>
    <fullName>Anexo_IV</fullName>
    <active>true</active>
    <businessProcess>Circuito de Anexos</businessProcess>
    <label>Anexo IV</label>
</RecordType>

Salesforce/main/default/objects/Opportunity/recordTypes/Descarte.recordType-meta.xml
<RecordType>
    <fullName>Descarte</fullName>
    <active>true</active>
    <businessProcess>Circuito de Anexos</businessProcess>
    <label>Descarte</label>
</RecordType>

Salesforce/main/default/objects/OpportunityLineItem/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Ha. Autorizados</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/main/default/objects/OpportunityLineItem/fields/Area_Plantada__c.field-meta.xml
<CustomField>
    <fullName>Area_Plantada__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Algunas veces la cantidad de hectares qué autorizamos para nuestros clientes, ellos sembra menos. Por ejemplo, la Brasmax autoriza 100 hectares para sembrar, pero lo cliente sembra solamente 50 ha. Entonces, ese campo es “Ha Plantado”.</description>
    <inlineHelpText>Algunas veces la cantidad de hectares qué autorizamos para nuestros clientes, ellos sembra menos. Por ejemplo, la Brasmax autoriza 100 hectares para sembrar, pero lo cliente sembra solamente 50 ha. Entonces, ese campo es “Ha Plantado”.</inlineHelpText>
    <label>Ha. Plantados</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/objects/OpportunityLineItem/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Categoria a ser licenciada</description>
    <inlineHelpText>Categoria a ser licenciada</inlineHelpText>
    <label>Categoria</label>
    <referenceTo>Categoria__c</referenceTo>
    <relationshipLabel>Producto de oportunidad</relationshipLabel>
    <relationshipName>Producto_de_oportunidad</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/OpportunityLineItem/fields/Descarte__c.field-meta.xml
<CustomField>
    <fullName>Descarte__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Descarte(Sacas)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/main/default/objects/OpportunityLineItem/fields/Estado_de_Comercializacion__c.field-meta.xml
<CustomField>
    <fullName>Estado_de_Comercializacion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Estado de Comercialização</label>
    <referenceTo>Estado__c</referenceTo>
    <relationshipLabel>Producto de oportunidad (Estado de Cermercializacion)</relationshipLabel>
    <relationshipName>Producto_de_oportunidad1</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/OpportunityLineItem/fields/Item_Rebajado__c.field-meta.xml
<CustomField>
    <fullName>Item_Rebajado__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indica si corresponde al ítem generado para restarle la cantidad a la categoría rebajada. Para la sumarizacion en reportes.</description>
    <label>Item Rebajado</label>
    <type>Checkbox</type>
</CustomField>

Salesforce/main/default/objects/OpportunityLineItem/fields/Registro_Cultivar__c.field-meta.xml
<CustomField>
    <fullName>Registro_Cultivar__c</fullName>
    <formula>PricebookEntry.Product2.Variedade__r.Nombre_de_Registro__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Registro Cultivar</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/OpportunityLineItem/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <formula>TEXT(Opportunity.Safra__c)</formula>
    <label>Safra</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/OpportunityLineItem/fields/Semente_aprovada__c.field-meta.xml
<CustomField>
    <fullName>Semente_aprovada__c</fullName>
    <label>Sem. Aprovada (Sacas)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/main/default/objects/OpportunityLineItem/fields/Semente_beneficiada__c.field-meta.xml
<CustomField>
    <fullName>Semente_beneficiada__c</fullName>
    <label>Sem. Beneficiada (Sacas)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/main/default/objects/OpportunityLineItem/fields/Semente_bruta__c.field-meta.xml
<CustomField>
    <fullName>Semente_bruta__c</fullName>
    <label>Sem. Bruta (Sacas)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/main/default/objects/OpportunityLineItem/fields/Semente_comercializada__c.field-meta.xml
<CustomField>
    <fullName>Semente_comercializada__c</fullName>
    <label>Sem. Comercializada (Sacas)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/main/default/objects/OpportunityLineItem/fields/Semente_uso_propio__c.field-meta.xml
<CustomField>
    <fullName>Semente_uso_propio__c</fullName>
    <label>Sem. Uso Próprio (Sacas)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/main/default/objects/OpportunityLineItem/fields/Variedad_de_Produto__c.field-meta.xml
<CustomField>
    <fullName>Variedad_de_Produto__c</fullName>
    <formula>PricebookEntry.Product2.Variedade__r.Nombre_de_Registro__c</formula>
    <label>Registro Cultivar</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/OpportunityLineItem/fields/Variedade_Prod__c.field-meta.xml
<CustomField>
    <fullName>Variedade_Prod__c</fullName>
    <formula>PricebookEntry.Product2.Variedade__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Nome Comercial</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/Product2/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <label>Categoria</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BREEDER</fullName>
            </value>
            <value>
                <fullName>FUNDADORA</fullName>
            </value>
            <value>
                <fullName>Genetica</fullName>
            </value>
            <value>
                <fullName>Pre Basica</fullName>
            </value>
            <value>
                <fullName>BASICA</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>C1</fullName>
            </value>
            <value>
                <fullName>C2</fullName>
            </value>
            <value>
                <fullName>R</fullName>
            </value>
            <value>
                <fullName>S1</fullName>
            </value>
            <value>
                <fullName>S2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Product2/fields/Variedade__c.field-meta.xml
<CustomField>
    <fullName>Variedade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Variedade</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Variedad__c.Licenciada__c</field>
            <operation>equals</operation>
            <valueField>$Source.Licenciada__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Variedad__c</referenceTo>
    <relationshipLabel>Productos</relationshipLabel>
    <relationshipName>Productos</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/classes/ProductsA5API.cls
/**
* @name ProductsA5API
* @author Jhonny Peroza
* updated 06-10-2021
* updated 03/01/2022 by Developer: Pablo Fraquia pablo.fraquia@cloudgaia.com
*/
@RestResource(urlMapping='/ProductsA5API/*')
global with sharing class ProductsA5API {
    
    @HttpGet
    global static void getProductsForAnexosV() {
        
        Id accountId = RestContext.request.params.get('accountId');
        String marca = RestContext.request.params.get('marca');
        String safra = RestContext.request.params.get('safra');
        
        RestResponse response = RestContext.response;
        response.statusCode = 404;
        
        Response result = new Response();
        result.status = false;
        
        try {
            //Las variedad de Anexos 3 y Anexos 4 son iguales por lo que traemos anexos3 tal y como lo hace la logica legacy
            List<Opportunity> anexos3List = aAppManager.getAnexos3(accountId, safra, marca);
            
            if(!anexos3List.isEmpty()){
                
                Map<Id,List<aAppendix.myOppItem>> productsByOpp = new Map<Id,List<aAppendix.myOppItem>>();

                
                for(Opportunity opp: anexos3List){
                    
                    List<OpportunityLineItem> oppLineItemsList = aAppManager.getAnexosItemsByOpp(opp.Id);
                    List<aAppendix.myOppItem> itemsbyOpp = oppLineItemJSONConverter(oppLineItemsList, getTotalSacasDisponibles(accountId, safra, marca));
                    
                    if(!itemsbyOpp.isEmpty()) {
                        productsByOpp.put(opp.Id, itemsbyOpp);
                    }
                }

                result.message = Label.ProductsA5API_Success_Message;
                result.productsToShow = productsByOpp;
                                
            } else {
                
                result.message = Label.ProductsA5API_Default_Error_Message;
            }

            result.status = true;
            response.statusCode = 200;
            
        } catch (Exception e) {
            
            result.message = e.getMessage();
        }
        
        response.responseBody = Blob.valueOf(JSON.serialize(result));
    }
    
    public Static Map<String, Double> getTotalSacasDisponibles(Id accountId, String safra, String marca){
          
        Map<String, Double> sacasDispByVariedad = new Map<String, Double>();
    
            String queryPlus = 'PricebookEntry.Product2.Variedade__c, Categoria__r.Name, Opportunity.Name';           
            List<OpportunityLineItem> oppLineItemsListA3A4 = aSiteUtils.queryResults6(OpportunityLineItem.SObjectType, queryPlus, 'Opportunity.RecordType.DeveloperName in :v1', new String[]{'Anexo_III', 'Anexo_IV'}, 'Opportunity.Safra__c = :v2', safra, 'Opportunity.Marca__c = :v3', marca, 'Opportunity.AccountId = :v4', accountId, 'Item_Rebajado__c = :v5', false, 'Opportunity.Estado_Anexos_Portal_Miltiplicadores__c != :v6', 'Anulado');
            if(!oppLineItemsListA3A4.isEmpty()) {
                
                for (OpportunityLineItem producto : oppLineItemsListA3A4){
                    
                    if(producto.Semente_comercializada__c == null){
                        producto.Semente_comercializada__c = 0;
                    }
                    if(producto.Semente_uso_propio__c == null){
                        producto.Semente_uso_propio__c = 0;
                    }
                    
                    if (!sacasDispByVariedad.containsKey(String.valueOf(producto.PricebookEntry.Product2.Variedade__c))){
                        
                        sacasDispByVariedad.put(String.valueOf(producto.PricebookEntry.Product2.Variedade__c), Double.valueOf(producto.Semente_comercializada__c) + Double.valueOf(producto.Semente_uso_propio__c));
                        
                    } else{
                        
                        Double sacasDisponibles = sacasDispByVariedad.get(String.valueOf(producto.PricebookEntry.Product2.Variedade__c));
                        sacasDisponibles += Double.valueOf(producto.Semente_comercializada__c) + Double.valueOf(producto.Semente_uso_propio__c);
                        sacasDispByVariedad.remove(String.valueOf(producto.PricebookEntry.Product2.Variedade__c));
                        sacasDispByVariedad.put(String.valueOf(producto.PricebookEntry.Product2.Variedade__c), sacasDisponibles);                       
                    }                  
                }
            }
       
        return sacasDispByVariedad;
    }
    
    public static List<aAppendix.myOppItem> oppLineItemJSONConverter(List<OpportunityLineItem> oppLineItemsList,  Map<String, Double> sacasDispByVariedad) {
        
        List<aAppendix.myOppItem> result = new List<aAppendix.myOppItem>();
        
        for(OpportunityLineItem oppLineItem : oppLineItemsList){
            aAppendix.myOppItem oli = new aAppendix.myOppItem();
            oli.variedad = oppLineItem.PricebookEntry.Product2.Variedade__c;
            oli.variedad_nombre = oppLineItem.Variedade_Prod__c;
            oli.variedad_registro = oppLineItem.Variedad_de_Produto__c;
            oli.registro = oppLineItem.Registro_Cultivar__c;
            oli.sem_comerci = oppLineItem.Semente_comercializada__c;
            oli.estado_comer = oppLineItem.Estado_de_Comercializacion__c;
            oli.categoria = oppLineItem.Categoria__r.Name;
            oli.categoria_id = oppLineItem.Categoria__c;
            oli.area_autorizada = String.valueOf(oppLineItem.Area__c);
            oli.area_plantada = String.valueOf(oppLineItem.Area_plantada__c);
            oli.sem_bruta = String.valueOf(oppLineItem.Semente_bruta__c);                
            oli.descarte = String.valueOf(oppLineItem.Descarte__c);
            oli.sem_beneficiada = String.valueOf(oppLineItem.Semente_beneficiada__c);                
            oli.sem_aprobada = String.valueOf(oppLineItem.Semente_aprovada__c);
            oli.sem_uso_propio = String.valueOf(oppLineItem.Semente_uso_propio__c);  
            oli.unidadDescarte = Integer.valueOf(oppLineItem.Descarte__c);
            oli.amount = Double.valueOf(oppLineItem.TotalPrice);
            oli.sacas_disponibles = String.valueOf(sacasDispByVariedad.get(oppLineItem.PricebookEntry.Product2.Variedade__c));
            
            result.add(oli);
        }
        
        return result;
    }
    
    public class Response {
        
        public Boolean status;
        public String message;
        public Map<Id,List<aAppendix.myOppItem>> productsToShow = new Map<Id,List<aAppendix.myOppItem>>();
    }
}