Salesforce/main/default/objects/Order/fields/Numero_Pedido_SAP__c.field-meta.xml
<CustomField>
    <fullName>Numero_Pedido_SAP__c</fullName>
    <label>Numero de Pedido SAP</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/Order/fields/Pai__c.field-meta.xml
<CustomField>
    <fullName>Pai__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Pedido padre</description>
    <label>Número da Oferta Subsequente</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Pedidos</relationshipLabel>
    <relationshipName>Filho</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/classes/ordemDeCompraController.cls
public class ordemDeCompraController {
    @AuraEnabled
    public static String consultaSapController(String purchaseOrder){
        
        List<Order> existOrder = sapHistorialDePedidosSoapFunctions.CheckExistingOrder(purchaseOrder);
        
        if (!existOrder.isEmpty() && existOrder[0].Status == 'Edição') {
            return 'Já existe um pedido em edição. Ative o antigo para criar um novo.';
        }
        
        Id orderId = sapHistorialDePedidosSoapFunctions.GenerateOrder(purchaseOrder);
        
        if (!existOrder.isEmpty() && orderId != null) {
            existOrder[0].Status = 'Draft';
            existOrder[0].Pai__c = orderId;
            update existOrder;
        }
        
        return orderId;
        
    }
    
       @AuraEnabled
    public static String consultaSapControllerWithOldOrder(Id orderId){                
        
        String orderNumber = [SELECT Numero_Pedido_sap__c FROM Order WHERE Id = :orderId][0].Numero_Pedido_sap__c;       
        return consultaSapController(orderNumber);     
        
    }
    
}