Salesforce/main/default/objects/GDMException__c/GDMException__c.object-meta.xml
<CustomObject>
    <label>GDMException</label>
    <nameField>
        <displayFormat>EXC-{0}</displayFormat>
        <label>Exception Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GDMExceptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/objects/GDMException__c/fields/Line__c.field-meta.xml
<CustomField>
    <fullName>Line__c</fullName>
    <label>Line</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/main/default/objects/GDMException__c/fields/Message_Long__c.field-meta.xml
<CustomField>
    <fullName>Message_Long__c</fullName>
    <label>Message Long</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

Salesforce/main/default/objects/GDMException__c/fields/StackTrace__c.field-meta.xml
<CustomField>
    <fullName>StackTrace__c</fullName>
    <label>StackTrace</label>
    <type>TextArea</type>
</CustomField>

Salesforce/main/default/objects/GDMException__c/fields/StackTrace_Long__c.field-meta.xml
<CustomField>
    <fullName>StackTrace_Long__c</fullName>
    <label>StackTrace Long</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

Salesforce/main/default/classes/ExceptionManager.cls
public class ExceptionManager {

    public static void saveException(Exception e, String apexClass, String method, Id recordId) {
        GDMException__c exceptionObject = new GDMException__c();
        exceptionObject.Class__c = apexClass;
        exceptionObject.Method__c = method;
        exceptionObject.Record_Id__c = recordId;
        
        if(e != null) {
            exceptionObject.Line__c = e.getLineNumber();
            exceptionObject.Type__c = e.getTypeName();
            exceptionObject.Message_Long__c = e.getMessage();
            exceptionObject.StackTrace_Long__c = e.getStackTraceString();
            if(e.getStackTraceString() != null && e.getStackTraceString().length() > 255) {
                exceptionObject.StackTrace__c = e.getStackTraceString().substring(0, 254);
            } else {
                exceptionObject.StackTrace__c = e.getStackTraceString();
            }
            if(e.getMessage() != null && e.getMessage().length() > 255) {
                exceptionObject.Message__c = e.getMessage().substring(0, 254);
            } else {
                exceptionObject.Message__c = e.getMessage();
            }
        }
        
        try {
            insert exceptionObject;
        } catch (Exception insertException) {
            System.debug('Erro to save Exception' + insertException.getMessage());
        }
    }
    
    public static void saveMessage(String message, String apexClass, String method, Id recordId, String messageType) {
        GDMException__c exceptionObject = new GDMException__c();
        exceptionObject.Class__c = apexClass;
        exceptionObject.Method__c = method;
        exceptionObject.Record_Id__c = recordId;
        exceptionObject.Message_Long__c = message;
        if(message != null && message.length() > 255) {
        	exceptionObject.Message__c = message.substring(0, 254);
        } else {
        	exceptionObject.Message__c = message;
        }
        exceptionObject.Type__c = messageType;
        
        try {
            insert exceptionObject;
        } catch (Exception insertException) {
            System.debug('Erro to save Exception' + insertException.getMessage());
        }
    }
}