Salesforce/main/default/main/default/objects/Categoria__c/Categoria__c.object-meta.xml
<CustomObject>
    <description>Categorías</description>
    <label>Categoria</label>
    <nameField>
        <label>Nombre de Categoría</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categorias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/objects/Opportunity/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <description>Identifica la marca para las Oportunidades del Circuito de Anexos. Se selecciona la lista de precios en función de este campo</description>
    <inlineHelpText>Identificar a marca de Oportunidades Circuito Anexos. Você seleciona a lista de preços com base neste campo</inlineHelpText>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BRMX</fullName>
            </value>
            <value>
                <fullName>DSEM</fullName>
            </value>
            <value>
                <fullName>NEOG</fullName>
            </value>
            <value>
                <fullName>DAGMA</fullName>
            </value>
            <value>
                <fullName>LICENÇAS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Opportunity/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <description>Safra o Campania agricola</description>
    <label>Safra</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>06/07</fullName>
            </value>
            <value>
                <fullName>07/08</fullName>
            </value>
            <value>
                <fullName>08/09</fullName>
            </value>
            <value>
                <fullName>09/10</fullName>
            </value>
            <value>
                <fullName>09/09</fullName>
            </value>
            <value>
                <fullName>10/10</fullName>
            </value>
            <value>
                <fullName>10/11</fullName>
            </value>
            <value>
                <fullName>11/11</fullName>
            </value>
            <value>
                <fullName>11/12</fullName>
            </value>
            <value>
                <fullName>12/12</fullName>
            </value>
            <value>
                <fullName>12/13</fullName>
            </value>
            <value>
                <fullName>13/14</fullName>
            </value>
            <value>
                <fullName>14/15</fullName>
            </value>
            <value>
                <fullName>15/16</fullName>
            </value>
            <value>
                <fullName>16/17</fullName>
            </value>
            <value>
                <fullName>17/18</fullName>
            </value>
            <value>
                <fullName>18/19</fullName>
            </value>
            <value>
                <fullName>19/20</fullName>
            </value>
            <value>
                <fullName>20/21</fullName>
            </value>
            <value>
                <fullName>21/22</fullName>
                <default>true</default>
                <label>21/22</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Opportunity/fields/TipoReg__c.field-meta.xml
<CustomField>
    <fullName>TipoReg__c</fullName>
    <formula>CASE($RecordType.Name, &quot;Comercial&quot;, &quot;Comercial&quot;, &quot;Produccion&quot;, &quot;Produccion&quot;,&quot;Pendiente&quot;,&quot;AU - Comercial&quot;,&quot;Autorizada&quot;,&quot;AU - SAP&quot;,&quot;Rebaja&quot;,&quot;Rebaja&quot;,$RecordType.Name)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>TipoReg</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/Opportunity/recordTypes/Autorizada.recordType-meta.xml
<RecordType>
    <fullName>Autorizada</fullName>
    <active>true</active>
    <businessProcess>Nota de Venta - Autorizada</businessProcess>
    <label>Autorizada</label>
</RecordType>

Salesforce/main/default/objects/Opportunity/recordTypes/Descarte.recordType-meta.xml
<RecordType>
    <fullName>Descarte</fullName>
    <active>true</active>
    <businessProcess>Circuito de Anexos</businessProcess>
    <label>Descarte</label>
</RecordType>

Salesforce/main/default/objects/OpportunityLineItem/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Categoria a ser licenciada</description>
    <inlineHelpText>Categoria a ser licenciada</inlineHelpText>
    <label>Categoria</label>
    <referenceTo>Categoria__c</referenceTo>
    <relationshipLabel>Producto de oportunidad</relationshipLabel>
    <relationshipName>Producto_de_oportunidad</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/OpportunityLineItem/fields/Categoria_a_Rebaixar__c.field-meta.xml
<CustomField>
    <fullName>Categoria_a_Rebaixar__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Categoria Plantada</label>
    <referenceTo>Categoria__c</referenceTo>
    <relationshipLabel>Producto de oportunidad (Categoria a Rebaixar)</relationshipLabel>
    <relationshipName>Producto_de_oportunidad1</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/OpportunityLineItem/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <formula>TEXT(Opportunity.Safra__c)</formula>
    <label>Safra</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/OpportunityLineItem/fields/Sem_Rebajada__c.field-meta.xml
<CustomField>
    <fullName>Sem_Rebajada__c</fullName>
    <label>Sem. Rebaixada (Sacas)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/main/default/objects/OpportunityLineItem/fields/UNIDADE__c.field-meta.xml
<CustomField>
    <fullName>UNIDADE__c</fullName>
    <formula>PricebookEntry.Product2.UNIDADE__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unidade</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/OpportunityLineItem/fields/Unidade_descarte__c.field-meta.xml
<CustomField>
    <fullName>Unidade_descarte__c</fullName>
    <label>Unidade descarte</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/OpportunityLineItem/fields/Variedad__c.field-meta.xml
<CustomField>
    <fullName>Variedad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Variedades que pueden incluirse en el contrato de multiplicacion</description>
    <inlineHelpText>Variedades que pueden incluirse en el contrato de multiplicacion</inlineHelpText>
    <label>Variedad</label>
    <referenceTo>Variedad__c</referenceTo>
    <relationshipLabel>Producto de oportunidad</relationshipLabel>
    <relationshipName>Producto_de_oportunidad</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Product2/fields/Categ__c.field-meta.xml
<CustomField>
    <fullName>Categ__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Categ</label>
    <referenceTo>Categoria__c</referenceTo>
    <relationshipLabel>Productos</relationshipLabel>
    <relationshipName>Productos</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Product2/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <label>Categoria</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BREEDER</fullName>
            </value>
            <value>
                <fullName>FUNDADORA</fullName>
            </value>
            <value>
                <fullName>Genetica</fullName>
            </value>
            <value>
                <fullName>Pre Basica</fullName>
            </value>
            <value>
                <fullName>BASICA</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>C1</fullName>
            </value>
            <value>
                <fullName>C2</fullName>
            </value>
            <value>
                <fullName>R</fullName>
            </value>
            <value>
                <fullName>S1</fullName>
            </value>
            <value>
                <fullName>S2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Product2/fields/UNIDADE__c.field-meta.xml
<CustomField>
    <fullName>UNIDADE__c</fullName>
    <label>UNIDADE</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/Product2/fields/Variedad__c.field-meta.xml
<CustomField>
    <fullName>Variedad__c</fullName>
    <label>Variedad</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Licenciada__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>BMX APOLO RR</fullName>
            </value>
            <value>
                <fullName>BMX IMPACTO RR</fullName>
            </value>
            <value>
                <fullName>BMX MAGNA RR</fullName>
            </value>
            <value>
                <fullName>BMX POTÊNCIA RR</fullName>
            </value>
            <value>
                <fullName>BMX TITAN RR</fullName>
            </value>
            <value>
                <fullName>BMX FORÇA RR</fullName>
            </value>
            <value>
                <fullName>BMX ENERGIA RR</fullName>
            </value>
            <value>
                <fullName>BMX ATIVA RR</fullName>
            </value>
            <value>
                <fullName>BMX TURBO RR</fullName>
            </value>
            <value>
                <fullName>BMX VELOZ RR</fullName>
            </value>
            <value>
                <fullName>BMX ALVO RR</fullName>
            </value>
            <value>
                <fullName>BMX TORNADO RR</fullName>
            </value>
            <value>
                <fullName>BMX CLASSE RR</fullName>
            </value>
            <value>
                <fullName>BMX DESAFIO RR</fullName>
            </value>
            <value>
                <fullName>BMX RAÇA RR</fullName>
            </value>
            <value>
                <fullName>BMX PROGRESSO RR</fullName>
            </value>
            <value>
                <fullName>BRASMAX ELITE IPRO</fullName>
            </value>
            <value>
                <fullName>BRASMAX FLECHA IPRO</fullName>
            </value>
            <value>
                <fullName>BRASMAX BONUS IPRO</fullName>
            </value>
            <value>
                <fullName>BRASMAX BRAVA</fullName>
            </value>
            <value>
                <fullName>BRASMAX CLASSE</fullName>
            </value>
            <value>
                <fullName>BRASMAX PRISMA</fullName>
            </value>
            <value>
                <fullName>BRASMAX OPUS IPRO</fullName>
            </value>
            <value>
                <fullName>BRASMAX LANÇA IPRO</fullName>
            </value>
            <value>
                <fullName>BRASMAX GARRA IPRO</fullName>
            </value>
            <value>
                <fullName>BRASMAX ÍCONE IPRO</fullName>
            </value>
            <value>
                <fullName>BRASMAX POWER IPRO</fullName>
            </value>
            <value>
                <fullName>68I69RSF IPRO</fullName>
            </value>
            <value>
                <fullName>75I76RSF IPRO</fullName>
            </value>
            <value>
                <fullName>81I84RSF IPRO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Product2/fields/Variedade__c.field-meta.xml
<CustomField>
    <fullName>Variedade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Variedade</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Variedad__c.Licenciada__c</field>
            <operation>equals</operation>
            <valueField>$Source.Licenciada__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Variedad__c</referenceTo>
    <relationshipLabel>Productos</relationshipLabel>
    <relationshipName>Productos</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Variedad__c/Variedad__c.object-meta.xml
<CustomObject>
    <description>Variedades, disponibles para incluir en los Contratos de Multiplicación</description>
    <label>Variedad</label>
    <nameField>
        <label>Nome Comercial</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Variedades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/Variedad__c/fields/Nombre_de_Registro__c.field-meta.xml
<CustomField>
    <fullName>Nombre_de_Registro__c</fullName>
    <externalId>true</externalId>
    <label>Nombre de Registro</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/classes/ManejadorProductos.cls
public virtual class ManejadorProductos  {

	public Map<Id, String> tmpvarietyNameById {get;set;}
	public Map<String, Set<String>> categoriasPorVariedad {get;set;}
	public Map<String,String> nombreRegistroVariedadPorId {get;set;}
	public Map<String,String> nombreVariedadPorId {get;set;}
	public Map<String, String> mapaRebajaCategorias {get;set;}

	public List<OpportunityLineItem> listaProductos {get;set;}

	public ManejadorProductos() {
		this.tmpvarietyNameById = new Map<Id,String>();
		this.categoriasPorVariedad = new Map<String, Set<String>>();
		this.nombreRegistroVariedadPorId = new Map<String, String>();
		this.nombreVariedadPorId = new Map<String, String>();
		this.mapaRebajaCategorias = new Map<String, String>();
	}


	/** METODOS VIRTUALES **/

	public virtual void setearMapas(){}


	public virtual void procesarProductosDescarte(Map<String, Map<String, Decimal>> mapaVolumenDisponible, List<OpportunityLineItem> productosDescarte) {
		for(OpportunityLineItem descarte : productosDescarte) {
        	String variedadId = String.valueOf(descarte.PricebookEntry.Product2.Variedade__c);
            String categoriaId = String.valueOf(descarte.Categoria__c);

			if(mapaVolumenDisponible.containsKey(variedadId) && mapaVolumenDisponible.get(variedadId).containsKey(categoriaId)) {
                Map<String, Decimal> tmpCategoriaAmountMap = mapaVolumenDisponible.get(variedadId);
                Decimal amountAvailable = tmpCategoriaAmountMap.get(categoriaId);
                Integer unidade = 0;
                if (descarte.Unidade_descarte__c == 'Quilograma') {
                    unidade = 1;
                }
                if (descarte.Unidade_descarte__c == 'Saca 25Kg') {
                    unidade = 25;
                }
                if (descarte.Unidade_descarte__c == 'Saca 40Kg') {
                    unidade = 40;
                }
                if (descarte.Unidade_descarte__c == 'Tonelada') {
                    unidade = 1000;
                }
                amountAvailable -=  descarte.Quantity * unidade;
                tmpCategoriaAmountMap.put(categoriaId, amountAvailable);
				
			}
		}
	}

	public virtual void procesarProductosAnexoIIRebaxa(Map<String, Map<String, Decimal>> mapaVolumenDisponible, List<OpportunityLineItem> productosAnexoIIRebaja) {
		for(OpportunityLineItem anexoRebaja : productosAnexoIIRebaja) {
        	String variedadRebId = String.valueOf(anexoRebaja.PricebookEntry.Product2.Variedade__c);
            String categoriaRebId = String.valueOf(anexoRebaja.Categoria_a_Rebaixar__c);
			String categoriaFinal = String.valueOf(anexoRebaja.Categoria__c);

			//Se hace la resta del Volumen para la Variedad + Categoria rebajada

			Map<String, Decimal> tmpCategoriaAmountMap = mapaVolumenDisponible.get(variedadRebId);
            Decimal amountAvailable = tmpCategoriaAmountMap.get(categoriaRebId);
			if(anexoRebaja.Sem_Rebajada__c != null) {
				amountAvailable -= anexoRebaja.Sem_Rebajada__c * 40;
            }
			tmpCategoriaAmountMap.put(categoriaRebId, amountAvailable);


			//Revisamos si existe la nueva Categoria (la que sale del rebajamiento). Si existe se suma la cantidad, sino se la agrega
			if (mapaVolumenDisponible.get(variedadRebId).containsKey(categoriaFinal)) {
                Map<String, Decimal> tmpNewCategoriaAmount = mapaVolumenDisponible.get(variedadRebId);
                String tmpNewCat = String.valueOf(anexoRebaja.Categoria__c);
                Decimal tmpNewAmount = tmpNewCategoriaAmount.get(tmpNewCat);
				if(anexoRebaja.Sem_Rebajada__c != null) {
					tmpNewAmount += anexoRebaja.Sem_Rebajada__c * 40;
				}
				tmpNewCategoriaAmount.put(tmpNewCat, tmpNewAmount);
			} else {
                Map<String, Decimal> tmpMapCategoriaAmount = mapaVolumenDisponible.get(variedadRebId);
                String tmpCategoria = String.valueOf(categoriaFinal);
				Decimal tmpAmount = 0;
				if(anexoRebaja.Sem_Rebajada__c != null) {
					  tmpAmount = anexoRebaja.Sem_Rebajada__c * 40;
				}
                tmpMapCategoriaAmount.put(tmpCategoria, tmpAmount);
			}
		}
	}


	public virtual void cargarProductos(String[] criterios, Id idCuenta, String safra, String marca) {
        
        
		List<OpportunityLineItem> productosBasica = this.obtenerProductos(criterios, idCuenta, safra, marca, new String[] {'Aprobada','AU - Autorizada'});
        
        System.debug(productosBasica);
        
		if(!productosBasica.isEmpty()) {
			for(OpportunityLineItem item : productosBasica) {
				this.listaProductos.add(item);
			}
		}
	}

	private List<OpportunityLineItem> obtenerProductos( String[] registros, Id idCuenta, String safra, String marca, String[] stages) {
        
        
        System.debug(idCuenta);
        System.debug(safra);
        System.debug(marca);
        System.debug(registros);
        
        String queryPlus = 'PricebookEntry.Product2.Variedade__c, PricebookEntry.Product2.Variedade__r.Name,' 
            +'PricebookEntry.Product2.Variedade__r.Nombre_de_Registro__c,PricebookEntry.Product2.UNIDADE__c,'
            +'PriceBookEntry.Product2.Categ__c, Categoria__r.Name, Opportunity.TipoReg__c, Categoria_a_Rebaixar__r.Name,'
            +'PriceBookEntry.PriceBook2Id, PricebookEntry.Product2.Variedad__c, PricebookEntry.Product2.Categ__r.Name ';

        return aSiteUtils.queryResults5(
            OpportunityLineItem.SObjectType, queryPlus,
            'Opportunity.AccountId = :v1', idCuenta, 
            'Opportunity.TipoReg__c in :v2', registros,
            'Opportunity.Safra__c = :v3', safra,
            'Opportunity.Marca__c = :v4', marca,
            'Opportunity.StageName = :v5', stages
        );
    }
}