Salesforce/main/default/main/default/objects/Categoria__c/Categoria__c.object-meta.xml
<CustomObject>
    <description>Categorías</description>
    <label>Categoria</label>
    <nameField>
        <label>Nombre de Categoría</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categorias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/Estado__c/Estado__c.object-meta.xml
<CustomObject>
    <label>Estado</label>
    <nameField>
        <label>Nome do Estado</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estados</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/objects/OpportunityLineItem/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Ha. Autorizados</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/objects/OpportunityLineItem/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Categoria a ser licenciada</description>
    <inlineHelpText>Categoria a ser licenciada</inlineHelpText>
    <label>Categoria</label>
    <referenceTo>Categoria__c</referenceTo>
    <relationshipLabel>Producto de oportunidad</relationshipLabel>
    <relationshipName>Producto_de_oportunidad</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/OpportunityLineItem/fields/Categoria_a_Rebaixar__c.field-meta.xml
<CustomField>
    <fullName>Categoria_a_Rebaixar__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Categoria Plantada</label>
    <referenceTo>Categoria__c</referenceTo>
    <relationshipLabel>Producto de oportunidad (Categoria a Rebaixar)</relationshipLabel>
    <relationshipName>Producto_de_oportunidad1</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/OpportunityLineItem/fields/Estado_de_Produccion__c.field-meta.xml
<CustomField>
    <fullName>Estado_de_Produccion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Estado de Produccion</label>
    <referenceTo>Estado__c</referenceTo>
    <relationshipLabel>Producto de oportunidad</relationshipLabel>
    <relationshipName>Producto_de_oportunidad</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/OpportunityLineItem/fields/Expec_Prod_Bruta__c.field-meta.xml
<CustomField>
    <fullName>Expec_Prod_Bruta__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Expec. Prod. Bruta(Sacos 40kg)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/objects/OpportunityLineItem/fields/Lote_Rebajado__c.field-meta.xml
<CustomField>
    <fullName>Lote_Rebajado__c</fullName>
    <label>Lote</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/OpportunityLineItem/fields/Qtde_Scs_40kg__c.field-meta.xml
<CustomField>
    <fullName>Qtde_Scs_40kg__c</fullName>
    <label>Qtde Scs (40kg)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/main/default/objects/OpportunityLineItem/fields/Semente_comercializada__c.field-meta.xml
<CustomField>
    <fullName>Semente_comercializada__c</fullName>
    <label>Sem. Comercializada (Sacas)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/main/default/objects/OpportunityLineItem/fields/UNIDADE__c.field-meta.xml
<CustomField>
    <fullName>UNIDADE__c</fullName>
    <formula>PricebookEntry.Product2.UNIDADE__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unidade</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/OpportunityLineItem/fields/Variedad__c.field-meta.xml
<CustomField>
    <fullName>Variedad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Variedades que pueden incluirse en el contrato de multiplicacion</description>
    <inlineHelpText>Variedades que pueden incluirse en el contrato de multiplicacion</inlineHelpText>
    <label>Variedad</label>
    <referenceTo>Variedad__c</referenceTo>
    <relationshipLabel>Producto de oportunidad</relationshipLabel>
    <relationshipName>Producto_de_oportunidad</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/OpportunityLineItem/fields/Variedade_Prod__c.field-meta.xml
<CustomField>
    <fullName>Variedade_Prod__c</fullName>
    <formula>PricebookEntry.Product2.Variedade__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Nome Comercial</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/Product2/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <label>Categoria</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BREEDER</fullName>
            </value>
            <value>
                <fullName>FUNDADORA</fullName>
            </value>
            <value>
                <fullName>Genetica</fullName>
            </value>
            <value>
                <fullName>Pre Basica</fullName>
            </value>
            <value>
                <fullName>BASICA</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>C1</fullName>
            </value>
            <value>
                <fullName>C2</fullName>
            </value>
            <value>
                <fullName>R</fullName>
            </value>
            <value>
                <fullName>S1</fullName>
            </value>
            <value>
                <fullName>S2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Product2/fields/UNIDADE__c.field-meta.xml
<CustomField>
    <fullName>UNIDADE__c</fullName>
    <label>UNIDADE</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/Product2/fields/Variedad__c.field-meta.xml
<CustomField>
    <fullName>Variedad__c</fullName>
    <label>Variedad</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Licenciada__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>BMX APOLO RR</fullName>
            </value>
            <value>
                <fullName>BMX IMPACTO RR</fullName>
            </value>
            <value>
                <fullName>BMX MAGNA RR</fullName>
            </value>
            <value>
                <fullName>BMX POTÊNCIA RR</fullName>
            </value>
            <value>
                <fullName>BMX TITAN RR</fullName>
            </value>
            <value>
                <fullName>BMX FORÇA RR</fullName>
            </value>
            <value>
                <fullName>BMX ENERGIA RR</fullName>
            </value>
            <value>
                <fullName>BMX ATIVA RR</fullName>
            </value>
            <value>
                <fullName>BMX TURBO RR</fullName>
            </value>
            <value>
                <fullName>BMX VELOZ RR</fullName>
            </value>
            <value>
                <fullName>BMX ALVO RR</fullName>
            </value>
            <value>
                <fullName>BMX TORNADO RR</fullName>
            </value>
            <value>
                <fullName>BMX CLASSE RR</fullName>
            </value>
            <value>
                <fullName>BMX DESAFIO RR</fullName>
            </value>
            <value>
                <fullName>BMX RAÇA RR</fullName>
            </value>
            <value>
                <fullName>BMX PROGRESSO RR</fullName>
            </value>
            <value>
                <fullName>BRASMAX ELITE IPRO</fullName>
            </value>
            <value>
                <fullName>BRASMAX FLECHA IPRO</fullName>
            </value>
            <value>
                <fullName>BRASMAX BONUS IPRO</fullName>
            </value>
            <value>
                <fullName>BRASMAX BRAVA</fullName>
            </value>
            <value>
                <fullName>BRASMAX CLASSE</fullName>
            </value>
            <value>
                <fullName>BRASMAX PRISMA</fullName>
            </value>
            <value>
                <fullName>BRASMAX OPUS IPRO</fullName>
            </value>
            <value>
                <fullName>BRASMAX LANÇA IPRO</fullName>
            </value>
            <value>
                <fullName>BRASMAX GARRA IPRO</fullName>
            </value>
            <value>
                <fullName>BRASMAX ÍCONE IPRO</fullName>
            </value>
            <value>
                <fullName>BRASMAX POWER IPRO</fullName>
            </value>
            <value>
                <fullName>68I69RSF IPRO</fullName>
            </value>
            <value>
                <fullName>75I76RSF IPRO</fullName>
            </value>
            <value>
                <fullName>81I84RSF IPRO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Product2/fields/Variedade__c.field-meta.xml
<CustomField>
    <fullName>Variedade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Variedade</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Variedad__c.Licenciada__c</field>
            <operation>equals</operation>
            <valueField>$Source.Licenciada__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Variedad__c</referenceTo>
    <relationshipLabel>Productos</relationshipLabel>
    <relationshipName>Productos</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Variedad__c/Variedad__c.object-meta.xml
<CustomObject>
    <description>Variedades, disponibles para incluir en los Contratos de Multiplicación</description>
    <label>Variedad</label>
    <nameField>
        <label>Nome Comercial</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Variedades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/Variedad__c/fields/Nombre_de_Registro__c.field-meta.xml
<CustomField>
    <fullName>Nombre_de_Registro__c</fullName>
    <externalId>true</externalId>
    <label>Nombre de Registro</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/classes/aAppendix.cls
public class aAppendix {
	
	public class myOppItem {
        public String id {get; set;}
        public String name {get; set; }
        public Decimal amount {get; set; }
        public String variedad {get; set; }
        public String variedad_nombre {get; set; }
        public String variedad_registro {get; set; }
        public String categoria {get; set; }
        public String categoria_nombre {get; set;}
        public String categoria_id {get; set; }
        public String categoria_a_rebajar {get; set; }
        public String categoria_a_rebajar_id {get; set; }
        public String area_autorizada {get; set; }
        public String area_plantada {get; set; }
        public String sem_bruta {get; set; }            
        public String sem_bruta_A2 {get; set; }
        public String sem_rebajada {get; set; }
		public Decimal sem_disponibles {get; set; }
        public String descarte {get; set; }        
        public String sem_beneficiada {get; set; }
        public String sem_aprobada {get; set; }
        public String sem_comer {get; set; }
        public String sacas_disponibles {get; set; }
		public Decimal sem_comerci {get; set; }
        public String unidade {get; set;}
        public String sem_uso_propio {get; set; }
        public String sem_comer_up_aIII {get; set; }
        public String epocaPlantio {get; set; }
        public String lote_rebajado {get; set; }
        public String estado_comer_id {get; set; }
		public String estado_comer {get; set; }
        public String error_msg {get; set;}
        public Integer indice {get; set; }
		public String error_lote {get;set;}
		public String registro {get;set;}
		public Decimal haAutorizados {get;set;}
		public String estadoProduccion_nombre {get;set;}
		public String estadoProduccion_id {get;set;}
		public String unidade_nombre {get;set;}
		public Integer unidadDescarte {get;set;}
		public String cnpj {get;set;}
    }

	public class oppWrapper {
		public String idCooperador {get;set;}
		public String estadoComercialzacion {get;set;}
		public String cnpj {get;set;}
		public String epocaPlantacion {get;set;}
		public String rechazo {get;set;}
		public String renasem {get;set;}
        public String sufixCNPJ {get;set;}
	}

	public static OpportunityLineItem armarLineItem(aAppendix.myOppItem item) {
		OpportunityLineItem producto = new OpportunityLineItem();
		producto.Variedad__c = item.variedad;
		producto.Categoria__c = item.categoria;
		producto.Area__c = item.haAutorizados;
		producto.Expec_Prod_Bruta__c = item.amount;
		producto.Qtde_Scs_40kg__c = item.amount;
		producto.Quantity = item.amount;
		producto.Estado_de_Produccion__c = item.estadoProduccion_id;
		producto.Area__c = item.haAutorizados;
		producto.Estado_de_Produccion__c = item.estadoProduccion_id;
		try {
			producto.Categoria_a_Rebaixar__c = item.categoria_a_rebajar_id;
		}catch(Exception e) {
			System.debug(e.getMessage());
		}		
		producto.UnitPrice = 1;
		return producto;
	}

	public static aAppendix.myOppItem armarWrapper(OpportunityLineItem item) {
		aAppendix.myOppItem customOli = new aAppendix.myOppItem();
		customOli.variedad = item.PricebookEntry.Product2.Variedade__c;
		customOli.variedad_nombre = item.Variedade_Prod__c;
		customOli.registro = item.PricebookEntry.Product2.Variedade__r.Nombre_de_Registro__c;
		customOli.categoria = item.Categoria__c;
		customOli.categoria_nombre = item.Categoria__r.Name;
		customOli.amount = item.Expec_Prod_Bruta__c;
		customOli.lote_rebajado = item.Lote_Rebajado__c;
		customOli.id = item.Id;
		customOli.haAutorizados = item.Area__c;
		customOli.estadoProduccion_nombre = item.Estado_de_Produccion__r.Name;
		customOli.estadoProduccion_id = item.Estado_de_Produccion__c;
		customOli.unidade = item.PricebookEntry.Product2.UNIDADE__c;
		customOli.categoria_a_rebajar = item.Categoria_a_Rebaixar__r.Name;
		customOli.categoria_a_rebajar_id = item.Categoria_a_Rebaixar__c;
		customOli.sem_comer = String.valueOf(item.Semente_comercializada__c);

		return customOli;
	}

}