Salesforce/main/default/main/default/objects/Categoria__c/Categoria__c.object-meta.xml
<CustomObject>
    <description>Categorías</description>
    <label>Categoria</label>
    <nameField>
        <label>Nombre de Categoría</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categorias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/objects/Negocio_por_Conta__c/Negocio_por_Conta__c.object-meta.xml
<CustomObject>
    <label>Negocio por Conta</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Negocios por Contas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/objects/Opportunity/fields/Activa__c.field-meta.xml
<CustomField>
    <fullName>Activa__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Activa</label>
    <type>Checkbox</type>
</CustomField>

Salesforce/main/default/main/default/objects/Opportunity/fields/Negocio_por_Conta__c.field-meta.xml
<CustomField>
    <fullName>Negocio_por_Conta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Negócio</label>
    <referenceTo>Negocio_por_Conta__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/Opportunity/fields/Regiao__c.field-meta.xml
<CustomField>
    <fullName>Regiao__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Região</label>
    <referenceTo>Regiao__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/OpportunityLineItem/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Categoria a ser licenciada</description>
    <inlineHelpText>Categoria a ser licenciada</inlineHelpText>
    <label>Categoria</label>
    <referenceTo>Categoria__c</referenceTo>
    <relationshipLabel>Producto de oportunidad</relationshipLabel>
    <relationshipName>Producto_de_oportunidad</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/OpportunityLineItem/fields/Embalagem__c.field-meta.xml
<CustomField>
    <fullName>Embalagem__c</fullName>
    <label>Embalagem</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Embalagems</valueSetName>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/OpportunityLineItem/fields/Quantidade__c.field-meta.xml
<CustomField>
    <fullName>Quantidade__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Quantidade</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/main/default/objects/OpportunityLineItem/fields/Quantidade_de_sementes__c.field-meta.xml
<CustomField>
    <fullName>Quantidade_de_sementes__c</fullName>
    <label>Quantidade de sementes</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/main/default/objects/OpportunityLineItem/fields/Tratamento__c.field-meta.xml
<CustomField>
    <fullName>Tratamento__c</fullName>
    <label>Tratamento</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Embalagem__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Tratamentos</valueSetName>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/OpportunityLineItem/fields/Variedad__c.field-meta.xml
<CustomField>
    <fullName>Variedad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Variedades que pueden incluirse en el contrato de multiplicacion</description>
    <inlineHelpText>Variedades que pueden incluirse en el contrato de multiplicacion</inlineHelpText>
    <label>Variedad</label>
    <referenceTo>Variedad__c</referenceTo>
    <relationshipLabel>Producto de oportunidad</relationshipLabel>
    <relationshipName>Producto_de_oportunidad</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Product2/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <label>Categoria</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BREEDER</fullName>
            </value>
            <value>
                <fullName>FUNDADORA</fullName>
            </value>
            <value>
                <fullName>Genetica</fullName>
            </value>
            <value>
                <fullName>Pre Basica</fullName>
            </value>
            <value>
                <fullName>BASICA</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>C1</fullName>
            </value>
            <value>
                <fullName>C2</fullName>
            </value>
            <value>
                <fullName>R</fullName>
            </value>
            <value>
                <fullName>S1</fullName>
            </value>
            <value>
                <fullName>S2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Product2/fields/Variedad__c.field-meta.xml
<CustomField>
    <fullName>Variedad__c</fullName>
    <label>Variedad</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Licenciada__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>BMX APOLO RR</fullName>
            </value>
            <value>
                <fullName>BMX IMPACTO RR</fullName>
            </value>
            <value>
                <fullName>BMX MAGNA RR</fullName>
            </value>
            <value>
                <fullName>BMX POTÊNCIA RR</fullName>
            </value>
            <value>
                <fullName>BMX TITAN RR</fullName>
            </value>
            <value>
                <fullName>BMX FORÇA RR</fullName>
            </value>
            <value>
                <fullName>BMX ENERGIA RR</fullName>
            </value>
            <value>
                <fullName>BMX ATIVA RR</fullName>
            </value>
            <value>
                <fullName>BMX TURBO RR</fullName>
            </value>
            <value>
                <fullName>BMX VELOZ RR</fullName>
            </value>
            <value>
                <fullName>BMX ALVO RR</fullName>
            </value>
            <value>
                <fullName>BMX TORNADO RR</fullName>
            </value>
            <value>
                <fullName>BMX CLASSE RR</fullName>
            </value>
            <value>
                <fullName>BMX DESAFIO RR</fullName>
            </value>
            <value>
                <fullName>BMX RAÇA RR</fullName>
            </value>
            <value>
                <fullName>BMX PROGRESSO RR</fullName>
            </value>
            <value>
                <fullName>BRASMAX ELITE IPRO</fullName>
            </value>
            <value>
                <fullName>BRASMAX FLECHA IPRO</fullName>
            </value>
            <value>
                <fullName>BRASMAX BONUS IPRO</fullName>
            </value>
            <value>
                <fullName>BRASMAX BRAVA</fullName>
            </value>
            <value>
                <fullName>BRASMAX CLASSE</fullName>
            </value>
            <value>
                <fullName>BRASMAX PRISMA</fullName>
            </value>
            <value>
                <fullName>BRASMAX OPUS IPRO</fullName>
            </value>
            <value>
                <fullName>BRASMAX LANÇA IPRO</fullName>
            </value>
            <value>
                <fullName>BRASMAX GARRA IPRO</fullName>
            </value>
            <value>
                <fullName>BRASMAX ÍCONE IPRO</fullName>
            </value>
            <value>
                <fullName>BRASMAX POWER IPRO</fullName>
            </value>
            <value>
                <fullName>68I69RSF IPRO</fullName>
            </value>
            <value>
                <fullName>75I76RSF IPRO</fullName>
            </value>
            <value>
                <fullName>81I84RSF IPRO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Produto_de_Requisicao__c/Produto_de_Requisicao__c.object-meta.xml
<CustomObject>
    <label>Produto de Requisição</label>
    <nameField>
        <label>Nombre de Produto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Produtos de Requisição</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/Produto_de_Requisicao__c/fields/Embalagem__c.field-meta.xml
<CustomField>
    <fullName>Embalagem__c</fullName>
    <label>Embalagem</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Saca 60 Mil Sementes</fullName>
            </value>
            <value>
                <fullName>Bag 5 Milhões Sementes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Produto_de_Requisicao__c/fields/Quantidade_de_Sementes__c.field-meta.xml
<CustomField>
    <fullName>Quantidade_de_Sementes__c</fullName>
    <label>Quantidade de Sementes</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/main/default/objects/Produto_de_Requisicao__c/fields/Requisicao_de_compra__c.field-meta.xml
<CustomField>
    <fullName>Requisicao_de_compra__c</fullName>
    <label>Requisição de compra</label>
    <referenceTo>Requisicao_de_compra__c</referenceTo>
    <relationshipLabel>Produtos de Requisição</relationshipLabel>
    <relationshipName>Produtos_de_Requisicao</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Salesforce/main/default/objects/Produto_de_Requisicao__c/fields/Tratamento__c.field-meta.xml
<CustomField>
    <fullName>Tratamento__c</fullName>
    <label>Tratamento</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Embalagem__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tratamento A</fullName>
            </value>
            <value>
                <fullName>Tratamento B</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Produto_de_Requisicao__c/fields/Variedad__c.field-meta.xml
<CustomField>
    <fullName>Variedad__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Variedad</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1 AND 2</booleanFilter>
        <filterItems>
            <field>Variedad__c.Disponivel_para_venda_basica__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Variedad__c.Cultura__c</field>
            <operation>equals</operation>
            <value>MILHO</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Variedad__c</referenceTo>
    <relationshipLabel>Produtos de Requisição</relationshipLabel>
    <relationshipName>Produtos_de_Requisicao</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Regiao__c/Regiao__c.object-meta.xml
<CustomObject>
    <label>Región</label>
    <nameField>
        <label>Nome da Região</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regiones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/objects/Requisicao_de_compra__c/Requisicao_de_compra__c.object-meta.xml
<CustomObject>
    <label>Estimativas</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Número de requisito</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Estimativas</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/Requisicao_de_compra__c/fields/Regiao__c.field-meta.xml
<CustomField>
    <fullName>Regiao__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Região</label>
    <referenceTo>Regiao__c</referenceTo>
    <relationshipName>Requisiaos_de_compra</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/Requisicao_de_compra__c/fields/Requisicao_de_compra__c.field-meta.xml
<CustomField>
    <fullName>Requisicao_de_compra__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Número da Estimativa Subsequente</label>
    <referenceTo>Requisicao_de_compra__c</referenceTo>
    <relationshipName>Requisitos_de_compra</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Variedad__c/Variedad__c.object-meta.xml
<CustomObject>
    <description>Variedades, disponibles para incluir en los Contratos de Multiplicación</description>
    <label>Variedad</label>
    <nameField>
        <label>Nome Comercial</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Variedades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/globalValueSets/Embalagems.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Saca 60 Mil Sementes</fullName>
    </customValue>
    <customValue>
        <fullName>Bag 5 Milhões Sementes</fullName>
    </customValue>
    <description>Contiene los diferentes tipos de embalaje que maneja GDM al momento de crear productos de estimativas o productos de Opportunidad (OpportunityLineItems)</description>
    <masterLabel>Embalagems</masterLabel>
</GlobalValueSet>

Salesforce/main/default/globalValueSets/Tratamentos.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Tratamento A</fullName>
    </customValue>
    <customValue>
        <fullName>Tratamento B</fullName>
    </customValue>
    <description>Contiene los diferentes tipos de tratamentos que maneja GDM al momento de crear productos de estimativas o productos de Opportunidad (OpportunityLineItems) estos valores son dependientes del emblagem previamente seleccionado</description>
    <masterLabel>Tratamentos</masterLabel>
</GlobalValueSet>

Salesforce/main/default/main/default/classes/OpportunityHelperTest.cls
/**
* @name OpportunityHelperTest
* @author Jhonny Peroza
* updated 02-12-2021
*/
@isTest 
public class OpportunityHelperTest {

    @isTest 
    public static void testVerifyOpportunity(){

        List<Regiao__c> regionsList = TestDataFactoryMilho.createRegions(1);
        List<Account> accountsList = TestDataFactoryMilho.createAccounts(regionsList);
        List<Negocio_por_Conta__c> businessList = TestDataFactoryMilho.createBusiness(accountsList);
        List<Requisicao_de_compra__c> requisicaoList = TestDataFactoryMilho.createRequisitions(businessList);
        List<Variedad__c> varietyList = TestDataFactoryMilho.createVariety(1);
        List<Produto_de_Requisicao__c> productRequisitionList = TestDataFactoryMilho.createRequisitionsProducts(requisicaoList, varietyList);
        List<Opportunity> opportunitiesList = TestDataFactoryMilho.createOpportunities(accountsList, 1);

        Test.startTest();
        OpportunityHelper.verifyOpportunity(opportunitiesList);
        Test.stopTest();

    }

    @isTest 
    public static void testOpportunityAndItems(){

        List<Regiao__c> regionsList = TestDataFactoryMilho.createRegions(1);
        List<Account> accountsList = TestDataFactoryMilho.createAccounts(regionsList);
        List<Negocio_por_Conta__c> businessList = TestDataFactoryMilho.createBusiness(accountsList);
        List<Requisicao_de_compra__c> requisicaoList = TestDataFactoryMilho.createRequisitionsAprovada(businessList);
        List<Categoria__c> categoryList = TestDataFactoryMilho.createCategory(1);
        List<Variedad__c> varietyList = TestDataFactoryMilho.createVariety(1);
        List<Product2> productList = TestDataFactoryMilho.createProduct(1, categoryList, varietyList);
        List<PriceBookEntry> priceBookList = TestDataFactoryMilho.createPriceBookEntry(1, productList);
        List<Produto_de_Requisicao__c> productRequisitionList = TestDataFactoryMilho.createRequisitionsProducts(requisicaoList, varietyList);
        List<Opportunity> opportunitiesList = TestDataFactoryMilho.createOpportunitiesPBComercial(1, accountsList, requisicaoList);
        List<OpportunityLineItem> opportunityLineItemList = TestDataFactoryMilho.createOpportunityLineItems(opportunitiesList, productList, productRequisitionList);

        Test.startTest();
        OpportunityHelper.verifyOpportunity(opportunitiesList);

        List<Opportunity> opportunityRows = [SELECT Id, Name
                                                FROM Opportunity];

        List<OpportunityLineItem> opportunityLineItemsRows = [SELECT Id, Quantidade_de_sementes__c
                                                                FROM OpportunityLineItem];

        Test.stopTest();

        System.assert(opportunityRows.size() > 0);
        System.assert(opportunityRows[0].Name != null);
        System.assert(opportunityLineItemsRows.size() > 0);

    }

    @isTest
    public static void testDeactivateOpportunity() {

        String result;
        Id idOpp;

        List<Regiao__c> regionsList = TestDataFactoryMilho.createRegions(1);
        List<Account> accountsList = TestDataFactoryMilho.createAccounts(regionsList);
        List<Negocio_por_Conta__c> businessList = TestDataFactoryMilho.createBusiness(accountsList);
        List<Requisicao_de_compra__c> requisicaoList = TestDataFactoryMilho.createRequisitionsAprovada(businessList);
        List<Categoria__c> categoryList = TestDataFactoryMilho.createCategory(1);
        List<Variedad__c> varietyList = TestDataFactoryMilho.createVariety(1);
        List<Product2> productList = TestDataFactoryMilho.createProduct(1, categoryList, varietyList);
        List<PriceBookEntry> priceBookList = TestDataFactoryMilho.createPriceBookEntry(1, productList);
        List<Produto_de_Requisicao__c> productRequisitionList = TestDataFactoryMilho.createRequisitionsProducts(requisicaoList, varietyList);
        List<Opportunity> opportunitiesList = TestDataFactoryMilho.createOpportunitiesPBComercial(1, accountsList, requisicaoList);
        List<OpportunityLineItem> opportunityLineItemList = TestDataFactoryMilho.createOpportunityLineItems(opportunitiesList, productList, productRequisitionList);

        idOpp = Id.valueOf(opportunitiesList[0].Id);

        Test.startTest();
        result = OpportunityHelper.deactivateOpportunity(idOpp);
        

        List<Opportunity> opportunityRows = [SELECT Id, Activa__c
                                                FROM Opportunity];

        Test.stopTest();
        System.assert(result != null);
        System.assert(opportunityRows[0].Activa__c == false);

    }

    @isTest
    public static void testSelectOpportunityLineItems() {

        Id idOpp;
        List<String> fields = new List <String> {'Variedad__c','Variedad__r.Name','Embalagem__c','Tratamento__c','Quantidade__c'}; 
        List<OpportunityLineItem> result;

        List<Regiao__c> regionsList = TestDataFactoryMilho.createRegions(1);
        List<Account> accountsList = TestDataFactoryMilho.createAccounts(regionsList);
        List<Negocio_por_Conta__c> businessList = TestDataFactoryMilho.createBusiness(accountsList);
        List<Requisicao_de_compra__c> requisicaoList = TestDataFactoryMilho.createRequisitionsAprovada(businessList);
        List<Categoria__c> categoryList = TestDataFactoryMilho.createCategory(1);
        List<Variedad__c> varietyList = TestDataFactoryMilho.createVariety(1);
        List<Product2> productList = TestDataFactoryMilho.createProduct(1, categoryList, varietyList);
        List<PriceBookEntry> priceBookList = TestDataFactoryMilho.createPriceBookEntry(1, productList);
        List<Produto_de_Requisicao__c> productRequisitionList = TestDataFactoryMilho.createRequisitionsProducts(requisicaoList, varietyList);
        List<Opportunity> opportunitiesList = TestDataFactoryMilho.createOpportunitiesPBComercial(1, accountsList, requisicaoList);
        List<OpportunityLineItem> opportunityLineItemList = TestDataFactoryMilho.createOpportunityLineItems(opportunitiesList, productList, productRequisitionList);

        idOpp = Id.valueOf(opportunitiesList[0].Id);

        Test.startTest();
        result = OpportunityHelper.selectOpportunityLineItems(idOpp, fields);
        Test.stopTest();

        System.assert(result != null);

    }

    @isTest
    public static void testVerifyOpportunityLineItemsDelete() {

        List<OpportunityLineItem> listUpsert = new List<OpportunityLineItem>();
        List<OpportunityLineItem> listDelete = new List<OpportunityLineItem>();

        List<Regiao__c> regionsList = TestDataFactoryMilho.createRegions(1);
        List<Account> accountsList = TestDataFactoryMilho.createAccounts(regionsList);
        List<Negocio_por_Conta__c> businessList = TestDataFactoryMilho.createBusiness(accountsList);
        List<Requisicao_de_compra__c> requisicaoList = TestDataFactoryMilho.createRequisitionsAprovada(businessList);
        List<Categoria__c> categoryList = TestDataFactoryMilho.createCategory(1);
        List<Variedad__c> varietyList = TestDataFactoryMilho.createVariety(1);
        List<Product2> productList = TestDataFactoryMilho.createProduct(1, categoryList, varietyList);
        List<PriceBookEntry> priceBookList = TestDataFactoryMilho.createPriceBookEntry(1, productList);
        List<Produto_de_Requisicao__c> productRequisitionList = TestDataFactoryMilho.createRequisitionsProducts(requisicaoList, varietyList);
        List<Opportunity> opportunitiesList = TestDataFactoryMilho.createOpportunitiesPBComercial(1, accountsList, requisicaoList);
        List<OpportunityLineItem> opportunityLineItemList = TestDataFactoryMilho.createOpportunityLineItems(opportunitiesList, productList, productRequisitionList);

        listDelete = opportunityLineItemList;

        Test.startTest();
        OpportunityHelper.verifyOpportunityLineItems(listUpsert, listDelete);
        Test.stopTest();

    }

    @isTest
    public static void testVerifyOpportunityLineItemsUpsert() {

        List<OpportunityLineItem> listUpsert = new List<OpportunityLineItem>();
        List<OpportunityLineItem> listDelete = new List<OpportunityLineItem>();

        List<Regiao__c> regionsList = TestDataFactoryMilho.createRegions(1);
        List<Account> accountsList = TestDataFactoryMilho.createAccounts(regionsList);
        List<Negocio_por_Conta__c> businessList = TestDataFactoryMilho.createBusiness(accountsList);
        List<Requisicao_de_compra__c> requisicaoList = TestDataFactoryMilho.createRequisitionsAprovada(businessList);
        List<Categoria__c> categoryList = TestDataFactoryMilho.createCategory(1);
        List<Variedad__c> varietyList = TestDataFactoryMilho.createVariety(1);
        List<Product2> productList = TestDataFactoryMilho.createProduct(1, categoryList, varietyList);
        List<PriceBookEntry> priceBookList = TestDataFactoryMilho.createPriceBookEntry(1, productList);
        List<Produto_de_Requisicao__c> productRequisitionList = TestDataFactoryMilho.createRequisitionsProducts(requisicaoList, varietyList);
        List<Opportunity> opportunitiesList = TestDataFactoryMilho.createOpportunitiesPBComercial(1, accountsList, requisicaoList);
        List<OpportunityLineItem> opportunityLineItemList = TestDataFactoryMilho.createOpportunityLineItems(opportunitiesList, productList, productRequisitionList);

        listUpsert = opportunityLineItemList;

        Test.startTest();
        OpportunityHelper.verifyOpportunityLineItems(listUpsert, listDelete);
        Test.stopTest();

    }

}