Salesforce/main/default/main/default/objects/Categoria__c/Categoria__c.object-meta.xml
<CustomObject>
    <description>Categorías</description>
    <label>Categoria</label>
    <nameField>
        <label>Nombre de Categoría</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categorias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/objects/Opportunity/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <description>Identifica la marca para las Oportunidades del Circuito de Anexos. Se selecciona la lista de precios en función de este campo</description>
    <inlineHelpText>Identificar a marca de Oportunidades Circuito Anexos. Você seleciona a lista de preços com base neste campo</inlineHelpText>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BRMX</fullName>
            </value>
            <value>
                <fullName>DSEM</fullName>
            </value>
            <value>
                <fullName>NEOG</fullName>
            </value>
            <value>
                <fullName>DAGMA</fullName>
            </value>
            <value>
                <fullName>LICENÇAS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Opportunity/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <description>Safra o Campania agricola</description>
    <label>Safra</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>06/07</fullName>
            </value>
            <value>
                <fullName>07/08</fullName>
            </value>
            <value>
                <fullName>08/09</fullName>
            </value>
            <value>
                <fullName>09/10</fullName>
            </value>
            <value>
                <fullName>09/09</fullName>
            </value>
            <value>
                <fullName>10/10</fullName>
            </value>
            <value>
                <fullName>10/11</fullName>
            </value>
            <value>
                <fullName>11/11</fullName>
            </value>
            <value>
                <fullName>11/12</fullName>
            </value>
            <value>
                <fullName>12/12</fullName>
            </value>
            <value>
                <fullName>12/13</fullName>
            </value>
            <value>
                <fullName>13/14</fullName>
            </value>
            <value>
                <fullName>14/15</fullName>
            </value>
            <value>
                <fullName>15/16</fullName>
            </value>
            <value>
                <fullName>16/17</fullName>
            </value>
            <value>
                <fullName>17/18</fullName>
            </value>
            <value>
                <fullName>18/19</fullName>
            </value>
            <value>
                <fullName>19/20</fullName>
            </value>
            <value>
                <fullName>20/21</fullName>
            </value>
            <value>
                <fullName>21/22</fullName>
                <default>true</default>
                <label>21/22</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Opportunity/recordTypes/Descarte.recordType-meta.xml
<RecordType>
    <fullName>Descarte</fullName>
    <active>true</active>
    <businessProcess>Circuito de Anexos</businessProcess>
    <label>Descarte</label>
</RecordType>

Salesforce/main/default/objects/OpportunityLineItem/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Categoria a ser licenciada</description>
    <inlineHelpText>Categoria a ser licenciada</inlineHelpText>
    <label>Categoria</label>
    <referenceTo>Categoria__c</referenceTo>
    <relationshipLabel>Producto de oportunidad</relationshipLabel>
    <relationshipName>Producto_de_oportunidad</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/OpportunityLineItem/fields/Descarte__c.field-meta.xml
<CustomField>
    <fullName>Descarte__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Descarte(Sacas)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/main/default/objects/OpportunityLineItem/fields/Quantidade__c.field-meta.xml
<CustomField>
    <fullName>Quantidade__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Quantidade</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/objects/OpportunityLineItem/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <formula>TEXT(Opportunity.Safra__c)</formula>
    <label>Safra</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/OpportunityLineItem/fields/Semente_aprovada__c.field-meta.xml
<CustomField>
    <fullName>Semente_aprovada__c</fullName>
    <label>Sem. Aprovada (Sacas)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/main/default/objects/OpportunityLineItem/fields/Semente_beneficiada__c.field-meta.xml
<CustomField>
    <fullName>Semente_beneficiada__c</fullName>
    <label>Sem. Beneficiada (Sacas)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/main/default/objects/OpportunityLineItem/fields/Semente_bruta__c.field-meta.xml
<CustomField>
    <fullName>Semente_bruta__c</fullName>
    <label>Sem. Bruta (Sacas)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/main/default/objects/OpportunityLineItem/fields/Semente_comercializada__c.field-meta.xml
<CustomField>
    <fullName>Semente_comercializada__c</fullName>
    <label>Sem. Comercializada (Sacas)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/main/default/objects/OpportunityLineItem/fields/Semente_uso_propio__c.field-meta.xml
<CustomField>
    <fullName>Semente_uso_propio__c</fullName>
    <label>Sem. Uso Próprio (Sacas)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/objects/OpportunityLineItem/fields/Unidade_descarte__c.field-meta.xml
<CustomField>
    <fullName>Unidade_descarte__c</fullName>
    <label>Unidade descarte</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/OpportunityLineItem/fields/Variedad_de_Produto__c.field-meta.xml
<CustomField>
    <fullName>Variedad_de_Produto__c</fullName>
    <formula>PricebookEntry.Product2.Variedade__r.Nombre_de_Registro__c</formula>
    <label>Registro Cultivar</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/OpportunityLineItem/fields/Variedade_Prod__c.field-meta.xml
<CustomField>
    <fullName>Variedade_Prod__c</fullName>
    <formula>PricebookEntry.Product2.Variedade__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Nome Comercial</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/Product2/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <label>Categoria</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BREEDER</fullName>
            </value>
            <value>
                <fullName>FUNDADORA</fullName>
            </value>
            <value>
                <fullName>Genetica</fullName>
            </value>
            <value>
                <fullName>Pre Basica</fullName>
            </value>
            <value>
                <fullName>BASICA</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>C1</fullName>
            </value>
            <value>
                <fullName>C2</fullName>
            </value>
            <value>
                <fullName>R</fullName>
            </value>
            <value>
                <fullName>S1</fullName>
            </value>
            <value>
                <fullName>S2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Product2/fields/Variedade__c.field-meta.xml
<CustomField>
    <fullName>Variedade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Variedade</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Variedad__c.Licenciada__c</field>
            <operation>equals</operation>
            <valueField>$Source.Licenciada__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Variedad__c</referenceTo>
    <relationshipLabel>Productos</relationshipLabel>
    <relationshipName>Productos</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/classes/ProductsA4API.cls
@RestResource(urlMapping='/ProductsA4API/*')
global with sharing class ProductsA4API {
 
    public class Response {
        public Boolean status;
        public String message;
        public List<aAppendix.myOppItem> productsA4 = new List<aAppendix.myOppItem>();
    }

    @HttpGet
    global static void getProductsAppendix4() {

        String accountId = RestContext.request.params.get('accountId');
        String safra = RestContext.request.params.get('safra');
        String marca = RestContext.request.params.get('marca');

        RestResponse response = RestContext.response;
        response.statusCode = 404;

        Response result = new Response();
        result.status = false;
        result.message = Label.Anexo_IV_Val_Existe_Anexo_III;
        
        try {
            List<OpportunityLineItem> tmpOppItems = aAppManager.getAnexosItemsToA4(accountId, safra, marca); 
            tmpOppItems = valAnexos4_A(tmpOppItems);
            tmpOppItems = getSacasDescarteValues(accountId, safra, marca, tmpOppItems);

            result.productsA4 = oppLineItemJSONConverter(tmpOppItems);
  
        } catch (Exception exc) {
            response.statusCode = 400;
            result.message = exc.getMessage();
        }
                
        if(result.productsA4 != null && !result.productsA4.isEmpty()) {
            result.status = true;
            result.message = Label.ProductsA4API_Success_Message;
            response.statusCode = 200;
        }

        response.responseBody = Blob.valueOf(JSON.serialize(result));
        response.headers.put('Content-Type', 'application/json');
        response.headers.put('Content-Length', RestContext.response.responseBody.size()+'');
    }

    public static List<aAppendix.myOppItem> oppLineItemJSONConverter(List<OpportunityLineItem> oppLineItems) {

        
        List<aAppendix.myOppItem> result = new List<aAppendix.myOppItem>();
        
        for(OpportunityLineItem oppLineItem : oppLineItems){
            
            aAppendix.myOppItem oli = new aAppendix.myOppItem();
            oli.variedad = oppLineItem.PricebookEntry.Product2.Variedade__c;
            oli.variedad_nombre = oppLineItem.Variedade_Prod__c;
            oli.variedad_registro = oppLineItem.Variedad_de_Produto__c;
            oli.categoria = oppLineItem.Categoria__r.Name;
            oli.categoria_id = oppLineItem.Categoria__c;

            if(oppLineItem.Semente_bruta__c != null) {
                
                oli.sem_bruta_A2 = String.valueOf(oppLineItem.Semente_bruta__c);
                oli.sem_bruta = String.valueOf(oppLineItem.Semente_bruta__c);
            } 

            if(oppLineItem.Semente_beneficiada__c != null) {

                oli.sem_beneficiada = String.valueOf(oppLineItem.Semente_beneficiada__c);                
            } 

            if(oppLineItem.Semente_aprovada__c != null) {
                oli.sem_aprobada = String.valueOf(oppLineItem.Semente_aprovada__c);
                oli.sem_disponibles = Decimal.valueOf(oli.sem_aprobada);
            }
            if(oppLineItem.Semente_comercializada__c != null) {
                oli.sem_comer = String.valueOf(oppLineItem.Semente_comercializada__c);
            } 
            if(oppLineItem.Semente_uso_propio__c != null) {
                oli.sem_uso_propio = String.valueOf(oppLineItem.Semente_uso_propio__c);
         }          
            if(oppLineItem.Descarte__c != null) {
                oli.descarte = String.valueOf(oppLineItem.Descarte__c);  
            } 
            if(oppLineItem.Quantidade__c != null) {
                oli.sem_comer_up_aIII = String.valueOf(oppLineItem.Quantidade__c);
            } 

            result.add(oli);
        }
        
        return result;
    }


    //Validacion A, anexos IV
    public static List<OpportunityLineItem> valAnexos4_A(List<OpportunityLineItem> items){
        try{
            Map<String, OpportunityLineItem> mapOppApp1 = new Map<String, OpportunityLineItem>();

            for (OpportunityLineItem s : items){

                if (!mapOppApp1.containsKey(String.valueOf(s.Categoria__c)+String.valueOf(s.PricebookEntry.Product2.Variedade__c))){
                    mapOppApp1.put(String.valueOf(s.Categoria__c)+String.valueOf(s.PricebookEntry.Product2.Variedade__c), s);

                } else{
 
                    OpportunityLineItem oli = mapOppApp1.get(String.valueOf(s.Categoria__c)+String.valueOf(s.PricebookEntry.Product2.Variedade__c));

                    if (oli != null){

                        if (s.Semente_comercializada__c == null)
                            s.Semente_comercializada__c = 0;
                        if (oli.Semente_comercializada__c == null)
                            oli.Semente_comercializada__c = 0;
                        oli.Semente_comercializada__c = oli.Semente_comercializada__c + s.Semente_comercializada__c;

                        if (s.Semente_uso_propio__c == null)
                            s.Semente_uso_propio__c = 0;
                        if (oli.Semente_uso_propio__c == null)
                            oli.Semente_uso_propio__c = 0;
                        oli.Semente_uso_propio__c = oli.Semente_uso_propio__c + s.Semente_uso_propio__c;
                    }
                }
            }

            for (OpportunityLineItem s : mapOppApp1.values()){
                if (s.Semente_aprovada__c == null)
                    s.Semente_aprovada__c = 0;
                if (s.Semente_comercializada__c == null)
                    s.Semente_comercializada__c = 0;
                if (s.Semente_uso_propio__c == null)
                    s.Semente_uso_propio__c = 0;

                s.Quantidade__c = s.Semente_comercializada__c + s.Semente_uso_propio__c;
            }

            return mapOppApp1.values();
        } catch (Exception e){
            return null;
        }
    }

    // Calcula el valor de "Descarte(Sacas)" (Descarte__c) para cada combinación de Variedad y Categoría
    public static List<OpportunityLineItem> getSacasDescarteValues(String accountId, String safra, String marca, List<OpportunityLineItem> oppLineItems) { 

        Map<String, Map<String, Double>> descarteByVariedadAndCategoria = getMapDescarteByVariedadAndCategoria(accountId, safra, marca);

        for(OpportunityLineItem oppLineItem : oppLineItems){
            String variedad = oppLineItem.PricebookEntry.Product2.Variedade__c;
            String categoria = oppLineItem.Categoria__c;
            if(descarteByVariedadAndCategoria.containsKey(variedad) 
                    && descarteByVariedadAndCategoria.get(variedad).containsKey(categoria)){
                oppLineItem.Descarte__c = descarteByVariedadAndCategoria.get(variedad).get(categoria);
            }
        }

        return oppLineItems;

    }

     // Obtiene el Mapa de Sacas Descarte segun Variedad y Categoria
     public static Map<String, Map<String, Double>> getMapDescarteByVariedadAndCategoria(String accountId, String safra, String marca) { 

        List<OpportunityLineItem> descarteProducts =    [SELECT Id, Variedade_Prod__c, Variedad_de_Produto__c, Categoria__c, Categoria__r.Name, 
                                                                PricebookEntry.Product2.Variedade__c, Quantity, Unidade_descarte__c
                                                        FROM OpportunityLineItem
                                                        WHERE Opportunity.RecordType.Name = 'Descarte'
                                                            AND Opportunity.AccountId = :accountId
                                                            AND Opportunity.Safra__c = :safra
                                                            AND Opportunity.Marca__c = :marca
                                                            AND Opportunity.StageName = 'Aprobada'];

        Map<String, Map<String, Double>> descarteByVariedadAndCategoria = new Map<String, Map<String, Double>>();
        
        for(OpportunityLineItem oppLineItem : descarteProducts) {
            String variedad = oppLineItem.PricebookEntry.Product2.Variedade__c;
            String categoria = oppLineItem.Categoria__c;
            Double sacasDescarte = 0;
            Decimal tempDecimalValue;
            if(oppLineItem.Quantity != null && oppLineItem.Unidade_descarte__c != ''){  
                Integer unidadDescarte = ProductsDescarteAPI.MAPNAMEBYUNIDAD.get(oppLineItem.Unidade_descarte__c);

                sacasDescarte = Double.valueOf((oppLineItem.Quantity * unidadDescarte) / 40);
                tempDecimalValue = Decimal.ValueOf(sacasDescarte);
                tempDecimalValue = tempDecimalValue.setScale(2);
                sacasDescarte = Double.ValueOf(tempDecimalValue);

            }
            Map<String, Double> sacasByCategoria = new Map<String, Double>();

            if(descarteByVariedadAndCategoria.containsKey(variedad)){
                if(descarteByVariedadAndCategoria.get(variedad).containsKey(categoria)){

                    Double sacas = descarteByVariedadAndCategoria.get(variedad).get(categoria) + sacasDescarte;
                    tempDecimalValue = Decimal.ValueOf(sacas);
                    tempDecimalValue = tempDecimalValue.setScale(2);
                    sacas = Double.ValueOf(tempDecimalValue);

                    descarteByVariedadAndCategoria.get(variedad).put(categoria, sacas);
                } else {
                    sacasByCategoria.put(categoria, sacasDescarte);
                    descarteByVariedadAndCategoria.get(variedad).put(categoria, sacasDescarte);
                }
            } else {
                sacasByCategoria.put(categoria, sacasDescarte);
                descarteByVariedadAndCategoria.put(variedad, sacasByCategoria);
            }
        }

        return descarteByVariedadAndCategoria;
    }
}