Salesforce/main/default/main/default/objects/Categoria__c/Categoria__c.object-meta.xml
<CustomObject>
    <description>Categorías</description>
    <label>Categoria</label>
    <nameField>
        <label>Nombre de Categoría</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categorias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/Product2/fields/Categ__c.field-meta.xml
<CustomField>
    <fullName>Categ__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Categ</label>
    <referenceTo>Categoria__c</referenceTo>
    <relationshipLabel>Productos</relationshipLabel>
    <relationshipName>Productos</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/Product2/fields/Variedade__c.field-meta.xml
<CustomField>
    <fullName>Variedade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Variedade</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Variedad__c.Licenciada__c</field>
            <operation>equals</operation>
            <valueField>$Source.Licenciada__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Variedad__c</referenceTo>
    <relationshipLabel>Productos</relationshipLabel>
    <relationshipName>Productos</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Variedad__c/Variedad__c.object-meta.xml
<CustomObject>
    <description>Variedades, disponibles para incluir en los Contratos de Multiplicación</description>
    <label>Variedad</label>
    <nameField>
        <label>Nome Comercial</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Variedades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/classes/CSVObject.cls
public class CSVObject  {

    @AuraEnabled
    public List<CSVHeader> headers {get; set;}

    @AuraEnabled
    public List<List<String>> lines {get; set;}

    @AuraEnabled
    public Integer line_count {get; set;}

    public CSVObject() {}

    public CSVObject(List<CSVHeader> headers, List<List<String>> lines) {
        this.headers = headers;
        this.lines = lines;
        this.line_count = lines.size();
        
        this.headers.add(new CSVHeader('Conta'));
        this.headers.add(new CSVHeader('Variedade'));
        
        Map<String,Account> accs = New Map<String,Account>();
        for(Account a : [Select Id, Name From Account])
            accs.put(a.Id, a);
            
        Map<String,PricebookEntry> pbes = New Map<String,PricebookEntry>();
        for(PricebookEntry p : [Select Id, Product2.Variedade__r.Name From PricebookEntry Where Pricebook2.Name = 'Lista Canal Multiplicadores' And Product2.Categ__r.Name = 'BASICA' And Product2.Family = 'Royalty x Basica'])
            pbes.put(p.Product2.Variedade__c, p);    
        
        for(List<String> s1 : this.lines){
            if (accs.containsKey(s1[0])){
                s1.add(accs.get(s1[0]).Name);
                }else{
                    s1.add('');
            }
            if (pbes.containsKey(s1[1])){
                s1.add(pbes.get(s1[1]).Product2.Variedade__r.Name);
                }else{
                    s1.add('');
            }
        }
        
    }

}