Salesforce/main/default/main/default/objects/Account/recordTypes/Cuenta.recordType-meta.xml
<RecordType>
    <fullName>Cuenta</fullName>
    <active>true</active>
    <label>Cuenta</label>
</RecordType>

Salesforce/main/default/main/default/objects/Opportunity/fields/Estado_Facturacion__c.field-meta.xml
<CustomField>
    <fullName>Estado_Facturacion__c</fullName>
    <label>Estado Facturacion</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>PE Contabilizar</fullName>
            </value>
            <value>
                <fullName>Contabilizada</fullName>
            </value>
            <value>
                <fullName>Impresa</fullName>
            </value>
            <value>
                <fullName>Anulada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Opportunity/fields/Numero_Legal__c.field-meta.xml
<CustomField>
    <fullName>Numero_Legal__c</fullName>
    <label>Numero Legal</label>
    <precision>15</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

Salesforce/main/default/main/default/objects/Opportunity/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <description>Safra o Campania agricola</description>
    <label>Safra</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>06/07</fullName>
            </value>
            <value>
                <fullName>07/08</fullName>
            </value>
            <value>
                <fullName>08/09</fullName>
            </value>
            <value>
                <fullName>09/10</fullName>
            </value>
            <value>
                <fullName>09/09</fullName>
            </value>
            <value>
                <fullName>10/10</fullName>
            </value>
            <value>
                <fullName>10/11</fullName>
            </value>
            <value>
                <fullName>11/11</fullName>
            </value>
            <value>
                <fullName>11/12</fullName>
            </value>
            <value>
                <fullName>12/12</fullName>
            </value>
            <value>
                <fullName>12/13</fullName>
            </value>
            <value>
                <fullName>13/14</fullName>
            </value>
            <value>
                <fullName>14/15</fullName>
            </value>
            <value>
                <fullName>15/16</fullName>
            </value>
            <value>
                <fullName>16/17</fullName>
            </value>
            <value>
                <fullName>17/18</fullName>
            </value>
            <value>
                <fullName>18/19</fullName>
            </value>
            <value>
                <fullName>19/20</fullName>
            </value>
            <value>
                <fullName>20/21</fullName>
            </value>
            <value>
                <fullName>21/22</fullName>
                <default>true</default>
                <label>21/22</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Opportunity/fields/Sucursal__c.field-meta.xml
<CustomField>
    <fullName>Sucursal__c</fullName>
    <label>Sucursal</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0094 Passo Fundo</fullName>
            </value>
            <value>
                <fullName>0095 Londrina</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Order/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <label>Safra</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Safra</valueSetName>
    </valueSet>
</CustomField>

Salesforce/main/default/globalValueSets/Safra.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>14/15</fullName>
    </customValue>
    <customValue>
        <fullName>15/16</fullName>
    </customValue>
    <customValue>
        <fullName>16/17</fullName>
    </customValue>
    <customValue>
        <fullName>17/18</fullName>
    </customValue>
    <customValue>
        <fullName>18/19</fullName>
    </customValue>
    <customValue>
        <fullName>19/20</fullName>
    </customValue>
    <customValue>
        <fullName>20/21</fullName>
    </customValue>
    <customValue>
        <fullName>21/22</fullName>
    </customValue>
    <customValue>
        <fullName>22/23</fullName>
    </customValue>
    <customValue>
        <fullName>23/24</fullName>
    </customValue>
    <customValue>
        <fullName>08/09</fullName>
        <isActive>false</isActive>
        <label>08/09</label>
    </customValue>
    <customValue>
        <fullName>07/08</fullName>
        <isActive>false</isActive>
        <label>07/08</label>
    </customValue>
    <customValue>
        <fullName>10/11</fullName>
        <isActive>false</isActive>
        <label>10/11</label>
    </customValue>
    <customValue>
        <fullName>11/12</fullName>
        <isActive>false</isActive>
        <label>11/12</label>
    </customValue>
    <customValue>
        <fullName>12/13</fullName>
        <isActive>false</isActive>
        <label>12/13</label>
    </customValue>
    <customValue>
        <fullName>13/14</fullName>
        <isActive>false</isActive>
        <label>13/14</label>
    </customValue>
    <customValue>
        <fullName>09/10</fullName>
        <isActive>false</isActive>
        <label>09/10</label>
    </customValue>
    <masterLabel>Safra</masterLabel>
</GlobalValueSet>

Salesforce/main/default/main/default/classes/Imprimir_Facturas_Controller_2.cls
Public class Imprimir_Facturas_Controller_2 {
   
   Public Opportunity opp = new Opportunity();
   Public Opportunity opp2 = new Opportunity();
   Public List<Opportunity> listaOpp = new List<Opportunity>();
   Public Account cuenta = new Account();
   Public String Mensaje;
   Public Opportunity Fact_Param = new Opportunity(); 
   Public String MiQuery='';
   Public Opportunity oppImprimir = new Opportunity();
   Public String ImprimirUrl;
   
   Public Imprimir_Facturas_Controller_2 () {
   
      ApexPages.Message msg = new ApexPages.Message(ApexPages.Severity.INFO, 'Aqui se muestra el Numero Legal de la Factura lista para Imprimir. Para ello haga click en el boton "Imprimir". Una vez Finalizado el Proceso y si la Factura se Imprimio Correctamente, haga click en "Siguiente" para pasar a la proxima Factura a Imprimir.');                             
      ApexPages.addMessage(msg); 
   
   }

   Public String getImprimirUrl(){
       return ImprimirUrl;
   }
   
   Public void setImprimirUrl(String arg){
       ImprimirUrl=arg;
   }
    
   Public Opportunity getoppImprimir() {
              
        if (listaOpp == null){
           return null;
        }   
        
        for (Opportunity o : listaOpp)
           if (o.Estado_Facturacion__c <> 'Impresa'){
              setoppImprimir(o);
              return o;
           }   
        
        return null;
   }
   
   Public void setoppImprimir(Opportunity o){
      oppImprimir = o;
   }
   
   Public Boolean getImprimirDisabled () {
   
      if (listaOpp.size() == 0)
         return true;
         
      for(Opportunity o : listaOpp)
         if (o.Estado_Facturacion__c!='Impresa')
            return false;   
         
      return true;   
   
   }
      
   Public Opportunity getOpp() {
       return opp;
   }    
   
   Public void setOpp(Opportunity i) {
       opp=i;
   }
   
   Public Opportunity getOpp2() {
       return opp2;
   }    
   
   Public void setOpp2(Opportunity i) {
       opp2=i;
   }
   
   Public Opportunity getFact_Param(){
      return Fact_Param;
   }

   Public Void setFact_Param(Opportunity arg){
       Fact_Param = arg;
   }

   Public Account getcuenta() {
       return cuenta;
   }    

   Public void setcuenta(Account i) {
       cuenta=i;
   }
   
   Public List<Opportunity> getlistaOpp() {
       return listaOpp;
   }
    
   Public void setlistaOpp(List<Opportunity> arg) {
       listaOpp=arg;
   }
   
   Public String getMensaje() {
      return Mensaje;      
   }

   Public void setMensaje(String arg) {
      Mensaje=arg;      
   }
       
   Public Void Buscar () {
   
        ApexPages.Message msg = new ApexPages.Message(ApexPages.Severity.INFO, 'Aqui se muestra el Numero Legal de la Factura lista para Imprimir. Para ello haga click en el boton "Imprimir". Una vez Finalizado el Proceso y si la Factura se Imprimio Correctamente, haga click en "Siguiente" para pasar a la proxima Factura a Imprimir.');                             
        ApexPages.addMessage(msg); 
    
        Mensaje='';
        
        if (listaOpp != null)
              listaOpp.clear();                                                               
                                               
        List<RecordType> rt=[SELECT Id FROM RecordType WHERE Name='Fc de Brasmax Contabilizada' AND SobjectType='Opportunity'];
        //List<Profile> prof=[SELECT Id, Name FROM Profile WHERE Name='Administrador del sistema'];
        List<Opportunity> result;
                        
        Integer cont = 0;
        
        String qry;

        qry = 'SELECT Id, Name, CloseDate, Estado_Facturacion__c, Account.Name, Account.Id, Safra__c, Numero_Legal__c, Sucursal__c FROM Opportunity';
        qry += ' WHERE RecordTypeId= \'' + rt[0].Id + '\'';
                                                                                   
        if (opp.Numero_Legal__c != null)
           qry += ' AND Numero_Legal__c >= ' + String.valueOf(opp.Numero_Legal__c);
           
        if (opp2.Numero_Legal__c != null)
           qry += ' AND Numero_Legal__c <= ' + String.valueOf(opp2.Numero_Legal__c);
                                                             
        if (opp.Sucursal__c != null)
            qry += ' AND Sucursal__c = \'' + String.valueOf(opp.Sucursal__c) + '\'';
           
        qry += ' AND (Estado_Facturacion__c= \'Contabilizada\' OR Estado_Facturacion__c= \'Impresa\')';
        
        qry += ' ORDER BY Numero_Legal__c';
        
        //qry += ' Limit 1000';
                
        MiQuery=qry;                                              
        result = Database.query(qry);
                                                                    
        if (result != null)
           for (Opportunity o:result) {
              listaOpp.add(o);           
            //  if (cont == 998 && Oportunidades.size() == 1000){
            //     ApexPages.Message msg = new ApexPages.Message(ApexPages.Severity.INFO, 'Se estan visualizando 999 registros. Hay mas registros para consultar.');                 
            //     ApexPages.addMessage(msg); 
            //     break;  
            //  }
              cont += 1;   
           }                                                                                              
    }
    
    Public void Imprimir(){
    
       if (this.oppImprimir.Sucursal__c=='0094 Passo Fundo')
          ImprimirUrl = '/apex/Imprimir_Facturas_HTML_Passo_Fundo';
          
       if (this.oppImprimir.Sucursal__c=='0095 Londrina')
          ImprimirUrl = '/apex/Imprimir_Facturas_HTML_Londrina';
       
       ImprimirUrl += '?id=' + this.oppImprimir.id;      
       getoppimprimir();
    }
    
    Public void Siguiente(){
    
       ApexPages.Message msg = new ApexPages.Message(ApexPages.Severity.INFO, 'Aqui se muestra el Numero Legal de la Factura lista para Imprimir. Para ello haga click en el boton "Imprimir". Una vez Finalizado el Proceso y si la Factura se Imprimio Correctamente, haga click en "Siguiente" para pasar a la proxima Factura a Imprimir.');                             
       ApexPages.addMessage(msg);
    
       this.oppImprimir.Estado_Facturacion__C='Impresa';
       
    
    }
    
    public static testMethod void test() {
    
       Imprimir_Facturas_Controller_2 ifc = new Imprimir_Facturas_Controller_2(); 
       Opportunity o = new Opportunity();
       Account cuenta = new Account();
       List<Opportunity> lista = new List<Opportunity>();
       ifc.setopp(o);
       o = ifc.getopp();
       ifc.setopp2(o);
       o=ifc.getopp2();
       ifc.setFact_Param(o);
       o=ifc.getFact_Param();
       ifc.setCuenta(cuenta);
       cuenta=ifc.getCuenta();
       ifc.setlistaopp(lista);
       lista = ifc.getListaOpp();    
       ifc.setMensaje('a');
       String a = ifc.getMensaje();
       ifc.Buscar();
       ifc.getoppImprimir();
       ifc.Imprimir();
       ifc.Siguiente();
       ifc.setImprimirUrl(ifc.getImprimirUrl());
    }
        
            
  }