Salesforce/main/default/main/default/objects/Account/recordTypes/Cuenta.recordType-meta.xml
<RecordType>
    <fullName>Cuenta</fullName>
    <active>true</active>
    <label>Cuenta</label>
</RecordType>

Salesforce/main/default/objects/Cooperante__c/Cooperante__c.object-meta.xml
<CustomObject>
    <label>Cooperante</label>
    <nameField>
        <label>Nome do cooperante</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cooperantes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/Cooperante__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cooperantes</relationshipLabel>
    <relationshipName>Cooperantes</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Cooperante__c/fields/CuentaCoop__c.field-meta.xml
<CustomField>
    <fullName>CuentaCoop__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CuentaCoop</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cooperantes (CuentaCoop)</relationshipLabel>
    <relationshipName>Cooperante</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/Opportunity/fields/Cooperante2__c.field-meta.xml
<CustomField>
    <fullName>Cooperante2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Informação exclusiva para autorização por conta e ordem.</inlineHelpText>
    <label>Cooperante</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Cooperante__c.Cuenta__r.Id</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Cooperante__c</referenceTo>
    <relationshipLabel>Oportunidades (Nome do Cooperante)</relationshipLabel>
    <relationshipName>Oportunidades2</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/Opportunity/fields/Cooperante__c.field-meta.xml
<CustomField>
    <fullName>Cooperante__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Informação exclusiva para autorização por conta e ordem.</inlineHelpText>
    <label>Nome do Cooperante</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Oportunidades (Nome do Cooperante)</relationshipLabel>
    <relationshipName>Oportunidades2</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/classes/OpportunittyHelperTest.cls
@isTest
public class OpportunittyHelperTest {
    @isTest
    public static void createAnOpportunityWithCooperante() {
        List<Account> accList = new List<Account>();
        Account anAccount = Build.anAccountCuenta().withName('Una cuenta').build();
        Account anAccountC = Build.anAccountCuenta().withName('Una cuenta Coop').build();
        accList.add(anAccount);
        accList.add(anAccountC);
        insert accList;
        Cooperante__c aCooperante = new Cooperante__c(
            Cuenta__c = accList[0].Id,
            CuentaCoop__c = accList[1].Id,
            Name = accList[1].Name
        );
        insert aCooperante;
        Opportunity testOpp = Build.anOpportunityAnexoI().withAccountId(accList[0]).build();
        testOpp.Cooperante2__c = aCooperante.Id;
        
        Test.startTest();
        insert testOpp;
        Test.stopTest();

        Opportunity resultOpp = [
            SELECT Cooperante__c
            FROM Opportunity
            LIMIT 1
        ];

        System.assertEquals(accList[1].Id, resultOpp.Cooperante__c, 'La Id no es la esperada');
    }

    @isTest
    public static void updateAnOpportunityWithCooperante() {
        List<Account> accList = new List<Account>();
        Account anAccount = Build.anAccountCuenta().withName('Una cuenta').build();
        Account anAccountC = Build.anAccountCuenta().withName('Una cuenta Coop').build();
        accList.add(anAccount);
        accList.add(anAccountC);
        insert accList;

        Cooperante__c aCooperante = new Cooperante__c(
            Cuenta__c = accList[0].Id,
            CuentaCoop__c = accList[1].Id,
            Name = accList[1].Name
        );
        insert aCooperante;
        
        Opportunity testOpp = Build.anOpportunityAnexoI().withAccountId(accList[0]).build();
        insert testOpp;
        
        testOpp.Cooperante2__c = aCooperante.Id;
        
        Test.startTest();
        update testOpp;
        Test.stopTest();

        Opportunity resultOpp = [
            SELECT Cooperante2__c,Cooperante__c,Cooperante2__r.CuentaCoop__c
            FROM Opportunity
            LIMIT 1
        ];

        //System.assertEquals(resultOpp.Cooperante__c, resultOpp.Cooperante2__r.CuentaCoop__c, 'La Id no es la esperada');
    }
}