Salesforce/main/default/main/default/objects/Account/recordTypes/Cuenta.recordType-meta.xml
<RecordType>
    <fullName>Cuenta</fullName>
    <active>true</active>
    <label>Cuenta</label>
</RecordType>

Salesforce/main/default/objects/Configuracion_BMX__c/Configuracion_BMX__c.object-meta.xml
<CustomObject>
    <description>Indicador de Parametros.</description>
    <label>Configuracion_BMX</label>
    <nameField>
        <label>Configuracion Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuraciones_BMX</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/Evento_Royalty__c/Evento_Royalty__c.object-meta.xml
<CustomObject>
    <label>Evento Royalty</label>
    <nameField>
        <label>Nombre de Evento Royalty</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Eventos Royalty</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/Evento_Royalty__c/fields/Saldo_por_safra__c.field-meta.xml
<CustomField>
    <fullName>Saldo_por_safra__c</fullName>
    <label>Saldo por safra</label>
    <referenceTo>Saldo_por_safra__c</referenceTo>
    <relationshipLabel>Eventos Royalty</relationshipLabel>
    <relationshipName>Eventos_Royalty</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Salesforce/main/default/main/default/objects/Saldo_por_safra__c/Saldo_por_safra__c.object-meta.xml
<CustomObject>
    <label>Saldo por safra</label>
    <nameField>
        <label>Nombre de Saldo por safra</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Saldos por safra</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Salesforce/main/default/classes/CrearFacturaSapEventoRoyaltyCTrlTest.cls
@IsTest
public class CrearFacturaSapEventoRoyaltyCTrlTest {
    
    static Evento_Royalty__c eventoRoyalty; 
    
    static {
        Configuracion_BMX__c endpointConfig = Build.aConfiguracionBMX()
            .withName('Test')
            .withLinkSapQa('gdmdev.dyndns.org:8000')
            .build();
        insert endpointConfig;
        
        Account cuenta = Build.anAccount().build();
        insert cuenta;
        
        Saldo_por_safra__c saldoPorSafra = Build.aSaldoPorSafra()
            .withAccount(cuenta)
            .withSafra('19/20')
            .build();
        insert saldoPorSafra;
        
        eventoRoyalty = Build.anEventoRoyalty()
            .withCuenta(cuenta)
            .withSaldoPorSafra(saldoPorSafra)
            .withValor(1)
            .build();
        
        insert eventoRoyalty;
        
        Test.setMock(WebServiceMock.class, new CrearFacturaSoapMOCK.CrearFacturaSoapSuccessfullyMOCK());
    }
    
    
    @IsTest
    public static void constructorTest(){
        //Inicialización y carga de datos
        ApexPages.StandardController standarController = new ApexPages.StandardController(eventoRoyalty);
        //Test
        Test.startTest();
        CrearFacturaSapEventoRoyaltyCntroller controller = new CrearFacturaSapEventoRoyaltyCntroller(standarController);
        Test.stopTest();
        //ASSERTS
        System.assertEquals( eventoRoyalty.id , controller.idCurrentRecord );
    }
    
    @IsTest
    public static void enviarASapTestSuccessfully(){
        //Inicialización y carga de datos
        ApexPages.StandardController standarController = new ApexPages.StandardController(eventoRoyalty);
        CrearFacturaSapEventoRoyaltyCntroller controller = new CrearFacturaSapEventoRoyaltyCntroller(standarController);
        //Test
        Test.startTest();
        Pagereference page = controller.enviarASap();
        Test.stopTest();
        //ASSERTS
        System.debug('mensaje: '+ ApexPages.getMessages() );
        //System.assertEquals( true , ApexPages.hasMessages(ApexPages.SEVERITY.CONFIRM) );
    }
    
    @IsTest
    public static void dummyTest(){
        //Inicialización y carga de datos
        ApexPages.StandardController standarController = new ApexPages.StandardController(eventoRoyalty);
        CrearFacturaSapEventoRoyaltyCntroller controller = new CrearFacturaSapEventoRoyaltyCntroller(standarController);
        //Test
        Test.startTest();
        Pagereference page = controller.dummy();
        System.debug('page: '+page.getUrl() );
        Test.stopTest();
        //ASSERTS
        System.assertEquals( true, page.getRedirect() );
    }    
}