Salesforce/main/default/objects/Case/fields/Ciudad_del_Problema__c.field-meta.xml
<CustomField>
    <fullName>Ciudad_del_Problema__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cidade do Problema</label>
    <referenceTo>Cidade__c</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Case/fields/Data_do_problema__c.field-meta.xml
<CustomField>
    <fullName>Data_do_problema__c</fullName>
    <label>Data do problema</label>
    <type>Date</type>
</CustomField>

Salesforce/main/default/main/default/objects/Case/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <description>Este campo indica a que empresa corresponde el reclamo.</description>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BRMX</fullName>
            </value>
            <value>
                <fullName>DSEM</fullName>
            </value>
            <value>
                <fullName>NEOG</fullName>
            </value>
            <value>
                <fullName>DAGMA</fullName>
            </value>
            <value>
                <fullName>LICENÇAS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Case/recordTypes/Reclamo.recordType-meta.xml
<RecordType>
    <fullName>Reclamo</fullName>
    <active>true</active>
    <businessProcess>Reclamos</businessProcess>
    <label>Reclamo</label>
</RecordType>

Salesforce/main/default/main/default/objects/Cidade__c/Cidade__c.object-meta.xml
<CustomObject>
    <label>Ciudad</label>
    <nameField>
        <label>Nome da Cidade</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ciudades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/classes/testCaseTrigger.cls
@isTest
private class testCaseTrigger {

   static testMethod void InsertCaseVB() {
    	RecordType rt = [Select Id, Name From RecordType Where Name = 'Reclamo Venda Basica'];  
    	
        Case rec = new Case(Subject='JERE',RecordTypeId=rt.Id,Data_do_problema__c=System.Today(),Marca__c='BRMX',Reason='NOO',Status='PE');
        insert rec;
        System.assertNotEquals(rec.Id,null);
    }
    
    static testMethod void updateCase() {
        RecordType rt = [Select Id, Name From RecordType Where Name = 'Reclamo Venda Basica'];  
    	Cidade__c ciudad = new Cidade__c(Name='JERE'); insert ciudad;
    	
        Case rec = new Case(Subject='JERE',RecordTypeId=rt.Id,Data_do_problema__c=System.Today(),Marca__c='BRMX',Reason='NOO',Status='PE');
        insert rec;
        
        rec.Ciudad_del_Problema__c = ciudad.Id;
        update rec;
          
    }
}