Salesforce/main/default/objects/Opportunity/fields/Destinatario_de_Mercaderia__c.field-meta.xml
<CustomField>
    <fullName>Destinatario_de_Mercaderia__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Recebedor mercadoria</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND (2 OR 3)</booleanFilter>
        <errorMessage>Destinatario de Mercadorias no pertenece a la Cuenta de la Venda o no se encuentra en SAP</errorMessage>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.RecordType.Name</field>
            <operation>equals</operation>
            <value>Destinatario Bloqueado</value>
        </filterItems>
        <filterItems>
            <field>Contact.RecordType.Name</field>
            <operation>equals</operation>
            <value>Destinatario Desbloqueado</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Opportunity/fields/Origen__c.field-meta.xml
<CustomField>
    <fullName>Origen__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Es el Centro logístico desde el cual se despachan los productos</description>
    <label>Origem</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>O valor não existe ou não coincidem os critérios de filtro.</errorMessage>
        <filterItems>
            <field>Centro_Logistico__c.Licencias__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Centro_Logistico__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/Opportunity/fields/Sucursal__c.field-meta.xml
<CustomField>
    <fullName>Sucursal__c</fullName>
    <label>Sucursal</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0094 Passo Fundo</fullName>
            </value>
            <value>
                <fullName>0095 Londrina</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Opportunity/recordTypes/CVB_Pendiente.recordType-meta.xml
<RecordType>
    <fullName>CVB_Pendiente</fullName>
    <active>true</active>
    <businessProcess>Prevision Venta Basica</businessProcess>
    <description>Es la confirmación de la venta de básica antes de ser enviada a SAP como NV.</description>
    <label>CVB Pendiente</label>
</RecordType>

Salesforce/main/default/main/default/classes/OpportunityAutorizationController.cls
public without sharing class OpportunityAutorizationController {

    @AuraEnabled
    public static String sendAutorizationRequest(Opportunity opp) {
        RecordType recordTypeCVBPendiente = XappiaHelper.getRecordType('Opportunity', 'CVB_Pendiente');
        
        if (!opp.HasOpportunityLineItem) {
            AuraHandledException e = new AuraHandledException('Opportunity sem Produtos');
            e.setMessage('Opportunity sem Produtos');
            throw e;
        } else if (opp.StageName == 'AN - Anulada') {
            AuraHandledException e = new AuraHandledException('Venda da Basica Anulada');
            e.setMessage('Venda da Basica Anulada');
            throw e;
        } else if (opp.Sucursal__c == null && opp.Origen__c == null) {
            AuraHandledException e = new AuraHandledException('Falta sucursal');
            e.setMessage('Falta sucursal');
            throw e;
        } else if (opp.RecordTypeId == recordTypeCVBPendiente.Id && opp.Destinatario_de_Mercaderia__c == null) {
            AuraHandledException e = new AuraHandledException('Falta Destinatario');
            e.setMessage('Falta Destinatario');
            throw e;
        } else if (opp.RecordTypeId == recordTypeCVBPendiente.Id) {
            List<String> resultsValidatePasoVBSAP = Opp_Utils.validarPasoVBSAP(opp.Id);

            if (resultsValidatePasoVBSAP[1] != 'OK') {
                AuraHandledException e = new AuraHandledException(resultsValidatePasoVBSAP[0]);
                e.setMessage(resultsValidatePasoVBSAP[0]);
                throw e;
            }
        }
        
        return JSON.serialize(Opp_Sap_Alta.enviarSAP(opp.Id, opp.StageName, 200));
    }
}