Salesforce/main/default/objects/Opportunity/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <description>Identifica la marca para las Oportunidades del Circuito de Anexos. Se selecciona la lista de precios en función de este campo</description>
    <inlineHelpText>Identificar a marca de Oportunidades Circuito Anexos. Você seleciona a lista de preços com base neste campo</inlineHelpText>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BRMX</fullName>
            </value>
            <value>
                <fullName>DSEM</fullName>
            </value>
            <value>
                <fullName>NEOG</fullName>
            </value>
            <value>
                <fullName>DAGMA</fullName>
            </value>
            <value>
                <fullName>LICENÇAS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Opportunity/fields/tienePdf__c.field-meta.xml
<CustomField>
    <fullName>tienePdf__c</fullName>
    <defaultValue>false</defaultValue>
    <label>tienePdf</label>
    <type>Checkbox</type>
</CustomField>

Salesforce/main/default/classes/PdfParaDescarteTest.cls
@IsTest
public class PdfParaDescarteTest {
	@IsTest
    public static void printDescarteAutorizationTest(){
        //Inicialización y carga de datos
        Opportunity oportunidad = new Opportunity(
            Marca__c = 'algo',
            StageName = 'Edicion',
            CloseDate = System.today(),
            tienePdf__c = true,
            Name = 'Test'
        );
        insert oportunidad;
        //Test
        Test.startTest();
        PdfParaDescarte.printDescarteAutorization(oportunidad.id);
        Test.stopTest();
        //ASSERTS
        List<Attachment> documentos = [SELECT Id,Name FROM Attachment WHERE ParentId = : oportunidad.id];
        System.assertEquals( 1 , documentos.size());
        System.assertEquals( 'Test_algo_autorizacao_descarte.pdf' , documentos[0].name);
    }
}