Salesforce/main/default/objects/Account/fields/Ativo__c.field-meta.xml
<CustomField>
    <fullName>Ativo__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Ativo</label>
    <type>Checkbox</type>
</CustomField>

Salesforce/main/default/main/default/objects/Account/fields/Cliente_de__c.field-meta.xml
<CustomField>
    <fullName>Cliente_de__c</fullName>
    <label>Cliente de:</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BRASMAX</fullName>
                <default>true</default>
                <label>BRASMAX</label>
            </value>
            <value>
                <fullName>FPS</fullName>
            </value>
            <value>
                <fullName>ROOS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Account/fields/CNPJ_CPF__c.field-meta.xml
<CustomField>
    <fullName>CNPJ_CPF__c</fullName>
    <externalId>true</externalId>
    <label>CNPJ/CPF</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Salesforce/main/default/main/default/objects/Account/fields/Grupo_de_Cuentas__c.field-meta.xml
<CustomField>
    <fullName>Grupo_de_Cuentas__c</fullName>
    <label>Grupo de Cuentas</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CMEX</fullName>
            </value>
            <value>
                <fullName>CPFI</fullName>
            </value>
            <value>
                <fullName>CPJU</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Account/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Região</label>
    <referenceTo>Regiao__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Account/fields/Region_Comercial__c.field-meta.xml
<CustomField>
    <fullName>Region_Comercial__c</fullName>
    <formula>TEXT(Region__r.Region_Comercial__c)</formula>
    <label>Região Comercial</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/Account/fields/Safras__c.field-meta.xml
<CustomField>
    <fullName>Safras__c</fullName>
    <label>Safras</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Safra</valueSetName>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Account/recordTypes/Cuenta.recordType-meta.xml
<RecordType>
    <fullName>Cuenta</fullName>
    <active>true</active>
    <label>Cuenta</label>
</RecordType>

Salesforce/main/default/main/default/objects/Attachment_Content__c/Attachment_Content__c.object-meta.xml
<CustomObject>
    <label>Attachment Content</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attachments Contents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/objects/Attachment_Content__c/fields/CRM_Calendario_de_Eventos__c.field-meta.xml
<CustomField>
    <fullName>CRM_Calendario_de_Eventos__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CRM Evento</label>
    <referenceTo>CRM_Calendario_de_Eventos__c</referenceTo>
    <relationshipLabel>Attachments Contents</relationshipLabel>
    <relationshipName>Attachments_Contents</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Categoria__c/Categoria__c.object-meta.xml
<CustomObject>
    <description>Categorías</description>
    <label>Categoria</label>
    <nameField>
        <label>Nombre de Categoría</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categorias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/objects/Categoria__c/fields/Mostrar_en_portal__c.field-meta.xml
<CustomField>
    <fullName>Mostrar_en_portal__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Mostrar en portal</label>
    <type>Checkbox</type>
</CustomField>

Salesforce/main/default/objects/CRM_Calendario_de_Eventos__c/CRM_Calendario_de_Eventos__c.object-meta.xml
<CustomObject>
    <description>Registro de eventos programados pelo Multiplicador</description>
    <label>CRM Evento</label>
    <nameField>
        <label>Nome de CRM Evento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Eventos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/Product2/fields/Categ__c.field-meta.xml
<CustomField>
    <fullName>Categ__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Categ</label>
    <referenceTo>Categoria__c</referenceTo>
    <relationshipLabel>Productos</relationshipLabel>
    <relationshipName>Productos</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Product2/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <label>Categoria</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BREEDER</fullName>
            </value>
            <value>
                <fullName>FUNDADORA</fullName>
            </value>
            <value>
                <fullName>Genetica</fullName>
            </value>
            <value>
                <fullName>Pre Basica</fullName>
            </value>
            <value>
                <fullName>BASICA</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>C1</fullName>
            </value>
            <value>
                <fullName>C2</fullName>
            </value>
            <value>
                <fullName>R</fullName>
            </value>
            <value>
                <fullName>S1</fullName>
            </value>
            <value>
                <fullName>S2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Product2/fields/UNIDADE__c.field-meta.xml
<CustomField>
    <fullName>UNIDADE__c</fullName>
    <label>UNIDADE</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/Product2/fields/Variedad__c.field-meta.xml
<CustomField>
    <fullName>Variedad__c</fullName>
    <label>Variedad</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Licenciada__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>BMX APOLO RR</fullName>
            </value>
            <value>
                <fullName>BMX IMPACTO RR</fullName>
            </value>
            <value>
                <fullName>BMX MAGNA RR</fullName>
            </value>
            <value>
                <fullName>BMX POTÊNCIA RR</fullName>
            </value>
            <value>
                <fullName>BMX TITAN RR</fullName>
            </value>
            <value>
                <fullName>BMX FORÇA RR</fullName>
            </value>
            <value>
                <fullName>BMX ENERGIA RR</fullName>
            </value>
            <value>
                <fullName>BMX ATIVA RR</fullName>
            </value>
            <value>
                <fullName>BMX TURBO RR</fullName>
            </value>
            <value>
                <fullName>BMX VELOZ RR</fullName>
            </value>
            <value>
                <fullName>BMX ALVO RR</fullName>
            </value>
            <value>
                <fullName>BMX TORNADO RR</fullName>
            </value>
            <value>
                <fullName>BMX CLASSE RR</fullName>
            </value>
            <value>
                <fullName>BMX DESAFIO RR</fullName>
            </value>
            <value>
                <fullName>BMX RAÇA RR</fullName>
            </value>
            <value>
                <fullName>BMX PROGRESSO RR</fullName>
            </value>
            <value>
                <fullName>BRASMAX ELITE IPRO</fullName>
            </value>
            <value>
                <fullName>BRASMAX FLECHA IPRO</fullName>
            </value>
            <value>
                <fullName>BRASMAX BONUS IPRO</fullName>
            </value>
            <value>
                <fullName>BRASMAX BRAVA</fullName>
            </value>
            <value>
                <fullName>BRASMAX CLASSE</fullName>
            </value>
            <value>
                <fullName>BRASMAX PRISMA</fullName>
            </value>
            <value>
                <fullName>BRASMAX OPUS IPRO</fullName>
            </value>
            <value>
                <fullName>BRASMAX LANÇA IPRO</fullName>
            </value>
            <value>
                <fullName>BRASMAX GARRA IPRO</fullName>
            </value>
            <value>
                <fullName>BRASMAX ÍCONE IPRO</fullName>
            </value>
            <value>
                <fullName>BRASMAX POWER IPRO</fullName>
            </value>
            <value>
                <fullName>68I69RSF IPRO</fullName>
            </value>
            <value>
                <fullName>75I76RSF IPRO</fullName>
            </value>
            <value>
                <fullName>81I84RSF IPRO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Product2/fields/Variedade__c.field-meta.xml
<CustomField>
    <fullName>Variedade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Variedade</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Variedad__c.Licenciada__c</field>
            <operation>equals</operation>
            <valueField>$Source.Licenciada__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Variedad__c</referenceTo>
    <relationshipLabel>Productos</relationshipLabel>
    <relationshipName>Productos</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Regiao__c/Regiao__c.object-meta.xml
<CustomObject>
    <label>Región</label>
    <nameField>
        <label>Nome da Região</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regiones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/objects/Regiao__c/fields/Region_Comercial__c.field-meta.xml
<CustomField>
    <fullName>Region_Comercial__c</fullName>
    <label>Region Comercial</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>REGION 1</fullName>
            </value>
            <value>
                <fullName>REGION 2</fullName>
            </value>
            <value>
                <fullName>CERRADO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Variedad__c/Variedad__c.object-meta.xml
<CustomObject>
    <description>Variedades, disponibles para incluir en los Contratos de Multiplicación</description>
    <label>Variedad</label>
    <nameField>
        <label>Nome Comercial</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Variedades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/globalValueSets/Safra.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>14/15</fullName>
    </customValue>
    <customValue>
        <fullName>15/16</fullName>
    </customValue>
    <customValue>
        <fullName>16/17</fullName>
    </customValue>
    <customValue>
        <fullName>17/18</fullName>
    </customValue>
    <customValue>
        <fullName>18/19</fullName>
    </customValue>
    <customValue>
        <fullName>19/20</fullName>
    </customValue>
    <customValue>
        <fullName>20/21</fullName>
    </customValue>
    <customValue>
        <fullName>21/22</fullName>
    </customValue>
    <customValue>
        <fullName>22/23</fullName>
    </customValue>
    <customValue>
        <fullName>23/24</fullName>
    </customValue>
    <customValue>
        <fullName>08/09</fullName>
        <isActive>false</isActive>
        <label>08/09</label>
    </customValue>
    <customValue>
        <fullName>07/08</fullName>
        <isActive>false</isActive>
        <label>07/08</label>
    </customValue>
    <customValue>
        <fullName>10/11</fullName>
        <isActive>false</isActive>
        <label>10/11</label>
    </customValue>
    <customValue>
        <fullName>11/12</fullName>
        <isActive>false</isActive>
        <label>11/12</label>
    </customValue>
    <customValue>
        <fullName>12/13</fullName>
        <isActive>false</isActive>
        <label>12/13</label>
    </customValue>
    <customValue>
        <fullName>13/14</fullName>
        <isActive>false</isActive>
        <label>13/14</label>
    </customValue>
    <customValue>
        <fullName>09/10</fullName>
        <isActive>false</isActive>
        <label>09/10</label>
    </customValue>
    <masterLabel>Safra</masterLabel>
</GlobalValueSet>

Salesforce/main/default/classes/DeleteAttachmentAPITest.cls
@isTest
public class DeleteAttachmentAPITest {

    @TestSetup
    static void makeData(){
        

        Regiao__c testRegion = new Regiao__c(Name = 'REGION 1',
                                             Region_Comercial__c = 'REGION 1'
                                            );
        insert testRegion;
        
        List<Account> accList = new List<Account>();

        Id accountRecordType = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Cuenta').getRecordTypeId();

        Account testAccount = new Account(Name = 'Test Account',
                                          CNPJ_CPF__c = '123456789-11',
                                          Grupo_de_Cuentas__c = 'CMEX',
                                          RecordTypeId = accountRecordType,
                                          Ativo__c = true,
                                          Cliente_de__c = 'BRASMAX',
                                          Safras__c = '20/21',
                                          Region__c = testRegion.Id
                                          );

        accList.add(testAccount);
        insert accList;             

        Categoria__c testCategory = new Categoria__c(Name = 'BASICA', Mostrar_en_portal__c = true);
        insert testCategory;

        List<Variedad__c> variedadList = new List<Variedad__c>();       
        Variedad__c testVariedad = new Variedad__c (Name = 'Variedad Test', Ativa__c = true);
        variedadList.add(testVariedad);
        insert variedadList;

        List<Product2> productList = new List<Product2>();
        Product2 testProduct =  new Product2(Name = 'Product 1 Test', 
                                             IsActive = true,
                                             Categ__c = testCategory.Id,
                                             Family = 'Royalty x Basica',
                                             Variedade__c = variedadList[0].Id,
                                             UNIDADE__c = 'Quilograma'
                                             );
         productList.add(testProduct);
         insert productList;

        List<CRM_Calendario_de_Eventos__c> eventList = TestDataFactory.createEventos(1, accList,'Test a campo');
         
        Attachment_Content__c testAttContent = new Attachment_Content__c(CRM_Calendario_de_Eventos__c = eventList[0].Id);
        insert testAttContent;
        
        List<Attachment> attachmentList = new List<Attachment>();

        Attachment testAttachment1 = new Attachment(Name = 'TestAttachment_1.txt',
                                                     ParentId = testAttContent.Id,
                                                     Body =  Blob.valueOf('Test Body')
                                                     );

        Attachment testAttachment2 = new Attachment(Name = 'TestAttachment_2.txt',
                                                     ParentId = testAttContent.Id,
                                                     Body = Blob.valueOf('Test Body')
                                                     );

        attachmentList.add(testAttachment1);
        attachmentList.add(testAttachment2);
        insert attachmentList;    
        
        List<ContentVersion> documentList = new List<ContentVersion>();
        ContentVersion version = new ContentVersion(Title = 'txt',
                                                    PathOnClient = 'testContentVersion.txt',
                                                    VersionData = Blob.valueOf('test body for contentVersion'),
                                                    IsMajorVersion = true);
        documentList.add(version);
        insert documentList;

        ContentVersion insertedDocument = [SELECT Id, ContentDocumentId FROM ContentVersion WHERE Id = :documentList[0].Id];

        ContentDocumentLink documentLink = new ContentDocumentLink();
        documentLink.ContentDocumentId = insertedDocument.ContentDocumentId;
        documentLink.LinkedEntityId = eventList[0].Id;

        insert documentLink;
    }

    @isTest
    public static void deleteOneAttachmentPositiveTest(){

        Attachment testAttach = [SELECT Id FROM Attachment WHERE Name = 'TestAttachment_2.txt' LIMIT 1];

        RestRequest req = new RestRequest(); 
        req.requestURI = '/services/apexrest/DeleteAttachmentAPI/';
        req.addParameter('attachmentId', String.valueOf(testAttach.Id));
        req.httpMethod = 'DELETE';

        RestContext.request = req;

        RestResponse resp = new RestResponse();
        RestContext.response = resp;

        test.startTest();
        DeleteAttachmentAPI.deleteAttachment();
        test.stopTest();
        
        DeleteAttachmentAPI.Response result = (DeleteAttachmentAPI.response)JSON.deserialize(resp.responseBody.toString(), DeleteAttachmentAPI.Response.class);
      
        System.assertEquals(true, result.status);
        System.assertEquals(testAttach.Id, result.deleted_Attachment_Id);
        System.assertEquals(null, result.deleted_AttachmentContent_Id);
    }

    @isTest
    public static void deleteAttachmentContentPositiveTest(){

        Attachment_Content__c testAttContent = [SELECT Id FROM Attachment_Content__c LIMIT 1];

        List<Attachment> testAttachList = [SELECT Id, Parent.Type FROM Attachment WHERE ParentId = :testAttContent.Id];

        
        delete testAttachList[1];

        RestRequest req = new RestRequest(); 
        req.requestURI = '/services/apexrest/DeleteAttachmentAPI/';
        req.addParameter('attachmentId', String.valueOf(testAttachList[0].Id));
        req.httpMethod = 'DELETE';

        RestContext.request = req;

        RestResponse resp = new RestResponse();
        RestContext.response = resp;

        test.startTest();
        DeleteAttachmentAPI.deleteAttachment();
        test.stopTest();

        DeleteAttachmentAPI.Response result = (DeleteAttachmentAPI.response)JSON.deserialize(resp.responseBody.toString(), DeleteAttachmentAPI.Response.class);
      
        System.assertEquals(true, result.status);
        System.assertEquals(testAttachList[0].Id, result.deleted_Attachment_Id);
        System.assertEquals(testAttContent.Id, result.deleted_AttachmentContent_Id);
    }

    @isTest
    public static void deleteAttachmentNoLadoaLadoEventPositiveTest(){

        List<Account> accList = [SELECT Id FROM Account WHERE Name =  'Test Account'];

        List<CRM_Calendario_de_Eventos__c> eventList2 = TestDataFactory.createEventos(1, accList,'Día de Campo');
                
        List<Attachment> attachmentList = new List<Attachment>();

        Attachment testAttachment3 = new Attachment(Name = 'TestAttachment_3.txt',
                                                     ParentId = eventList2[0].Id,
                                                     Body =  Blob.valueOf('Test Body')
                                                     );

        attachmentList.add(testAttachment3);
        insert attachmentList;

        RestRequest req = new RestRequest(); 
        req.requestURI = '/services/apexrest/DeleteAttachmentAPI/';
        req.addParameter('attachmentId', String.valueOf(attachmentList[0].Id));
        req.httpMethod = 'DELETE';

        RestContext.request = req;

        RestResponse resp = new RestResponse();
        RestContext.response = resp;

        test.startTest();
        DeleteAttachmentAPI.deleteAttachment();
        test.stopTest();
        
        DeleteAttachmentAPI.Response result = (DeleteAttachmentAPI.response)JSON.deserialize(resp.responseBody.toString(), DeleteAttachmentAPI.Response.class);
      
        System.assertEquals(true, result.status);
        System.assertEquals(attachmentList[0].Id, result.deleted_Attachment_Id);
        System.assertEquals(null, result.deleted_AttachmentContent_Id);
    }

    @isTest
    public static void deleteContentVersionPositiveTest(){

        ContentDocument document = [SELECT Id, (SELECT Id FROM ContentVersions) FROM ContentDocument LIMIT 1];

        RestRequest req = new RestRequest(); 
        req.requestURI = '/services/apexrest/DeleteAttachmentAPI/';
        req.addParameter('attachmentId', String.valueOf(document.ContentVersions[0].Id));
        req.httpMethod = 'DELETE';

        RestContext.request = req;

        RestResponse resp = new RestResponse();
        RestContext.response = resp;

        test.startTest();
        DeleteAttachmentAPI.deleteAttachment();
        test.stopTest();

        DeleteAttachmentAPI.Response result = (DeleteAttachmentAPI.response)JSON.deserialize(resp.responseBody.toString(), DeleteAttachmentAPI.Response.class);
      
        System.assertEquals(true, result.status);
        System.assertEquals(document.Id, result.deleted_ContentDocument_Id);
        System.assertEquals(document.ContentVersions[0].Id, result.deleted_ContentVersion_Id);
    }
}