Salesforce/main/default/objects/Account/fields/Barrio__c.field-meta.xml
<CustomField>
    <fullName>Barrio__c</fullName>
    <label>Bairro</label>
    <type>TextArea</type>
</CustomField>

Salesforce/main/default/objects/Account/fields/Calle__c.field-meta.xml
<CustomField>
    <fullName>Calle__c</fullName>
    <label>Rua</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/Account/fields/Categoria_CFOP__c.field-meta.xml
<CustomField>
    <fullName>Categoria_CFOP__c</fullName>
    <label>Categoria CFOP</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>00 - Industria (cooperativa)</fullName>
            </value>
            <value>
                <fullName>01 - Electricidad</fullName>
            </value>
            <value>
                <fullName>02 - Comunicacion</fullName>
            </value>
            <value>
                <fullName>03 - Transporte</fullName>
            </value>
            <value>
                <fullName>04 - Servicios</fullName>
            </value>
            <value>
                <fullName>05 - Bienes de consumo</fullName>
            </value>
            <value>
                <fullName>06 - Cliente, no contribuyente</fullName>
            </value>
            <value>
                <fullName>07 - Cliente agricola</fullName>
            </value>
            <value>
                <fullName>08 - Empresa de distribucion</fullName>
            </value>
            <value>
                <fullName>09 - Sucursal del fabricante</fullName>
            </value>
            <value>
                <fullName>0 - Industria (cooperativa)</fullName>
                <isActive>false</isActive>
                <label>0 - Industria (cooperativa)</label>
            </value>
            <value>
                <fullName>1 - Electricidad</fullName>
                <isActive>false</isActive>
                <label>1 - Electricidad</label>
            </value>
            <value>
                <fullName>2 - Comunicacion</fullName>
                <isActive>false</isActive>
                <label>2 - Comunicacion</label>
            </value>
            <value>
                <fullName>3 - Transporte</fullName>
                <isActive>false</isActive>
                <label>3 - Transporte</label>
            </value>
            <value>
                <fullName>4 - Servicios</fullName>
                <isActive>false</isActive>
                <label>4 - Servicios</label>
            </value>
            <value>
                <fullName>5 - Bienes de consumo</fullName>
                <isActive>false</isActive>
                <label>5 - Bienes de consumo</label>
            </value>
            <value>
                <fullName>6 - Cliente, no contribuyente</fullName>
                <isActive>false</isActive>
                <label>6 - Cliente, no contribuyente</label>
            </value>
            <value>
                <fullName>7 - Cliente agricola</fullName>
                <isActive>false</isActive>
                <label>7 - Cliente agricola</label>
            </value>
            <value>
                <fullName>8 - Empresa de distribucion</fullName>
                <isActive>false</isActive>
                <label>8 - Empresa de distribucion</label>
            </value>
            <value>
                <fullName>9 - Sucursal del fabricante</fullName>
                <isActive>false</isActive>
                <label>9 - Sucursal del fabricante</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Account/fields/CNPJ_CPF__c.field-meta.xml
<CustomField>
    <fullName>CNPJ_CPF__c</fullName>
    <externalId>true</externalId>
    <label>CNPJ/CPF</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Salesforce/main/default/objects/Account/fields/CNPJ_CPF_Solo_Numeros__c.field-meta.xml
<CustomField>
    <fullName>CNPJ_CPF_Solo_Numeros__c</fullName>
    <formula>SUBSTITUTE ( SUBSTITUTE ( SUBSTITUTE ( SUBSTITUTE( SUBSTITUTE( SUBSTITUTE(  CNPJ_CPF__c , &quot; &quot;, &quot;&quot;) , &quot;-&quot;, &quot;&quot;) , &quot;.&quot;, &quot;&quot;) , &quot;/&quot;, &quot;&quot;),&quot;,&quot; , &quot;&quot;),&quot;|&quot;,&quot;&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CNPJ/CPF (Solo Numeros)</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/Account/fields/Cod_Juros__c.field-meta.xml
<CustomField>
    <fullName>Cod_Juros__c</fullName>
    <label>Cod Juros</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01 - CálcJuros parts.pdr.</fullName>
            </value>
            <value>
                <fullName>02 - Cálc.juros saldos</fullName>
            </value>
            <value>
                <fullName>03 - CálcJurosSald cond.2</fullName>
            </value>
            <value>
                <fullName>04 - CálcJuros part.cond2</fullName>
            </value>
            <value>
                <fullName>05 - CálcJurosSald cond.3</fullName>
            </value>
            <value>
                <fullName>10 - Cálc.juros projeto</fullName>
            </value>
            <value>
                <fullName>12 - Cálc.jrs. sld.cta.Rz</fullName>
            </value>
            <value>
                <fullName>D1 - Cálc.juros p/advert.</fullName>
            </value>
            <value>
                <fullName>RS - N/A</fullName>
            </value>
            <value>
                <fullName>VK - CálcJurosParts.Ad CP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Account/fields/Codigo_Postal_SAP__c.field-meta.xml
<CustomField>
    <fullName>Codigo_Postal_SAP__c</fullName>
    <formula>IF(PoblacionSAP__c==null, &quot;&quot;, PoblacionSAP__r.Codigo_Postal__c)</formula>
    <label>Codigo Postal</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/Account/fields/CodigoSAP__c.field-meta.xml
<CustomField>
    <fullName>CodigoSAP__c</fullName>
    <label>CodigoSAP</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/Account/fields/Contribuinte_ICMS__c.field-meta.xml
<CustomField>
    <fullName>Contribuinte_ICMS__c</fullName>
    <label>Contribuinte ICMS</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1 - Contribuinte de ICMS</fullName>
            </value>
            <value>
                <fullName>2 - Contribuinte de ICMS - Isento</fullName>
            </value>
            <value>
                <fullName>9 - Não Contribuinte de ICMS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Account/fields/esta_en_SAP__c.field-meta.xml
<CustomField>
    <fullName>esta_en_SAP__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Está en SAP?</label>
    <type>Checkbox</type>
</CustomField>

Salesforce/main/default/main/default/objects/Account/fields/Formas_de_pagamento__c.field-meta.xml
<CustomField>
    <fullName>Formas_de_pagamento__c</fullName>
    <label>Formas de pagamento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A - Duplicata - Boleto Clientes</fullName>
            </value>
            <value>
                <fullName>B - Cartão de Crédito</fullName>
            </value>
            <value>
                <fullName>D - Boleto/Duplicata - Cobrança</fullName>
            </value>
            <value>
                <fullName>G - Boleto Fornec / DDA</fullName>
            </value>
            <value>
                <fullName>H - Depósito</fullName>
            </value>
            <value>
                <fullName>U - Transfêrencia</fullName>
            </value>
            <value>
                <fullName>K - Débito em Conta</fullName>
            </value>
            <value>
                <fullName>P - PIX</fullName>
            </value>
            <value>
                <fullName>T - TED</fullName>
            </value>
            <value>
                <fullName>C - Cheque</fullName>
            </value>
            <value>
                <fullName>E - Pagamento a vista</fullName>
            </value>
            <value>
                <fullName>R - Trib. e Concession. Cod Barras</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Account/fields/Grupo_de_Cuentas__c.field-meta.xml
<CustomField>
    <fullName>Grupo_de_Cuentas__c</fullName>
    <label>Grupo de Cuentas</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CMEX</fullName>
            </value>
            <value>
                <fullName>CPFI</fullName>
            </value>
            <value>
                <fullName>CPJU</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Account/fields/Numero__c.field-meta.xml
<CustomField>
    <fullName>Numero__c</fullName>
    <label>Numero</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/Account/fields/PoblacionSAP__c.field-meta.xml
<CustomField>
    <fullName>PoblacionSAP__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ciudad</label>
    <referenceTo>Cidade__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/Account/fields/Region_SAP__c.field-meta.xml
<CustomField>
    <fullName>Region_SAP__c</fullName>
    <formula>IF(PoblacionSAP__c==null, &quot;&quot;, PoblacionSAP__r.Nombre_Estado__c)</formula>
    <label>Region SAP</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/Account/recordTypes/Cuenta.recordType-meta.xml
<RecordType>
    <fullName>Cuenta</fullName>
    <active>true</active>
    <label>Cuenta</label>
</RecordType>

Salesforce/main/default/main/default/objects/Contact/fields/Barrio__c.field-meta.xml
<CustomField>
    <fullName>Barrio__c</fullName>
    <label>Barrio</label>
    <type>TextArea</type>
</CustomField>

Salesforce/main/default/objects/Contact/fields/Esta_en_SAP__c.field-meta.xml
<CustomField>
    <fullName>Esta_en_SAP__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Esta en SAP</label>
    <type>Checkbox</type>
</CustomField>

Salesforce/main/default/main/default/classes/Acc_SAP_Alta.cls
global class Acc_SAP_Alta {

    global class Retorno{
        webservice String msg;
        webservice Boolean ret;
        Webservice String cliente;
    }    
    static Account Acc(Id accId){
        try{
            return [Select Id, Grupo_de_Cuentas__c,
            Phone, Fax, CNPJ_CPF__c, CNPJ_CPF_Solo_Numeros__c, Parent.CNPJ_CPF__c,
            Calle__c, Numero__c, Region_SAP__c, Name, Barrio__c,
            PoblacionSAP__c, Codigo_Postal_SAP__c, esta_en_Sap__c, Categoria_CFOP__c,
            Cod_Juros__c, Formas_de_pagamento__c, Contribuinte_ICMS__c, RecordTypeId 
            From Account Where Id = :accId];
        }
        catch(Exception e){
            return null;
        }       
    }    
      
    WebService Static Retorno enviarCtaSAP(Id accId, Integer target){
        Retorno r = new Retorno(); Retorno r1 = new Retorno(); Retorno r2 = new Retorno();
        r.msg = '';
        r.ret = true;

        try{            
            Account a = Acc(accId);
            r.ret = true;
            r1 = altaCtaSAP(a, null, target);
            if(r1.ret){
                r.cliente = r1.cliente;
                r.msg = r1.msg;
            }
            else{                  
                r.msg += '\nNo ha podido ser actualizada en SAP\n' + r1.msg; r.ret = false;
            }
        }
        catch(Exception e){
            r.msg = '\nEn EnviarCtaSAP - Error: ' + e.getMessage(); r.ret = false;
        }
        return r;
    }
    
    Static Retorno altaCtaSAP(Account a, Contact contacto, Integer target){
        Retorno r = new Retorno();
        sapAltaCliente.Z_SD_ALTA_CLIENTEResponse_element resultado; 
        sapAltaCliente.TABLE_OF_BAPIRET2 EtReturn = new sapAltaCliente.TABLE_OF_BAPIRET2();
        String debuger = '';
        r.ret = true;
        r.msg = '\n';
        
        String sociedad = '01BR';
        
        String correo = ' ';
                    
        debuger = 'solo contacto';
        
        sapAltaCliente.Z_SD_ALTA_CLIENTE soap = new sapAltaCliente.Z_SD_ALTA_CLIENTE();           
        sapAltaCliente.ZSSD_IN_CLIE_GRAL ICliente = new sapAltaCliente.ZSSD_IN_CLIE_GRAL();           
        sapAltaCliente.TABLE_OF_ZSSD_IN_CLIE_CFIS TCategorias = new sapAltaCliente.TABLE_OF_ZSSD_IN_CLIE_CFIS();
        TCategorias.item = new List<sapAltaCliente.ZSSD_IN_CLIE_CFIS>();                   
        sapAltaCliente.TABLE_OF_ZSSD_IN_CLIE_IMPTO TDatos = new sapAltaCliente.TABLE_OF_ZSSD_IN_CLIE_IMPTO();
        TDatos.item = new List<sapAltaCliente.ZSSD_IN_CLIE_IMPTO>();
        String ampVentas = 'X';
        String ampSociedad = '';
            
        try{                        
            ICliente.ACREEDOR = '';                 
            ICliente.CANAL_DIST = '01';
            ICliente.CLIENTE_SAP = '';
                         
            ICliente.CLIENTE_SF = a.Id;
            
            String nombre = a.Name;
            if(nombre.length() > 20)
                ICliente.CONC_BUSQUEDA = nombre.substring(0,20);
            else
                ICliente.CONC_BUSQUEDA = nombre;
                         
            ICliente.COND_EXPEDICION = '05';
            
            ICliente.CUENTA_ASOCIADA = '0012100001';
            ICliente.GRUPO_CLIENTES = '01';
            ICliente.GRUPO_TESORERIA = 'E2';
            
            ICliente.GRUPO_CTAS = 'CUST';
            
            if(a.Grupo_de_Cuentas__c.substring(0,4) == 'CPFI'){
                ICliente.NRO_IIBB = a.CNPJ_CPF_Solo_Numeros__c;                
                ICliente.TP_CLIENTE = 'PF BRASIL';
                ICliente.PERS_FIS = '1';
            }
            
            if(a.Grupo_de_Cuentas__c.substring(0,4) == 'CPJU'){
                ICliente.NIF = a.CNPJ_CPF_Solo_Numeros__c;                
                ICliente.TP_CLIENTE = 'PJ BRASIL';
                ICliente.PERS_FIS = '2';
            }     
            
            if (a.Cod_Juros__c != null)
                ICliente.VZSKZ = a.Cod_Juros__c.substring(0,2);     
                
            if (a.Formas_de_pagamento__c != null)
                ICliente.ZWELS = a.Formas_de_pagamento__c.substring(0,1);         
                
            if (a.Contribuinte_ICMS__c != null)
                ICliente.ICMSTAXPAY = a.Contribuinte_ICMS__c.substring(0,1); 
                
            if (a.Categoria_CFOP__c != null)
                ICliente.CAT_CFOPC = a.Categoria_CFOP__c.substring(0,2);    
            
            //Data de Domicilio
            ICliente.PAIS = 'BR';
            ICliente.COD_POSTAL = a.Codigo_Postal_SAP__c;
            ICliente.POBLACION = a.PoblacionSAP__c;
            ICliente.REGION = a.Region_SAP__c;
            ICliente.BARRIO = a.Barrio__c;
            if(a.Calle__c.length() > 60)
                ICliente.CALLE = a.Calle__c.substring(0,60);
            else
                ICliente.CALLE = a.Calle__c;
            ICliente.NUMERO = a.Numero__c;
            
            //Correo electronico que sale del contacto 1
            ICliente.EMAIL = correo;
            
            ICliente.ESQUEMA_CLIENTE = '01';
            ICliente.FAX = '';
            if(a.Fax != null) ICliente.FAX = a.Fax;
             
            ICliente.GRUPO_IMPUTACION = '01';
            
            ICliente.MONEDA = 'BRL';
            
                        
            if(nombre.length() > 40)
                ICliente.NOMBRE = a.Name.substring(0,40);
            else
                ICliente.NOMBRE = a.Name;
                                 
            ICliente.ORG_VTAS = sociedad;
            ICliente.SECTOR = '01';
            ICliente.SOCIEDAD = sociedad;
            
            //Telefono de la cuenta
            ICliente.TELEFONO = '';
            if(a.Phone != null) ICliente.TELEFONO = String.valueOf(a.Phone);
            
            ICliente.Prientrega = '00'; //Por defecto se pasa la prioridad mas baja            
                              
            
            ICliente.GRP_COND = '';
            
            //LIMITE DE COMPRA
            ICliente.CALC_LIMITE = '';
            ICliente.LIMITE_COMPRA = '0';
            
            
            sapAltaCliente.ZSSD_IN_CLIE_IMPTO IDatos1 = new sapAltaCliente.ZSSD_IN_CLIE_IMPTO();
            
            IDatos1.TIPO_IMPUESTO = 'IBRX';
            IDatos1.CLASIF_FISCAL = '1';
            TDatos.item.add(IDatos1);
                        
            
            debuger = 'CallOut altaCliente de SAP - Error'; 
            
            soap.inputHttpHeaders_x = new Map<String, String>();
            String encodedusernameandpassword;
            
            String myData = 'SALESFORCEBR:2o21gdms33dS';
            Blob hash = Blob.valueOf(myData);
            encodedusernameandpassword = EncodingUtil.base64Encode(hash);
            soap.timeout_x = 60000;
            soap.inputHttpHeaders_x.put('Authorization', 'Basic '+ encodedusernameandpassword);    
            
            resultado = soap.Z_SD_ALTA_CLIENTE (EtReturn, TCategorias, TDatos, ampSociedad, ampVentas, ICliente, String.valueOf(target));
            
            //debuger = resultado;
            
            if (resultado != null){                        
               Integer i;
               if (resultado.ET_RETURN.item != null)
                   for (i=0;i<resultado.ET_RETURN.item.size();i++)
                      r.msg += resultado.ET_RETURN.item[i].Message;
               if (Integer.valueOf(resultado.E_SUBRC) == 0){
                  r.ret = true;
                  r.cliente = resultado.E_NRO_CLIENTE;
               }else{
                  r.msg += '\nError - No se actualizó SAP -El cliente queda pendiente de descargar';
                  r.ret = false;
               }
            }else{
               r.msg += '\n El resultado es nulo';
               r.ret = false;
            }   
            
        }catch(Exception e){
            r.msg += 'En altaCtaSAP - ';
            r.msg += debuger + '\n' + e.getMessage(); r.ret = false;            
        }
        return r;
    }
    
    // @isTest(seeAllData=true)
    // public static void test(){
        
    //     Acc(null);
        
    //     Account cuenta = [Select Id From Account Where Grupo_de_Cuentas__c = 'CNAC - Cliente Nacional' And codigoSAP__c != null And esta_en_Sap__c = true limit 1];
    
    //     Account cuenta2 = Acc(cuenta.Id);
                
    //     cuenta2.name = 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa';
        
    //     altaCtaSAP(cuenta2, null, 200);
    
    // }
    
}