Salesforce/main/default/objects/Account/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Estado</label>
    <referenceTo>Estado__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/Configuracion_BMX__c/Configuracion_BMX__c.object-meta.xml
<CustomObject>
    <description>Indicador de Parametros.</description>
    <label>Configuracion_BMX</label>
    <nameField>
        <label>Configuracion Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuraciones_BMX</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/Configuracion_BMX__c/fields/PM_Safra_Actual_DescontoRoyalty__c.field-meta.xml
<CustomField>
    <fullName>PM_Safra_Actual_DescontoRoyalty__c</fullName>
    <label>PM Safra Actual DescontoRoyalty</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/Estado__c/Estado__c.object-meta.xml
<CustomObject>
    <label>Estado</label>
    <nameField>
        <label>Nome do Estado</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estados</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/Evento_Royalty__c/Evento_Royalty__c.object-meta.xml
<CustomObject>
    <label>Evento Royalty</label>
    <nameField>
        <label>Nombre de Evento Royalty</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Eventos Royalty</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/Evento_Royalty__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pendiente de aprobación</fullName>
                <label>Aprovação pendente</label>
            </value>
            <value>
                <fullName>Aprobado</fullName>
                <label>Aprovado</label>
            </value>
            <value>
                <fullName>Edicion</fullName>
                <default>true</default>
                <label>Edição</label>
            </value>
            <value>
                <fullName>Anulado</fullName>
            </value>
            <value>
                <fullName>Rechazado</fullName>
                <isActive>false</isActive>
                <label>Rechazado</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Evento_Royalty__c/fields/Saldo_por_safra__c.field-meta.xml
<CustomField>
    <fullName>Saldo_por_safra__c</fullName>
    <label>Saldo por safra</label>
    <referenceTo>Saldo_por_safra__c</referenceTo>
    <relationshipLabel>Eventos Royalty</relationshipLabel>
    <relationshipName>Eventos_Royalty</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Salesforce/main/default/main/default/objects/Saldo_por_safra__c/Saldo_por_safra__c.object-meta.xml
<CustomObject>
    <label>Saldo por safra</label>
    <nameField>
        <label>Nombre de Saldo por safra</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Saldos por safra</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/Saldo_por_safra__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Saldos por safra</relationshipLabel>
    <relationshipName>Saldos_por_safra</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Salesforce/main/default/objects/Saldo_por_safra__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Activo</fullName>
            </value>
            <value>
                <fullName>Inactivo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Saldo_por_safra__c/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <label>Safra</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/Saldo_por_safra__c/fields/Saldo__c.field-meta.xml
<CustomField>
    <fullName>Saldo__c</fullName>
    <label>Saldo Inicial</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Salesforce/main/default/main/default/objects/Saldo_por_safra__c/fields/Saldo_Disponible__c.field-meta.xml
<CustomField>
    <fullName>Saldo_Disponible__c</fullName>
    <formula>Saldo__c - Saldo_Gastado__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Saldo Disponível</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Salesforce/main/default/objects/SiteUser__c/SiteUser__c.object-meta.xml
<CustomObject>
    <description>Forma parte del circuito del Sitio Portal Web.</description>
    <label>SiteUser</label>
    <nameField>
        <label>Nombre de Usuário</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SiteUsers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/SiteUserAccount__c/SiteUserAccount__c.object-meta.xml
<CustomObject>
    <label>SiteUserAccount</label>
    <nameField>
        <label>Nombre de SiteUserAccount</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SiteUserAccounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/SiteUserAccount__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SiteUserAccounts</relationshipLabel>
    <relationshipName>SiteUserAccounts</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/SiteUserAccount__c/fields/SiteUser__c.field-meta.xml
<CustomField>
    <fullName>SiteUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SiteUser</label>
    <referenceTo>SiteUser__c</referenceTo>
    <relationshipLabel>SiteUserAccounts</relationshipLabel>
    <relationshipName>SiteUserAccounts</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/SiteUserSession__c/SiteUserSession__c.object-meta.xml
<CustomObject>
    <label>SiteUserSession</label>
    <nameField>
        <displayFormat>S{00000000}</displayFormat>
        <label>Nombre de SiteUserSession</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SiteUserSessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/SiteUserSession__c/fields/SiteUser__c.field-meta.xml
<CustomField>
    <fullName>SiteUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SiteUser</label>
    <referenceTo>SiteUser__c</referenceTo>
    <relationshipLabel>SiteUserSessions</relationshipLabel>
    <relationshipName>SiteUserSessions</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/classes/aSiteSaldoSafraControllerTest.cls
@IsTest
public class aSiteSaldoSafraControllerTest {

    @IsTest
    private static void verifyWhenTokenIsNull() {
        
        aSiteSaldoSafraController aSiteSaldoSafra = new aSiteSaldoSafraController();

        Test.setCurrentPageReference(new PageReference('Page.aSiteSaldoSafra'));
        System.currentPageReference().getParameters().put('token', null);

        Test.startTest();
        PageReference pr = aSiteSaldoSafra.validate();
        Test.stopTest();

        PageReference pageExpected = new PageReference('/apex/aSiteLogin');

        //System.assertEquals(pageExpected.getUrl(), pr.getUrl());
        //System.assertEquals(false, aSiteSaldoSafra.activeNuevoEvento);
    }

    @IsTest
    private static void verifyWhenUserIsIncorrect() {
        
        Account testAccount = [SELECT Id FROM Account LIMIT 1];

        aSiteSaldoSafraController aSiteSaldoSafra = new aSiteSaldoSafraController();

        Test.setCurrentPageReference(new PageReference('Page.aSiteSaldoSafra'));
        System.currentPageReference().getParameters().put('token', testAccount.id);
         
        Test.startTest();
        PageReference pr = aSiteSaldoSafra.validate(); 
        Test.stopTest();

        //System.assertEquals(false, aSiteSaldoSafra.activeNuevoEvento);
    }

    @IsTest
    private static void verifyWhenUserIsCorrect() {
        
        SiteUserSession__c testSiteUserSession = [SELECT Id FROM SiteUserSession__c LIMIT 1]; 

        aSiteSaldoSafraController aSiteSaldoSafra = new aSiteSaldoSafraController();

        Test.setCurrentPageReference(new PageReference('Page.aSiteSaldoSafra'));
        System.currentPageReference().getParameters().put('token', testSiteUserSession.id);

        Test.startTest();
        PageReference pr = aSiteSaldoSafra.validate();
        Test.stopTest();

        System.assertEquals(null, pr);
    }

    @IsTest
    private static void shouldReturnAFalseBooleanIfThereIsNoAccountOfSaldoPorSafraRelatedToTheAccount() {
        
        Account newAccount = Build.anAccount()
            .withName('Test account')
            .withType('Multiplicador')
            .withMarca('BRMX')
            .build();
        insert newAccount;

        SiteUserAccount__c testSiteUserAccount = [SELECT Id, Account__c FROM SiteUserAccount__c LIMIT 1];
        testSiteUserAccount.Account__c = newAccount.Id;
        update testSiteUserAccount;

        SiteUserSession__c testSiteUserSession = [SELECT Id FROM SiteUserSession__c LIMIT 1];

        aSiteSaldoSafraController aSiteSaldoSafra = new aSiteSaldoSafraController();

        Test.setCurrentPageReference(new PageReference('Page.aSiteSaldoSafra'));
        System.currentPageReference().getParameters().put('token', testSiteUserSession.id);

        Test.startTest();
        PageReference pr = aSiteSaldoSafra.validate();
        Test.stopTest();

        //System.assertEquals(false, aSiteSaldoSafra.renderSaldo); 
    }

    @IsTest
    private static void ifTheAccountHasSaldoPorSafraTheRenderSaldoIsEqualToTrueAndSaldoActualEqualToTheSaldoPorSafraAndTheEventoRoyaltyListIsEmptyBecauseThereIsNoEventoRoyaltyWithTheSafraActual() {
        
        SiteUserSession__c testSiteUserSession = [SELECT Id FROM SiteUserSession__c LIMIT 1]; 

        aSiteSaldoSafraController aSiteSaldoSafra = new aSiteSaldoSafraController();

        Test.setCurrentPageReference(new PageReference('Page.aSiteSaldoSafra'));
        System.currentPageReference().getParameters().put('token', testSiteUserSession.id);

        Test.startTest();
        PageReference pr = aSiteSaldoSafra.validate();
        Test.stopTest();

        Saldo_por_safra__c saldoPorSafraOne = [SELECT Id, Saldo_Disponible__c, Saldo__c, Estado__c FROM Saldo_por_safra__c LIMIT 1];

        //System.assertEquals(true, aSiteSaldoSafra.renderSaldo);
        //System.assertEquals(saldoPorSafraOne, aSiteSaldoSafra.saldoActual);
        //System.assert(aSiteSaldoSafra.eventos.isEmpty());
    }

    @IsTest
    private static void theListOfEventosMustBeDifferentFromEmptyBecauseThereIsEventoRoyaltyWithTheSafraActual() {
        
        List<Evento_Royalty__c> eventosRoyaltys = [
            SELECT Id, Safra__c 
            FROM Evento_Royalty__c
        ];

        for(Evento_Royalty__c eRoyalty : eventosRoyaltys) {
            eRoyalty.Safra__c = '18/19';
        }
        eventosRoyaltys[0].Estado__c = 'Pendiente de aprobación';
        update eventosRoyaltys;

        SiteUserSession__c testSiteUserSession = [SELECT Id FROM SiteUserSession__c LIMIT 1]; 

        aSiteSaldoSafraController aSiteSaldoSafra = new aSiteSaldoSafraController();

        Test.setCurrentPageReference(new PageReference('Page.aSiteSaldoSafra'));
        System.currentPageReference().getParameters().put('token', testSiteUserSession.id);

        Test.startTest();
        PageReference pr = aSiteSaldoSafra.validate();
        Test.stopTest();

        //System.assertEquals(3, aSiteSaldoSafra.eventos.size());
    }

    @IsTest
    private static void shouldReturnADateInTextFormat() {

        aSiteSaldoSafraController aSiteSaldoSafra = new aSiteSaldoSafraController();
    
        Test.startTest();
        String fechaReturn = aSiteSaldoSafra.getTextoFecha(Date.today());
        Test.stopTest();

        String fecha = Date.today().day() + '/' + Date.today().month() + '/' + Date.today().year();

        //System.assertEquals(fecha, fechaReturn);
    }

    @IsTest
    private static void shouldReturnThePageReferenceToCreateAnEventoRoyalty() {

        aSiteSaldoSafraController aSiteSaldoSafra = new aSiteSaldoSafraController();
    
        Test.startTest();
        //PageReference newPr = aSiteSaldoSafra.goToCreateRoyaltyEventReembolso();
        Test.stopTest();

        PageReference pageExpected = new PageReference('/apex/aSiteCreateRoyaltyEvent');

        //System.assertEquals(pageExpected.getUrl(), newPr.getUrl());
    }

    @IsTest
    private static void shouldReturnThePageReferenceToModifyAnEventRoyalty() {

        List<Evento_Royalty__c> eventosRoyaltys = [
            SELECT Id, Safra__c 
            FROM Evento_Royalty__c
        ];

        aSiteSaldoSafraController aSiteSaldoSafra = new aSiteSaldoSafraController();
    
        Test.startTest();
        aSiteSaldoSafra.eventoId = eventosRoyaltys[0].Id;
        PageReference newPr = aSiteSaldoSafra.editar();
        Test.stopTest();

        PageReference pageExpected = new PageReference('/apex/aSiteCreateRoyaltyEvent?eventoId=' + eventosRoyaltys[0].Id);

        //ystem.assertEquals(pageExpected.getUrl(), newPr.getUrl());
    }

    @IsTest
    private static void shouldSendTheEventoRoyaltyForApproval() {

        Account testAccount = [SELECT Id FROM Account LIMIT 1];

        Saldo_por_safra__c saldoPorSafraOne = [SELECT Id FROM Saldo_por_safra__c LIMIT 1];
    
        Evento_Royalty__c eventoRoyaltyFour = Build.anEventoRoyalty()
            .withCuenta(testAccount)
            .withName('Evento Royalty Four')
            .withSaldoPorSafra(saldoPorSafraOne)
            .withData('17/2/2020')
            .withEstado('Edicion')
            .withValor(1299)
            .withItems('Outdoor')
            .withSafra('18/19')
            .build();
        insert eventoRoyaltyFour;

        aSiteSaldoSafraController aSiteSaldoSafra = new aSiteSaldoSafraController();

        Test.startTest();
        aSiteSaldoSafra.safraActual = '18/19';
        aSiteSaldoSafra.activeAccount = testAccount;
        aSiteSaldoSafra.eventoId = eventoRoyaltyFour.Id;
        //aSiteSaldoSafra.enviarParaAprobacion();
        Test.stopTest();

        List<Evento_Royalty__c> eventosRoyaltys = [
            SELECT Id, Safra__c, Estado__c
            FROM Evento_Royalty__c
            WHERE Id = :eventoRoyaltyFour.Id
        ];

        //System.assertEquals('Pendiente de aprobación', eventosRoyaltys[0].Estado__c);
    }

    @TestSetup
    private static void IsTheSetup() {

        Profile profileIdSupervisor = [SELECT Id FROM Profile WHERE Name = 'Supervisor Administrativo' LIMIT 1];
        Profile profileIdGerente = [SELECT Id FROM Profile WHERE Name = 'Gerente Administrativo' LIMIT 1];
         
        User supervisor = new User(
            LastName = 'Rosa',
            FirstName='Jorge Cristiano',
            Alias = 'jcr',
            Email = 'jorge.rosa@asdf.com',
            Username = 'jorge.rosa@asdf.com',
            ProfileId = profileIdSupervisor.id,
            TimeZoneSidKey = 'GMT',
            LanguageLocaleKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            LocaleSidKey = 'en_US'
        );

        User gerente = new User(
            LastName = 'Bertagnolli',
            FirstName='Sergio Vieira',
            Alias = 'svb',
            Email = 'sergio.bertagnolli@asdf.com',
            Username = 'sergio.bertagnolli@asdf.com',
            ProfileId = profileIdGerente.id,
            TimeZoneSidKey = 'GMT',
            LanguageLocaleKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            LocaleSidKey = 'en_US'
        );

        List<User> users = new List<User> {
            supervisor, gerente
        };
        insert users;

        Account testAccount = Build.anAccount()
            .withName('Test account')
            .withType('Multiplicador')
            .withMarca('BRMX')
            .withSupervisor(supervisor)
            .withGerenteComercial(gerente)
            .build();
        insert testAccount;

        SiteUser__c testSiteUser = Build.aSiteUser()
            .withName('Test site user')
            .withEmail('testsu@test.com')
            .withPassword('test')
            .withActive(true)
            .withHabilitadoAnexos(true)
            .build();
        insert testSiteUser;

        Estado__c estado = Build.anEstado()
            .withMostrarenportal(true)
            .withName('Estado test')
            .build();
        insert estado;

        SiteUserAccount__c testSiteUserAccount = Build.aSiteUserAccount()
            .withName('Test site user account')
            .withAccount(testAccount)
            .withSiteUser(testSiteUser)
            .withActive(true)
            .build();
        insert testSiteUserAccount;

        SiteUserSession__c testSiteUserSession = Build.aSiteUserSession()
            .withSiteUser(testSiteUser)
            .withMarca('BRMX')
            .withSafra('18/19')
            .build();
        insert testSiteUserSession;

        Configuracion_BMX__c testConfiguracionBMX = Build.aConfiguracionBMX()           
            .build();
        insert testConfiguracionBMX;
        testConfiguracionBMX.PM_Safra_Actual_DescontoRoyalty__c = '18/19';
        update testConfiguracionBMX;

        Saldo_por_safra__c saldoPorSafraOne = Build.aSaldoPorSafra()
            .withName('Saldo Por Safra One')
            .withAccount(testAccount)
            .withEstado('Activo')
            .withSafra('18/19')
            .withSaldo(1200)
            .build();
        insert saldoPorSafraOne;

        Evento_Royalty__c eventoRoyaltyOne = Build.anEventoRoyalty()
            .withCuenta(testAccount)
            .withName('Evento Royalty One')
            .withSaldoPorSafra(saldoPorSafraOne)
            .withData('31/1/2020')
            .withEstado('Aprobado')
            .withValor(1199)
            .withItems('Outdoor;Palestrante')
            .build();

        Evento_Royalty__c eventoRoyaltyTwo = Build.anEventoRoyalty()
            .withCuenta(testAccount)
            .withName('Evento Royalty Two')
            .withSaldoPorSafra(saldoPorSafraOne)
            .withData('10/2/2020')
            .withEstado('Aprobado')
            .withValor(1545)
            .withItems('Palestrante')
            .build();

        Evento_Royalty__c eventoRoyaltyThree = Build.anEventoRoyalty()
            .withCuenta(testAccount)
            .withName('Evento Royalty Three')
            .withSaldoPorSafra(saldoPorSafraOne)
            .withData('15/1/2020')
            .withEstado('Aprobado')
            .withValor(899)
            .withItems('Outdoor')
            .build();

        List<Evento_Royalty__c> eventoRoyaltyList = new List<Evento_Royalty__c> {
            eventoRoyaltyOne, eventoRoyaltyTwo, eventoRoyaltyThree
        };
        insert eventoRoyaltyList;
    }
}