Salesforce/main/default/objects/Account/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Estado</label>
    <referenceTo>Estado__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Account/fields/Region_Comercial__c.field-meta.xml
<CustomField>
    <fullName>Region_Comercial__c</fullName>
    <formula>TEXT(Region__r.Region_Comercial__c)</formula>
    <label>Região Comercial</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/Account/recordTypes/Cuenta.recordType-meta.xml
<RecordType>
    <fullName>Cuenta</fullName>
    <active>true</active>
    <label>Cuenta</label>
</RecordType>

Salesforce/main/default/objects/Contract/fields/Region_Comercial__c.field-meta.xml
<CustomField>
    <fullName>Region_Comercial__c</fullName>
    <label>Regiao Comercial</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/Contract/fields/Sociedad__c.field-meta.xml
<CustomField>
    <fullName>Sociedad__c</fullName>
    <label>Sociedad</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Marca</valueSetName>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Contrato__c/Contrato__c.object-meta.xml
<CustomObject>
    <description>CONTRATO DE LICENCIAMENTO PARA MULTIPLICAÇÃO E COMERCIALIZAÇÃO</description>
    <label>Contrato de Multiplicação</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Numero do Contrato de Multiplicação</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contratos de Multiplicação</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/Contrato__c/fields/Contrato_marco__c.field-meta.xml
<CustomField>
    <fullName>Contrato_marco__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contrato guarda chuva para 3 safras</description>
    <label>Contrato Macro</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Termos Aditivos</relationshipLabel>
    <relationshipName>Contratos_de_Multiplicacion</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Contrato__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Edição</fullName>
                <default>true</default>
                <label>Edição</label>
            </value>
            <value>
                <fullName>Pendente de Aprovação</fullName>
            </value>
            <value>
                <fullName>Aguardando Assinatura</fullName>
            </value>
            <value>
                <fullName>Pendente de Impressão</fullName>
            </value>
            <value>
                <fullName>Pendente de Envio</fullName>
            </value>
            <value>
                <fullName>Pendente de Postagem</fullName>
            </value>
            <value>
                <fullName>Aguarda Retorno</fullName>
            </value>
            <value>
                <fullName>Chegou</fullName>
            </value>
            <value>
                <fullName>Inutilizado</fullName>
            </value>
            <value>
                <fullName>Anulado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Contrato__c/fields/Estados_Comercializacao__c.field-meta.xml
<CustomField>
    <fullName>Estados_Comercializacao__c</fullName>
    <label>Estados de Comercialização</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AC</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AM</fullName>
            </value>
            <value>
                <fullName>AP</fullName>
            </value>
            <value>
                <fullName>BA</fullName>
            </value>
            <value>
                <fullName>CE</fullName>
            </value>
            <value>
                <fullName>DF</fullName>
            </value>
            <value>
                <fullName>ES</fullName>
            </value>
            <value>
                <fullName>GO</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MG</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>PA</fullName>
            </value>
            <value>
                <fullName>Paraguai</fullName>
            </value>
            <value>
                <fullName>PB</fullName>
            </value>
            <value>
                <fullName>PE</fullName>
            </value>
            <value>
                <fullName>PI</fullName>
            </value>
            <value>
                <fullName>PR</fullName>
            </value>
            <value>
                <fullName>RJ</fullName>
            </value>
            <value>
                <fullName>RN</fullName>
            </value>
            <value>
                <fullName>RO</fullName>
            </value>
            <value>
                <fullName>RR</fullName>
            </value>
            <value>
                <fullName>RS</fullName>
            </value>
            <value>
                <fullName>SC</fullName>
            </value>
            <value>
                <fullName>SE</fullName>
            </value>
            <value>
                <fullName>SP</fullName>
            </value>
            <value>
                <fullName>TO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Contrato__c/fields/Meta_Qde_comodato_de_area__c.field-meta.xml
<CustomField>
    <fullName>Meta_Qde_comodato_de_area__c</fullName>
    <label>Meta Qde Comodato de Área</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/main/default/objects/Contrato__c/fields/Meta_Qde_Dias_de_Campo__c.field-meta.xml
<CustomField>
    <fullName>Meta_Qde_Dias_de_Campo__c</fullName>
    <label>Meta Qde Días de Campo Sem Custo</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/main/default/objects/Contrato__c/fields/Observacao__c.field-meta.xml
<CustomField>
    <fullName>Observacao__c</fullName>
    <description>Informações genéricas sobre o processo de recebimento dos contratos</description>
    <inlineHelpText>Informações genéricas sobre o processo de recebimento dos contratos</inlineHelpText>
    <label>Observação</label>
    <type>TextArea</type>
</CustomField>

Salesforce/main/default/objects/Contrato__c/fields/Region_Comercial__c.field-meta.xml
<CustomField>
    <fullName>Region_Comercial__c</fullName>
    <label>Região Comercial</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>REGION 1</fullName>
            </value>
            <value>
                <fullName>REGION 2</fullName>
            </value>
            <value>
                <fullName>CERRADO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Contrato__c/fields/Sociedad__c.field-meta.xml
<CustomField>
    <fullName>Sociedad__c</fullName>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BRMX</fullName>
            </value>
            <value>
                <fullName>DSEM</fullName>
            </value>
            <value>
                <fullName>NEOG</fullName>
            </value>
            <value>
                <fullName>DAGMA</fullName>
            </value>
            <value>
                <fullName>LICENÇAS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Contrato__c/recordTypes/DSEM.recordType-meta.xml
<RecordType>
    <fullName>DSEM</fullName>
    <active>true</active>
    <description>Contratos de la sociedad Don Mario</description>
    <label>DSEM</label>
</RecordType>

Salesforce/main/default/main/default/objects/Contrato__c/recordTypes/Termo_Aditivo.recordType-meta.xml
<RecordType>
    <fullName>Termo_Aditivo</fullName>
    <active>true</active>
    <description>Termo Aditivos de Contrato de multiplicação - a partir de 2018</description>
    <label>Termo Aditivo Comerciais</label>
</RecordType>

Salesforce/main/default/objects/Item_del_Contrato__c/Item_del_Contrato__c.object-meta.xml
<CustomObject>
    <description>Item de CONTRATO DE LICENCIAMENTO PARA MULTIPLICAÇÃO E COMERCIALIZAÇÃO</description>
    <label>Item del Contrato</label>
    <nameField>
        <label>Nombre de Item del Contrato</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items del Contrato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/Item_del_Contrato__c/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Indica la categoría del ítem</description>
    <label>Categoria</label>
    <referenceTo>Categoria__c</referenceTo>
    <relationshipLabel>Items del Contrato</relationshipLabel>
    <relationshipName>Items_del_Contrato</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/Item_del_Contrato__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AC</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AM</fullName>
            </value>
            <value>
                <fullName>AP</fullName>
            </value>
            <value>
                <fullName>BA</fullName>
            </value>
            <value>
                <fullName>CE</fullName>
            </value>
            <value>
                <fullName>DF</fullName>
            </value>
            <value>
                <fullName>ES</fullName>
            </value>
            <value>
                <fullName>GO</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MG</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>PA</fullName>
            </value>
            <value>
                <fullName>Paraguai</fullName>
            </value>
            <value>
                <fullName>PB</fullName>
            </value>
            <value>
                <fullName>PE</fullName>
            </value>
            <value>
                <fullName>PI</fullName>
            </value>
            <value>
                <fullName>PR</fullName>
            </value>
            <value>
                <fullName>RJ</fullName>
            </value>
            <value>
                <fullName>RN</fullName>
            </value>
            <value>
                <fullName>RO</fullName>
            </value>
            <value>
                <fullName>RR</fullName>
            </value>
            <value>
                <fullName>RS</fullName>
            </value>
            <value>
                <fullName>SC</fullName>
            </value>
            <value>
                <fullName>SE</fullName>
            </value>
            <value>
                <fullName>SP</fullName>
            </value>
            <value>
                <fullName>TO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Item_del_Contrato__c/fields/Variedad__c.field-meta.xml
<CustomField>
    <fullName>Variedad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Variedade</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Marca__c</field>
            <operation>equals</operation>
            <valueField>Variedad__c.Sociedad__c</valueField>
        </filterItems>
        <filterItems>
            <field>Variedad__c.Ativa__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Variedad__c</referenceTo>
    <relationshipLabel>Items del Contrato</relationshipLabel>
    <relationshipName>Items_del_Contrato</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Variedad__c/Variedad__c.object-meta.xml
<CustomObject>
    <description>Variedades, disponibles para incluir en los Contratos de Multiplicación</description>
    <label>Variedad</label>
    <nameField>
        <label>Nome Comercial</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Variedades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/Variedad__c/fields/Marca_comercial__c.field-meta.xml
<CustomField>
    <fullName>Marca_comercial__c</fullName>
    <label>Marca comercial</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DM Sementes</fullName>
                <label>DONMARIO</label>
            </value>
            <value>
                <fullName>Brasmax</fullName>
                <label>BRASMAX</label>
            </value>
            <value>
                <fullName>Neogen</fullName>
                <label>NEOGEN</label>
            </value>
            <value>
                <fullName>Dagma</fullName>
                <label>DAGMA</label>
            </value>
            <value>
                <fullName>Licenças</fullName>
                <label>LICENÇAS</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Variedad__c/fields/Sociedad__c.field-meta.xml
<CustomField>
    <fullName>Sociedad__c</fullName>
    <formula>CASE(Marca_comercial__c,&quot;Brasmax&quot;,&quot;BRMX&quot;,&quot;DM Sementes&quot;,&quot;DSEM&quot;,&quot;Neogen&quot;,&quot;NEOG&quot;,&quot;&quot;)</formula>
    <label>Sociedad</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/globalValueSets/Marca.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BRMX</fullName>
    </customValue>
    <customValue>
        <fullName>DSEM</fullName>
    </customValue>
    <customValue>
        <fullName>NEOG</fullName>
    </customValue>
    <customValue>
        <fullName>DAGMA</fullName>
    </customValue>
    <customValue>
        <fullName>LICENÇAS</fullName>
    </customValue>
    <masterLabel>Marca</masterLabel>
</GlobalValueSet>

Salesforce/main/default/classes/ClonarContratoControllerTest.cls
@isTest
public class ClonarContratoControllerTest{
	@TestSetup
	static void setup(){
		Account cuenta = new Account(Name = 'Test');
		insert cuenta;
		Contract contratoMarco = new Contract(Name = 'Contrato marco', AccountId = cuenta.Id);
		insert contratoMarco;
		Contrato__c contrato = new Contrato__c(RecordTypeId = [SELECT ID
		                                                       FROM RecordType
		                                                       WHERE DeveloperName = 'Termo_Aditivo'].id, Estado__c = 'Chegou', Observacao__c = 'Soy el original', Sociedad__c = 'DSEM', Estados_Comercializacao__c = 'CE', Contrato_marco__c = contratoMarco.Id, Region_Comercial__c = 'REGION 1', Meta_Qde_comodato_de_area__c = 1, Meta_Qde_Dias_de_Campo__c = 1);
		insert contrato;

		Categoria__c categoria = new Categoria__c(Name = 'ElPsyKongroo');
		insert categoria;

		Variedad__c variedad = new Variedad__c(Name = 'Reading Steiner', Ativa__c = true, Marca_comercial__c = 'Brasmax');
		insert variedad;
	}

	@IsTest
	static void debeClonarseElContratoConSusItems(){

		PageReference pref = Page.ClonarContrato;
		Test.setCurrentPage(pref);

		Contrato__c contrato = [SELECT ID
		                        FROM Contrato__c
		                        WHERE Estado__c = 'Chegou'];

		Item_del_Contrato__c item = new Item_del_Contrato__c();
		item.Contrato_de_Multiplicacion__c = contrato.Id;
		item.Contrato_de_Multiplicacao_vol__c = contrato.Id;
		insert item;

		ApexPages.StandardController con = new ApexPages.StandardController(contrato);

		ClonarContratoController controlador = new ClonarContratoController(con);

		Test.startTest();

		PageReference ref = controlador.cloneWithItems();

		PageReference redir = new PageReference('/' + controlador.newRecordId + '/e?retURL=%2F' + controlador.newRecordId);

		System.assertEquals(ref.getUrl(), redir.getUrl());
		Test.stopTest();
		Contrato__c newPO = [select id
		                     from Contrato__c
		                     where id = :controlador.newRecordId];
		System.assertNotEquals(newPO, null);
		List<Item_del_Contrato__c> newItems = [Select Id
		                                       From Item_del_Contrato__c
		                                       WHERE Contrato_de_Multiplicacion__c = :newPO.id];
		System.assertEquals(newItems.size(), 1);
	}

	@isTest
	static void debeActualizarElCampoLogDeCambios(){
		Contrato__c contrato = [SELECT ID
		                        FROM Contrato__c];
		ApexPages.StandardController con = new ApexPages.StandardController(contrato);
		ClonarContratoController controlador = new ClonarContratoController(con);
		Test.startTest();

		controlador.cloneWithItems();
		List<Contrato__c> listaContratos = [SELECT ID, Estado__c, Observacao__c, log_cambios__c
		                                    FROM Contrato__c];
		listaContratos[1].Sociedad__c = 'NEOG';
		listaContratos[1].Estado__c = 'Pendente de Aprovação';
		listaContratos[1].Estados_Comercializacao__c = 'AM';
		listaContratos[1].Region_Comercial__c = 'REGION 2';
		listaContratos[1].Contrato_marco__c = null;
		listaContratos[1].Meta_Qde_comodato_de_area__c = 5;
		listaContratos[1].Meta_Qde_Dias_de_Campo__c = 5;
		update listaContratos[1];
		listaContratos = [SELECT ID, Estado__c, Observacao__c, log_cambios__c
		                  FROM Contrato__c];
		System.debug(listaContratos[1].log_cambios__c);
		Test.stopTest();

		System.assertNotEquals(null, listaContratos[1].log_cambios__c, 'El Log no se escribió');
		System.assertEquals(true, listaContratos[1].log_cambios__c.contains('alterada'), 'No se tomaron los cambios');
	}

	@isTest
	static void debeContarCorrectamenteLaCantidadDeItems(){
		PageReference pref = Page.ClonarContrato;
		Test.setCurrentPage(pref);

		Contrato__c contrato = [SELECT ID
		                        FROM Contrato__c
		                        WHERE Estado__c = 'Chegou'];


		Item_del_Contrato__c item = new Item_del_Contrato__c();
		item.Contrato_de_Multiplicacion__c = contrato.Id;
		item.Contrato_de_Multiplicacao_vol__c = contrato.Id;
		item.Contrato_de_Multiplicacion__c = contrato.Id;
		insert item;
		System.debug(item.Contrato_de_Multiplicacion__c);

		ApexPages.StandardController con = new ApexPages.StandardController(contrato);

		ClonarContratoController controlador = new ClonarContratoController(con);

		Test.startTest();

		PageReference ref = controlador.cloneWithItems();

		PageReference redir = new PageReference('/' + controlador.newRecordId + '/e?retURL=%2F' + controlador.newRecordId);

		System.assertEquals(ref.getUrl(), redir.getUrl());
		Test.stopTest();
		Contrato__c newPO = [select id
		                     from Contrato__c
		                     where id = :controlador.newRecordId];
		List<Item_del_Contrato__c> items = [SELECT ID, Contrato_de_Multiplicacion__c
		                                    FROM Item_del_Contrato__c];
		System.assertEquals(items[1].Contrato_de_Multiplicacion__c, newPO.Id, 'No se clono la relacion mater-detail');
	}

	@IsTest
	static void debeClonarElContratoEnLightning(){
		Contrato__c contrato = [SELECT ID
		                        FROM Contrato__c
		                        WHERE Estado__c = 'Chegou'];
		Test.startTest();
		String id = ClonarContratoLightningController.cloneContract(contrato.Id);
		Test.stopTest();
		System.assertNotEquals(null, id, 'No se clono el contrato');
	}

	@isTest
	static void NoDebeClonarElContratoSiElEstadoNoEsChego(){
		Contrato__c contrato = [SELECT ID
		                        FROM Contrato__c
		                        WHERE Estado__c = 'Chegou'];
		contrato.Estado__c = 'Pendente de Aprovação';
		update contrato;
		String id;
		String mensaje;
		Test.startTest();
		try{
			id = ClonarContratoLightningController.cloneContract(contrato.Id);
		} catch (Exception e){
			mensaje = e.getMessage();
		}
		Test.stopTest();
		System.assertEquals(null, id, 'No se lanzo la excepcion para impedir clonar el contrato');
		System.assertEquals('Script-thrown exception', mensaje, 'No se disparo la expcecion');
	}

	@IsTest
	static void debeClonarElContratoConSusItems(){
		Contrato__c contrato = [SELECT ID
		                        FROM Contrato__c
		                        WHERE Estado__c = 'Chegou'];
		Item_del_Contrato__c item = new Item_del_Contrato__c();
		item.Contrato_de_Multiplicacion__c = contrato.Id;
		item.Contrato_de_Multiplicacao_vol__c = contrato.Id;
		item.Contrato_de_Multiplicacion__c = contrato.Id;
		insert item;
		Test.startTest();
		String id = ClonarContratoLightningController.cloneContract(contrato.Id);
		Test.stopTest();
		List<Item_del_Contrato__c> itemClon = [SELECT ID
		                                       FROM Item_del_Contrato__c
		                                       WHERE Contrato_de_Multiplicacion__c = :id];
		System.assertNotEquals(null, id, 'No se clono el contrato');
		System.assertEquals(1, itemClon.size(), 'No se clono el item');
	}

	@isTest
	static void TipodeCotacao_NoPuedeSerCambiado(){
		try{
			Contrato__c contract = [SELECT ID, Tipo_de_Cota_o__c, Name
			                       FROM Contrato__c];
			Item_del_Contrato__c item = new Item_del_Contrato__c();
			item.Contrato_de_Multiplicacion__c = contract.id;
			insert item;

			contract.Tipo_de_Cota_o__c = 'SOJA';
			test.startTest();
			Database.SaveResult updateResult = Database.update(contract);
			test.stopTest();

			Boolean wasUpdated = updateResult.isSuccess();
		} catch (Exception e){
			System.debug('Exception captured: ');
			System.debug(e.getMessage());
			//System.assertEquals(false, wasUpdated);
		}


		
	}
}