Salesforce/main/default/objects/Account/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Estado</label>
    <referenceTo>Estado__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/Account/fields/Gerente_comercial__c.field-meta.xml
<CustomField>
    <fullName>Gerente_comercial__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Gerente comercial</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Gerentes</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/Account/fields/Supervisor__c.field-meta.xml
<CustomField>
    <fullName>Supervisor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supervisor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Supervisores</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/Configuracion_BMX__c/Configuracion_BMX__c.object-meta.xml
<CustomObject>
    <description>Indicador de Parametros.</description>
    <label>Configuracion_BMX</label>
    <nameField>
        <label>Configuracion Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuraciones_BMX</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/Estado__c/Estado__c.object-meta.xml
<CustomObject>
    <label>Estado</label>
    <nameField>
        <label>Nome do Estado</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estados</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/Evento_Royalty__c/Evento_Royalty__c.object-meta.xml
<CustomObject>
    <label>Evento Royalty</label>
    <nameField>
        <label>Nombre de Evento Royalty</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Eventos Royalty</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/Evento_Royalty__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Eventos Royalty</relationshipLabel>
    <relationshipName>Eventos_Royalty</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Salesforce/main/default/main/default/objects/Evento_Royalty__c/fields/Data__c.field-meta.xml
<CustomField>
    <fullName>Data__c</fullName>
    <description>Fecha de evento royalty - Xappia</description>
    <label>Data</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/Evento_Royalty__c/fields/Enviado_para_SAP__c.field-meta.xml
<CustomField>
    <fullName>Enviado_para_SAP__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enviado para SAP</label>
    <type>Checkbox</type>
</CustomField>

Salesforce/main/default/main/default/objects/Evento_Royalty__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pendiente de aprobación</fullName>
                <label>Aprovação pendente</label>
            </value>
            <value>
                <fullName>Aprobado</fullName>
                <label>Aprovado</label>
            </value>
            <value>
                <fullName>Edicion</fullName>
                <default>true</default>
                <label>Edição</label>
            </value>
            <value>
                <fullName>Anulado</fullName>
            </value>
            <value>
                <fullName>Rechazado</fullName>
                <isActive>false</isActive>
                <label>Rechazado</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Evento_Royalty__c/fields/Gerente_comercial__c.field-meta.xml
<CustomField>
    <fullName>Gerente_comercial__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Gerente comercial</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Eventos_Royalty1</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Evento_Royalty__c/fields/Items__c.field-meta.xml
<CustomField>
    <fullName>Items__c</fullName>
    <label>Items</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Placas</fullName>
            </value>
            <value>
                <fullName>Outdoor</fullName>
            </value>
            <value>
                <fullName>Camiseta</fullName>
            </value>
            <value>
                <fullName>Palestrante</fullName>
            </value>
            <value>
                <fullName>Outros</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Evento_Royalty__c/fields/Resposta_SAP__c.field-meta.xml
<CustomField>
    <fullName>Resposta_SAP__c</fullName>
    <label>Resposta SAP</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

Salesforce/main/default/main/default/objects/Evento_Royalty__c/fields/Saldo_por_safra__c.field-meta.xml
<CustomField>
    <fullName>Saldo_por_safra__c</fullName>
    <label>Saldo por safra</label>
    <referenceTo>Saldo_por_safra__c</referenceTo>
    <relationshipLabel>Eventos Royalty</relationshipLabel>
    <relationshipName>Eventos_Royalty</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Salesforce/main/default/objects/Evento_Royalty__c/fields/Supervisor__c.field-meta.xml
<CustomField>
    <fullName>Supervisor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supervisor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Eventos_Royalty</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/Opportunity/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <formula>IF(NOT(ISNULL(Inicio_Cargamento__c)),
			IF(NOT(ISNULL(Inicio_Transporte__c)),
						IF(NOT(ISNULL(Fin_Transporte__c)),
									IF(AND(Confirmado__c,NOT(Solicitacao_de_reembolso__c)),
											&apos;Confirmado&apos;,
											IF(AND(Solicitacao_de_reembolso__c,NOT(Confirmado__c)),
													&apos;Em Troca&apos;,
													&apos;Entregue&apos;)
											),
									&apos;Pedido em trânsito&apos;),
						&apos;Em carregamento&apos;),
			&apos;&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status de transporte</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/Opportunity/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <description>Safra o Campania agricola</description>
    <label>Safra</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>06/07</fullName>
            </value>
            <value>
                <fullName>07/08</fullName>
            </value>
            <value>
                <fullName>08/09</fullName>
            </value>
            <value>
                <fullName>09/10</fullName>
            </value>
            <value>
                <fullName>09/09</fullName>
            </value>
            <value>
                <fullName>10/10</fullName>
            </value>
            <value>
                <fullName>10/11</fullName>
            </value>
            <value>
                <fullName>11/11</fullName>
            </value>
            <value>
                <fullName>11/12</fullName>
            </value>
            <value>
                <fullName>12/12</fullName>
            </value>
            <value>
                <fullName>12/13</fullName>
            </value>
            <value>
                <fullName>13/14</fullName>
            </value>
            <value>
                <fullName>14/15</fullName>
            </value>
            <value>
                <fullName>15/16</fullName>
            </value>
            <value>
                <fullName>16/17</fullName>
            </value>
            <value>
                <fullName>17/18</fullName>
            </value>
            <value>
                <fullName>18/19</fullName>
            </value>
            <value>
                <fullName>19/20</fullName>
            </value>
            <value>
                <fullName>20/21</fullName>
            </value>
            <value>
                <fullName>21/22</fullName>
                <default>true</default>
                <label>21/22</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Opportunity/fields/Saldo_por_safra__c.field-meta.xml
<CustomField>
    <fullName>Saldo_por_safra__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relacion al saldo con el safra actual</description>
    <label>Saldo por safra</label>
    <referenceTo>Saldo_por_safra__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Opportunity/fields/Supervisor__c.field-meta.xml
<CustomField>
    <fullName>Supervisor__c</fullName>
    <formula>IF(ISPICKVAL(Marca__c, &apos;BRMX&apos;),  RIGHT(TEXT(Account.Responsavel__c), LEN(TEXT(Account.Responsavel__c)) - 6), 
IF(ISPICKVAL(Marca__c, &apos;DSEM&apos;),  RIGHT(TEXT(Account.Reponsavel_DSEM__c), LEN(TEXT(Account.Reponsavel_DSEM__c)) - 6),
RIGHT(TEXT(Account.Responsavel_NEOGEN__c), LEN(TEXT(Account.Responsavel_NEOGEN__c)) - 6)))</formula>
    <label>Supervisor</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/Opportunity/recordTypes/Pendiente.recordType-meta.xml
<RecordType>
    <fullName>Pendiente</fullName>
    <active>true</active>
    <businessProcess>Nota de Venta - Pendiente</businessProcess>
    <label>Pendiente</label>
</RecordType>

Salesforce/main/default/main/default/objects/OpportunityLineItem/fields/Data__c.field-meta.xml
<CustomField>
    <fullName>Data__c</fullName>
    <label>Data</label>
    <type>Date</type>
</CustomField>

Salesforce/main/default/main/default/objects/OpportunityLineItem/fields/Descuento__c.field-meta.xml
<CustomField>
    <fullName>Descuento__c</fullName>
    <label>Descuento</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/main/default/objects/OpportunityLineItem/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Estado</label>
    <referenceTo>Estado__c</referenceTo>
    <relationshipLabel>Producto de oportunidad (Estado)</relationshipLabel>
    <relationshipName>Producto_de_oportunidad2</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/OpportunityLineItem/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <formula>TEXT(Opportunity.Safra__c)</formula>
    <label>Safra</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/Product2/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/main/default/objects/Saldo_por_safra__c/Saldo_por_safra__c.object-meta.xml
<CustomObject>
    <label>Saldo por safra</label>
    <nameField>
        <label>Nombre de Saldo por safra</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Saldos por safra</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Salesforce/main/default/objects/Saldo_por_safra__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Activo</fullName>
            </value>
            <value>
                <fullName>Inactivo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Saldo_por_safra__c/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <label>Safra</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/Saldo_por_safra__c/fields/Saldo__c.field-meta.xml
<CustomField>
    <fullName>Saldo__c</fullName>
    <label>Saldo Inicial</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Salesforce/main/default/main/default/objects/Saldo_por_safra__c/fields/Saldo_Disponible__c.field-meta.xml
<CustomField>
    <fullName>Saldo_Disponible__c</fullName>
    <formula>Saldo__c - Saldo_Gastado__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Saldo Disponível</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Salesforce/main/default/main/default/objects/Saldo_por_safra__c/fields/Saldo_Gastado__c.field-meta.xml
<CustomField>
    <fullName>Saldo_Gastado__c</fullName>
    <label>Saldo Utilizado</label>
    <summarizedField>Evento_Royalty__c.Valor__c</summarizedField>
    <summaryFilterItems>
        <field>Evento_Royalty__c.Estado__c</field>
        <operation>equals</operation>
        <value>Aprobado</value>
    </summaryFilterItems>
    <summaryForeignKey>Evento_Royalty__c.Saldo_por_safra__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

Salesforce/main/default/classes/EventoRoyaltyTriggerTest.cls
@isTest
public class EventoRoyaltyTriggerTest  {
	
	//Se agrego static para evitar problema con Too many SOQL queries: 101
	static{
		Test.setMock(WebServiceMock.class, new CrearFacturaSoapMOCK.CrearFacturaSoapSuccessfullyMOCK());
	}

	@TestSetup
	public static void setup(){
		Account acc = new Account(Name='Conta');
		acc.Supervisor__c = UserInfo.getUserId();
		acc.Gerente_comercial__c = UserInfo.getUserId();
        insert acc;

		Product2 prod = Build.aProduct2().
            withName('Test product2').
            withCategoria('BASICA').
            withFamily('Royalty x Basica').
            withPrice(40).
            withIsActive(true).
            build();
        insert prod;

		Pricebook2 pricebook = new Pricebook2();
        pricebook.Name = 'Lista de precios estándar';
        insert pricebook;

		PricebookEntry pbe = Build.aPricebookEntry().
            withPricebook2Id(Test.getStandardPricebookId()).
            withUnitPrice(58).
            withProduct2Id(prod).
            withIsActive(true).
            build();
        insert pbe;

		Configuracion_BMX__c testConfiguracionBMX = Build.aConfiguracionBMX().
            withPMSafraActualA1('18/19').
            build();
        insert testConfiguracionBMX;

		Saldo_por_safra__c saldoPorSafra = Build.aSaldoPorSafra().
		withAccount(acc).
		withSafra('18/19').

		build();
		insert saldoPorSafra;

		Opportunity opp = Build.anOpportunityAnexoIII().withSafra('18/19').withAccountId(acc).withPricebook2Id(Test.getStandardPricebookId()).build();
		insert opp;

		List<OpportunityLineItem> items = new List<OpportunityLineItem>();
		for(Integer i = 0; i < 10; i++) {
			OpportunityLineItem item = new OpportunityLineItem();
			item.OpportunityId = opp.Id;
			item.Quantity = 10;
			item.Product2Id = prod.Id;
			item.Descuento__c = 10;
			item.TotalPrice = item.Quantity * prod.Price__c;
			item.PricebookEntryId = pbe.Id;
			items.add(item);
		}
		insert items;
		opp.StageName = 'Aprobada';
		update opp;
	}

	@IsTest
	public static void eventoRoyaltyRestaSaldo() {
		Evento_Royalty__c evento = new Evento_Royalty__c();
		evento.Cuenta__c = [SELECT Id FROM Account].Id;
		evento.Saldo_por_safra__c = [SELECT Id FROM Saldo_por_safra__c].Id;
		evento.Safra__c = '18/19';
		evento.Data__c = '22/01/2020';
		evento.Items__c = 'Placas';
		evento.Valor__c = 1000.00;
		evento.Estado__c = 'Aprobado';


		Test.startTest();
		insert evento;
		Test.stopTest();

		Saldo_por_safra__c saldo = [SELECT Id,Saldo__c, Saldo_Disponible__c, Saldo_Gastado__c 
									FROM Saldo_por_safra__c];

		System.assertEquals(evento.Valor__c, saldo.Saldo_Gastado__c);
	}

	@IsTest
	public static void eventoRoyaltiesRestaSaldo() {
		List<Evento_Royalty__c> eventos = new List<Evento_Royalty__c>();
		Double total = 0;
		for(Integer i = 0; i < 3; i++) {
			Evento_Royalty__c evento = new Evento_Royalty__c();
			evento.Cuenta__c = [SELECT Id FROM Account].Id;
			evento.Saldo_por_safra__c = [SELECT Id FROM Saldo_por_safra__c].Id;
			evento.Safra__c = '18/19';
			evento.Data__c = '22/01/2020';
			evento.Items__c = 'Placas';
			evento.Valor__c = 1000.00;
			evento.Estado__c = 'Aprobado';
			total += evento.Valor__c;
			eventos.add(evento);
		}

		Test.startTest();
		insert eventos;
		Test.stopTest();

		Saldo_por_safra__c saldo = [SELECT Id,Saldo__c, Saldo_Disponible__c, Saldo_Gastado__c 
									FROM Saldo_por_safra__c];

		System.assertEquals(total, saldo.Saldo_Gastado__c);
	}

	@IsTest
	public static void revisarSaldoPorEventoPendiente() {
		Evento_Royalty__c evento = new Evento_Royalty__c();
		evento.Cuenta__c = [SELECT Id FROM Account].Id;
		evento.Saldo_por_safra__c = [SELECT Id FROM Saldo_por_safra__c].Id;
		evento.Safra__c = '18/19';
		evento.Data__c = '22/01/2020';
		evento.Items__c = 'Placas';
		evento.Valor__c = 1000.00;
		evento.Estado__c = 'Pendiente de aprobación';
		
		insert evento;
		
		Evento_Royalty__c evento2 = new Evento_Royalty__c();
		evento2.Cuenta__c = [SELECT Id FROM Account].Id;
		evento2.Saldo_por_safra__c = [SELECT Id FROM Saldo_por_safra__c].Id;
		evento2.Safra__c = '18/19';
		evento2.Data__c = '22/01/2020';
		evento2.Items__c = 'Placas';
		evento2.Valor__c = 1000.00;
		evento2.Estado__c = 'Pendiente de aprobación';

		Test.startTest();

		try {
			insert evento2;
		}
		catch(Exception e) {
			System.debug(e.getMessage());
		}

		Test.stopTest();

		List<Evento_Royalty__c> eventos = [SELECT Id FROM Evento_Royalty__c];
		System.assertEquals(1, eventos.size(), 'No deberia insertarse el segundo evento');

	}

	// @IsTest
	// public static void siSeApruebaEventoRoyalty_llamaAsyncCrearFacturaSoap() {
	// 	//Inicialización y carga de datos
	// 	Evento_Royalty__c evento = new Evento_Royalty__c();
	// 	evento.Cuenta__c = [SELECT Id FROM Account].Id;
	// 	evento.Saldo_por_safra__c = [SELECT Id FROM Saldo_por_safra__c].Id;
	// 	evento.Safra__c = '18/19';
	// 	evento.Data__c = '22/01/2020';
	// 	evento.Items__c = 'Placas';
	// 	evento.Valor__c = 1000.00;
	// 	evento.Estado__c = 'Aprobado';

	// 	//Test
	// 	Test.startTest();
	// 	insert evento;
	// 	Test.stopTest();

	// 	//ASSERTS
	// 	evento = [
	// 		SELECT Resposta_SAP__c,Enviado_para_SAP__c 
	// 		FROM Evento_Royalty__c 
	// 		WHERE Id = :evento.id
	// 	];
	// 	System.assertEquals( 1 , EventoRoyaltyTriggerHelper.cantLlamadas );
	// 	System.assertEquals( 'Mock response' , evento.Resposta_SAP__c);
	// 	System.assertEquals( true , evento.Enviado_para_SAP__c);
		
	// }
}