Salesforce/main/default/objects/Account/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Estado</label>
    <referenceTo>Estado__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/Account/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Marca</valueSetName>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Account/fields/Obtentor__c.field-meta.xml
<CustomField>
    <fullName>Obtentor__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Campo utilizado sólo por el administrador. Todas las Sociedades que están en los productos deben tener la cuenta marcada con Obtentor = true</description>
    <inlineHelpText>Campo utilizado sólo por el administrador. Todas las Sociedades que están en los productos deben tener la cuenta marcada con Obtentor = true</inlineHelpText>
    <label>Obtentor</label>
    <type>Checkbox</type>
</CustomField>

Salesforce/main/default/main/default/objects/Area_Plantada__c/Area_Plantada__c.object-meta.xml
<CustomObject>
    <label>Área Plantada</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Código Area Plantada</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Áreas Plantadas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/Area_Plantada__c/fields/Especie__c.field-meta.xml
<CustomField>
    <fullName>Especie__c</fullName>
    <label>Especie</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Soja</fullName>
            </value>
            <value>
                <fullName>Milho</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Area_Plantada__c/fields/Municipio__c.field-meta.xml
<CustomField>
    <fullName>Municipio__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Municipio</label>
    <referenceTo>Cidade__c</referenceTo>
    <relationshipLabel>Áreas Plantadas</relationshipLabel>
    <relationshipName>Areas_Plantadas</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Cidade__c/Cidade__c.object-meta.xml
<CustomObject>
    <label>Ciudad</label>
    <nameField>
        <label>Nome da Cidade</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ciudades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/Cidade__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Estado</label>
    <referenceTo>Estado__c</referenceTo>
    <relationshipName>Cidades</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/Cidade__c/fields/GeoCod_municipio__c.field-meta.xml
<CustomField>
    <fullName>GeoCod_municipio__c</fullName>
    <label>GeoCod Municipio</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/Cidade__c/fields/Mesorregion__c.field-meta.xml
<CustomField>
    <fullName>Mesorregion__c</fullName>
    <label>Mesorregião</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/Configuracion_BMX__c/Configuracion_BMX__c.object-meta.xml
<CustomObject>
    <description>Indicador de Parametros.</description>
    <label>Configuracion_BMX</label>
    <nameField>
        <label>Configuracion Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuraciones_BMX</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/Configuracion_BMX__c/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BRMX</fullName>
                <default>true</default>
                <label>BRMX</label>
            </value>
            <value>
                <fullName>DSEM</fullName>
            </value>
            <value>
                <fullName>NEOG</fullName>
            </value>
            <value>
                <fullName>DAGMA</fullName>
            </value>
            <value>
                <fullName>LICENÇAS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/CRM_Calendario_de_Eventos__c/CRM_Calendario_de_Eventos__c.object-meta.xml
<CustomObject>
    <description>Registro de eventos programados pelo Multiplicador</description>
    <label>CRM Evento</label>
    <nameField>
        <label>Nome de CRM Evento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Eventos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/objects/CRM_Calendario_de_Eventos__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Conta multiplicador, que realizou ou eventos agendados</description>
    <inlineHelpText>Conta multiplicador, que realizou ou eventos agendados</inlineHelpText>
    <label>Nome da conta</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Agricultor__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Eventos (Cuenta)</relationshipLabel>
    <relationshipName>CRM_Calend_rio_de_eventos</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/CRM_Calendario_de_Eventos__c/fields/Data__c.field-meta.xml
<CustomField>
    <fullName>Data__c</fullName>
    <description>Data do evento</description>
    <inlineHelpText>Data do evento</inlineHelpText>
    <label>Data</label>
    <type>Date</type>
</CustomField>

Salesforce/main/default/objects/CRM_Calendario_de_Eventos__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <description>Nome do Estado</description>
    <formula>Municipio__r.Estado__r.Name</formula>
    <inlineHelpText>Nome do Estado</inlineHelpText>
    <label>Estado</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/CRM_Calendario_de_Eventos__c/fields/Fase__c.field-meta.xml
<CustomField>
    <fullName>Fase__c</fullName>
    <label>Fase</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Edição</fullName>
            </value>
            <value>
                <fullName>Aguardando validação dados de plantio</fullName>
            </value>
            <value>
                <fullName>Edição de dados de colheita</fullName>
            </value>
            <value>
                <fullName>Aguardando resultado de colheita</fullName>
            </value>
            <value>
                <fullName>Aguardando validação dados de colheita</fullName>
            </value>
            <value>
                <fullName>Pendente</fullName>
            </value>
            <value>
                <fullName>Aprovado</fullName>
                <default>true</default>
                <label>Aprovado</label>
            </value>
            <value>
                <fullName>Reprovado</fullName>
            </value>
            <value>
                <fullName>Anulado</fullName>
            </value>
            <value>
                <fullName>Edição de dados de plantio</fullName>
            </value>
            <value>
                <fullName>Reprovado Colheita</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/CRM_Calendario_de_Eventos__c/fields/Municipio__c.field-meta.xml
<CustomField>
    <fullName>Municipio__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Evento município</description>
    <inlineHelpText>Evento município</inlineHelpText>
    <label>Cidade</label>
    <referenceTo>Cidade__c</referenceTo>
    <relationshipName>CRM_Calend_rio_de_eventos</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/CRM_Calendario_de_Eventos__c/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <label>Safra</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>11/12</fullName>
            </value>
            <value>
                <fullName>12/13</fullName>
            </value>
            <value>
                <fullName>17/18</fullName>
            </value>
            <value>
                <fullName>18/19</fullName>
            </value>
            <value>
                <fullName>19/20</fullName>
            </value>
            <value>
                <fullName>20/21</fullName>
            </value>
            <value>
                <fullName>21/22</fullName>
                <default>true</default>
                <label>21/22</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/CRM_Detalle_Calendario_de_eventos__c/CRM_Detalle_Calendario_de_eventos__c.object-meta.xml
<CustomObject>
    <label>CRM Detalle Calendário de eventos</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Nombre de CRM Detalle Calendário de even</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CRM Detalles Calendário de eventos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Salesforce/main/default/objects/CRM_Detalle_Calendario_de_eventos__c/fields/CRM_Calendario_de_eventos__c.field-meta.xml
<CustomField>
    <fullName>CRM_Calendario_de_eventos__c</fullName>
    <label>CRM Calendário de eventos</label>
    <referenceTo>CRM_Calendario_de_Eventos__c</referenceTo>
    <relationshipLabel>Itens</relationshipLabel>
    <relationshipName>CRM_Detalles_Calend_rio_de_eventos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Salesforce/main/default/main/default/objects/CRM_Detalle_Calendario_de_eventos__c/fields/Obtentor__c.field-meta.xml
<CustomField>
    <fullName>Obtentor__c</fullName>
    <label>Obtentor</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/Estado__c/Estado__c.object-meta.xml
<CustomObject>
    <label>Estado</label>
    <nameField>
        <label>Nome do Estado</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estados</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/objects/Estado__c/fields/Estado_de_Origem__c.field-meta.xml
<CustomField>
    <fullName>Estado_de_Origem__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Este campo indica si el estado es estado de Origen.</description>
    <label>Estado de Origem?</label>
    <type>Checkbox</type>
</CustomField>

Salesforce/main/default/main/default/objects/Product2/fields/Especie__c.field-meta.xml
<CustomField>
    <fullName>Especie__c</fullName>
    <label>Especie</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Soja</fullName>
                <label>SOJA</label>
            </value>
            <value>
                <fullName>Milho</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Product2/fields/Obtentor__c.field-meta.xml
<CustomField>
    <fullName>Obtentor__c</fullName>
    <description>Lista de Obtentores que debemos mantener(admin)</description>
    <inlineHelpText>Lista de Obtentores que debemos mantener(admin)</inlineHelpText>
    <label>Obtentor</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ADVANTA</fullName>
            </value>
            <value>
                <fullName>Agrária</fullName>
            </value>
            <value>
                <fullName>Agroeste</fullName>
            </value>
            <value>
                <fullName>AGROMEN</fullName>
            </value>
            <value>
                <fullName>Agro Norte</fullName>
            </value>
            <value>
                <fullName>Avanti Seeds</fullName>
            </value>
            <value>
                <fullName>Basf</fullName>
            </value>
            <value>
                <fullName>Bayer</fullName>
            </value>
            <value>
                <fullName>Brasmax</fullName>
            </value>
            <value>
                <fullName>BREVANT</fullName>
            </value>
            <value>
                <fullName>Br Genetica</fullName>
            </value>
            <value>
                <fullName>CARAIBA</fullName>
            </value>
            <value>
                <fullName>CCGL Tecnología</fullName>
            </value>
            <value>
                <fullName>Coodetec</fullName>
            </value>
            <value>
                <fullName>CORDIUS</fullName>
            </value>
            <value>
                <fullName>CPTA</fullName>
            </value>
            <value>
                <fullName>Credenz</fullName>
            </value>
            <value>
                <fullName>CTP</fullName>
            </value>
            <value>
                <fullName>CTPA/Emgopa</fullName>
            </value>
            <value>
                <fullName>DM Licenças</fullName>
            </value>
            <value>
                <fullName>Don Mario</fullName>
            </value>
            <value>
                <fullName>Dow</fullName>
            </value>
            <value>
                <fullName>Embrapa</fullName>
            </value>
            <value>
                <fullName>FMT</fullName>
            </value>
            <value>
                <fullName>FPS</fullName>
            </value>
            <value>
                <fullName>FT</fullName>
            </value>
            <value>
                <fullName>Fundacep</fullName>
            </value>
            <value>
                <fullName>GDML</fullName>
            </value>
            <value>
                <fullName>Genetica Soy</fullName>
            </value>
            <value>
                <fullName>Geneze</fullName>
            </value>
            <value>
                <fullName>Syngenta</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/globalValueSets/Marca.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BRMX</fullName>
    </customValue>
    <customValue>
        <fullName>DSEM</fullName>
    </customValue>
    <customValue>
        <fullName>NEOG</fullName>
    </customValue>
    <customValue>
        <fullName>DAGMA</fullName>
    </customValue>
    <customValue>
        <fullName>LICENÇAS</fullName>
    </customValue>
    <masterLabel>Marca</masterLabel>
</GlobalValueSet>

Salesforce/main/default/classes/approvalButtonCRMEventoControllerTest.cls
@isTest
private class approvalButtonCRMEventoControllerTest {

    @TestSetup static void setup() {
        Configuracion_BMX__c testConfiguracionBMX = Build.aConfiguracionBMX()
        .withPMSafraActualEventos('18/19')
        .build();

        insert testConfiguracionBMX;

        Account account = Build.anAccount()
            .withName('JERE')
            .withNomefantasia('JRERE')
            .withResponsavel('061 - Fernando Frehner')
            .withType('Multiplicador')
            .build();

        insert account;

        Product2[] products = new Product2[]{
            new Product2(Name = 'Outro', Especie__c = 'SOJA', Obtentor__c = 'ADVANTA'),
            new Product2(Name = '68i69RSF IPRO', Especie__c = 'TRIGO', Obtentor__c = 'Don Mario'),
            new Product2(Name = 'SYN 1359S IPRO', Especie__c = 'SOJA', Obtentor__c = 'Syngenta')
        };

        insert products;

        Estado__c estado = new Estado__c(
            Name = 'SP',
            Mostrar_en_portal__c = true,
            Estado_de_Origem__c = true
        );

        insert estado;

        Cidade__c ciudad = new Cidade__c(
            Name = 'ADAMANTINA',
            GeoCod_municipio__c = '3500105',
            Mesorregion__c = 'PRESIDENTE PRUDENTE',
            Estado__c = estado.Id
        );

        insert ciudad;

        CRM_Calendario_de_Eventos__c crmEvento = new CRM_Calendario_de_Eventos__c(
            Data__c = Date.today(),
            Cuenta__c = account.id,
            RecordTypeId = [SELECT Id FROM RecordType WHERE DeveloperName = 'Test_a_campo'].Id,
            Safra__c = '18/19',
            Marca__c = 'NEOG',
            Fase__c = 'Edição',
            Municipio__c = ciudad.Id,
            Realizado_por__c = 'Multiplicador'
        );

        insert crmEvento;

        CRM_Detalle_Calendario_de_eventos__c detalleCRMEvento = new CRM_Detalle_Calendario_de_eventos__c(
            CRM_Calendario_de_eventos__c = crmEvento.Id,
            Obtentor__c = 'ADVANTA',
            Cultivar__c = products[0].Id,
            Data_de_colheita__c = Date.today().addDays(-30),
            Data_de_plantio__c = Date.today().addDays(30),
            Area_Colhida__c = 3.5,
            Area_Plantada__c = 3.5,
            Produtividade__c = 500,
            Volume_Doado__c = 5.0,
            Populacao_de_plantas__c = 5.5,
            Espacamento__c = 5.5,
            Cultura_antecessora__c = 'Ervilhaca',
            Produto_Principal__c = true
        );

        insert detalleCRMEvento;

        ContentVersion contentVersion = new ContentVersion(
            Title = 'picture 1',
            PathOnClient = 'pic_1.jpg',
            VersionData = Blob.valueOf('Test Content 1'),
            IsMajorVersion = true
        );

        insert contentVersion;

        List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];

        ContentDocumentLink cdl = new ContentDocumentLink(
            LinkedEntityId = crmEvento.Id,
            ContentDocumentId = documents[0].Id,
            ShareType = 'V',
            Visibility = 'AllUsers'
        );

        insert cdl;
    }

    @isTest static void getItemsTest() {
        CRM_Calendario_de_Eventos__c crmEvento = [SELECT Id FROM CRM_Calendario_de_Eventos__c];
        List<CRM_Detalle_Calendario_de_eventos__c> result = null;

        Test.startTest();
        result = approvalButtonCRMEventoController.getItems(crmEvento.Id);
        System.assertEquals(1, result.size());

        insert new CRM_Detalle_Calendario_de_eventos__c(
            CRM_Calendario_de_eventos__c = crmEvento.Id,
            Obtentor__c = 'Don Mario',
            Cultivar__c = [SELECT Id FROM Product2 WHERE Name = '68i69RSF IPRO'].Id,
            Data_de_colheita__c = Date.today().addDays(-25),
            Data_de_plantio__c = Date.today().addDays(35),
            Area_Colhida__c = 3.3,
            Area_Plantada__c = 3.3,
            Produtividade__c = 300,
            Volume_Doado__c = 2.5,
            Populacao_de_plantas__c = 4.5,
            Espacamento__c = 4.5,
            Cultura_antecessora__c = 'Ervilhaca'
        );

        result = approvalButtonCRMEventoController.getItems(crmEvento.Id);
        System.assertEquals(2, result.size());
        Test.stopTest();
    }

    @isTest static void countNumberOfDocumentsTest() {
        CRM_Calendario_de_Eventos__c crmEvento = [SELECT Id FROM CRM_Calendario_de_Eventos__c];
        AggregateResult result = null;

        Test.startTest();
        result = approvalButtonCRMEventoController.countNumberOfDocuments(crmEvento.Id);
        System.assertEquals(1, result.get('Total'));

        ContentVersion contentVersion = new ContentVersion(
            Title = 'picture 2',
            PathOnClient = 'pic_2.jpg',
            VersionData = Blob.valueOf('Test Content 2'),
            IsMajorVersion = true
        );

        insert contentVersion;

        List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];

        ContentDocumentLink cdl = new ContentDocumentLink(
            LinkedEntityId = crmEvento.Id,
            ContentDocumentId = documents[1].Id,
            ShareType = 'V',
            Visibility = 'AllUsers'
        );

        insert cdl;

        result = approvalButtonCRMEventoController.countNumberOfDocuments(crmEvento.Id);
        System.assertEquals(2, result.get('Total'));
        Test.stopTest();
    }

    @isTest static void sendApprovalRequestTest() {
        CRM_Calendario_de_Eventos__c crmEvento = [SELECT Id, OwnerId FROM CRM_Calendario_de_Eventos__c];

        Test.startTest();
        Boolean result = approvalButtonCRMEventoController.sendApprovalRequest(crmEvento.Id, crmEvento.OwnerId);

        System.assert(result);

        ProcessInstance[] processInstances = [SELECT Id, TargetObjectId FROM ProcessInstance WHERE TargetObjectId = :crmEvento.Id];

        System.assertEquals(1, processInstances.size());
        Test.stopTest();
    }
}