Salesforce/main/default/objects/Account/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Estado</label>
    <referenceTo>Estado__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/Account/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Marca</valueSetName>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Account/fields/Multiplicador__c.field-meta.xml
<CustomField>
    <fullName>Multiplicador__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Multiplicador</label>
    <type>Checkbox</type>
</CustomField>

Salesforce/main/default/objects/Account/fields/Nome_fantasia__c.field-meta.xml
<CustomField>
    <fullName>Nome_fantasia__c</fullName>
    <label>Nome fantasia</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/Account/fields/Region_Comercial__c.field-meta.xml
<CustomField>
    <fullName>Region_Comercial__c</fullName>
    <formula>TEXT(Region__r.Region_Comercial__c)</formula>
    <label>Região Comercial</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/Account/fields/Safras__c.field-meta.xml
<CustomField>
    <fullName>Safras__c</fullName>
    <label>Safras</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Safra</valueSetName>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Contract/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Marca</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/Contract/fields/Region_Comercial__c.field-meta.xml
<CustomField>
    <fullName>Region_Comercial__c</fullName>
    <label>Regiao Comercial</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/Contract/fields/Safras__c.field-meta.xml
<CustomField>
    <fullName>Safras__c</fullName>
    <label>Safras</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>16/17</fullName>
            </value>
            <value>
                <fullName>17/18</fullName>
            </value>
            <value>
                <fullName>18/19</fullName>
            </value>
            <value>
                <fullName>19/20</fullName>
            </value>
            <value>
                <fullName>20/21</fullName>
            </value>
            <value>
                <fullName>21/22</fullName>
            </value>
            <value>
                <fullName>22/23</fullName>
            </value>
            <value>
                <fullName>23/24</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Contract/fields/Sociedad__c.field-meta.xml
<CustomField>
    <fullName>Sociedad__c</fullName>
    <label>Sociedad</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Marca</valueSetName>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Contrato__c/Contrato__c.object-meta.xml
<CustomObject>
    <description>CONTRATO DE LICENCIAMENTO PARA MULTIPLICAÇÃO E COMERCIALIZAÇÃO</description>
    <label>Contrato de Multiplicação</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Numero do Contrato de Multiplicação</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contratos de Multiplicação</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/Contrato__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Edição</fullName>
                <default>true</default>
                <label>Edição</label>
            </value>
            <value>
                <fullName>Pendente de Aprovação</fullName>
            </value>
            <value>
                <fullName>Aguardando Assinatura</fullName>
            </value>
            <value>
                <fullName>Pendente de Impressão</fullName>
            </value>
            <value>
                <fullName>Pendente de Envio</fullName>
            </value>
            <value>
                <fullName>Pendente de Postagem</fullName>
            </value>
            <value>
                <fullName>Aguarda Retorno</fullName>
            </value>
            <value>
                <fullName>Chegou</fullName>
            </value>
            <value>
                <fullName>Inutilizado</fullName>
            </value>
            <value>
                <fullName>Anulado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Contrato__c/fields/Estados_Comercializacao__c.field-meta.xml
<CustomField>
    <fullName>Estados_Comercializacao__c</fullName>
    <label>Estados de Comercialização</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AC</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AM</fullName>
            </value>
            <value>
                <fullName>AP</fullName>
            </value>
            <value>
                <fullName>BA</fullName>
            </value>
            <value>
                <fullName>CE</fullName>
            </value>
            <value>
                <fullName>DF</fullName>
            </value>
            <value>
                <fullName>ES</fullName>
            </value>
            <value>
                <fullName>GO</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MG</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>PA</fullName>
            </value>
            <value>
                <fullName>Paraguai</fullName>
            </value>
            <value>
                <fullName>PB</fullName>
            </value>
            <value>
                <fullName>PE</fullName>
            </value>
            <value>
                <fullName>PI</fullName>
            </value>
            <value>
                <fullName>PR</fullName>
            </value>
            <value>
                <fullName>RJ</fullName>
            </value>
            <value>
                <fullName>RN</fullName>
            </value>
            <value>
                <fullName>RO</fullName>
            </value>
            <value>
                <fullName>RR</fullName>
            </value>
            <value>
                <fullName>RS</fullName>
            </value>
            <value>
                <fullName>SC</fullName>
            </value>
            <value>
                <fullName>SE</fullName>
            </value>
            <value>
                <fullName>SP</fullName>
            </value>
            <value>
                <fullName>TO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Contrato__c/fields/Multiplicador__c.field-meta.xml
<CustomField>
    <fullName>Multiplicador__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Conta do multiplicador</description>
    <label>Multiplicador</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Contrato_de_Multiplica_o</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Contrato__c/fields/Nome_Fantasia__c.field-meta.xml
<CustomField>
    <fullName>Nome_Fantasia__c</fullName>
    <formula>Multiplicador__r.Nome_fantasia__c</formula>
    <label>Nome Fantasia Multiplicador</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/Contrato__c/fields/Region_Comercial__c.field-meta.xml
<CustomField>
    <fullName>Region_Comercial__c</fullName>
    <label>Região Comercial</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>REGION 1</fullName>
            </value>
            <value>
                <fullName>REGION 2</fullName>
            </value>
            <value>
                <fullName>CERRADO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Contrato__c/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <label>Safra</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>17/18</fullName>
                <default>true</default>
                <label>17/18</label>
            </value>
            <value>
                <fullName>18/19</fullName>
            </value>
            <value>
                <fullName>19/20</fullName>
            </value>
            <value>
                <fullName>20/21</fullName>
            </value>
            <value>
                <fullName>21/22</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Contrato__c/fields/Sociedad__c.field-meta.xml
<CustomField>
    <fullName>Sociedad__c</fullName>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BRMX</fullName>
            </value>
            <value>
                <fullName>DSEM</fullName>
            </value>
            <value>
                <fullName>NEOG</fullName>
            </value>
            <value>
                <fullName>DAGMA</fullName>
            </value>
            <value>
                <fullName>LICENÇAS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Contrato__c/recordTypes/BRMX.recordType-meta.xml
<RecordType>
    <fullName>BRMX</fullName>
    <active>true</active>
    <description>Contratos de la sociedad BRASMAX</description>
    <label>BRMX</label>
</RecordType>

Salesforce/main/default/main/default/objects/Opportunity/fields/Anexo_Relacionado__c.field-meta.xml
<CustomField>
    <fullName>Anexo_Relacionado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Anexo Relacionado</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Oportunidades (Anexo Relacionado)</relationshipLabel>
    <relationshipName>Oportunidades2</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/Opportunity/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <description>Identifica la marca para las Oportunidades del Circuito de Anexos. Se selecciona la lista de precios en función de este campo</description>
    <inlineHelpText>Identificar a marca de Oportunidades Circuito Anexos. Você seleciona a lista de preços com base neste campo</inlineHelpText>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BRMX</fullName>
            </value>
            <value>
                <fullName>DSEM</fullName>
            </value>
            <value>
                <fullName>NEOG</fullName>
            </value>
            <value>
                <fullName>DAGMA</fullName>
            </value>
            <value>
                <fullName>LICENÇAS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Opportunity/fields/Region_Comercial__c.field-meta.xml
<CustomField>
    <fullName>Region_Comercial__c</fullName>
    <formula>TEXT(Account.Region__r.Region_Comercial__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Region Comercial</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/Opportunity/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <description>Safra o Campania agricola</description>
    <label>Safra</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>06/07</fullName>
            </value>
            <value>
                <fullName>07/08</fullName>
            </value>
            <value>
                <fullName>08/09</fullName>
            </value>
            <value>
                <fullName>09/10</fullName>
            </value>
            <value>
                <fullName>09/09</fullName>
            </value>
            <value>
                <fullName>10/10</fullName>
            </value>
            <value>
                <fullName>10/11</fullName>
            </value>
            <value>
                <fullName>11/11</fullName>
            </value>
            <value>
                <fullName>11/12</fullName>
            </value>
            <value>
                <fullName>12/12</fullName>
            </value>
            <value>
                <fullName>12/13</fullName>
            </value>
            <value>
                <fullName>13/14</fullName>
            </value>
            <value>
                <fullName>14/15</fullName>
            </value>
            <value>
                <fullName>15/16</fullName>
            </value>
            <value>
                <fullName>16/17</fullName>
            </value>
            <value>
                <fullName>17/18</fullName>
            </value>
            <value>
                <fullName>18/19</fullName>
            </value>
            <value>
                <fullName>19/20</fullName>
            </value>
            <value>
                <fullName>20/21</fullName>
            </value>
            <value>
                <fullName>21/22</fullName>
                <default>true</default>
                <label>21/22</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Opportunity/fields/Sociedad__c.field-meta.xml
<CustomField>
    <fullName>Sociedad__c</fullName>
    <label>Sociedad</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/Opportunity/recordTypes/Comercial.recordType-meta.xml
<RecordType>
    <fullName>Comercial</fullName>
    <active>true</active>
    <businessProcess>Control_Multiplicador</businessProcess>
    <description>Detalle de lo que el multiplicador va a vender: relatorio de venda</description>
    <label>Comercial</label>
</RecordType>

Salesforce/main/default/main/default/objects/Opportunity/recordTypes/Pendiente.recordType-meta.xml
<RecordType>
    <fullName>Pendiente</fullName>
    <active>true</active>
    <businessProcess>Nota de Venta - Pendiente</businessProcess>
    <label>Pendiente</label>
</RecordType>

Salesforce/main/default/globalValueSets/Marca.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BRMX</fullName>
    </customValue>
    <customValue>
        <fullName>DSEM</fullName>
    </customValue>
    <customValue>
        <fullName>NEOG</fullName>
    </customValue>
    <customValue>
        <fullName>DAGMA</fullName>
    </customValue>
    <customValue>
        <fullName>LICENÇAS</fullName>
    </customValue>
    <masterLabel>Marca</masterLabel>
</GlobalValueSet>

Salesforce/main/default/globalValueSets/Safra.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>14/15</fullName>
    </customValue>
    <customValue>
        <fullName>15/16</fullName>
    </customValue>
    <customValue>
        <fullName>16/17</fullName>
    </customValue>
    <customValue>
        <fullName>17/18</fullName>
    </customValue>
    <customValue>
        <fullName>18/19</fullName>
    </customValue>
    <customValue>
        <fullName>19/20</fullName>
    </customValue>
    <customValue>
        <fullName>20/21</fullName>
    </customValue>
    <customValue>
        <fullName>21/22</fullName>
    </customValue>
    <customValue>
        <fullName>22/23</fullName>
    </customValue>
    <customValue>
        <fullName>23/24</fullName>
    </customValue>
    <customValue>
        <fullName>08/09</fullName>
        <isActive>false</isActive>
        <label>08/09</label>
    </customValue>
    <customValue>
        <fullName>07/08</fullName>
        <isActive>false</isActive>
        <label>07/08</label>
    </customValue>
    <customValue>
        <fullName>10/11</fullName>
        <isActive>false</isActive>
        <label>10/11</label>
    </customValue>
    <customValue>
        <fullName>11/12</fullName>
        <isActive>false</isActive>
        <label>11/12</label>
    </customValue>
    <customValue>
        <fullName>12/13</fullName>
        <isActive>false</isActive>
        <label>12/13</label>
    </customValue>
    <customValue>
        <fullName>13/14</fullName>
        <isActive>false</isActive>
        <label>13/14</label>
    </customValue>
    <customValue>
        <fullName>09/10</fullName>
        <isActive>false</isActive>
        <label>09/10</label>
    </customValue>
    <masterLabel>Safra</masterLabel>
</GlobalValueSet>

Salesforce/main/default/classes/Test_Utils.cls
@isTest
public class Test_Utils {

    private static Test_Utils testUtils;
    
    public static Test_Utils getInstance(){
        if (testUtils == null){
            testUtils = new Test_Utils();
        }
        return testUtils;
    }
    
    public Account createNewAccount(Account accountObject){
        if(accountObject == null) {
            accountObject = new Account();
        }
        if(accountObject.Nome_fantasia__c == null) { accountObject.Nome_fantasia__c = 'FantasiaTest';}
        if(accountObject.Name == null) { accountObject.Name = 'AccountTest';}
        return accountObject;
    }
    
    public User createNewDiretorComercial(User userObject) {
        if(userObject == null) {
            userObject = new User();
        }
        User userBase = [SELECT CommunityNickname, TimeZoneSidKey, LocaleSidKey, EmailEncodingKey, LanguageLocaleKey FROM User LIMIT 1];
        Profile profileDiretorObject = [SELECT Id FROM Profile WHERE Name = 'Solo Lectura Custom' LIMIT 1];
        
        userObject.ProfileId = profileDiretorObject.Id;
        if(userObject.FirstName == null) { userObject.FirstName = 'Diretor'; }
        if(userObject.LastName == null) { userObject.LastName = 'Comercial'; }
        if(userObject.Email == null) { userObject.Email = 'teste3@email.com.br'; }
        if(userObject.Username == null) { userObject.Username = 'diretor'+System.now().millisecond()+'@comercial.com'; }
        if(userObject.Alias == null) { userObject.Alias = 'pdftes'; }
        if(userObject.CommunityNickname == null) { userObject.CommunityNickname = 'nicknamegerente'+System.now().millisecond(); }
        if(userObject.TimeZoneSidKey == null) { userObject.TimeZoneSidKey = userBase.TimeZoneSidKey; }
        if(userObject.LocaleSidKey == null) { userObject.LocaleSidKey = userBase.LocaleSidKey; }
        if(userObject.EmailEncodingKey == null) { userObject.EmailEncodingKey = userBase.EmailEncodingKey; }
        if(userObject.LanguageLocaleKey == null) { userObject.LanguageLocaleKey = userBase.LanguageLocaleKey; }
        return userObject;
    }
    
    public User createNewUserGerente(User userObject){
        if(userObject == null) {
            userObject = new User();
        }
        User userBase = [SELECT CommunityNickname, TimeZoneSidKey, LocaleSidKey, EmailEncodingKey, LanguageLocaleKey FROM User LIMIT 1];
        Profile profileGerenteObject = [SELECT Id FROM Profile WHERE Name = 'Gerente LE' LIMIT 1];
        
		if(userObject.ManagerId == null) { 
            User diretorComercial = createNewDiretorComercial(null);
            insert diretorComercial;
            userObject.ManagerId = diretorComercial.Id;
        }
        if(userObject.FirstName == null) { userObject.FirstName = 'Gerente'; }
        if(userObject.LastName == null) { userObject.LastName = 'Test'; }
        if(userObject.Email == null) { userObject.Email = 'teste@email.com.br'; }
        userObject.ProfileId = profileGerenteObject.Id;
        if(userObject.Username == null) { userObject.Username = 'gerente'+System.now().millisecond()+'@comercial.com'; }
        if(userObject.Alias == null) { userObject.Alias = 'pdftes'; }
        if(userObject.CommunityNickname == null) { userObject.CommunityNickname = 'nicknamegerente'+System.now().millisecond(); }
        if(userObject.TimeZoneSidKey == null) { userObject.TimeZoneSidKey = userBase.TimeZoneSidKey; }
        if(userObject.LocaleSidKey == null) { userObject.LocaleSidKey = userBase.LocaleSidKey; }
        if(userObject.EmailEncodingKey == null) { userObject.EmailEncodingKey = userBase.EmailEncodingKey; }
        if(userObject.LanguageLocaleKey == null) { userObject.LanguageLocaleKey = userBase.LanguageLocaleKey; }
        return userObject;
    }
    
    public User createNewUserSupervisor(User userObject){
        if(userObject == null) {
            userObject = new User();
        }
        User userBase = [SELECT CommunityNickname, TimeZoneSidKey, LocaleSidKey, EmailEncodingKey, LanguageLocaleKey FROM User LIMIT 1];
        Profile profileSupervisorObject = [SELECT Id FROM Profile WHERE Name = 'Comercial LE' LIMIT 1];
        
        if(userObject.FirstName == null) { userObject.FirstName = 'Supervisor'; }
        if(userObject.LastName == null) { userObject.LastName = 'Test'; }
        if(userObject.Email == null) { userObject.Email = 'testes@email.com.br'; }
        userObject.ProfileId = profileSupervisorObject.Id;
        if(userObject.Username == null) { userObject.Username = 'supervisor'+System.now().millisecond()+'@comercial.com'; }
        if(userObject.Alias == null) { userObject.Alias = 'pdftest'; }
        if(userObject.CommunityNickname == null) { userObject.CommunityNickname = 'nicknamesupervisor'+System.now().millisecond(); }
        if(userObject.TimeZoneSidKey == null) { userObject.TimeZoneSidKey = userBase.TimeZoneSidKey; }
        if(userObject.LocaleSidKey == null) { userObject.LocaleSidKey = userBase.LocaleSidKey; }
        if(userObject.EmailEncodingKey == null) { userObject.EmailEncodingKey = userBase.EmailEncodingKey; }
        if(userObject.LanguageLocaleKey == null) { userObject.LanguageLocaleKey = userBase.LanguageLocaleKey; }
        if(userObject.ManagerId == null) {
            User userGerenteObject = createNewUserGerente(null);
        	insert userGerenteObject;
            userObject.ManagerId = userGerenteObject.Id;
        }
        return userObject;
    }
    
    public Opportunity createNewOpportunityAnexo2(Opportunity opportunityObject) {
        if(opportunityObject == null) {
            opportunityObject = new Opportunity();
        }
        RecordType rtAnexo2Object = [SELECT Id FROM RecordType WHERE SobjectType = 'Opportunity' AND Name = 'Anexo II' LIMIT 1];
        
        opportunityObject.RecordTypeId = rtAnexo2Object.Id;
        if(opportunityObject.StageName == null) { opportunityObject.StageName = 'Pendiente de Análisis'; }
        if(opportunityObject.Name == null) { opportunityObject.Name = 'OppTeste'; }
        if(opportunityObject.Marca__c == null) { opportunityObject.Marca__c = 'MarcaTeste'; }
        if(opportunityObject.AccountId == null) { 
            Account accountObject = createNewAccount(null);
            insert accountObject;
            opportunityObject.AccountId = accountObject.Id; 
        }
        if(opportunityObject.OwnerId == null) { 
            User userObject = createNewUserGerente(null);
            userObject.CommunityNickname = 'UserAnexo2';
            userObject.Username = 'aaaewasdaeerfrf@gmail.com';
            insert userObject;
            opportunityObject.OwnerId = userObject.Id; 
        }
        if(opportunityObject.CloseDate == null) { opportunityObject.CloseDate = System.today(); }
        return opportunityObject;
    }
    
    public Opportunity createNewOpportunityAnexo2RebajaSupervisorOrGerente(Opportunity opportunityObject, String ownerUser) {
        if(opportunityObject == null) {
            opportunityObject = new Opportunity();
        }
        RecordType rtRebObject = [SELECT Id FROM RecordType WHERE SobjectType = 'Opportunity' AND Name = 'Anexo II Rebaixamento Sacas' LIMIT 1];
        
        opportunityObject.RecordTypeId = rtRebObject.Id;
        if(opportunityObject.StageName == null) { opportunityObject.StageName = 'Pendiente de Análisis'; }
        if(opportunityObject.Name  == null) { opportunityObject.Name = 'OppTest'; }
        if(opportunityObject.Marca__c == null) { opportunityObject.Marca__c = 'MarcaTest'; }
        if(opportunityObject.AccountId == null) { 
            Account accountObject = createNewAccount(null);
            insert accountObject;
            opportunityObject.AccountId = accountObject.Id; 
        }
        if(opportunityObject.OwnerId == null) {
            User userObject;
            if(ownerUser == 'Supervisor') {
                userObject = createNewUserSupervisor(null);
            } else {
            	userObject=createNewUserGerente(null);
            }
            insert userObject;
            opportunityObject.OwnerId = userObject.Id; 
        }
        if(opportunityObject.Anexo_Relacionado__c == null) { 
            Opportunity opportunityBaseObject = createNewOpportunityAnexo2(null);
            insert opportunityBaseObject;
            opportunityObject.Anexo_Relacionado__c = opportunityBaseObject.Id; 
        }
        if(opportunityObject.CloseDate == null) { opportunityObject.CloseDate = System.today(); }
        return opportunityObject;
    }
    
    public Contract createNewContract(Contract contractObject, Account accountObject) {
        if(contractObject == null) {
            contractObject = new Contract();
        }
        if(accountObject == null) {
            accountObject = createNewAccount(null);
        }
        if(accountObject.Id == null) {
            insert accountObject;
        }
        if(contractObject.AccountId == null) { contractObject.AccountId = accountObject.Id; }
        if(contractObject.Status == null) { contractObject.Status = 'Edição'; }
        if(contractObject.Safras__c == null) { 
            Integer actualYear = System.today().year();
            contractObject.Safras__c = String.valueOf(actualYear).right(2)+'/'+String.valueOf(actualYear+1).right(2); 
        }
        if(contractObject.Sociedad__c == null) { contractObject.Sociedad__c = 'BRMX'; }
        return contractObject;
    }
    
    public Contrato__c createNewContratoMultiplicacao(Contrato__c contratoMultiplicacaoObject, Account accountObject, Contract contractObject, User userObject) {
        if(contratoMultiplicacaoObject == null) {
            contratoMultiplicacaoObject = new Contrato__c();
        }
        if(accountObject == null) {
            accountObject = createNewAccount(null);
        }
        if(accountObject.Id == null) {
            insert accountObject;
        }
        if(contractObject == null) {
            contractObject = createNewContract(null, accountObject);
        }
        if(contractObject.Id == null) {
            insert contractObject;
        }
        if(userObject == null) {
            userObject = createNewUserSupervisor(null);
        }
        if(userObject.Id == null) {
            insert userObject;
        }
        if(contratoMultiplicacaoObject.OwnerId == null) { contratoMultiplicacaoObject.OwnerId = userObject.Id; }
        if(contratoMultiplicacaoObject.Multiplicador__c == null) { contratoMultiplicacaoObject.Multiplicador__c = accountObject.Id; }
        if(contratoMultiplicacaoObject.Safra__c == null) { 
            Integer actualYear = System.today().year();
            contratoMultiplicacaoObject.Safra__c = String.valueOf(actualYear).right(2)+'/'+String.valueOf(actualYear+1).right(2); 
        }
        if(contratoMultiplicacaoObject.Sociedad__c == null) { contratoMultiplicacaoObject.Sociedad__c = 'BRMX'; }
        if(contratoMultiplicacaoObject.Region_Comercial__c == null) { contratoMultiplicacaoObject.Region_Comercial__c = 'CERRADO'; }
        if(contratoMultiplicacaoObject.Estados_Comercializacao__c == null) { contratoMultiplicacaoObject.Estados_Comercializacao__c = 'SP'; }
        if(contratoMultiplicacaoObject.Estado__c == null) { contratoMultiplicacaoObject.Estado__c = 'Edição'; }
        if(contratoMultiplicacaoObject.Contrato_marco__c == null) { contratoMultiplicacaoObject.Contrato_marco__c = contractObject.Id; }  
        if(contratoMultiplicacaoObject.RecordTypeId == null) { contratoMultiplicacaoObject.RecordTypeId = Contrato__c.SObjectType.getDescribe().getRecordTypeInfosByName().get('Termo Aditivo Comerciais').getRecordTypeId(); }
        return contratoMultiplicacaoObject;
    }
}