Salesforce/main/default/objects/Account/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Estado</label>
    <referenceTo>Estado__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/Account/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Marca</valueSetName>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Account/fields/Reponsavel_DSEM__c.field-meta.xml
<CustomField>
    <fullName>Reponsavel_DSEM__c</fullName>
    <description>Qual dos funcionários da DSEM que estará responsável pela conta</description>
    <inlineHelpText>Qual dos funcionários da DSEM que estará responsável pela conta</inlineHelpText>
    <label>Responsável DSEM</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>061 - Fernando Frehner</fullName>
            </value>
            <value>
                <fullName>066 - Marcelo Steffen</fullName>
            </value>
            <value>
                <fullName>067 - Sergio Bertagnoli</fullName>
            </value>
            <value>
                <fullName>010 - GDM Genetica</fullName>
            </value>
            <value>
                <fullName>011 - Pablo R. de Souza</fullName>
            </value>
            <value>
                <fullName>014 - Cristian Pirolli</fullName>
            </value>
            <value>
                <fullName>015 - Fagner Regis de Oliveira</fullName>
            </value>
            <value>
                <fullName>016 - Murilo Brazero Cacheffo</fullName>
            </value>
            <value>
                <fullName>234 - Julio Cesar Poletto</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Account/fields/Responsavel__c.field-meta.xml
<CustomField>
    <fullName>Responsavel__c</fullName>
    <description>Qual dos funcionários da Brasmax que estará responsável pela conta</description>
    <inlineHelpText>Qual dos funcionários da Brasmax que estará responsável pela conta</inlineHelpText>
    <label>Responsável BRMX</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>061 - Fernando Frehner</fullName>
            </value>
            <value>
                <fullName>066 - Marcelo Steffen</fullName>
            </value>
            <value>
                <fullName>067 - Sergio Bertagnolli</fullName>
            </value>
            <value>
                <fullName>076 - Tiago Goulart</fullName>
            </value>
            <value>
                <fullName>083 - Jorge Cristiano Rosa</fullName>
            </value>
            <value>
                <fullName>010 - Brasmax</fullName>
            </value>
            <value>
                <fullName>101 - Fausto Tadeu Fanchin</fullName>
            </value>
            <value>
                <fullName>104 - Otavio Gorni</fullName>
            </value>
            <value>
                <fullName>150 - João Serrano</fullName>
            </value>
            <value>
                <fullName>012 - Anderson Weissheimer</fullName>
            </value>
            <value>
                <fullName>197 - Wagner Rank</fullName>
            </value>
            <value>
                <fullName>198 - Bernardo Zanardo</fullName>
            </value>
            <value>
                <fullName>199 - Lucas Costa</fullName>
            </value>
            <value>
                <fullName>231 - Willian Von Scharten</fullName>
            </value>
            <value>
                <fullName>234 - Julio Cesar Poletto</fullName>
            </value>
            <value>
                <fullName>017 - Luis Fernando Cecatto</fullName>
            </value>
            <value>
                <fullName>018 - Flávio Marçal dos Santos</fullName>
            </value>
            <value>
                <fullName>312 - Lucas Hilario Fantineli</fullName>
            </value>
            <value>
                <fullName>019 - Felipe Oliveira Costa</fullName>
            </value>
            <value>
                <fullName>379 - Diego F. Gonçalves</fullName>
            </value>
            <value>
                <fullName>031 - Guilherme Sousa</fullName>
            </value>
            <value>
                <fullName>023 - Gabriel V. Finatto</fullName>
            </value>
            <value>
                <fullName>464 - Ana Laura Fernandes</fullName>
            </value>
            <value>
                <fullName>467 - Natalie de Mattos</fullName>
            </value>
            <value>
                <fullName>474 - Guilherme Menezes Salau</fullName>
            </value>
            <value>
                <fullName>403 - Felipe Bianchessi</fullName>
            </value>
            <value>
                <fullName>380 - Lucas de Souza Furlan</fullName>
            </value>
            <value>
                <fullName>037 - Felipe Dias Louzada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Account/fields/Responsavel_DAGMA__c.field-meta.xml
<CustomField>
    <fullName>Responsavel_DAGMA__c</fullName>
    <label>Responsável DAGMA</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>033 - Gustavo Suzano</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Account/fields/Responsavel_LICENCAS__c.field-meta.xml
<CustomField>
    <fullName>Responsavel_LICENCAS__c</fullName>
    <label>Responsável LICENÇAS</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>124 - Thiago Schwonka</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Account/fields/Responsavel_NEOGEN__c.field-meta.xml
<CustomField>
    <fullName>Responsavel_NEOGEN__c</fullName>
    <label>Responsável NEOGEN</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>020 - Eduardo L. da Silva</fullName>
            </value>
            <value>
                <fullName>346 - Marco A. Marchioro</fullName>
            </value>
            <value>
                <fullName>022 - Josiane Dotto Dalla Corte</fullName>
            </value>
            <value>
                <fullName>485 - Felipe Biasi</fullName>
            </value>
            <value>
                <fullName>486 - Vagner Carvalho</fullName>
            </value>
            <value>
                <fullName>487 - Clevison Moraes</fullName>
            </value>
            <value>
                <fullName>319 - Felipe Oliveira Costa</fullName>
                <isActive>false</isActive>
                <label>319 - Felipe Oliveira Costa</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Account/fields/Supervisor__c.field-meta.xml
<CustomField>
    <fullName>Supervisor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supervisor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Supervisores</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Account/recordTypes/Cuenta.recordType-meta.xml
<RecordType>
    <fullName>Cuenta</fullName>
    <active>true</active>
    <label>Cuenta</label>
</RecordType>

Salesforce/main/default/objects/CRM_Calendario_de_Eventos__c/CRM_Calendario_de_Eventos__c.object-meta.xml
<CustomObject>
    <description>Registro de eventos programados pelo Multiplicador</description>
    <label>CRM Evento</label>
    <nameField>
        <label>Nome de CRM Evento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Eventos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/objects/CRM_Calendario_de_Eventos__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Conta multiplicador, que realizou ou eventos agendados</description>
    <inlineHelpText>Conta multiplicador, que realizou ou eventos agendados</inlineHelpText>
    <label>Nome da conta</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Agricultor__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Eventos (Cuenta)</relationshipLabel>
    <relationshipName>CRM_Calend_rio_de_eventos</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/CRM_Calendario_de_Eventos__c/fields/Data__c.field-meta.xml
<CustomField>
    <fullName>Data__c</fullName>
    <description>Data do evento</description>
    <inlineHelpText>Data do evento</inlineHelpText>
    <label>Data</label>
    <type>Date</type>
</CustomField>

Salesforce/main/default/main/default/objects/CRM_Calendario_de_Eventos__c/fields/Data_e_horario_inicio__c.field-meta.xml
<CustomField>
    <fullName>Data_e_horario_inicio__c</fullName>
    <label>Data e horario inicio</label>
    <type>DateTime</type>
</CustomField>

Salesforce/main/default/objects/CRM_Calendario_de_Eventos__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <description>Nome do Estado</description>
    <formula>Municipio__r.Estado__r.Name</formula>
    <inlineHelpText>Nome do Estado</inlineHelpText>
    <label>Estado</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/CRM_Calendario_de_Eventos__c/fields/Evento__c.field-meta.xml
<CustomField>
    <fullName>Evento__c</fullName>
    <description>Tipo de evento</description>
    <inlineHelpText>Tipo de evento</inlineHelpText>
    <label>Evento</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Día de Campo</fullName>
            </value>
            <value>
                <fullName>Area comercial</fullName>
            </value>
            <value>
                <fullName>Emplacamento</fullName>
            </value>
            <value>
                <fullName>Encontro Técnico</fullName>
            </value>
            <value>
                <fullName>Estação DONMARIO MAS</fullName>
            </value>
            <value>
                <fullName>Feiras</fullName>
            </value>
            <value>
                <fullName>Jornada Técnica</fullName>
            </value>
            <value>
                <fullName>Lado a Lado</fullName>
            </value>
            <value>
                <fullName>Painel Técnico</fullName>
            </value>
            <value>
                <fullName>Palestra</fullName>
            </value>
            <value>
                <fullName>Strip Test</fullName>
            </value>
            <value>
                <fullName>Tour dos Máximos Rendimentos</fullName>
            </value>
            <value>
                <fullName>Treinamento</fullName>
            </value>
            <value>
                <fullName>CESB</fullName>
            </value>
            <value>
                <fullName>Outdoor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/CRM_Calendario_de_Eventos__c/fields/Responsavel__c.field-meta.xml
<CustomField>
    <fullName>Responsavel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Responsável</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Responsavel</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/CRM_Calendario_de_Eventos__c/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <label>Safra</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>11/12</fullName>
            </value>
            <value>
                <fullName>12/13</fullName>
            </value>
            <value>
                <fullName>17/18</fullName>
            </value>
            <value>
                <fullName>18/19</fullName>
            </value>
            <value>
                <fullName>19/20</fullName>
            </value>
            <value>
                <fullName>20/21</fullName>
            </value>
            <value>
                <fullName>21/22</fullName>
                <default>true</default>
                <label>21/22</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/CRM_Calendario_de_Eventos__c/recordTypes/Emplacamento.recordType-meta.xml
<RecordType>
    <fullName>Emplacamento</fullName>
    <active>true</active>
    <description>Emplacamentos</description>
    <label>Emplacamento</label>
</RecordType>

Salesforce/main/default/main/default/objects/Estado__c/Estado__c.object-meta.xml
<CustomObject>
    <label>Estado</label>
    <nameField>
        <label>Nome do Estado</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estados</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/globalValueSets/Marca.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BRMX</fullName>
    </customValue>
    <customValue>
        <fullName>DSEM</fullName>
    </customValue>
    <customValue>
        <fullName>NEOG</fullName>
    </customValue>
    <customValue>
        <fullName>DAGMA</fullName>
    </customValue>
    <customValue>
        <fullName>LICENÇAS</fullName>
    </customValue>
    <masterLabel>Marca</masterLabel>
</GlobalValueSet>

Salesforce/main/default/classes/CRMEventoUtilsTest.cls
@isTest
private class CRMEventoUtilsTest {

    @TestSetup
    static void makeData() {

        Estado__c newState = new Estado__c();
        newState.Name = 'ESTADO TEST';
        insert newState;

        Account newAccount = new Account();
        newAccount.Name = 'ACME';
        newAccount.Estado__c = newState.Id;
        newAccount.Supervisor__c = UserInfo.getUserId();

        newAccount.Responsavel__c = '104 - Otavio Gorni';
        newAccount.Reponsavel_DSEM__c = '014 - Cristian Pirolli';
        newAccount.Responsavel_NEOGEN__c = '020 - Eduardo L. da Silva';
        newAccount.Responsavel_DAGMA__c = '033 - Gustavo Suzano';
        newAccount.Responsavel_LICENCAS__c = '124 - Thiago Schwonka'; 
        insert newAccount;
    }

    @isTest
    static void testBRMX(){
      
      CRMEventoUtils crm = new CRMEventoUtils();
      Account cuenta = [Select Id, Estado__c From Account Where Name = 'ACME' limit 1]; 
        
      CRM_Calendario_de_Eventos__c eventos = new CRM_Calendario_de_Eventos__c();
        eventos.evento__c = 'Emplacamento';
        eventos.cuenta__c = cuenta.Id;
        eventos.Marca__c = 'BRMX';
        eventos.data__c = system.today();
        eventos.Data_e_horario_inicio__c = System.Now();
        eventos.Data_e_horario_termino__c = System.Now()+1;
        eventos.Custo__c = 32;
        eventos.safra__c = '17/18';
        insert eventos;      
        
        eventos.data__c = system.today() + 1;
        update eventos;
    }
    
    @isTest
    static void testDSEM(){      
        Account cuenta = [Select Id, Estado__c From Account Where Name = 'ACME' limit 1];
      
        CRM_Calendario_de_Eventos__c eventos = new CRM_Calendario_de_Eventos__c();
        eventos.evento__c = 'Día de Campo';
        eventos.cuenta__c = cuenta.Id;
        eventos.Marca__c = 'DSEM';
        eventos.Data_e_horario_inicio__c = System.Now();
        eventos.Data_e_horario_termino__c = System.Now()+1;
        eventos.Custo__c = 32;
        eventos.data__c = system.today();
        eventos.safra__c = '17/18';
        insert eventos;
        
        CRM_Calendario_de_Eventos__c eventos2 = new CRM_Calendario_de_Eventos__c();
        eventos2.evento__c = 'Emplacamento';
        eventos2.cuenta__c = cuenta.Id;
        eventos2.Marca__c = 'DSEM';
        eventos2.Data_e_horario_inicio__c = System.Now();
        eventos2.Data_e_horario_termino__c = System.Now()+1;        
        eventos2.data__c = system.today();
        eventos2.safra__c = '17/18';
        insert eventos2;

    }
}