Salesforce/main/default/objects/Account/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Estado</label>
    <referenceTo>Estado__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Account/fields/Region_Comercial__c.field-meta.xml
<CustomField>
    <fullName>Region_Comercial__c</fullName>
    <formula>TEXT(Region__r.Region_Comercial__c)</formula>
    <label>Região Comercial</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/Account/recordTypes/Cuenta.recordType-meta.xml
<RecordType>
    <fullName>Cuenta</fullName>
    <active>true</active>
    <label>Cuenta</label>
</RecordType>

Salesforce/main/default/objects/Contract/fields/Region_Comercial__c.field-meta.xml
<CustomField>
    <fullName>Region_Comercial__c</fullName>
    <label>Regiao Comercial</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/Contract/fields/Sociedad__c.field-meta.xml
<CustomField>
    <fullName>Sociedad__c</fullName>
    <label>Sociedad</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Marca</valueSetName>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Contrato__c/Contrato__c.object-meta.xml
<CustomObject>
    <description>CONTRATO DE LICENCIAMENTO PARA MULTIPLICAÇÃO E COMERCIALIZAÇÃO</description>
    <label>Contrato de Multiplicação</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Numero do Contrato de Multiplicação</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contratos de Multiplicação</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/Contrato__c/fields/Contrato_marco__c.field-meta.xml
<CustomField>
    <fullName>Contrato_marco__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contrato guarda chuva para 3 safras</description>
    <label>Contrato Macro</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Termos Aditivos</relationshipLabel>
    <relationshipName>Contratos_de_Multiplicacion</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Contrato__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Edição</fullName>
                <default>true</default>
                <label>Edição</label>
            </value>
            <value>
                <fullName>Pendente de Aprovação</fullName>
            </value>
            <value>
                <fullName>Aguardando Assinatura</fullName>
            </value>
            <value>
                <fullName>Pendente de Impressão</fullName>
            </value>
            <value>
                <fullName>Pendente de Envio</fullName>
            </value>
            <value>
                <fullName>Pendente de Postagem</fullName>
            </value>
            <value>
                <fullName>Aguarda Retorno</fullName>
            </value>
            <value>
                <fullName>Chegou</fullName>
            </value>
            <value>
                <fullName>Inutilizado</fullName>
            </value>
            <value>
                <fullName>Anulado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Contrato__c/fields/Estados_Comercializacao__c.field-meta.xml
<CustomField>
    <fullName>Estados_Comercializacao__c</fullName>
    <label>Estados de Comercialização</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AC</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AM</fullName>
            </value>
            <value>
                <fullName>AP</fullName>
            </value>
            <value>
                <fullName>BA</fullName>
            </value>
            <value>
                <fullName>CE</fullName>
            </value>
            <value>
                <fullName>DF</fullName>
            </value>
            <value>
                <fullName>ES</fullName>
            </value>
            <value>
                <fullName>GO</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MG</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>PA</fullName>
            </value>
            <value>
                <fullName>Paraguai</fullName>
            </value>
            <value>
                <fullName>PB</fullName>
            </value>
            <value>
                <fullName>PE</fullName>
            </value>
            <value>
                <fullName>PI</fullName>
            </value>
            <value>
                <fullName>PR</fullName>
            </value>
            <value>
                <fullName>RJ</fullName>
            </value>
            <value>
                <fullName>RN</fullName>
            </value>
            <value>
                <fullName>RO</fullName>
            </value>
            <value>
                <fullName>RR</fullName>
            </value>
            <value>
                <fullName>RS</fullName>
            </value>
            <value>
                <fullName>SC</fullName>
            </value>
            <value>
                <fullName>SE</fullName>
            </value>
            <value>
                <fullName>SP</fullName>
            </value>
            <value>
                <fullName>TO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Contrato__c/fields/log_cambios__c.field-meta.xml
<CustomField>
    <fullName>log_cambios__c</fullName>
    <description>Campo para especificar los cambios que se hicieron en un contrato clonado a partir de la comparacion con el contrato original</description>
    <label>Log de alterações</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

Salesforce/main/default/main/default/objects/Contrato__c/fields/Meta_Qde_comodato_de_area__c.field-meta.xml
<CustomField>
    <fullName>Meta_Qde_comodato_de_area__c</fullName>
    <label>Meta Qde Comodato de Área</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/main/default/objects/Contrato__c/fields/Meta_Qde_Dias_de_Campo__c.field-meta.xml
<CustomField>
    <fullName>Meta_Qde_Dias_de_Campo__c</fullName>
    <label>Meta Qde Días de Campo Sem Custo</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/main/default/objects/Contrato__c/fields/Observacao__c.field-meta.xml
<CustomField>
    <fullName>Observacao__c</fullName>
    <description>Informações genéricas sobre o processo de recebimento dos contratos</description>
    <inlineHelpText>Informações genéricas sobre o processo de recebimento dos contratos</inlineHelpText>
    <label>Observação</label>
    <type>TextArea</type>
</CustomField>

Salesforce/main/default/objects/Contrato__c/fields/Region_Comercial__c.field-meta.xml
<CustomField>
    <fullName>Region_Comercial__c</fullName>
    <label>Região Comercial</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>REGION 1</fullName>
            </value>
            <value>
                <fullName>REGION 2</fullName>
            </value>
            <value>
                <fullName>CERRADO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Contrato__c/fields/Sociedad__c.field-meta.xml
<CustomField>
    <fullName>Sociedad__c</fullName>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BRMX</fullName>
            </value>
            <value>
                <fullName>DSEM</fullName>
            </value>
            <value>
                <fullName>NEOG</fullName>
            </value>
            <value>
                <fullName>DAGMA</fullName>
            </value>
            <value>
                <fullName>LICENÇAS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Contrato__c/recordTypes/DSEM.recordType-meta.xml
<RecordType>
    <fullName>DSEM</fullName>
    <active>true</active>
    <description>Contratos de la sociedad Don Mario</description>
    <label>DSEM</label>
</RecordType>

Salesforce/main/default/main/default/objects/Contrato__c/recordTypes/Termo_Aditivo.recordType-meta.xml
<RecordType>
    <fullName>Termo_Aditivo</fullName>
    <active>true</active>
    <description>Termo Aditivos de Contrato de multiplicação - a partir de 2018</description>
    <label>Termo Aditivo Comerciais</label>
</RecordType>

Salesforce/main/default/main/default/objects/Estado__c/Estado__c.object-meta.xml
<CustomObject>
    <label>Estado</label>
    <nameField>
        <label>Nome do Estado</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estados</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/objects/Item_del_Contrato__c/Item_del_Contrato__c.object-meta.xml
<CustomObject>
    <description>Item de CONTRATO DE LICENCIAMENTO PARA MULTIPLICAÇÃO E COMERCIALIZAÇÃO</description>
    <label>Item del Contrato</label>
    <nameField>
        <label>Nombre de Item del Contrato</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items del Contrato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Salesforce/main/default/objects/Item_del_Contrato__c/fields/Contrato_de_Multiplicacao__c.field-meta.xml
<CustomField>
    <fullName>Contrato_de_Multiplicacao__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contrato (Objetivo)</label>
    <referenceTo>Contrato__c</referenceTo>
    <relationshipLabel>Objetivos (Eventos)</relationshipLabel>
    <relationshipName>objetivos</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/Item_del_Contrato__c/fields/Contrato_de_Multiplicacion__c.field-meta.xml
<CustomField>
    <fullName>Contrato_de_Multiplicacion__c</fullName>
    <description>Relación entre la cabecera del Contrato con los items(información de la variedad, precio, etc)</description>
    <inlineHelpText>Relación entre la cabecera del Contrato con los items(información de la variedad, precio, etc)</inlineHelpText>
    <label>Contrato de Multiplicação</label>
    <referenceTo>Contrato__c</referenceTo>
    <relationshipLabel>Items del Contrato</relationshipLabel>
    <relationshipName>Items_del_Contrato</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Salesforce/main/default/objects/Item_del_Contrato__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AC</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AM</fullName>
            </value>
            <value>
                <fullName>AP</fullName>
            </value>
            <value>
                <fullName>BA</fullName>
            </value>
            <value>
                <fullName>CE</fullName>
            </value>
            <value>
                <fullName>DF</fullName>
            </value>
            <value>
                <fullName>ES</fullName>
            </value>
            <value>
                <fullName>GO</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MG</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>PA</fullName>
            </value>
            <value>
                <fullName>Paraguai</fullName>
            </value>
            <value>
                <fullName>PB</fullName>
            </value>
            <value>
                <fullName>PE</fullName>
            </value>
            <value>
                <fullName>PI</fullName>
            </value>
            <value>
                <fullName>PR</fullName>
            </value>
            <value>
                <fullName>RJ</fullName>
            </value>
            <value>
                <fullName>RN</fullName>
            </value>
            <value>
                <fullName>RO</fullName>
            </value>
            <value>
                <fullName>RR</fullName>
            </value>
            <value>
                <fullName>RS</fullName>
            </value>
            <value>
                <fullName>SC</fullName>
            </value>
            <value>
                <fullName>SE</fullName>
            </value>
            <value>
                <fullName>SP</fullName>
            </value>
            <value>
                <fullName>TO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Item_del_Contrato__c/fields/Quantidade__c.field-meta.xml
<CustomField>
    <fullName>Quantidade__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Indica la cantidad por la que se cerró el aditivo</description>
    <label>Quantidade</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/objects/Item_del_Contrato__c/fields/Volumen_Aut_Comercializacion__c.field-meta.xml
<CustomField>
    <fullName>Volumen_Aut_Comercializacion__c</fullName>
    <label>Volumen Aut. Comercializacion</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/main/default/objects/Item_del_Contrato__c/recordTypes/Volumen.recordType-meta.xml
<RecordType>
    <fullName>Volumen</fullName>
    <active>true</active>
    <label>Volumen</label>
</RecordType>

Salesforce/main/default/globalValueSets/Marca.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BRMX</fullName>
    </customValue>
    <customValue>
        <fullName>DSEM</fullName>
    </customValue>
    <customValue>
        <fullName>NEOG</fullName>
    </customValue>
    <customValue>
        <fullName>DAGMA</fullName>
    </customValue>
    <customValue>
        <fullName>LICENÇAS</fullName>
    </customValue>
    <masterLabel>Marca</masterLabel>
</GlobalValueSet>

Salesforce/main/default/main/default/classes/ItemDelContratoTriggerHelperTest.cls
@isTest
public class ItemDelContratoTriggerHelperTest  {

	@TestSetup
	static void setup() {
		Account cuenta = new Account(
			Name = 'Test'
		);
		insert cuenta;
		Contract contratoMarco = new Contract (
			Name = 'Contrato marco',
			AccountId = cuenta.Id
		);
		insert contratoMarco;
		Contrato__c contrato = new Contrato__c(
			RecordTypeId = [SELECT ID FROM RecordType WHERE DeveloperName = 'Termo_Aditivo'].id,
			Estado__c = 'Chegou',
			Observacao__c = 'Soy el original',
			Sociedad__c = 'DSEM',
			Estados_Comercializacao__c = 'CE',
			Contrato_marco__c = contratoMarco.Id,
			Region_Comercial__c = 'REGION 1',
			Meta_Qde_comodato_de_area__c = 1,
			Meta_Qde_Dias_de_Campo__c = 1
		);
		insert contrato;
	}


	@isTest
	static void debeAniadirAlLogLosNuevosProductosAlContratoClonado() {
		Contrato__c contrato = [SELECT ID FROM Contrato__c WHERE Estado__c = 'Chegou'];
        Item_del_Contrato__c itemObjetivo = new Item_del_Contrato__c();
        Item_del_Contrato__c item = new Item_del_Contrato__c();
		String id = ClonarContratoLightningController.cloneContract(contrato.Id);
		Test.startTest();
			item.Contrato_de_Multiplicacion__c = id;
			insert item;
			itemObjetivo.Contrato_de_Multiplicacao__c = id;
			itemObjetivo.Contrato_de_Multiplicacion__c = id;
			insert itemObjetivo;
			Contrato__c clon = [SELECT ID, log_cambios__c FROM Contrato__c WHERE ID =: id];
		Test.stopTest();
		System.assertEquals(true, clon.log_cambios__c.contains('Novo cultivar'), 'No se escribio el log');
		System.assertEquals(true, clon.log_cambios__c.contains('Novo objetivo'), 'No se escribio el log');
	}

	@isTest
	static void debeAniadirAlLogLasModificacionesEnLosItems() {
		Contrato__c contrato = [SELECT ID FROM Contrato__c WHERE Estado__c = 'Chegou'];
        Item_del_Contrato__c itemObjetivo = new Item_del_Contrato__c();
        Item_del_Contrato__c item = new Item_del_Contrato__c();
		String id = ClonarContratoLightningController.cloneContract(contrato.Id);
		Test.startTest();
			item.Contrato_de_Multiplicacion__c = id;
			insert item;
			itemObjetivo.Contrato_de_Multiplicacao__c = id;
			itemObjetivo.Contrato_de_Multiplicacion__c = id;
			insert itemObjetivo;
			itemObjetivo.Quantidade__c = 100;
			itemObjetivo.Volumen_Aut_Comercializacion__c = 100;
			update itemObjetivo;
			Contrato__c clon = [SELECT ID, log_cambios__c FROM Contrato__c WHERE ID =: id];
		Test.stopTest();
		System.debug(clon.log_cambios__c);
		System.assertEquals(true, clon.log_cambios__c.contains('Volume de comercialização'), 'No se esctibio el log del volumen');
		System.assertEquals(true, clon.log_cambios__c.contains('Quantidade alterado de'), 'No se esctibio el log de la cantidad');
	}

	@IsTest
	static void debeAniadirAlLogAlBorrarUnItem() {
		Contrato__c contrato = [SELECT ID FROM Contrato__c WHERE Estado__c = 'Chegou'];
        Item_del_Contrato__c itemObjetivo = new Item_del_Contrato__c();
        Item_del_Contrato__c item = new Item_del_Contrato__c();
		String id = ClonarContratoLightningController.cloneContract(contrato.Id);
		Test.startTest();
			item.Contrato_de_Multiplicacion__c = id;
			insert item;
			itemObjetivo.Contrato_de_Multiplicacao__c = id;
			itemObjetivo.Contrato_de_Multiplicacion__c = id;
			insert itemObjetivo;
			itemObjetivo.Quantidade__c = 100;
			itemObjetivo.Volumen_Aut_Comercializacion__c = 100;
			update itemObjetivo;
			delete itemObjetivo;
			Contrato__c clon = [SELECT ID, log_cambios__c FROM Contrato__c WHERE ID =: id];
		Test.stopTest();
		System.debug(clon.log_cambios__c);
		System.assertEquals(true, clon.log_cambios__c.contains('Removido'), 'No se esctibio el log al borrar el item');


	}
}