Salesforce/main/default/objects/Account/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Estado</label>
    <referenceTo>Estado__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Attachment_Content__c/Attachment_Content__c.object-meta.xml
<CustomObject>
    <label>Attachment Content</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attachments Contents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/objects/Attachment_Content__c/fields/CRM_Calendario_de_Eventos__c.field-meta.xml
<CustomField>
    <fullName>CRM_Calendario_de_Eventos__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CRM Evento</label>
    <referenceTo>CRM_Calendario_de_Eventos__c</referenceTo>
    <relationshipLabel>Attachments Contents</relationshipLabel>
    <relationshipName>Attachments_Contents</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Cidade__c/Cidade__c.object-meta.xml
<CustomObject>
    <label>Ciudad</label>
    <nameField>
        <label>Nome da Cidade</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ciudades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/Cidade__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Estado</label>
    <referenceTo>Estado__c</referenceTo>
    <relationshipName>Cidades</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/Configuracion_BMX__c/Configuracion_BMX__c.object-meta.xml
<CustomObject>
    <description>Indicador de Parametros.</description>
    <label>Configuracion_BMX</label>
    <nameField>
        <label>Configuracion Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuraciones_BMX</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/objects/CRM_Calendario_de_Eventos__c/CRM_Calendario_de_Eventos__c.object-meta.xml
<CustomObject>
    <description>Registro de eventos programados pelo Multiplicador</description>
    <label>CRM Evento</label>
    <nameField>
        <label>Nome de CRM Evento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Eventos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/objects/CRM_Calendario_de_Eventos__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Conta multiplicador, que realizou ou eventos agendados</description>
    <inlineHelpText>Conta multiplicador, que realizou ou eventos agendados</inlineHelpText>
    <label>Nome da conta</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Agricultor__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Eventos (Cuenta)</relationshipLabel>
    <relationshipName>CRM_Calend_rio_de_eventos</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/CRM_Calendario_de_Eventos__c/fields/Data__c.field-meta.xml
<CustomField>
    <fullName>Data__c</fullName>
    <description>Data do evento</description>
    <inlineHelpText>Data do evento</inlineHelpText>
    <label>Data</label>
    <type>Date</type>
</CustomField>

Salesforce/main/default/objects/CRM_Calendario_de_Eventos__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <description>Nome do Estado</description>
    <formula>Municipio__r.Estado__r.Name</formula>
    <inlineHelpText>Nome do Estado</inlineHelpText>
    <label>Estado</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/CRM_Calendario_de_Eventos__c/fields/Evento__c.field-meta.xml
<CustomField>
    <fullName>Evento__c</fullName>
    <description>Tipo de evento</description>
    <inlineHelpText>Tipo de evento</inlineHelpText>
    <label>Evento</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Día de Campo</fullName>
            </value>
            <value>
                <fullName>Area comercial</fullName>
            </value>
            <value>
                <fullName>Emplacamento</fullName>
            </value>
            <value>
                <fullName>Encontro Técnico</fullName>
            </value>
            <value>
                <fullName>Estação DONMARIO MAS</fullName>
            </value>
            <value>
                <fullName>Feiras</fullName>
            </value>
            <value>
                <fullName>Jornada Técnica</fullName>
            </value>
            <value>
                <fullName>Lado a Lado</fullName>
            </value>
            <value>
                <fullName>Painel Técnico</fullName>
            </value>
            <value>
                <fullName>Palestra</fullName>
            </value>
            <value>
                <fullName>Strip Test</fullName>
            </value>
            <value>
                <fullName>Tour dos Máximos Rendimentos</fullName>
            </value>
            <value>
                <fullName>Treinamento</fullName>
            </value>
            <value>
                <fullName>CESB</fullName>
            </value>
            <value>
                <fullName>Outdoor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/CRM_Calendario_de_Eventos__c/fields/Fase__c.field-meta.xml
<CustomField>
    <fullName>Fase__c</fullName>
    <label>Fase</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Edição</fullName>
            </value>
            <value>
                <fullName>Aguardando validação dados de plantio</fullName>
            </value>
            <value>
                <fullName>Edição de dados de colheita</fullName>
            </value>
            <value>
                <fullName>Aguardando resultado de colheita</fullName>
            </value>
            <value>
                <fullName>Aguardando validação dados de colheita</fullName>
            </value>
            <value>
                <fullName>Pendente</fullName>
            </value>
            <value>
                <fullName>Aprovado</fullName>
                <default>true</default>
                <label>Aprovado</label>
            </value>
            <value>
                <fullName>Reprovado</fullName>
            </value>
            <value>
                <fullName>Anulado</fullName>
            </value>
            <value>
                <fullName>Edição de dados de plantio</fullName>
            </value>
            <value>
                <fullName>Reprovado Colheita</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/CRM_Calendario_de_Eventos__c/fields/Municipio__c.field-meta.xml
<CustomField>
    <fullName>Municipio__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Evento município</description>
    <inlineHelpText>Evento município</inlineHelpText>
    <label>Cidade</label>
    <referenceTo>Cidade__c</referenceTo>
    <relationshipName>CRM_Calend_rio_de_eventos</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/CRM_Calendario_de_Eventos__c/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <label>Safra</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>11/12</fullName>
            </value>
            <value>
                <fullName>12/13</fullName>
            </value>
            <value>
                <fullName>17/18</fullName>
            </value>
            <value>
                <fullName>18/19</fullName>
            </value>
            <value>
                <fullName>19/20</fullName>
            </value>
            <value>
                <fullName>20/21</fullName>
            </value>
            <value>
                <fullName>21/22</fullName>
                <default>true</default>
                <label>21/22</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Estado__c/Estado__c.object-meta.xml
<CustomObject>
    <label>Estado</label>
    <nameField>
        <label>Nome do Estado</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estados</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/classes/AttachmentContentControllerTest.cls
@isTest
private class AttachmentContentControllerTest {

    @TestSetup static void setup() {
        Configuracion_BMX__c testConfiguracionBMX = Build.aConfiguracionBMX()
            .withPMSafraActualEventos('18/19')
            .build();

        insert testConfiguracionBMX;

        Account account = Build.anAccount()
            .withName('JERE')
            .withNomefantasia('JRERE')
            .withResponsavel('061 - Fernando Frehner')
            .withType('Multiplicador')
            .build();

        insert account;

        Estado__c estado = new Estado__c(Name = 'California');
        insert estado;

        Cidade__c ciudad = new Cidade__c(Name = 'Los Angeles', Estado__c = estado.Id);
        insert ciudad;

        CRM_Calendario_de_Eventos__c crmEvento = new CRM_Calendario_de_Eventos__c(
            Data__c = Date.today(),
            Cuenta__c = account.Id,
            Evento__c = 'Lado a Lado',
            Fase__c = 'Edição',
            Safra__c = '18/19',
            Municipio__c = ciudad.Id
        );

        insert crmEvento;

        Attachment_Content__c attContent = new Attachment_Content__c(
            CRM_Calendario_de_Eventos__c = crmEvento.Id
        );

        insert attContent;

        Attachment att = new Attachment(
            Name = 'Unit Test Attachment',
            Body = Blob.valueOf('Unit Test Attachment Body'),
            parentId = attContent.Id
        );

        insert att;
    }

    @isTest static void addAttachmentContentTest() {
        CRM_Calendario_de_Eventos__c crmEvento = [SELECT Id FROM CRM_Calendario_de_Eventos__c LIMIT 1];

        Test.startTest();
        AttachmentContentController.addAttachmentContent(crmEvento.Id, 'Arquivos gerais', 'Test Attachment', 'image/jpg', 'AAABBBCCC');

        System.assertEquals(2, [SELECT Id FROM Attachment_Content__c].size());
        System.assertEquals(2, [SELECT Id FROM Attachment].size());

        try {
            AttachmentContentController.addAttachmentContent(crmEvento.Id, '', '', '', null);
        } catch (Exception e) {}
        Test.stopTest();
    }

    @isTest static void getAttachmentContentsTest() {
        CRM_Calendario_de_Eventos__c crmEvento = [SELECT Id FROM CRM_Calendario_de_Eventos__c LIMIT 1];

        Test.startTest();
        List<Map<String, String>> attContents = AttachmentContentController.getAttachmentContents(crmEvento.Id);

        System.assertEquals(1, attContents.size());

        Map<String, String> attContent = attContents[0];

        System.assert(String.isNotEmpty(attContent.get('id')));
        System.assertEquals('Unit Test Attachment', attContent.get('AttachmentName'));
        Test.stopTest();
    }

    @isTest static void downloadAttachmentContentTest() {
        Attachment_Content__c attContent = [SELECT Id FROM Attachment_Content__c LIMIT 1];

        Test.startTest();
        Id attachmentId = AttachmentContentController.downloadAttachmentContent(attContent.Id);

        System.assertEquals([SELECT Id FROM Attachment LIMIT 1].Id, attachmentId);
        Test.stopTest();
    }

    @isTest static void removeAttachmentContentTest() {
        Attachment_Content__c attContent = [SELECT Id FROM Attachment_Content__c LIMIT 1];

        Test.startTest();
        AttachmentContentController.removeAttachmentContent(attContent.Id);

        System.assertEquals(0, [SELECT Id FROM Attachment_Content__c].size());
        System.assertEquals(0, [SELECT Id FROM Attachment].size());

        try {
            AttachmentContentController.removeAttachmentContent(attContent.Id);
        } catch (Exception e) {}
        Test.stopTest();
    }
}