Salesforce/main/default/objects/Account/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Estado</label>
    <referenceTo>Estado__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Account/fields/Plano_de_Auditoria__c.field-meta.xml
<CustomField>
    <fullName>Plano_de_Auditoria__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plano de Auditoria</label>
    <referenceTo>Plano_de_Auditoria__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IMAGE( CASE( Status_Base__c , &quot;Verde&quot;, &quot;/img/samples/light_green.gif&quot;, &quot;Amarelo&quot;, &quot;/img/samples/light_yellow.gif&quot;, &quot;Vermelho&quot;, &quot;/img/samples/light_red.gif&quot;, &quot;/s.gif&quot;), &quot;Status da conta&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status BMX</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/Calendar_Event__c/Calendar_Event__c.object-meta.xml
<CustomObject>
    <label>Calendar Event</label>
    <nameField>
        <label>Event Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Calendar Event</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Salesforce/main/default/objects/Calendar_Event__c/fields/Plano_de_Auditoria__c.field-meta.xml
<CustomField>
    <fullName>Plano_de_Auditoria__c</fullName>
    <label>Plano de Auditoria</label>
    <referenceTo>Plano_de_Auditoria__c</referenceTo>
    <relationshipLabel>Visita</relationshipLabel>
    <relationshipName>Visita</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Salesforce/main/default/objects/Calendar_Event__c/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <label>Safra</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Safra</valueSetName>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Calendar_Event__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pendente</fullName>
                <default>true</default>
                <label>Pendente</label>
            </value>
            <value>
                <fullName>Concluída</fullName>
            </value>
            <value>
                <fullName>Cancelada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Configuracion_BMX__c/Configuracion_BMX__c.object-meta.xml
<CustomObject>
    <description>Indicador de Parametros.</description>
    <label>Configuracion_BMX</label>
    <nameField>
        <label>Configuracion Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuraciones_BMX</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/Configuracion_BMX__c/fields/PM_Safra_Actual_DescontoRoyalty__c.field-meta.xml
<CustomField>
    <fullName>PM_Safra_Actual_DescontoRoyalty__c</fullName>
    <label>PM Safra Actual DescontoRoyalty</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/Estado__c/Estado__c.object-meta.xml
<CustomObject>
    <label>Estado</label>
    <nameField>
        <label>Nome do Estado</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estados</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/objects/Opportunity/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <formula>IF(NOT(ISNULL(Inicio_Cargamento__c)),
			IF(NOT(ISNULL(Inicio_Transporte__c)),
						IF(NOT(ISNULL(Fin_Transporte__c)),
									IF(AND(Confirmado__c,NOT(Solicitacao_de_reembolso__c)),
											&apos;Confirmado&apos;,
											IF(AND(Solicitacao_de_reembolso__c,NOT(Confirmado__c)),
													&apos;Em Troca&apos;,
													&apos;Entregue&apos;)
											),
									&apos;Pedido em trânsito&apos;),
						&apos;Em carregamento&apos;),
			&apos;&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status de transporte</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/Opportunity/fields/Plano_de_Auditoria__c.field-meta.xml
<CustomField>
    <fullName>Plano_de_Auditoria__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plano de Auditoria</label>
    <referenceTo>Plano_de_Auditoria__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Anexos</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Opportunity/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <description>Safra o Campania agricola</description>
    <label>Safra</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>06/07</fullName>
            </value>
            <value>
                <fullName>07/08</fullName>
            </value>
            <value>
                <fullName>08/09</fullName>
            </value>
            <value>
                <fullName>09/10</fullName>
            </value>
            <value>
                <fullName>09/09</fullName>
            </value>
            <value>
                <fullName>10/10</fullName>
            </value>
            <value>
                <fullName>10/11</fullName>
            </value>
            <value>
                <fullName>11/11</fullName>
            </value>
            <value>
                <fullName>11/12</fullName>
            </value>
            <value>
                <fullName>12/12</fullName>
            </value>
            <value>
                <fullName>12/13</fullName>
            </value>
            <value>
                <fullName>13/14</fullName>
            </value>
            <value>
                <fullName>14/15</fullName>
            </value>
            <value>
                <fullName>15/16</fullName>
            </value>
            <value>
                <fullName>16/17</fullName>
            </value>
            <value>
                <fullName>17/18</fullName>
            </value>
            <value>
                <fullName>18/19</fullName>
            </value>
            <value>
                <fullName>19/20</fullName>
            </value>
            <value>
                <fullName>20/21</fullName>
            </value>
            <value>
                <fullName>21/22</fullName>
                <default>true</default>
                <label>21/22</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Opportunity/fields/Saldo_por_safra__c.field-meta.xml
<CustomField>
    <fullName>Saldo_por_safra__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relacion al saldo con el safra actual</description>
    <label>Saldo por safra</label>
    <referenceTo>Saldo_por_safra__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/Opportunity/recordTypes/Comercial.recordType-meta.xml
<RecordType>
    <fullName>Comercial</fullName>
    <active>true</active>
    <businessProcess>Control_Multiplicador</businessProcess>
    <description>Detalle de lo que el multiplicador va a vender: relatorio de venda</description>
    <label>Comercial</label>
</RecordType>

Salesforce/main/default/main/default/objects/OpportunityLineItem/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Estado</label>
    <referenceTo>Estado__c</referenceTo>
    <relationshipLabel>Producto de oportunidad (Estado)</relationshipLabel>
    <relationshipName>Producto_de_oportunidad2</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/OpportunityLineItem/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <formula>TEXT(Opportunity.Safra__c)</formula>
    <label>Safra</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/Plano_de_Auditoria__c/Plano_de_Auditoria__c.object-meta.xml
<CustomObject>
    <label>Plano de Auditoria</label>
    <nameField>
        <displayFormat>PA-{0000}</displayFormat>
        <label>Nombre de Plano de Auditoria</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Planos de Auditoria</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/Plano_de_Auditoria__c/fields/Cuenta_Principal__c.field-meta.xml
<CustomField>
    <fullName>Cuenta_Principal__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Cuenta Principal</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Plano de Auditoria</relationshipLabel>
    <relationshipName>Plano_de_Auditoria</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Plano_de_Auditoria__c/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <label>Safra</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Safra</valueSetName>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Plano_de_Auditoria__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Não Iniciado</fullName>
                <default>true</default>
                <label>Não Iniciado</label>
            </value>
            <value>
                <fullName>Em andamento</fullName>
            </value>
            <value>
                <fullName>Concluido</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
            <value>
                <fullName>Auditado</fullName>
                <isActive>false</isActive>
                <label>Auditado</label>
            </value>
            <value>
                <fullName>Pendente</fullName>
                <isActive>false</isActive>
                <label>Pendente</label>
            </value>
            <value>
                <fullName>Rejeitado</fullName>
                <isActive>false</isActive>
                <label>Rejeitado</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Producto_Auditado__c/Producto_Auditado__c.object-meta.xml
<CustomObject>
    <label>Producto Auditado</label>
    <nameField>
        <label>Nombre de Producto Auditado</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Productos Auditados</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/objects/Producto_Auditado__c/fields/Plano_de_Auditoria__c.field-meta.xml
<CustomField>
    <fullName>Plano_de_Auditoria__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plano de Auditoria</label>
    <referenceTo>Plano_de_Auditoria__c</referenceTo>
    <relationshipLabel>Productos Auditados</relationshipLabel>
    <relationshipName>Productos_Auditados</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Saldo_por_safra__c/Saldo_por_safra__c.object-meta.xml
<CustomObject>
    <label>Saldo por safra</label>
    <nameField>
        <label>Nombre de Saldo por safra</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Saldos por safra</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Salesforce/main/default/objects/Saldo_por_safra__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Activo</fullName>
            </value>
            <value>
                <fullName>Inactivo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Saldo_por_safra__c/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <label>Safra</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/SiteUser__c/SiteUser__c.object-meta.xml
<CustomObject>
    <description>Forma parte del circuito del Sitio Portal Web.</description>
    <label>SiteUser</label>
    <nameField>
        <label>Nombre de Usuário</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SiteUsers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/SiteUserAccount__c/SiteUserAccount__c.object-meta.xml
<CustomObject>
    <label>SiteUserAccount</label>
    <nameField>
        <label>Nombre de SiteUserAccount</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SiteUserAccounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/SiteUserAccount__c/fields/SiteUser__c.field-meta.xml
<CustomField>
    <fullName>SiteUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SiteUser</label>
    <referenceTo>SiteUser__c</referenceTo>
    <relationshipLabel>SiteUserAccounts</relationshipLabel>
    <relationshipName>SiteUserAccounts</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/SiteUserSession__c/SiteUserSession__c.object-meta.xml
<CustomObject>
    <label>SiteUserSession</label>
    <nameField>
        <displayFormat>S{00000000}</displayFormat>
        <label>Nombre de SiteUserSession</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SiteUserSessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/SiteUserSession__c/fields/SiteUser__c.field-meta.xml
<CustomField>
    <fullName>SiteUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SiteUser</label>
    <referenceTo>SiteUser__c</referenceTo>
    <relationshipLabel>SiteUserSessions</relationshipLabel>
    <relationshipName>SiteUserSessions</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/globalValueSets/Safra.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>14/15</fullName>
    </customValue>
    <customValue>
        <fullName>15/16</fullName>
    </customValue>
    <customValue>
        <fullName>16/17</fullName>
    </customValue>
    <customValue>
        <fullName>17/18</fullName>
    </customValue>
    <customValue>
        <fullName>18/19</fullName>
    </customValue>
    <customValue>
        <fullName>19/20</fullName>
    </customValue>
    <customValue>
        <fullName>20/21</fullName>
    </customValue>
    <customValue>
        <fullName>21/22</fullName>
    </customValue>
    <customValue>
        <fullName>22/23</fullName>
    </customValue>
    <customValue>
        <fullName>23/24</fullName>
    </customValue>
    <customValue>
        <fullName>08/09</fullName>
        <isActive>false</isActive>
        <label>08/09</label>
    </customValue>
    <customValue>
        <fullName>07/08</fullName>
        <isActive>false</isActive>
        <label>07/08</label>
    </customValue>
    <customValue>
        <fullName>10/11</fullName>
        <isActive>false</isActive>
        <label>10/11</label>
    </customValue>
    <customValue>
        <fullName>11/12</fullName>
        <isActive>false</isActive>
        <label>11/12</label>
    </customValue>
    <customValue>
        <fullName>12/13</fullName>
        <isActive>false</isActive>
        <label>12/13</label>
    </customValue>
    <customValue>
        <fullName>13/14</fullName>
        <isActive>false</isActive>
        <label>13/14</label>
    </customValue>
    <customValue>
        <fullName>09/10</fullName>
        <isActive>false</isActive>
        <label>09/10</label>
    </customValue>
    <masterLabel>Safra</masterLabel>
</GlobalValueSet>

Salesforce/main/default/classes/AuditarVisitaControllerTest.cls
@isTest 
private class AuditarVisitaControllerTest {

    @isTest static void getOnePlanoWith3Products() {
        Plano_de_Auditoria__c plano = [SELECT Id FROM Plano_de_Auditoria__c LIMIT 1];        
        Test.setCurrentPageReference(new PageReference('Page.AuditarVisitaController'));
        System.currentPageReference().getParameters().put('Id', plano.Id);
        System.currentPageReference().getParameters().put('Safra', '16/17');
        ApexPages.StandardController sc = new ApexPages.StandardController(plano);
        Integer cantidadDeProductos = 0;
        Test.startTest();
		AuditarVisitaController controller = new AuditarVisitaController(sc);
		cantidadDeProductos = controller.productosDelPlano.size();
		controller.save();
		controller.goToCalendario();
		controller.goToObservaciones();
		controller.goToPlano();
		controller.generatePDF();
        Test.stopTest();
        System.assertEquals(3, cantidadDeProductos);
    }

    @TestSetup static void setup() {
		Profile profileSupervisor = [SELECT Id FROM Profile WHERE Name = 'Comercial LE' LIMIT 1];
        Profile profileGerente = [SELECT Id FROM Profile WHERE Name = 'Gerente LE' LIMIT 1];

        User supervisor = Build.anUser()
            .withFirstName('Rosa')
            .withLastName('Jorge Cristiano')
            .withAlias('jcr')
            .withEmail('jorge.rosa@asdf.com')
            .withUsername('jorge.rosa@asdf.com')
            .withProfileId(profileSupervisor)
            .withCommunityNickname('jcr')
            .build();

        User gerente = Build.anUser()
            .withFirstName('Sergio Vieira')
            .withLastName('Bertagnolli')
            .withAlias('svb')
            .withEmail('sergio.bertagnolli@asdf.com')
            .withUsername('sergio.bertagnolli@asdf.com')
            .withProfileId(profileGerente)
            .withCommunityNickname('svb')
            .build();

        User[] users = new User[]{supervisor, gerente};
        insert users;

		Account testAccount = Build.anAccount()
			.withName('Test account')
			.withType('Multiplicador')
			.withMultiplicador(true)
			.withMarca('BRMX')
			.withSupervisor(supervisor)
			.withGerenteComercial(gerente)
			.build();

		insert testAccount;

		SiteUser__c testSiteUser = Build.aSiteUser()
            .withName('Test site user')
            .withEmail('testsu@test.com')
            .withPassword('test')
            .withActive(true)
            .withHabilitadoAnexos(true)
            .build();

		insert testSiteUser;

		Estado__c estado = Build.anEstado()
            .withMostrarenportal(true)
            .withName('Estado test')
            .build();

		insert estado;

		SiteUserAccount__c testSiteUserAccount = Build.aSiteUserAccount()
            .withName('Test site user account')
            .withAccount(testAccount)
            .withSiteUser(testSiteUser)
            .withActive(true)
            .build();

		insert testSiteUserAccount;

		SiteUserSession__c testSiteUserSession = Build.aSiteUserSession()
            .withSiteUser(testSiteUser)
            .withMarca('BRMX')
            .withSafra('18/19')
            .build();

		insert testSiteUserSession;

		Configuracion_BMX__c testConfiguracionBMX = Build.aConfiguracionBMX().build();
		insert testConfiguracionBMX;
		testConfiguracionBMX.PM_Safra_Actual_DescontoRoyalty__c = '18/19';
		update testConfiguracionBMX;

		Saldo_por_safra__c saldoPorSafra = Build.aSaldoPorSafra()
            .withAccount(testAccount)
            .withSaldo(10)
            .withSafra('18/19')
            .build();

        insert saldoPorSafra;

        Opportunity opportunity = Build.anOpportunityAnexoI()
			.withName('Anexo 1')
			.withAccountId(testAccount)
			.withStageName('Aberta')
			.withPricebook2Id(Test.getStandardPricebookId())
			.withCloseDate(Date.today())
			.build();

        insert opportunity;

        Product2 product2Test = Build.aProduct2()
			.withName('BMX DESAFIO RR - Basica  (G)')
			.withIsActive(true)
			.withFamily('Semilla')
			.withVariedad('BMX DESAFIO RR')
			.withCategoria('BASICA')
			.withPrice(Double.valueOf(0.1))
			.withSociedad('BRMX')
			.withUnidad('KG')
			.withCantSubUnidad('1')
			.build();

        insert product2Test;

        PricebookEntry pricebookE = Build.aPricebookEntry()
			.withProduct2Id(product2Test)
			.withPricebook2Id(Test.getStandardPricebookId())
			.withUnitPrice(0.1)
			.withIsActive(true)
			.build();

        insert pricebookE;
        
        OpportunityLineItem[] OLIs = new OpportunityLineItem[2];

        OLIs[0] = Build.anOpportunityLineItem()
			.withOpportunityId(opportunity)
			.withPricebookEntryId(pricebookE)
			.withQuantity(10)
			.withUnitPrice(0.1)
			.build();

        OLIs[1] = Build.anOpportunityLineItem()
			.withOpportunityId(opportunity)
			.withPricebookEntryId(pricebookE)
			.withQuantity(10)
			.withUnitPrice(0.1)
			.build();

        insert OLIs;

        Plano_de_Auditoria__c plano = new Plano_de_Auditoria__c(
            Cuenta_Principal__c = testAccount.Id,
            Safra__c = '16/17',
            Status__c = 'Não Iniciado'
        );

        insert plano;

        Calendar_Event__c visita = new Calendar_event__c(
            Plano_de_Auditoria__c = plano.Id,
            Start_Time__c = System.Today(),
            End_Time__c = System.today().addDays(1)
        );

        insert visita;

		Producto_Auditado__c[] productos = new Producto_Auditado__c[]{
			new Producto_Auditado__c(
				Plano_de_Auditoria__c = plano.Id,
				Safra__c = '16/17'
			),
			new Producto_Auditado__c(
				Plano_de_Auditoria__c = plano.Id,
				Safra__c = '16/17'
			),
			new Producto_Auditado__c(
				Plano_de_Auditoria__c = plano.Id,
				Safra__c = '16/17'
			)
		};

        insert productos;
    }
}