Salesforce/main/default/objects/Account/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Estado</label>
    <referenceTo>Estado__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/Account/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Marca</valueSetName>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Cidade__c/Cidade__c.object-meta.xml
<CustomObject>
    <label>Ciudad</label>
    <nameField>
        <label>Nome da Cidade</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ciudades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/Cidade__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Estado</label>
    <referenceTo>Estado__c</referenceTo>
    <relationshipName>Cidades</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Evento_Royalty__c/Evento_Royalty__c.object-meta.xml
<CustomObject>
    <label>Evento Royalty</label>
    <nameField>
        <label>Nombre de Evento Royalty</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Eventos Royalty</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/Evento_Royalty__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pendiente de aprobación</fullName>
                <label>Aprovação pendente</label>
            </value>
            <value>
                <fullName>Aprobado</fullName>
                <label>Aprovado</label>
            </value>
            <value>
                <fullName>Edicion</fullName>
                <default>true</default>
                <label>Edição</label>
            </value>
            <value>
                <fullName>Anulado</fullName>
            </value>
            <value>
                <fullName>Rechazado</fullName>
                <isActive>false</isActive>
                <label>Rechazado</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Evento_Royalty__c/fields/Items__c.field-meta.xml
<CustomField>
    <fullName>Items__c</fullName>
    <label>Items</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Placas</fullName>
            </value>
            <value>
                <fullName>Outdoor</fullName>
            </value>
            <value>
                <fullName>Camiseta</fullName>
            </value>
            <value>
                <fullName>Palestrante</fullName>
            </value>
            <value>
                <fullName>Outros</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Evento_Royalty__c/fields/Saldo_por_safra__c.field-meta.xml
<CustomField>
    <fullName>Saldo_por_safra__c</fullName>
    <label>Saldo por safra</label>
    <referenceTo>Saldo_por_safra__c</referenceTo>
    <relationshipLabel>Eventos Royalty</relationshipLabel>
    <relationshipName>Eventos_Royalty</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Salesforce/main/default/objects/Evento_Royalty_Item__c/Evento_Royalty_Item__c.object-meta.xml
<CustomObject>
    <description>Items relacionados al evento Royalty</description>
    <label>Evento Royalty Item</label>
    <nameField>
        <label>Nombre de Evento Royalty</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Evento Royalty Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/objects/Evento_Royalty_Item__c/fields/Evento_Royalty__c.field-meta.xml
<CustomField>
    <fullName>Evento_Royalty__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Evento Royalty</label>
    <referenceTo>Evento_Royalty__c</referenceTo>
    <relationshipLabel>Evento Royalty Items</relationshipLabel>
    <relationshipName>Evento_Royalty_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/Evento_Royalty_Item__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <label>Item</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Comunicação em rádio</fullName>
            </value>
            <value>
                <fullName>Outdoor</fullName>
            </value>
            <value>
                <fullName>Palestrante</fullName>
            </value>
            <value>
                <fullName>Palestras</fullName>
                <label>Palestras e Treinamentos</label>
            </value>
            <value>
                <fullName>Placas</fullName>
            </value>
            <value>
                <fullName>Outros</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Opportunity/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <formula>IF(NOT(ISNULL(Inicio_Cargamento__c)),
			IF(NOT(ISNULL(Inicio_Transporte__c)),
						IF(NOT(ISNULL(Fin_Transporte__c)),
									IF(AND(Confirmado__c,NOT(Solicitacao_de_reembolso__c)),
											&apos;Confirmado&apos;,
											IF(AND(Solicitacao_de_reembolso__c,NOT(Confirmado__c)),
													&apos;Em Troca&apos;,
													&apos;Entregue&apos;)
											),
									&apos;Pedido em trânsito&apos;),
						&apos;Em carregamento&apos;),
			&apos;&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status de transporte</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/Opportunity/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <description>Identifica la marca para las Oportunidades del Circuito de Anexos. Se selecciona la lista de precios en función de este campo</description>
    <inlineHelpText>Identificar a marca de Oportunidades Circuito Anexos. Você seleciona a lista de preços com base neste campo</inlineHelpText>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BRMX</fullName>
            </value>
            <value>
                <fullName>DSEM</fullName>
            </value>
            <value>
                <fullName>NEOG</fullName>
            </value>
            <value>
                <fullName>DAGMA</fullName>
            </value>
            <value>
                <fullName>LICENÇAS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Opportunity/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <description>Safra o Campania agricola</description>
    <label>Safra</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>06/07</fullName>
            </value>
            <value>
                <fullName>07/08</fullName>
            </value>
            <value>
                <fullName>08/09</fullName>
            </value>
            <value>
                <fullName>09/10</fullName>
            </value>
            <value>
                <fullName>09/09</fullName>
            </value>
            <value>
                <fullName>10/10</fullName>
            </value>
            <value>
                <fullName>10/11</fullName>
            </value>
            <value>
                <fullName>11/11</fullName>
            </value>
            <value>
                <fullName>11/12</fullName>
            </value>
            <value>
                <fullName>12/12</fullName>
            </value>
            <value>
                <fullName>12/13</fullName>
            </value>
            <value>
                <fullName>13/14</fullName>
            </value>
            <value>
                <fullName>14/15</fullName>
            </value>
            <value>
                <fullName>15/16</fullName>
            </value>
            <value>
                <fullName>16/17</fullName>
            </value>
            <value>
                <fullName>17/18</fullName>
            </value>
            <value>
                <fullName>18/19</fullName>
            </value>
            <value>
                <fullName>19/20</fullName>
            </value>
            <value>
                <fullName>20/21</fullName>
            </value>
            <value>
                <fullName>21/22</fullName>
                <default>true</default>
                <label>21/22</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Opportunity/fields/Saldo_por_safra__c.field-meta.xml
<CustomField>
    <fullName>Saldo_por_safra__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relacion al saldo con el safra actual</description>
    <label>Saldo por safra</label>
    <referenceTo>Saldo_por_safra__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Opportunity/recordTypes/Pendiente.recordType-meta.xml
<RecordType>
    <fullName>Pendiente</fullName>
    <active>true</active>
    <businessProcess>Nota de Venta - Pendiente</businessProcess>
    <label>Pendiente</label>
</RecordType>

Salesforce/main/default/main/default/objects/Order/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Marca</valueSetName>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Order/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <label>Safra</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Safra</valueSetName>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Saldo_por_safra__c/Saldo_por_safra__c.object-meta.xml
<CustomObject>
    <label>Saldo por safra</label>
    <nameField>
        <label>Nombre de Saldo por safra</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Saldos por safra</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/Saldo_por_safra__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Saldos por safra</relationshipLabel>
    <relationshipName>Saldos_por_safra</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Salesforce/main/default/objects/Saldo_por_safra__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Activo</fullName>
            </value>
            <value>
                <fullName>Inactivo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Saldo_por_safra__c/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Marca</valueSetName>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Saldo_por_safra__c/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <label>Safra</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/Saldo_por_safra__c/fields/Saldo__c.field-meta.xml
<CustomField>
    <fullName>Saldo__c</fullName>
    <label>Saldo Inicial</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Salesforce/main/default/main/default/objects/Saldo_por_safra__c/fields/Saldo_Disponible__c.field-meta.xml
<CustomField>
    <fullName>Saldo_Disponible__c</fullName>
    <formula>Saldo__c - Saldo_Gastado__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Saldo Disponível</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Salesforce/main/default/main/default/objects/SiteUserSession__c/SiteUserSession__c.object-meta.xml
<CustomObject>
    <label>SiteUserSession</label>
    <nameField>
        <displayFormat>S{00000000}</displayFormat>
        <label>Nombre de SiteUserSession</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SiteUserSessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/SiteUserSession__c/fields/SiteUser__c.field-meta.xml
<CustomField>
    <fullName>SiteUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SiteUser</label>
    <referenceTo>SiteUser__c</referenceTo>
    <relationshipLabel>SiteUserSessions</relationshipLabel>
    <relationshipName>SiteUserSessions</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/globalValueSets/Marca.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BRMX</fullName>
    </customValue>
    <customValue>
        <fullName>DSEM</fullName>
    </customValue>
    <customValue>
        <fullName>NEOG</fullName>
    </customValue>
    <customValue>
        <fullName>DAGMA</fullName>
    </customValue>
    <customValue>
        <fullName>LICENÇAS</fullName>
    </customValue>
    <masterLabel>Marca</masterLabel>
</GlobalValueSet>

Salesforce/main/default/globalValueSets/Safra.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>14/15</fullName>
    </customValue>
    <customValue>
        <fullName>15/16</fullName>
    </customValue>
    <customValue>
        <fullName>16/17</fullName>
    </customValue>
    <customValue>
        <fullName>17/18</fullName>
    </customValue>
    <customValue>
        <fullName>18/19</fullName>
    </customValue>
    <customValue>
        <fullName>19/20</fullName>
    </customValue>
    <customValue>
        <fullName>20/21</fullName>
    </customValue>
    <customValue>
        <fullName>21/22</fullName>
    </customValue>
    <customValue>
        <fullName>22/23</fullName>
    </customValue>
    <customValue>
        <fullName>23/24</fullName>
    </customValue>
    <customValue>
        <fullName>08/09</fullName>
        <isActive>false</isActive>
        <label>08/09</label>
    </customValue>
    <customValue>
        <fullName>07/08</fullName>
        <isActive>false</isActive>
        <label>07/08</label>
    </customValue>
    <customValue>
        <fullName>10/11</fullName>
        <isActive>false</isActive>
        <label>10/11</label>
    </customValue>
    <customValue>
        <fullName>11/12</fullName>
        <isActive>false</isActive>
        <label>11/12</label>
    </customValue>
    <customValue>
        <fullName>12/13</fullName>
        <isActive>false</isActive>
        <label>12/13</label>
    </customValue>
    <customValue>
        <fullName>13/14</fullName>
        <isActive>false</isActive>
        <label>13/14</label>
    </customValue>
    <customValue>
        <fullName>09/10</fullName>
        <isActive>false</isActive>
        <label>09/10</label>
    </customValue>
    <masterLabel>Safra</masterLabel>
</GlobalValueSet>

Salesforce/main/default/classes/aSiteSaldoSafraController.cls
public class aSiteSaldoSafraController  {
    
    private String token;
    private SiteUser__c logUser;
    private SiteUserSession__c activeSession;
    public Account activeAccount            {get; set;}
    public Saldo_por_safra__c saldoActual   {get; set;}
    public String safraActual               {get; set;}
    
    public Boolean renderSaldo              {get; set;}
    public Boolean activeNuevoEvento        {get; set;}
    
    public List<Evento_Royalty__c> eventos  {get; set;}
    public List<Opportunity> opps           {get; set;}
    public Id eventoId                      {get; set;}
    public List<Evento_Royalty_Item__c> itemsDelEvento {get; set;}    
    
    public String categoria                 {get; set;} 
    public Double porcBrindes               {get; set;} 
    public Opportunity montoBrindes         {get; set;}   
    public String mensaje                   {get; set;} 
    public String tipoSel                   {get; set;}
    
    public aSiteSaldoSafraController(){
        itemsDelEvento = new List<Evento_Royalty_Item__c>();
    }
    
    public PageReference validate() {  
        
        activeNuevoEvento = true;
        
        token = System.currentPageReference().getParameters().get('token'); 
        
        if(token!=null){
            logUser = aSiteAuthManager.VerifyUserSession(token);
            if(logUser!=null){
                activeSession = aSiteAuthManager.getUserSession(token);
                activeAccount = aSiteAuthManager.getActiveAccount_byUser(logUser);
                safraActual = aAppManager.getSafraActualByApp('DescontoRoyalty');
                setItems();
                return null;
            }
            else {
                activeNuevoEvento = false;
            }
        }
        else {
            activeNuevoEvento = false;
        }       
        
        PageReference p = new PageReference('/apex/aSiteLogin');
        String marca = aSiteAuthManager.getMarcaBySession(token);
        if (marca != null)
            p.getParameters().put('comp',marca);
        p.setRedirect(true);
        return p;
        
    }
    
    public void setItems() {
        eventos = new List<Evento_Royalty__c>();
        List<Saldo_por_safra__c> saldo = [SELECT Id, Saldo_Disponible__c, Saldo__c, Estado__c 
                                          FROM Saldo_por_safra__c 
                                          WHERE Safra__c = :safraActual AND Account__c =: activeAccount.Id AND Marca__c =: activeSession.Marca__c
                                          LIMIT 1];
        if(saldo.isEmpty()){
            renderSaldo = false;
            activeNuevoEvento = false;
        }
        else {
            renderSaldo = true;
            saldoActual = saldo[0];
            
            List<Evento_Royalty__c> royalties = [SELECT Id, Fecha__c, Items__c, Name,
                                                 Comentarios__c, Valor__c,
                                                 Estado__c, Accion__c 
                                                 FROM Evento_Royalty__c 
                                                 WHERE Cuenta__c =: activeAccount.Id 
                                                 AND Safra__c =: safraActual AND Marca__c =: activeSession.Marca__c
                                                 ORDER BY CreatedDate DESC];    
            
            for(Evento_Royalty__c royalty : royalties) {
                if (royalty.Estado__c.containsIgnoreCase('Pendiente') || royalty.Estado__c.containsIgnoreCase('Edicion')) {
                    activeNuevoEvento = false;
                }
                eventos.add(royalty);
            }
            //eventos = sortByDate(eventos);
            if(saldoActual.Saldo_Disponible__c <= 0) {
                activeNuevoEvento = false;
            }                                       
            
            categoria = 'Categoria 1';
            porcBrindes = 60;            
            
            if (saldoActual.Saldo__c >= 100000 && saldoActual.Saldo__c < 200000){
                categoria = 'Categoria 2';
                porcBrindes = 50;    
            } 
               
            if (saldoActual.Saldo__c >= 200000 && saldoActual.Saldo__c < 300000){
                categoria = 'Categoria 3';
                porcBrindes = 40;
            }    
                
            if (saldoActual.Saldo__c >= 300000 && saldoActual.Saldo__c < 400000){
                categoria = 'Categoria 4';
                porcBrindes = 30;
            }    
                
            if (saldoActual.Saldo__c >= 400000 && saldoActual.Saldo__c < 600000){
                categoria = 'Categoria 5';
                porcBrindes = 20;
            }    
                
            if (saldoActual.Saldo__c >= 600000){
                categoria = 'Categoria 6'; 
                porcBrindes = 15;
            }    
            
            montoBrindes = New Opportunity();
            montoBrindes.Amount = (porcBrindes * saldoActual.Saldo__c / 100).divide(1, 2, System.RoundingMode.HALF_EVEN);
            
        }
        
    }
    
    public String getTextoFecha(Date fecha) {
        String textoFecha = fecha.day() + '/' + fecha.month() + '/' + fecha.year();
        return textoFecha;
    }
    
    public PageReference goToCreateRoyaltyEventPedido() {
        String token = System.currentPageReference().getParameters().get('token');
        PageReference pr = new PageReference('/apex/aSiteCreateRoyaltyEvent');
        pr.setRedirect(true);
        pr.getParameters().put('token',token);
        pr.getParameters().put('tipo','Pedido');
        return pr;
    }
    
    public Boolean validateSecuenciaTipos(String paso) {
        Double brindes = 0;
        Boolean hayOutdoor = false;
        for (AggregateResult ar : [Select Tipo__c tipo, Sum(Valor__c) valor From Evento_Royalty_Item__c Where Evento_Royalty__r.Saldo_por_safra__c = :saldoActual.Id And Evento_Royalty__r.Estado__c = 'Aprobado' Group By Tipo__c]){
            if (String.valueOf(ar.get('tipo')) == 'Brinde')
                brindes = Double.valueOf(ar.get('valor'));        
            if (String.valueOf(ar.get('tipo')) == 'Outdoor')    
                hayOutdoor = true;
        }
        
        if (paso == 'irReembolso' && (!validarBrindesCategoria(brindes) || !hayOutdoor))
            return false;   
            
        List<Evento_Royalty_Item__c> items = New List<Evento_Royalty_Item__c>();
        items = [Select Tipo__c, Valor__c From Evento_Royalty_Item__c Where Evento_Royalty__c =: eventoId];

        for (Evento_Royalty_Item__c i : items){
            if (i.Tipo__c == 'Brinde')
                brindes += i.Valor__c;        
            if (i.Tipo__c == 'Outdoor')    
                hayOutdoor = true;
        }       
        
        for (Evento_Royalty_Item__c i : items){
            if (i.Tipo__c == 'Outdoor')
                if (validarBrindesCategoria(brindes)){
                    break;
                }else{
                    return false;
                }
        }
        
        for (Evento_Royalty_Item__c i : items){
            if (i.Tipo__c != 'Brinde' && i.Tipo__c != 'Outdoor')
                if (validarBrindesCategoria(brindes) && hayOutdoor){
                    break;
                }else{
                    return false;
                }
        }
        
        return true;
        
    }
    
    public Boolean validarBrindesCategoria (Double brindes){
    
        if (brindes < montoBrindes.Amount)
            return false;                                
                
        return true;        
    
    }
    
    public PageReference goToCreateRoyaltyEventReembolso() {
        
        mensaje = '';
        
        if(!validateSecuenciaTipos('irReembolso')) {
            mensaje = 'Você não solicitou o valor mínimo necessário em brindes e/ou outdoor.';
            return null;
        }                  
        
        String token = System.currentPageReference().getParameters().get('token');
        PageReference pr = new PageReference('/apex/aSiteCreateRoyaltyEvent');
        pr.setRedirect(true);
        pr.getParameters().put('token',token);
        pr.getParameters().put('tipo','Reembolso');
        return pr;
    }
    
    public void verItems(){
        itemsDelEvento = [SELECT Id, Item__c, Valor__c, Data__c, 
                          Comentario__c, Evento_Royalty__c, Variedad__r.Name, UF__r.Name, Cidade__c, Quantidade__c, Tipo__c, Valor_Unitario__c, Evento_Royalty__r.Accion__c, Modelo__c, Tamanio__c
                          FROM Evento_Royalty_Item__c
                          WHERE Evento_Royalty__c = :eventoId];
                          
        tipoSel = itemsDelEvento[0].Evento_Royalty__r.Accion__c;
        
    }
    
    public PageReference editar(){
        Evento_Royalty__c roy = [SELECT Id, Accion__c 
                                         FROM Evento_Royalty__c 
                                         WHERE Id =: eventoId 
                                         limit 1];          
        String token = System.currentPageReference().getParameters().get('token');
        PageReference pr = new PageReference('/apex/aSiteCreateRoyaltyEvent');
        pr.setRedirect(true);
        pr.getParameters().put('token',token);
        pr.getParameters().put('eventoId',eventoId);
        pr.getParameters().put('tipo',roy.Accion__c);
        return pr;
    }
    
    public void enviarParaAprobacion(){
        
        mensaje = '';
        
        if(!validateSecuenciaTipos('enviarAprobacion')) {
            mensaje = 'Você não solicitou o valor mínimo necessário em brindes e/ou outdoor.';
            return;
        }
        
        Evento_Royalty__c evento = [SELECT Id, Name, Estado__c
                                    FROM Evento_Royalty__c
                                    WHERE Id = :eventoId];
        
        evento.Estado__c = 'Pendiente de aprobación';
        update evento;
        setItems();
    }
    
}