Salesforce/main/default/objects/Account/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Estado</label>
    <referenceTo>Estado__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/Account/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Marca</valueSetName>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Account/fields/Multiplicador__c.field-meta.xml
<CustomField>
    <fullName>Multiplicador__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Multiplicador</label>
    <type>Checkbox</type>
</CustomField>

Salesforce/main/default/main/default/objects/Account/recordTypes/Cuenta.recordType-meta.xml
<RecordType>
    <fullName>Cuenta</fullName>
    <active>true</active>
    <label>Cuenta</label>
</RecordType>

Salesforce/main/default/main/default/objects/Contrato__c/Contrato__c.object-meta.xml
<CustomObject>
    <description>CONTRATO DE LICENCIAMENTO PARA MULTIPLICAÇÃO E COMERCIALIZAÇÃO</description>
    <label>Contrato de Multiplicação</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Numero do Contrato de Multiplicação</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contratos de Multiplicação</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Salesforce/main/default/objects/Contrato__c/fields/Aditivo_Facturado__c.field-meta.xml
<CustomField>
    <fullName>Aditivo_Facturado__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indica si se facturó el aditivo y lo inhabilita para volver a utilizarlo.</description>
    <label>Aditivo Facturado</label>
    <type>Checkbox</type>
</CustomField>

Salesforce/main/default/main/default/objects/Contrato__c/fields/Cotacao_de_soja__c.field-meta.xml
<CustomField>
    <fullName>Cotacao_de_soja__c</fullName>
    <description>No pagamento dos Royalties, usamos a cotação de soja de duas empresas, dependendo da região da conta</description>
    <inlineHelpText>No pagamento dos Royalties, usamos a cotação de soja de duas empresas, dependendo da região da conta</inlineHelpText>
    <label>Cotação de soja</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Tipo_de_Cota_o__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>COAMO</fullName>
            </value>
            <value>
                <fullName>COTRIJAL</fullName>
            </value>
            <value>
                <fullName>SAFRAS &amp; MERCADO</fullName>
            </value>
            <value>
                <fullName>CHICAGO</fullName>
            </value>
            <value>
                <fullName>C. VALE</fullName>
            </value>
            <value>
                <fullName>ADM</fullName>
            </value>
            <value>
                <fullName>ASUNCION</fullName>
            </value>
            <value>
                <fullName>S&amp;M - Campo Grande (MS)</fullName>
            </value>
            <value>
                <fullName>S&amp;M - Rio Verde (GO)</fullName>
            </value>
            <value>
                <fullName>S&amp;M - Sorriso (MT)</fullName>
            </value>
            <value>
                <fullName>S&amp;M - Passo Fundo (RS)</fullName>
            </value>
            <value>
                <fullName>S&amp;M - Londrina (PR)</fullName>
            </value>
            <value>
                <fullName>S&amp;M - Rondonópolis (MT)</fullName>
            </value>
            <value>
                <fullName>S&amp;M - Barreiras (BA)</fullName>
            </value>
            <value>
                <fullName>S&amp;M - Uberlandia (MG)</fullName>
            </value>
            <value>
                <fullName>S&amp;M - Diamantino (MT)</fullName>
            </value>
            <value>
                <fullName>S&amp;M - Pedro Afonso (TO)</fullName>
            </value>
            <value>
                <fullName>S&amp;M - Brasília (DF)</fullName>
            </value>
            <value>
                <fullName>S&amp;M - Primavera (MT)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Contrato__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Edição</fullName>
                <default>true</default>
                <label>Edição</label>
            </value>
            <value>
                <fullName>Pendente de Aprovação</fullName>
            </value>
            <value>
                <fullName>Aguardando Assinatura</fullName>
            </value>
            <value>
                <fullName>Pendente de Impressão</fullName>
            </value>
            <value>
                <fullName>Pendente de Envio</fullName>
            </value>
            <value>
                <fullName>Pendente de Postagem</fullName>
            </value>
            <value>
                <fullName>Aguarda Retorno</fullName>
            </value>
            <value>
                <fullName>Chegou</fullName>
            </value>
            <value>
                <fullName>Inutilizado</fullName>
            </value>
            <value>
                <fullName>Anulado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Contrato__c/fields/Multiplicador__c.field-meta.xml
<CustomField>
    <fullName>Multiplicador__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Conta do multiplicador</description>
    <label>Multiplicador</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Contrato_de_Multiplica_o</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Contrato__c/fields/Observacao__c.field-meta.xml
<CustomField>
    <fullName>Observacao__c</fullName>
    <description>Informações genéricas sobre o processo de recebimento dos contratos</description>
    <inlineHelpText>Informações genéricas sobre o processo de recebimento dos contratos</inlineHelpText>
    <label>Observação</label>
    <type>TextArea</type>
</CustomField>

Salesforce/main/default/objects/Contrato__c/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <label>Safra</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>17/18</fullName>
                <default>true</default>
                <label>17/18</label>
            </value>
            <value>
                <fullName>18/19</fullName>
            </value>
            <value>
                <fullName>19/20</fullName>
            </value>
            <value>
                <fullName>20/21</fullName>
            </value>
            <value>
                <fullName>21/22</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Contrato__c/fields/Sociedad__c.field-meta.xml
<CustomField>
    <fullName>Sociedad__c</fullName>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BRMX</fullName>
            </value>
            <value>
                <fullName>DSEM</fullName>
            </value>
            <value>
                <fullName>NEOG</fullName>
            </value>
            <value>
                <fullName>DAGMA</fullName>
            </value>
            <value>
                <fullName>LICENÇAS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Contrato__c/fields/Tipo_de_cambio__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_cambio__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Tipo de câmbio</label>
    <precision>16</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

Salesforce/main/default/main/default/objects/Contrato__c/fields/Tipo_de_Cota_o__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Cota_o__c</fullName>
    <label>Tipo de Cotação</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sociedad__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>DOLAR</fullName>
            </value>
            <value>
                <fullName>SOJA</fullName>
            </value>
            <value>
                <fullName>FATURAMENTO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Contrato__c/recordTypes/BRMX.recordType-meta.xml
<RecordType>
    <fullName>BRMX</fullName>
    <active>true</active>
    <description>Contratos de la sociedad BRASMAX</description>
    <label>BRMX</label>
</RecordType>

Salesforce/main/default/objects/Contrato__c/recordTypes/DSEM.recordType-meta.xml
<RecordType>
    <fullName>DSEM</fullName>
    <active>true</active>
    <description>Contratos de la sociedad Don Mario</description>
    <label>DSEM</label>
</RecordType>

Salesforce/main/default/main/default/objects/Estado__c/Estado__c.object-meta.xml
<CustomObject>
    <label>Estado</label>
    <nameField>
        <label>Nome do Estado</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estados</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/objects/Opportunity/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <formula>IF(NOT(ISNULL(Inicio_Cargamento__c)),
			IF(NOT(ISNULL(Inicio_Transporte__c)),
						IF(NOT(ISNULL(Fin_Transporte__c)),
									IF(AND(Confirmado__c,NOT(Solicitacao_de_reembolso__c)),
											&apos;Confirmado&apos;,
											IF(AND(Solicitacao_de_reembolso__c,NOT(Confirmado__c)),
													&apos;Em Troca&apos;,
													&apos;Entregue&apos;)
											),
									&apos;Pedido em trânsito&apos;),
						&apos;Em carregamento&apos;),
			&apos;&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status de transporte</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/Opportunity/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <description>Identifica la marca para las Oportunidades del Circuito de Anexos. Se selecciona la lista de precios en función de este campo</description>
    <inlineHelpText>Identificar a marca de Oportunidades Circuito Anexos. Você seleciona a lista de preços com base neste campo</inlineHelpText>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BRMX</fullName>
            </value>
            <value>
                <fullName>DSEM</fullName>
            </value>
            <value>
                <fullName>NEOG</fullName>
            </value>
            <value>
                <fullName>DAGMA</fullName>
            </value>
            <value>
                <fullName>LICENÇAS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Opportunity/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <description>Safra o Campania agricola</description>
    <label>Safra</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>06/07</fullName>
            </value>
            <value>
                <fullName>07/08</fullName>
            </value>
            <value>
                <fullName>08/09</fullName>
            </value>
            <value>
                <fullName>09/10</fullName>
            </value>
            <value>
                <fullName>09/09</fullName>
            </value>
            <value>
                <fullName>10/10</fullName>
            </value>
            <value>
                <fullName>10/11</fullName>
            </value>
            <value>
                <fullName>11/11</fullName>
            </value>
            <value>
                <fullName>11/12</fullName>
            </value>
            <value>
                <fullName>12/12</fullName>
            </value>
            <value>
                <fullName>12/13</fullName>
            </value>
            <value>
                <fullName>13/14</fullName>
            </value>
            <value>
                <fullName>14/15</fullName>
            </value>
            <value>
                <fullName>15/16</fullName>
            </value>
            <value>
                <fullName>16/17</fullName>
            </value>
            <value>
                <fullName>17/18</fullName>
            </value>
            <value>
                <fullName>18/19</fullName>
            </value>
            <value>
                <fullName>19/20</fullName>
            </value>
            <value>
                <fullName>20/21</fullName>
            </value>
            <value>
                <fullName>21/22</fullName>
                <default>true</default>
                <label>21/22</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Opportunity/fields/Sociedad__c.field-meta.xml
<CustomField>
    <fullName>Sociedad__c</fullName>
    <label>Sociedad</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/Opportunity/fields/Tipo_de_cambio__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_cambio__c</fullName>
    <description>Tipo de cambio al que sale impresa la factura</description>
    <inlineHelpText>Tipo de cambio al que sale impresa la factura</inlineHelpText>
    <label>Tipo de câmbio</label>
    <precision>16</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

Salesforce/main/default/main/default/objects/Opportunity/fields/Tipo_de_Cota_o__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Cota_o__c</fullName>
    <label>Tipo de Cotação</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DOLAR</fullName>
            </value>
            <value>
                <fullName>SOJA</fullName>
            </value>
            <value>
                <fullName>FATURAMENTO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Order/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Marca</valueSetName>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Order/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <label>Safra</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Safra</valueSetName>
    </valueSet>
</CustomField>

Salesforce/main/default/globalValueSets/Marca.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BRMX</fullName>
    </customValue>
    <customValue>
        <fullName>DSEM</fullName>
    </customValue>
    <customValue>
        <fullName>NEOG</fullName>
    </customValue>
    <customValue>
        <fullName>DAGMA</fullName>
    </customValue>
    <customValue>
        <fullName>LICENÇAS</fullName>
    </customValue>
    <masterLabel>Marca</masterLabel>
</GlobalValueSet>

Salesforce/main/default/globalValueSets/Safra.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>14/15</fullName>
    </customValue>
    <customValue>
        <fullName>15/16</fullName>
    </customValue>
    <customValue>
        <fullName>16/17</fullName>
    </customValue>
    <customValue>
        <fullName>17/18</fullName>
    </customValue>
    <customValue>
        <fullName>18/19</fullName>
    </customValue>
    <customValue>
        <fullName>19/20</fullName>
    </customValue>
    <customValue>
        <fullName>20/21</fullName>
    </customValue>
    <customValue>
        <fullName>21/22</fullName>
    </customValue>
    <customValue>
        <fullName>22/23</fullName>
    </customValue>
    <customValue>
        <fullName>23/24</fullName>
    </customValue>
    <customValue>
        <fullName>08/09</fullName>
        <isActive>false</isActive>
        <label>08/09</label>
    </customValue>
    <customValue>
        <fullName>07/08</fullName>
        <isActive>false</isActive>
        <label>07/08</label>
    </customValue>
    <customValue>
        <fullName>10/11</fullName>
        <isActive>false</isActive>
        <label>10/11</label>
    </customValue>
    <customValue>
        <fullName>11/12</fullName>
        <isActive>false</isActive>
        <label>11/12</label>
    </customValue>
    <customValue>
        <fullName>12/13</fullName>
        <isActive>false</isActive>
        <label>12/13</label>
    </customValue>
    <customValue>
        <fullName>13/14</fullName>
        <isActive>false</isActive>
        <label>13/14</label>
    </customValue>
    <customValue>
        <fullName>09/10</fullName>
        <isActive>false</isActive>
        <label>09/10</label>
    </customValue>
    <masterLabel>Safra</masterLabel>
</GlobalValueSet>

Salesforce/main/default/classes/opportunityFichaExtension.cls
public with sharing class opportunityFichaExtension{
    
    private List<Opportunity> oppz;
    public Account cuenta {get; set;} 
    public Boolean sbx {get; set;}
    
    public String IdView = '00B40000005PjLu'; //Recientes
    public String marca = '';
    public opportunityFichaExtension(ApexPages.StandardController controller){
        //this.cuenta= (Account)controller.getRecord();
        String idAcc = ApexPages.currentPage().getParameters().get('id');
        this.cuenta = [Select Id, Name From Account Where Id = : idAcc];
        sbx = [Select id, isSandbox From Organization].isSandbox;
    }
    
    public opportunityFichaExtension(){
        
    }
    
    public class archivosYNotas{
        public String id { get; set; }
        public String tipo { get; set; }
        public String titulo { get; set; }
        public String ultimaModif { get; set; }
        public String creadoPor { get; set; }
        public String creadoPorId { get; set; }
    }
    
    public List<Opportunity> getOppz()
    {
        marca = '';
        if(UserInfo.getProfileId() == '00e40000000yyv4AAA' || UserInfo.getProfileId() == '00e40000000yysjAAA'){ //Perfiles DSEM
            marca = 'DSEM';
        }else{
            if(UserInfo.getProfileId() == '00e40000000yyIOAAY' || UserInfo.getProfileId() == '00e40000000yyHBAAY' || UserInfo.getProfileId() == '00e40000000yyHBAAY'){ //Perfiles BRMX
                marca = 'BRMX';
            }
        }
        if(marca == ''){
            oppz = [Select Id, Name, Account.Name, CloseDate, StageName, Safra__c, RecordType.Name from Opportunity where Account.id = :this.cuenta.Id AND (RecordType.Name != 'Stock Multipplicadores' OR (RecordType.Name = 'Stock Multiplicadores' AND StageName != 'Fechada')) Order By CreatedDate Desc Limit 150];
        }else{
            oppz = [Select Id, Name, Account.Name, CloseDate, StageName, Safra__c, RecordType.Name from Opportunity where Account.id = :this.cuenta.Id AND Marca__c = :marca AND (RecordType.Name != 'Stock Multipplicadores' OR (RecordType.Name = 'Stock Multiplicadores' AND StageName != 'Fechada')) Order By CreatedDate Desc Limit 150];
        }
        return oppz;
    }
    
    public List<Contrato__c> getContratos(){
        return [Select Id, Name, Observacao__c, RecordType.Name, Safra__c, Tipo_de_Cota_o__c, Cotacao_de_soja__c, Tipo_de_cambio__c, Aditivo_Facturado__c, Sociedad__c, Estado__c From Contrato__c Where Multiplicador__c = :this.cuenta.Id Order By CreatedDate desc];
    }
    
    public List<archivosYNotas> getArchivosYNotas(){
        
        List<archivosYNotas> ret = New List<archivosYNotas>();
        for (Attachment a : [Select Id, Name, LastModifiedDate, CreatedById, CreatedBy.Name From Attachment Where ParentId = : this.cuenta.Id Order By LastModifiedDate desc]){
            archivosYNotas a2 = New archivosYNotas();
            a2.id = a.Id;
            a2.tipo = 'Anexo';
            a2.titulo = a.Name;
            String dia = String.valueOf(a.LastModifiedDate.day());
            String mes = String.valueOf(a.LastModifiedDate.month());
            String hora = String.valueOf(a.LastModifiedDate.hour());
            String minutos = String.valueOf(a.LastModifiedDate.minute());
            if (Integer.valueOf(dia) < 10)
                dia = '0' + dia;            
            if (Integer.valueOf(mes) < 10)
                mes = '0' + mes;
            if (Integer.valueOf(hora) < 10)
                hora = '0' + hora;
            if (Integer.valueOf(minutos) < 10)
                minutos = '0' + minutos;            
            a2.ultimaModif = dia + '/' + mes + '/' + a.LastModifiedDate.year() + ' ' + hora + ':' + minutos;
            a2.creadoPor = a.CreatedBy.Name; 
            a2.creadoPorId = a.CreatedById;
            ret.add(a2);    
        }    
        
        for (Note n : [Select Id, Title, LastModifiedDate, CreatedBy.Name From Note Where ParentId = : this.cuenta.Id Order By LastModifiedDate desc]){
            archivosYNotas a2 = New archivosYNotas();
            a2.id = n.Id;
            a2.tipo = 'Nota';
            a2.titulo = n.Title;
            String dia = String.valueOf(n.LastModifiedDate.day());
            String mes = String.valueOf(n.LastModifiedDate.month());
            String hora = String.valueOf(n.LastModifiedDate.hour());
            String minutos = String.valueOf(n.LastModifiedDate.minute());
            if (Integer.valueOf(dia) < 10)
                dia = '0' + dia;            
            if (Integer.valueOf(mes) < 10)
                mes = '0' + mes;
            if (Integer.valueOf(hora) < 10)
                hora = '0' + hora;
            if (Integer.valueOf(minutos) < 10)
                minutos = '0' + minutos;
            a2.ultimaModif = dia + '/' + mes + '/' + n.LastModifiedDate.year() + ' ' + hora + ':' + minutos;
            a2.creadoPor = n.CreatedBy.Name; 
            a2.creadoPorId = n.CreatedById;
            ret.add(a2);
        }                   
        
        return ret;     
    }
    
    public PageReference nuevaNota (){
        PageReference pr = New PageReference('/002/e');
        pr.getParameters().put('parentId', String.valueOf(this.cuenta.Id));
        pr.getParameters().put('retURL', String.valueOf(this.cuenta.Id));
        return pr.setRedirect(true);
    }
 
    public PageReference crearOpp (){
        return Page.nueva_opp;
    }
    
    public PageReference ListadoOpp(){
        PageReference pr = System.currentPageReference();//new PageReference('/006/e');
        pr.getParameters().put('Id', String.valueOf(this.cuenta.Id));
        pr.getParameters().put('rlid', 'RelatedOpportunityList');
        pr.getParameters().put('nooverride', '1');      
        return pr.setRedirect(true);
    }         
   
    public Boolean getShowShortTable(){
        Boolean resultado = false;
        User usuario = [Select Id, Email From User Where Id =: UserInfo.getUserId() limit 1];
        if(usuario != null){
            resultado =   usuario.Email.contains('pueno@gdmseeds.com');        
        }            
        return resultado;
    }
}