Salesforce/main/default/objects/Account/fields/Gerente_comercial__c.field-meta.xml
<CustomField>
    <fullName>Gerente_comercial__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Gerente comercial</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Gerentes</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/Account/fields/Supervisor__c.field-meta.xml
<CustomField>
    <fullName>Supervisor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supervisor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Supervisores</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Account/recordTypes/Cuenta.recordType-meta.xml
<RecordType>
    <fullName>Cuenta</fullName>
    <active>true</active>
    <label>Cuenta</label>
</RecordType>

Salesforce/main/default/main/default/objects/Evento_Royalty__c/Evento_Royalty__c.object-meta.xml
<CustomObject>
    <label>Evento Royalty</label>
    <nameField>
        <label>Nombre de Evento Royalty</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Eventos Royalty</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/Evento_Royalty__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Eventos Royalty</relationshipLabel>
    <relationshipName>Eventos_Royalty</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Salesforce/main/default/objects/Evento_Royalty__c/fields/Gerente_comercial__c.field-meta.xml
<CustomField>
    <fullName>Gerente_comercial__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Gerente comercial</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Eventos_Royalty1</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/Evento_Royalty__c/fields/Supervisor__c.field-meta.xml
<CustomField>
    <fullName>Supervisor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supervisor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Eventos_Royalty</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/classes/EventoRoyaltyTriggerHelper.cls
global class EventoRoyaltyTriggerHelper {
    public static void sincronizarSupervisorYGerenteComercial(List<Evento_Royalty__c> eventosConAccount){
        Map<Evento_Royalty__c,Account> mapaEventoAccount = new Map<Evento_Royalty__c,Account>();
        List<Id> idsAccounts = new List<Id>();
        List<Account> Accounts = new List<Account>();
        for(Evento_Royalty__c evento : eventosConAccount){
            System.debug('Cuenta: '+evento.Cuenta__c);
            idsAccounts.add(evento.Cuenta__c);
        }
        Accounts = [
            SELECT Id,Supervisor__c,Gerente_comercial__c
            FROM Account
            WHERE Id IN : idsAccounts
        ];
        System.debug('Cuentas en BBDD: '+Accounts);
        for(Evento_Royalty__c evento : eventosConAccount){
            for(Account cuenta : Accounts){
                if(evento.Cuenta__c == cuenta.Id){
                    evento.Supervisor__c = cuenta.Supervisor__c;
                    evento.Gerente_comercial__c = cuenta.Gerente_comercial__c;
                }
            }
        }
    }

    
}