Salesforce/main/default/objects/Account/fields/IE__c.field-meta.xml
<CustomField>
    <fullName>IE__c</fullName>
    <label>IE</label>
    <type>TextArea</type>
</CustomField>

Salesforce/main/default/main/default/objects/Account/fields/Multiplicador__c.field-meta.xml
<CustomField>
    <fullName>Multiplicador__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Multiplicador</label>
    <type>Checkbox</type>
</CustomField>

Salesforce/main/default/main/default/objects/Account/fields/Region_Comercial__c.field-meta.xml
<CustomField>
    <fullName>Region_Comercial__c</fullName>
    <formula>TEXT(Region__r.Region_Comercial__c)</formula>
    <label>Região Comercial</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/Contract/fields/Region_Comercial__c.field-meta.xml
<CustomField>
    <fullName>Region_Comercial__c</fullName>
    <label>Regiao Comercial</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/Contract/fields/Sociedad__c.field-meta.xml
<CustomField>
    <fullName>Sociedad__c</fullName>
    <label>Sociedad</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Marca</valueSetName>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Contrato__c/Contrato__c.object-meta.xml
<CustomObject>
    <description>CONTRATO DE LICENCIAMENTO PARA MULTIPLICAÇÃO E COMERCIALIZAÇÃO</description>
    <label>Contrato de Multiplicação</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Numero do Contrato de Multiplicação</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contratos de Multiplicação</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/Contrato__c/fields/Multiplicador__c.field-meta.xml
<CustomField>
    <fullName>Multiplicador__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Conta do multiplicador</description>
    <label>Multiplicador</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Contrato_de_Multiplica_o</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/Contrato__c/fields/Region_Comercial__c.field-meta.xml
<CustomField>
    <fullName>Region_Comercial__c</fullName>
    <label>Região Comercial</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>REGION 1</fullName>
            </value>
            <value>
                <fullName>REGION 2</fullName>
            </value>
            <value>
                <fullName>CERRADO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Contrato__c/fields/Sociedad__c.field-meta.xml
<CustomField>
    <fullName>Sociedad__c</fullName>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BRMX</fullName>
            </value>
            <value>
                <fullName>DSEM</fullName>
            </value>
            <value>
                <fullName>NEOG</fullName>
            </value>
            <value>
                <fullName>DAGMA</fullName>
            </value>
            <value>
                <fullName>LICENÇAS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Contrato__c/recordTypes/DSEM.recordType-meta.xml
<RecordType>
    <fullName>DSEM</fullName>
    <active>true</active>
    <description>Contratos de la sociedad Don Mario</description>
    <label>DSEM</label>
</RecordType>

Salesforce/main/default/main/default/objects/Opportunity/fields/Estados_Comercializacion__c.field-meta.xml
<CustomField>
    <fullName>Estados_Comercializacion__c</fullName>
    <label>Estados Comercialização</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AC</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AM</fullName>
            </value>
            <value>
                <fullName>AP</fullName>
            </value>
            <value>
                <fullName>BA</fullName>
            </value>
            <value>
                <fullName>CE</fullName>
            </value>
            <value>
                <fullName>DF</fullName>
            </value>
            <value>
                <fullName>ES</fullName>
            </value>
            <value>
                <fullName>GO</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MG</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>PA</fullName>
            </value>
            <value>
                <fullName>Paraguai</fullName>
            </value>
            <value>
                <fullName>PB</fullName>
            </value>
            <value>
                <fullName>PE</fullName>
            </value>
            <value>
                <fullName>PI</fullName>
            </value>
            <value>
                <fullName>PR</fullName>
            </value>
            <value>
                <fullName>RJ</fullName>
            </value>
            <value>
                <fullName>RN</fullName>
            </value>
            <value>
                <fullName>RO</fullName>
            </value>
            <value>
                <fullName>RR</fullName>
            </value>
            <value>
                <fullName>RS</fullName>
            </value>
            <value>
                <fullName>SC</fullName>
            </value>
            <value>
                <fullName>SE</fullName>
            </value>
            <value>
                <fullName>SP</fullName>
            </value>
            <value>
                <fullName>TO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Opportunity/fields/Region_Comercial__c.field-meta.xml
<CustomField>
    <fullName>Region_Comercial__c</fullName>
    <formula>TEXT(Account.Region__r.Region_Comercial__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Region Comercial</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/Opportunity/fields/Sociedad__c.field-meta.xml
<CustomField>
    <fullName>Sociedad__c</fullName>
    <label>Sociedad</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/Opportunity/recordTypes/Reembalaje.recordType-meta.xml
<RecordType>
    <fullName>Reembalaje</fullName>
    <active>true</active>
    <businessProcess>Docusign - Anexos</businessProcess>
    <label>Reembalaje</label>
</RecordType>

Salesforce/main/default/globalValueSets/Marca.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BRMX</fullName>
    </customValue>
    <customValue>
        <fullName>DSEM</fullName>
    </customValue>
    <customValue>
        <fullName>NEOG</fullName>
    </customValue>
    <customValue>
        <fullName>DAGMA</fullName>
    </customValue>
    <customValue>
        <fullName>LICENÇAS</fullName>
    </customValue>
    <masterLabel>Marca</masterLabel>
</GlobalValueSet>

Salesforce/main/default/classes/PdfGeneratorController_Test.cls
@isTest
public class PdfGeneratorController_Test {

    private static final Test_Utils testUtils = Test_Utils.getInstance();
    
    public static testmethod void shouldGenerateOpportunityDocusignPDFRebaixaSacas() {
        PdfGeneratorController.generateOpportunityDocusignPDFFuture('006000000000000000', 'Anexo II Rebaixamento Sacas', false);
    }
    
    public static testmethod void shouldGenerateOpportunityDocusignPDFAnexoI() {
        PdfGeneratorController.generateOpportunityDocusignPDFFuture('006000000000000000', 'Anexo I', false);
    }
    
    public static testmethod void shouldGenerateOpportunityDocusignPDFReembalaje() {
        PdfGeneratorController.generateOpportunityDocusignPDFFuture('006000000000000000', 'Reembalaje', false);
    }
    
    public static testmethod void shouldGenerateContratoMultiplicacaoDocusignPDFForBRMXCerrado() {
        Contrato__c contratoMultiplicacaoObject = testUtils.createNewContratoMultiplicacao(null, null, null, null);
        insert contratoMultiplicacaoObject;
        PdfGeneratorController.generateContratoMultiplicacaoDocusignPDF(contratoMultiplicacaoObject.Id, 'Termo Aditivo');
    }
    
    public static testmethod void shouldGenerateContratoMultiplicacaoDocusignPDFForBRMXRegion() {
        Contrato__c contratoMultiplicacaoObject = testUtils.createNewContratoMultiplicacao(new Contrato__c(Region_Comercial__c='REGION 1'), null, null, null);
        insert contratoMultiplicacaoObject;
        PdfGeneratorController.generateContratoMultiplicacaoDocusignPDF(contratoMultiplicacaoObject.Id, 'Termo Aditivo');
    }
    
    public static testmethod void shouldGenerateContratoMultiplicacaoDocusignPDFForDSEMCerrado() {
        Contrato__c contratoMultiplicacaoObject = testUtils.createNewContratoMultiplicacao(new Contrato__c(Sociedad__c='DSEM'), null, null, null);
        insert contratoMultiplicacaoObject;
        PdfGeneratorController.generateContratoMultiplicacaoDocusignPDF(contratoMultiplicacaoObject.Id, 'Termo Aditivo');
    }
    
    public static testmethod void shouldGenerateContratoMultiplicacaoDocusignPDFForDSEMRegion() {
        Contrato__c contratoMultiplicacaoObject = testUtils.createNewContratoMultiplicacao(new Contrato__c(Sociedad__c='DSEM',Region_Comercial__c='REGION 1'), null, null, null);
        insert contratoMultiplicacaoObject;
        PdfGeneratorController.generateContratoMultiplicacaoDocusignPDF(contratoMultiplicacaoObject.Id, 'Termo Aditivo');
    }
    public static testmethod void shouldGenerateContratoMultiplicacaoDocusignPDFForNEOGRegion() {
        Contrato__c contratoMultiplicacaoObject = testUtils.createNewContratoMultiplicacao(new Contrato__c(Sociedad__c='NEOG',Region_Comercial__c='REGION 1'), null, null, null);
        insert contratoMultiplicacaoObject;
        PdfGeneratorController.generateContratoMultiplicacaoDocusignPDF(contratoMultiplicacaoObject.Id, 'Termo Aditivo');
		PageReference pdf = Page.pdfContratoTA_NEOG_Sul;
    }

    @IsTest
    public static void constructorTest(){
        //Inicializacion y carga de datos
        PdfGeneratorController controller;
        Opportunity oportunidad = testUtils.createNewOpportunityAnexo2(null);
        oportunidad.Estados_Comercializacion__c = 'estado test';
        insert oportunidad;
        ApexPages.StandardController standarController = new ApexPages.StandardController(oportunidad);
        ApexPages.currentPage().getParameters().put('id', oportunidad.Id);
        //Test
        Test.startTest();
        controller = new PdfGeneratorController(standarController);
        Test.stopTest();
        //ASSERTS
        System.assertEquals('MarcaTeste', controller.marca);
        System.assertEquals('estadotest', controller.estCom );
    }

    @IsTest
    public static void impresionContratoGuardaChuva_attachment_Test(){
        //Inicializacion y carga de datos
        Contract contract = testUtils.createNewContract(null,null);
        insert contract;
        //Test
        Test.startTest();
        PdfGeneratorController.impresionContratoGuardaChuva(contract.Id);
        Test.stopTest();
        //ASSERTS
        System.assertEquals(1, [SELECT ID FROM Attachment WHERE ParentId = :contract.Id].size());
    }

    @IsTest
    public static void impresionContratoTA_Attachment_Test(){
        //Inicializacion y carga de datos
        Contrato__c contrato = testUtils.createNewContratoMultiplicacao(null,null,null,null);
        insert contrato;
        //Test
        Test.startTest();
        PdfGeneratorController.impresionContratoTA(contrato.Id);
        Test.stopTest();
        //ASSERTS
        System.assertEquals(1, [SELECT ID FROM Attachment WHERE ParentId = :contrato.Id].size());
    }

    @IsTest
    public static void initImpresionContratoGuardaChuva_Test(){
        //Inicializacion y carga de datos
        Contract contract = testUtils.createNewContract(null,null);
        insert contract;
        Account mutiplicador = [SELECT ID FROM Account WHERE Id = : contract.AccountId];
        mutiplicador.ShippingStreet = 'calle falsa 123';
        mutiplicador.BillingStreet = 'calle falsa 1234';
        update mutiplicador;
        ApexPages.StandardController standarController = new ApexPages.StandardController(contract);
        PdfGeneratorController controller = new PdfGeneratorController(standarController);
        ApexPages.currentPage().getParameters().put('id', contract.Id);
        //Test
        Test.startTest();
        controller.initImpresionContratoGuardaChuva();
        Test.stopTest();
        //ASSERTS
        System.assertEquals('callefalsa123', controller.dirUnidade.deleteWhitespace());
        System.assertEquals('callefalsa1234', controller.dirCorrespondencia.deleteWhitespace() );
    }

    @IsTest
    public static void initImpresionContratoTA_Test(){
        //Inicializacion y carga de datos
        Contrato__c contrato = testUtils.createNewContratoMultiplicacao(null,null,null,null);
        insert contrato;
        Account mutiplicador = [SELECT ID FROM Account WHERE Id = : contrato.Multiplicador__c];
        mutiplicador.IE__c = 'texto cualquiera';
        update mutiplicador;
        ApexPages.StandardController standarController = new ApexPages.StandardController(contrato);
        PdfGeneratorController controller = new PdfGeneratorController(standarController);
        ApexPages.currentPage().getParameters().put('id', contrato.Id);
        //Test
        Test.startTest();
        controller.initImpresionContratoTA();
        Test.stopTest();
        //ASSERTS
        System.assertEquals('AccountTest', controller.nombre);
        System.assertEquals('texto cualquiera', controller.inscEst);
    }
}