Salesforce/main/default/objects/Account/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Marca</valueSetName>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Account/fields/Multiplicador__c.field-meta.xml
<CustomField>
    <fullName>Multiplicador__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Multiplicador</label>
    <type>Checkbox</type>
</CustomField>

Salesforce/main/default/main/default/objects/Account/recordTypes/Cuenta.recordType-meta.xml
<RecordType>
    <fullName>Cuenta</fullName>
    <active>true</active>
    <label>Cuenta</label>
</RecordType>

Salesforce/main/default/objects/Produto_de_Requisicao__c/Produto_de_Requisicao__c.object-meta.xml
<CustomObject>
    <label>Produto de Requisição</label>
    <nameField>
        <label>Nombre de Produto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Produtos de Requisição</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/Produto_de_Requisicao__c/fields/Embalagem__c.field-meta.xml
<CustomField>
    <fullName>Embalagem__c</fullName>
    <label>Embalagem</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Saca 60 Mil Sementes</fullName>
            </value>
            <value>
                <fullName>Bag 5 Milhões Sementes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Produto_de_Requisicao__c/fields/Multiplicador__c.field-meta.xml
<CustomField>
    <fullName>Multiplicador__c</fullName>
    <formula>Requisicao_de_compra__r.Multiplicador__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Multiplicador</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/Produto_de_Requisicao__c/fields/Oportunidade__c.field-meta.xml
<CustomField>
    <fullName>Oportunidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Oportunidade</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Produtos de Requisição</relationshipLabel>
    <relationshipName>Produtos_de_Requisi_o</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Produto_de_Requisicao__c/fields/Requisicao_de_compra__c.field-meta.xml
<CustomField>
    <fullName>Requisicao_de_compra__c</fullName>
    <label>Requisição de compra</label>
    <referenceTo>Requisicao_de_compra__c</referenceTo>
    <relationshipLabel>Produtos de Requisição</relationshipLabel>
    <relationshipName>Produtos_de_Requisicao</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Salesforce/main/default/main/default/objects/Produto_de_Requisicao__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <formula>TEXT(Requisicao_de_compra__r.Tipo__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tipo</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/Produto_de_Requisicao__c/fields/Tratamento__c.field-meta.xml
<CustomField>
    <fullName>Tratamento__c</fullName>
    <label>Tratamento</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Embalagem__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tratamento A</fullName>
            </value>
            <value>
                <fullName>Tratamento B</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Produto_de_Requisicao__c/fields/Variedad__c.field-meta.xml
<CustomField>
    <fullName>Variedad__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Variedad</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1 AND 2</booleanFilter>
        <filterItems>
            <field>Variedad__c.Disponivel_para_venda_basica__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Variedad__c.Cultura__c</field>
            <operation>equals</operation>
            <value>MILHO</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Variedad__c</referenceTo>
    <relationshipLabel>Produtos de Requisição</relationshipLabel>
    <relationshipName>Produtos_de_Requisicao</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/Produto_de_Requisicao__c/recordTypes/Milho.recordType-meta.xml
<RecordType>
    <fullName>Milho</fullName>
    <active>true</active>
    <label>Milho</label>
</RecordType>

Salesforce/main/default/objects/Requisicao_de_compra__c/Requisicao_de_compra__c.object-meta.xml
<CustomObject>
    <label>Estimativas</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Número de requisito</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Estimativas</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Salesforce/main/default/objects/Requisicao_de_compra__c/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BRMX</fullName>
            </value>
            <value>
                <fullName>DSEM</fullName>
            </value>
            <value>
                <fullName>NEOG</fullName>
            </value>
            <value>
                <fullName>DAGMA</fullName>
            </value>
            <value>
                <fullName>LICENÇAS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Requisicao_de_compra__c/fields/Multiplicador__c.field-meta.xml
<CustomField>
    <fullName>Multiplicador__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Multiplicador</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Requisitos_de_compra</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Requisicao_de_compra__c/fields/Regiao_comercial__c.field-meta.xml
<CustomField>
    <fullName>Regiao_comercial__c</fullName>
    <label>Região comercial</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BRASIL</fullName>
            </value>
            <value>
                <fullName>REGION 1</fullName>
            </value>
            <value>
                <fullName>REGION 2</fullName>
            </value>
            <value>
                <fullName>CERRADO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Requisicao_de_compra__c/fields/Requisicao_de_compra__c.field-meta.xml
<CustomField>
    <fullName>Requisicao_de_compra__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Número da Estimativa Subsequente</label>
    <referenceTo>Requisicao_de_compra__c</referenceTo>
    <relationshipName>Requisitos_de_compra</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/Requisicao_de_compra__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Multiplicador</fullName>
            </value>
            <value>
                <fullName>Supervisor</fullName>
            </value>
            <value>
                <fullName>Gerente Comercial</fullName>
            </value>
            <value>
                <fullName>Gerente</fullName>
                <isActive>false</isActive>
                <label>Gerente</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Requisicao_de_compra__c/recordTypes/Milho.recordType-meta.xml
<RecordType>
    <fullName>Milho</fullName>
    <active>true</active>
    <label>Milho</label>
</RecordType>

Salesforce/main/default/main/default/objects/Variedad__c/Variedad__c.object-meta.xml
<CustomObject>
    <description>Variedades, disponibles para incluir en los Contratos de Multiplicación</description>
    <label>Variedad</label>
    <nameField>
        <label>Nome Comercial</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Variedades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/globalValueSets/Marca.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BRMX</fullName>
    </customValue>
    <customValue>
        <fullName>DSEM</fullName>
    </customValue>
    <customValue>
        <fullName>NEOG</fullName>
    </customValue>
    <customValue>
        <fullName>DAGMA</fullName>
    </customValue>
    <customValue>
        <fullName>LICENÇAS</fullName>
    </customValue>
    <masterLabel>Marca</masterLabel>
</GlobalValueSet>

Salesforce/main/default/classes/WrapperRequisionDeCompra.cls
public class WrapperRequisionDeCompra {

    public static final Decimal SACOS = 83.33;
    public static Id milhoRecordType = Schema.SObjectType.Produto_de_Requisicao__c.getRecordTypeInfosByDeveloperName().get('Milho').getRecordTypeId();
    
    @AuraEnabled public Id  productId                          {get; set;}
    @AuraEnabled public Decimal  quantity                      {get; set;}
    @AuraEnabled public Decimal  managerQuantity               {get; set;}
    @AuraEnabled public Decimal sementes                       {get; set;}
    @AuraEnabled public String  type                           {get; set;}
    @AuraEnabled public List<WrapperRequisionDeCompra> childs  {get; set;}
    @AuraEnabled public String  owner                          {get; set;}
    @AuraEnabled public String  ownerId                        {get; set;}
    @AuraEnabled public String  marca                          {get; set;}
    @AuraEnabled public String  region                         {get; set;}
    @AuraEnabled public String varietyName                     {get; set;}
    @AuraEnabled public String varietyEmbalagem                {get; set;}
    @AuraEnabled public String varietyTratamento               {get; set;}
    @AuraEnabled public String embalagem                       {get; set;}
    @AuraEnabled public String tratamento                      {get; set;}
    @AuraEnabled public String  reqName                        {get; set;}
    @AuraEnabled public String  reqId                          {get; set;}
    @AuraEnabled public variedad__c variety                    {get; set;}
    @AuraEnabled public Boolean parentProduct                  {get; set;}
    @AuraEnabled public String cuenta                          {get; set;}
    @AuraEnabled public Id multiplica                          {get; set;}
    
    public WrapperRequisionDeCompra(Variedad__c variety, String rType, 
                                    Requisicao_de_compra__c req) {
        quantity = 0;
        managerQuantity = 0;
        this.type = rType;
        this.variety = variety;
        this.varietyName = variety.name;
        childs = new List<WrapperRequisionDeCompra> (); 
        owner = '';

        if(req.RecordType.Name == 'Milho') {
          this.varietyEmbalagem = 'Saca 60 Mil Sementes';
        }
       
        this.parentProduct = true;
        this.marca = req.marca__c;
        this.region = req.regiao_comercial__c;
        this.reqId = req.Id;
        this.reqName = req.Name;
        
        if (rType == 'Multiplicador') {
          ownerId = req.Multiplicador__c;
            owner = req.Multiplicador__r.name;
        } else {
          ownerId = req.OwnerId;
            owner = req.Owner.Name;
            multiplica = req.Multiplicador__c;          
        }
    }

    public WrapperRequisionDeCompra(Produto_de_requisicao__c p, String rType,
                                    Boolean parentProduct) {
        productId = p.id;
        if (parentProduct) { 
            managerQuantity = p.Quantidade__c;
            quantity = 0;
        } else {
            quantity = p.Quantidade__c;
        }
        
        this.type = type;
        childs = new List<WrapperRequisionDeCompra> ();
        this.marca = p.Requisicao_de_compra__r.marca__c;
        this.region = p.Requisicao_de_compra__r.regiao_comercial__c;
        this.reqId = p.Requisicao_de_compra__c;
        this.reqName = p.Requisicao_de_compra__r.Name;
        this.type = rType;
        this.embalagem = p.Embalagem__c;
        this.tratamento = p.Tratamento__c;

        if (rType == 'Multiplicador') {
          ownerId = p.Requisicao_de_compra__r.Multiplicador__c;
          owner = p.Multiplicador__c;
          cuenta = p.Multiplicador__c;
        } else {
          ownerId = p.Requisicao_de_compra__r.OwnerId;
          owner = p.Requisicao_de_compra__r.Owner.Name;
          cuenta = p.Multiplicador__c;
        }
        this.variety = p.Variedad__r;
        this.varietyName =  p.Variedad__r.name;
        this.varietyEmbalagem = p.Requisicao_de_compra__r.RecordType.Name == 'Milho' ? 'Saca 60 Mil Sementes' : null;
    }
    
    public void addProduct(Produto_de_requisicao__c p) {
        childs.add(new WrapperRequisionDeCompra(p, p.Requisicao_de_compra__r.Tipo__c, false));
        quantity += p.RecordType.Name == 'Milho' && p.Embalagem__c == 'Bag 5 Milhões Sementes' ? (SACOS * p.Quantidade__c).round(system.RoundingMode.CEILING) : p.Quantidade__c;
    }
        
    public Produto_de_requisicao__c getProduct(Id rqId) {
      
        Requisicao_de_compra__c queryRequisicao = [SELECT Id, RecordType.Name, Requisicao_de_compra__c
                                                        FROM Requisicao_de_compra__c 
                                                           WHERE Requisicao_de_compra__c =: rqId LIMIT 1];

        Produto_de_requisicao__c p = new Produto_de_requisicao__c();

        if(queryRequisicao.RecordType.Name == 'Milho') {    

            Produto_de_Requisicao__c queryProduct = [SELECT Id, Name, Embalagem__c, Quantidade__c, Tratamento__c, RecordType.Name
                                                          FROM Produto_de_Requisicao__c 
                                                             WHERE Requisicao_de_compra__c =: queryRequisicao.Id 
                                                                  AND Quantidade__c != 0 
                                                                  AND Oportunidade__c = null LIMIT 1];
            p.id = productId;
            p.Name = queryProduct.Name;
            p.Embalagem__c = embalagem;
            p.Tratamento__c = tratamento;
            p.Variedad__c = variety.id;
            p.Quantidade__c = managerQuantity;
            p.Requisicao_de_compra__c = rqId;
            p.RecordTypeId = milhoRecordType;
        
        } else {

            p.id = productId;
            p.Name = varietyName;
            p.Variedad__c = variety.id;
            p.Quantidade__c = managerQuantity;
            p.Requisicao_de_compra__c = rqId;
            
        }

        return p;
    }
}