Salesforce/main/default/objects/Account/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Marca</valueSetName>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Account/fields/Multiplicador__c.field-meta.xml
<CustomField>
    <fullName>Multiplicador__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Multiplicador</label>
    <type>Checkbox</type>
</CustomField>

Salesforce/main/default/main/default/objects/Account/fields/Plano_de_Auditoria__c.field-meta.xml
<CustomField>
    <fullName>Plano_de_Auditoria__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plano de Auditoria</label>
    <referenceTo>Plano_de_Auditoria__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/Calendar_Event__c/Calendar_Event__c.object-meta.xml
<CustomObject>
    <label>Calendar Event</label>
    <nameField>
        <label>Event Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Calendar Event</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Salesforce/main/default/objects/Calendar_Event__c/fields/Plano_de_Auditoria__c.field-meta.xml
<CustomField>
    <fullName>Plano_de_Auditoria__c</fullName>
    <label>Plano de Auditoria</label>
    <referenceTo>Plano_de_Auditoria__c</referenceTo>
    <relationshipLabel>Visita</relationshipLabel>
    <relationshipName>Visita</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Salesforce/main/default/objects/Calendar_Event__c/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <label>Safra</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Safra</valueSetName>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Plano_de_Auditoria__c/Plano_de_Auditoria__c.object-meta.xml
<CustomObject>
    <label>Plano de Auditoria</label>
    <nameField>
        <displayFormat>PA-{0000}</displayFormat>
        <label>Nombre de Plano de Auditoria</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Planos de Auditoria</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/Plano_de_Auditoria__c/fields/Cuenta_Principal__c.field-meta.xml
<CustomField>
    <fullName>Cuenta_Principal__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Cuenta Principal</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Plano de Auditoria</relationshipLabel>
    <relationshipName>Plano_de_Auditoria</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/Plano_de_Auditoria__c/fields/Observacion__c.field-meta.xml
<CustomField>
    <fullName>Observacion__c</fullName>
    <label>Observacion</label>
    <length>144</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/Plano_de_Auditoria__c/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <label>Safra</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Safra</valueSetName>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Producto_Auditado__c/Producto_Auditado__c.object-meta.xml
<CustomObject>
    <label>Producto Auditado</label>
    <nameField>
        <label>Nombre de Producto Auditado</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Productos Auditados</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/Producto_Auditado__c/fields/Area_Autorizada__c.field-meta.xml
<CustomField>
    <fullName>Area_Autorizada__c</fullName>
    <label>Area Autorizada</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/objects/Producto_Auditado__c/fields/Area_Plantada__c.field-meta.xml
<CustomField>
    <fullName>Area_Plantada__c</fullName>
    <label>Area Plantada</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/objects/Producto_Auditado__c/fields/Categoria_Oli__c.field-meta.xml
<CustomField>
    <fullName>Categoria_Oli__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Categoria del producto de oportunidad</description>
    <label>Categoria</label>
    <referenceTo>Categoria__c</referenceTo>
    <relationshipLabel>Productos Auditados</relationshipLabel>
    <relationshipName>Productos_Auditados</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/Producto_Auditado__c/fields/Comercializado__c.field-meta.xml
<CustomField>
    <fullName>Comercializado__c</fullName>
    <label>Comercializado</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/objects/Producto_Auditado__c/fields/Descarte__c.field-meta.xml
<CustomField>
    <fullName>Descarte__c</fullName>
    <label>Descarte</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/main/default/objects/Producto_Auditado__c/fields/Descarte_Cliente__c.field-meta.xml
<CustomField>
    <fullName>Descarte_Cliente__c</fullName>
    <label>Descarte Cliente</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/main/default/objects/Producto_Auditado__c/fields/Diferencia_de_Venta__c.field-meta.xml
<CustomField>
    <fullName>Diferencia_de_Venta__c</fullName>
    <formula>Total_Com_Up__c  -  Comercializado__c -  Uso_Propio__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Diferencia de Venta</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/objects/Producto_Auditado__c/fields/Diferencia_Descarte__c.field-meta.xml
<CustomField>
    <fullName>Diferencia_Descarte__c</fullName>
    <formula>( Comercializado__c +  Uso_Propio__c +  Descarte_Cliente__c ) -  Sem_Aprovada_Verificada__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Diferencia Descarte</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/objects/Producto_Auditado__c/fields/Observacion__c.field-meta.xml
<CustomField>
    <fullName>Observacion__c</fullName>
    <label>Observação</label>
    <length>144</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/Producto_Auditado__c/fields/Plano_de_Auditoria__c.field-meta.xml
<CustomField>
    <fullName>Plano_de_Auditoria__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plano de Auditoria</label>
    <referenceTo>Plano_de_Auditoria__c</referenceTo>
    <relationshipLabel>Productos Auditados</relationshipLabel>
    <relationshipName>Productos_Auditados</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/Producto_Auditado__c/fields/Productividad__c.field-meta.xml
<CustomField>
    <fullName>Productividad__c</fullName>
    <formula>IF(OR(ISNULL(Area_Plantada__c),Area_Plantada__c=0) , Sem_Bruta__c, Sem_Bruta__c/Area_Plantada__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Productividade</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/main/default/objects/Producto_Auditado__c/fields/Quebra__c.field-meta.xml
<CustomField>
    <fullName>Quebra__c</fullName>
    <formula>100*(( Sem_Beneficiada__c/ Sem_Bruta__c)-1)/100</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Quebra</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

Salesforce/main/default/objects/Producto_Auditado__c/fields/Salir_de_la_Visita__c.field-meta.xml
<CustomField>
    <fullName>Salir_de_la_Visita__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Salir de la Visita</label>
    <type>Checkbox</type>
</CustomField>

Salesforce/main/default/objects/Producto_Auditado__c/fields/Sem_Aprobada__c.field-meta.xml
<CustomField>
    <fullName>Sem_Aprobada__c</fullName>
    <label>Sem. Aprovada</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/main/default/objects/Producto_Auditado__c/fields/Sem_Aprovada_Verificada__c.field-meta.xml
<CustomField>
    <fullName>Sem_Aprovada_Verificada__c</fullName>
    <label>Sem. Aprovada Verificada</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/objects/Producto_Auditado__c/fields/Sem_Beneficiada__c.field-meta.xml
<CustomField>
    <fullName>Sem_Beneficiada__c</fullName>
    <label>Sem. Beneficiada</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/objects/Producto_Auditado__c/fields/Sem_Bruta__c.field-meta.xml
<CustomField>
    <fullName>Sem_Bruta__c</fullName>
    <label>Sem. Bruta</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/objects/Producto_Auditado__c/fields/Sem_Comercializada__c.field-meta.xml
<CustomField>
    <fullName>Sem_Comercializada__c</fullName>
    <label>Sem. Comercializada</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/objects/Producto_Auditado__c/fields/Sem_Uso_Propio__c.field-meta.xml
<CustomField>
    <fullName>Sem_Uso_Propio__c</fullName>
    <label>Sem. Uso Propio</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/main/default/objects/Producto_Auditado__c/fields/Total_Com_Up__c.field-meta.xml
<CustomField>
    <fullName>Total_Com_Up__c</fullName>
    <formula>Sem_Comercializada__c+ Sem_Uso_Propio__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Com+Up</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/main/default/objects/Producto_Auditado__c/fields/Total_Com_UP_Cliente__c.field-meta.xml
<CustomField>
    <fullName>Total_Com_UP_Cliente__c</fullName>
    <formula>Comercializado__c+Uso_Propio__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Com+UP Cliente</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/objects/Producto_Auditado__c/fields/Uso_Propio__c.field-meta.xml
<CustomField>
    <fullName>Uso_Propio__c</fullName>
    <label>Uso Propio</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/main/default/objects/Producto_Auditado__c/fields/Variedad__c.field-meta.xml
<CustomField>
    <fullName>Variedad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Variedad</label>
    <referenceTo>Variedad__c</referenceTo>
    <relationshipLabel>Productos Auditado</relationshipLabel>
    <relationshipName>Productos_Auditado</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/Resumo_da_conta__c/Resumo_da_conta__c.object-meta.xml
<CustomObject>
    <label>CRM</label>
    <nameField>
        <label>Nombre de CRM</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CRM</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/objects/Resumo_da_conta__c/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Marca</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Marca</valueSetName>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Resumo_da_conta__c/fields/Multiplicador__c.field-meta.xml
<CustomField>
    <fullName>Multiplicador__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Multiplicador</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Resumo da conta</relationshipLabel>
    <relationshipName>Resumo_da_conta</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Resumo_da_conta__c/fields/Quebra__c.field-meta.xml
<CustomField>
    <fullName>Quebra__c</fullName>
    <description>Qual é a % de Quebra Técnica MÉDIA (da empresa) referente ao volume BRUTO de semente de soja que entra na UBS para o volume que é Beneficiado ?</description>
    <inlineHelpText>Qual é a % de Quebra Técnica MÉDIA (da empresa) referente ao volume BRUTO de semente de soja que entra na UBS para o volume que é Beneficiado ?</inlineHelpText>
    <label>Quebra</label>
    <type>TextArea</type>
</CustomField>

Salesforce/main/default/main/default/objects/Resumo_da_conta__c/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <label>Safra</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Safra</valueSetName>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Resumo_da_conta__c/fields/Sistema_Implantado__c.field-meta.xml
<CustomField>
    <fullName>Sistema_Implantado__c</fullName>
    <description>Possuem Sistema implantado na empresa ? Qual ?</description>
    <inlineHelpText>Possuem Sistema implantado na empresa ? Qual ?</inlineHelpText>
    <label>Sistema Implantado</label>
    <type>TextArea</type>
</CustomField>

Salesforce/main/default/globalValueSets/Marca.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BRMX</fullName>
    </customValue>
    <customValue>
        <fullName>DSEM</fullName>
    </customValue>
    <customValue>
        <fullName>NEOG</fullName>
    </customValue>
    <customValue>
        <fullName>DAGMA</fullName>
    </customValue>
    <customValue>
        <fullName>LICENÇAS</fullName>
    </customValue>
    <masterLabel>Marca</masterLabel>
</GlobalValueSet>

Salesforce/main/default/globalValueSets/Safra.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>14/15</fullName>
    </customValue>
    <customValue>
        <fullName>15/16</fullName>
    </customValue>
    <customValue>
        <fullName>16/17</fullName>
    </customValue>
    <customValue>
        <fullName>17/18</fullName>
    </customValue>
    <customValue>
        <fullName>18/19</fullName>
    </customValue>
    <customValue>
        <fullName>19/20</fullName>
    </customValue>
    <customValue>
        <fullName>20/21</fullName>
    </customValue>
    <customValue>
        <fullName>21/22</fullName>
    </customValue>
    <customValue>
        <fullName>22/23</fullName>
    </customValue>
    <customValue>
        <fullName>23/24</fullName>
    </customValue>
    <customValue>
        <fullName>08/09</fullName>
        <isActive>false</isActive>
        <label>08/09</label>
    </customValue>
    <customValue>
        <fullName>07/08</fullName>
        <isActive>false</isActive>
        <label>07/08</label>
    </customValue>
    <customValue>
        <fullName>10/11</fullName>
        <isActive>false</isActive>
        <label>10/11</label>
    </customValue>
    <customValue>
        <fullName>11/12</fullName>
        <isActive>false</isActive>
        <label>11/12</label>
    </customValue>
    <customValue>
        <fullName>12/13</fullName>
        <isActive>false</isActive>
        <label>12/13</label>
    </customValue>
    <customValue>
        <fullName>13/14</fullName>
        <isActive>false</isActive>
        <label>13/14</label>
    </customValue>
    <customValue>
        <fullName>09/10</fullName>
        <isActive>false</isActive>
        <label>09/10</label>
    </customValue>
    <masterLabel>Safra</masterLabel>
</GlobalValueSet>

Salesforce/main/default/main/default/classes/AuditarVisitaController.cls
public with sharing class AuditarVisitaController {

    @TestVisible public Plano_de_Auditoria__c planoDeAuditoria                   {get; set;}
    @TestVisible public Map<String, Producto_auditado__c> productoPorVariedad    {get; set;}
    @TestVisible public List<Producto_auditado__c> productosDelPlano             {get; set;}
    @TestVisible public Calendar_Event__c calendarEvent                          {get; set;}
    @TestVisible public List<SelectOption> safraFiltrer         				 {get; set;}
    @TestVisible public String safraSelected									 {get; set;}

    public AuditarVisitaController(ApexPages.StandardController controller) {
        Id planoDeAuditoriaId = controller.getRecord().Id;
        String safras = ApexPages.currentPage().getParameters().get('safras');
        safraSelected = ApexPages.currentPage().getParameters().get('Safra');
        System.debug('id: ' + planoDeAuditoriaId);
        System.debug('safras: ' + safras);

        planoDeAuditoria = [
            SELECT Id, Name, Safra__c, Cuenta_Principal__c, Observacion__c, Cuenta_Principal__r.Marca__c
            FROM Plano_de_Auditoria__c WHERE Id = :planoDeAuditoriaId
        ];

        productoPorVariedad = new Map<String, Producto_auditado__c>();
        productosDelPlano = new List<Producto_auditado__c>();

        safraFiltrer = new SelectOption[]{ new SelectOption('', 'Seleccione Safra') };

        if (String.isNotEmpty(safras)) {
            for (String safra : safras.split(';')) {
                safraFiltrer.add(new SelectOption(safra, safra));
            }
        } else {
            for (String safra : planoDeAuditoria.Safra__c.split(';')) {
                safraFiltrer.add(new SelectOption(safra, safra));
            }
        }

        getProductosParaAuditar();
    }

    public void getProductosParaAuditar() {
        System.debug('Safra seleccionada: ' + safraSelected);
        productosDelPlano = [
            SELECT Id, Name, Safra__C, Variedad__c, Variedad__r.Name, Marca__c, Categoria_Oli__c, Area_Autorizada__c, Area_Plantada__c, Productividad__c,
                Sem_Bruta__c, Quebra__c, Sem_Beneficiada__c, Sem_Aprobada__c, Sem_Aprovada_Verificada__c, Sem_Comercializada__c, Sem_Uso_Propio__c, Total_Com_Up__c, Descarte__c, Comercializado__c,
                Uso_Propio__c, Descarte_Cliente__c, Total_Com_UP_Cliente__c, Diferencia_de_Venta__c, Diferencia_Descarte__c, Observacion__c, Salir_de_la_visita__c
            FROM Producto_auditado__c WHERE Plano_de_Auditoria__c = :planoDeAuditoria.Id AND Safra__c = :safraSelected
        ];

        for (Producto_auditado__c product : productosDelPlano) {
            if (product.Diferencia_de_Venta__c != 0 || product.Diferencia_Descarte__c != 0) {
                product.Salir_de_la_visita__c = true;
            }
            System.debug('Diferencia de venta: ' + product.Diferencia_de_Venta__c);
        }
    }

    public PageReference save() {
        update productosDelPlano;
        update planoDeAuditoria;
        Id planoId = planoDeAuditoria.Id;
        PageReference pr = new PageReference('/apex/AuditarVisita');
        pr.getParameters().put('Id',planoId);
        pr.getParameters().put('Safra',safraSelected);
        pr.setRedirect(true);
        return pr;
    }

    public PageReference goToPlano() {
        return new PageReference('/' + ApexPages.currentPage().getParameters().get('Id'));
    }

    public PageReference goToCalendario() {
        PageReference pr = new PageReference('/apex/FullCalendarDemo');
        pr.setRedirect(true);
        return pr;
    }

    public PageReference goToObservaciones() {
        PageReference pr = new PageReference('/apex/ObservacionesDeAuditoria');
        Id planoId = planoDeAuditoria.Id;
        List<Resumo_da_Conta__c> CRMs = [
            SELECT Id, Name,Multiplicador__c, Multiplicador__r.Name, Sistema_Implantado__c, Miembros_o_area_para_Multiplicar__c,
                Emiten_Facturas_de_Venta_Transferencia__c, Separa_los_volumenes__c, Compra_Vende_Semillas_de_Terceros__c, Separa_los_volumenes_2__c, 
                Mencion_factura_de_venta__c, Clausula_5_1__c, Quebra__c, Otros_criadores__c, Participacion_en_la_cosecha__c, Ventas_Totales_RR__c,
                Ventas_Totales_INTACTA__c, Safra__c
            FROM Resumo_da_Conta__c WHERE Multiplicador__c = :planoDeAuditoria.Cuenta_Principal__c AND Safra__c = :safraSelected
        ];

        if (CRMs.isEmpty()) { createCRM(); }

        pr.getParameters().put('Id',planoId);
        pr.getParameters().put('Safra',safraSelected);
        pr.setRedirect(true);
        return pr;
    }

    public void createCRM() {
        Resumo_da_Conta__c newCRM = new Resumo_da_Conta__c(
            Name = 'CRM',
            Multiplicador__c = planoDeAuditoria.Cuenta_Principal__c,
            safra__c = safraSelected,
            Marca__c = planoDeAuditoria.Cuenta_Principal__r.Marca__c
        );

        insert newCRM;
    }

    public PageReference generatePDF() {
        PageReference pr = new PageReference('/' + ApexPages.currentPage().getParameters().get('Id'));
        Id planoId = planoDeAuditoria.Id;

        //Your PDF
        PageReference pdf = new PageReference('/apex/PDFVisitaAuditada?Id=' + planoId);
        Blob bodyBlob;

        if (Test.isRunningTest()) { 
            bodyBlob = Blob.valueOf('Unit.Test');
        } else {
            bodyBlob = pdf.getContentAsPDF();
        }

        //ContentVersion
        Integer currentYear = System.Today().year();
        ContentVersion contentVersion_1 = new ContentVersion(
            Title = 'ApuntamentoPDF',
            PathOnClient ='/ApuntamentoPDF.pdf',
            VersionData = bodyBlob,
            origin = 'H'
        );

        insert contentVersion_1;

        ContentVersion contentVersion_2 = [
            SELECT Id, Title, ContentDocumentId, PathOnClient, VersionNumber, CreatedDate FROM ContentVersion WHERE Id = :contentVersion_1.Id LIMIT 1
        ];

        Integer cantidadDeVersiones = [SELECT COUNT() FROM ContentDocumentLink WHERE LinkedEntityId = :planoId];

        ContentDocumentLink contentlink = new ContentDocumentLink();
        contentlink.LinkedEntityId = planoId;
        contentlink.ContentDocumentId = contentVersion_2.ContentDocumentId;
        contentlink.ShareType = 'V';
        insert contentlink;
        contentVersion_2.Title = currentYear + '/' + (cantidadDeVersiones+1);
        update contentVersion_2;

        return pr;
    }
}