Salesforce/main/default/objects/Account/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Marca</valueSetName>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Account/fields/Multiplicador__c.field-meta.xml
<CustomField>
    <fullName>Multiplicador__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Multiplicador</label>
    <type>Checkbox</type>
</CustomField>

Salesforce/main/default/main/default/objects/Account/recordTypes/Cuenta.recordType-meta.xml
<RecordType>
    <fullName>Cuenta</fullName>
    <active>true</active>
    <label>Cuenta</label>
</RecordType>

Salesforce/main/default/main/default/objects/Case/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <description>Este campo indica a que empresa corresponde el reclamo.</description>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BRMX</fullName>
            </value>
            <value>
                <fullName>DSEM</fullName>
            </value>
            <value>
                <fullName>NEOG</fullName>
            </value>
            <value>
                <fullName>DAGMA</fullName>
            </value>
            <value>
                <fullName>LICENÇAS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Configuracion_BMX__c/Configuracion_BMX__c.object-meta.xml
<CustomObject>
    <description>Indicador de Parametros.</description>
    <label>Configuracion_BMX</label>
    <nameField>
        <label>Configuracion Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuraciones_BMX</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/Configuracion_BMX__c/fields/Data_Final_CRM__c.field-meta.xml
<CustomField>
    <fullName>Data_Final_CRM__c</fullName>
    <label>Data Final CRM</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/Configuracion_BMX__c/fields/Data_Inicial_CRM__c.field-meta.xml
<CustomField>
    <fullName>Data_Inicial_CRM__c</fullName>
    <label>Data Inicial CRM</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/Configuracion_BMX__c/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BRMX</fullName>
                <default>true</default>
                <label>BRMX</label>
            </value>
            <value>
                <fullName>DSEM</fullName>
            </value>
            <value>
                <fullName>NEOG</fullName>
            </value>
            <value>
                <fullName>DAGMA</fullName>
            </value>
            <value>
                <fullName>LICENÇAS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Resumo_da_conta__c/Resumo_da_conta__c.object-meta.xml
<CustomObject>
    <label>CRM</label>
    <nameField>
        <label>Nombre de CRM</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CRM</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/objects/Resumo_da_conta__c/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Marca</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Marca</valueSetName>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Resumo_da_conta__c/fields/Multiplicador__c.field-meta.xml
<CustomField>
    <fullName>Multiplicador__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Multiplicador</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Resumo da conta</relationshipLabel>
    <relationshipName>Resumo_da_conta</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Resumo_da_conta__c/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <label>Safra</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Safra</valueSetName>
    </valueSet>
</CustomField>

Salesforce/main/default/globalValueSets/Marca.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BRMX</fullName>
    </customValue>
    <customValue>
        <fullName>DSEM</fullName>
    </customValue>
    <customValue>
        <fullName>NEOG</fullName>
    </customValue>
    <customValue>
        <fullName>DAGMA</fullName>
    </customValue>
    <customValue>
        <fullName>LICENÇAS</fullName>
    </customValue>
    <masterLabel>Marca</masterLabel>
</GlobalValueSet>

Salesforce/main/default/globalValueSets/Safra.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>14/15</fullName>
    </customValue>
    <customValue>
        <fullName>15/16</fullName>
    </customValue>
    <customValue>
        <fullName>16/17</fullName>
    </customValue>
    <customValue>
        <fullName>17/18</fullName>
    </customValue>
    <customValue>
        <fullName>18/19</fullName>
    </customValue>
    <customValue>
        <fullName>19/20</fullName>
    </customValue>
    <customValue>
        <fullName>20/21</fullName>
    </customValue>
    <customValue>
        <fullName>21/22</fullName>
    </customValue>
    <customValue>
        <fullName>22/23</fullName>
    </customValue>
    <customValue>
        <fullName>23/24</fullName>
    </customValue>
    <customValue>
        <fullName>08/09</fullName>
        <isActive>false</isActive>
        <label>08/09</label>
    </customValue>
    <customValue>
        <fullName>07/08</fullName>
        <isActive>false</isActive>
        <label>07/08</label>
    </customValue>
    <customValue>
        <fullName>10/11</fullName>
        <isActive>false</isActive>
        <label>10/11</label>
    </customValue>
    <customValue>
        <fullName>11/12</fullName>
        <isActive>false</isActive>
        <label>11/12</label>
    </customValue>
    <customValue>
        <fullName>12/13</fullName>
        <isActive>false</isActive>
        <label>12/13</label>
    </customValue>
    <customValue>
        <fullName>13/14</fullName>
        <isActive>false</isActive>
        <label>13/14</label>
    </customValue>
    <customValue>
        <fullName>09/10</fullName>
        <isActive>false</isActive>
        <label>09/10</label>
    </customValue>
    <masterLabel>Safra</masterLabel>
</GlobalValueSet>

Salesforce/main/default/classes/CRMAPITest.cls
@isTest
public with sharing class CRMAPITest {

    public static final String TESTACCTNAME = 'Test Account Name';
    public static final String TESTMARCA = 'BRMX';
    public static final String TESTSAFRA = '21/22';

    @TestSetup
    static void makeData(){

        // Insert Configuacion
        Configuracion_BMX__c configBMX = new Configuracion_BMX__c();
        configBMX.Name = 'Test Configuracion';
        insert configBMX;

        // Insert Account
        List<Account> accountList = new List<Account>();
        accountList.add( new Account(Name = TESTACCTNAME) );
        insert accountList;

    }    
    
    /**
     *  METHOD:         getNewCRMIsValidTestPositive
     *  DESCRIPTION:    Test class for CRMAPI.getNewCRMIsValid. Created for US #14316 
     *  AUTHOR:         irina.benitez@cloudgaia.com (19-nov-21)
     *  TEST CASE:      call method with valid date settings ==> success, returns true
     **/ 
    @isTest
    public static void getNewCRMIsValidTestPositive() {

        Configuracion_BMX__c configuracion = [  SELECT  Data_Inicial_CRM__c, Data_Final_CRM__c
                                                FROM Configuracion_BMX__c 
                                                LIMIT 1];

        String dayInicial = String.valueOf(System.today().day() - 1);
        String dayFinal = String.valueOf(System.today().day() + 2);
        String mesInicial = (System.today().month()<10?'0'+String.valueOf(System.today().month()):String.valueOf(System.today().month()));
        String mesFinal = (System.today().month()<10?'0'+String.valueOf(System.today().month()):String.valueOf(System.today().month()));

        if (Integer.valueOf(dayInicial) == 0) {

            dayInicial= '01';
            mesInicial = (Integer.valueOf(mesInicial) -1) == 0 ? '12' : '0' +String.valueOf(Integer.valueOf(mesInicial) - 1);
        }

        if (Integer.valueOf(dayFinal) > 28) {

            dayFinal= '03';
            mesFinal = (Integer.valueOf(mesFinal) +1) > 12 ? '01' : '0' +String.valueOf(Integer.valueOf(mesFinal) + 1);
        }
        
        dayInicial = dayInicial.length() < 2 ? '0' + dayInicial : dayInicial;
        dayFinal = dayFinal.length() < 2 ? '0' + dayFinal : dayFinal;

        configuracion.Data_Inicial_CRM__c = dayInicial + '/' +mesInicial;
        configuracion.Data_Final_CRM__c = dayFinal + '/' +mesFinal;
        
        update configuracion;

        Account acct = [SELECT Id FROM Account LIMIT 1];

        RestRequest req = new RestRequest(); 
        req.requestURI = '/services/apexrest/CRMAPI/';  
        req.addParameter('cuenta', acct.Id);
        req.addParameter('marca', TESTMARCA);
        req.addParameter('safra', TESTSAFRA);
        //req.addParameter('campania', 'campaniaId');
        req.httpMethod = 'GET';

        RestResponse resp = new RestResponse();
        RestContext.request = req;
        RestContext.response = resp;

        Test.startTest();
        CRMAPI.getNewCRMIsValid();
        Test.stopTest();

        CRMAPI.Response result = (CRMAPI.Response)JSON.deserialize(resp.responseBody.toString(), CRMAPI.Response.class);
        System.debug('result: ' + result);
        System.assert(result.status);
        System.assertEquals(Label.CRMAPI_Success_Message, result.message);
    }

    /**
     *  METHOD:         getNewCRMIsValidTestNegative1
     *  DESCRIPTION:    Test class for CRMAPI.getNewCRMIsValid. Created for US #14316 
     *  AUTHOR:         irina.benitez@cloudgaia.com (19-nov-21)
     *  TEST CASE:      call method with invalid date settings ==> returns false status and error message
     **/ 
    @isTest
    public static void getNewCRMIsValidTestNegative1() {

        Configuracion_BMX__c configuracion = [  SELECT  Data_Inicial_CRM__c, Data_Final_CRM__c
                                                FROM Configuracion_BMX__c 
                                                LIMIT 1];

        String dayInicial = String.valueOf(System.today().day() + 1);
        String dayFinal = String.valueOf(System.today().day() + 2);
        String mesInicial = (System.today().month()<10?'0'+String.valueOf(System.today().month()):String.valueOf(System.today().month()));
        String mesFinal = (System.today().month()<10?'0'+String.valueOf(System.today().month()):String.valueOf(System.today().month()));
                                        
        if (Integer.valueOf(dayInicial) > 28) {
                                        
            dayInicial= '01';
            mesInicial = (Integer.valueOf(mesInicial) +1) > 12 ? '01' : '0' +String.valueOf(Integer.valueOf(mesInicial) + 1);
        }
                                        
        if (Integer.valueOf(dayFinal) > 28) {
                                        
            dayFinal= '03';
            mesFinal = (Integer.valueOf(mesFinal) +1) > 12 ? '01' : '0' +String.valueOf(Integer.valueOf(mesFinal) + 1);
        }                               
        
        dayInicial = dayInicial.length() < 2 ? '0' + dayInicial : dayInicial;
        dayFinal = dayFinal.length() < 2 ? '0' + dayFinal : dayFinal;

        configuracion.Data_Inicial_CRM__c =  dayInicial + '/' +mesInicial;
        configuracion.Data_Final_CRM__c =  dayInicial + '/' +mesFinal;

        System.debug('@@@ configuracion.Data_Inicial_CRM__c:   ' +configuracion.Data_Inicial_CRM__c);
        System.debug('@@@ configuracion.Data_Final_CRM__c:   ' +configuracion.Data_Final_CRM__c);
        
        update configuracion;

        RestRequest req = new RestRequest(); 
        req.requestURI = '/services/apexrest/CRMAPI/';  
        req.addParameter('cuenta', 'invalidcuentaId');
        req.addParameter('marca', TESTMARCA);
        req.addParameter('safra', TESTSAFRA);
        //req.addParameter('campania', 'campaniaId');
        req.httpMethod = 'GET';

        RestResponse resp = new RestResponse();
        RestContext.request = req;
        RestContext.response = resp;

        Test.startTest();
        CRMAPI.getNewCRMIsValid();
        Test.stopTest();

        CRMAPI.Response result = (CRMAPI.Response)JSON.deserialize(resp.responseBody.toString(), CRMAPI.Response.class);
        System.debug('result: ' + result);
        System.assertEquals(false, result.status);
        System.assertEquals(Label.CRMAPI_Default_Error_Message, result.message);

    }

        /**
     *  METHOD:         getNewCRMIsValidTestNegative2
     *  DESCRIPTION:    Test class for CRMAPI.getNewCRMIsValid. Created for US #14316 
     *  AUTHOR:         irina.benitez@cloudgaia.com (19-nov-21)
     *  TEST CASE:      call method with valid date settings and existing CRM ==> returns false status and error message
     **/ 
    @isTest
    public static void getNewCRMIsValidTestNegative2() {

        Configuracion_BMX__c configuracion = [  SELECT  Data_Inicial_CRM__c, Data_Final_CRM__c
                                                FROM Configuracion_BMX__c 
                                                LIMIT 1];

        String dayInicial = String.valueOf(System.today().day() + 1);
        String dayFinal = String.valueOf(System.today().day() + 2);
        String mesInicial = (System.today().month()<10?'0'+String.valueOf(System.today().month()):String.valueOf(System.today().month()));
        String mesFinal = (System.today().month()<10?'0'+String.valueOf(System.today().month()):String.valueOf(System.today().month()));
                                                                                
        if (Integer.valueOf(dayInicial) > 28) {
                                                                                
            dayInicial= '01';
            mesInicial = (Integer.valueOf(mesInicial) +1) > 12 ? '01' : '0' +String.valueOf(Integer.valueOf(mesInicial) + 1);
        }
                                                                                
        if (Integer.valueOf(dayFinal) > 28) {
                                                                                
            dayFinal= '03';
            mesFinal = (Integer.valueOf(mesFinal) +1) > 12 ? '01' : '0' +String.valueOf(Integer.valueOf(mesFinal) + 1);
        }
                                                                                                                                                                    
           
        dayInicial = dayInicial.length() < 2 ? '0' + dayInicial : dayInicial;
        dayFinal = dayFinal.length() < 2 ? '0' + dayFinal : dayFinal;

        configuracion.Data_Inicial_CRM__c = dayInicial  + '/' +mesInicial;
        configuracion.Data_Final_CRM__c = dayFinal + '/' +mesFinal;
                                        
        update configuracion;

        Account acct = [SELECT Id FROM Account LIMIT 1];

        Resumo_da_Conta__c existingCRM = new Resumo_da_Conta__c(Multiplicador__c = acct.Id, Safra__c = TESTSAFRA, Marca__c = TESTMARCA);
        insert existingCRM;

        RestRequest req = new RestRequest(); 
        req.requestURI = '/services/apexrest/CRMAPI/';  
        req.addParameter('cuenta', acct.Id);
        req.addParameter('marca', TESTMARCA);
        req.addParameter('safra', TESTSAFRA);
        //req.addParameter('campania', 'campaniaId');
        req.httpMethod = 'GET';

        RestResponse resp = new RestResponse();
        RestContext.request = req;
        RestContext.response = resp;

        Test.startTest();
        CRMAPI.getNewCRMIsValid();
        Test.stopTest();

        CRMAPI.Response result = (CRMAPI.Response)JSON.deserialize(resp.responseBody.toString(), CRMAPI.Response.class);
        System.debug('result: ' + result);
        System.assertEquals(false, result.status);
        System.assertEquals(Label.CRMAPI_CRM_Created_Error_Message, result.message);

    }

        /**
     *  METHOD:         getNewCRMIsValidTestNegative3
     *  DESCRIPTION:    Test class for CRMAPI.getNewCRMIsValid. Created for US #14316 
     *  AUTHOR:         irina.benitez@cloudgaia.com (19-nov-21)
     *  TEST CASE:      call method with bad configuration date settings ==> returns false status and error message
     **/ 
    @isTest
    public static void getNewCRMIsValidTestNegative3() {

        Account acct = [SELECT Id FROM Account LIMIT 1];

        RestRequest req = new RestRequest(); 
        req.requestURI = '/services/apexrest/CRMAPI/';  
        req.addParameter('cuenta', acct.Id);
        req.addParameter('marca', TESTMARCA);
        req.addParameter('safra', TESTSAFRA);
        //req.addParameter('campania', 'campaniaId');
        req.httpMethod = 'GET';

        RestResponse resp = new RestResponse();
        RestContext.request = req;
        RestContext.response = resp;

        Test.startTest();
        CRMAPI.getNewCRMIsValid();
        Test.stopTest();

        CRMAPI.Response result = (CRMAPI.Response)JSON.deserialize(resp.responseBody.toString(), CRMAPI.Response.class);
        System.debug('result: ' + result);
        System.assertEquals(false, result.status);
        System.assertEquals(Label.CRMAPI_Bad_Setting_Error_Message, result.message);
    }
}