Salesforce/main/default/objects/Account/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Marca</valueSetName>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Account/fields/Multiplicador__c.field-meta.xml
<CustomField>
    <fullName>Multiplicador__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Multiplicador</label>
    <type>Checkbox</type>
</CustomField>

Salesforce/main/default/objects/Account/fields/Obtentor__c.field-meta.xml
<CustomField>
    <fullName>Obtentor__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Campo utilizado sólo por el administrador. Todas las Sociedades que están en los productos deben tener la cuenta marcada con Obtentor = true</description>
    <inlineHelpText>Campo utilizado sólo por el administrador. Todas las Sociedades que están en los productos deben tener la cuenta marcada con Obtentor = true</inlineHelpText>
    <label>Obtentor</label>
    <type>Checkbox</type>
</CustomField>

Salesforce/main/default/main/default/objects/Item_de_resumo_da_conta__c/Item_de_resumo_da_conta__c.object-meta.xml
<CustomObject>
    <label>Item de CRM</label>
    <nameField>
        <label>Nombre de Item de CRM</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Itens de CRM</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/Item_de_resumo_da_conta__c/fields/Obtentor__c.field-meta.xml
<CustomField>
    <fullName>Obtentor__c</fullName>
    <label>Obtentor</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Obtentor</valueSetName>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Item_de_resumo_da_conta__c/fields/Resumo_da_conta__c.field-meta.xml
<CustomField>
    <fullName>Resumo_da_conta__c</fullName>
    <label>Resumo da conta</label>
    <referenceTo>Resumo_da_conta__c</referenceTo>
    <relationshipName>Itens_de_resumo_da_conta</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Salesforce/main/default/objects/Resumo_da_conta__c/Resumo_da_conta__c.object-meta.xml
<CustomObject>
    <label>CRM</label>
    <nameField>
        <label>Nombre de CRM</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CRM</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/objects/Resumo_da_conta__c/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Marca</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Marca</valueSetName>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Resumo_da_conta__c/fields/Multiplicador__c.field-meta.xml
<CustomField>
    <fullName>Multiplicador__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Multiplicador</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Resumo da conta</relationshipLabel>
    <relationshipName>Resumo_da_conta</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Resumo_da_conta__c/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <label>Safra</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Safra</valueSetName>
    </valueSet>
</CustomField>

Salesforce/main/default/globalValueSets/Marca.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BRMX</fullName>
    </customValue>
    <customValue>
        <fullName>DSEM</fullName>
    </customValue>
    <customValue>
        <fullName>NEOG</fullName>
    </customValue>
    <customValue>
        <fullName>DAGMA</fullName>
    </customValue>
    <customValue>
        <fullName>LICENÇAS</fullName>
    </customValue>
    <masterLabel>Marca</masterLabel>
</GlobalValueSet>

Salesforce/main/default/globalValueSets/Obtentor.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ADVANTA</fullName>
    </customValue>
    <customValue>
        <fullName>Agroeste</fullName>
    </customValue>
    <customValue>
        <fullName>Agro Norte</fullName>
    </customValue>
    <customValue>
        <fullName>Bayer</fullName>
    </customValue>
    <customValue>
        <fullName>Brasmax</fullName>
    </customValue>
    <customValue>
        <fullName>CARAIBA</fullName>
    </customValue>
    <customValue>
        <fullName>Coodetec</fullName>
    </customValue>
    <customValue>
        <fullName>DM Licenças</fullName>
    </customValue>
    <customValue>
        <fullName>Don Mario</fullName>
    </customValue>
    <customValue>
        <fullName>Dow</fullName>
    </customValue>
    <customValue>
        <fullName>Embrapa</fullName>
    </customValue>
    <customValue>
        <fullName>FPS</fullName>
    </customValue>
    <customValue>
        <fullName>FT</fullName>
    </customValue>
    <customValue>
        <fullName>GDML</fullName>
    </customValue>
    <customValue>
        <fullName>Geneze</fullName>
    </customValue>
    <customValue>
        <fullName>HO</fullName>
    </customValue>
    <customValue>
        <fullName>IGRA</fullName>
    </customValue>
    <customValue>
        <fullName>IMA</fullName>
    </customValue>
    <customValue>
        <fullName>KWS RIBER</fullName>
    </customValue>
    <customValue>
        <fullName>Limagrain</fullName>
    </customValue>
    <customValue>
        <fullName>Macroseed</fullName>
    </customValue>
    <customValue>
        <fullName>Monsoy</fullName>
    </customValue>
    <customValue>
        <fullName>M-SOY</fullName>
    </customValue>
    <customValue>
        <fullName>Nidera</fullName>
    </customValue>
    <customValue>
        <fullName>Outros</fullName>
    </customValue>
    <customValue>
        <fullName>Pioneer</fullName>
    </customValue>
    <customValue>
        <fullName>Sementes Guerra</fullName>
    </customValue>
    <customValue>
        <fullName>SEMPRE</fullName>
    </customValue>
    <customValue>
        <fullName>Soy Tech</fullName>
    </customValue>
    <customValue>
        <fullName>Syngenta</fullName>
    </customValue>
    <masterLabel>Obtentor</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

Salesforce/main/default/globalValueSets/Safra.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>14/15</fullName>
    </customValue>
    <customValue>
        <fullName>15/16</fullName>
    </customValue>
    <customValue>
        <fullName>16/17</fullName>
    </customValue>
    <customValue>
        <fullName>17/18</fullName>
    </customValue>
    <customValue>
        <fullName>18/19</fullName>
    </customValue>
    <customValue>
        <fullName>19/20</fullName>
    </customValue>
    <customValue>
        <fullName>20/21</fullName>
    </customValue>
    <customValue>
        <fullName>21/22</fullName>
    </customValue>
    <customValue>
        <fullName>22/23</fullName>
    </customValue>
    <customValue>
        <fullName>23/24</fullName>
    </customValue>
    <customValue>
        <fullName>08/09</fullName>
        <isActive>false</isActive>
        <label>08/09</label>
    </customValue>
    <customValue>
        <fullName>07/08</fullName>
        <isActive>false</isActive>
        <label>07/08</label>
    </customValue>
    <customValue>
        <fullName>10/11</fullName>
        <isActive>false</isActive>
        <label>10/11</label>
    </customValue>
    <customValue>
        <fullName>11/12</fullName>
        <isActive>false</isActive>
        <label>11/12</label>
    </customValue>
    <customValue>
        <fullName>12/13</fullName>
        <isActive>false</isActive>
        <label>12/13</label>
    </customValue>
    <customValue>
        <fullName>13/14</fullName>
        <isActive>false</isActive>
        <label>13/14</label>
    </customValue>
    <customValue>
        <fullName>09/10</fullName>
        <isActive>false</isActive>
        <label>09/10</label>
    </customValue>
    <masterLabel>Safra</masterLabel>
</GlobalValueSet>

Salesforce/main/default/main/default/classes/ItensResumoDaContaExtensionTest.cls
@IsTest
public class ItensResumoDaContaExtensionTest {
 
    //Unit test

    @IsTest
    private static void addItem() {

        Resumo_da_conta__c crmTest = [SELECT Id FROM Resumo_da_conta__c];
        ApexPages.StandardController sc = new ApexPages.StandardController(crmTest);
        ItensResumoDaContaExtension controller = new ItensResumoDaContaExtension(sc);
        controller.getObtentores();
        
        Test.startTest();
            controller.toAdd = 'ADVANTA';
            controller.addToItemsAlreadySelected();
        Test.stopTest();

        system.assertEquals(2, controller.itemsAlreadySelected.size());

    }

    @IsTest
    private static void removeItem() {

        Resumo_da_conta__c crmTest = [SELECT Id FROM Resumo_da_conta__c];
        ApexPages.StandardController sc = new ApexPages.StandardController(crmTest);
        ItensResumoDaContaExtension controller = new ItensResumoDaContaExtension(sc);
        controller.getObtentores();
        controller.toAdd = 'ADVANTA';
        controller.addToItemsAlreadySelected();
        controller.toAdd = 'Agroeste';
        controller.addToItemsAlreadySelected();
        
        Test.startTest();
            controller.toRemove = '0'; //se borra el que se inserto en el setUp asi recorre la linea de agregar a la lista de Delete.
            controller.removeFromItemsAlreadySelected();
        Test.stopTest();

        system.assertEquals(2, controller.itemsAlreadySelected.size());

    }

    //Integratio test

    @IsTest
    private static void saveCRMWithTwoNewItemsAndDeletingExistingItem() {

        Resumo_da_conta__c crmTest = [SELECT Id FROM Resumo_da_conta__c];
        ApexPages.StandardController sc = new ApexPages.StandardController(crmTest);
        ItensResumoDaContaExtension controller = new ItensResumoDaContaExtension(sc);
        controller.getObtentores();
        controller.toAdd = 'ADVANTA';
        controller.addToItemsAlreadySelected();
        controller.toAdd = 'Agroeste';
        controller.addToItemsAlreadySelected();
        controller.toRemove = '0'; //se borra el que se inserto en el setUp asi recorre la linea de agregar a la lista de Delete.
        controller.removeFromItemsAlreadySelected();

        Test.startTest();                      
            controller.save();    
        Test.stopTest();

        List<Item_de_resumo_da_conta__c> itemsDelCrm = [SELECT Id, Obtentor__c FROM Item_de_resumo_da_conta__c WHERE resumo_da_conta__c = :crmTest.id];
        system.assertEquals(2, itemsDelCrm.size());

    }

    @TestSetup
	private static void IsTheSetup() {

        Profile profileIdSupervisor = [SELECT Id FROM Profile WHERE Name = 'Supervisor Administrativo' LIMIT 1];
		Profile profileIdGerente = [SELECT Id FROM Profile WHERE Name = 'Gerente Administrativo' LIMIT 1];

		User supervisor = new User(
		                           LastName = 'Rosa',
		                           FirstName = 'Jorge Cristiano',
		                           Alias = 'jcr',
		                           Email = 'jorge.rosa@asdf.com',
		                           Username = 'jorge.rosa@asdf.com',
		                           ProfileId = profileIdSupervisor.id,
		                           TimeZoneSidKey = 'GMT',
		                           LanguageLocaleKey = 'en_US',
		                           EmailEncodingKey = 'UTF-8',
		                           LocaleSidKey = 'en_US'
		);

		User gerente = new User(
		                        LastName = 'Bertagnolli',
		                        FirstName = 'Sergio Vieira',
		                        Alias = 'svb',
		                        Email = 'sergio.bertagnolli@asdf.com',
		                        Username = 'sergio.bertagnolli@asdf.com',
		                        ProfileId = profileIdGerente.id,
		                        TimeZoneSidKey = 'GMT',
		                        LanguageLocaleKey = 'en_US',
		                        EmailEncodingKey = 'UTF-8',
		                        LocaleSidKey = 'en_US'
		);

		List<User> users = new List<User> {
			supervisor, gerente
		};
		insert users;

		Account testAccount = Build.anAccount()
			.withName('Test account')
			.withType('Multiplicador')
			.withMarca('BRMX')
			.withSupervisor(supervisor)
			.withGerenteComercial(gerente)
			.build();
        insert testAccount;
        
        Resumo_da_conta__c crmTest = new Resumo_da_conta__c(
            Multiplicador__c = testAccount.id,
            Safra__c = '19/20',
            Marca__c = 'BRMX'
        );
        insert crmTest;

        Item_de_resumo_da_conta__c newItem = new Item_de_resumo_da_conta__c(
            Resumo_da_conta__c = crmTest.id,
            Obtentor__c = 'Brasmax'
        );
        Insert newItem;

    }

}