Salesforce/main/default/objects/Account/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Marca</valueSetName>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Account/fields/Multiplicador__c.field-meta.xml
<CustomField>
    <fullName>Multiplicador__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Multiplicador</label>
    <type>Checkbox</type>
</CustomField>

Salesforce/main/default/main/default/objects/Account/fields/Plano_de_Auditoria__c.field-meta.xml
<CustomField>
    <fullName>Plano_de_Auditoria__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plano de Auditoria</label>
    <referenceTo>Plano_de_Auditoria__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IMAGE( CASE( Status_Base__c , &quot;Verde&quot;, &quot;/img/samples/light_green.gif&quot;, &quot;Amarelo&quot;, &quot;/img/samples/light_yellow.gif&quot;, &quot;Vermelho&quot;, &quot;/img/samples/light_red.gif&quot;, &quot;/s.gif&quot;), &quot;Status da conta&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status BMX</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/Opportunity/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <description>Identifica la marca para las Oportunidades del Circuito de Anexos. Se selecciona la lista de precios en función de este campo</description>
    <inlineHelpText>Identificar a marca de Oportunidades Circuito Anexos. Você seleciona a lista de preços com base neste campo</inlineHelpText>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BRMX</fullName>
            </value>
            <value>
                <fullName>DSEM</fullName>
            </value>
            <value>
                <fullName>NEOG</fullName>
            </value>
            <value>
                <fullName>DAGMA</fullName>
            </value>
            <value>
                <fullName>LICENÇAS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Opportunity/fields/Plano_de_Auditoria__c.field-meta.xml
<CustomField>
    <fullName>Plano_de_Auditoria__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plano de Auditoria</label>
    <referenceTo>Plano_de_Auditoria__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Anexos</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Opportunity/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <description>Safra o Campania agricola</description>
    <label>Safra</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>06/07</fullName>
            </value>
            <value>
                <fullName>07/08</fullName>
            </value>
            <value>
                <fullName>08/09</fullName>
            </value>
            <value>
                <fullName>09/10</fullName>
            </value>
            <value>
                <fullName>09/09</fullName>
            </value>
            <value>
                <fullName>10/10</fullName>
            </value>
            <value>
                <fullName>10/11</fullName>
            </value>
            <value>
                <fullName>11/11</fullName>
            </value>
            <value>
                <fullName>11/12</fullName>
            </value>
            <value>
                <fullName>12/12</fullName>
            </value>
            <value>
                <fullName>12/13</fullName>
            </value>
            <value>
                <fullName>13/14</fullName>
            </value>
            <value>
                <fullName>14/15</fullName>
            </value>
            <value>
                <fullName>15/16</fullName>
            </value>
            <value>
                <fullName>16/17</fullName>
            </value>
            <value>
                <fullName>17/18</fullName>
            </value>
            <value>
                <fullName>18/19</fullName>
            </value>
            <value>
                <fullName>19/20</fullName>
            </value>
            <value>
                <fullName>20/21</fullName>
            </value>
            <value>
                <fullName>21/22</fullName>
                <default>true</default>
                <label>21/22</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Opportunity/recordTypes/AnexoI.recordType-meta.xml
<RecordType>
    <fullName>AnexoI</fullName>
    <active>true</active>
    <businessProcess>Docusign - Anexos</businessProcess>
    <description>Anexo I -Autorização para multiplicação</description>
    <label>Anexo I</label>
</RecordType>

Salesforce/main/default/main/default/objects/Opportunity/recordTypes/AnexoII.recordType-meta.xml
<RecordType>
    <fullName>AnexoII</fullName>
    <active>true</active>
    <businessProcess>Circuito de Anexos</businessProcess>
    <description>Anexo II - Relatório de produção de sementes</description>
    <label>Anexo II</label>
</RecordType>

Salesforce/main/default/objects/Opportunity/recordTypes/Comercial.recordType-meta.xml
<RecordType>
    <fullName>Comercial</fullName>
    <active>true</active>
    <businessProcess>Control_Multiplicador</businessProcess>
    <description>Detalle de lo que el multiplicador va a vender: relatorio de venda</description>
    <label>Comercial</label>
</RecordType>

Salesforce/main/default/main/default/objects/Order/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Marca</valueSetName>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Order/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <label>Safra</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Safra</valueSetName>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Plano_de_Auditoria__c/Plano_de_Auditoria__c.object-meta.xml
<CustomObject>
    <label>Plano de Auditoria</label>
    <nameField>
        <displayFormat>PA-{0000}</displayFormat>
        <label>Nombre de Plano de Auditoria</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Planos de Auditoria</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/Plano_de_Auditoria__c/fields/Cuenta_Principal__c.field-meta.xml
<CustomField>
    <fullName>Cuenta_Principal__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Cuenta Principal</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Plano de Auditoria</relationshipLabel>
    <relationshipName>Plano_de_Auditoria</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Plano_de_Auditoria__c/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <label>Safra</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Safra</valueSetName>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Plano_de_Auditoria__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Não Iniciado</fullName>
                <default>true</default>
                <label>Não Iniciado</label>
            </value>
            <value>
                <fullName>Em andamento</fullName>
            </value>
            <value>
                <fullName>Concluido</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
            <value>
                <fullName>Auditado</fullName>
                <isActive>false</isActive>
                <label>Auditado</label>
            </value>
            <value>
                <fullName>Pendente</fullName>
                <isActive>false</isActive>
                <label>Pendente</label>
            </value>
            <value>
                <fullName>Rejeitado</fullName>
                <isActive>false</isActive>
                <label>Rejeitado</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/globalValueSets/Marca.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BRMX</fullName>
    </customValue>
    <customValue>
        <fullName>DSEM</fullName>
    </customValue>
    <customValue>
        <fullName>NEOG</fullName>
    </customValue>
    <customValue>
        <fullName>DAGMA</fullName>
    </customValue>
    <customValue>
        <fullName>LICENÇAS</fullName>
    </customValue>
    <masterLabel>Marca</masterLabel>
</GlobalValueSet>

Salesforce/main/default/globalValueSets/Safra.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>14/15</fullName>
    </customValue>
    <customValue>
        <fullName>15/16</fullName>
    </customValue>
    <customValue>
        <fullName>16/17</fullName>
    </customValue>
    <customValue>
        <fullName>17/18</fullName>
    </customValue>
    <customValue>
        <fullName>18/19</fullName>
    </customValue>
    <customValue>
        <fullName>19/20</fullName>
    </customValue>
    <customValue>
        <fullName>20/21</fullName>
    </customValue>
    <customValue>
        <fullName>21/22</fullName>
    </customValue>
    <customValue>
        <fullName>22/23</fullName>
    </customValue>
    <customValue>
        <fullName>23/24</fullName>
    </customValue>
    <customValue>
        <fullName>08/09</fullName>
        <isActive>false</isActive>
        <label>08/09</label>
    </customValue>
    <customValue>
        <fullName>07/08</fullName>
        <isActive>false</isActive>
        <label>07/08</label>
    </customValue>
    <customValue>
        <fullName>10/11</fullName>
        <isActive>false</isActive>
        <label>10/11</label>
    </customValue>
    <customValue>
        <fullName>11/12</fullName>
        <isActive>false</isActive>
        <label>11/12</label>
    </customValue>
    <customValue>
        <fullName>12/13</fullName>
        <isActive>false</isActive>
        <label>12/13</label>
    </customValue>
    <customValue>
        <fullName>13/14</fullName>
        <isActive>false</isActive>
        <label>13/14</label>
    </customValue>
    <customValue>
        <fullName>09/10</fullName>
        <isActive>false</isActive>
        <label>09/10</label>
    </customValue>
    <masterLabel>Safra</masterLabel>
</GlobalValueSet>

Salesforce/main/default/main/default/classes/addAccountToPlanoControllerTest.cls
@isTest
private class addAccountToPlanoControllerTest {

    @TestSetup static void setup() {
        Integer CANT_CONST = 5;
        Profile profileSupervisor = [SELECT Id FROM Profile WHERE Name = 'Comercial LE' LIMIT 1];
        Profile profileGerente = [SELECT Id FROM Profile WHERE Name = 'Gerente LE' LIMIT 1];

        User supervisor = Build.anUser()
            .withFirstName('Rosa')
            .withLastName('Jorge Cristiano')
            .withAlias('jcr')
            .withEmail('jorge.rosa@asdf.com')
            .withUsername('jorge.rosa@asdf.com')
            .withProfileId(profileSupervisor)
            .withCommunityNickname('jcr')
            .build();

        User gerente = Build.anUser()
            .withFirstName('Sergio Vieira')
            .withLastName('Bertagnolli')
            .withAlias('svb')
            .withEmail('sergio.bertagnolli@asdf.com')
            .withUsername('sergio.bertagnolli@asdf.com')
            .withProfileId(profileGerente)
            .withCommunityNickname('svb')
            .build();

        User[] users = new User[]{supervisor, gerente};
        insert users;

        List<Account> accList = new List<Account>();

        for (Integer i = 0; i < CANT_CONST; i++) {
            accList.add(Build.anAccount()
                .withName('Test account ' + i)
                .withNomefantasia('Test account ' + i)
                .withType('Multiplicador')
                .withMultiplicador(true)
                .withMarca('BRMX')
                .withSupervisor(supervisor)
                .withGerenteComercial(gerente)
                .build()
            );
        }

        insert accList;

        List<Plano_de_Auditoria__c> auditPlanList = new List<Plano_de_Auditoria__c>();

        for (Integer i = 0; i < CANT_CONST; i++) {
            auditPlanList.add(
                new Plano_de_Auditoria__c(
                    Cuenta_Principal__c = accList[i].Id,
                    safra__c = '19/20',
                    status__c = 'Concluido'
                )
            );
        }

        insert auditPlanList;

        List<Opportunity> opps = new List<Opportunity>();

        for (Integer i = 0; i < CANT_CONST; i++) {
            opps.add(Build.anOpportunityAnexoI()
                .withName('Retorna '+ i)
                .withAccountId(accList[i])
                .withStageName('Aberta')
                .withPricebook2Id(Test.getStandardPricebookId())
                .withCloseDate(Date.today())
                .build()
            );
        }

        insert opps;
    }

    @isTest static void addAcountToAddTest() {
        Plano_de_Auditoria__c planoAuditTest = [SELECT Id, Cuenta_Principal__c FROM Plano_de_Auditoria__c LIMIT 1];

        planoAuditTest.status__c = 'Concluido';
        update planoAuditTest;

        ApexPages.StandardController sc = new ApexPages.standardController(planoAuditTest);
        addAccountsToPlanoController controller = new addAccountsToPlanoController(sc);

        List<Account> accList = [SELECT Id FROM Account WHERE Id != :planoAuditTest.Cuenta_Principal__c];

        Test.startTest();
        controller.getAccounts();
        controller.toAdd = accList[0].Id;
        controller.addAccount();
        controller.toAdd = accList[1].Id;
        controller.addAccount();
        controller.getDisablePrevious();
        controller.getDisableNext();
        controller.Cancel();
        Test.stopTest();

        System.assertEquals(2, controller.accountsSelected.size(), 'The amount of accounts added should be [2]' 
                                                                    + ' but it is [' + controller.accountsSelected.size() + ']');
    }

    @isTest static void removeAccountToRemoveTest() {
        List<Plano_de_Auditoria__c> planoAuditTest = [SELECT Id, Cuenta_Principal__c FROM Plano_de_Auditoria__c];

        ApexPages.StandardController sc = new ApexPages.standardController(planoAuditTest[0]);
        addAccountsToPlanoController controller = new addAccountsToPlanoController(sc);

        List<Account> accList = [SELECT Id FROM Account];

        planoAuditTest[0].Status__c = 'Não Iniciado';
        accList[0].Plano_de_Auditoria__c = planoAuditTest[0].Id;
        accList[0].Multiplicador__c = true;
        accList[1].Plano_de_Auditoria__c = planoAuditTest[0].Id;
        accList[1].Multiplicador__c = true;
        accList[2].Plano_de_Auditoria__c = planoAuditTest[0].Id;
        accList[2].Multiplicador__c = true;

        planoAuditTest[1].Status__c = 'Concluido';
        accList[3].Plano_de_Auditoria__c = planoAuditTest[1].Id;
        accList[3].Multiplicador__c = true;

        planoAuditTest[2].Status__c = 'Cancelado';
        accList[4].Plano_de_Auditoria__c = planoAuditTest[2].Id;
        accList[4].Multiplicador__c = true;
        update accList;
        update planoAuditTest;
        controller.retrieveAccountsFromPlanoDeAuditoria();
       
        Test.startTest();
        controller.toRemove = accList[0].Id;
        controller.removeAccount();
        Test.stopTest();

        System.assertEquals(2, controller.accountsSelected.size(), 'The amount of accounts added should be [2]' 
                                                                + ' but it is [' + controller.accountsSelected.size() + ']');
        System.assertEquals(3, controller.accountsInDataBase.size(), 'The amount of accounts in accountsInDataBase should be [3]' 
                                                                + ' but it is [' + controller.accountsInDataBase.size() + ']');
    }

    @isTest static void retrieveAccountsFromPlanoDeAuditoriaTest() {
        List<Plano_de_Auditoria__c> planoAuditTest = [SELECT Id, Cuenta_Principal__c FROM Plano_de_Auditoria__c];

        ApexPages.StandardController sc = new ApexPages.standardController(planoAuditTest[0]);
        addAccountsToPlanoController controller = new addAccountsToPlanoController(sc);

        List<Account> accList = [SELECT Id FROM Account];

        accList[0].Plano_de_Auditoria__c = controller.planoDeAuditoria;
        accList[1].Plano_de_Auditoria__c = controller.planoDeAuditoria;

        /* Plano_de_Auditoria__r.Status__c = Auditado, Multiplicador__c = true */
        accList[2].Plano_de_Auditoria__c = planoAuditTest[2].Id;
        accList[2].Multiplicador__c = true;
        planoAuditTest[2].Status__c = 'Concluido';

        /* Plano_de_Auditoria__r.Status__c = Auditado, Multiplicador__c = false */
        accList[3].Plano_de_Auditoria__c = planoAuditTest[3].Id;
        accList[3].Multiplicador__c = false;
        planoAuditTest[3].Status__c = 'Concluido';

        /* Plano_de_Auditoria__r.Status__c = Pendente, Multiplicador__c = true */
        accList[4].Plano_de_Auditoria__c = planoAuditTest[4].Id;
        accList[4].Multiplicador__c = true;
        planoAuditTest[4].Status__c = 'Não Iniciado';

        update planoAuditTest;
        update accList;

        Test.startTest();
        controller.retrieveAccountsFromPlanoDeAuditoria();
        Test.stopTest();

        System.assertEquals(2, controller.accountsSelected.size(), 'The amount of accounts added should be [2]' 
                                                                + ' but it is [' + controller.accountsSelected.size() + ']');
        System.assertEquals(1, controller.accountsInDataBase.size(), 'The amount of accounts in accountsInDataBase should be [1]' 
                                                                + ' but it is [' + controller.accountsInDataBase.size() + ']');
        System.assertEquals(accList[0].Id, controller.accountsSelected.get(accList[0].Id).Id, 'The AccountSelected[0] should be[' + accList[0].Id + ']' 
                                                                            + ' but it is [' + controller.accountsSelected.get(accList[0].Id).Id + ']');
        System.assertEquals(accList[1].Id, controller.accountsSelected.get(accList[1].Id).Id, 'The AccountSelected[1] should be[' + accList[1].Id + ']' 
                                                                            + ' but it is [' + controller.accountsSelected.get(accList[1].Id).Id + ']');
        System.assertEquals(accList[2].Id, controller.accountsInDataBase.get(accList[2].Id).Id, 'The AccountInDataBase[0] should be[' + accList[2].Id + ']' 
                                                                            + ' but it is [' + controller.accountsInDataBase.get(accList[2].Id).Id + ']');
        System.assertEquals(null, controller.accountsInDataBase.get(accList[3].Id), 'An account with Multiplicador__c = [FALSE]' 
                                                                                        + ' should not be added to AccountsInDataBase.');
        System.assertEquals(null, controller.accountsInDataBase.get(accList[4].Id), 'An account with Plano_de_Auditoria__c != Pendente' 
                                                                                        + ' should not be added to AccountsInDataBase.');
    }

    @isTest static void getAccount_With_AccountSearch_Null_Test() {
        List<Plano_de_Auditoria__c> planoAuditTest = [SELECT Id, Cuenta_Principal__c, Status__c FROM Plano_de_Auditoria__c];

        ApexPages.StandardController sc = new ApexPages.standardController(planoAuditTest[0]);
        addAccountsToPlanoController controller = new addAccountsToPlanoController(sc);

        List<Account> accList = [SELECT Id, Name, Multiplicador__c, Plano_de_Auditoria__r.Status__c FROM Account];

        //agrego en accountSelected dos cuentas con plano_de_auditoria == RecordId
        accList[0].Plano_de_Auditoria__c = controller.planoDeAuditoria;
        controller.accountsSelected.put(accList[0].Id, accList[0]);
        accList[1].Plano_de_Auditoria__c = controller.planoDeAuditoria;
        controller.accountsSelected.put(accList[1].Id, accList[1]);

        /* Plano_de_Auditoria__r.Status__c = Auditado, Multiplicador__c = true */
        accList[2].Plano_de_Auditoria__c = planoAuditTest[2].Id;
        accList[2].Multiplicador__c = true;
        planoAuditTest[2].Status__c = 'Concluido';

        /* Plano_de_Auditoria__r.Status__c = Auditado, Multiplicador__c = false */
        accList[3].Plano_de_Auditoria__c = planoAuditTest[3].Id;
        accList[3].Multiplicador__c = false;
        planoAuditTest[3].Status__c = 'Concluido';

        /* Plano_de_Auditoria__r.Status__c = Pendente, Multiplicador__c = true */
        accList[4].Plano_de_Auditoria__c = planoAuditTest[4].Id;
        accList[4].Multiplicador__c = true;
        planoAuditTest[4].Status__c = 'Não Iniciado';
        update planoAuditTest;
        update accList;

        Test.startTest();
        controller.getAccounts();
        Test.stopTest();
       
        System.assertEquals(2, controller.accountsSelected.size());
        System.assertEquals(1, controller.accountsInDataBase.size());
    }

    @isTest static void getAccount_With_AccountSearch_NotNull_Test() {
        List<Plano_de_Auditoria__c> planoAuditTest = [SELECT Id, Cuenta_Principal__c FROM Plano_de_Auditoria__c];

        ApexPages.StandardController sc = new ApexPages.standardController(planoAuditTest[0]);
        addAccountsToPlanoController controller = new addAccountsToPlanoController(sc);

        List<Account> accList = [SELECT Id, Name FROM Account];

        //agrego en accountSelected dos cuentas con plano_de_auditoria == RecordId
        accList[0].Plano_de_Auditoria__c = controller.planoDeAuditoria;
        controller.accountsSelected.put(accList[0].Id, accList[0]);
        accList[1].Plano_de_Auditoria__c = controller.planoDeAuditoria;
        controller.accountsSelected.put(accList[1].Id, accList[1]);

        /* Plano_de_Auditoria__r.Status__c = Auditado, Multiplicador__c = true */
        accList[2].Plano_de_Auditoria__c = planoAuditTest[2].Id;
        accList[2].Multiplicador__c = true;
        planoAuditTest[2].Status__c = 'Concluido';

        /* Plano_de_Auditoria__r.Status__c = Auditado, Multiplicador__c = false */
        accList[3].Plano_de_Auditoria__c = planoAuditTest[3].Id;
        accList[3].Multiplicador__c = false;
        planoAuditTest[3].Status__c = 'Concluido';

        /* Plano_de_Auditoria__r.Status__c = Pendente, Multiplicador__c = true */
        accList[4].Plano_de_Auditoria__c = planoAuditTest[4].Id;
        accList[4].Multiplicador__c = true;
        planoAuditTest[4].Status__c = 'Não Iniciado';

        controller.accountSearch = accList[2].Name;
        update accList;
        update planoAuditTest;

        Test.startTest();
        controller.getAccounts();
        Test.stopTest();

        System.assertEquals(2, controller.accountsSelected.size());
        System.assertEquals(1, controller.accountsInDataBase.size());
    }

    @isTest static void saveTest() {
        List<Plano_de_Auditoria__c> planoAuditTest = [SELECT Id, Cuenta_Principal__c, Status__c FROM Plano_de_Auditoria__c];

        ApexPages.StandardController sc = new ApexPages.standardController(planoAuditTest[0]);
        addAccountsToPlanoController controller = new addAccountsToPlanoController(sc);

        List<Account> accList = [
            SELECT Id, Name, Plano_de_Auditoria__c, Plano_de_Auditoria__r.Status__c, Multiplicador__c FROM Account ORDER BY Name
        ];

        controller.retrieveAccountsFromPlanoDeAuditoria();

        accList[0].Multiplicador__c = true;
        accList[1].Multiplicador__c = true;
        controller.toAdd = accList[1].Id;
        controller.addAccount();
        accList[2].Multiplicador__c = true;
        controller.toAdd = accList[2].Id;
        controller.addAccount();

        controller.toRemove = accList[2].Id;
        controller.removeAccount();

        List<Opportunity> anexos = [
            SELECT Id, Name, Account.Name, RecordType.Name, Marca__c, Safra__c,
                Plano_de_Auditoria__c, Plano_de_Auditoria__r.Status__c, Plano_de_Auditoria__r.Safra__c
            FROM Opportunity ORDER BY Name
        ];

        anexos[0].RecordType.DeveloperName = 'AnexoI';
        anexos[0].Plano_de_Auditoria__c = planoAuditTest[1].Id;
        planoAuditTest[1].Status__c = 'Não Iniciado';
        anexos[0].AccountId = accList[2].Id;

        anexos[1].RecordType.DeveloperName = 'AnexoII';
        anexos[1].Plano_de_Auditoria__c = planoAuditTest[2].Id;
        planoAuditTest[2].Status__c = 'Não Iniciado';
        anexos[1].AccountId = accList[3].Id;

        update planoAuditTest;
        update anexos;

        Test.startTest();
        controller.save();
        Test.stopTest();

        List<Account> accListToVerify = [
            SELECT Id, Name, Plano_de_Auditoria__c, Plano_de_Auditoria__r.Status__c 
            FROM Account ORDER BY Name
        ];

        List<Opportunity> anexosToVerify = [
            SELECT Id, Name, Account.Name, RecordType.Name, Marca__c, Safra__c, Plano_de_Auditoria__c,
                Plano_de_Auditoria__r.Status__c, Plano_de_Auditoria__r.Safra__c
            FROM Opportunity ORDER BY Name
        ];

        System.assertEquals(controller.toRemove, accListToVerify[2].Id, 'Account to remove must be assigned to toRemove variable');
        System.assertEquals(null, accListToVerify[2].Plano_de_Auditoria__c, 'Plano_de_Auditoria in variable toRemove, must be deleted from Account');
    }

    @isTest static void nextPageTest() {
        List<Plano_de_Auditoria__c> planoAuditTest = [SELECT Id, Cuenta_Principal__c, Status__c FROM Plano_de_Auditoria__c];

        ApexPages.StandardController sc = new ApexPages.standardController(planoAuditTest[0]);
        addAccountsToPlanoController controller = new addAccountsToPlanoController(sc);

        controller.OffsetSize = 0;
        controller.QueryLimit = 2;

        List<Account> accListSetup = [
            SELECT Id, Name, Plano_de_Auditoria__c, Plano_de_Auditoria__r.Status__c FROM Account ORDER BY Name
        ];

        for (Account a : accListSetup) { a.Plano_de_Auditoria__c = planoAuditTest[1].Id; }

        update accListSetup;

        controller.retrieveAccountsFromPlanoDeAuditoria();

        Test.startTest();
        controller.next();
        Test.StopTest();

        System.assertEquals(accListSetup[controller.OffsetSize].Id, controller.accountsInDataBase.values()[0].Id);
    }

    @isTest static void previusPageTest() {
        List<Plano_de_Auditoria__c> planoAuditTest = [SELECT Id, Cuenta_Principal__c, Status__c FROM Plano_de_Auditoria__c];

        ApexPages.StandardController sc = new ApexPages.standardController(planoAuditTest[0]);
        addAccountsToPlanoController controller = new addAccountsToPlanoController(sc);
        
        controller.OffsetSize = 4;
        controller.QueryLimit = 2;
        
        List<Account> accListSetup = [
            SELECT Id, Name, Plano_de_Auditoria__c, Plano_de_Auditoria__r.Status__c FROM Account ORDER BY Name
        ];

        for (Account a : accListSetup) {
            a.Plano_de_Auditoria__c = planoAuditTest[1].Id;
        }

        update accListSetup;

        controller.retrieveAccountsFromPlanoDeAuditoria();

        Test.startTest();
        controller.previous();
        Test.StopTest();

        System.assertEquals(accListSetup[controller.OffsetSize].Id, controller.accountsInDataBase.values()[0].Id);
    }
}