Salesforce/main/default/objects/Account/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Marca</valueSetName>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Account/fields/Region_Comercial__c.field-meta.xml
<CustomField>
    <fullName>Region_Comercial__c</fullName>
    <formula>TEXT(Region__r.Region_Comercial__c)</formula>
    <label>Região Comercial</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/Negocio_por_Conta__c/Negocio_por_Conta__c.object-meta.xml
<CustomObject>
    <label>Negocio por Conta</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Negocios por Contas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/objects/Negocio_por_Conta__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Negocios por Contas</relationshipLabel>
    <relationshipName>Negocios_por_Contas</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/Negocio_por_Conta__c/fields/Cultura__c.field-meta.xml
<CustomField>
    <fullName>Cultura__c</fullName>
    <label>Cultura</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SOJA</fullName>
                <default>true</default>
                <label>SOJA</label>
            </value>
            <value>
                <fullName>MILHO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Negocio_por_Conta__c/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Marca</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Marca</valueSetName>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Negocio_por_Conta__c/fields/Region_Comercial__c.field-meta.xml
<CustomField>
    <fullName>Region_Comercial__c</fullName>
    <label>Região Comercial</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BRASIL</fullName>
            </value>
            <value>
                <fullName>REGION 1</fullName>
            </value>
            <value>
                <fullName>REGION 2</fullName>
            </value>
            <value>
                <fullName>CERRADO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Negocio_por_Conta__c/fields/Supervidor__c.field-meta.xml
<CustomField>
    <fullName>Supervidor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supervidor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Negocios_por_Contas</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Regiao__c/Regiao__c.object-meta.xml
<CustomObject>
    <label>Región</label>
    <nameField>
        <label>Nome da Região</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regiones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/objects/Regiao__c/fields/Region_Comercial__c.field-meta.xml
<CustomField>
    <fullName>Region_Comercial__c</fullName>
    <label>Region Comercial</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>REGION 1</fullName>
            </value>
            <value>
                <fullName>REGION 2</fullName>
            </value>
            <value>
                <fullName>CERRADO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/globalValueSets/Marca.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BRMX</fullName>
    </customValue>
    <customValue>
        <fullName>DSEM</fullName>
    </customValue>
    <customValue>
        <fullName>NEOG</fullName>
    </customValue>
    <customValue>
        <fullName>DAGMA</fullName>
    </customValue>
    <customValue>
        <fullName>LICENÇAS</fullName>
    </customValue>
    <masterLabel>Marca</masterLabel>
</GlobalValueSet>

Salesforce/main/default/classes/BusinessHelperTest.cls
/**
* @name BusinessHelperTest
* @author Jhonny Peroza
* updated 21-10-2021
*/
@isTest
public class BusinessHelperTest {

    @isTest 
    public static void testUpdateBusiness(){

        List<Negocio_por_Conta__c> newBusinessList = new List<Negocio_por_Conta__c>();

        List<Regiao__c> regionsList = TestDataFactoryMilho.createRegions(2);
        List<Account> accountsList = TestDataFactoryMilho.createAccounts(regionsList);
        List<Negocio_por_Conta__c> businessList = TestDataFactoryMilho.createBusiness(accountsList);

        for(Negocio_por_Conta__c bus : businessList) {
            Negocio_por_Conta__c upsertNegocio = new Negocio_por_Conta__c();
            upsertNegocio.Id = bus.Id;
            upsertNegocio.Region_Comercial__c = 'REGION 2';
            upsertNegocio.Marca__c = 'DSEM';
            upsertNegocio.Cultura__c = 'MILHO';
            upsertNegocio.Supervidor__c = UserInfo.getUserId();
            upsertNegocio.Name = bus.Conta__c + '-' + bus.Cultura__c + '-' + bus.Marca__c + '-' + bus.Supervidor__c;
            newBusinessList.add(upsertNegocio);
        }
    
        Test.startTest();
        upsert newBusinessList;
        Test.stopTest();

        List<Negocio_por_Conta__c> negociosList = [SELECT Name 
                                                       FROM Negocio_por_Conta__c 
                                                         WHERE Id =: newBusinessList[0].Id];

        System.assert(negociosList.size() > 0);
        System.assert(negociosList[0].Name != null);

    }

}