Salesforce/main/default/objects/Account/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Marca</valueSetName>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Account/fields/Multiplicador__c.field-meta.xml
<CustomField>
    <fullName>Multiplicador__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Multiplicador</label>
    <type>Checkbox</type>
</CustomField>

Salesforce/main/default/main/default/objects/Account/fields/Region_Comercial__c.field-meta.xml
<CustomField>
    <fullName>Region_Comercial__c</fullName>
    <formula>TEXT(Region__r.Region_Comercial__c)</formula>
    <label>Região Comercial</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/Account/fields/Supervisor__c.field-meta.xml
<CustomField>
    <fullName>Supervisor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supervisor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Supervisores</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/Negocio_por_Conta__c/Negocio_por_Conta__c.object-meta.xml
<CustomObject>
    <label>Negocio por Conta</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Negocios por Contas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/objects/Negocio_por_Conta__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Negocios por Contas</relationshipLabel>
    <relationshipName>Negocios_por_Contas</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/Negocio_por_Conta__c/fields/Cultura__c.field-meta.xml
<CustomField>
    <fullName>Cultura__c</fullName>
    <label>Cultura</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SOJA</fullName>
                <default>true</default>
                <label>SOJA</label>
            </value>
            <value>
                <fullName>MILHO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Negocio_por_Conta__c/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Marca</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Marca</valueSetName>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Negocio_por_Conta__c/fields/Region_Comercial__c.field-meta.xml
<CustomField>
    <fullName>Region_Comercial__c</fullName>
    <label>Região Comercial</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BRASIL</fullName>
            </value>
            <value>
                <fullName>REGION 1</fullName>
            </value>
            <value>
                <fullName>REGION 2</fullName>
            </value>
            <value>
                <fullName>CERRADO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Negocio_por_Conta__c/fields/Supervidor__c.field-meta.xml
<CustomField>
    <fullName>Supervidor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supervidor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Negocios_por_Contas</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Regiao__c/Regiao__c.object-meta.xml
<CustomObject>
    <label>Región</label>
    <nameField>
        <label>Nome da Região</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regiones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/objects/Regiao__c/fields/Region_Comercial__c.field-meta.xml
<CustomField>
    <fullName>Region_Comercial__c</fullName>
    <label>Region Comercial</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>REGION 1</fullName>
            </value>
            <value>
                <fullName>REGION 2</fullName>
            </value>
            <value>
                <fullName>CERRADO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Requisicao_de_compra__c/Requisicao_de_compra__c.object-meta.xml
<CustomObject>
    <label>Estimativas</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Número de requisito</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Estimativas</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/Requisicao_de_compra__c/fields/Aprovador__c.field-meta.xml
<CustomField>
    <fullName>Aprovador__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Aprovador</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Aprovador_de_requisicoes</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/Requisicao_de_compra__c/fields/Cultura__c.field-meta.xml
<CustomField>
    <fullName>Cultura__c</fullName>
    <label>Cultura</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/Requisicao_de_compra__c/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BRMX</fullName>
            </value>
            <value>
                <fullName>DSEM</fullName>
            </value>
            <value>
                <fullName>NEOG</fullName>
            </value>
            <value>
                <fullName>DAGMA</fullName>
            </value>
            <value>
                <fullName>LICENÇAS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Requisicao_de_compra__c/fields/Multiplicador__c.field-meta.xml
<CustomField>
    <fullName>Multiplicador__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Multiplicador</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Requisitos_de_compra</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Requisicao_de_compra__c/fields/Regiao__c.field-meta.xml
<CustomField>
    <fullName>Regiao__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Região</label>
    <referenceTo>Regiao__c</referenceTo>
    <relationshipName>Requisiaos_de_compra</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Requisicao_de_compra__c/fields/Regiao_comercial__c.field-meta.xml
<CustomField>
    <fullName>Regiao_comercial__c</fullName>
    <label>Região comercial</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BRASIL</fullName>
            </value>
            <value>
                <fullName>REGION 1</fullName>
            </value>
            <value>
                <fullName>REGION 2</fullName>
            </value>
            <value>
                <fullName>CERRADO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Requisicao_de_compra__c/fields/Requisicao_de_compra__c.field-meta.xml
<CustomField>
    <fullName>Requisicao_de_compra__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Número da Estimativa Subsequente</label>
    <referenceTo>Requisicao_de_compra__c</referenceTo>
    <relationshipName>Requisitos_de_compra</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/Requisicao_de_compra__c/fields/Responsavel_y_Tipo__c.field-meta.xml
<CustomField>
    <fullName>Responsavel_y_Tipo__c</fullName>
    <formula>CASESAFEID(OwnerId) + &quot;-&quot; + TEXT(Tipo__c)</formula>
    <label>Responsavel y Tipo</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/Requisicao_de_compra__c/fields/Supervisor__c.field-meta.xml
<CustomField>
    <fullName>Supervisor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supervisor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Estimativas</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/Requisicao_de_compra__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Multiplicador</fullName>
            </value>
            <value>
                <fullName>Supervisor</fullName>
            </value>
            <value>
                <fullName>Gerente Comercial</fullName>
            </value>
            <value>
                <fullName>Gerente</fullName>
                <isActive>false</isActive>
                <label>Gerente</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Requisicao_de_compra__c/recordTypes/Milho.recordType-meta.xml
<RecordType>
    <fullName>Milho</fullName>
    <active>true</active>
    <label>Milho</label>
</RecordType>

Salesforce/main/default/globalValueSets/Marca.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BRMX</fullName>
    </customValue>
    <customValue>
        <fullName>DSEM</fullName>
    </customValue>
    <customValue>
        <fullName>NEOG</fullName>
    </customValue>
    <customValue>
        <fullName>DAGMA</fullName>
    </customValue>
    <customValue>
        <fullName>LICENÇAS</fullName>
    </customValue>
    <masterLabel>Marca</masterLabel>
</GlobalValueSet>

Salesforce/main/default/classes/RequisicaoDeCompraHelperTest.cls
/**
* @name RequisicaoDeCompraHelperTest
* @author Jhonny Peroza
* updated 21-10-2021
*/
@isTest
public class RequisicaoDeCompraHelperTest {

    @isTest 
    public static void testUpdateRequisicaoDeCompra(){

        List<Requisicao_de_compra__c> newRequisicaoList = new List<Requisicao_de_compra__c>();

        List<Regiao__c> regionsList = TestDataFactoryMilho.createRegions(1);
        List<Account> accountsList = TestDataFactoryMilho.createAccounts(regionsList);
        List<Negocio_por_Conta__c> businessList = TestDataFactoryMilho.createBusiness(accountsList);
        List<Requisicao_de_compra__c> requisicaoList = TestDataFactoryMilho.createRequisitions(businessList);

        Id queryRecordType = Schema.SObjectType.Requisicao_de_compra__c.getRecordTypeInfosByName().get('Milho').getRecordTypeId();

        for(Requisicao_de_compra__c req : requisicaoList) {
            for(Negocio_por_Conta__c neg : businessList) {
                Requisicao_de_compra__c upsertRequisicao = new Requisicao_de_compra__c();
                upsertRequisicao.Id = req.Id;
                upsertRequisicao.Tipo__c = 'Gerente Comercial';
                upsertRequisicao.Marca__c = neg.Marca__c;
                upsertRequisicao.Regiao_Comercial__c = neg.Region_Comercial__c;
                upsertRequisicao.Cultura__c = neg.Cultura__c;
                upsertRequisicao.Multiplicador__c = neg.Conta__c;
                upsertRequisicao.Supervisor__c = neg.Supervidor__c;
                upsertRequisicao.OwnerId = neg.Supervidor__c;
                upsertRequisicao.Aprovador__c = neg.Supervidor__c;
                upsertRequisicao.OwnerId = UserInfo.getUserId();
                newRequisicaoList.add(upsertRequisicao);
            }
        }

        Test.startTest();
        upsert newRequisicaoList;
        Test.stopTest();

        List<Requisicao_de_compra__c> requisitionList = [SELECT Id, Cultura__c, Aprovador__c, Supervisor__c
                                                            FROM Requisicao_de_compra__c 
                                                                WHERE Id =: newRequisicaoList[0].Id];

        System.assert(requisitionList.size() > 0);
        System.assert(requisitionList[0].Cultura__c != null);
        System.assert(requisitionList[0].Aprovador__c != null);
        System.assert(requisitionList[0].Supervisor__c != null);

    }

    @isTest 
    public static void testRequisicaoDeCompraMultiplicador(){

        List<Requisicao_de_compra__c> newRequisicaoList = new List<Requisicao_de_compra__c>();

        List<Regiao__c> regionsList = TestDataFactoryMilho.createRegions(1);
        List<Account> accountsList = TestDataFactoryMilho.createAccounts(regionsList);
        List<Negocio_por_Conta__c> businessList = TestDataFactoryMilho.createBusiness(accountsList);
        List<Requisicao_de_compra__c> requisicaoList = TestDataFactoryMilho.createRequisitionsMultiplicador(businessList);
        List<User> userList = TestDataFactoryMilho.createUserRequisition(1);

        Test.startTest();
        RequisicaoDeCompraHelper.setParent(requisicaoList);
        Test.stopTest();

        List<Requisicao_de_compra__c> requisitionList = [SELECT Id, Cultura__c, Tipo__c, Responsavel_y_Tipo__c, Requisicao_de_compra__c
                                                            FROM Requisicao_de_compra__c];

        System.assert(requisitionList[0].Responsavel_y_Tipo__c != null);

    }

}