Salesforce/main/default/objects/Account/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Marca</valueSetName>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Categoria__c/Categoria__c.object-meta.xml
<CustomObject>
    <description>Categorías</description>
    <label>Categoria</label>
    <nameField>
        <label>Nombre de Categoría</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categorias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/objects/Opportunity/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <description>Identifica la marca para las Oportunidades del Circuito de Anexos. Se selecciona la lista de precios en función de este campo</description>
    <inlineHelpText>Identificar a marca de Oportunidades Circuito Anexos. Você seleciona a lista de preços com base neste campo</inlineHelpText>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BRMX</fullName>
            </value>
            <value>
                <fullName>DSEM</fullName>
            </value>
            <value>
                <fullName>NEOG</fullName>
            </value>
            <value>
                <fullName>DAGMA</fullName>
            </value>
            <value>
                <fullName>LICENÇAS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Opportunity/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <description>Safra o Campania agricola</description>
    <label>Safra</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>06/07</fullName>
            </value>
            <value>
                <fullName>07/08</fullName>
            </value>
            <value>
                <fullName>08/09</fullName>
            </value>
            <value>
                <fullName>09/10</fullName>
            </value>
            <value>
                <fullName>09/09</fullName>
            </value>
            <value>
                <fullName>10/10</fullName>
            </value>
            <value>
                <fullName>10/11</fullName>
            </value>
            <value>
                <fullName>11/11</fullName>
            </value>
            <value>
                <fullName>11/12</fullName>
            </value>
            <value>
                <fullName>12/12</fullName>
            </value>
            <value>
                <fullName>12/13</fullName>
            </value>
            <value>
                <fullName>13/14</fullName>
            </value>
            <value>
                <fullName>14/15</fullName>
            </value>
            <value>
                <fullName>15/16</fullName>
            </value>
            <value>
                <fullName>16/17</fullName>
            </value>
            <value>
                <fullName>17/18</fullName>
            </value>
            <value>
                <fullName>18/19</fullName>
            </value>
            <value>
                <fullName>19/20</fullName>
            </value>
            <value>
                <fullName>20/21</fullName>
            </value>
            <value>
                <fullName>21/22</fullName>
                <default>true</default>
                <label>21/22</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Opportunity/fields/TipoReg__c.field-meta.xml
<CustomField>
    <fullName>TipoReg__c</fullName>
    <formula>CASE($RecordType.Name, &quot;Comercial&quot;, &quot;Comercial&quot;, &quot;Produccion&quot;, &quot;Produccion&quot;,&quot;Pendiente&quot;,&quot;AU - Comercial&quot;,&quot;Autorizada&quot;,&quot;AU - SAP&quot;,&quot;Rebaja&quot;,&quot;Rebaja&quot;,$RecordType.Name)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>TipoReg</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/Opportunity/recordTypes/Autorizada.recordType-meta.xml
<RecordType>
    <fullName>Autorizada</fullName>
    <active>true</active>
    <businessProcess>Nota de Venta - Autorizada</businessProcess>
    <label>Autorizada</label>
</RecordType>

Salesforce/main/default/main/default/objects/Opportunity/recordTypes/Reembalaje.recordType-meta.xml
<RecordType>
    <fullName>Reembalaje</fullName>
    <active>true</active>
    <businessProcess>Docusign - Anexos</businessProcess>
    <label>Reembalaje</label>
</RecordType>

Salesforce/main/default/objects/OpportunityLineItem/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Categoria a ser licenciada</description>
    <inlineHelpText>Categoria a ser licenciada</inlineHelpText>
    <label>Categoria</label>
    <referenceTo>Categoria__c</referenceTo>
    <relationshipLabel>Producto de oportunidad</relationshipLabel>
    <relationshipName>Producto_de_oportunidad</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/OpportunityLineItem/fields/Categoria_a_Rebaixar__c.field-meta.xml
<CustomField>
    <fullName>Categoria_a_Rebaixar__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Categoria Plantada</label>
    <referenceTo>Categoria__c</referenceTo>
    <relationshipLabel>Producto de oportunidad (Categoria a Rebaixar)</relationshipLabel>
    <relationshipName>Producto_de_oportunidad1</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/OpportunityLineItem/fields/Lote_Rebajado__c.field-meta.xml
<CustomField>
    <fullName>Lote_Rebajado__c</fullName>
    <label>Lote</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/OpportunityLineItem/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <formula>TEXT(Opportunity.Safra__c)</formula>
    <label>Safra</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/OpportunityLineItem/fields/Sem_Rebajada__c.field-meta.xml
<CustomField>
    <fullName>Sem_Rebajada__c</fullName>
    <label>Sem. Rebaixada (Sacas)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/main/default/objects/OpportunityLineItem/fields/Semente_bruta__c.field-meta.xml
<CustomField>
    <fullName>Semente_bruta__c</fullName>
    <label>Sem. Bruta (Sacas)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/main/default/objects/OpportunityLineItem/fields/UNIDADE__c.field-meta.xml
<CustomField>
    <fullName>UNIDADE__c</fullName>
    <formula>PricebookEntry.Product2.UNIDADE__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unidade</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/OpportunityLineItem/fields/Variedade_Prod__c.field-meta.xml
<CustomField>
    <fullName>Variedade_Prod__c</fullName>
    <formula>PricebookEntry.Product2.Variedade__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Nome Comercial</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/Product2/fields/Categ__c.field-meta.xml
<CustomField>
    <fullName>Categ__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Categ</label>
    <referenceTo>Categoria__c</referenceTo>
    <relationshipLabel>Productos</relationshipLabel>
    <relationshipName>Productos</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Product2/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <label>Categoria</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BREEDER</fullName>
            </value>
            <value>
                <fullName>FUNDADORA</fullName>
            </value>
            <value>
                <fullName>Genetica</fullName>
            </value>
            <value>
                <fullName>Pre Basica</fullName>
            </value>
            <value>
                <fullName>BASICA</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>C1</fullName>
            </value>
            <value>
                <fullName>C2</fullName>
            </value>
            <value>
                <fullName>R</fullName>
            </value>
            <value>
                <fullName>S1</fullName>
            </value>
            <value>
                <fullName>S2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Product2/fields/UNIDADE__c.field-meta.xml
<CustomField>
    <fullName>UNIDADE__c</fullName>
    <label>UNIDADE</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/Product2/fields/Variedade__c.field-meta.xml
<CustomField>
    <fullName>Variedade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Variedade</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Variedad__c.Licenciada__c</field>
            <operation>equals</operation>
            <valueField>$Source.Licenciada__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Variedad__c</referenceTo>
    <relationshipLabel>Productos</relationshipLabel>
    <relationshipName>Productos</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Variedad__c/Variedad__c.object-meta.xml
<CustomObject>
    <description>Variedades, disponibles para incluir en los Contratos de Multiplicación</description>
    <label>Variedad</label>
    <nameField>
        <label>Nome Comercial</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Variedades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/globalValueSets/Marca.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BRMX</fullName>
    </customValue>
    <customValue>
        <fullName>DSEM</fullName>
    </customValue>
    <customValue>
        <fullName>NEOG</fullName>
    </customValue>
    <customValue>
        <fullName>DAGMA</fullName>
    </customValue>
    <customValue>
        <fullName>LICENÇAS</fullName>
    </customValue>
    <masterLabel>Marca</masterLabel>
</GlobalValueSet>

Salesforce/main/default/main/default/classes/ProductsReembalajeAPI.cls
@RestResource(urlMapping='/ProductsReembalajeAPI/*')
global with sharing class ProductsReembalajeAPI {

    public static final String REEMBALAJERECTYPE = 'Reembalagem';                                                                    

    /**
     *  SUBCLASS:       Response
     *  CONSTRUCTORS:   - 
     *  DESCRIPTION:    wrapper class for Products Reembalaje API response. Created for US #13079 
     *  AUTHOR:         irina.benitez@cloudgaia.com (12-oct-21)
     **/ 
    public class Response {
        public Boolean status;
        public String message;
        public List<aAppendix.myOppItem> productsReembalaje;
        public Map<String, String> mapVariedadById;
        public Map<String, String> mapRegistroVariedadById;
        public Map<Id, String> mapCategoriaById;
        public Map<String, Set<String>> mapCategoriaByVariedad;
        public Map<String, Set<String>> mapUnidadesByProduct;
        public Map<String, Map<String, Id>> mapProductByVariedadeAndUnidade;       
    }


     /**
     *  METHOD:         getProductsReembalaje 
     *  PARAMETERS:     accountId: Id of an Account record 
     *                  safra  
     *                  marca 
     *  RETURN:         message: displays 'success' or error message  
     *                  status: boolean shows if operation was succesfull
     *                  productsReembalaje: list of available products for Reembalaje
     *                  mapVariedadById: map of Id - Name pairs for Variedades
     *                  mapCategoriaByVariedad:  map of Variedad Id - List<Categoria Name> pairs
     *  DESCRIPTION:    Return list of products for Reembalaje along with variedad and categoria maps. Created for US #13079 
     *  AUTHOR:         irina.benitez@cloudgaia.com (12-oct-21)
     **/ 
    @HttpGet
    global static void getProductsReembalaje() {

        String accountId = RestContext.request.params.get('accountId');
        String safra = RestContext.request.params.get('safra');
        String marca = RestContext.request.params.get('marca');

        RestResponse response = RestContext.response;
        response.statusCode = 404;

        Response result = new Response();
        result.status = false;
        result.message = Label.ProductsReembalajeAPI_Default_Error_Message;

        FactoryManejador factory = new FactoryManejador();
        ManejadorReembalagem manejador;

        
        try {

            manejador = (ManejadorReembalagem)factory.devuelveManejador(REEMBALAJERECTYPE, accountId, safra, marca);
            manejador.setearMapas();
            Map<String, String> mapQuantities = calculateQuantities(accountId, safra, marca);
            List<aAppendix.myOppItem> tmpProductsReembalaje = oppLineItemJSONConverter(manejador.listaProductos, manejador);
            result.productsReembalaje = setQuantitiesByVariedadAndUnidade(tmpProductsReembalaje, mapQuantities);
            result.mapVariedadById = manejador.nombreVariedadPorId;
            result.mapCategoriaByVariedad = manejador.categoriasPorVariedad;
            result.mapCategoriaById = getCategoriaByIdMap(manejador);
            result.mapRegistroVariedadById = manejador.nombreRegistroVariedadPorId;
            result.mapUnidadesByProduct = manejador.mapaUnidadesProductos;
            result.mapProductByVariedadeAndUnidade = manejador.productByVariedadeAndUnidade;

        } catch (Exception exc) {
            response.statusCode = 400;
            result.message = exc.getMessage();
        }
                
        if(result.productsReembalaje != null && !result.productsReembalaje.isEmpty()) {
            result.status = true;
            result.message = Label.ProductsReembalajeAPI_Success_Message;
            response.statusCode = 200;
        }

        response.responseBody = Blob.valueOf(JSON.serialize(result));
        response.headers.put('Content-Type', 'application/json');
        response.headers.put('Content-Length', RestContext.response.responseBody.size()+'');
    }


    /**
     *  METHOD:         oppLineItemJSONConverter 
     *  PARAMETERS:     oppLineItems: List of OpportunityLineItems in sObject format 
     *  RETURN:         List<aAppendix.myOppItem>: list of records in JSON format to return
     *  DESCRIPTION:    Helper method converts opportunityLineItem sObject in aAppendix.myOppItem JSON wrapper. Created for US #13079 
     *  AUTHOR:         irina.benitez@cloudgaia.com (12-oct-21)
     **/ 
    public static List<aAppendix.myOppItem> oppLineItemJSONConverter(List<OpportunityLineItem> oppLineItems, ManejadorReembalagem manejador) {

        List<aAppendix.myOppItem> result = new List<aAppendix.myOppItem>();

        if(oppLineItems != null && oppLineItems.size() > 0) {
            for(OpportunityLineItem oppLineItem : oppLineItems) {
                aAppendix.myOppItem customOli = new aAppendix.myOppItem();
                customOli.variedad = oppLineItem.PricebookEntry.Product2.Variedade__c;
                customOli.variedad_nombre = oppLineItem.Variedade_Prod__c;
                customOli.variedad_registro = manejador.nombreRegistroVariedadPorId.get(oppLineItem.PricebookEntry.Product2.Variedade__c);
                customOli.categoria = oppLineItem.PricebookEntry.Product2.Categ__c;
                customOli.categoria_nombre = oppLineItem.PricebookEntry.Product2.Categ__r.Name;
                customOli.amount = oppLineItem.Quantity;
                customOli.unidade = oppLineItem.PricebookEntry.Product2.UNIDADE__c;
                customOli.lote_rebajado = oppLineItem.Lote_Rebajado__c;
                customOli.categoria_a_rebajar_id = oppLineItem.Categoria_a_Rebaixar__c;
                customOli.sem_bruta = String.valueOf(oppLineItem.Semente_bruta__c);
                customOli.sem_rebajada = String.valueOf(oppLineItem.Sem_Rebajada__c);
                result.add(customOli);
            }
        }

        return result;
    }

    /**
     *  METHOD:         getCategoriaByIdMap 
     *  PARAMETERS:     ManejadorReembalagem: helper manejador class for Reembalaje opps
     *  RETURN:         Map<Id, String>: map of Categoria names by Id
     *  DESCRIPTION:    Helper method converts opportunityLineItem sObject in aAppendix.myOppItem JSON wrapper. Created for US #13079 
     *  AUTHOR:         irina.benitez@cloudgaia.com (12-oct-21)
     **/     
    public static Map<Id, String> getCategoriaByIdMap(ManejadorReembalagem manejador) {

        Map<Id, String> result = new Map<Id, String>();
        
        for( String variedad : manejador.nombreVariedadPorId.keySet() ) {
            Set<String> categoriesForSelectedVariedad = manejador.categoriasPorVariedad.get(manejador.nombreVariedadPorId.get(variedad));          
            List<Categoria__c> categoriesInDb = aAppManager.getCategorias(); 
            if (!categoriesInDb.isEmpty()) {
                for (Categoria__c tmpCategory : categoriesInDb) {
                    if (categoriesForSelectedVariedad.contains(tmpCategory.Name)) {
                        result.put(tmpCategory.Id, tmpCategory.Name);
                    }
                }
            }
        }
        
        return result;
    }

    public static Map<String, String> calculateQuantities(String accountId, String safra, String marca) {

            List<OpportunityLineItem> tmpOppItems = new List<OpportunityLineItem>();

            String queryPlus = 'PricebookEntry.Product2.Variedade__c, PricebookEntry.Product2.Variedade__r.Name, PricebookEntry.Product2.Categ__c, PricebookEntry.Product2.Categ__r.Name, Opportunity.TipoReg__c, Opportunity.Safra__c, Opportunity.Marca__c, Opportunity.AccountId, Opportunity.StageName';
    
            tmpOppItems = aSiteUtils.queryResults5(OpportunityLineItem.SObjectType, queryPlus, 
                                                    'Opportunity.TipoReg__c in :v1', new String[]{'CVB Autorizada', 'Reembalaje'}, 
                                                    'Opportunity.Safra__c = :v2', safra, 
                                                    'Opportunity.Marca__c = :v3', marca, 
                                                    'Opportunity.AccountId = :v4', accountId, 
                                                    'Opportunity.StageName in :v5', new String[] {'Aprobada', 'AU - Autorizada'});

            Map<String, Double> mapCantidades = new Map<String, Double>();
            Map<String, Double> mapReembalajes = new Map<String, Double>();

            for (OpportunityLineItem s : tmpOppItems) {

                if (s.Opportunity.TipoReg__c == 'CVB Autorizada') {
           
                    if (!mapCantidades.containsKey(String.valueOf(s.PricebookEntry.Product2.Variedade__c) + String.valueOf(s.UNIDADE__c) + String.valueOf(s.PricebookEntry.Product2.Categ__c))) {

                            mapCantidades.put(String.valueOf(s.PricebookEntry.Product2.Variedade__c) + String.valueOf(s.UNIDADE__c) + String.valueOf(s.PricebookEntry.Product2.Categ__c), s.Quantity);

                    } else {

                        Double cant = mapCantidades.get(String.valueOf(s.PricebookEntry.Product2.Variedade__c) + String.valueOf(s.UNIDADE__c) + String.valueOf(s.PricebookEntry.Product2.Categ__c));
                        cant += s.Quantity;
                        mapCantidades.remove(String.valueOf(s.PricebookEntry.Product2.Variedade__c) + String.valueOf(s.UNIDADE__c) + String.valueOf(s.PricebookEntry.Product2.Categ__c));
                        mapCantidades.put(String.valueOf(s.PricebookEntry.Product2.Variedade__c) + String.valueOf(s.UNIDADE__c) + String.valueOf(s.PricebookEntry.Product2.Categ__c), cant);
                    }
                }

                if (s.Opportunity.TipoReg__c == 'Reembalaje') {
  
                    if (!mapReembalajes.containsKey(String.valueOf(s.PricebookEntry.Product2.Variedade__c) + String.valueOf(s.UNIDADE__c) + String.valueOf(s.PricebookEntry.Product2.Categ__c))) {

                            mapReembalajes.put(String.valueOf(s.PricebookEntry.Product2.Variedade__c) + String.valueOf(s.UNIDADE__c) + String.valueOf(s.PricebookEntry.Product2.Categ__c), s.Quantity);

                    } else {

                        Double cant = mapReembalajes.get(String.valueOf(s.PricebookEntry.Product2.Variedade__c) + String.valueOf(s.UNIDADE__c) + String.valueOf(s.PricebookEntry.Product2.Categ__c));
                        cant += s.Quantity;
                        mapReembalajes.remove(String.valueOf(s.PricebookEntry.Product2.Variedade__c) + String.valueOf(s.UNIDADE__c) + String.valueOf(s.PricebookEntry.Product2.Categ__c));
                        mapReembalajes.put(String.valueOf(s.PricebookEntry.Product2.Variedade__c) + String.valueOf(s.UNIDADE__c) + String.valueOf(s.PricebookEntry.Product2.Categ__c), cant);
                    }
                }
            }

            Map<String,String> result = new Map<String,String>();

            for(String key : mapCantidades.KeySet()) {

                if(mapReembalajes.containsKey(key)) {

                    Double cantidad = mapCantidades.get(key) - mapReembalajes.get(key);
                    result.put(key, String.valueof(cantidad));
                }
            }

        return result;
    }

    public static List<aAppendix.myOppItem> setQuantitiesByVariedadAndUnidade(List<aAppendix.myOppItem> productList, Map<String, String> mapQuantities) {

        for(aAppendix.myOppItem product : productList) {
            if (mapQuantities.containsKey(product.variedad + product.unidade + product.categoria)) {
 
                product.sacas_disponibles = mapQuantities.get(product.variedad + product.unidade + product.categoria);
            }
        }
 
        return productList;            
    }  
}