Salesforce/main/default/objects/Account/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Marca</valueSetName>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Account/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Região</label>
    <referenceTo>Regiao__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/Opportunity/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <description>Identifica la marca para las Oportunidades del Circuito de Anexos. Se selecciona la lista de precios en función de este campo</description>
    <inlineHelpText>Identificar a marca de Oportunidades Circuito Anexos. Você seleciona a lista de preços com base neste campo</inlineHelpText>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BRMX</fullName>
            </value>
            <value>
                <fullName>DSEM</fullName>
            </value>
            <value>
                <fullName>NEOG</fullName>
            </value>
            <value>
                <fullName>DAGMA</fullName>
            </value>
            <value>
                <fullName>LICENÇAS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Opportunity/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Região</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SUR</fullName>
            </value>
            <value>
                <fullName>CERRADO</fullName>
            </value>
            <value>
                <fullName>REGION 1</fullName>
            </value>
            <value>
                <fullName>REGION 2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Opportunity/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <description>Safra o Campania agricola</description>
    <label>Safra</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>06/07</fullName>
            </value>
            <value>
                <fullName>07/08</fullName>
            </value>
            <value>
                <fullName>08/09</fullName>
            </value>
            <value>
                <fullName>09/10</fullName>
            </value>
            <value>
                <fullName>09/09</fullName>
            </value>
            <value>
                <fullName>10/10</fullName>
            </value>
            <value>
                <fullName>10/11</fullName>
            </value>
            <value>
                <fullName>11/11</fullName>
            </value>
            <value>
                <fullName>11/12</fullName>
            </value>
            <value>
                <fullName>12/12</fullName>
            </value>
            <value>
                <fullName>12/13</fullName>
            </value>
            <value>
                <fullName>13/14</fullName>
            </value>
            <value>
                <fullName>14/15</fullName>
            </value>
            <value>
                <fullName>15/16</fullName>
            </value>
            <value>
                <fullName>16/17</fullName>
            </value>
            <value>
                <fullName>17/18</fullName>
            </value>
            <value>
                <fullName>18/19</fullName>
            </value>
            <value>
                <fullName>19/20</fullName>
            </value>
            <value>
                <fullName>20/21</fullName>
            </value>
            <value>
                <fullName>21/22</fullName>
                <default>true</default>
                <label>21/22</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Opportunity/fields/Tipo_de_cambio__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_cambio__c</fullName>
    <description>Tipo de cambio al que sale impresa la factura</description>
    <inlineHelpText>Tipo de cambio al que sale impresa la factura</inlineHelpText>
    <label>Tipo de câmbio</label>
    <precision>16</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

Salesforce/main/default/main/default/objects/Opportunity/fields/Total_VL_Liquido__c.field-meta.xml
<CustomField>
    <fullName>Total_VL_Liquido__c</fullName>
    <label>Valor Total</label>
    <summarizedField>OpportunityLineItem.VL_Liquido_Copia__c</summarizedField>
    <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

Salesforce/main/default/main/default/objects/OpportunityLineItem/fields/Cot_Soja__c.field-meta.xml
<CustomField>
    <fullName>Cot_Soja__c</fullName>
    <label>Cot. Soja</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/OpportunityLineItem/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <formula>TEXT(Opportunity.Safra__c)</formula>
    <label>Safra</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/OpportunityLineItem/fields/Tipo_de_cambio__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_cambio__c</fullName>
    <label>Tipo de câmbio</label>
    <precision>16</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

Salesforce/main/default/objects/OpportunityLineItem/fields/Variedad__c.field-meta.xml
<CustomField>
    <fullName>Variedad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Variedades que pueden incluirse en el contrato de multiplicacion</description>
    <inlineHelpText>Variedades que pueden incluirse en el contrato de multiplicacion</inlineHelpText>
    <label>Variedad</label>
    <referenceTo>Variedad__c</referenceTo>
    <relationshipLabel>Producto de oportunidad</relationshipLabel>
    <relationshipName>Producto_de_oportunidad</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/OpportunityLineItem/fields/VL_Liquido__c.field-meta.xml
<CustomField>
    <fullName>VL_Liquido__c</fullName>
    <formula>Precio_total_estimado__c - Desconto__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>VL Liquido</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Salesforce/main/default/main/default/objects/Order/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Marca</valueSetName>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Order/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <label>Safra</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Safra</valueSetName>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Product2/fields/Variedad__c.field-meta.xml
<CustomField>
    <fullName>Variedad__c</fullName>
    <label>Variedad</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Licenciada__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>BMX APOLO RR</fullName>
            </value>
            <value>
                <fullName>BMX IMPACTO RR</fullName>
            </value>
            <value>
                <fullName>BMX MAGNA RR</fullName>
            </value>
            <value>
                <fullName>BMX POTÊNCIA RR</fullName>
            </value>
            <value>
                <fullName>BMX TITAN RR</fullName>
            </value>
            <value>
                <fullName>BMX FORÇA RR</fullName>
            </value>
            <value>
                <fullName>BMX ENERGIA RR</fullName>
            </value>
            <value>
                <fullName>BMX ATIVA RR</fullName>
            </value>
            <value>
                <fullName>BMX TURBO RR</fullName>
            </value>
            <value>
                <fullName>BMX VELOZ RR</fullName>
            </value>
            <value>
                <fullName>BMX ALVO RR</fullName>
            </value>
            <value>
                <fullName>BMX TORNADO RR</fullName>
            </value>
            <value>
                <fullName>BMX CLASSE RR</fullName>
            </value>
            <value>
                <fullName>BMX DESAFIO RR</fullName>
            </value>
            <value>
                <fullName>BMX RAÇA RR</fullName>
            </value>
            <value>
                <fullName>BMX PROGRESSO RR</fullName>
            </value>
            <value>
                <fullName>BRASMAX ELITE IPRO</fullName>
            </value>
            <value>
                <fullName>BRASMAX FLECHA IPRO</fullName>
            </value>
            <value>
                <fullName>BRASMAX BONUS IPRO</fullName>
            </value>
            <value>
                <fullName>BRASMAX BRAVA</fullName>
            </value>
            <value>
                <fullName>BRASMAX CLASSE</fullName>
            </value>
            <value>
                <fullName>BRASMAX PRISMA</fullName>
            </value>
            <value>
                <fullName>BRASMAX OPUS IPRO</fullName>
            </value>
            <value>
                <fullName>BRASMAX LANÇA IPRO</fullName>
            </value>
            <value>
                <fullName>BRASMAX GARRA IPRO</fullName>
            </value>
            <value>
                <fullName>BRASMAX ÍCONE IPRO</fullName>
            </value>
            <value>
                <fullName>BRASMAX POWER IPRO</fullName>
            </value>
            <value>
                <fullName>68I69RSF IPRO</fullName>
            </value>
            <value>
                <fullName>75I76RSF IPRO</fullName>
            </value>
            <value>
                <fullName>81I84RSF IPRO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Product2/fields/Variedade__c.field-meta.xml
<CustomField>
    <fullName>Variedade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Variedade</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Variedad__c.Licenciada__c</field>
            <operation>equals</operation>
            <valueField>$Source.Licenciada__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Variedad__c</referenceTo>
    <relationshipLabel>Productos</relationshipLabel>
    <relationshipName>Productos</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Variedad__c/Variedad__c.object-meta.xml
<CustomObject>
    <description>Variedades, disponibles para incluir en los Contratos de Multiplicación</description>
    <label>Variedad</label>
    <nameField>
        <label>Nome Comercial</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Variedades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/Variedad__c/fields/Nombre_de_Registro__c.field-meta.xml
<CustomField>
    <fullName>Nombre_de_Registro__c</fullName>
    <externalId>true</externalId>
    <label>Nombre de Registro</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/globalValueSets/Marca.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BRMX</fullName>
    </customValue>
    <customValue>
        <fullName>DSEM</fullName>
    </customValue>
    <customValue>
        <fullName>NEOG</fullName>
    </customValue>
    <customValue>
        <fullName>DAGMA</fullName>
    </customValue>
    <customValue>
        <fullName>LICENÇAS</fullName>
    </customValue>
    <masterLabel>Marca</masterLabel>
</GlobalValueSet>

Salesforce/main/default/globalValueSets/Safra.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>14/15</fullName>
    </customValue>
    <customValue>
        <fullName>15/16</fullName>
    </customValue>
    <customValue>
        <fullName>16/17</fullName>
    </customValue>
    <customValue>
        <fullName>17/18</fullName>
    </customValue>
    <customValue>
        <fullName>18/19</fullName>
    </customValue>
    <customValue>
        <fullName>19/20</fullName>
    </customValue>
    <customValue>
        <fullName>20/21</fullName>
    </customValue>
    <customValue>
        <fullName>21/22</fullName>
    </customValue>
    <customValue>
        <fullName>22/23</fullName>
    </customValue>
    <customValue>
        <fullName>23/24</fullName>
    </customValue>
    <customValue>
        <fullName>08/09</fullName>
        <isActive>false</isActive>
        <label>08/09</label>
    </customValue>
    <customValue>
        <fullName>07/08</fullName>
        <isActive>false</isActive>
        <label>07/08</label>
    </customValue>
    <customValue>
        <fullName>10/11</fullName>
        <isActive>false</isActive>
        <label>10/11</label>
    </customValue>
    <customValue>
        <fullName>11/12</fullName>
        <isActive>false</isActive>
        <label>11/12</label>
    </customValue>
    <customValue>
        <fullName>12/13</fullName>
        <isActive>false</isActive>
        <label>12/13</label>
    </customValue>
    <customValue>
        <fullName>13/14</fullName>
        <isActive>false</isActive>
        <label>13/14</label>
    </customValue>
    <customValue>
        <fullName>09/10</fullName>
        <isActive>false</isActive>
        <label>09/10</label>
    </customValue>
    <masterLabel>Safra</masterLabel>
</GlobalValueSet>

Salesforce/main/default/classes/Autorizar_Anticipos_Controller.cls
Public with sharing class Autorizar_Anticipos_Controller  {

    Public OpportunityLineItem Item;
    Public Opportunity opp = new Opportunity();    
    Public List<Opor> listaOpp = new List<Opor>();    
    Public String Mensaje;    
        
    Set<Id> resultIdsItemsAux = new Set<Id>();
         
    public Autorizar_Anticipos_Controller(){
        opp.safra__c = '20/21';
        opp.Marca__c = 'BRMX';
        opp.Region__c = 'REGION 1';
        opp.RecordTypeId = '01240000000M58N';
        if(Item == null)
            Item = new OpportunityLineItem();    
    }
        
    public class Opor{
        public Opportunity oport {get;set;}
        public Boolean selected {get;set;}        
    }                    
                   
    Public OpportunityLineItem getItem() {
        return Item;
    }
    
    Public void setItem(OpportunityLineItem i) {
        Item=i;
    }

    Public Opportunity getOpp() {
        return opp;
    }    
    Public void setOpp(Opportunity i) {
        opp=i;
    }
        
    Public List<Opor> getlistaOpp() {
        return listaOpp;
    }
    
    Public void setlistaOpp(List<Opor> arg) {
        listaOpp=arg;
    }
                        
    Public Void Buscar () {
    
        Mensaje='';
        
        if (listaOpp != null)
              listaOpp.clear();
              
        resultIdsItemsAux.clear();  
        
        if (opp.Safra__c == null){ Mensaje = 'Deve Selecionar uma Safra'; return;}
        
        if (opp.Marca__c == null || opp.Marca__c == ''){ Mensaje = 'Deve Selecionar uma Marca'; return;}
        
        if (opp.Region__c == null || opp.Region__c == ''){ Mensaje = 'Deve Selecionar uma Região'; return;}                                         
                                                       
        List<Opportunity> result;
                
        String qry;

        qry = 'SELECT Id, Name, CloseDate, Account.Name, Account.Id, Safra__c, Total_VL_Liquido__c';
        qry += ',(SELECT Id, PriceBookEntry.Product2.Name, PriceBookEntry.Product2.Variedad__c, PriceBookEntry.Product2.Variedade__r.Nombre_de_Registro__c, Quantity, UnitPrice, Tipo_de_Cambio__c, Cot_Soja__c, VL_Liquido__c From OpportunityLineItems)';
        qry += ' FROM Opportunity WHERE RecordType.Name= \'Antecipação Pendente\'';
        
        if (this.opp.Safra__c != null) qry += ' AND Safra__c = \''+this.opp.Safra__c+'\'';     
        
        if (this.opp.Marca__c != null) qry += ' AND Marca__c = \''+this.opp.Marca__c+'\'';     
        
        if (this.opp.Region__c != null) qry += ' AND Region__c = \''+this.opp.Region__c+'\'';     
                   
        qry += ' Order By Account.Name';                                                        
                        
        result = Database.query(qry);
                                    
        if (result != null){          
                        
           for (Opportunity o:result) {
              Opor op = new Opor();
              op.oport=o;
              op.selected=false; 
              listaOpp.add(op);           
           }
        }                                                                                                 
    }
              
    Public void AutorizarAnticipos () {
    
       List <Id> IdsOpps = New List <Id>();
       Boolean HaySeleccion = false;
       String retorno;
       
       Mensaje = '';              
                            
       for (Opor opo :listaOpp)
          if (opo.selected == true){
             HaySeleccion=true;
             break;
          }
          
       if (!HaySeleccion){
          Mensaje = 'Debe Seleccionar al menos una Oportunidad';
          return;
       }    
    
       for (Opor o :listaOpp)
          if (o.Selected == true)          
             IdsOpps.add(o.oport.Id);
             
       Anticipo_Sap_Alta.Retorno ret = Anticipo_Sap_Alta.enviarSAP(IdsOpps, '', 300);
       Mensaje = ret.msg;
                                  
       //Mensaje = 'El Proceso de Autorizacion ha comenzado. Recibira un Mail cuando haya finalizado.';
       listaOpp.clear();       
    }
            
    Public String getMensaje() {
       return Mensaje;      
    }

    Public void setMensaje(String arg) {
       Mensaje=arg;      
    }
    
    Public void SelectAll(){

       for (Opor o:listaOpp){        
          o.selected=true;
       }             

    }

    Public void quitarSeleccion(){

       for (Opor o:listaOpp){        
          o.selected=false;
       }             

    }        
}