Salesforce/main/default/objects/Account/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Marca</valueSetName>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Account/fields/Obtentor__c.field-meta.xml
<CustomField>
    <fullName>Obtentor__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Campo utilizado sólo por el administrador. Todas las Sociedades que están en los productos deben tener la cuenta marcada con Obtentor = true</description>
    <inlineHelpText>Campo utilizado sólo por el administrador. Todas las Sociedades que están en los productos deben tener la cuenta marcada con Obtentor = true</inlineHelpText>
    <label>Obtentor</label>
    <type>Checkbox</type>
</CustomField>

Salesforce/main/default/objects/CRM_Calendario_de_Eventos__c/CRM_Calendario_de_Eventos__c.object-meta.xml
<CustomObject>
    <description>Registro de eventos programados pelo Multiplicador</description>
    <label>CRM Evento</label>
    <nameField>
        <label>Nome de CRM Evento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Eventos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/objects/CRM_Calendario_de_Eventos__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Conta multiplicador, que realizou ou eventos agendados</description>
    <inlineHelpText>Conta multiplicador, que realizou ou eventos agendados</inlineHelpText>
    <label>Nome da conta</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Agricultor__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Eventos (Cuenta)</relationshipLabel>
    <relationshipName>CRM_Calend_rio_de_eventos</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/CRM_Calendario_de_Eventos__c/fields/Evento__c.field-meta.xml
<CustomField>
    <fullName>Evento__c</fullName>
    <description>Tipo de evento</description>
    <inlineHelpText>Tipo de evento</inlineHelpText>
    <label>Evento</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Día de Campo</fullName>
            </value>
            <value>
                <fullName>Area comercial</fullName>
            </value>
            <value>
                <fullName>Emplacamento</fullName>
            </value>
            <value>
                <fullName>Encontro Técnico</fullName>
            </value>
            <value>
                <fullName>Estação DONMARIO MAS</fullName>
            </value>
            <value>
                <fullName>Feiras</fullName>
            </value>
            <value>
                <fullName>Jornada Técnica</fullName>
            </value>
            <value>
                <fullName>Lado a Lado</fullName>
            </value>
            <value>
                <fullName>Painel Técnico</fullName>
            </value>
            <value>
                <fullName>Palestra</fullName>
            </value>
            <value>
                <fullName>Strip Test</fullName>
            </value>
            <value>
                <fullName>Tour dos Máximos Rendimentos</fullName>
            </value>
            <value>
                <fullName>Treinamento</fullName>
            </value>
            <value>
                <fullName>CESB</fullName>
            </value>
            <value>
                <fullName>Outdoor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/CRM_Calendario_de_Eventos__c/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <label>Safra</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>11/12</fullName>
            </value>
            <value>
                <fullName>12/13</fullName>
            </value>
            <value>
                <fullName>17/18</fullName>
            </value>
            <value>
                <fullName>18/19</fullName>
            </value>
            <value>
                <fullName>19/20</fullName>
            </value>
            <value>
                <fullName>20/21</fullName>
            </value>
            <value>
                <fullName>21/22</fullName>
                <default>true</default>
                <label>21/22</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/CRM_Calendario_de_Eventos__c/recordTypes/Emplacamento.recordType-meta.xml
<RecordType>
    <fullName>Emplacamento</fullName>
    <active>true</active>
    <description>Emplacamentos</description>
    <label>Emplacamento</label>
</RecordType>

Salesforce/main/default/objects/CRM_Detalle_Calendario_de_eventos__c/CRM_Detalle_Calendario_de_eventos__c.object-meta.xml
<CustomObject>
    <label>CRM Detalle Calendário de eventos</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Nombre de CRM Detalle Calendário de even</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CRM Detalles Calendário de eventos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Salesforce/main/default/objects/CRM_Detalle_Calendario_de_eventos__c/fields/CRM_Calendario_de_eventos__c.field-meta.xml
<CustomField>
    <fullName>CRM_Calendario_de_eventos__c</fullName>
    <label>CRM Calendário de eventos</label>
    <referenceTo>CRM_Calendario_de_Eventos__c</referenceTo>
    <relationshipLabel>Itens</relationshipLabel>
    <relationshipName>CRM_Detalles_Calend_rio_de_eventos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Salesforce/main/default/main/default/objects/CRM_Detalle_Calendario_de_eventos__c/fields/Cultivar__c.field-meta.xml
<CustomField>
    <fullName>Cultivar__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cultivar</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1</booleanFilter>
        <filterItems>
            <field>Product2.Obtentor__c</field>
            <operation>notEqual</operation>
            <value/>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>CRM Detalles Calendário de eventos</relationshipLabel>
    <relationshipName>CRM_Detalles_Calend_rio_de_eventos</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/CRM_Detalle_Calendario_de_eventos__c/fields/Obtentor__c.field-meta.xml
<CustomField>
    <fullName>Obtentor__c</fullName>
    <label>Obtentor</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/Product2/fields/Obtentor__c.field-meta.xml
<CustomField>
    <fullName>Obtentor__c</fullName>
    <description>Lista de Obtentores que debemos mantener(admin)</description>
    <inlineHelpText>Lista de Obtentores que debemos mantener(admin)</inlineHelpText>
    <label>Obtentor</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ADVANTA</fullName>
            </value>
            <value>
                <fullName>Agrária</fullName>
            </value>
            <value>
                <fullName>Agroeste</fullName>
            </value>
            <value>
                <fullName>AGROMEN</fullName>
            </value>
            <value>
                <fullName>Agro Norte</fullName>
            </value>
            <value>
                <fullName>Avanti Seeds</fullName>
            </value>
            <value>
                <fullName>Basf</fullName>
            </value>
            <value>
                <fullName>Bayer</fullName>
            </value>
            <value>
                <fullName>Brasmax</fullName>
            </value>
            <value>
                <fullName>BREVANT</fullName>
            </value>
            <value>
                <fullName>Br Genetica</fullName>
            </value>
            <value>
                <fullName>CARAIBA</fullName>
            </value>
            <value>
                <fullName>CCGL Tecnología</fullName>
            </value>
            <value>
                <fullName>Coodetec</fullName>
            </value>
            <value>
                <fullName>CORDIUS</fullName>
            </value>
            <value>
                <fullName>CPTA</fullName>
            </value>
            <value>
                <fullName>Credenz</fullName>
            </value>
            <value>
                <fullName>CTP</fullName>
            </value>
            <value>
                <fullName>CTPA/Emgopa</fullName>
            </value>
            <value>
                <fullName>DM Licenças</fullName>
            </value>
            <value>
                <fullName>Don Mario</fullName>
            </value>
            <value>
                <fullName>Dow</fullName>
            </value>
            <value>
                <fullName>Embrapa</fullName>
            </value>
            <value>
                <fullName>FMT</fullName>
            </value>
            <value>
                <fullName>FPS</fullName>
            </value>
            <value>
                <fullName>FT</fullName>
            </value>
            <value>
                <fullName>Fundacep</fullName>
            </value>
            <value>
                <fullName>GDML</fullName>
            </value>
            <value>
                <fullName>Genetica Soy</fullName>
            </value>
            <value>
                <fullName>Geneze</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/globalValueSets/Marca.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BRMX</fullName>
    </customValue>
    <customValue>
        <fullName>DSEM</fullName>
    </customValue>
    <customValue>
        <fullName>NEOG</fullName>
    </customValue>
    <customValue>
        <fullName>DAGMA</fullName>
    </customValue>
    <customValue>
        <fullName>LICENÇAS</fullName>
    </customValue>
    <masterLabel>Marca</masterLabel>
</GlobalValueSet>

Salesforce/main/default/main/default/classes/TestDAOCRMCalendarioDeEventos.cls
@isTest
public class TestDAOCRMCalendarioDeEventos {
    @isTest
    public static void testEvents(){
        Account acc = new Account(Name = 'Teste');
        insert acc;
        CRM_Calendario_de_Eventos__c event = new CRM_Calendario_de_Eventos__c(Name = 'Teste', Cuenta__c = acc.Id, Marca__c = 'NEOG', Evento__c = 'Emplacamento', Safra__c = '18/19');
        insert event;
        DAOCRMCalendarioDeEventos.getInstance().get(event.Id);
        DAOCRMCalendarioDeEventos.getInstance(DTOUtils.SharingMode.Without).get(event.Id);
        Product2 prod = new Product2();
        prod.Name = 'Test';
        prod.Obtentor__c = 'Bayer';
        insert prod;
        CRM_Detalle_Calendario_de_eventos__c nprod = new CRM_Detalle_Calendario_de_eventos__c(CRM_Calendario_de_eventos__c = event.id,Cultivar__c = prod.id );
        insert nprod;
        DAOCRMDetalleCalendarioDeEventos.getInstance().getByCRMCalendarioId(event.Id);
        DAOCRMDetalleCalendarioDeEventos.getInstance(DTOUtils.SharingMode.Without).getByCRMCalendarioId(event.Id);
        
    }
}