Salesforce/main/default/objects/Account/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Marca</valueSetName>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Account/fields/Responsavel__c.field-meta.xml
<CustomField>
    <fullName>Responsavel__c</fullName>
    <description>Qual dos funcionários da Brasmax que estará responsável pela conta</description>
    <inlineHelpText>Qual dos funcionários da Brasmax que estará responsável pela conta</inlineHelpText>
    <label>Responsável BRMX</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>061 - Fernando Frehner</fullName>
            </value>
            <value>
                <fullName>066 - Marcelo Steffen</fullName>
            </value>
            <value>
                <fullName>067 - Sergio Bertagnolli</fullName>
            </value>
            <value>
                <fullName>076 - Tiago Goulart</fullName>
            </value>
            <value>
                <fullName>083 - Jorge Cristiano Rosa</fullName>
            </value>
            <value>
                <fullName>010 - Brasmax</fullName>
            </value>
            <value>
                <fullName>101 - Fausto Tadeu Fanchin</fullName>
            </value>
            <value>
                <fullName>104 - Otavio Gorni</fullName>
            </value>
            <value>
                <fullName>150 - João Serrano</fullName>
            </value>
            <value>
                <fullName>012 - Anderson Weissheimer</fullName>
            </value>
            <value>
                <fullName>197 - Wagner Rank</fullName>
            </value>
            <value>
                <fullName>198 - Bernardo Zanardo</fullName>
            </value>
            <value>
                <fullName>199 - Lucas Costa</fullName>
            </value>
            <value>
                <fullName>231 - Willian Von Scharten</fullName>
            </value>
            <value>
                <fullName>234 - Julio Cesar Poletto</fullName>
            </value>
            <value>
                <fullName>017 - Luis Fernando Cecatto</fullName>
            </value>
            <value>
                <fullName>018 - Flávio Marçal dos Santos</fullName>
            </value>
            <value>
                <fullName>312 - Lucas Hilario Fantineli</fullName>
            </value>
            <value>
                <fullName>019 - Felipe Oliveira Costa</fullName>
            </value>
            <value>
                <fullName>379 - Diego F. Gonçalves</fullName>
            </value>
            <value>
                <fullName>031 - Guilherme Sousa</fullName>
            </value>
            <value>
                <fullName>023 - Gabriel V. Finatto</fullName>
            </value>
            <value>
                <fullName>464 - Ana Laura Fernandes</fullName>
            </value>
            <value>
                <fullName>467 - Natalie de Mattos</fullName>
            </value>
            <value>
                <fullName>474 - Guilherme Menezes Salau</fullName>
            </value>
            <value>
                <fullName>403 - Felipe Bianchessi</fullName>
            </value>
            <value>
                <fullName>380 - Lucas de Souza Furlan</fullName>
            </value>
            <value>
                <fullName>037 - Felipe Dias Louzada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Account/recordTypes/Cuenta.recordType-meta.xml
<RecordType>
    <fullName>Cuenta</fullName>
    <active>true</active>
    <label>Cuenta</label>
</RecordType>

Salesforce/main/default/objects/Case/fields/Ciudad_del_Problema__c.field-meta.xml
<CustomField>
    <fullName>Ciudad_del_Problema__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cidade do Problema</label>
    <referenceTo>Cidade__c</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/Case/fields/Data_da_solu_o_do_caso__c.field-meta.xml
<CustomField>
    <fullName>Data_da_solu_o_do_caso__c</fullName>
    <label>Data da solução do caso</label>
    <type>Date</type>
</CustomField>

Salesforce/main/default/main/default/objects/Case/fields/Data_do_problema__c.field-meta.xml
<CustomField>
    <fullName>Data_do_problema__c</fullName>
    <label>Data do problema</label>
    <type>Date</type>
</CustomField>

Salesforce/main/default/main/default/objects/Case/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <description>Este campo indica a que empresa corresponde el reclamo.</description>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BRMX</fullName>
            </value>
            <value>
                <fullName>DSEM</fullName>
            </value>
            <value>
                <fullName>NEOG</fullName>
            </value>
            <value>
                <fullName>DAGMA</fullName>
            </value>
            <value>
                <fullName>LICENÇAS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Case/fields/Responsavel__c.field-meta.xml
<CustomField>
    <fullName>Responsavel__c</fullName>
    <description>Asignado en base al responsable de la cuenta para cada marca</description>
    <inlineHelpText>Asignado en base al responsable de la cuenta para cada marca</inlineHelpText>
    <label>Responsável</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/Case/fields/Responsavel_pelo_atendimento__c.field-meta.xml
<CustomField>
    <fullName>Responsavel_pelo_atendimento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Responsável pelo atendimento</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Case/fields/Respuesta__c.field-meta.xml
<CustomField>
    <fullName>Respuesta__c</fullName>
    <description>Respuesta al reclamo de Venta de Basica</description>
    <label>Resolução</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

Salesforce/main/default/main/default/objects/Case/recordTypes/Reclamo.recordType-meta.xml
<RecordType>
    <fullName>Reclamo</fullName>
    <active>true</active>
    <businessProcess>Reclamos</businessProcess>
    <label>Reclamo</label>
</RecordType>

Salesforce/main/default/main/default/objects/Cidade__c/Cidade__c.object-meta.xml
<CustomObject>
    <label>Ciudad</label>
    <nameField>
        <label>Nome da Cidade</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ciudades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/Contact/fields/Cidade__c.field-meta.xml
<CustomField>
    <fullName>Cidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cidade</label>
    <referenceTo>Cidade__c</referenceTo>
    <relationshipLabel>Contactos</relationshipLabel>
    <relationshipName>Contactos</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Contact/fields/Usuario_Reclamos__c.field-meta.xml
<CustomField>
    <fullName>Usuario_Reclamos__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Usuario Reclamos</label>
    <length>60</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Salesforce/main/default/objects/User/fields/Usuario_Reclamos__c.field-meta.xml
<CustomField>
    <fullName>Usuario_Reclamos__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Usuario Reclamos</label>
    <length>60</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Salesforce/main/default/globalValueSets/Marca.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BRMX</fullName>
    </customValue>
    <customValue>
        <fullName>DSEM</fullName>
    </customValue>
    <customValue>
        <fullName>NEOG</fullName>
    </customValue>
    <customValue>
        <fullName>DAGMA</fullName>
    </customValue>
    <customValue>
        <fullName>LICENÇAS</fullName>
    </customValue>
    <masterLabel>Marca</masterLabel>
</GlobalValueSet>

Salesforce/main/default/classes/ReclamosTest.cls
@istest (seeAllData=true)
    private class ReclamosTest {
        static testmethod void theTest(){
            Case reclamoPrueba = New Case();
            Case pdfPrueba = New Case();
            User duenioReclamo = New User();
            Account cuenta = New Account();
            Contact contactoR = New Contact();
            Cidade__c CiudadTest = New Cidade__c();
            
            duenioReclamo = [SELECT Id FROM User WHERE isActive = true and Usuario_Reclamos__c like '%Fernando%' limit 1];
            cuenta = [SELECT Id FROM Account WHERE Name = 'ACME' limit 1];
            contactoR = [SELECT Id FROM Contact WHERE Usuario_Reclamos__c = 'Tiago Goulart' limit 1];
            CiudadTest = [SELECT Id FROM Cidade__c WHERE Name = 'PASSO FUNDO' limit 1];
            reclamoPrueba.Responsavel__c = '061 - Fernando Frehner';
            reclamoPrueba.Responsavel_pelo_atendimento__c = duenioReclamo.Id;
            reclamoPrueba.OwnerId = duenioReclamo.Id;
            reclamoPrueba.Marca__c = 'BRASMAX';
            reclamoPrueba.ContactId = contactoR.Id;
            reclamoPrueba.AccountId = cuenta.Id;
            reclamoPrueba.Ciudad_del_Problema__c = CiudadTest.Id;
            
            insert reclamoPrueba;

            PdfGeneratorController.savePdfReclamo(reclamoPrueba.Id, 'TestPdf');
            ApexPages.StandardController sc = new ApexPages.standardController(reclamoPrueba);
            PdfGeneratorController myPage = new PdfGeneratorController(sc);            
                    
            PageReference pageRef = Page.PdfGeneratorReclamo;
            pageRef.getParameters().put('id', String.valueOf(reclamoPrueba.Id));
            Test.setCurrentPage(pageRef);
            
            myPage.getReclamo();
            
            reclamosController.Asignar(reclamoPrueba.Id, duenioReclamo.Id);
            reclamosController.reclamoAEdicion(reclamoPrueba.Id, true);
        }
            
        static testmethod void theTest1(){
            Case reclamoPrueba = New Case();
            User duenioReclamo = New User();
            Account cuenta = New Account();
            Contact contactoR = New Contact();
            RecordType rt = New RecordType();
            
            duenioReclamo = [SELECT Id FROM User WHERE Name = 'Patricia Ueno' limit 1];
            cuenta = [SELECT Id FROM Account WHERE Name = 'ACME' limit 1];
            contactoR = [SELECT Id FROM Contact WHERE Usuario_Reclamos__c = 'Tiago Goulart' limit 1];
            rt = [SELECT Id, Name FROM RecordType WHERE Name = 'Reclamo Venda Basica' limit 1];
            reclamoPrueba.OwnerId = duenioReclamo.Id;
            reclamoPrueba.Marca__c = 'BRMX';
            reclamoPrueba.ContactId = contactoR.Id;
            reclamoPrueba.AccountId = cuenta.Id;
            reclamoPrueba.Reason = 'Atraso';
            reclamoPrueba.RecordTypeId = rt.Id;
            reclamoPrueba.Status = 'Aberta';
            reclamoPrueba.Description = 'Lalalalala';
            reclamoPrueba.Data_do_problema__c = System.today();
            
            //insert reclamoPrueba;
            
            reclamoPrueba.Respuesta__c = 'dsdfskfhkshfkjshfjks';
            reclamoPrueba.Data_da_solu_o_do_caso__c = System.today();
            reclamoPrueba.Status = 'Fechada';
            
            //update reclamoPrueba;            
            
        }   
    }