Salesforce/main/default/objects/Account/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Marca</valueSetName>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Account/recordTypes/Cuenta.recordType-meta.xml
<RecordType>
    <fullName>Cuenta</fullName>
    <active>true</active>
    <label>Cuenta</label>
</RecordType>

Salesforce/main/default/main/default/objects/Categoria__c/Categoria__c.object-meta.xml
<CustomObject>
    <description>Categorías</description>
    <label>Categoria</label>
    <nameField>
        <label>Nombre de Categoría</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categorias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/objects/Opportunity/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <description>Identifica la marca para las Oportunidades del Circuito de Anexos. Se selecciona la lista de precios en función de este campo</description>
    <inlineHelpText>Identificar a marca de Oportunidades Circuito Anexos. Você seleciona a lista de preços com base neste campo</inlineHelpText>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BRMX</fullName>
            </value>
            <value>
                <fullName>DSEM</fullName>
            </value>
            <value>
                <fullName>NEOG</fullName>
            </value>
            <value>
                <fullName>DAGMA</fullName>
            </value>
            <value>
                <fullName>LICENÇAS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Opportunity/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <description>Safra o Campania agricola</description>
    <label>Safra</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>06/07</fullName>
            </value>
            <value>
                <fullName>07/08</fullName>
            </value>
            <value>
                <fullName>08/09</fullName>
            </value>
            <value>
                <fullName>09/10</fullName>
            </value>
            <value>
                <fullName>09/09</fullName>
            </value>
            <value>
                <fullName>10/10</fullName>
            </value>
            <value>
                <fullName>10/11</fullName>
            </value>
            <value>
                <fullName>11/11</fullName>
            </value>
            <value>
                <fullName>11/12</fullName>
            </value>
            <value>
                <fullName>12/12</fullName>
            </value>
            <value>
                <fullName>12/13</fullName>
            </value>
            <value>
                <fullName>13/14</fullName>
            </value>
            <value>
                <fullName>14/15</fullName>
            </value>
            <value>
                <fullName>15/16</fullName>
            </value>
            <value>
                <fullName>16/17</fullName>
            </value>
            <value>
                <fullName>17/18</fullName>
            </value>
            <value>
                <fullName>18/19</fullName>
            </value>
            <value>
                <fullName>19/20</fullName>
            </value>
            <value>
                <fullName>20/21</fullName>
            </value>
            <value>
                <fullName>21/22</fullName>
                <default>true</default>
                <label>21/22</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Opportunity/recordTypes/Autorizada.recordType-meta.xml
<RecordType>
    <fullName>Autorizada</fullName>
    <active>true</active>
    <businessProcess>Nota de Venta - Autorizada</businessProcess>
    <label>Autorizada</label>
</RecordType>

Salesforce/main/default/objects/Opportunity/recordTypes/Comercial.recordType-meta.xml
<RecordType>
    <fullName>Comercial</fullName>
    <active>true</active>
    <businessProcess>Control_Multiplicador</businessProcess>
    <description>Detalle de lo que el multiplicador va a vender: relatorio de venda</description>
    <label>Comercial</label>
</RecordType>

Salesforce/main/default/main/default/objects/Opportunity/recordTypes/Exportacion.recordType-meta.xml
<RecordType>
    <fullName>Exportacion</fullName>
    <active>true</active>
    <businessProcess>Circuito de Anexos</businessProcess>
    <label>Exportacion</label>
</RecordType>

Salesforce/main/default/main/default/objects/Opportunity/recordTypes/Pendiente.recordType-meta.xml
<RecordType>
    <fullName>Pendiente</fullName>
    <active>true</active>
    <businessProcess>Nota de Venta - Pendiente</businessProcess>
    <label>Pendiente</label>
</RecordType>

Salesforce/main/default/main/default/objects/Opportunity/recordTypes/Previsao.recordType-meta.xml
<RecordType>
    <fullName>Previsao</fullName>
    <active>true</active>
    <businessProcess>Prevision Venta Basica</businessProcess>
    <description>Previsiones de Ventas de Bolsas de Básica</description>
    <label>Previsao</label>
</RecordType>

Salesforce/main/default/objects/Opportunity/recordTypes/Rechazada.recordType-meta.xml
<RecordType>
    <fullName>Rechazada</fullName>
    <active>true</active>
    <businessProcess>Fc de Brasmax</businessProcess>
    <label>Rechazada</label>
</RecordType>

Salesforce/main/default/objects/OpportunityLineItem/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Categoria a ser licenciada</description>
    <inlineHelpText>Categoria a ser licenciada</inlineHelpText>
    <label>Categoria</label>
    <referenceTo>Categoria__c</referenceTo>
    <relationshipLabel>Producto de oportunidad</relationshipLabel>
    <relationshipName>Producto_de_oportunidad</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/OpportunityLineItem/fields/Previsao__c.field-meta.xml
<CustomField>
    <fullName>Previsao__c</fullName>
    <label>Previsão</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/objects/OpportunityLineItem/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <formula>TEXT(Opportunity.Safra__c)</formula>
    <label>Safra</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/Product2/fields/Categ__c.field-meta.xml
<CustomField>
    <fullName>Categ__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Categ</label>
    <referenceTo>Categoria__c</referenceTo>
    <relationshipLabel>Productos</relationshipLabel>
    <relationshipName>Productos</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Product2/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <label>Categoria</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BREEDER</fullName>
            </value>
            <value>
                <fullName>FUNDADORA</fullName>
            </value>
            <value>
                <fullName>Genetica</fullName>
            </value>
            <value>
                <fullName>Pre Basica</fullName>
            </value>
            <value>
                <fullName>BASICA</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>C1</fullName>
            </value>
            <value>
                <fullName>C2</fullName>
            </value>
            <value>
                <fullName>R</fullName>
            </value>
            <value>
                <fullName>S1</fullName>
            </value>
            <value>
                <fullName>S2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/globalValueSets/Marca.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BRMX</fullName>
    </customValue>
    <customValue>
        <fullName>DSEM</fullName>
    </customValue>
    <customValue>
        <fullName>NEOG</fullName>
    </customValue>
    <customValue>
        <fullName>DAGMA</fullName>
    </customValue>
    <customValue>
        <fullName>LICENÇAS</fullName>
    </customValue>
    <masterLabel>Marca</masterLabel>
</GlobalValueSet>

Salesforce/main/default/main/default/classes/opportunitySacasExtensionTest.cls
@isTest
public class opportunitySacasExtensionTest{
	@isTest(SeeAllData = true)
	static void test(){

		Map<String, Id> rt = new Map<String, Id>();
		for (RecordType reTy : [Select Id, Name
		                        From RecordType
		                        Where sObjectType = 'Opportunity'])
			rt.put(reTy.Name, reTy.Id);
		opportunitySacasExtension anexos = new opportunitySacasExtension();

		anexos.searchAnexos();
		anexos.listarAnexos();
		String a;
		anexos.setetapaAnexo(a);
		a = anexos.getetapaAnexo();
		List<SelectOption> op = new List<SelectOption>();
		op = anexos.getEtapasAnexos();
		op = anexos.getTiposAnexos();
		anexos.getResultAnexos();
		List<OpportunityLineItem> items = new List<OpportunityLineItem>();

		Categoria__c cat = [SELECT Id, Name
		                    FROM Categoria__c
		                    WHERE Name = 'BASICA'
		                    limit 1];

		Account cuenta = [Select Id
		                  From Account
		                  Where Name = 'ACME'
		                  limit 1];
		Pricebook2 pb = [Select Id, Name
		                 From Pricebook2
		                 where Name = 'Lista de Básica BMX SUL' and isActive = true
		                 limit 1];
		Opportunity prevision = new Opportunity(RecordTypeId = rt.get('Previsao'), Name = 'Previsao', AccountId = cuenta.Id, Pricebook2Id = pb.Id, CloseDate = System.today(), Marca__c = 'BRMX', StageName = 'Aberta', Safra__c = '12/13');
		//insert prevision;
		PricebookEntry pbe = [Select Id, Product2Id
		                      From PricebookEntry
		                      where Pricebook2Id = :pb.Id and isActive = true and Product2.Categ__c = :cat.Id
		                      limit 1];

		OpportunityLineItem oi2 = new OpportunityLineItem(OpportunityId = prevision.Id, Quantity = 0.01, Previsao__c = 50, TotalPrice = 10, PricebookEntryId = pbe.Id);
		//insert oi2;
	}

	@isTest(SeeAllData = true)
	static void test2(){

		Map<String, Id> rt = new Map<String, Id>();
		for (RecordType reTy : [Select Id, Name
		                        From RecordType
		                        Where sObjectType = 'Opportunity'])
			rt.put(reTy.Name, reTy.Id);
		opportunitySacasExtension anexos = new opportunitySacasExtension();

		List<OpportunityLineItem> items = new List<OpportunityLineItem>();

		Categoria__c cat = [SELECT Id, Name
		                    FROM Categoria__c
		                    WHERE Name = 'BASICA'
		                    limit 1];

		Account cuenta = [Select Id
		                  From Account
		                  Where Name = 'ACME'
		                  limit 1];
		Pricebook2 pb = [Select Id, Name
		                 From Pricebook2
		                 where Name = 'Lista de Básica BMX SUL' and isActive = true
		                 limit 1];
		Opportunity prevision = new Opportunity(RecordTypeId = rt.get('Previsao'), Name = 'Previsao', AccountId = cuenta.Id, Pricebook2Id = pb.Id, CloseDate = System.today(), Marca__c = 'BRMX', StageName = 'Aberta', Safra__c = '12/13');
		insert prevision;
		PricebookEntry pbe = [Select Id, Product2Id
		                      From PricebookEntry
		                      where Pricebook2Id = :pb.Id and isActive = true and Product2.Categ__c = :cat.Id
		                      limit 1];

		OpportunityLineItem oi2 = new OpportunityLineItem(OpportunityId = prevision.Id, Quantity = 0.01, Previsao__c = 50, TotalPrice = 10, PricebookEntryId = pbe.Id);
		insert oi2;


		ApexPages.currentPage().getParameters().put('id', prevision.Id);
		items = anexos.getItems();
		List<Schema.FieldSetMember> b = anexos.getFields();

		Opportunity prueba1 = new Opportunity(RecordTypeId = rt.get('VB - Pendiente'), Name = 'Prueba1', AccountId = cuenta.Id, Pricebook2Id = pb.Id, CloseDate = System.today(), Marca__c = 'BRMX', StageName = 'Aberta', Safra__c = '12/13');
		insert prueba1;

		OpportunityLineItem p1oi2 = new OpportunityLineItem(OpportunityId = prevision.Id, Quantity = 0.01, Previsao__c = 50, TotalPrice = 10, PricebookEntryId = pbe.Id);
		insert p1oi2;

		ApexPages.currentPage().getParameters().put('id', prueba1.Id);
		anexos.getFields();

		Opportunity prueba2 = new Opportunity(RecordTypeId = rt.get('Disponibilidade da Basica'), Name = 'Prueba2', AccountId = cuenta.Id, Pricebook2Id = pb.Id, CloseDate = System.today(), Marca__c = 'BRMX', StageName = 'Aberta', Safra__c = '12/13');
		insert prueba2;

		OpportunityLineItem p2oi2 = new OpportunityLineItem(OpportunityId = prevision.Id, Quantity = 0.01, Previsao__c = 50, TotalPrice = 10, PricebookEntryId = pbe.Id);
		Test.StartTest();
		insert p2oi2;
		Test.StopTest();

		ApexPages.currentPage().getParameters().put('id', prueba2.Id);
		anexos.getFields();

		Opportunity prueba3 = new Opportunity(RecordTypeId = rt.get('Stock Multiplicadores'), Name = 'Prueba1', AccountId = cuenta.Id, Pricebook2Id = pb.Id, CloseDate = System.today(), Marca__c = 'BRMX', StageName = 'Aberta', Safra__c = '12/13');
		insert prueba3;


		ApexPages.currentPage().getParameters().put('id', prueba3.Id);
		anexos.getFields();

		Opportunity prueba4 = new Opportunity(RecordTypeId = rt.get('Rechazada'), Name = 'Prueba1', AccountId = cuenta.Id, Pricebook2Id = pb.Id, CloseDate = System.today(), Marca__c = 'BRMX', StageName = 'Aberta', Safra__c = '12/13');
		insert prueba4;


		ApexPages.currentPage().getParameters().put('id', prueba4.Id);
		anexos.getFields();
	}
    

	@isTest(SeeAllData = true)
	static void test3(){

		Map<String, Id> rt = new Map<String, Id>();
		for (RecordType reTy : [Select Id, Name
		                        From RecordType
		                        Where sObjectType = 'Opportunity'])
			rt.put(reTy.Name, reTy.Id);
		opportunitySacasExtension anexos = new opportunitySacasExtension();

		List<OpportunityLineItem> items = new List<OpportunityLineItem>();

		Categoria__c cat = [SELECT Id, Name
		                    FROM Categoria__c
		                    WHERE Name = 'BASICA'
		                    limit 1];

		Account cuenta = [Select Id
		                  From Account
		                  Where Name = 'ACME'
		                  limit 1];
		Pricebook2 pb = [Select Id, Name
		                 From Pricebook2
		                 where Name = 'Lista de Básica BMX SUL' and isActive = true
		                 limit 1];
		Opportunity prevision = new Opportunity(RecordTypeId = rt.get('Previsao'), Name = 'Previsao', AccountId = cuenta.Id, Pricebook2Id = pb.Id, CloseDate = System.today(), Marca__c = 'BRMX', StageName = 'Aberta', Safra__c = '12/13');
		insert prevision;
		PricebookEntry pbe = [Select Id, Product2Id
		                      From PricebookEntry
		                      where Pricebook2Id = :pb.Id and isActive = true and Product2.Categ__c = :cat.Id
		                      limit 1];

		OpportunityLineItem oi2 = new OpportunityLineItem(OpportunityId = prevision.Id, Quantity = 0.01, Previsao__c = 50, TotalPrice = 10, PricebookEntryId = pbe.Id);
		insert oi2;


		ApexPages.currentPage().getParameters().put('id', prevision.Id);
		items = anexos.getItems();
		List<Schema.FieldSetMember> b = anexos.getFields();

		Opportunity prueba5 = new Opportunity(RecordTypeId = rt.get('Pendiente'), Name = 'Prueba1', AccountId = cuenta.Id, Pricebook2Id = pb.Id, CloseDate = System.today(), Marca__c = 'BRMX', StageName = 'Aberta', Safra__c = '12/13');
		insert prueba5;


		ApexPages.currentPage().getParameters().put('id', prueba5.Id);
		anexos.getFields();

		Opportunity prueba6 = new Opportunity(RecordTypeId = rt.get('Anexo V'), Name = 'Prueba1', AccountId = cuenta.Id, Pricebook2Id = pb.Id, CloseDate = System.today(), Marca__c = 'BRMX', StageName = 'Aberta', Safra__c = '12/13');
		insert prueba6;


		ApexPages.currentPage().getParameters().put('id', prueba6.Id);
		anexos.getFields();

		Opportunity prueba7 = new Opportunity(RecordTypeId = rt.get('Anexo IV'), Name = 'Prueba1', AccountId = cuenta.Id, Pricebook2Id = pb.Id, CloseDate = System.today(), Marca__c = 'BRMX', StageName = 'Aberta', Safra__c = '12/13');
		Test.StartTest();
		insert prueba7;
		Test.StopTest();


		ApexPages.currentPage().getParameters().put('id', prueba7.Id);
		anexos.getFields();

		Opportunity prueba8 = new Opportunity(RecordTypeId = rt.get('Anexo III'), Name = 'Prueba1', AccountId = cuenta.Id, Pricebook2Id = pb.Id, CloseDate = System.today(), Marca__c = 'BRMX', StageName = 'Aberta', Safra__c = '12/13');
		insert prueba8;


		ApexPages.currentPage().getParameters().put('id', prueba8.Id);
		anexos.getFields();

		anexos.anexo = 'A1';
		anexos.searchAnexos();
		anexos.anexo = 'A2';
		anexos.searchAnexos();
		anexos.anexo = 'A3';
		anexos.searchAnexos();
		anexos.anexo = 'A4';
		anexos.searchAnexos();
		anexos.anexo = 'A5';
		anexos.searchAnexos();
		anexos.anexo = 'ALL';
		anexos.searchAnexos();

		anexos.etapaAnexo = 'PEAN';
		anexos.searchAnexos();
		anexos.etapaAnexo = 'PEAP';
		anexos.searchAnexos();
		anexos.etapaAnexo = 'APR';
		anexos.searchAnexos();

		for (AggregateResult ar : [Select Max(Id)id, RecordType.Name rt
		                           From Opportunity
		                           Where RecordType.Name In ('Anexo I', 'Anexo II', 'NC - Autorizada', 'Autorizada', 'Anexo I Rebaixamento Ha', 'Anexo II Rebaixamento Sacas', 'VB - Pasada SAP', 'CVB Autorizada', 'PB-Comercial', 'Exportacion', 'Objetivo Ventas Semilla', 'Objetivo Ventas Royalties', 'Objetivo Contrato Royalties')
		                           Group By RecordType.Name]){
			apexpages.currentpage().getparameters().put('Id', String.valueOf(ar.get('id')));
			anexos.getFields();
		}
	}
}