Salesforce/main/default/objects/Account/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Marca</valueSetName>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Opportunity/fields/Estado_de_produccion__c.field-meta.xml
<CustomField>
    <fullName>Estado_de_produccion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Estado de produccion, para incluir en el contrato de multiplicacion</description>
    <inlineHelpText>Estado de produccion, para incluir en el contrato de multiplicacion</inlineHelpText>
    <label>Estado de produccion</label>
    <referenceTo>Estado__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Opportunity/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <description>Safra o Campania agricola</description>
    <label>Safra</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>06/07</fullName>
            </value>
            <value>
                <fullName>07/08</fullName>
            </value>
            <value>
                <fullName>08/09</fullName>
            </value>
            <value>
                <fullName>09/10</fullName>
            </value>
            <value>
                <fullName>09/09</fullName>
            </value>
            <value>
                <fullName>10/10</fullName>
            </value>
            <value>
                <fullName>10/11</fullName>
            </value>
            <value>
                <fullName>11/11</fullName>
            </value>
            <value>
                <fullName>11/12</fullName>
            </value>
            <value>
                <fullName>12/12</fullName>
            </value>
            <value>
                <fullName>12/13</fullName>
            </value>
            <value>
                <fullName>13/14</fullName>
            </value>
            <value>
                <fullName>14/15</fullName>
            </value>
            <value>
                <fullName>15/16</fullName>
            </value>
            <value>
                <fullName>16/17</fullName>
            </value>
            <value>
                <fullName>17/18</fullName>
            </value>
            <value>
                <fullName>18/19</fullName>
            </value>
            <value>
                <fullName>19/20</fullName>
            </value>
            <value>
                <fullName>20/21</fullName>
            </value>
            <value>
                <fullName>21/22</fullName>
                <default>true</default>
                <label>21/22</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Opportunity/fields/TipoReg__c.field-meta.xml
<CustomField>
    <fullName>TipoReg__c</fullName>
    <formula>CASE($RecordType.Name, &quot;Comercial&quot;, &quot;Comercial&quot;, &quot;Produccion&quot;, &quot;Produccion&quot;,&quot;Pendiente&quot;,&quot;AU - Comercial&quot;,&quot;Autorizada&quot;,&quot;AU - SAP&quot;,&quot;Rebaja&quot;,&quot;Rebaja&quot;,$RecordType.Name)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>TipoReg</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/Opportunity/recordTypes/Autorizada.recordType-meta.xml
<RecordType>
    <fullName>Autorizada</fullName>
    <active>true</active>
    <businessProcess>Nota de Venta - Autorizada</businessProcess>
    <label>Autorizada</label>
</RecordType>

Salesforce/main/default/objects/Opportunity/recordTypes/Descarte.recordType-meta.xml
<RecordType>
    <fullName>Descarte</fullName>
    <active>true</active>
    <businessProcess>Circuito de Anexos</businessProcess>
    <label>Descarte</label>
</RecordType>

Salesforce/main/default/objects/OpportunityLineItem/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Categoria a ser licenciada</description>
    <inlineHelpText>Categoria a ser licenciada</inlineHelpText>
    <label>Categoria</label>
    <referenceTo>Categoria__c</referenceTo>
    <relationshipLabel>Producto de oportunidad</relationshipLabel>
    <relationshipName>Producto_de_oportunidad</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/OpportunityLineItem/fields/Categoria_a_Rebaixar__c.field-meta.xml
<CustomField>
    <fullName>Categoria_a_Rebaixar__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Categoria Plantada</label>
    <referenceTo>Categoria__c</referenceTo>
    <relationshipLabel>Producto de oportunidad (Categoria a Rebaixar)</relationshipLabel>
    <relationshipName>Producto_de_oportunidad1</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/OpportunityLineItem/fields/Estado_de_Produccion__c.field-meta.xml
<CustomField>
    <fullName>Estado_de_Produccion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Estado de Produccion</label>
    <referenceTo>Estado__c</referenceTo>
    <relationshipLabel>Producto de oportunidad</relationshipLabel>
    <relationshipName>Producto_de_oportunidad</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/OpportunityLineItem/fields/Lote_Rebajado__c.field-meta.xml
<CustomField>
    <fullName>Lote_Rebajado__c</fullName>
    <label>Lote</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/OpportunityLineItem/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <formula>TEXT(Opportunity.Safra__c)</formula>
    <label>Safra</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/OpportunityLineItem/fields/Sem_Rebajada__c.field-meta.xml
<CustomField>
    <fullName>Sem_Rebajada__c</fullName>
    <label>Sem. Rebaixada (Sacas)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/main/default/objects/OpportunityLineItem/fields/Semente_bruta__c.field-meta.xml
<CustomField>
    <fullName>Semente_bruta__c</fullName>
    <label>Sem. Bruta (Sacas)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/main/default/objects/OpportunityLineItem/fields/UNIDADE__c.field-meta.xml
<CustomField>
    <fullName>UNIDADE__c</fullName>
    <formula>PricebookEntry.Product2.UNIDADE__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unidade</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/OpportunityLineItem/fields/Unidade_descarte__c.field-meta.xml
<CustomField>
    <fullName>Unidade_descarte__c</fullName>
    <label>Unidade descarte</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/OpportunityLineItem/fields/Variedad__c.field-meta.xml
<CustomField>
    <fullName>Variedad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Variedades que pueden incluirse en el contrato de multiplicacion</description>
    <inlineHelpText>Variedades que pueden incluirse en el contrato de multiplicacion</inlineHelpText>
    <label>Variedad</label>
    <referenceTo>Variedad__c</referenceTo>
    <relationshipLabel>Producto de oportunidad</relationshipLabel>
    <relationshipName>Producto_de_oportunidad</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/OpportunityLineItem/fields/Variedade_Prod__c.field-meta.xml
<CustomField>
    <fullName>Variedade_Prod__c</fullName>
    <formula>PricebookEntry.Product2.Variedade__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Nome Comercial</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/Product2/fields/Categ__c.field-meta.xml
<CustomField>
    <fullName>Categ__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Categ</label>
    <referenceTo>Categoria__c</referenceTo>
    <relationshipLabel>Productos</relationshipLabel>
    <relationshipName>Productos</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Product2/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <label>Categoria</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BREEDER</fullName>
            </value>
            <value>
                <fullName>FUNDADORA</fullName>
            </value>
            <value>
                <fullName>Genetica</fullName>
            </value>
            <value>
                <fullName>Pre Basica</fullName>
            </value>
            <value>
                <fullName>BASICA</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>C1</fullName>
            </value>
            <value>
                <fullName>C2</fullName>
            </value>
            <value>
                <fullName>R</fullName>
            </value>
            <value>
                <fullName>S1</fullName>
            </value>
            <value>
                <fullName>S2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Product2/fields/UNIDADE__c.field-meta.xml
<CustomField>
    <fullName>UNIDADE__c</fullName>
    <label>UNIDADE</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/Product2/fields/Variedad__c.field-meta.xml
<CustomField>
    <fullName>Variedad__c</fullName>
    <label>Variedad</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Licenciada__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>BMX APOLO RR</fullName>
            </value>
            <value>
                <fullName>BMX IMPACTO RR</fullName>
            </value>
            <value>
                <fullName>BMX MAGNA RR</fullName>
            </value>
            <value>
                <fullName>BMX POTÊNCIA RR</fullName>
            </value>
            <value>
                <fullName>BMX TITAN RR</fullName>
            </value>
            <value>
                <fullName>BMX FORÇA RR</fullName>
            </value>
            <value>
                <fullName>BMX ENERGIA RR</fullName>
            </value>
            <value>
                <fullName>BMX ATIVA RR</fullName>
            </value>
            <value>
                <fullName>BMX TURBO RR</fullName>
            </value>
            <value>
                <fullName>BMX VELOZ RR</fullName>
            </value>
            <value>
                <fullName>BMX ALVO RR</fullName>
            </value>
            <value>
                <fullName>BMX TORNADO RR</fullName>
            </value>
            <value>
                <fullName>BMX CLASSE RR</fullName>
            </value>
            <value>
                <fullName>BMX DESAFIO RR</fullName>
            </value>
            <value>
                <fullName>BMX RAÇA RR</fullName>
            </value>
            <value>
                <fullName>BMX PROGRESSO RR</fullName>
            </value>
            <value>
                <fullName>BRASMAX ELITE IPRO</fullName>
            </value>
            <value>
                <fullName>BRASMAX FLECHA IPRO</fullName>
            </value>
            <value>
                <fullName>BRASMAX BONUS IPRO</fullName>
            </value>
            <value>
                <fullName>BRASMAX BRAVA</fullName>
            </value>
            <value>
                <fullName>BRASMAX CLASSE</fullName>
            </value>
            <value>
                <fullName>BRASMAX PRISMA</fullName>
            </value>
            <value>
                <fullName>BRASMAX OPUS IPRO</fullName>
            </value>
            <value>
                <fullName>BRASMAX LANÇA IPRO</fullName>
            </value>
            <value>
                <fullName>BRASMAX GARRA IPRO</fullName>
            </value>
            <value>
                <fullName>BRASMAX ÍCONE IPRO</fullName>
            </value>
            <value>
                <fullName>BRASMAX POWER IPRO</fullName>
            </value>
            <value>
                <fullName>68I69RSF IPRO</fullName>
            </value>
            <value>
                <fullName>75I76RSF IPRO</fullName>
            </value>
            <value>
                <fullName>81I84RSF IPRO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Product2/fields/Variedade__c.field-meta.xml
<CustomField>
    <fullName>Variedade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Variedade</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Variedad__c.Licenciada__c</field>
            <operation>equals</operation>
            <valueField>$Source.Licenciada__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Variedad__c</referenceTo>
    <relationshipLabel>Productos</relationshipLabel>
    <relationshipName>Productos</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Variedad__c/Variedad__c.object-meta.xml
<CustomObject>
    <description>Variedades, disponibles para incluir en los Contratos de Multiplicación</description>
    <label>Variedad</label>
    <nameField>
        <label>Nome Comercial</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Variedades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/Variedad__c/fields/Nombre_de_Registro__c.field-meta.xml
<CustomField>
    <fullName>Nombre_de_Registro__c</fullName>
    <externalId>true</externalId>
    <label>Nombre de Registro</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/globalValueSets/Marca.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BRMX</fullName>
    </customValue>
    <customValue>
        <fullName>DSEM</fullName>
    </customValue>
    <customValue>
        <fullName>NEOG</fullName>
    </customValue>
    <customValue>
        <fullName>DAGMA</fullName>
    </customValue>
    <customValue>
        <fullName>LICENÇAS</fullName>
    </customValue>
    <masterLabel>Marca</masterLabel>
</GlobalValueSet>

Salesforce/main/default/main/default/classes/ProductsDescarteAPI.cls
@RestResource(urlMapping='/ProductsDescarteAPI/*')
global with sharing class ProductsDescarteAPI {

    public static final String DESCARTERECTYPE = 'Descarte';
    public static final Map<String, Integer> MAPNAMEBYUNIDAD = new Map<String, Integer>{'Quilograma'    => 1,
                                                                                        'Saca 25Kg'     => 25,
                                                                                        'Saca 40Kg'     => 40,
                                                                                        'Tonelada'      => 1000};                                                                        

    /**
     *  SUBCLASS:       Response
     *  CONSTRUCTORS:   - 
     *  DESCRIPTION:    wrapper class for Products Descarte API response. Created for US #13041 
     *  AUTHOR:         irina.benitez@cloudgaia.com (29-sept-21)
     **/ 

    public class Response {
        public Boolean status;
        public String message;
        public List<aAppendix.myOppItem> productsDescarte;
        public Map<String, String> mapVariedadById;
        public Map<String, String> mapRegistroVariedadById;
        public Map<Id, String> mapCategoriaById;
        public Map<String, Set<String>> mapCategoriaByVariedad;
        public Map<Integer, String> mapUnidadByName = new Map<Integer, String>{ 1     => 'Quilograma',
                                                                                25    => 'Saca 25Kg',
                                                                                40    => 'Saca 40Kg',
                                                                                1000  => 'Tonelada'};
    }

     /**
     *  METHOD:         getProductsDescarte 
     *  PARAMETERS:     accountId: Id of an Account record 
     *                  safra  
     *                  marca 
     *  RETURN:         message: displays 'success' or error message  
     *                  status: boolean shows if operation was succesfull
     *                  productsDescarte: list of available products for Descarte
     *                  mapVariedadById: map of Id - Name pairs for Variedades
     *                  mapCategoriaByVariedad:  map of Variedad Id - List<Categoria Name> pairs
     *  DESCRIPTION:    Return list of products for Descarte along with variedad and categoria maps. Created for US #13041 
     *  AUTHOR:         german.diaz@cloudgaia.com (09-dec-21)
     **/ 
    @HttpGet
    global static void getProductsDescarte() {

        String accountId = RestContext.request.params.get('accountId');
        String safra = RestContext.request.params.get('safra');
        String marca = RestContext.request.params.get('marca');
        String cultura = RestContext.request.params.get('cultura');

        RestResponse response = RestContext.response;
        response.statusCode = 404;

        Response result = new Response();
        result.status = false;
        result.message = Label.ProductsDescarteAPI_Default_Error_Message;

        FactoryManejador factory = new FactoryManejador();
        ManejadorDescarte manejador;

        
        try {

            List<OpportunityLineItem> oppItemsForDescarteCalculation = getProductsForNewDescarte(accountId, marca, safra, cultura);
            if(oppItemsForDescarteCalculation != null && !oppItemsForDescarteCalculation.isEmpty()) {
                List<OpportunityLineItem> anexo3items = new List<OpportunityLineItem>();
                List<OpportunityLineItem> descarteitems = new List<OpportunityLineItem>();
        
                for(OpportunityLineItem product : oppItemsForDescarteCalculation) {
                    if(product.Opportunity.TipoReg__c == 'Anexo III') {
                        anexo3items.add(product);
                    } else if (product.Opportunity.TipoReg__c == 'Descarte') {
                        descarteitems.add(product);
                    }
                }
                Map<String, Map<String, Double>> sacasDisponibles = getSacasDisponibles(anexo3items, descarteItems);
    
                result.productsDescarte = oppLineItemJSONConverter(anexo3items, sacasDisponibles);
                completeMapValues(result, anexo3items);
                result.mapCategoriaById = getCategoriaByIdMap(result);
            } else {
                result.message = Label.Anexo_IV_Val_Existe_Anexo_III;
            }


        } catch (Exception exc) {
            response.statusCode = 400;
            result.message = exc.getMessage();
        }
                
        if(result.productsDescarte != null && !result.productsDescarte.isEmpty()) {
            result.status = true;
            result.message = Label.ProductsDescarteAPI_Success_Message;
            response.statusCode = 200;
        }

        System.debug('result: ' + result);
        response.responseBody = Blob.valueOf(JSON.serialize(result));
        response.headers.put('Content-Type', 'application/json');
        response.headers.put('Content-Length', RestContext.response.responseBody.size()+'');
    }


    /**
     *  METHOD:         oppLineItemJSONConverter 
     *  PARAMETERS:     oppLineItems: List of OpportunityLineItems in sObject format 
     *  RETURN:         List<aAppendix.myOppItem>: list of records in JSON format to return
     *  DESCRIPTION:    Helper method converts opportunityLineItem sObject in aAppendix.myOppItem JSON wrapper. Created for US #13041 
     *  AUTHOR:         irina.benitez@cloudgaia.com (29-sept-21)
     * TO DELETE AFTER CHANGES 
     **/ 
    public static List<aAppendix.myOppItem> oppLineItemJSONConverter(List<OpportunityLineItem> oppLineItems, Map<String, Map<String, Double>> sacasDisponibles) {

        List<aAppendix.myOppItem> result = new List<aAppendix.myOppItem>();

        if(oppLineItems != null && oppLineItems.size() > 0) {

            for(OpportunityLineItem oppLineItem : oppLineItems){

                String variedad = oppLineItem.PricebookEntry.Product2.Variedade__c;
                String categoria = oppLineItem.Categoria__c;
                Double semDisponibles = sacasDisponibles.get(variedad).get(categoria);

                aAppendix.myOppItem customOli = new aAppendix.myOppItem();
                customOli.variedad = oppLineItem.PricebookEntry.Product2.Variedade__c;
                customOli.variedad_nombre = oppLineItem.Variedade_Prod__c;
                customOli.variedad_registro = oppLineItem.PricebookEntry.Product2.Variedade__r.Nombre_de_Registro__c;
                customOli.categoria = oppLineItem.Categoria__c;
                customOli.categoria_nombre = oppLineItem.Categoria__r.Name;
                customOli.amount = oppLineItem.Quantity;
                customOli.unidadDescarte = MAPNAMEBYUNIDAD.get(oppLineItem.Unidade_descarte__c);
                customOli.unidade = oppLineItem.Unidade_descarte__c;
                customOli.unidade_nombre = oppLineItem.Unidade_descarte__c;
                customOli.lote_rebajado = oppLineItem.Lote_Rebajado__c;
                customOli.categoria_a_rebajar_id = oppLineItem.Categoria_a_Rebaixar__c;
                customOli.sem_bruta = String.valueOf(oppLineItem.Semente_bruta__c);
                customOli.sem_bruta_A2 = String.valueOf(oppLineItem.Semente_bruta__c);
                customOli.sem_rebajada = String.valueOf(oppLineItem.Sem_Rebajada__c);
                CustomOli.sem_disponibles = semDisponibles;
                result.add(customOli);
            }
        }

        return result;
    }

    /**
     *  METHOD:         completeMapValues 
     *  PARAMETERS:     Response
     *  RETURN:         -
     *  DESCRIPTION:    Loops productsDescarte and completes response maps for Variedad and Categoria 
     *  AUTHOR:         irina.benitez@cloudgaia.com (12-jan-22)
     **/     
    public static void completeMapValues(Response resp, List<OpportunityLineItem> productList) {

        resp.mapVariedadById = new Map<String, String>();
        resp.mapRegistroVariedadById = new Map<String, String>();
        resp.mapCategoriaByVariedad = new Map<String, Set<String>>();
        Map<Id, String> tmpVarietyNameById = new Map<Id, String>();

        if(!productList.isEmpty()) {
            for(OpportunityLineItem oppItem : productList){
                String tmpVarietyId = oppItem.PricebookEntry.Product2.Variedade__c;
                String tmpVarietyName = oppItem.PricebookEntry.Product2.Variedade__r.Name;
                String tmpVarietyRegisterName = oppItem.PricebookEntry.Product2.Variedade__r.Nombre_de_Registro__c;
                String tmpCategoryName = oppItem.Categoria__r.Name;

                if (!tmpvarietyNameById.containsKey(tmpVarietyId)) { 

                    Set<String> categoriesForVariety  = new Set<String>();

                    categoriesForVariety.add(tmpCategoryName);
                    resp.mapCategoriaByVariedad.put(tmpVarietyName, categoriesForVariety);
                    tmpvarietyNameById.put(tmpVarietyId, tmpVarietyName);
                    resp.mapRegistroVariedadById.put(tmpVarietyId, tmpVarietyRegisterName);                 
                    resp.mapVariedadById.put(tmpVarietyId, tmpVarietyName);
                } else {
                    Set<String> categoriesForVariety = resp.mapCategoriaByVariedad.get(tmpVarietyName);
                    if (!categoriesForVariety.contains(tmpCategoryName)) {
                        categoriesForVariety.add(tmpCategoryName);
                    }
                }  
            }
        }

    }


    /**
     *  METHOD:         getCategoriaByIdMap 
     *  PARAMETERS:     Response
     *  RETURN:         Map<Id, String>: map of Categoria names by Id
     *  DESCRIPTION:    Helper method converts opportunityLineItem sObject in aAppendix.myOppItem JSON wrapper. Created for US #13041 
     *  AUTHOR:         irina.benitez@cloudgaia.com (29-sept-21)
     * TO DELETE AFTER CHANGES
     **/     
    public static Map<Id, String> getCategoriaByIdMap(Response resp) {

        Map<Id, String> result = new Map<Id, String>();
        
        for( String variedad : resp.mapVariedadById.keySet() ) {
            Set<String> categoriesForSelectedVariedad = resp.mapCategoriaByVariedad.get(resp.mapVariedadById.get(variedad));          
            List<Categoria__c> categoriesInDb = aAppManager.getCategorias(); 
            if (!categoriesInDb.isEmpty()) {
                for (Categoria__c tmpCategory : categoriesInDb) {
                    if (categoriesForSelectedVariedad.contains(tmpCategory.Name)) {
                        result.put(tmpCategory.Id, tmpCategory.Name);
                    }
                }
            }
        }
        
        return result;
    }

    /**
     *  METHOD:         getProductsForNewDescarte 
     *  PARAMETERS:     accountId
     *                  marca
     *                  safra
     *                  cultura
     *  RETURN:         List<OpportunityLineItem>: list of available products for a new descarte
     *  DESCRIPTION:    Queries products for approved Anexo III & Descarte opps for same accountId, marca, safra and cultura. Created for US #19174 
     *  AUTHOR:         irina.benitez@cloudgaia.com (12-jan-22)
     **/     
    public static List<OpportunityLineItem> getProductsForNewDescarte(String accountId, String marca, String safra, String cultura) {

        String queryPlus = 'PricebookEntry.Product2.Variedade__c, PricebookEntry.Product2.Variedade__r.Name, ' +
            'PricebookEntry.Product2.Variedade__r.Nombre_de_Registro__c, PricebookEntry.Product2.UNIDADE__c, ' +
            'PriceBookEntry.Product2.Categ__c, Categoria__r.Name, Opportunity.TipoReg__c, Categoria_a_Rebaixar__r.Name, ' +
            'PriceBookEntry.PriceBook2Id, PricebookEntry.Product2.Variedad__c, Variedad__r.Name, Estado_de_Produccion__r.Name';

        List<OpportunityLineItem> oppItems = aSiteUtils.queryResults6(  OpportunityLineItem.SObjectType, queryPlus,
                                                                        'Opportunity.AccountId = :v1', accountId, 
                                                                        'Opportunity.TipoReg__c in :v2', new String[] {'Anexo III', 'Descarte'},
                                                                        'Opportunity.Safra__c = :v3', safra,
                                                                        'Opportunity.Marca__c = :v4', marca,
                                                                        'Opportunity.Cultura__c = :v5', cultura,
                                                                        'Opportunity.StageName in :v6', new String[] {'Aprobada', 'AU - Autorizada'}
                                                                    );
        return oppItems;   
    }
    
    
    /**
     *  METHOD:         getMapA3SacasDisponibles 
     *  PARAMETERS:     List<OpportunityLineItem>: list of anexo III products to process
     *  RETURN:         Map< String, Map <String, Double>>: map with quantities by Variedad and Categoria
     *  DESCRIPTION:    Loop products for approved Anexo III  to determine Sacas Disponibles A3. Created for US #19174 
     *  AUTHOR:         irina.benitez@cloudgaia.com (12-jan-22)
     **/    
    public static Map<String, Map<String,Double>> getSacasDisponibles(List<OpportunityLineItem> anexo3items, List<OpportunityLineItem> descarteItems) {
        Map<String, Map<String,Double>> sacasDisponibles = getMapA3SacasDisponibles(anexo3items);
        sacasDisponibles = processDescarteProducts(sacasDisponibles, descarteItems);
        return sacasDisponibles;
    }

    /**
     *  METHOD:         getMapA3SacasDisponibles 
     *  PARAMETERS:     List<OpportunityLineItem>: list of anexo III products to process
     *  RETURN:         Map< String, Map <String, Double>>: map with quantities by Variedad and Categoria
     *  DESCRIPTION:    Loop products for approved Anexo III  to determine Sacas Disponibles A3. Created for US #19174 
     *  AUTHOR:         irina.benitez@cloudgaia.com (12-jan-22)
     **/     
    public static Map<String, Map<String,Double>> getMapA3SacasDisponibles(List<OpportunityLineItem> anexo3items) {

        Map<String, Map<String,Double>> sacasDisponiblesA3 = new Map<String, Map<String, Double>>();

        for(OpportunityLineItem oppItem : anexo3items) {
            String variedad = oppItem.PricebookEntry.Product2.Variedade__c;
            String categoria = oppItem.Categoria__c;
            Double disponibleSacas = oppItem.Semente_aprovada__c;
            if( !sacasDisponiblesA3.containsKey(variedad) ) {
                Map<String, Double> sacasByCategoria = new Map<String, Double>();
                sacasByCategoria.put(categoria, disponibleSacas);
                sacasDisponiblesA3.put(variedad, sacasByCategoria);
            } else {
                if(sacasDisponiblesA3.get(variedad).containsKey(categoria)) {
                    Double totalDisponible = sacasDisponiblesA3.get(variedad).get(categoria) + disponibleSacas;
                    sacasDisponiblesA3.get(variedad).put(categoria, totalDisponible);
                } else {
                    sacasDisponiblesA3.get(variedad).put(categoria, disponibleSacas);
                }
            }
        }

        return sacasDisponiblesA3;
    }

    /**
     *  METHOD:         processDescarteProducts 
     *  PARAMETERS:     Map<String, Map <String, String>>: map with sacas disponibles for A3 by Variedad and Categoria
     *                  List<OpportunityLineItem>: list of descarte products to process
     *  RETURN:         Map<String, Map <String, String>>: map with sacas disponibles by Variedad and Categoria
     *  DESCRIPTION:    Loop products for Descarte products to determine Sacas Disponibles from A3 map. Created for US #19174 
     *  AUTHOR:         irina.benitez@cloudgaia.com (12-jan-22)
     **/     
    public static Map<String, Map<String,Double>> processDescarteProducts(Map<String, Map<String,Double>> sacasDisponiblesA3, List<OpportunityLineItem> descarteItems) {

        Map<String, Map<String,Double>> sacasDisponibles = sacasDisponiblesA3;

        for(OpportunityLineItem oppItem : descarteItems) {
            String variedad = oppItem.PricebookEntry.Product2.Variedade__c;
            String categoria = oppItem.Categoria__c;

            Double descarte = (oppItem.Quantity * MAPNAMEBYUNIDAD.get(oppItem.Unidade_descarte__c)) / 40;

            if( sacasDisponibles.containsKey(variedad) && sacasDisponibles.get(variedad).containsKey(categoria) ) {
                Double cantidadRestante = sacasDisponibles.get(variedad).get(categoria) - descarte;
                sacasDisponibles.get(variedad).put(categoria, cantidadRestante);
            }
        }

        return sacasDisponibles;
    }

}