Salesforce/main/default/objects/Account/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Marca</valueSetName>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Account/fields/Multiplicador__c.field-meta.xml
<CustomField>
    <fullName>Multiplicador__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Multiplicador</label>
    <type>Checkbox</type>
</CustomField>

Salesforce/main/default/main/default/objects/Account/fields/Plano_de_Auditoria__c.field-meta.xml
<CustomField>
    <fullName>Plano_de_Auditoria__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plano de Auditoria</label>
    <referenceTo>Plano_de_Auditoria__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Plano_de_Auditoria__c/Plano_de_Auditoria__c.object-meta.xml
<CustomObject>
    <label>Plano de Auditoria</label>
    <nameField>
        <displayFormat>PA-{0000}</displayFormat>
        <label>Nombre de Plano de Auditoria</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Planos de Auditoria</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/Plano_de_Auditoria__c/fields/Cuenta_Principal__c.field-meta.xml
<CustomField>
    <fullName>Cuenta_Principal__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Cuenta Principal</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Plano de Auditoria</relationshipLabel>
    <relationshipName>Plano_de_Auditoria</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Plano_de_Auditoria__c/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <label>Safra</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Safra</valueSetName>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Resumo_da_conta__c/Resumo_da_conta__c.object-meta.xml
<CustomObject>
    <label>CRM</label>
    <nameField>
        <label>Nombre de CRM</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CRM</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/objects/Resumo_da_conta__c/fields/Clausula_5_1__c.field-meta.xml
<CustomField>
    <fullName>Clausula_5_1__c</fullName>
    <description>Conforme Cláusula 5.1, parágrafo &quot;i&quot; e &quot;j&quot; do Contrato de Licença de Uso de Cultivar ao efetuar o descarte, obrigatoriamente deve especificar na Nota Fiscal de Venda a indústria os seguintes dados: Nome da Cultivar, Categoria, Lotes e Quantidades. Realizam a operação ?</description>
    <inlineHelpText>Conforme Cláusula 5.1, parágrafo &quot;i&quot; e &quot;j&quot; do Contrato de Licença de Uso de Cultivar ao efetuar o descarte, obrigatoriamente deve especificar na Nota Fiscal de Venda a indústria os seguintes dados: Nome da Cultivar, Categoria, Lotes e Quantidades. Realiza</inlineHelpText>
    <label>Clausula 5.1</label>
    <type>TextArea</type>
</CustomField>

Salesforce/main/default/main/default/objects/Resumo_da_conta__c/fields/Compra_Vende_Semillas_de_Terceros__c.field-meta.xml
<CustomField>
    <fullName>Compra_Vende_Semillas_de_Terceros__c</fullName>
    <description>Realizam Compra e Venda de Sementes de Terceiros ?</description>
    <inlineHelpText>Realizam Compra e Venda de Sementes de Terceiros ?</inlineHelpText>
    <label>Compra/Vende Semillas de Terceros</label>
    <type>TextArea</type>
</CustomField>

Salesforce/main/default/main/default/objects/Resumo_da_conta__c/fields/Emiten_Facturas_de_Venta_Transferencia__c.field-meta.xml
<CustomField>
    <fullName>Emiten_Facturas_de_Venta_Transferencia__c</fullName>
    <description>Para realizarem a inscrição dos Campos de Produção de Sementes, emitem Notas Fiscais de Venda / ou Tranferência para Consumo para os Volumes que são destinados a Plantio (Uso Próprio), e que são informados na Relação de Campos para Produção de Sementes ?</description>
    <inlineHelpText>Para realizarem a inscrição dos Campos de Produção de Sementes, emitem Notas Fiscais de Venda / ou Tranferência para Consumo para os Volumes que são destinados a Plantio (Uso Próprio), e que são informados na Relação de Campos para Produção de Sementes ?</inlineHelpText>
    <label>Emiten Facturas de Venta / Transferencia</label>
    <type>TextArea</type>
</CustomField>

Salesforce/main/default/objects/Resumo_da_conta__c/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Marca</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Marca</valueSetName>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Resumo_da_conta__c/fields/Mencion_factura_de_venta__c.field-meta.xml
<CustomField>
    <fullName>Mencion_factura_de_venta__c</fullName>
    <description>O Saldo de Descarte de Sementes Aprovadas e Reprovadas que NÃO foram Comercializadas ou destinadas a Plantio (Uso Próprio) é mencionado na Nota Fiscal de Venda ( Envio à Indústria ) ?</description>
    <inlineHelpText>O Saldo de Descarte de Sementes Aprovadas e Reprovadas que NÃO foram Comercializadas ou destinadas a Plantio (Uso Próprio) é mencionado na Nota Fiscal de Venda ( Envio à Indústria ) ?</inlineHelpText>
    <label>Mencion factura de venta</label>
    <type>TextArea</type>
</CustomField>

Salesforce/main/default/objects/Resumo_da_conta__c/fields/Miembros_o_area_para_Multiplicar__c.field-meta.xml
<CustomField>
    <fullName>Miembros_o_area_para_Multiplicar__c</fullName>
    <description>Possuem Cooperados ou Somente áreas próprias para multiplicação ?</description>
    <inlineHelpText>Possuem Cooperados ou Somente áreas próprias para multiplicação ?</inlineHelpText>
    <label>Miembros o area para Multiplicar</label>
    <type>TextArea</type>
</CustomField>

Salesforce/main/default/main/default/objects/Resumo_da_conta__c/fields/Multiplicador__c.field-meta.xml
<CustomField>
    <fullName>Multiplicador__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Multiplicador</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Resumo da conta</relationshipLabel>
    <relationshipName>Resumo_da_conta</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/Resumo_da_conta__c/fields/Otros_criadores__c.field-meta.xml
<CustomField>
    <fullName>Otros_criadores__c</fullName>
    <description>Trabalha com outros obtentores ? Quais ?</description>
    <inlineHelpText>Trabalha com outros obtentores ? Quais ?</inlineHelpText>
    <label>Otros criadores</label>
    <type>TextArea</type>
</CustomField>

Salesforce/main/default/main/default/objects/Resumo_da_conta__c/fields/Participacion_en_la_cosecha__c.field-meta.xml
<CustomField>
    <fullName>Participacion_en_la_cosecha__c</fullName>
    <description>Qual foi a Participação (%) da BRASMAX /e ou DONMARIO na safra  ( _______________ ):</description>
    <inlineHelpText>Qual foi a Participação (%) da BRASMAX /e ou DONMARIO na safra  ( _______________ ):</inlineHelpText>
    <label>Participacion en la cosecha</label>
    <type>TextArea</type>
</CustomField>

Salesforce/main/default/main/default/objects/Resumo_da_conta__c/fields/Quebra__c.field-meta.xml
<CustomField>
    <fullName>Quebra__c</fullName>
    <description>Qual é a % de Quebra Técnica MÉDIA (da empresa) referente ao volume BRUTO de semente de soja que entra na UBS para o volume que é Beneficiado ?</description>
    <inlineHelpText>Qual é a % de Quebra Técnica MÉDIA (da empresa) referente ao volume BRUTO de semente de soja que entra na UBS para o volume que é Beneficiado ?</inlineHelpText>
    <label>Quebra</label>
    <type>TextArea</type>
</CustomField>

Salesforce/main/default/main/default/objects/Resumo_da_conta__c/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <label>Safra</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Safra</valueSetName>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Resumo_da_conta__c/fields/Separa_los_volumenes_2__c.field-meta.xml
<CustomField>
    <fullName>Separa_los_volumenes_2__c</fullName>
    <description>O Sistema da empresa consegue separar os volumes de Produção Própria dos volumes adquiridos e vendidos de Terceiros ?</description>
    <inlineHelpText>O Sistema da empresa consegue separar os volumes de Produção Própria dos volumes adquiridos e vendidos de Terceiros ?</inlineHelpText>
    <label>Separa los volumenes 2</label>
    <type>TextArea</type>
</CustomField>

Salesforce/main/default/main/default/objects/Resumo_da_conta__c/fields/Separa_los_volumenes__c.field-meta.xml
<CustomField>
    <fullName>Separa_los_volumenes__c</fullName>
    <description>O Sistema da empresa separa os volumes destinados a Uso Próprio dos volumes que são comercializados ao produtor ?</description>
    <inlineHelpText>O Sistema da empresa separa os volumes destinados a Uso Próprio dos volumes que são comercializados ao produtor ?</inlineHelpText>
    <label>Separa los volumenes</label>
    <type>TextArea</type>
</CustomField>

Salesforce/main/default/main/default/objects/Resumo_da_conta__c/fields/Sistema_Implantado__c.field-meta.xml
<CustomField>
    <fullName>Sistema_Implantado__c</fullName>
    <description>Possuem Sistema implantado na empresa ? Qual ?</description>
    <inlineHelpText>Possuem Sistema implantado na empresa ? Qual ?</inlineHelpText>
    <label>Sistema Implantado</label>
    <type>TextArea</type>
</CustomField>

Salesforce/main/default/objects/Resumo_da_conta__c/fields/Ventas_Totales_INTACTA__c.field-meta.xml
<CustomField>
    <fullName>Ventas_Totales_INTACTA__c</fullName>
    <description>Porcentagem (%) das Vendas Totais RR  ( _______ ) e INTACTA ( _______ ) na safra  ( _______________ ).</description>
    <inlineHelpText>Porcentagem (%) das Vendas Totais RR  ( _______ ) e INTACTA ( _______ ) na safra  ( _______________ ).</inlineHelpText>
    <label>Ventas Totales INTACTA</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

Salesforce/main/default/main/default/objects/Resumo_da_conta__c/fields/Ventas_Totales_RR__c.field-meta.xml
<CustomField>
    <fullName>Ventas_Totales_RR__c</fullName>
    <description>Porcentagem (%) das Vendas Totais RR  ( _______ ) e INTACTA ( _______ ) na safra  ( _______________ ).</description>
    <inlineHelpText>Porcentagem (%) das Vendas Totais RR  ( _______ ) e INTACTA ( _______ ) na safra  ( _______________ ).</inlineHelpText>
    <label>Ventas Totales RR</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

Salesforce/main/default/globalValueSets/Marca.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BRMX</fullName>
    </customValue>
    <customValue>
        <fullName>DSEM</fullName>
    </customValue>
    <customValue>
        <fullName>NEOG</fullName>
    </customValue>
    <customValue>
        <fullName>DAGMA</fullName>
    </customValue>
    <customValue>
        <fullName>LICENÇAS</fullName>
    </customValue>
    <masterLabel>Marca</masterLabel>
</GlobalValueSet>

Salesforce/main/default/globalValueSets/Safra.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>14/15</fullName>
    </customValue>
    <customValue>
        <fullName>15/16</fullName>
    </customValue>
    <customValue>
        <fullName>16/17</fullName>
    </customValue>
    <customValue>
        <fullName>17/18</fullName>
    </customValue>
    <customValue>
        <fullName>18/19</fullName>
    </customValue>
    <customValue>
        <fullName>19/20</fullName>
    </customValue>
    <customValue>
        <fullName>20/21</fullName>
    </customValue>
    <customValue>
        <fullName>21/22</fullName>
    </customValue>
    <customValue>
        <fullName>22/23</fullName>
    </customValue>
    <customValue>
        <fullName>23/24</fullName>
    </customValue>
    <customValue>
        <fullName>08/09</fullName>
        <isActive>false</isActive>
        <label>08/09</label>
    </customValue>
    <customValue>
        <fullName>07/08</fullName>
        <isActive>false</isActive>
        <label>07/08</label>
    </customValue>
    <customValue>
        <fullName>10/11</fullName>
        <isActive>false</isActive>
        <label>10/11</label>
    </customValue>
    <customValue>
        <fullName>11/12</fullName>
        <isActive>false</isActive>
        <label>11/12</label>
    </customValue>
    <customValue>
        <fullName>12/13</fullName>
        <isActive>false</isActive>
        <label>12/13</label>
    </customValue>
    <customValue>
        <fullName>13/14</fullName>
        <isActive>false</isActive>
        <label>13/14</label>
    </customValue>
    <customValue>
        <fullName>09/10</fullName>
        <isActive>false</isActive>
        <label>09/10</label>
    </customValue>
    <masterLabel>Safra</masterLabel>
</GlobalValueSet>

Salesforce/main/default/main/default/classes/ObservacionesDeAuditoriaController.cls
public with sharing class ObservacionesDeAuditoriaController {

    public Plano_de_Auditoria__c planoDeAuditoria                   {get; set;}
    public String safra												{get; set;}
    public Resumo_da_Conta__c crm                                   {get; set;}

    public ObservacionesDeAuditoriaController(ApexPages.StandardController controller) {
        Id planoDeAuditoriaId = controller.getRecord().Id;
        safra = apexpages.currentPage().getParameters().get('Safra');

        planoDeAuditoria = [
            SELECT Id, Name, Safra__c, Cuenta_Principal__c, Cuenta_Principal__r.Marca__c FROM Plano_de_Auditoria__c WHERE Id = :planoDeAuditoriaId
        ];

        crm= [
            SELECT Id, Name,Multiplicador__c, Multiplicador__r.Name, Sistema_Implantado__c, Miembros_o_area_para_Multiplicar__c,
                Emiten_Facturas_de_Venta_Transferencia__c, Separa_los_volumenes__c, Compra_Vende_Semillas_de_Terceros__c, Separa_los_volumenes_2__c, 
                Mencion_factura_de_venta__c, Clausula_5_1__c, Quebra__c, Otros_criadores__c, Participacion_en_la_cosecha__c, Ventas_Totales_RR__c,
                Ventas_Totales_INTACTA__c, Safra__c 
            FROM Resumo_da_Conta__c 
            WHERE Multiplicador__c = :planoDeAuditoria.Cuenta_Principal__c AND Safra__c = :safra LIMIT 1
        ];
    }

    public PageReference save() {
        update crm;
        PageReference pr = new PageReference('/apex/AuditarVisita');
        Id PlanoId = apexpages.currentPage().getParameters().get('Id');
        pr.getParameters().put('Id',PlanoId);
        pr.setRedirect(true);
        return pr;
    }

    public PageReference goToAuditar() {
        PageReference pr = new PageReference('/apex/AuditarVisita');
        Id PlanoId = planoDeAuditoria.Id;
        pr.getParameters().put('Id',PlanoId);
        pr.setRedirect(true); // If you want a redirect. Do not set anything if you want a forward.
        return pr;
    }

    public PageReference goToCalendario() {
        PageReference pr = new PageReference('/apex/FullCalendarDemo');
        pr.setRedirect(true);
        return pr;
    }
}