Salesforce/main/default/objects/Account/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Marca</valueSetName>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Account/fields/Responsavel__c.field-meta.xml
<CustomField>
    <fullName>Responsavel__c</fullName>
    <description>Qual dos funcionários da Brasmax que estará responsável pela conta</description>
    <inlineHelpText>Qual dos funcionários da Brasmax que estará responsável pela conta</inlineHelpText>
    <label>Responsável BRMX</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>061 - Fernando Frehner</fullName>
            </value>
            <value>
                <fullName>066 - Marcelo Steffen</fullName>
            </value>
            <value>
                <fullName>067 - Sergio Bertagnolli</fullName>
            </value>
            <value>
                <fullName>076 - Tiago Goulart</fullName>
            </value>
            <value>
                <fullName>083 - Jorge Cristiano Rosa</fullName>
            </value>
            <value>
                <fullName>010 - Brasmax</fullName>
            </value>
            <value>
                <fullName>101 - Fausto Tadeu Fanchin</fullName>
            </value>
            <value>
                <fullName>104 - Otavio Gorni</fullName>
            </value>
            <value>
                <fullName>150 - João Serrano</fullName>
            </value>
            <value>
                <fullName>012 - Anderson Weissheimer</fullName>
            </value>
            <value>
                <fullName>197 - Wagner Rank</fullName>
            </value>
            <value>
                <fullName>198 - Bernardo Zanardo</fullName>
            </value>
            <value>
                <fullName>199 - Lucas Costa</fullName>
            </value>
            <value>
                <fullName>231 - Willian Von Scharten</fullName>
            </value>
            <value>
                <fullName>234 - Julio Cesar Poletto</fullName>
            </value>
            <value>
                <fullName>017 - Luis Fernando Cecatto</fullName>
            </value>
            <value>
                <fullName>018 - Flávio Marçal dos Santos</fullName>
            </value>
            <value>
                <fullName>312 - Lucas Hilario Fantineli</fullName>
            </value>
            <value>
                <fullName>019 - Felipe Oliveira Costa</fullName>
            </value>
            <value>
                <fullName>379 - Diego F. Gonçalves</fullName>
            </value>
            <value>
                <fullName>031 - Guilherme Sousa</fullName>
            </value>
            <value>
                <fullName>023 - Gabriel V. Finatto</fullName>
            </value>
            <value>
                <fullName>464 - Ana Laura Fernandes</fullName>
            </value>
            <value>
                <fullName>467 - Natalie de Mattos</fullName>
            </value>
            <value>
                <fullName>474 - Guilherme Menezes Salau</fullName>
            </value>
            <value>
                <fullName>403 - Felipe Bianchessi</fullName>
            </value>
            <value>
                <fullName>380 - Lucas de Souza Furlan</fullName>
            </value>
            <value>
                <fullName>037 - Felipe Dias Louzada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Opportunity/fields/Estado_de_produccion__c.field-meta.xml
<CustomField>
    <fullName>Estado_de_produccion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Estado de produccion, para incluir en el contrato de multiplicacion</description>
    <inlineHelpText>Estado de produccion, para incluir en el contrato de multiplicacion</inlineHelpText>
    <label>Estado de produccion</label>
    <referenceTo>Estado__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Opportunity/fields/Estado_Facturacion__c.field-meta.xml
<CustomField>
    <fullName>Estado_Facturacion__c</fullName>
    <label>Estado Facturacion</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>PE Contabilizar</fullName>
            </value>
            <value>
                <fullName>Contabilizada</fullName>
            </value>
            <value>
                <fullName>Impresa</fullName>
            </value>
            <value>
                <fullName>Anulada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Opportunity/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <description>Identifica la marca para las Oportunidades del Circuito de Anexos. Se selecciona la lista de precios en función de este campo</description>
    <inlineHelpText>Identificar a marca de Oportunidades Circuito Anexos. Você seleciona a lista de preços com base neste campo</inlineHelpText>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BRMX</fullName>
            </value>
            <value>
                <fullName>DSEM</fullName>
            </value>
            <value>
                <fullName>NEOG</fullName>
            </value>
            <value>
                <fullName>DAGMA</fullName>
            </value>
            <value>
                <fullName>LICENÇAS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Opportunity/fields/Mes__c.field-meta.xml
<CustomField>
    <fullName>Mes__c</fullName>
    <description>Nombre del mes para identificar la oportunidad de control de stock.</description>
    <label>Mês</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Janeiro</fullName>
            </value>
            <value>
                <fullName>Fevereiro</fullName>
            </value>
            <value>
                <fullName>Março</fullName>
            </value>
            <value>
                <fullName>Abril</fullName>
            </value>
            <value>
                <fullName>Maio</fullName>
            </value>
            <value>
                <fullName>Junho</fullName>
            </value>
            <value>
                <fullName>Julho</fullName>
            </value>
            <value>
                <fullName>Agosto</fullName>
            </value>
            <value>
                <fullName>Setembro</fullName>
            </value>
            <value>
                <fullName>Outubro</fullName>
            </value>
            <value>
                <fullName>Novembro</fullName>
            </value>
            <value>
                <fullName>Dezembro</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Opportunity/fields/Nro_Pedido_SAP__c.field-meta.xml
<CustomField>
    <fullName>Nro_Pedido_SAP__c</fullName>
    <externalId>true</externalId>
    <label>Nro Pedido SAP</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/Opportunity/fields/Numero_del__c.field-meta.xml
<CustomField>
    <fullName>Numero_del__c</fullName>
    <label>Numero</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/Opportunity/fields/Regiao__c.field-meta.xml
<CustomField>
    <fullName>Regiao__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Região</label>
    <referenceTo>Regiao__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/Opportunity/fields/Relatorio_Relacionado__c.field-meta.xml
<CustomField>
    <fullName>Relatorio_Relacionado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Relatorio Relacionado</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Opportunity/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <description>Safra o Campania agricola</description>
    <label>Safra</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>06/07</fullName>
            </value>
            <value>
                <fullName>07/08</fullName>
            </value>
            <value>
                <fullName>08/09</fullName>
            </value>
            <value>
                <fullName>09/10</fullName>
            </value>
            <value>
                <fullName>09/09</fullName>
            </value>
            <value>
                <fullName>10/10</fullName>
            </value>
            <value>
                <fullName>10/11</fullName>
            </value>
            <value>
                <fullName>11/11</fullName>
            </value>
            <value>
                <fullName>11/12</fullName>
            </value>
            <value>
                <fullName>12/12</fullName>
            </value>
            <value>
                <fullName>12/13</fullName>
            </value>
            <value>
                <fullName>13/14</fullName>
            </value>
            <value>
                <fullName>14/15</fullName>
            </value>
            <value>
                <fullName>15/16</fullName>
            </value>
            <value>
                <fullName>16/17</fullName>
            </value>
            <value>
                <fullName>17/18</fullName>
            </value>
            <value>
                <fullName>18/19</fullName>
            </value>
            <value>
                <fullName>19/20</fullName>
            </value>
            <value>
                <fullName>20/21</fullName>
            </value>
            <value>
                <fullName>21/22</fullName>
                <default>true</default>
                <label>21/22</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Opportunity/fields/VB_Cidade__c.field-meta.xml
<CustomField>
    <fullName>VB_Cidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cidade</label>
    <referenceTo>Cidade__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/Opportunity/fields/VB_Franqueado__c.field-meta.xml
<CustomField>
    <fullName>VB_Franqueado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Franqueado en la operacion donde el Franqueado le vende semilla basica al Multiplicador</description>
    <inlineHelpText>Franqueado en la operacion donde el Franqueado le vende semilla basica al Multiplicador</inlineHelpText>
    <label>Franqueado</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Oportunidades de Exportação</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Opportunity/recordTypes/Anexo_III.recordType-meta.xml
<RecordType>
    <fullName>Anexo_III</fullName>
    <active>true</active>
    <businessProcess>Circuito de Anexos</businessProcess>
    <label>Anexo III</label>
</RecordType>

Salesforce/main/default/objects/Opportunity/recordTypes/AnexoI.recordType-meta.xml
<RecordType>
    <fullName>AnexoI</fullName>
    <active>true</active>
    <businessProcess>Docusign - Anexos</businessProcess>
    <description>Anexo I -Autorização para multiplicação</description>
    <label>Anexo I</label>
</RecordType>

Salesforce/main/default/main/default/objects/Opportunity/recordTypes/AnexoII.recordType-meta.xml
<RecordType>
    <fullName>AnexoII</fullName>
    <active>true</active>
    <businessProcess>Circuito de Anexos</businessProcess>
    <description>Anexo II - Relatório de produção de sementes</description>
    <label>Anexo II</label>
</RecordType>

Salesforce/main/default/objects/Opportunity/recordTypes/Comercial.recordType-meta.xml
<RecordType>
    <fullName>Comercial</fullName>
    <active>true</active>
    <businessProcess>Control_Multiplicador</businessProcess>
    <description>Detalle de lo que el multiplicador va a vender: relatorio de venda</description>
    <label>Comercial</label>
</RecordType>

Salesforce/main/default/main/default/objects/Opportunity/recordTypes/Pendiente.recordType-meta.xml
<RecordType>
    <fullName>Pendiente</fullName>
    <active>true</active>
    <businessProcess>Nota de Venta - Pendiente</businessProcess>
    <label>Pendiente</label>
</RecordType>

Salesforce/main/default/objects/OpportunityLineItem/fields/Estado_de_Produccion__c.field-meta.xml
<CustomField>
    <fullName>Estado_de_Produccion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Estado de Produccion</label>
    <referenceTo>Estado__c</referenceTo>
    <relationshipLabel>Producto de oportunidad</relationshipLabel>
    <relationshipName>Producto_de_oportunidad</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/OpportunityLineItem/fields/Estado_Facturacion__c.field-meta.xml
<CustomField>
    <fullName>Estado_Facturacion__c</fullName>
    <label>Estado Facturacion</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Facturado</fullName>
            </value>
            <value>
                <fullName>No facturado</fullName>
                <default>true</default>
                <label>No facturado</label>
            </value>
            <value>
                <fullName>Pasado Pedido</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/OpportunityLineItem/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <formula>TEXT(Opportunity.Safra__c)</formula>
    <label>Safra</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/Order/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Marca</valueSetName>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Order/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <label>Safra</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Safra</valueSetName>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Regiao__c/Regiao__c.object-meta.xml
<CustomObject>
    <label>Región</label>
    <nameField>
        <label>Nome da Região</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regiones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/globalValueSets/Marca.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BRMX</fullName>
    </customValue>
    <customValue>
        <fullName>DSEM</fullName>
    </customValue>
    <customValue>
        <fullName>NEOG</fullName>
    </customValue>
    <customValue>
        <fullName>DAGMA</fullName>
    </customValue>
    <customValue>
        <fullName>LICENÇAS</fullName>
    </customValue>
    <masterLabel>Marca</masterLabel>
</GlobalValueSet>

Salesforce/main/default/globalValueSets/Safra.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>14/15</fullName>
    </customValue>
    <customValue>
        <fullName>15/16</fullName>
    </customValue>
    <customValue>
        <fullName>16/17</fullName>
    </customValue>
    <customValue>
        <fullName>17/18</fullName>
    </customValue>
    <customValue>
        <fullName>18/19</fullName>
    </customValue>
    <customValue>
        <fullName>19/20</fullName>
    </customValue>
    <customValue>
        <fullName>20/21</fullName>
    </customValue>
    <customValue>
        <fullName>21/22</fullName>
    </customValue>
    <customValue>
        <fullName>22/23</fullName>
    </customValue>
    <customValue>
        <fullName>23/24</fullName>
    </customValue>
    <customValue>
        <fullName>08/09</fullName>
        <isActive>false</isActive>
        <label>08/09</label>
    </customValue>
    <customValue>
        <fullName>07/08</fullName>
        <isActive>false</isActive>
        <label>07/08</label>
    </customValue>
    <customValue>
        <fullName>10/11</fullName>
        <isActive>false</isActive>
        <label>10/11</label>
    </customValue>
    <customValue>
        <fullName>11/12</fullName>
        <isActive>false</isActive>
        <label>11/12</label>
    </customValue>
    <customValue>
        <fullName>12/13</fullName>
        <isActive>false</isActive>
        <label>12/13</label>
    </customValue>
    <customValue>
        <fullName>13/14</fullName>
        <isActive>false</isActive>
        <label>13/14</label>
    </customValue>
    <customValue>
        <fullName>09/10</fullName>
        <isActive>false</isActive>
        <label>09/10</label>
    </customValue>
    <masterLabel>Safra</masterLabel>
</GlobalValueSet>

Salesforce/main/default/classes/anexosController.cls
Public class anexosController{

   public anexosController(ApexPages.StandardController controller) {

   }

   public String searchTextAnexo {get; set;}
   public List<Opportunity> resultAnexos = new List<Opportunity>();
   public String anexo {get; set;}
   public String etapaAnexo;
   private String rt_anexoI_opps;
   private String rt_anexoII_opps;
   private String rt_anexoIII_opps;
   private String rt_anexoIV_opps;
   private String rt_anexoV_opps;
   
   public void setetapaAnexo(String arg){
       etapaAnexo = arg;
   }

   public String getetapaAnexo(){
       Profile pro = [Select Name From Profile Where Id = : UserInfo.getProfileId()];       
       if (pro.Name == 'Administrador del sistema' || pro.Name == 'Gerente Administrativo')
           etapaAnexo = 'PEAP';
       if (pro.Name == 'Comercial')
           etapaAnexo = 'PEAN';    
       if (pro.Name == 'Administrativo')
           etapaAnexo = 'APR';    
   
       return etapaAnexo;
   }
   
   public anexosController(){    
       searchTextAnexo = '';
      
       for (RecordType rt : [Select Id, Name From RecordType Where Name in ('Anexo I','Anexo II','Anexo III', 'Anexo IV', 'Anexo V')]){
           if (rt.Name == 'Anexo I')
              rt_anexoI_opps = rt.Id;
           if (rt.Name == 'Anexo II')
              rt_anexoII_opps = rt.Id;
           if (rt.Name == 'Anexo III')
              rt_anexoIII_opps = rt.Id;
           if (rt.Name == 'Anexo IV')
              rt_anexoIV_opps = rt.Id;
           if (rt.Name == 'Anexo V')
              rt_anexoV_opps = rt.Id;      
       }
   }
       
   public List<Opportunity> getresultAnexos() {return resultAnexos;}    
   
   public List<SelectOption> getTiposAnexos() {
       List<SelectOption> options = new List<SelectOption>();
       options.add(new SelectOption('ALL','--Todos--'));
       options.add(new SelectOption('A1','Anexo I'));
       options.add(new SelectOption('A2','Anexo II'));
       options.add(new SelectOption('A3','Anexo III'));
       options.add(new SelectOption('A4','Anexo IV'));
       options.add(new SelectOption('A5','Anexo V'));
       return options;
   }
   
   public List<SelectOption> getEtapasAnexos() {        
       List<SelectOption> options = new List<SelectOption>();
       options.add(new SelectOption('ALL','--Todas--'));
       options.add(new SelectOption('PEAN','Pendiente de Analisis'));
       options.add(new SelectOption('PEAP','Pendiente de Aprobacion'));
       options.add(new SelectOption('APR','Aprobada'));      
       
       return options;
   }
   
   public void listarAnexos(){
       resultAnexos = null;
       this.searchAnexos();       
   }
   
   public void searchAnexos(){
       String s = searchTextAnexo;
       
       String qry = 'select Id, Name, Mes__c, Regiao__r.Name, VB_Franqueado__c, VB_Franqueado__r.Name, StageName, Safra__c, Estado_Facturacion__c, CloseDate, Numero_del__c, Account.Id, Account.Name, Account.Responsavel__c, RecordType.Name, LastModifiedDate, Relatorio_Relacionado__c, Relatorio_Relacionado__r.Name, Nro_Pedido_SAP__c, VB_Cidade__c, Estado_de_Produccion__c From Opportunity ';
       
       qry += 'where OwnerId != null ';
       if (anexo == 'A1')
           qry += ' and RecordTypeId = : rt_anexoI_opps ';
       if (anexo == 'A2')
           qry += ' and RecordTypeId = : rt_anexoII_opps ';
       if (anexo == 'A3')
           qry += ' and RecordTypeId = : rt_anexoIII_opps ';
       if (anexo == 'A4')
           qry += ' and RecordTypeId = : rt_anexoIV_opps ';
       if (anexo == 'A5')
           qry += ' and RecordTypeId = : rt_anexoV_opps ';        
       if (anexo == 'ALL')
           qry += ' and (RecordTypeId = : rt_anexoI_opps OR RecordTypeId = : rt_anexoII_opps OR RecordTypeId = : rt_anexoIII_opps OR RecordTypeId = : rt_anexoIV_opps OR RecordTypeId = : rt_anexoV_opps) ';
           
       if (etapaAnexo == 'PEAN')
           qry += ' and StageName = \'Pendiente de Análisis\'';    
       if (etapaAnexo == 'PEAP')
           qry += ' and StageName = \'Pendiente de Aprobación\'';    
       if (etapaAnexo == 'APR')
           qry += ' and StageName = \'Aprobada\'';                   
                       
       if(s != ''){ s = '%' + s + '%'; qry += ' and Name like : s';}
       qry += ' Order by Nro_Pedido_SAP__c, Safra__c Desc, LastModifiedDate Desc';
       resultAnexos = Database.query(qry);
   }
      
   public List<OpportunityLineItem> getItems() {
       String query = 'SELECT ';
       for(Schema.FieldSetMember f : this.getFields()) {
           query += f.getFieldPath() + ', ';
       }
       query += 'Id FROM OpportunityLineItem Where OpportunityId = \'' + apexpages.currentpage().getparameters().get('id') + '\'';
       return Database.query(query);
   }
   
   public List<Schema.FieldSetMember> getFields() {
        Opportunity o = [Select RecordType.Name From Opportunity Where Id = : apexpages.currentpage().getparameters().get('id')];
        if (o.RecordType.Name == 'Anexo I')
            return SObjectType.OpportunityLineItem.FieldSets.AnexoI.getFields();
        if (o.RecordType.Name == 'Anexo II')
            return SObjectType.OpportunityLineItem.FieldSets.AnexoII.getFields();
        if (o.RecordType.Name == 'Anexo III')
            return SObjectType.OpportunityLineItem.FieldSets.Anexo_III.getFields();  
            
        return null;                      
   }
   
   
   static testmethod void test(){
   	
       anexosController anexos = New anexosController();
       
       anexos.searchAnexos();	
       anexos.listarAnexos();
       String a;
       anexos.setetapaAnexo(a);
       a = anexos.getetapaAnexo();
       List<SelectOption> op = New List<SelectOption>();
       op = anexos.getEtapasAnexos();
       op = anexos.getTiposAnexos();       
       List <OpportunityLineItem> items = New List<OpportunityLineItem>();
       
       RecordType rt = [Select Id From RecordType Where Name = 'Anexo I' And SObjectType = 'Opportunity' limit 1];
       Opportunity o = New Opportunity();
       o.Name = 'a';
       o.CloseDate = system.today();
       o.RecordTypeId = rt.Id;
       o.StageName = 'Edición';
       o.Marca__c = 'BRMX';
       insert o;
       ApexPages.currentPage().getParameters().put('id',o.Id);
       items = anexos.getItems();              
       
       //ApexPages.currentPage().getParameters().put('id',o.Id);
       //items = anexos.getItems();
       //List<Schema.FieldSetMember> b = anexos.getFields();
   	
   }
   
}