Salesforce/main/default/objects/Account/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Marca</valueSetName>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Account/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Região</label>
    <referenceTo>Regiao__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Campaign/fields/Epoca_de_Producao__c.field-meta.xml
<CustomField>
    <fullName>Epoca_de_Producao__c</fullName>
    <label>Época de Produção</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inverno</fullName>
            </value>
            <value>
                <fullName>Verão</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Campaign/fields/Lista_de_precios__c.field-meta.xml
<CustomField>
    <fullName>Lista_de_precios__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lista de precios</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Campaigns</relationshipLabel>
    <relationshipName>Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Campaign/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <description>Para desarrollo &quot;Venda de Basica&quot;</description>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Marca</valueSetName>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Campaign/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Region seleccionada para desarrollo Venda de Basica</description>
    <label>Region</label>
    <referenceTo>Regiao__c</referenceTo>
    <relationshipLabel>Campaigns</relationshipLabel>
    <relationshipName>Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Campaign/fields/Region_VB__c.field-meta.xml
<CustomField>
    <fullName>Region_VB__c</fullName>
    <label>Region VB</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>REGION 1</fullName>
            </value>
            <value>
                <fullName>REGION 2</fullName>
            </value>
            <value>
                <fullName>CERRADO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Campaign/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <description>Para desarrollo &quot;Venda de Basica&quot;</description>
    <label>Safra</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Safra</valueSetName>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Campaign/recordTypes/Venda_de_Basica.recordType-meta.xml
<RecordType>
    <fullName>Venda_de_Basica</fullName>
    <active>true</active>
    <description>Para desarrollo &quot;Venda de Basica&quot;</description>
    <label>Venda de Basica</label>
</RecordType>

Salesforce/main/default/main/default/objects/Contrato__c/Contrato__c.object-meta.xml
<CustomObject>
    <description>CONTRATO DE LICENCIAMENTO PARA MULTIPLICAÇÃO E COMERCIALIZAÇÃO</description>
    <label>Contrato de Multiplicação</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Numero do Contrato de Multiplicação</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contratos de Multiplicação</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Salesforce/main/default/objects/Contrato__c/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <label>Safra</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>17/18</fullName>
                <default>true</default>
                <label>17/18</label>
            </value>
            <value>
                <fullName>18/19</fullName>
            </value>
            <value>
                <fullName>19/20</fullName>
            </value>
            <value>
                <fullName>20/21</fullName>
            </value>
            <value>
                <fullName>21/22</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Contrato__c/recordTypes/BRMX.recordType-meta.xml
<RecordType>
    <fullName>BRMX</fullName>
    <active>true</active>
    <description>Contratos de la sociedad BRASMAX</description>
    <label>BRMX</label>
</RecordType>

Salesforce/main/default/objects/Contrato__c/recordTypes/DSEM.recordType-meta.xml
<RecordType>
    <fullName>DSEM</fullName>
    <active>true</active>
    <description>Contratos de la sociedad Don Mario</description>
    <label>DSEM</label>
</RecordType>

Salesforce/main/default/objects/CRM_Calendario_de_Eventos__c/CRM_Calendario_de_Eventos__c.object-meta.xml
<CustomObject>
    <description>Registro de eventos programados pelo Multiplicador</description>
    <label>CRM Evento</label>
    <nameField>
        <label>Nome de CRM Evento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Eventos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/CRM_Calendario_de_Eventos__c/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <label>Safra</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>11/12</fullName>
            </value>
            <value>
                <fullName>12/13</fullName>
            </value>
            <value>
                <fullName>17/18</fullName>
            </value>
            <value>
                <fullName>18/19</fullName>
            </value>
            <value>
                <fullName>19/20</fullName>
            </value>
            <value>
                <fullName>20/21</fullName>
            </value>
            <value>
                <fullName>21/22</fullName>
                <default>true</default>
                <label>21/22</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Opportunity/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <description>Identifica la marca para las Oportunidades del Circuito de Anexos. Se selecciona la lista de precios en función de este campo</description>
    <inlineHelpText>Identificar a marca de Oportunidades Circuito Anexos. Você seleciona a lista de preços com base neste campo</inlineHelpText>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BRMX</fullName>
            </value>
            <value>
                <fullName>DSEM</fullName>
            </value>
            <value>
                <fullName>NEOG</fullName>
            </value>
            <value>
                <fullName>DAGMA</fullName>
            </value>
            <value>
                <fullName>LICENÇAS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Opportunity/fields/Regiao__c.field-meta.xml
<CustomField>
    <fullName>Regiao__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Região</label>
    <referenceTo>Regiao__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/Opportunity/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Região</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SUR</fullName>
            </value>
            <value>
                <fullName>CERRADO</fullName>
            </value>
            <value>
                <fullName>REGION 1</fullName>
            </value>
            <value>
                <fullName>REGION 2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Opportunity/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <description>Safra o Campania agricola</description>
    <label>Safra</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>06/07</fullName>
            </value>
            <value>
                <fullName>07/08</fullName>
            </value>
            <value>
                <fullName>08/09</fullName>
            </value>
            <value>
                <fullName>09/10</fullName>
            </value>
            <value>
                <fullName>09/09</fullName>
            </value>
            <value>
                <fullName>10/10</fullName>
            </value>
            <value>
                <fullName>10/11</fullName>
            </value>
            <value>
                <fullName>11/11</fullName>
            </value>
            <value>
                <fullName>11/12</fullName>
            </value>
            <value>
                <fullName>12/12</fullName>
            </value>
            <value>
                <fullName>12/13</fullName>
            </value>
            <value>
                <fullName>13/14</fullName>
            </value>
            <value>
                <fullName>14/15</fullName>
            </value>
            <value>
                <fullName>15/16</fullName>
            </value>
            <value>
                <fullName>16/17</fullName>
            </value>
            <value>
                <fullName>17/18</fullName>
            </value>
            <value>
                <fullName>18/19</fullName>
            </value>
            <value>
                <fullName>19/20</fullName>
            </value>
            <value>
                <fullName>20/21</fullName>
            </value>
            <value>
                <fullName>21/22</fullName>
                <default>true</default>
                <label>21/22</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Regiao__c/Regiao__c.object-meta.xml
<CustomObject>
    <label>Región</label>
    <nameField>
        <label>Nome da Região</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regiones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/globalValueSets/Marca.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BRMX</fullName>
    </customValue>
    <customValue>
        <fullName>DSEM</fullName>
    </customValue>
    <customValue>
        <fullName>NEOG</fullName>
    </customValue>
    <customValue>
        <fullName>DAGMA</fullName>
    </customValue>
    <customValue>
        <fullName>LICENÇAS</fullName>
    </customValue>
    <masterLabel>Marca</masterLabel>
</GlobalValueSet>

Salesforce/main/default/globalValueSets/Safra.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>14/15</fullName>
    </customValue>
    <customValue>
        <fullName>15/16</fullName>
    </customValue>
    <customValue>
        <fullName>16/17</fullName>
    </customValue>
    <customValue>
        <fullName>17/18</fullName>
    </customValue>
    <customValue>
        <fullName>18/19</fullName>
    </customValue>
    <customValue>
        <fullName>19/20</fullName>
    </customValue>
    <customValue>
        <fullName>20/21</fullName>
    </customValue>
    <customValue>
        <fullName>21/22</fullName>
    </customValue>
    <customValue>
        <fullName>22/23</fullName>
    </customValue>
    <customValue>
        <fullName>23/24</fullName>
    </customValue>
    <customValue>
        <fullName>08/09</fullName>
        <isActive>false</isActive>
        <label>08/09</label>
    </customValue>
    <customValue>
        <fullName>07/08</fullName>
        <isActive>false</isActive>
        <label>07/08</label>
    </customValue>
    <customValue>
        <fullName>10/11</fullName>
        <isActive>false</isActive>
        <label>10/11</label>
    </customValue>
    <customValue>
        <fullName>11/12</fullName>
        <isActive>false</isActive>
        <label>11/12</label>
    </customValue>
    <customValue>
        <fullName>12/13</fullName>
        <isActive>false</isActive>
        <label>12/13</label>
    </customValue>
    <customValue>
        <fullName>13/14</fullName>
        <isActive>false</isActive>
        <label>13/14</label>
    </customValue>
    <customValue>
        <fullName>09/10</fullName>
        <isActive>false</isActive>
        <label>09/10</label>
    </customValue>
    <masterLabel>Safra</masterLabel>
</GlobalValueSet>

Salesforce/main/default/main/default/classes/accUpdateResponsibleControllerTest.cls
@isTest
private class accUpdateResponsibleControllerTest {
    
    @TestSetup static void setup() {
        Map<String, User> users = new Map<String, User>();

        for (User user : [SELECT Id, Name FROM User]) {
            users.put(user.Name, user);
        }

        Regiao__c region = Build.aRegiao().withRegionComercial('REGION 1').build();

        insert region;

        Account account = Build.anAccount()
            .withName('CENTRAL DE ASSOCIAÇÕES DE PEQUENOS PRODUTORES RURAIS')
            .withNomefantasia('CAPRUL')
            .withRegion(region)
            .withResponsavel('009 - Jorge Cristiano Rosa')
            .withReponsavelDSEM('014 - Cristian Pirolli')
            .withType('Multiplicador')
            .withSupervisor(users.get('Jorge Cristiano Rosa'))
            .withGerenteComercial(users.get('Cristian Pirolli'))
            .build();

        insert account;

        Campaign campaign = new Campaign(
            Name = 'Campaña VB - 20/21 - BRMX -',
            Marca__c = 'BRMX',
            Safra__c = '20/21',
            Region__c = region.Id,
            epoca_de_producao__c = 'Verão',
            StartDate = System.today().addDays(-10),
            EndDate = System.today().addDays(10),
            Lista_de_precios__c = Test.getStandardPricebookId(),
            RecordTypeId = XappiaHelper.getRecordType('Campaign','Venda_de_Basica').Id,
            Region_VB__c = 'REGION 1;CERRADO'
        );

        insert campaign;

        Opportunity opportunity = Build.anOpportunityVendaDaBasicaCompleta()
            .withStageName('Edición')
            .withMarca('BRMX')
            .withAccountId(account)
            .withCampaignId(campaign)
            .withRegion('REGION 1')
            .withTipoDeCultivares('Comerciais')
            .withTipoDeNecessidade('Multiplicação')
            .withPricebook2Id(Test.getStandardPricebookId())
            .build();

        insert opportunity;

        CRM_Calendario_de_Eventos__c[] crmEventos = new CRM_Calendario_de_Eventos__c[2];

        crmEventos[0] = Build.aCRMCalendariodeEventosDiadeCampo()
            .withName('Test Responsável 1')
            .withRealizadopor('Andre Aguilar')
            .withParticipante('Andre Aguilar;Carlos Martinelli')
            .withData(Date.today())
            .withDataehorarioinicio(Datetime.now())
            .withDataehorariotermino(Datetime.now().addHours(5))
            .withCuenta(account)
            .withSafra('19/20')
            .withMarca('BRMX')
            .withFase('Aprovado')
            .withEvento('Día de Campo')
            .build();

        crmEventos[1] = Build.aCRMCalendariodeEventosTreinamentoTecnico()
            .withName('Test Responsável 2')
            .withRealizadopor('Andre Aguilar')
            .withParticipante('Andre Aguilar;Carlos Martinelli')
            .withData(Date.today())
            .withDataehorarioinicio(Datetime.now())
            .withDataehorariotermino(Datetime.now().addHours(8))
            .withCuenta(account)
            .withSafra('19/20')
            .withMarca('DSEM')
            .withFase('Aprovado')
            .withEvento('Treinamento')
            .build();

        //insert crmEventos;

        Contrato__c[] contratos = new Contrato__c[2];

        contratos[0] = Build.aContratoAditivoBRMX()
            .withMultiplicador(account)
            .withSafra('19/20')
            .withSociedad('BRMX')
            .withTipodeCotao('SOJA')
            .build();

        contratos[1] = Build.aContratoAditivoDSEM()
            .withMultiplicador(account)
            .withSafra('19/20')
            .withSociedad('DSEM')
            .withTipodeCotao('SOJA')
            .build();

        insert contratos;
    }

    @isTest static void updateResponsibles() {
        Account account = [SELECT Id FROM Account LIMIT 1];
        Opportunity opportunity = null;
        CRM_Calendario_de_Eventos__c[] crmEventos = null;
        Contrato__c[] contratos = null;
        User[] users = [SELECT Id, Name FROM User WHERE Name = 'Jorge Cristiano Rosa' OR Name = 'Cristian Pirolli'];

        Test.startTest();
        String[] retorno = accUpdateResponsibleController.sendUpdateRequest(account.Id);

        //System.assertEquals('true', retorno[1], 'El response no es el esperado');
        //System.assertEquals('Oportunidades atualizadas 1, CRM Eventos atualizados 2, Aditivos atualizados 2', retorno[0], 'El response no es el esperado');

        opportunity = [SELECT Id, OwnerId FROM Opportunity LIMIT 1];
        crmEventos = [SELECT Id, OwnerId FROM CRM_Calendario_de_Eventos__c];
        contratos = [SELECT Id, OwnerId FROM Contrato__c];
        Test.stopTest();

        //System.assertNotEquals(UserInfo.getUserId(), opportunity.OwnerId, 'No se ha modificado el propietario del registro');

        /*for (CRM_Calendario_de_Eventos__c evento : crmEventos) {
            System.assertNotEquals(UserInfo.getUserId(), evento.OwnerId, 'No se ha modificado el propietario del registro');
        }

        for (Contrato__c contrato : contratos) {
            System.assertNotEquals(UserInfo.getUserId(), contrato.OwnerId, 'No se ha modificado el propietario del registro');
        }*/
    }

    @isTest static void updateResponsiblesBySupervisor() {
        Account account = [SELECT Id FROM Account LIMIT 1];
        Opportunity opportunity = null;
        CRM_Calendario_de_Eventos__c[] crmEventos = null;
        Contrato__c[] contratos = null;
        User[] users = [SELECT Id, Name FROM User WHERE Name = 'Jorge Cristiano Rosa' OR Name = 'Cristian Pirolli'];

        Test.startTest();
        String[] retorno = null;

        User user = Build.anUser()
            .withUsername('testuser@gdmseeds.com.test')
            .withFirstName('Test')
            .withLastName('User')
            .withCompanyName('GDM Genetica do Brasil')
            .withEmail('testuser@gdmseeds.com.test')
            .withTitle('Anal. Carteira de Clientes')
            .withCentrodeCosto('14000006')
            .withUserRoleId([SELECT Id FROM UserRole WHERE Name = 'Administracion y Fiscalizador' LIMIT 1])
            .withProfileId([SELECT Id FROM Profile WHERE Name = 'Administrativo' LIMIT 1])
            .withCommunityNickname('testuser')
            .withIsActive(true)
            .build();
        
        System.runAs(user) {
            retorno = accUpdateResponsibleController.sendUpdateRequest(account.Id);
        }

        //System.assertEquals('true', retorno[1], 'El response no es el esperado');
        //System.assertEquals('Oportunidades atualizadas 1, CRM Eventos atualizados 2, Aditivos atualizados 2', retorno[0], 'El response no es el esperado');

        opportunity = [SELECT Id, OwnerId FROM Opportunity LIMIT 1];
        crmEventos = [SELECT Id, OwnerId FROM CRM_Calendario_de_Eventos__c];
        contratos = [SELECT Id, OwnerId FROM Contrato__c];
        Test.stopTest();

        //System.assertNotEquals(UserInfo.getUserId(), opportunity.OwnerId, 'No se ha modificado el propietario del registro');

        //for (CRM_Calendario_de_Eventos__c evento : crmEventos) {
        //    System.assertNotEquals(UserInfo.getUserId(), evento.OwnerId, 'No se ha modificado el propietario del registro');
        //}

        //for (Contrato__c contrato : contratos) {
        //    System.assertNotEquals(UserInfo.getUserId(), contrato.OwnerId, 'No se ha modificado el propietario del registro');
        //}
    }
}