Salesforce/main/default/objects/Account/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Marca</valueSetName>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Account/fields/Multiplicador__c.field-meta.xml
<CustomField>
    <fullName>Multiplicador__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Multiplicador</label>
    <type>Checkbox</type>
</CustomField>

Salesforce/main/default/main/default/objects/Contrato__c/Contrato__c.object-meta.xml
<CustomObject>
    <description>CONTRATO DE LICENCIAMENTO PARA MULTIPLICAÇÃO E COMERCIALIZAÇÃO</description>
    <label>Contrato de Multiplicação</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Numero do Contrato de Multiplicação</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contratos de Multiplicação</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Salesforce/main/default/objects/Contrato__c/fields/Cultivar__c.field-meta.xml
<CustomField>
    <fullName>Cultivar__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Se refere ao produto (cultivar) que será feito o contrato (um contrato para cada produto). É por este fato que todos possuem o número 1 nas cultivares que a conta vai multiplicar</description>
    <inlineHelpText>Se refere ao produto (cultivar) que será feito o contrato (um contrato para cada produto). É por este fato que todos possuem o número 1 nas cultivares que a conta vai multiplicar</inlineHelpText>
    <label>Cultivar</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Contrato_de_Multiplica_o</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Contrato__c/fields/Multiplicador__c.field-meta.xml
<CustomField>
    <fullName>Multiplicador__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Conta do multiplicador</description>
    <label>Multiplicador</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Contrato_de_Multiplica_o</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/Contrato__c/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <label>Safra</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>17/18</fullName>
                <default>true</default>
                <label>17/18</label>
            </value>
            <value>
                <fullName>18/19</fullName>
            </value>
            <value>
                <fullName>19/20</fullName>
            </value>
            <value>
                <fullName>20/21</fullName>
            </value>
            <value>
                <fullName>21/22</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Contrato__c/fields/Sociedad__c.field-meta.xml
<CustomField>
    <fullName>Sociedad__c</fullName>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BRMX</fullName>
            </value>
            <value>
                <fullName>DSEM</fullName>
            </value>
            <value>
                <fullName>NEOG</fullName>
            </value>
            <value>
                <fullName>DAGMA</fullName>
            </value>
            <value>
                <fullName>LICENÇAS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Item_del_Contrato__c/Item_del_Contrato__c.object-meta.xml
<CustomObject>
    <description>Item de CONTRATO DE LICENCIAMENTO PARA MULTIPLICAÇÃO E COMERCIALIZAÇÃO</description>
    <label>Item del Contrato</label>
    <nameField>
        <label>Nombre de Item del Contrato</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items del Contrato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Salesforce/main/default/objects/Item_del_Contrato__c/fields/Contrato_de_Multiplicacion__c.field-meta.xml
<CustomField>
    <fullName>Contrato_de_Multiplicacion__c</fullName>
    <description>Relación entre la cabecera del Contrato con los items(información de la variedad, precio, etc)</description>
    <inlineHelpText>Relación entre la cabecera del Contrato con los items(información de la variedad, precio, etc)</inlineHelpText>
    <label>Contrato de Multiplicação</label>
    <referenceTo>Contrato__c</referenceTo>
    <relationshipLabel>Items del Contrato</relationshipLabel>
    <relationshipName>Items_del_Contrato</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Salesforce/main/default/objects/Item_del_Contrato__c/fields/Cultivar__c.field-meta.xml
<CustomField>
    <fullName>Cultivar__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Cultivar por el/los que se confecciona el contrato</description>
    <inlineHelpText>Cultivar por el/los que se confecciona el contrato</inlineHelpText>
    <label>Cultivar</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Items del Contrato</relationshipLabel>
    <relationshipName>Items_del_Contrato</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/Opportunity/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <description>Identifica la marca para las Oportunidades del Circuito de Anexos. Se selecciona la lista de precios en función de este campo</description>
    <inlineHelpText>Identificar a marca de Oportunidades Circuito Anexos. Você seleciona a lista de preços com base neste campo</inlineHelpText>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BRMX</fullName>
            </value>
            <value>
                <fullName>DSEM</fullName>
            </value>
            <value>
                <fullName>NEOG</fullName>
            </value>
            <value>
                <fullName>DAGMA</fullName>
            </value>
            <value>
                <fullName>LICENÇAS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Opportunity/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <description>Safra o Campania agricola</description>
    <label>Safra</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>06/07</fullName>
            </value>
            <value>
                <fullName>07/08</fullName>
            </value>
            <value>
                <fullName>08/09</fullName>
            </value>
            <value>
                <fullName>09/10</fullName>
            </value>
            <value>
                <fullName>09/09</fullName>
            </value>
            <value>
                <fullName>10/10</fullName>
            </value>
            <value>
                <fullName>10/11</fullName>
            </value>
            <value>
                <fullName>11/11</fullName>
            </value>
            <value>
                <fullName>11/12</fullName>
            </value>
            <value>
                <fullName>12/12</fullName>
            </value>
            <value>
                <fullName>12/13</fullName>
            </value>
            <value>
                <fullName>13/14</fullName>
            </value>
            <value>
                <fullName>14/15</fullName>
            </value>
            <value>
                <fullName>15/16</fullName>
            </value>
            <value>
                <fullName>16/17</fullName>
            </value>
            <value>
                <fullName>17/18</fullName>
            </value>
            <value>
                <fullName>18/19</fullName>
            </value>
            <value>
                <fullName>19/20</fullName>
            </value>
            <value>
                <fullName>20/21</fullName>
            </value>
            <value>
                <fullName>21/22</fullName>
                <default>true</default>
                <label>21/22</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Opportunity/fields/Sociedad__c.field-meta.xml
<CustomField>
    <fullName>Sociedad__c</fullName>
    <label>Sociedad</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/Product2/fields/Sociedad__c.field-meta.xml
<CustomField>
    <fullName>Sociedad__c</fullName>
    <label>Sociedad</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BRMX</fullName>
            </value>
            <value>
                <fullName>DSEM</fullName>
            </value>
            <value>
                <fullName>NEOG</fullName>
            </value>
            <value>
                <fullName>DAGMA</fullName>
            </value>
            <value>
                <fullName>LICENÇAS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/globalValueSets/Marca.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BRMX</fullName>
    </customValue>
    <customValue>
        <fullName>DSEM</fullName>
    </customValue>
    <customValue>
        <fullName>NEOG</fullName>
    </customValue>
    <customValue>
        <fullName>DAGMA</fullName>
    </customValue>
    <customValue>
        <fullName>LICENÇAS</fullName>
    </customValue>
    <masterLabel>Marca</masterLabel>
</GlobalValueSet>

Salesforce/main/default/classes/TestDAOOpportunity.cls
@IsTest
public class TestDAOOpportunity {
    @isTest public static void test(){
        Account acc = new Account(Name = 'Teste');
        Contrato__c cont = new Contrato__c();
        cont.Multiplicador__c = acc.Id;
        cont.Safra__c = '19/20';
        cont.Sociedad__c = 'NEOG';
        insert cont;
        Product2 prod = new Product2(Name = 'Test');
        Item_del_Contrato__c icon = new Item_del_Contrato__c();
        icon.Cultivar__c = prod.Id;
        icon.Contrato_de_Multiplicacion__c = cont.Id;
        insert icon;
        Opportunity opp = new Opportunity(Name = 'Test', CloseDate = System.Today(), StageName = 'Edición', AccountId = acc.Id, Marca__c = 'NEOG', Safra__c = '18/19');
        insert opp;
        
        DAOOpportunity.getInstance().get(opp.Id);
        DAOOpportunity.getInstance(DTOUtils.SharingMode.Without).get(opp.Id);

        DAOOpportunity.getInstance().get(opp.Id);
        DAOOpportunity.getInstance(DTOUtils.SharingMode.Without).get(new List<Id> {opp.Id});

        
        DAOOpportunity.getInstance().getByFilter('NEOG', '19/20', acc.Id, new List<String> {'Anexo I'}, 'Edición');
        DAOOpportunity.getInstance(DTOUtils.SharingMode.Without).getByFilter('NEOG', '19/20', acc.Id, new List<String> {'Anexo I'}, 'Edición');

        
      
    }
    
}