Salesforce/main/default/objects/Account/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Marca</valueSetName>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Midia_Kit__c/Midia_Kit__c.object-meta.xml
<CustomObject>
    <label>Midia Kit</label>
    <nameField>
        <label>Nome de Midia Kit</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Midia Kits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/objects/Midia_Kit__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Arte de Resultado de Produtividade</fullName>
            </value>
            <value>
                <fullName>Big Bag</fullName>
            </value>
            <value>
                <fullName>Logos</fullName>
            </value>
            <value>
                <fullName>Cultivares</fullName>
            </value>
            <value>
                <fullName>Manual de Identidade Visual</fullName>
            </value>
            <value>
                <fullName>Placas de campo</fullName>
            </value>
            <value>
                <fullName>Sacaria</fullName>
            </value>
            <value>
                <fullName>Outdoor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Midia_Kit__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Midia Kits</relationshipLabel>
    <relationshipName>Midia_Kits</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/globalValueSets/Marca.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BRMX</fullName>
    </customValue>
    <customValue>
        <fullName>DSEM</fullName>
    </customValue>
    <customValue>
        <fullName>NEOG</fullName>
    </customValue>
    <customValue>
        <fullName>DAGMA</fullName>
    </customValue>
    <customValue>
        <fullName>LICENÇAS</fullName>
    </customValue>
    <masterLabel>Marca</masterLabel>
</GlobalValueSet>

Salesforce/main/default/classes/MidiaKitAPITest.cls
@isTest
public class MidiaKitAPITest {
	
    @TestSetup
    static void makeData(){
        
        Account testAccount = new Account(Name = 'TestAccount');
        insert testAccount;
        
        Account testAccountNoItems = new Account(Name = 'TestAccountNoItems');
        insert testAccountNoItems;
        

        List<Midia_Kit__c> testMidiaKitsList = new List<Midia_Kit__c>();
        
        testMidiaKitsList.add( new Midia_Kit__c(Name = 'Midia Kit 1 Test', 
                                                Active__c = true, 
                                                Cuenta__c = testAccount.Id, 
                                                Marca__c = 'NEOG', 
                                                Category__c = 'Arte de Resultado de Produtividade', 
                                                URL__c = 'https://www.salesforce.com'));
        
        testMidiaKitsList.add( new Midia_Kit__c(Name = 'Midia Kit 2 Test', 
                                                Active__c = true, 
                                                Cuenta__c = testAccount.Id, 
                                                Marca__c = 'NEOG', 
                                                Category__c = 'Big Bag', 
                                                URL__c = 'https://trailhead.salesforce.com'));
        
        testMidiaKitsList.add( new Midia_Kit__c(Name = 'Midia Kit 3 Test', 
                                                Active__c = true, 
                                                Cuenta__c = testAccount.Id, 
                                                Marca__c = 'NEOG', 
                                                Category__c = 'Logos', 
                                                URL__c = 'https://trailhead.salesforce.com'));
        
        
        insert testMidiaKitsList;
    }
    
    @isTest
    public static void getMidiaKitsListTestPositive() {
        
        String accountId = [SELECT Id FROM Account WHERE Name = 'TestAccount' LIMIT 1].Id;
        String testMarca = 'NEOG';
        
        MidiaKitAPI.MidiaKitAPIResponse result;
        
        RestRequest req = new RestRequest(); 
        req.requestURI = '/services/apexrest/MidiaKitAPI/';  
        req.addParameter('accountId', accountId);
        req.addParameter('marca', testMarca);
        req.httpMethod = 'GET';

        RestResponse resp = new RestResponse();
        RestContext.request = req;
        RestContext.response = resp;

        test.startTest();
        MidiaKitAPI.listarMidiaKits();
        test.stopTest();

        result = (MidiaKitAPI.MidiaKitAPIResponse)JSON.deserialize(resp.responseBody.toString(), MidiaKitAPI.MidiaKitAPIResponse.class);
        
        System.assert(result.status);
        System.assertEquals(Label.MidiaKitAPI_Success_Message, result.message);
        System.assertEquals(3, result.midiaKits.size());
    }
    
    @isTest
    public static void getMidiaKitsListNoItemsTest() {
        
        String accountNoItemsId = [SELECT Id FROM Account WHERE Name = 'testAccountNoItems' LIMIT 1].Id;
        String testMarca = 'NEOG';
        
        MidiaKitAPI.MidiaKitAPIResponse result;
        
        RestRequest req = new RestRequest(); 
        req.requestURI = '/services/apexrest/MidiaKitAPI/';  
        req.addParameter('accountId', accountNoItemsId);
        req.addParameter('marca', testMarca);
        req.httpMethod = 'GET';

        RestResponse resp = new RestResponse();
        RestContext.request = req;
        RestContext.response = resp;

        test.startTest();
        MidiaKitAPI.listarMidiaKits();
        test.stopTest();

        result = (MidiaKitAPI.MidiaKitAPIResponse)JSON.deserialize(resp.responseBody.toString(), MidiaKitAPI.MidiaKitAPIResponse.class);
        
        System.assertEquals(false, result.status);
        System.assertEquals(Label.MidiaKitAPI_No_Items_Error_Message, result.message);
    }
    
    @isTest
    public static void getMidiaKitsListNoParametersTest() {
        
        String accountId = [SELECT Id FROM Account WHERE Name = 'TestAccount' LIMIT 1].Id;
        String testMarca = '';
        
        MidiaKitAPI.MidiaKitAPIResponse result;
        
        RestRequest req = new RestRequest(); 
        req.requestURI = '/services/apexrest/MidiaKitAPI/';  
        req.addParameter('accountId', accountId);
        req.addParameter('marca', testMarca);
        req.httpMethod = 'GET';

        RestResponse resp = new RestResponse();
        RestContext.request = req;
        RestContext.response = resp;

        test.startTest();
        MidiaKitAPI.listarMidiaKits();
        test.stopTest();

        result = (MidiaKitAPI.MidiaKitAPIResponse)JSON.deserialize(resp.responseBody.toString(), MidiaKitAPI.MidiaKitAPIResponse.class);
        
        System.assertEquals(false, result.status);
        System.assertEquals(Label.MidiaKitAPI_Validation_Error_Message, result.message);
    }
}