Salesforce/main/default/objects/Account/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Marca</valueSetName>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Account/fields/Multiplicador__c.field-meta.xml
<CustomField>
    <fullName>Multiplicador__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Multiplicador</label>
    <type>Checkbox</type>
</CustomField>

Salesforce/main/default/main/default/objects/Account/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Região</label>
    <referenceTo>Regiao__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Account/fields/Region_Comercial__c.field-meta.xml
<CustomField>
    <fullName>Region_Comercial__c</fullName>
    <formula>TEXT(Region__r.Region_Comercial__c)</formula>
    <label>Região Comercial</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/Account/fields/Responsavel__c.field-meta.xml
<CustomField>
    <fullName>Responsavel__c</fullName>
    <description>Qual dos funcionários da Brasmax que estará responsável pela conta</description>
    <inlineHelpText>Qual dos funcionários da Brasmax que estará responsável pela conta</inlineHelpText>
    <label>Responsável BRMX</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>061 - Fernando Frehner</fullName>
            </value>
            <value>
                <fullName>066 - Marcelo Steffen</fullName>
            </value>
            <value>
                <fullName>067 - Sergio Bertagnolli</fullName>
            </value>
            <value>
                <fullName>076 - Tiago Goulart</fullName>
            </value>
            <value>
                <fullName>083 - Jorge Cristiano Rosa</fullName>
            </value>
            <value>
                <fullName>010 - Brasmax</fullName>
            </value>
            <value>
                <fullName>101 - Fausto Tadeu Fanchin</fullName>
            </value>
            <value>
                <fullName>104 - Otavio Gorni</fullName>
            </value>
            <value>
                <fullName>150 - João Serrano</fullName>
            </value>
            <value>
                <fullName>012 - Anderson Weissheimer</fullName>
            </value>
            <value>
                <fullName>197 - Wagner Rank</fullName>
            </value>
            <value>
                <fullName>198 - Bernardo Zanardo</fullName>
            </value>
            <value>
                <fullName>199 - Lucas Costa</fullName>
            </value>
            <value>
                <fullName>231 - Willian Von Scharten</fullName>
            </value>
            <value>
                <fullName>234 - Julio Cesar Poletto</fullName>
            </value>
            <value>
                <fullName>017 - Luis Fernando Cecatto</fullName>
            </value>
            <value>
                <fullName>018 - Flávio Marçal dos Santos</fullName>
            </value>
            <value>
                <fullName>312 - Lucas Hilario Fantineli</fullName>
            </value>
            <value>
                <fullName>019 - Felipe Oliveira Costa</fullName>
            </value>
            <value>
                <fullName>379 - Diego F. Gonçalves</fullName>
            </value>
            <value>
                <fullName>031 - Guilherme Sousa</fullName>
            </value>
            <value>
                <fullName>023 - Gabriel V. Finatto</fullName>
            </value>
            <value>
                <fullName>464 - Ana Laura Fernandes</fullName>
            </value>
            <value>
                <fullName>467 - Natalie de Mattos</fullName>
            </value>
            <value>
                <fullName>474 - Guilherme Menezes Salau</fullName>
            </value>
            <value>
                <fullName>403 - Felipe Bianchessi</fullName>
            </value>
            <value>
                <fullName>380 - Lucas de Souza Furlan</fullName>
            </value>
            <value>
                <fullName>037 - Felipe Dias Louzada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Account/fields/Supervisor__c.field-meta.xml
<CustomField>
    <fullName>Supervisor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supervisor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Supervisores</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/Configuracion_BMX__c/Configuracion_BMX__c.object-meta.xml
<CustomObject>
    <description>Indicador de Parametros.</description>
    <label>Configuracion_BMX</label>
    <nameField>
        <label>Configuracion Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuraciones_BMX</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/Configuracion_BMX__c/fields/CRM_Safra_Actual__c.field-meta.xml
<CustomField>
    <fullName>CRM_Safra_Actual__c</fullName>
    <description>Indica la campaña actual con la que está trabajando CRM</description>
    <label>CRM_Safra_Actual</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/Configuracion_BMX__c/fields/PM_Safra_Actual_VB_Estimativa_de_Compra__c.field-meta.xml
<CustomField>
    <fullName>PM_Safra_Actual_VB_Estimativa_de_Compra__c</fullName>
    <label>PM Safra Actual VB-Estimativa de Compra</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Safra</valueSetName>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Produto_de_Requisicao__c/Produto_de_Requisicao__c.object-meta.xml
<CustomObject>
    <label>Produto de Requisição</label>
    <nameField>
        <label>Nombre de Produto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Produtos de Requisição</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/Produto_de_Requisicao__c/fields/Multiplicador__c.field-meta.xml
<CustomField>
    <fullName>Multiplicador__c</fullName>
    <formula>Requisicao_de_compra__r.Multiplicador__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Multiplicador</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/Produto_de_Requisicao__c/fields/Requisicao_de_compra__c.field-meta.xml
<CustomField>
    <fullName>Requisicao_de_compra__c</fullName>
    <label>Requisição de compra</label>
    <referenceTo>Requisicao_de_compra__c</referenceTo>
    <relationshipLabel>Produtos de Requisição</relationshipLabel>
    <relationshipName>Produtos_de_Requisicao</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Salesforce/main/default/main/default/objects/Produto_de_Requisicao__c/fields/Variedad__c.field-meta.xml
<CustomField>
    <fullName>Variedad__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Variedad</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1 AND 2</booleanFilter>
        <filterItems>
            <field>Variedad__c.Disponivel_para_venda_basica__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Variedad__c.Cultura__c</field>
            <operation>equals</operation>
            <value>MILHO</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Variedad__c</referenceTo>
    <relationshipLabel>Produtos de Requisição</relationshipLabel>
    <relationshipName>Produtos_de_Requisicao</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/Produto_de_Requisicao__c/recordTypes/Milho.recordType-meta.xml
<RecordType>
    <fullName>Milho</fullName>
    <active>true</active>
    <label>Milho</label>
</RecordType>

Salesforce/main/default/main/default/objects/Regiao__c/Regiao__c.object-meta.xml
<CustomObject>
    <label>Región</label>
    <nameField>
        <label>Nome da Região</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regiones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/objects/Regiao__c/fields/Region_Comercial__c.field-meta.xml
<CustomField>
    <fullName>Region_Comercial__c</fullName>
    <label>Region Comercial</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>REGION 1</fullName>
            </value>
            <value>
                <fullName>REGION 2</fullName>
            </value>
            <value>
                <fullName>CERRADO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Requisicao_de_compra__c/Requisicao_de_compra__c.object-meta.xml
<CustomObject>
    <label>Estimativas</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Número de requisito</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Estimativas</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Salesforce/main/default/objects/Requisicao_de_compra__c/fields/Cultura__c.field-meta.xml
<CustomField>
    <fullName>Cultura__c</fullName>
    <label>Cultura</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/Requisicao_de_compra__c/fields/Multiplicador__c.field-meta.xml
<CustomField>
    <fullName>Multiplicador__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Multiplicador</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Requisitos_de_compra</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Requisicao_de_compra__c/fields/Regiao__c.field-meta.xml
<CustomField>
    <fullName>Regiao__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Região</label>
    <referenceTo>Regiao__c</referenceTo>
    <relationshipName>Requisiaos_de_compra</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/Requisicao_de_compra__c/fields/Requisicao_de_compra__c.field-meta.xml
<CustomField>
    <fullName>Requisicao_de_compra__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Número da Estimativa Subsequente</label>
    <referenceTo>Requisicao_de_compra__c</referenceTo>
    <relationshipName>Requisitos_de_compra</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Requisicao_de_compra__c/fields/Supervisor__c.field-meta.xml
<CustomField>
    <fullName>Supervisor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supervisor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Estimativas</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Requisicao_de_compra__c/recordTypes/Milho.recordType-meta.xml
<RecordType>
    <fullName>Milho</fullName>
    <active>true</active>
    <label>Milho</label>
</RecordType>

Salesforce/main/default/main/default/objects/Variedad__c/Variedad__c.object-meta.xml
<CustomObject>
    <description>Variedades, disponibles para incluir en los Contratos de Multiplicación</description>
    <label>Variedad</label>
    <nameField>
        <label>Nome Comercial</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Variedades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/Variedad__c/fields/Cultura__c.field-meta.xml
<CustomField>
    <fullName>Cultura__c</fullName>
    <label>Cultura</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SOJA</fullName>
            </value>
            <value>
                <fullName>MILHO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Variedad__c/fields/Disponivel_para_venda_basica__c.field-meta.xml
<CustomField>
    <fullName>Disponivel_para_venda_basica__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Disponivel para venda basica</label>
    <type>Checkbox</type>
</CustomField>

Salesforce/main/default/main/default/objects/Variedad__c/fields/Marca_comercial__c.field-meta.xml
<CustomField>
    <fullName>Marca_comercial__c</fullName>
    <label>Marca comercial</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DM Sementes</fullName>
                <label>DONMARIO</label>
            </value>
            <value>
                <fullName>Brasmax</fullName>
                <label>BRASMAX</label>
            </value>
            <value>
                <fullName>Neogen</fullName>
                <label>NEOGEN</label>
            </value>
            <value>
                <fullName>Dagma</fullName>
                <label>DAGMA</label>
            </value>
            <value>
                <fullName>Licenças</fullName>
                <label>LICENÇAS</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Variedad__c/fields/Nombre_de_Registro__c.field-meta.xml
<CustomField>
    <fullName>Nombre_de_Registro__c</fullName>
    <externalId>true</externalId>
    <label>Nombre de Registro</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/Variedad__c/fields/Regiao_disponivel_para_venda_basica__c.field-meta.xml
<CustomField>
    <fullName>Regiao_disponivel_para_venda_basica__c</fullName>
    <label>Região disponível para venda básica</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>REGION 1</fullName>
            </value>
            <value>
                <fullName>REGION 2</fullName>
            </value>
            <value>
                <fullName>CERRADO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/globalValueSets/Marca.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BRMX</fullName>
    </customValue>
    <customValue>
        <fullName>DSEM</fullName>
    </customValue>
    <customValue>
        <fullName>NEOG</fullName>
    </customValue>
    <customValue>
        <fullName>DAGMA</fullName>
    </customValue>
    <customValue>
        <fullName>LICENÇAS</fullName>
    </customValue>
    <masterLabel>Marca</masterLabel>
</GlobalValueSet>

Salesforce/main/default/globalValueSets/Safra.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>14/15</fullName>
    </customValue>
    <customValue>
        <fullName>15/16</fullName>
    </customValue>
    <customValue>
        <fullName>16/17</fullName>
    </customValue>
    <customValue>
        <fullName>17/18</fullName>
    </customValue>
    <customValue>
        <fullName>18/19</fullName>
    </customValue>
    <customValue>
        <fullName>19/20</fullName>
    </customValue>
    <customValue>
        <fullName>20/21</fullName>
    </customValue>
    <customValue>
        <fullName>21/22</fullName>
    </customValue>
    <customValue>
        <fullName>22/23</fullName>
    </customValue>
    <customValue>
        <fullName>23/24</fullName>
    </customValue>
    <customValue>
        <fullName>08/09</fullName>
        <isActive>false</isActive>
        <label>08/09</label>
    </customValue>
    <customValue>
        <fullName>07/08</fullName>
        <isActive>false</isActive>
        <label>07/08</label>
    </customValue>
    <customValue>
        <fullName>10/11</fullName>
        <isActive>false</isActive>
        <label>10/11</label>
    </customValue>
    <customValue>
        <fullName>11/12</fullName>
        <isActive>false</isActive>
        <label>11/12</label>
    </customValue>
    <customValue>
        <fullName>12/13</fullName>
        <isActive>false</isActive>
        <label>12/13</label>
    </customValue>
    <customValue>
        <fullName>13/14</fullName>
        <isActive>false</isActive>
        <label>13/14</label>
    </customValue>
    <customValue>
        <fullName>09/10</fullName>
        <isActive>false</isActive>
        <label>09/10</label>
    </customValue>
    <masterLabel>Safra</masterLabel>
</GlobalValueSet>

Salesforce/main/default/main/default/classes/SalvarEstimativaAPITest.cls
/**
* @name SalvarEstimativaAPITest
* @author Jhonny Peroza
* updated 08-11-2021
*
* UPDATED  26-Jan-2022  pablo.fraquia@cloudgaia.com /  Se actualizan y agregan métodos acorde a los requerimientos de  BUG-18829
*/

@isTest
public class SalvarEstimativaAPITest {

    final static String MARCA = 'BRMX';
    final static String MARCACOMERCIAL = 'Brasmax';
    final static String TIPO = 'Multiplicador';
    final static String REGIONCOMERCIAL = 'REGION 1';
 
    @TestSetup
    static void makeData(){

        Configuracion_BMX__c testConfig = new Configuracion_BMX__c(Name = 'Test Facturacion',
                                                                   CRM_Safra_Actual__c = '21/22',
                                                                   PM_Safra_Actual_VB_Estimativa_de_Compra__c = '21/22'
                                                                   );
        insert testConfig;
        
        Regiao__c testRegion = new Regiao__c(Name = 'REGION 1',
                                             Region_Comercial__c = 'REGION 1'
                                             );
        insert testRegion;
            
        List<Account> accList = new List<Account>();

        accList.add(new Account(Name = 'Test Account 1', 
                                Region__c = testRegion.Id, 
                                Supervisor__c = UserInfo.getUserId(),
                                Responsavel__c = '104 - Otavio Gorni'
                                ));

        accList.add(new Account(Name = 'Test Account 2', 
                                Region__c = testRegion.Id,
                                Supervisor__c = UserInfo.getUserId(),
                                Responsavel__c = '104 - Otavio Gorni'
                                ));
                                
        insert accList;
        
        List<Variedad__c> varietyList = new List<Variedad__c>();

        varietyList.add(new Variedad__c(Name = 'Test Variedad 1',
                                        Nombre_de_Registro__c = 'Test Variedad 1',
                                        Marca_comercial__c = MARCACOMERCIAL,
                                        Ativa__c = true,
                                        Regiao_disponivel_para_venda_basica__c = 'REGION 1;REGION 2;CERRADO',
                                        Disponivel_para_venda_basica__c = true,
                                        Cultura__c = 'MILHO'
                                        ));

        varietyList.add(new Variedad__c(Name = 'Test Variedad 2',
                                        Nombre_de_Registro__c = 'Test Variedad 2',
                                        Marca_comercial__c = MARCACOMERCIAL,
                                        Ativa__c = true,
                                        Regiao_disponivel_para_venda_basica__c = 'REGION 1;REGION 2;CERRADO',
                                        Disponivel_para_venda_basica__c = true,
                                        Cultura__c = 'MILHO'
                                        ));
                                        
        varietyList.add(new Variedad__c(Name = 'Test Variedad 3',
                                        Nombre_de_Registro__c = 'Test Variedad 3',
                                        Marca_comercial__c = MARCACOMERCIAL,
                                        Ativa__c = true,
                                        Regiao_disponivel_para_venda_basica__c = 'REGION 1;REGION 2;CERRADO',
                                        Disponivel_para_venda_basica__c = true,
                                        Cultura__c = 'MILHO'
                                        ));
                                        
        insert varietyList;
        
        Requisicao_de_compra__c testRequisicao = new Requisicao_de_compra__c(Multiplicador__c = accList[1].Id,
                                                                             Marca__c = MARCA,
                                                                             Safra__c = testConfig.PM_Safra_Actual_VB_Estimativa_de_Compra__c,
                                                                             Tipo__c = TIPO,
                                                                             Regiao_comercial__c = REGIONCOMERCIAL
                                                                             );

        insert testRequisicao;                                                                     

        List<Produto_de_Requisicao__c> tesProductList = new List<Produto_de_Requisicao__c>();
        
        tesProductList.add(new Produto_de_Requisicao__c(Quantidade__c = 10,
                                                        Variedad__c = varietyList[0].Id,
                                                        Requisicao_de_compra__c = testRequisicao.Id
                                                        ));

        tesProductList.add(new Produto_de_Requisicao__c(Quantidade__c = 20,
                                                        Variedad__c = varietyList[1].Id,
                                                        Requisicao_de_compra__c = testRequisicao.Id
                                                        ));
                                                        
        insert tesProductList;                                       
    }

    @isTest
    public static void saveEstimativaProductsTest() {

        List<Atributo_venda_de_basica__mdt> supportTierList = [SELECT Id, Marca__c, Usuario_Gerente_de_Marca__c FROM Atributo_venda_de_basica__mdt];

        Configuracion_BMX__c testConfig = [SELECT Id, Name, PM_Safra_Actual_VB_Estimativa_de_Compra__c FROM Configuracion_BMX__c WHERE Name = 'Test Facturacion' LIMIT 1];

        Account testAccount = [SELECT Id, Name, Region_comercial__c FROM Account WHERE Name = 'Test account 1' LIMIT 1];

        List<Variedad__c> testVarietyList = [SELECT Id, Name FROM Variedad__c WHERE Name IN ('Test Variedad 1','Test Variedad 2') LIMIT 2];
       
        List<aSiteVendaDeBasicaController.ProductoRequisicion> testItems = new List<aSiteVendaDeBasicaController.ProductoRequisicion>();

        aSiteVendaDeBasicaController.ProductoRequisicion item1 = new aSiteVendaDeBasicaController.ProductoRequisicion();

        item1.cantidad=10;
        item1.variedadId = testVarietyList[0].Id;
        testItems.add(item1);

        aSiteVendaDeBasicaController.ProductoRequisicion item2 = new aSiteVendaDeBasicaController.ProductoRequisicion();

        item2.cantidad=20;
        item2.variedadId = testVarietyList[1].Id;
        testItems.add(item2);
        
        List<aSiteVendaDeBasicaController.ProductoRequisicion> emptyList = new List<aSiteVendaDeBasicaController.ProductoRequisicion>();

        SalvarEstimativaAPI.response result;
        SalvarEstimativaAPI.Request requestBody = new SalvarEstimativaAPI.Request();

        requestBody.items = testItems;
        requestBody.itemsToRemove = emptyList;
        requestBody.requisicaoId = null;
        requestBody.multiplicadorId = testAccount.Id;
        requestBody.marca = MARCA;
        requestBody.tipo = TIPO;
        requestBody.regiaoComercial = REGIONCOMERCIAL;
        requestBody.paraAprobacion = true;

        RestResponse resp = new RestResponse();
        RestRequest req = new RestRequest(); 
        
        req.requestURI = '/services/apexrest/SalvarEstimativaAPI/';  
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueof(JSON.serialize(requestBody));

        RestContext.request = req;
        RestContext.response = resp;

        test.startTest();
        SalvarEstimativaAPI.salvarEstimativa();
        test.stopTest();

        result = (SalvarEstimativaAPI.response)JSON.deserialize(resp.responseBody.toString(), SalvarEstimativaAPI.response.class);
      	
        System.assertEquals(true, result.status);
        System.assertEquals(result.message, Label.SalvarEstimativaAPI_Success_Message);
        System.assertNotEquals(null, result.id);
    }

    @isTest
    public static void editEstimativaProductsTest() {

        List<Atributo_venda_de_basica__mdt> supportTierList = [SELECT Id, Marca__c, Usuario_Gerente_de_Marca__c FROM Atributo_venda_de_basica__mdt];

        Configuracion_BMX__c testConfig = [SELECT Id, Name, PM_Safra_Actual_VB_Estimativa_de_Compra__c FROM Configuracion_BMX__c WHERE Name = 'Test Facturacion' LIMIT 1];


        Account testAccount = [SELECT Id, Name, Region_comercial__c FROM Account WHERE Name = 'Test account 2' LIMIT 1];

        Requisicao_de_compra__c testRequisicao = [SELECT Id FROM Requisicao_de_compra__c WHERE Multiplicador__c = :testAccount.Id LIMIT 1];

        List<Variedad__c> testVarietyList = [SELECT Id, Name FROM Variedad__c WHERE Name IN ('Test Variedad 1','Test Variedad 2') LIMIT 2];
       
        List<aSiteVendaDeBasicaController.ProductoRequisicion> testItems = new List<aSiteVendaDeBasicaController.ProductoRequisicion>();

        aSiteVendaDeBasicaController.ProductoRequisicion item1 = new aSiteVendaDeBasicaController.ProductoRequisicion();

        item1.cantidad=100;
        item1.variedadId = testVarietyList[0].Id;
        testItems.add(item1);

        aSiteVendaDeBasicaController.ProductoRequisicion item2 = new aSiteVendaDeBasicaController.ProductoRequisicion();

        item2.cantidad=200;
        item2.variedadId = testVarietyList[1].Id;
        testItems.add(item2);  
        
        List<aSiteVendaDeBasicaController.ProductoRequisicion> emptyList = new List<aSiteVendaDeBasicaController.ProductoRequisicion>();

        SalvarEstimativaAPI.response result;
        SalvarEstimativaAPI.Request requestBody = new SalvarEstimativaAPI.Request();

        requestBody.items = testItems;
        requestBody.itemsToRemove = emptyList;
        requestBody.requisicaoId = testRequisicao.Id;
        requestBody.multiplicadorId = testAccount.Id;
        requestBody.marca = MARCA;
        requestBody.tipo = TIPO;
        requestBody.regiaoComercial = REGIONCOMERCIAL;
        requestBody.paraAprobacion = true;

        RestResponse resp = new RestResponse();
        RestRequest req = new RestRequest(); 
        
        req.requestURI = '/services/apexrest/SalvarEstimativaAPI/';  
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueof(JSON.serialize(requestBody));

        RestContext.request = req;
        RestContext.response = resp;

        test.startTest();
        SalvarEstimativaAPI.salvarEstimativa();
        test.stopTest();

        Requisicao_de_compra__c testUpdatedRequisicao = [SELECT Id, Cantidad_Productos__c FROM Requisicao_de_compra__c WHERE Multiplicador__c = :testAccount.Id LIMIT 1];

        List<Produto_de_Requisicao__c> tesProductList = [SELECT Id, Quantidade__c, Variedad__c  FROM Produto_de_Requisicao__c WHERE Requisicao_de_compra__c = :testUpdatedRequisicao.Id LIMIT 2];

        result = (SalvarEstimativaAPI.response)JSON.deserialize(resp.responseBody.toString(), SalvarEstimativaAPI.response.class);
      	
        System.assertEquals(true, result.status);
        System.assertEquals(result.message, Label.SalvarEstimativaAPI_Success_Message);
        System.assertEquals(testUpdatedRequisicao.Id, result.id);
        System.assertEquals(2, testUpdatedRequisicao.Cantidad_Productos__c);
        System.assertEquals(100, tesProductList[0].Quantidade__c);
    }

    @isTest
    public static void editEstimativaDeleteProductsTest() {

        List<Atributo_venda_de_basica__mdt> supportTierList = [SELECT Id, Marca__c, Usuario_Gerente_de_Marca__c FROM Atributo_venda_de_basica__mdt];

        Configuracion_BMX__c testConfig = [SELECT Id, Name, PM_Safra_Actual_VB_Estimativa_de_Compra__c FROM Configuracion_BMX__c WHERE Name = 'Test Facturacion' LIMIT 1];

        Account testAccount = [SELECT Id, Name, Region_comercial__c FROM Account WHERE Name = 'Test account 2' LIMIT 1];

        Requisicao_de_compra__c testRequisicao = [SELECT Id, Cantidad_Productos__c FROM Requisicao_de_compra__c WHERE Multiplicador__c = :testAccount.Id LIMIT 1];

        System.assertEquals(2, testRequisicao.Cantidad_Productos__c);

        List<Variedad__c> testVarietyList = [SELECT Id, Name FROM Variedad__c WHERE Name IN ('Test Variedad 1','Test Variedad 2') LIMIT 2];
       
        List<aSiteVendaDeBasicaController.ProductoRequisicion> testItems = new List<aSiteVendaDeBasicaController.ProductoRequisicion>();

        aSiteVendaDeBasicaController.ProductoRequisicion item1 = new aSiteVendaDeBasicaController.ProductoRequisicion();

        item1.cantidad=100;
        item1.variedadId = testVarietyList[0].Id;
        testItems.add(item1);      
        
        List<aSiteVendaDeBasicaController.ProductoRequisicion> testItemsToRemove = new List<aSiteVendaDeBasicaController.ProductoRequisicion>();

        aSiteVendaDeBasicaController.ProductoRequisicion item2 = new aSiteVendaDeBasicaController.ProductoRequisicion();

        item2.variedadId = testVarietyList[1].Id;
        testItemsToRemove.add(item2);  

        SalvarEstimativaAPI.response result;
        SalvarEstimativaAPI.Request requestBody = new SalvarEstimativaAPI.Request();

        requestBody.items = testItems;
        requestBody.itemsToRemove = testItemsToRemove;
        requestBody.requisicaoId = testRequisicao.Id;
        requestBody.multiplicadorId = testAccount.Id;
        requestBody.marca = MARCA;
        requestBody.tipo = TIPO;
        requestBody.regiaoComercial = REGIONCOMERCIAL;
        requestBody.paraAprobacion = true;

        RestResponse resp = new RestResponse();
        RestRequest req = new RestRequest(); 
        
        req.requestURI = '/services/apexrest/SalvarEstimativaAPI/';  
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueof(JSON.serialize(requestBody));

        RestContext.request = req;
        RestContext.response = resp;

        test.startTest();
        SalvarEstimativaAPI.salvarEstimativa();
        test.stopTest();

        Requisicao_de_compra__c testUpdatedRequisicao = [SELECT Id, Cantidad_Productos__c FROM Requisicao_de_compra__c WHERE Multiplicador__c = :testAccount.Id LIMIT 1];

        List<Produto_de_Requisicao__c> tesProductList = [SELECT Id, Quantidade__c, Variedad__c  FROM Produto_de_Requisicao__c WHERE Requisicao_de_compra__c = :testUpdatedRequisicao.Id LIMIT 2];

        result = (SalvarEstimativaAPI.response)JSON.deserialize(resp.responseBody.toString(), SalvarEstimativaAPI.response.class);
      	
        System.assertEquals(true, result.status);
        System.assertEquals(result.message, Label.SalvarEstimativaAPI_Success_Message);
        System.assertEquals(testUpdatedRequisicao.Id, result.id);
        System.assertEquals(1, testUpdatedRequisicao.Cantidad_Productos__c);
        System.assertEquals(100, tesProductList[0].Quantidade__c);
    }

    @isTest
    public static void editEstimativaAddProductTest() {

        List<Atributo_venda_de_basica__mdt> supportTierList = [SELECT Id, Marca__c, Usuario_Gerente_de_Marca__c FROM Atributo_venda_de_basica__mdt];

        Configuracion_BMX__c testConfig = [SELECT Id, Name, PM_Safra_Actual_VB_Estimativa_de_Compra__c FROM Configuracion_BMX__c WHERE Name = 'Test Facturacion' LIMIT 1];

        Account testAccount = [SELECT Id, Name, Region_comercial__c FROM Account WHERE Name = 'Test account 2' LIMIT 1];

        Requisicao_de_compra__c testRequisicao = [SELECT Id, Cantidad_Productos__c FROM Requisicao_de_compra__c WHERE Multiplicador__c = :testAccount.Id LIMIT 1];

        System.assertEquals(2, testRequisicao.Cantidad_Productos__c);

        List<Variedad__c> testVarietyList = [SELECT Id, Name FROM Variedad__c WHERE Name IN ('Test Variedad 1','Test Variedad 2', 'Test Variedad 3')];
       
        List<aSiteVendaDeBasicaController.ProductoRequisicion> testItems = new List<aSiteVendaDeBasicaController.ProductoRequisicion>();

        aSiteVendaDeBasicaController.ProductoRequisicion item1 = new aSiteVendaDeBasicaController.ProductoRequisicion();

        item1.cantidad=10;
        item1.variedadId = testVarietyList[0].Id;
        testItems.add(item1);

        aSiteVendaDeBasicaController.ProductoRequisicion item2 = new aSiteVendaDeBasicaController.ProductoRequisicion();

        item2.cantidad=20;
        item2.variedadId = testVarietyList[1].Id;
        testItems.add(item2);   
        
        aSiteVendaDeBasicaController.ProductoRequisicion item3 = new aSiteVendaDeBasicaController.ProductoRequisicion();

        item3.cantidad=30;
        item3.variedadId = testVarietyList[2].Id;
        testItems.add(item3);

        List<aSiteVendaDeBasicaController.ProductoRequisicion> emptyList = new List<aSiteVendaDeBasicaController.ProductoRequisicion>();

        SalvarEstimativaAPI.response result;
        SalvarEstimativaAPI.Request requestBody = new SalvarEstimativaAPI.Request();

        requestBody.items = testItems;
        requestBody.itemsToRemove = emptyList;
        requestBody.requisicaoId = testRequisicao.Id;
        requestBody.multiplicadorId = testAccount.Id;
        requestBody.marca = MARCA;
        requestBody.tipo = TIPO;
        requestBody.regiaoComercial = REGIONCOMERCIAL;
        requestBody.paraAprobacion = true;

        RestResponse resp = new RestResponse();
        RestRequest req = new RestRequest(); 
        
        req.requestURI = '/services/apexrest/SalvarEstimativaAPI/';  
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueof(JSON.serialize(requestBody));

        RestContext.request = req;
        RestContext.response = resp;

        test.startTest();
        SalvarEstimativaAPI.salvarEstimativa();
        test.stopTest();

        Requisicao_de_compra__c testUpdatedRequisicao = [SELECT Id, Cantidad_Productos__c FROM Requisicao_de_compra__c WHERE Multiplicador__c = :testAccount.Id LIMIT 1];

        result = (SalvarEstimativaAPI.response)JSON.deserialize(resp.responseBody.toString(), SalvarEstimativaAPI.response.class);
      	
        System.assertEquals(true, result.status);
        System.assertEquals(result.message, Label.SalvarEstimativaAPI_Success_Message);
        System.assertEquals(testUpdatedRequisicao.Id, result.id);
        System.assertEquals(3, testUpdatedRequisicao.Cantidad_Productos__c);

    }
    
    @isTest
    public static void editEstimativaEmptyProductTest() {

        List<Atributo_venda_de_basica__mdt> supportTierList = [SELECT Id, Marca__c, Usuario_Gerente_de_Marca__c FROM Atributo_venda_de_basica__mdt];

        Configuracion_BMX__c testConfig = [SELECT Id, Name, PM_Safra_Actual_VB_Estimativa_de_Compra__c FROM Configuracion_BMX__c WHERE Name = 'Test Facturacion' LIMIT 1];

        Account testAccount = [SELECT Id, Name, Region_comercial__c FROM Account WHERE Name = 'Test account 2' LIMIT 1];

        Requisicao_de_compra__c testRequisicao = [SELECT Id, Cantidad_Productos__c FROM Requisicao_de_compra__c WHERE Multiplicador__c = :testAccount.Id LIMIT 1];

        System.assertEquals(2, testRequisicao.Cantidad_Productos__c);

        List<Produto_de_Requisicao__c> tesProductList = [SELECT Id, Quantidade__c, Variedad__c  FROM Produto_de_Requisicao__c WHERE Requisicao_de_compra__c = :testRequisicao.Id];

        delete tesProductList;

        Requisicao_de_compra__c testEmptyRequisicao = [SELECT Id, Cantidad_Productos__c FROM Requisicao_de_compra__c WHERE Multiplicador__c = :testAccount.Id LIMIT 1];

        System.assertEquals(0, testEmptyRequisicao.Cantidad_Productos__c);

        List<Variedad__c> testVarietyList = [SELECT Id, Name FROM Variedad__c WHERE Name IN ('Test Variedad 1','Test Variedad 2', 'Test Variedad 3') LIMIT 3];
       
        List<aSiteVendaDeBasicaController.ProductoRequisicion> testItems = new List<aSiteVendaDeBasicaController.ProductoRequisicion>();

        aSiteVendaDeBasicaController.ProductoRequisicion item1 = new aSiteVendaDeBasicaController.ProductoRequisicion();

        item1.cantidad=10;
        item1.variedadId = testVarietyList[0].Id;
        testItems.add(item1);

        aSiteVendaDeBasicaController.ProductoRequisicion item2 = new aSiteVendaDeBasicaController.ProductoRequisicion();

        item2.cantidad=20;
        item2.variedadId = testVarietyList[1].Id;
        testItems.add(item2);   
        
        aSiteVendaDeBasicaController.ProductoRequisicion item3 = new aSiteVendaDeBasicaController.ProductoRequisicion();

        item2.cantidad=30;
        item2.variedadId = testVarietyList[2].Id;
        testItems.add(item2);

        List<aSiteVendaDeBasicaController.ProductoRequisicion> emptyList = new List<aSiteVendaDeBasicaController.ProductoRequisicion>();

        SalvarEstimativaAPI.response result;
        SalvarEstimativaAPI.Request requestBody = new SalvarEstimativaAPI.Request();

        requestBody.items = testItems;
        requestBody.itemsToRemove = emptyList;
        requestBody.requisicaoId = testRequisicao.Id;
        requestBody.multiplicadorId = testAccount.Id;
        requestBody.marca = MARCA;
        requestBody.tipo = TIPO;
        requestBody.regiaoComercial = REGIONCOMERCIAL;
        requestBody.paraAprobacion = true;

        RestResponse resp = new RestResponse();
        RestRequest req = new RestRequest(); 
        
        req.requestURI = '/services/apexrest/SalvarEstimativaAPI/';  
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueof(JSON.serialize(requestBody));

        RestContext.request = req;
        RestContext.response = resp;

        test.startTest();
        SalvarEstimativaAPI.salvarEstimativa();
        test.stopTest();

        Requisicao_de_compra__c testUpdatedRequisicao = [SELECT Id, Cantidad_Productos__c FROM Requisicao_de_compra__c WHERE Multiplicador__c = :testAccount.Id LIMIT 1];

        result = (SalvarEstimativaAPI.response)JSON.deserialize(resp.responseBody.toString(), SalvarEstimativaAPI.response.class);
      	
        System.assertEquals(true, result.status);
        System.assertEquals(result.message, Label.SalvarEstimativaAPI_Success_Message);
        System.assertEquals(testUpdatedRequisicao.Id, result.id);
        System.assertEquals(3, testUpdatedRequisicao.Cantidad_Productos__c);

    }

    @isTest
    public static void estimativeCouldNotBeSaved() {
	
        List<Atributo_venda_de_basica__mdt> supportTierList = [SELECT Id, Marca__c, Usuario_Gerente_de_Marca__c FROM Atributo_venda_de_basica__mdt];

        Configuracion_BMX__c testConfig = [SELECT Id, Name, PM_Safra_Actual_VB_Estimativa_de_Compra__c FROM Configuracion_BMX__c WHERE Name = 'Test Facturacion' LIMIT 1];


        Account testAccount = [SELECT Id, Name, Region_comercial__c FROM Account WHERE Name = 'Test account 1' LIMIT 1];

        List<Variedad__c> testVarietyList = [SELECT Id, Name FROM Variedad__c WHERE Name IN ('Test Variedad 1','Test Variedad 2') LIMIT 2];
       
        List<aSiteVendaDeBasicaController.ProductoRequisicion> testItems = new List<aSiteVendaDeBasicaController.ProductoRequisicion>();

        aSiteVendaDeBasicaController.ProductoRequisicion item1 = new aSiteVendaDeBasicaController.ProductoRequisicion();

        item1.cantidad=10;
        item1.variedadId = testVarietyList[0].Id;
        testItems.add(item1);
        
        List<aSiteVendaDeBasicaController.ProductoRequisicion> emptyList = new List<aSiteVendaDeBasicaController.ProductoRequisicion>();

        SalvarEstimativaAPI.response result;
        SalvarEstimativaAPI.Request requestBody = new SalvarEstimativaAPI.Request();

        requestBody.items = testItems;
        requestBody.itemsToRemove = emptyList;
        requestBody.requisicaoId = 'a1T0x000000XxxxXXX';
        requestBody.multiplicadorId = testAccount.Id;
        requestBody.marca = MARCA;
        requestBody.tipo = TIPO;
        requestBody.regiaoComercial = REGIONCOMERCIAL;
        requestBody.paraAprobacion = true;

		RestResponse resp = new RestResponse();
        RestRequest req = new RestRequest(); 
        
        req.requestURI = '/services/apexrest/SalvarEstimativaAPI/';  
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueof(JSON.serialize(requestBody));

        RestContext.request = req;
        RestContext.response = resp;

        test.startTest();
        SalvarEstimativaAPI.salvarEstimativa();
        test.stopTest();
        
        result = (SalvarEstimativaAPI.response)JSON.deserialize(resp.responseBody.toString(), SalvarEstimativaAPI.response.class);
      	
        System.assertEquals(false, result.status);
        System.assertNotEquals(result.message, Label.SalvarEstimativaAPI_Success_Message);
    }

    @isTest
    public static void estimativeCouldNotBeSubmitedForApproval() {
	
        List<Atributo_venda_de_basica__mdt> supportTierList = [SELECT Id, Marca__c, Usuario_Gerente_de_Marca__c FROM Atributo_venda_de_basica__mdt];

        Configuracion_BMX__c testConfig = [SELECT Id, Name, PM_Safra_Actual_VB_Estimativa_de_Compra__c FROM Configuracion_BMX__c WHERE Name = 'Test Facturacion' LIMIT 1];


        Account testAccount = [SELECT Id, Name, Region_comercial__c FROM Account WHERE Name = 'Test account 1' LIMIT 1];

        List<Variedad__c> testVarietyList = [SELECT Id, Name FROM Variedad__c WHERE Name IN ('Test Variedad 1','Test Variedad 2') LIMIT 2];
       
        List<aSiteVendaDeBasicaController.ProductoRequisicion> testItemsToRemove = new List<aSiteVendaDeBasicaController.ProductoRequisicion>();

        aSiteVendaDeBasicaController.ProductoRequisicion item1 = new aSiteVendaDeBasicaController.ProductoRequisicion();

        item1.variedadId = testVarietyList[0].Id;
        testItemsToRemove.add(item1);
        
        aSiteVendaDeBasicaController.ProductoRequisicion item2 = new aSiteVendaDeBasicaController.ProductoRequisicion();

        
        item2.variedadId = testVarietyList[1].Id;
        testItemsToRemove.add(item2); 

        List<aSiteVendaDeBasicaController.ProductoRequisicion> emptyList = new List<aSiteVendaDeBasicaController.ProductoRequisicion>();

        SalvarEstimativaAPI.response result;
        SalvarEstimativaAPI.Request requestBody = new SalvarEstimativaAPI.Request();

        requestBody.items = emptyList;
        requestBody.itemsToRemove = testItemsToRemove;
        requestBody.requisicaoId = testAccount.Id;
        requestBody.multiplicadorId = testAccount.Id;
        requestBody.marca = MARCA;
        requestBody.tipo = TIPO;
        requestBody.regiaoComercial = REGIONCOMERCIAL;
        requestBody.paraAprobacion = true;

		RestResponse resp = new RestResponse();
        RestRequest req = new RestRequest(); 
        
        req.requestURI = '/services/apexrest/SalvarEstimativaAPI/';  
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueof(JSON.serialize(requestBody));

        RestContext.request = req;
        RestContext.response = resp;

        test.startTest();
        SalvarEstimativaAPI.salvarEstimativa();
        test.stopTest();
        
        result = (SalvarEstimativaAPI.response)JSON.deserialize(resp.responseBody.toString(), SalvarEstimativaAPI.response.class);
      	
        System.assertEquals(false, result.status);
        System.assertNotEquals(result.message, Label.SalvarEstimativaAPI_Products_Quantity_Error_Message);
    }
}