Salesforce/main/default/objects/Account/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Marca</valueSetName>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Account/fields/Nome_fantasia__c.field-meta.xml
<CustomField>
    <fullName>Nome_fantasia__c</fullName>
    <label>Nome fantasia</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/Opportunity/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <description>Identifica la marca para las Oportunidades del Circuito de Anexos. Se selecciona la lista de precios en función de este campo</description>
    <inlineHelpText>Identificar a marca de Oportunidades Circuito Anexos. Você seleciona a lista de preços com base neste campo</inlineHelpText>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BRMX</fullName>
            </value>
            <value>
                <fullName>DSEM</fullName>
            </value>
            <value>
                <fullName>NEOG</fullName>
            </value>
            <value>
                <fullName>DAGMA</fullName>
            </value>
            <value>
                <fullName>LICENÇAS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Opportunity/fields/Next_Step__c.field-meta.xml
<CustomField>
    <fullName>Next_Step__c</fullName>
    <label>Next Step</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/Opportunity/fields/tienePdf__c.field-meta.xml
<CustomField>
    <fullName>tienePdf__c</fullName>
    <defaultValue>false</defaultValue>
    <label>tienePdf</label>
    <type>Checkbox</type>
</CustomField>

Salesforce/main/default/globalValueSets/Marca.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BRMX</fullName>
    </customValue>
    <customValue>
        <fullName>DSEM</fullName>
    </customValue>
    <customValue>
        <fullName>NEOG</fullName>
    </customValue>
    <customValue>
        <fullName>DAGMA</fullName>
    </customValue>
    <customValue>
        <fullName>LICENÇAS</fullName>
    </customValue>
    <masterLabel>Marca</masterLabel>
</GlobalValueSet>

Salesforce/main/default/classes/PdfParaDescarte.cls
public class PdfParaDescarte  {

	@Future(Callout=true)
    public static void printDescarteAutorization(Id opId) {
        PageReference pdf = Page.PdfGeneratorTemplateDescarte;
		Opportunity op = [
            SELECT Id, Marca__c, Account.Nome_fantasia__c, tienePdf__c, Next_Step__c, Name
            FROM Opportunity 
            WHERE id = : opId
        ];
        pdf.getParameters().put('id',opId);

        Attachment attach = new Attachment();
        Blob body;

        try {
            body = pdf.getContent();
        } 
        catch (VisualforceException e) {
            body = Blob.valueOf('Some Text ' + e.getMessage());
        }
        attach.Body = body;

        attach.Name = op.Name + '_' + op.Marca__c + '_autorizacao_descarte.pdf';
        attach.IsPrivate = false;
        attach.ParentId = op.id;
        insert attach;
    }
}