Salesforce/main/default/objects/Account/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Marca</valueSetName>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Account/recordTypes/Cuenta.recordType-meta.xml
<RecordType>
    <fullName>Cuenta</fullName>
    <active>true</active>
    <label>Cuenta</label>
</RecordType>

Salesforce/main/default/main/default/objects/Categoria__c/Categoria__c.object-meta.xml
<CustomObject>
    <description>Categorías</description>
    <label>Categoria</label>
    <nameField>
        <label>Nombre de Categoría</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categorias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/objects/Opportunity/fields/Control_Stock_Multiplicadores__c.field-meta.xml
<CustomField>
    <fullName>Control_Stock_Multiplicadores__c</fullName>
    <label>Control Stock Multiplicadores</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Salesforce/main/default/objects/Opportunity/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <description>Identifica la marca para las Oportunidades del Circuito de Anexos. Se selecciona la lista de precios en función de este campo</description>
    <inlineHelpText>Identificar a marca de Oportunidades Circuito Anexos. Você seleciona a lista de preços com base neste campo</inlineHelpText>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BRMX</fullName>
            </value>
            <value>
                <fullName>DSEM</fullName>
            </value>
            <value>
                <fullName>NEOG</fullName>
            </value>
            <value>
                <fullName>DAGMA</fullName>
            </value>
            <value>
                <fullName>LICENÇAS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Opportunity/fields/Mes__c.field-meta.xml
<CustomField>
    <fullName>Mes__c</fullName>
    <description>Nombre del mes para identificar la oportunidad de control de stock.</description>
    <label>Mês</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Janeiro</fullName>
            </value>
            <value>
                <fullName>Fevereiro</fullName>
            </value>
            <value>
                <fullName>Março</fullName>
            </value>
            <value>
                <fullName>Abril</fullName>
            </value>
            <value>
                <fullName>Maio</fullName>
            </value>
            <value>
                <fullName>Junho</fullName>
            </value>
            <value>
                <fullName>Julho</fullName>
            </value>
            <value>
                <fullName>Agosto</fullName>
            </value>
            <value>
                <fullName>Setembro</fullName>
            </value>
            <value>
                <fullName>Outubro</fullName>
            </value>
            <value>
                <fullName>Novembro</fullName>
            </value>
            <value>
                <fullName>Dezembro</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Opportunity/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <description>Safra o Campania agricola</description>
    <label>Safra</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>06/07</fullName>
            </value>
            <value>
                <fullName>07/08</fullName>
            </value>
            <value>
                <fullName>08/09</fullName>
            </value>
            <value>
                <fullName>09/10</fullName>
            </value>
            <value>
                <fullName>09/09</fullName>
            </value>
            <value>
                <fullName>10/10</fullName>
            </value>
            <value>
                <fullName>10/11</fullName>
            </value>
            <value>
                <fullName>11/11</fullName>
            </value>
            <value>
                <fullName>11/12</fullName>
            </value>
            <value>
                <fullName>12/12</fullName>
            </value>
            <value>
                <fullName>12/13</fullName>
            </value>
            <value>
                <fullName>13/14</fullName>
            </value>
            <value>
                <fullName>14/15</fullName>
            </value>
            <value>
                <fullName>15/16</fullName>
            </value>
            <value>
                <fullName>16/17</fullName>
            </value>
            <value>
                <fullName>17/18</fullName>
            </value>
            <value>
                <fullName>18/19</fullName>
            </value>
            <value>
                <fullName>19/20</fullName>
            </value>
            <value>
                <fullName>20/21</fullName>
            </value>
            <value>
                <fullName>21/22</fullName>
                <default>true</default>
                <label>21/22</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Opportunity/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ZB00 - BR Oferta</fullName>
            </value>
            <value>
                <fullName>ZCO - Oferta da Básica</fullName>
            </value>
            <value>
                <fullName>ZO00 - BR Cuenta y Orden</fullName>
            </value>
            <value>
                <fullName>ZO01 - BR Entrega Futura</fullName>
            </value>
            <value>
                <fullName>ZO02 - BR Venta Exportación</fullName>
            </value>
            <value>
                <fullName>ZO03 - BR Venta Futura</fullName>
            </value>
            <value>
                <fullName>ZO04 - BR Vta. s/entrega</fullName>
            </value>
            <value>
                <fullName>ZO05 - BR Vta. Almacenam.</fullName>
            </value>
            <value>
                <fullName>ZO07 - BR Entrega Muestra</fullName>
            </value>
            <value>
                <fullName>ZO08 - BR Regalías s/NF</fullName>
            </value>
            <value>
                <fullName>ZO09 - BR Regalías</fullName>
            </value>
            <value>
                <fullName>ZO10 - BR Material s/nombre</fullName>
            </value>
            <value>
                <fullName>ZO11 - BR Fidelización</fullName>
            </value>
            <value>
                <fullName>ZO12 - BR Venta Normal</fullName>
            </value>
            <value>
                <fullName>ZO13 - Ped. Exterior</fullName>
            </value>
            <value>
                <fullName>ZO14 - Ped.Local - Fc ref/Entr</fullName>
            </value>
            <value>
                <fullName>ZO15 - Ped.Local - Fc ref/Ped</fullName>
            </value>
            <value>
                <fullName>ZC01 - Solicit. Nota de Cred.</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Opportunity/recordTypes/Autorizada.recordType-meta.xml
<RecordType>
    <fullName>Autorizada</fullName>
    <active>true</active>
    <businessProcess>Nota de Venta - Autorizada</businessProcess>
    <label>Autorizada</label>
</RecordType>

Salesforce/main/default/main/default/objects/Opportunity/recordTypes/Previsao.recordType-meta.xml
<RecordType>
    <fullName>Previsao</fullName>
    <active>true</active>
    <businessProcess>Prevision Venta Basica</businessProcess>
    <description>Previsiones de Ventas de Bolsas de Básica</description>
    <label>Previsao</label>
</RecordType>

Salesforce/main/default/main/default/objects/OpportunityLineItem/fields/Base_de_Calculo__c.field-meta.xml
<CustomField>
    <fullName>Base_de_Calculo__c</fullName>
    <label>Base de Calculo</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/objects/OpportunityLineItem/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Categoria a ser licenciada</description>
    <inlineHelpText>Categoria a ser licenciada</inlineHelpText>
    <label>Categoria</label>
    <referenceTo>Categoria__c</referenceTo>
    <relationshipLabel>Producto de oportunidad</relationshipLabel>
    <relationshipName>Producto_de_oportunidad</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/OpportunityLineItem/fields/Previsao__c.field-meta.xml
<CustomField>
    <fullName>Previsao__c</fullName>
    <label>Previsão</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/objects/OpportunityLineItem/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <formula>TEXT(Opportunity.Safra__c)</formula>
    <label>Safra</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/OpportunityLineItem/fields/Semente_aprovada__c.field-meta.xml
<CustomField>
    <fullName>Semente_aprovada__c</fullName>
    <label>Sem. Aprovada (Sacas)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/main/default/objects/OpportunityLineItem/fields/Semente_comercializada__c.field-meta.xml
<CustomField>
    <fullName>Semente_comercializada__c</fullName>
    <label>Sem. Comercializada (Sacas)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/objects/OpportunityLineItem/fields/Tasas__c.field-meta.xml
<CustomField>
    <fullName>Tasas__c</fullName>
    <description>Tasas que se le descuentan al precio en los pedidos de royaltys ZPRE.</description>
    <label>Taxas</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/main/default/objects/Order/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Marca</valueSetName>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Order/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <label>Safra</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Safra</valueSetName>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Product2/fields/Categ__c.field-meta.xml
<CustomField>
    <fullName>Categ__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Categ</label>
    <referenceTo>Categoria__c</referenceTo>
    <relationshipLabel>Productos</relationshipLabel>
    <relationshipName>Productos</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Product2/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <label>Categoria</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BREEDER</fullName>
            </value>
            <value>
                <fullName>FUNDADORA</fullName>
            </value>
            <value>
                <fullName>Genetica</fullName>
            </value>
            <value>
                <fullName>Pre Basica</fullName>
            </value>
            <value>
                <fullName>BASICA</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>C1</fullName>
            </value>
            <value>
                <fullName>C2</fullName>
            </value>
            <value>
                <fullName>R</fullName>
            </value>
            <value>
                <fullName>S1</fullName>
            </value>
            <value>
                <fullName>S2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Product2/fields/Especie__c.field-meta.xml
<CustomField>
    <fullName>Especie__c</fullName>
    <label>Especie</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Soja</fullName>
                <label>SOJA</label>
            </value>
            <value>
                <fullName>Milho</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/globalValueSets/Marca.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BRMX</fullName>
    </customValue>
    <customValue>
        <fullName>DSEM</fullName>
    </customValue>
    <customValue>
        <fullName>NEOG</fullName>
    </customValue>
    <customValue>
        <fullName>DAGMA</fullName>
    </customValue>
    <customValue>
        <fullName>LICENÇAS</fullName>
    </customValue>
    <masterLabel>Marca</masterLabel>
</GlobalValueSet>

Salesforce/main/default/globalValueSets/Safra.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>14/15</fullName>
    </customValue>
    <customValue>
        <fullName>15/16</fullName>
    </customValue>
    <customValue>
        <fullName>16/17</fullName>
    </customValue>
    <customValue>
        <fullName>17/18</fullName>
    </customValue>
    <customValue>
        <fullName>18/19</fullName>
    </customValue>
    <customValue>
        <fullName>19/20</fullName>
    </customValue>
    <customValue>
        <fullName>20/21</fullName>
    </customValue>
    <customValue>
        <fullName>21/22</fullName>
    </customValue>
    <customValue>
        <fullName>22/23</fullName>
    </customValue>
    <customValue>
        <fullName>23/24</fullName>
    </customValue>
    <customValue>
        <fullName>08/09</fullName>
        <isActive>false</isActive>
        <label>08/09</label>
    </customValue>
    <customValue>
        <fullName>07/08</fullName>
        <isActive>false</isActive>
        <label>07/08</label>
    </customValue>
    <customValue>
        <fullName>10/11</fullName>
        <isActive>false</isActive>
        <label>10/11</label>
    </customValue>
    <customValue>
        <fullName>11/12</fullName>
        <isActive>false</isActive>
        <label>11/12</label>
    </customValue>
    <customValue>
        <fullName>12/13</fullName>
        <isActive>false</isActive>
        <label>12/13</label>
    </customValue>
    <customValue>
        <fullName>13/14</fullName>
        <isActive>false</isActive>
        <label>13/14</label>
    </customValue>
    <customValue>
        <fullName>09/10</fullName>
        <isActive>false</isActive>
        <label>09/10</label>
    </customValue>
    <masterLabel>Safra</masterLabel>
</GlobalValueSet>

Salesforce/main/default/main/default/classes/testOpp_Utils.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class testOpp_Utils {

    static void test() {
            
        Product2 px1 = new Product2(Name = 'Test 1', Especie__c = 'SOJA');//BORRAR
        insert px1;
        //////Product2 px2 = new Product2(Name = 'Test 1', tipo__c = 'SEM', Especie__c = 'TRIGO');
        Product2 px2 = new Product2(Name = 'Test 1', Especie__c = 'TRIGO');//BORRAR
        insert px2;
        
        Pricebook2 s = [select ID from Pricebook2 where IsStandard = TRUE];
        PricebookEntry pbesx = new PricebookEntry(Pricebook2Id=s.ID,Product2Id=px1.ID, UnitPrice=0.00, IsActive=TRUE, UseStandardPrice=FALSE);
        insert pbesx;
        PricebookEntry pbesx2 = new PricebookEntry(Pricebook2Id=s.ID,Product2Id=px2.ID, UnitPrice=0.00, IsActive=TRUE, UseStandardPrice=FALSE);
        insert pbesx2;
        
        //////Opportunity o = new Opportunity(Name = 'Test 1', Tipo__c = 'ZPLO - PEDIDO CON PAGO EN ESPECIE', CloseDate = System.today(), StageName = 'Clientes potenciales');
        //BORRAR
        Opportunity o = new Opportunity(Name = 'COPIA 154', CloseDate = System.today(), StageName = 'Clientes potenciales');
        //BORRAR
        test.starttest();
        insert o;
        OpportunityLineItem opli1 = new OpportunityLineItem(OpportunityId = o.id, PricebookEntryId = pbesx.id, unitPrice = 10, quantity = 1);
        insert opli1;
        OpportunityLineItem opli2 = new OpportunityLineItem(OpportunityId = o.id, PricebookEntryId = pbesx2.id, unitPrice = 10, quantity = 1); 
        insert opli2;
        test.stoptest();
        
        Opp_Utils.DuplicarPedido (o.Id);
        
    }
    @isTest(SeeAllData=true)
    static void test2() {
            
        Categoria__c cat = [SELECT Id, Name FROM Categoria__c WHERE Name = 'BASICA' limit 1];
        RecordType rt_prev = [Select Id From RecordType Where Name = 'Stock Multiplicadores' And SObjectType = 'Opportunity' limit 1];
        Account cuenta = [Select Id From Account Where Name = 'ACME' limit 1];
        Pricebook2 pb = [Select Id, Name From Pricebook2 where Name = 'Lista de Básica BMX SUL' and isActive = true limit 1];
        Opportunity prevision = New Opportunity(RecordTypeId=rt_prev.Id, Name='Previsao', AccountId = cuenta.Id,Pricebook2Id=pb.Id, CloseDate=System.today(), Marca__c='BRMX',StageName='Aberta', Safra__c='14/15', Mes__c = 'Março');
        insert prevision;
        PricebookEntry pbe = [Select Id, Product2Id From PricebookEntry where Pricebook2Id = :pb.Id and isActive = true and Product2.Categ__c = :cat.Id limit 1];

        OpportunityLineItem oi2 = new OpportunityLineItem(OpportunityId=prevision.Id,Quantity=0.01,Previsao__c = 50,TotalPrice=10,PricebookEntryId=pbe.Id, Semente_aprovada__c=50,Semente_comercializada__c=50);
        insert oi2;
        
        //proximoStockMult(prevision.Id);
        
        Opp_Utils.proximaOpp(prevision.Id);
        
        RecordType rt = [Select Id From RecordType Where Name = 'Objetivo Ventas Royalties' limit 1];
        prevision.RecordTypeId = rt.Id;
        prevision.Safra__c = '12/13';
        prevision.Control_Stock_Multiplicadores__c = null;
        test.starttest();
        //update prevision;
        test.stoptest();
        //proximaOpp(prevision.Id);
        
    }
    @isTest(SeeAllData=true)
    static void test3() {
                
        Categoria__c cat = [SELECT Id, Name FROM Categoria__c WHERE Name = 'BASICA' limit 1];
        RecordType rt_prev = [Select Id From RecordType Where Name = 'VB - Autorizada' And SObjectType = 'Opportunity' limit 1];
        Account cuenta = [Select Id From Account Where Name = 'ACME' limit 1];
        Pricebook2 pb = [Select Id, Name From Pricebook2 where Name = 'Lista de Básica BMX SUL' and isActive = true limit 1];
        Opportunity prevision = New Opportunity(RecordTypeId=rt_prev.Id, Name='Previsao', AccountId = cuenta.Id,Pricebook2Id=pb.Id, CloseDate=System.today(), Marca__c='BRMX',StageName='Aberta', Safra__c='14/15', Mes__c = 'Março');
        insert prevision;
        PricebookEntry pbe = [Select Id, Product2Id From PricebookEntry where Pricebook2Id = :pb.Id and isActive = true and Product2.Categ__c = :cat.Id limit 1];

        OpportunityLineItem oi2 = new OpportunityLineItem(OpportunityId=prevision.Id,Quantity=20,TotalPrice=10,PricebookEntryId=pbe.Id, Semente_aprovada__c=50,Semente_comercializada__c=50);
        insert oi2;
        
        Opp_Utils.validarPasoVBSAP(prevision.Id);
    }
    @isTest(SeeAllData=true)
    static void test4() {
                
        Categoria__c cat = [SELECT Id, Name FROM Categoria__c WHERE Name = 'BASICA' limit 1];
        RecordType rt_prev = [Select Id From RecordType Where Name = 'VB - Autorizada' And SObjectType = 'Opportunity' limit 1];
        Account cuenta = [Select Id From Account Where Name = 'ACME' limit 1];
        Pricebook2 pb = [Select Id, Name From Pricebook2 where Name = 'Lista de Básica BMX SUL' and isActive = true limit 1];
        Opportunity prevision = New Opportunity(RecordTypeId=rt_prev.Id, Name='Previsao', AccountId = cuenta.Id,Pricebook2Id=pb.Id, CloseDate=System.today(), Marca__c='BRMX',StageName='Aberta', Safra__c='14/15', Mes__c = 'Março');
        insert prevision;
        PricebookEntry pbe = [Select Id, Product2Id From PricebookEntry where Pricebook2Id = :pb.Id and isActive = true and Product2.Categ__c = :cat.Id limit 1];

        OpportunityLineItem oi2 = new OpportunityLineItem(OpportunityId=prevision.Id,Quantity=20,TotalPrice=10,PricebookEntryId=pbe.Id, Semente_aprovada__c=50,Semente_comercializada__c=50, Base_de_Calculo__c= 40.0, Tasas__c=12.0);
        insert oi2;
        
        Opp_Utils.validarPasoVBSAP(prevision.Id);
        
        Opp_Utils.mapaMensajes2(oi2, 1, 2, 3, 4, 5, 6, 7, 8);
        Opp_Utils.mapaMensajes2(oi2, 2, 1, 3, 4, 5, 6, 7, 8);
        Opp_Utils.mapaMensajes2(oi2, 2, 1, 3, 4, 5, 8, 7, 6);
        Opp_Utils.mapaMensajes2(oi2, 2, 1, 3, 4, 5, 6, 7, 8);
        
        Opp_Utils.getSiguienteMes('Janeiro');
        Opp_Utils.getSiguienteMes('Fevereiro');
        Opp_Utils.getSiguienteMes('Abril');
        Opp_Utils.getSiguienteMes('Maio');
        Opp_Utils.getSiguienteMes('Junho');
        Opp_Utils.getSiguienteMes('Julho');
        Opp_Utils.getSiguienteMes('Agosto');
        Opp_Utils.getSiguienteMes('Setembro');
        Opp_Utils.getSiguienteMes('Outubro');
        Opp_Utils.getSiguienteMes('Novembro');
        
        Opp_Utils.actualizarPasoVBSAP(prevision.Id, true);
        
        Contact con = [Select Id from contact limit 1];
        User us = [Select Id from user limit 1];
        
        Opp_Utils.notificacionContacto(con.Id, us.Id);
        
    }
    
    @isTest(SeeAllData=true)
    static void test5() {
        /*
        Account o = [Select Id From Account limit 1];
        
        Blob beforeblob=Blob.valueOf('Unit Test Attachment Body');
        
        ContentVersion cv = new ContentVersion();
        cv.title = 'test content trigger';      
        cv.PathOnClient ='test';      
        cv.VersionData =beforeblob;                
        insert cv;         

        ContentVersion testContent = [SELECT id, ContentDocumentId FROM ContentVersion where Id = :cv.Id];
        List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];
        
        ContentDocumentLink contentlink=new ContentDocumentLink();
        contentlink.LinkedEntityId=o.id;
        contentlink.ContentDocumentId=testContent.ContentDocumentId;
        contentlink.ShareType= 'V';        
        contentlink.Visibility = 'AllUsers';
         
        insert contentlink;
        */
        Account acct = new Account(Name='TEST_ACCT');
        insert acct;
		
		ContentVersion contentVersion = new ContentVersion(
            Title = 'Penguins',
            PathOnClient = 'Penguins.jpg',
            VersionData = Blob.valueOf('Test Content')
            
        );
        insert contentVersion;    
        List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];

        //create ContentDocumentLink  record 
        ContentDocumentLink cdl = New ContentDocumentLink();
        cdl.LinkedEntityId = acct.id;
        cdl.ContentDocumentId = documents[0].Id;
        cdl.shareType = 'V';
        insert cdl;        
        
        delete cdl;
        delete documents[0];
    }
}