Salesforce/main/default/objects/Account/fields/Responsavel__c.field-meta.xml
<CustomField>
    <fullName>Responsavel__c</fullName>
    <description>Qual dos funcionários da Brasmax que estará responsável pela conta</description>
    <inlineHelpText>Qual dos funcionários da Brasmax que estará responsável pela conta</inlineHelpText>
    <label>Responsável BRMX</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>061 - Fernando Frehner</fullName>
            </value>
            <value>
                <fullName>066 - Marcelo Steffen</fullName>
            </value>
            <value>
                <fullName>067 - Sergio Bertagnolli</fullName>
            </value>
            <value>
                <fullName>076 - Tiago Goulart</fullName>
            </value>
            <value>
                <fullName>083 - Jorge Cristiano Rosa</fullName>
            </value>
            <value>
                <fullName>010 - Brasmax</fullName>
            </value>
            <value>
                <fullName>101 - Fausto Tadeu Fanchin</fullName>
            </value>
            <value>
                <fullName>104 - Otavio Gorni</fullName>
            </value>
            <value>
                <fullName>150 - João Serrano</fullName>
            </value>
            <value>
                <fullName>012 - Anderson Weissheimer</fullName>
            </value>
            <value>
                <fullName>197 - Wagner Rank</fullName>
            </value>
            <value>
                <fullName>198 - Bernardo Zanardo</fullName>
            </value>
            <value>
                <fullName>199 - Lucas Costa</fullName>
            </value>
            <value>
                <fullName>231 - Willian Von Scharten</fullName>
            </value>
            <value>
                <fullName>234 - Julio Cesar Poletto</fullName>
            </value>
            <value>
                <fullName>017 - Luis Fernando Cecatto</fullName>
            </value>
            <value>
                <fullName>018 - Flávio Marçal dos Santos</fullName>
            </value>
            <value>
                <fullName>312 - Lucas Hilario Fantineli</fullName>
            </value>
            <value>
                <fullName>019 - Felipe Oliveira Costa</fullName>
            </value>
            <value>
                <fullName>379 - Diego F. Gonçalves</fullName>
            </value>
            <value>
                <fullName>031 - Guilherme Sousa</fullName>
            </value>
            <value>
                <fullName>023 - Gabriel V. Finatto</fullName>
            </value>
            <value>
                <fullName>464 - Ana Laura Fernandes</fullName>
            </value>
            <value>
                <fullName>467 - Natalie de Mattos</fullName>
            </value>
            <value>
                <fullName>474 - Guilherme Menezes Salau</fullName>
            </value>
            <value>
                <fullName>403 - Felipe Bianchessi</fullName>
            </value>
            <value>
                <fullName>380 - Lucas de Souza Furlan</fullName>
            </value>
            <value>
                <fullName>037 - Felipe Dias Louzada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Opportunity/fields/Estado_de_produccion__c.field-meta.xml
<CustomField>
    <fullName>Estado_de_produccion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Estado de produccion, para incluir en el contrato de multiplicacion</description>
    <inlineHelpText>Estado de produccion, para incluir en el contrato de multiplicacion</inlineHelpText>
    <label>Estado de produccion</label>
    <referenceTo>Estado__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Opportunity/fields/Estado_Facturacion__c.field-meta.xml
<CustomField>
    <fullName>Estado_Facturacion__c</fullName>
    <label>Estado Facturacion</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>PE Contabilizar</fullName>
            </value>
            <value>
                <fullName>Contabilizada</fullName>
            </value>
            <value>
                <fullName>Impresa</fullName>
            </value>
            <value>
                <fullName>Anulada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Opportunity/fields/Mes__c.field-meta.xml
<CustomField>
    <fullName>Mes__c</fullName>
    <description>Nombre del mes para identificar la oportunidad de control de stock.</description>
    <label>Mês</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Janeiro</fullName>
            </value>
            <value>
                <fullName>Fevereiro</fullName>
            </value>
            <value>
                <fullName>Março</fullName>
            </value>
            <value>
                <fullName>Abril</fullName>
            </value>
            <value>
                <fullName>Maio</fullName>
            </value>
            <value>
                <fullName>Junho</fullName>
            </value>
            <value>
                <fullName>Julho</fullName>
            </value>
            <value>
                <fullName>Agosto</fullName>
            </value>
            <value>
                <fullName>Setembro</fullName>
            </value>
            <value>
                <fullName>Outubro</fullName>
            </value>
            <value>
                <fullName>Novembro</fullName>
            </value>
            <value>
                <fullName>Dezembro</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Opportunity/fields/Nro_Pedido_SAP__c.field-meta.xml
<CustomField>
    <fullName>Nro_Pedido_SAP__c</fullName>
    <externalId>true</externalId>
    <label>Nro Pedido SAP</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/Opportunity/fields/Numero_del__c.field-meta.xml
<CustomField>
    <fullName>Numero_del__c</fullName>
    <label>Numero</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/Opportunity/fields/Regiao__c.field-meta.xml
<CustomField>
    <fullName>Regiao__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Região</label>
    <referenceTo>Regiao__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/Opportunity/fields/Relatorio_Relacionado__c.field-meta.xml
<CustomField>
    <fullName>Relatorio_Relacionado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Relatorio Relacionado</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Opportunity/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <description>Safra o Campania agricola</description>
    <label>Safra</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>06/07</fullName>
            </value>
            <value>
                <fullName>07/08</fullName>
            </value>
            <value>
                <fullName>08/09</fullName>
            </value>
            <value>
                <fullName>09/10</fullName>
            </value>
            <value>
                <fullName>09/09</fullName>
            </value>
            <value>
                <fullName>10/10</fullName>
            </value>
            <value>
                <fullName>10/11</fullName>
            </value>
            <value>
                <fullName>11/11</fullName>
            </value>
            <value>
                <fullName>11/12</fullName>
            </value>
            <value>
                <fullName>12/12</fullName>
            </value>
            <value>
                <fullName>12/13</fullName>
            </value>
            <value>
                <fullName>13/14</fullName>
            </value>
            <value>
                <fullName>14/15</fullName>
            </value>
            <value>
                <fullName>15/16</fullName>
            </value>
            <value>
                <fullName>16/17</fullName>
            </value>
            <value>
                <fullName>17/18</fullName>
            </value>
            <value>
                <fullName>18/19</fullName>
            </value>
            <value>
                <fullName>19/20</fullName>
            </value>
            <value>
                <fullName>20/21</fullName>
            </value>
            <value>
                <fullName>21/22</fullName>
                <default>true</default>
                <label>21/22</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Opportunity/fields/VB_Cidade__c.field-meta.xml
<CustomField>
    <fullName>VB_Cidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cidade</label>
    <referenceTo>Cidade__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/Opportunity/fields/VB_Franqueado__c.field-meta.xml
<CustomField>
    <fullName>VB_Franqueado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Franqueado en la operacion donde el Franqueado le vende semilla basica al Multiplicador</description>
    <inlineHelpText>Franqueado en la operacion donde el Franqueado le vende semilla basica al Multiplicador</inlineHelpText>
    <label>Franqueado</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Oportunidades de Exportação</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Opportunity/recordTypes/Anexo_III.recordType-meta.xml
<RecordType>
    <fullName>Anexo_III</fullName>
    <active>true</active>
    <businessProcess>Circuito de Anexos</businessProcess>
    <label>Anexo III</label>
</RecordType>

Salesforce/main/default/objects/Opportunity/recordTypes/Anexo_IV.recordType-meta.xml
<RecordType>
    <fullName>Anexo_IV</fullName>
    <active>true</active>
    <businessProcess>Circuito de Anexos</businessProcess>
    <label>Anexo IV</label>
</RecordType>

Salesforce/main/default/objects/Opportunity/recordTypes/AnexoI.recordType-meta.xml
<RecordType>
    <fullName>AnexoI</fullName>
    <active>true</active>
    <businessProcess>Docusign - Anexos</businessProcess>
    <description>Anexo I -Autorização para multiplicação</description>
    <label>Anexo I</label>
</RecordType>

Salesforce/main/default/main/default/objects/Opportunity/recordTypes/AnexoII.recordType-meta.xml
<RecordType>
    <fullName>AnexoII</fullName>
    <active>true</active>
    <businessProcess>Circuito de Anexos</businessProcess>
    <description>Anexo II - Relatório de produção de sementes</description>
    <label>Anexo II</label>
</RecordType>

Salesforce/main/default/objects/Opportunity/recordTypes/Aquisicion_Sementes_Terceiros.recordType-meta.xml
<RecordType>
    <fullName>Aquisicion_Sementes_Terceiros</fullName>
    <active>true</active>
    <businessProcess>Circuito de Anexos</businessProcess>
    <label>Aquisição Sementes Terceiros</label>
</RecordType>

Salesforce/main/default/objects/Opportunity/recordTypes/Autorizada.recordType-meta.xml
<RecordType>
    <fullName>Autorizada</fullName>
    <active>true</active>
    <businessProcess>Nota de Venta - Autorizada</businessProcess>
    <label>Autorizada</label>
</RecordType>

Salesforce/main/default/objects/Opportunity/recordTypes/Comercial.recordType-meta.xml
<RecordType>
    <fullName>Comercial</fullName>
    <active>true</active>
    <businessProcess>Control_Multiplicador</businessProcess>
    <description>Detalle de lo que el multiplicador va a vender: relatorio de venda</description>
    <label>Comercial</label>
</RecordType>

Salesforce/main/default/main/default/objects/Opportunity/recordTypes/CVB_Autorizada.recordType-meta.xml
<RecordType>
    <fullName>CVB_Autorizada</fullName>
    <active>true</active>
    <businessProcess>Prevision Venta Basica</businessProcess>
    <description>Confirmación de Venta de Básica bajada a SAP</description>
    <label>CVB Autorizada</label>
</RecordType>

Salesforce/main/default/main/default/objects/Opportunity/recordTypes/CVB_Pendiente.recordType-meta.xml
<RecordType>
    <fullName>CVB_Pendiente</fullName>
    <active>true</active>
    <businessProcess>Prevision Venta Basica</businessProcess>
    <description>Es la confirmación de la venta de básica antes de ser enviada a SAP como NV.</description>
    <label>CVB Pendiente</label>
</RecordType>

Salesforce/main/default/objects/Opportunity/recordTypes/Descarte.recordType-meta.xml
<RecordType>
    <fullName>Descarte</fullName>
    <active>true</active>
    <businessProcess>Circuito de Anexos</businessProcess>
    <label>Descarte</label>
</RecordType>

Salesforce/main/default/main/default/objects/Opportunity/recordTypes/Disponibilidade_da_Basica.recordType-meta.xml
<RecordType>
    <fullName>Disponibilidade_da_Basica</fullName>
    <active>true</active>
    <businessProcess>Controle de Estoque</businessProcess>
    <description>Oportunidad para ingresar el stock de Básica por Safra, Marca y Macroregión.</description>
    <label>Disponibilidade da Basica</label>
</RecordType>

Salesforce/main/default/main/default/objects/Opportunity/recordTypes/Exportacion.recordType-meta.xml
<RecordType>
    <fullName>Exportacion</fullName>
    <active>true</active>
    <businessProcess>Circuito de Anexos</businessProcess>
    <label>Exportacion</label>
</RecordType>

Salesforce/main/default/objects/Opportunity/recordTypes/Objetivo_Contrato_Royalties.recordType-meta.xml
<RecordType>
    <fullName>Objetivo_Contrato_Royalties</fullName>
    <active>true</active>
    <businessProcess>Objetivo Ventas</businessProcess>
    <label>Objetivo Contrato Royalties</label>
</RecordType>

Salesforce/main/default/main/default/objects/Opportunity/recordTypes/Objetivo_Ventas_Royalties.recordType-meta.xml
<RecordType>
    <fullName>Objetivo_Ventas_Royalties</fullName>
    <active>true</active>
    <businessProcess>Objetivo Ventas</businessProcess>
    <description>Se utiliza para indicar los objetivos tanto de Venta de Royalties</description>
    <label>Objetivo Ventas Royalties</label>
</RecordType>

Salesforce/main/default/main/default/objects/Opportunity/recordTypes/Objetivo_Ventas_Semilla.recordType-meta.xml
<RecordType>
    <fullName>Objetivo_Ventas_Semilla</fullName>
    <active>true</active>
    <businessProcess>Objetivo Ventas</businessProcess>
    <description>Se utiliza para indicar los objetivos tanto de Venta de Basica</description>
    <label>Objetivo Ventas Semilla</label>
</RecordType>

Salesforce/main/default/main/default/objects/Opportunity/recordTypes/Pendiente.recordType-meta.xml
<RecordType>
    <fullName>Pendiente</fullName>
    <active>true</active>
    <businessProcess>Nota de Venta - Pendiente</businessProcess>
    <label>Pendiente</label>
</RecordType>

Salesforce/main/default/main/default/objects/Opportunity/recordTypes/Previsao.recordType-meta.xml
<RecordType>
    <fullName>Previsao</fullName>
    <active>true</active>
    <businessProcess>Prevision Venta Basica</businessProcess>
    <description>Previsiones de Ventas de Bolsas de Básica</description>
    <label>Previsao</label>
</RecordType>

Salesforce/main/default/main/default/objects/Opportunity/recordTypes/Produccion.recordType-meta.xml
<RecordType>
    <fullName>Produccion</fullName>
    <active>true</active>
    <businessProcess>Control_Multiplicador</businessProcess>
    <description>Detalle de lo que el multiplicador va a sembrar: autorización correspondiente y relatorio de produccion</description>
    <label>Produccion</label>
</RecordType>

Salesforce/main/default/objects/Opportunity/recordTypes/Rechazada.recordType-meta.xml
<RecordType>
    <fullName>Rechazada</fullName>
    <active>true</active>
    <businessProcess>Fc de Brasmax</businessProcess>
    <label>Rechazada</label>
</RecordType>

Salesforce/main/default/main/default/objects/Opportunity/recordTypes/Reembalaje.recordType-meta.xml
<RecordType>
    <fullName>Reembalaje</fullName>
    <active>true</active>
    <businessProcess>Docusign - Anexos</businessProcess>
    <label>Reembalaje</label>
</RecordType>

Salesforce/main/default/main/default/objects/Opportunity/recordTypes/Stock_Multiplicadores.recordType-meta.xml
<RecordType>
    <fullName>Stock_Multiplicadores</fullName>
    <active>true</active>
    <businessProcess>Stock Multiplicadores</businessProcess>
    <label>Stock Multiplicadores</label>
</RecordType>

Salesforce/main/default/objects/OpportunityLineItem/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Categoria a ser licenciada</description>
    <inlineHelpText>Categoria a ser licenciada</inlineHelpText>
    <label>Categoria</label>
    <referenceTo>Categoria__c</referenceTo>
    <relationshipLabel>Producto de oportunidad</relationshipLabel>
    <relationshipName>Producto_de_oportunidad</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/OpportunityLineItem/fields/Categoria_a_Rebaixar__c.field-meta.xml
<CustomField>
    <fullName>Categoria_a_Rebaixar__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Categoria Plantada</label>
    <referenceTo>Categoria__c</referenceTo>
    <relationshipLabel>Producto de oportunidad (Categoria a Rebaixar)</relationshipLabel>
    <relationshipName>Producto_de_oportunidad1</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/OpportunityLineItem/fields/Estado_de_Produccion__c.field-meta.xml
<CustomField>
    <fullName>Estado_de_Produccion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Estado de Produccion</label>
    <referenceTo>Estado__c</referenceTo>
    <relationshipLabel>Producto de oportunidad</relationshipLabel>
    <relationshipName>Producto_de_oportunidad</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/OpportunityLineItem/fields/Estado_Facturacion__c.field-meta.xml
<CustomField>
    <fullName>Estado_Facturacion__c</fullName>
    <label>Estado Facturacion</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Facturado</fullName>
            </value>
            <value>
                <fullName>No facturado</fullName>
                <default>true</default>
                <label>No facturado</label>
            </value>
            <value>
                <fullName>Pasado Pedido</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/OpportunityLineItem/fields/Item_Rebajado__c.field-meta.xml
<CustomField>
    <fullName>Item_Rebajado__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indica si corresponde al ítem generado para restarle la cantidad a la categoría rebajada. Para la sumarizacion en reportes.</description>
    <label>Item Rebajado</label>
    <type>Checkbox</type>
</CustomField>

Salesforce/main/default/objects/OpportunityLineItem/fields/Lote_Rebajado__c.field-meta.xml
<CustomField>
    <fullName>Lote_Rebajado__c</fullName>
    <label>Lote</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/OpportunityLineItem/fields/Registro_Cultivar__c.field-meta.xml
<CustomField>
    <fullName>Registro_Cultivar__c</fullName>
    <formula>PricebookEntry.Product2.Variedade__r.Nombre_de_Registro__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Registro Cultivar</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/OpportunityLineItem/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <formula>TEXT(Opportunity.Safra__c)</formula>
    <label>Safra</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/OpportunityLineItem/fields/Sem_Rebajada__c.field-meta.xml
<CustomField>
    <fullName>Sem_Rebajada__c</fullName>
    <label>Sem. Rebaixada (Sacas)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/objects/OpportunityLineItem/fields/Variedade_Prod__c.field-meta.xml
<CustomField>
    <fullName>Variedade_Prod__c</fullName>
    <formula>PricebookEntry.Product2.Variedade__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Nome Comercial</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/Order/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <label>Safra</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Safra</valueSetName>
    </valueSet>
</CustomField>

Salesforce/main/default/globalValueSets/Safra.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>14/15</fullName>
    </customValue>
    <customValue>
        <fullName>15/16</fullName>
    </customValue>
    <customValue>
        <fullName>16/17</fullName>
    </customValue>
    <customValue>
        <fullName>17/18</fullName>
    </customValue>
    <customValue>
        <fullName>18/19</fullName>
    </customValue>
    <customValue>
        <fullName>19/20</fullName>
    </customValue>
    <customValue>
        <fullName>20/21</fullName>
    </customValue>
    <customValue>
        <fullName>21/22</fullName>
    </customValue>
    <customValue>
        <fullName>22/23</fullName>
    </customValue>
    <customValue>
        <fullName>23/24</fullName>
    </customValue>
    <customValue>
        <fullName>08/09</fullName>
        <isActive>false</isActive>
        <label>08/09</label>
    </customValue>
    <customValue>
        <fullName>07/08</fullName>
        <isActive>false</isActive>
        <label>07/08</label>
    </customValue>
    <customValue>
        <fullName>10/11</fullName>
        <isActive>false</isActive>
        <label>10/11</label>
    </customValue>
    <customValue>
        <fullName>11/12</fullName>
        <isActive>false</isActive>
        <label>11/12</label>
    </customValue>
    <customValue>
        <fullName>12/13</fullName>
        <isActive>false</isActive>
        <label>12/13</label>
    </customValue>
    <customValue>
        <fullName>13/14</fullName>
        <isActive>false</isActive>
        <label>13/14</label>
    </customValue>
    <customValue>
        <fullName>09/10</fullName>
        <isActive>false</isActive>
        <label>09/10</label>
    </customValue>
    <masterLabel>Safra</masterLabel>
</GlobalValueSet>

Salesforce/main/default/classes/opportunitySacasExtension.cls
public class opportunitySacasExtension {
    
   public opportunitySacasExtension(ApexPages.StandardController controller) {

}

public String searchTextAnexo {get; set;}
   public List<Opportunity> resultAnexos = new List<Opportunity>();
   public String anexo {get; set;}
   public String etapaAnexo;
   private String rt_anexoI_opps;
   private String rt_anexoII_opps;
   private String rt_anexoIII_opps;
   private String rt_anexoIV_opps;
   private String rt_anexoV_opps;
   private String rt_Previsao_opps;
   private String rt_Previsao_Cerrada_opps;
   private String rt_VB_Fc_opps;
   private String rt_VB_Pe_opps;
   private String rt_VB_Au_opps;
   private String rt_VB_Re_opps;
   private String rt_DB_opps;
   private String rt_PBC_opps;
   private String rt_PBP_opps;
   private String rt_Exp_opps;
   private String rt_Reemb_opps;
   private String rt_Descarte_opps;
   
   public void setetapaAnexo(String arg){
       etapaAnexo = arg;
   }

   public String getetapaAnexo(){
       Profile pro = [Select Name From Profile Where Id = : UserInfo.getProfileId()];       
       if (pro.Name == 'Administrador del sistema' || pro.Name == 'Gerente Administrativo')
           etapaAnexo = 'PEAP';
       if (pro.Name == 'Comercial')
           etapaAnexo = 'PEAN';    
       if (pro.Name == 'Administrativo')
           etapaAnexo = 'APR';    
   
       return etapaAnexo;
   }
   
   public opportunitySacasExtension(){    
       searchTextAnexo = '';
      
       for (RecordType rt : [Select Id, Name From RecordType Where Name in ('Anexo I','Anexo II','Anexo III', 'Anexo IV', 'Anexo V', 'Previsao', 'Previsao Cerrada', 'VB - Pasada SAP', 'VB - Pendiente', 'VB - Autorizada', 'VB - Rechazada', 'Disponibilidade da Basica', 'Exportacion', 'PB-Comercial', 'PB-Produccion', 'Reembalaje', 'Descarte')]){
           if (rt.Name == 'Anexo I')
              rt_anexoI_opps = rt.Id;
           if (rt.Name == 'Anexo II')
              rt_anexoII_opps = rt.Id;
           if (rt.Name == 'Anexo III')
              rt_anexoIII_opps = rt.Id;
           if (rt.Name == 'Anexo IV')
              rt_anexoIV_opps = rt.Id;
           if (rt.Name == 'Anexo V')
              rt_anexoV_opps = rt.Id; 
           if (rt.Name == 'Previsao')
              rt_Previsao_opps = rt.Id;
           if (rt.Name == 'Previsao Cerrada')
              rt_Previsao_Cerrada_opps = rt.Id;              
           if (rt.Name == 'VB - Pasada SAP')
              rt_VB_Fc_opps = rt.Id;
           if (rt.Name == 'VB - Pendiente')
              rt_VB_Pe_opps = rt.Id;
           if (rt.Name == 'VB - Autorizada')
              rt_VB_Au_opps = rt.Id;
           if (rt.Name == 'VB - Rechazada')
              rt_VB_Re_opps = rt.Id;
           if (rt.Name == 'Disponibilidade da Basica')
              rt_DB_opps = rt.id;
           if (rt.Name == 'PB-Comercial')
              rt_PBC_opps = rt.Id;
           if (rt.Name == 'PB-Produccion')
              rt_PBP_opps = rt.Id;
           if (rt.Name == 'Exportacion')
              rt_Exp_opps = rt.Id;
           if (rt.Name == 'Reembalaje')
              rt_Reemb_opps = rt.Id;
           if(rt.Name == 'Descarte')
              rt_Descarte_opps = rt.Id;
       }
   }
       
   public List<Opportunity> getresultAnexos() {return resultAnexos;}    
   
   public List<SelectOption> getTiposAnexos() {
       List<SelectOption> options = new List<SelectOption>();
       options.add(new SelectOption('ALL','--Todos--'));
       options.add(new SelectOption('A1','Anexo I'));
       options.add(new SelectOption('A2','Anexo II'));
       options.add(new SelectOption('A3','Anexo III'));
       options.add(new SelectOption('A4','Anexo IV'));
       options.add(new SelectOption('A5','Anexo V'));
       return options;
   }
   
   public List<SelectOption> getEtapasAnexos() {        
       List<SelectOption> options = new List<SelectOption>();
       options.add(new SelectOption('ALL','--Todas--'));
       options.add(new SelectOption('PEAN','Pendiente de Analisis'));
       options.add(new SelectOption('PEAP','Pendiente de Aprobacion'));
       options.add(new SelectOption('APR','Aprobada'));      
       
       return options;
   }
   
   public void listarAnexos(){
       resultAnexos = null;
       this.searchAnexos();       
   }
   
   public void searchAnexos(){
       String s = searchTextAnexo;
       
       String qry = 'select Id, Name, Mes__c, Regiao__r.Name, VB_Franqueado__c, VB_Franqueado__r.Name, StageName, Safra__c, Estado_Facturacion__c, CloseDate, Numero_del__c, Account.Id, Account.Name, Account.Responsavel__c, RecordType.Name, LastModifiedDate, Relatorio_Relacionado__c, Relatorio_Relacionado__r.Name, Nro_Pedido_SAP__c, VB_Cidade__c, Estado_de_Produccion__c From Opportunity ';
       
       qry += 'where OwnerId != null ';
       if (anexo == 'A1')
           qry += ' and RecordTypeId = : rt_anexoI_opps ';
       if (anexo == 'A2')
           qry += ' and RecordTypeId = : rt_anexoII_opps ';
       if (anexo == 'A3')
           qry += ' and RecordTypeId = : rt_anexoIII_opps ';
       if (anexo == 'A4')
           qry += ' and RecordTypeId = : rt_anexoIV_opps ';
       if (anexo == 'A5')
           qry += ' and RecordTypeId = : rt_anexoV_opps ';        
       if (anexo == 'ALL')
           qry += ' and (RecordTypeId = : rt_anexoI_opps OR RecordTypeId = : rt_anexoII_opps OR RecordTypeId = : rt_anexoIII_opps OR RecordTypeId = : rt_anexoIV_opps OR RecordTypeId = : rt_anexoV_opps) ';
           
       if (etapaAnexo == 'PEAN')
           qry += ' and StageName = \'Pendiente de Análisis\'';    
       if (etapaAnexo == 'PEAP')
           qry += ' and StageName = \'Pendiente de Aprobación\'';    
       if (etapaAnexo == 'APR')
           qry += ' and StageName = \'Aprobada\'';                   
                       
       if(s != ''){ s = '%' + s + '%'; qry += ' and Name like : s';}
       if(Test.isRunningTest()){
        qry += ' Order by Nro_Pedido_SAP__c, Safra__c Desc, LastModifiedDate Desc LIMIT 100';
       }else{
          qry += ' Order by Nro_Pedido_SAP__c, Safra__c Desc, LastModifiedDate Desc';   
       }
     
       resultAnexos = Database.query(qry);
   }
      
   public List<OpportunityLineItem> getItems() {
         String query ='';
       /*
       String query = 'SELECT ';
       for(Schema.FieldSetMember f : this.getFields()) {
           query += f.getFieldPath() + ', ';
       }*/
       query = 'SELECT Id,Variedade_Prod__c,Registro_Cultivar__c,Categoria__r.Name,Categoria_a_Rebaixar__r.Name,Sem_Rebajada__c,Lote_Rebajado__c FROM OpportunityLineItem Where OpportunityId = \'' + apexpages.currentpage().getparameters().get('id') + '\'';
       if(Test.isRunningTest()){
        query += ' And Item_Rebajado__c = false Order by Variedade_Prod__c LIMIT 100' ;
       }else{
          query += ' And Item_Rebajado__c = false Order by Variedade_Prod__c' ; 
       }
       
       return Database.query(query);
   }
   
   public List<Schema.FieldSetMember> getFields() {
        Opportunity opp = [SELECT RecordType.Name, Setor__c, Oportunidad_Relacionada__r.RecordType.Name FROM Opportunity WHERE Id =: apexpages.currentpage().getparameters().get('id')];

        if (opp.RecordType.Name == 'Anexo I')
            return SObjectType.OpportunityLineItem.FieldSets.AnexoI.getFields();
        if (opp.RecordType.Name == 'Anexo II')
            return SObjectType.OpportunityLineItem.FieldSets.AnexoII.getFields();
        if (opp.RecordType.Name == 'Anexo III')
            return SObjectType.OpportunityLineItem.FieldSets.Anexo_III.getFields();  
        if (opp.RecordType.Name == 'Anexo IV')
            return SObjectType.OpportunityLineItem.FieldSets.Anexo_IV.getFields();
        if (opp.RecordType.Name == 'Anexo V')
            return SObjectType.OpportunityLineItem.FieldSets.Anexo_V.getFields();        
        if (opp.RecordType.Name == 'Pendiente')
            return SObjectType.OpportunityLineItem.FieldSets.Pendiente.getFields();    
        if (opp.RecordType.Name == 'NC - Pendiente' || opp.RecordType.Name == 'NC - Autorizada' || opp.RecordType.Name == 'NC - Rechazada')
            return SObjectType.OpportunityLineItem.FieldSets.Nota_de_Credito.getFields();    
        if (opp.RecordType.Name == 'Autorizada')
            return SObjectType.OpportunityLineItem.FieldSets.Autorizada.getFields();    
        if (opp.RecordType.Name == 'Rechazada')
            return SObjectType.OpportunityLineItem.FieldSets.Rechazada.getFields();    
        if (opp.RecordType.Name == 'Anexo I Rebaixamento Ha')
            return SObjectType.OpportunityLineItem.FieldSets.AnexoI_Rebaixamento.getFields();    
        if (opp.RecordType.Name == 'Anexo II Rebaixamento Sacas')
            return SObjectType.OpportunityLineItem.FieldSets.Anexo_Rebajamiento_Bolsas.getFields();
        if (opp.RecordType.Name == 'Stock Multiplicadores')
            return SObjectType.OpportunityLineItem.FieldSets.Stock_Multiplicadores.getFields();        
        if (opp.RecordType.Name == 'Previsao' || opp.RecordType.Name == 'Previsao Cerrada')
            return SObjectType.OpportunityLineItem.FieldSets.Previsao.getFields();
        if (opp.RecordType.Name == 'VB - Pendiente' || opp.RecordType.Name == 'VB - Autorizada' || opp.RecordType.Name == 'VB - Rechazada')
            return SObjectType.OpportunityLineItem.FieldSets.VB_General.getFields();
        if (opp.RecordType.Name == 'VB - Pasada SAP')
            return SObjectType.OpportunityLineItem.FieldSets.VB_SAP.getFields();
        if (opp.RecordType.Name == 'CVB Pendiente') {
            if (opp.Oportunidad_Relacionada__r.RecordType.Name == 'Venda da Basica Completo') { // relacionado a una CVB Completa
                return SObjectType.OpportunityLineItem.FieldSets.CVB_Pendiente_VB_Completa.getFields();
            } else {
                return SObjectType.OpportunityLineItem.FieldSets.CVB_Pendiente.getFields();
            }
        }
        if (opp.RecordType.Name == 'CVB Rechazada' || opp.RecordType.Name == 'CVB Autorizada') {
            if (opp.Oportunidad_Relacionada__r.RecordType.Name == 'Venda da Basica Completo') { // relacionado a una CVB Completa
                return SObjectType.OpportunityLineItem.FieldSets.CVB_Autorizada_VB_Completa.getFields();
            } else {
                return SObjectType.OpportunityLineItem.FieldSets.CVB_Autorizada.getFields();
            }
        }
        if (opp.RecordType.Name == 'Disponibilidade da Basica')
            return SObjectType.OpportunityLineItem.FieldSets.Disponibilidade_da_Basica.getFields();
        if (opp.RecordType.Name == 'PB-Comercial')
            return SObjectType.OpportunityLineItem.FieldSets.Produccion_Basica.getFields();
        if (opp.RecordType.Name == 'Exportacion')
            return SObjectType.OpportunityLineItem.FieldSets.Exportacion.getFields();
        if (opp.RecordType.Name == 'Reembalaje')
            return SObjectType.OpportunityLineItem.FieldSets.Reembalaje.getFields();
        if (opp.RecordType.Name == 'Objetivo Ventas Semilla')
            return SObjectType.OpportunityLineItem.FieldSets.Objetivo_Ventas_Semilla.getFields();
        if (opp.RecordType.Name == 'PB-Desarrollo')
            return SObjectType.OpportunityLineItem.FieldSets.Produccion_Basica_Desarrollo.getFields();
        if (opp.RecordType.Name == 'PB-Produccion' && opp.Setor__c == 'Comercial')
            return SObjectType.OpportunityLineItem.FieldSets.Produccion_Basica.getFields();
        if (opp.RecordType.Name == 'PB-Produccion' && opp.Setor__c == 'Desarrollo')
            return SObjectType.OpportunityLineItem.FieldSets.Produccion_Basica_Desarrollo.getFields();  
        if (opp.RecordType.Name == 'PB-Oferta')
            return SObjectType.OpportunityLineItem.FieldSets.Produccion_Basica_Oferta.getFields();  
        if (opp.RecordType.Name == 'Objetivo Ventas Royalties')
            return SObjectType.OpportunityLineItem.FieldSets.Objetivo_Ventas_Royalties.getFields();
        if (opp.RecordType.Name == 'Estimativa de venda')
            return SObjectType.OpportunityLineItem.FieldSets.Estimativa.getFields();
        if (opp.RecordType.Name == 'Objetivo Contrato Royalties')
            return SObjectType.OpportunityLineItem.FieldSets.Objetivo_Contrato_Royalties.getFields();
        if (opp.RecordType.Name.contains('Antecipação'))
            return SObjectType.OpportunityLineItem.FieldSets.Anticipo.getFields();  
        if (opp.RecordType.Name.contains('Descarte'))
            return SObjectType.OpportunityLineItem.FieldSets.Anexo_Descarte.getFields(); 
        if (opp.RecordType.Name.contains('Aquisição Sementes Terceiros'))
            return SObjectType.OpportunityLineItem.FieldSets.Aquisicion_Sementes_Terceiros.getFields(); 
        if (opp.RecordType.Name == 'Estimativa de Faturamento')
            return SObjectType.OpportunityLineItem.FieldSets.Pendiente.getFields();
        if (opp.RecordType.Name == 'Venda da Basica Completo')
            return SObjectType.OpportunityLineItem.FieldSets.VB_Completa.getFields();
        
        return null;                      
    }
   
  

   

}