Salesforce/main/default/objects/Account/fields/Responsavel__c.field-meta.xml
<CustomField>
    <fullName>Responsavel__c</fullName>
    <description>Qual dos funcionários da Brasmax que estará responsável pela conta</description>
    <inlineHelpText>Qual dos funcionários da Brasmax que estará responsável pela conta</inlineHelpText>
    <label>Responsável BRMX</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>061 - Fernando Frehner</fullName>
            </value>
            <value>
                <fullName>066 - Marcelo Steffen</fullName>
            </value>
            <value>
                <fullName>067 - Sergio Bertagnolli</fullName>
            </value>
            <value>
                <fullName>076 - Tiago Goulart</fullName>
            </value>
            <value>
                <fullName>083 - Jorge Cristiano Rosa</fullName>
            </value>
            <value>
                <fullName>010 - Brasmax</fullName>
            </value>
            <value>
                <fullName>101 - Fausto Tadeu Fanchin</fullName>
            </value>
            <value>
                <fullName>104 - Otavio Gorni</fullName>
            </value>
            <value>
                <fullName>150 - João Serrano</fullName>
            </value>
            <value>
                <fullName>012 - Anderson Weissheimer</fullName>
            </value>
            <value>
                <fullName>197 - Wagner Rank</fullName>
            </value>
            <value>
                <fullName>198 - Bernardo Zanardo</fullName>
            </value>
            <value>
                <fullName>199 - Lucas Costa</fullName>
            </value>
            <value>
                <fullName>231 - Willian Von Scharten</fullName>
            </value>
            <value>
                <fullName>234 - Julio Cesar Poletto</fullName>
            </value>
            <value>
                <fullName>017 - Luis Fernando Cecatto</fullName>
            </value>
            <value>
                <fullName>018 - Flávio Marçal dos Santos</fullName>
            </value>
            <value>
                <fullName>312 - Lucas Hilario Fantineli</fullName>
            </value>
            <value>
                <fullName>019 - Felipe Oliveira Costa</fullName>
            </value>
            <value>
                <fullName>379 - Diego F. Gonçalves</fullName>
            </value>
            <value>
                <fullName>031 - Guilherme Sousa</fullName>
            </value>
            <value>
                <fullName>023 - Gabriel V. Finatto</fullName>
            </value>
            <value>
                <fullName>464 - Ana Laura Fernandes</fullName>
            </value>
            <value>
                <fullName>467 - Natalie de Mattos</fullName>
            </value>
            <value>
                <fullName>474 - Guilherme Menezes Salau</fullName>
            </value>
            <value>
                <fullName>403 - Felipe Bianchessi</fullName>
            </value>
            <value>
                <fullName>380 - Lucas de Souza Furlan</fullName>
            </value>
            <value>
                <fullName>037 - Felipe Dias Louzada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Account/recordTypes/Cuenta.recordType-meta.xml
<RecordType>
    <fullName>Cuenta</fullName>
    <active>true</active>
    <label>Cuenta</label>
</RecordType>

Salesforce/main/default/main/default/objects/Opportunity/fields/Estado_de_produccion__c.field-meta.xml
<CustomField>
    <fullName>Estado_de_produccion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Estado de produccion, para incluir en el contrato de multiplicacion</description>
    <inlineHelpText>Estado de produccion, para incluir en el contrato de multiplicacion</inlineHelpText>
    <label>Estado de produccion</label>
    <referenceTo>Estado__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Opportunity/fields/Estado_Facturacion__c.field-meta.xml
<CustomField>
    <fullName>Estado_Facturacion__c</fullName>
    <label>Estado Facturacion</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>PE Contabilizar</fullName>
            </value>
            <value>
                <fullName>Contabilizada</fullName>
            </value>
            <value>
                <fullName>Impresa</fullName>
            </value>
            <value>
                <fullName>Anulada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Opportunity/fields/Mes__c.field-meta.xml
<CustomField>
    <fullName>Mes__c</fullName>
    <description>Nombre del mes para identificar la oportunidad de control de stock.</description>
    <label>Mês</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Janeiro</fullName>
            </value>
            <value>
                <fullName>Fevereiro</fullName>
            </value>
            <value>
                <fullName>Março</fullName>
            </value>
            <value>
                <fullName>Abril</fullName>
            </value>
            <value>
                <fullName>Maio</fullName>
            </value>
            <value>
                <fullName>Junho</fullName>
            </value>
            <value>
                <fullName>Julho</fullName>
            </value>
            <value>
                <fullName>Agosto</fullName>
            </value>
            <value>
                <fullName>Setembro</fullName>
            </value>
            <value>
                <fullName>Outubro</fullName>
            </value>
            <value>
                <fullName>Novembro</fullName>
            </value>
            <value>
                <fullName>Dezembro</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Opportunity/fields/Nro_Pedido_SAP__c.field-meta.xml
<CustomField>
    <fullName>Nro_Pedido_SAP__c</fullName>
    <externalId>true</externalId>
    <label>Nro Pedido SAP</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/Opportunity/fields/Numero_del__c.field-meta.xml
<CustomField>
    <fullName>Numero_del__c</fullName>
    <label>Numero</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/Opportunity/fields/Oportunidad_Relacionada__c.field-meta.xml
<CustomField>
    <fullName>Oportunidad_Relacionada__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Oportunidad Relacionada</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Oportunidades (Oportunidad Relacionada)</relationshipLabel>
    <relationshipName>Oportunidades3</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/Opportunity/fields/Regiao__c.field-meta.xml
<CustomField>
    <fullName>Regiao__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Região</label>
    <referenceTo>Regiao__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/Opportunity/fields/Relatorio_Relacionado__c.field-meta.xml
<CustomField>
    <fullName>Relatorio_Relacionado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Relatorio Relacionado</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Opportunity/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <description>Safra o Campania agricola</description>
    <label>Safra</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>06/07</fullName>
            </value>
            <value>
                <fullName>07/08</fullName>
            </value>
            <value>
                <fullName>08/09</fullName>
            </value>
            <value>
                <fullName>09/10</fullName>
            </value>
            <value>
                <fullName>09/09</fullName>
            </value>
            <value>
                <fullName>10/10</fullName>
            </value>
            <value>
                <fullName>10/11</fullName>
            </value>
            <value>
                <fullName>11/11</fullName>
            </value>
            <value>
                <fullName>11/12</fullName>
            </value>
            <value>
                <fullName>12/12</fullName>
            </value>
            <value>
                <fullName>12/13</fullName>
            </value>
            <value>
                <fullName>13/14</fullName>
            </value>
            <value>
                <fullName>14/15</fullName>
            </value>
            <value>
                <fullName>15/16</fullName>
            </value>
            <value>
                <fullName>16/17</fullName>
            </value>
            <value>
                <fullName>17/18</fullName>
            </value>
            <value>
                <fullName>18/19</fullName>
            </value>
            <value>
                <fullName>19/20</fullName>
            </value>
            <value>
                <fullName>20/21</fullName>
            </value>
            <value>
                <fullName>21/22</fullName>
                <default>true</default>
                <label>21/22</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Opportunity/fields/Setor__c.field-meta.xml
<CustomField>
    <fullName>Setor__c</fullName>
    <description>En este campo se indica que sector está cargando la oportunidad de Producción de Básica</description>
    <label>Setor</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Comercial</fullName>
            </value>
            <value>
                <fullName>Desarrollo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Opportunity/fields/VB_Cidade__c.field-meta.xml
<CustomField>
    <fullName>VB_Cidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cidade</label>
    <referenceTo>Cidade__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/Opportunity/fields/VB_Franqueado__c.field-meta.xml
<CustomField>
    <fullName>VB_Franqueado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Franqueado en la operacion donde el Franqueado le vende semilla basica al Multiplicador</description>
    <inlineHelpText>Franqueado en la operacion donde el Franqueado le vende semilla basica al Multiplicador</inlineHelpText>
    <label>Franqueado</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Oportunidades de Exportação</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Opportunity/recordTypes/Anexo_I_Rebaixamento_Ha.recordType-meta.xml
<RecordType>
    <fullName>Anexo_I_Rebaixamento_Ha</fullName>
    <active>true</active>
    <businessProcess>Circuito de Anexos</businessProcess>
    <label>Anexo I Rebaixamento Ha</label>
</RecordType>

Salesforce/main/default/main/default/objects/Opportunity/recordTypes/Anexo_II_Rebaixamento_Sacas.recordType-meta.xml
<RecordType>
    <fullName>Anexo_II_Rebaixamento_Sacas</fullName>
    <active>true</active>
    <businessProcess>Docusign - Anexos</businessProcess>
    <description>Anexo II Rebaixamento Sacas</description>
    <label>Anexo II Rebaixamento Sacas</label>
</RecordType>

Salesforce/main/default/main/default/objects/Opportunity/recordTypes/Anexo_III.recordType-meta.xml
<RecordType>
    <fullName>Anexo_III</fullName>
    <active>true</active>
    <businessProcess>Circuito de Anexos</businessProcess>
    <label>Anexo III</label>
</RecordType>

Salesforce/main/default/objects/Opportunity/recordTypes/Anexo_IV.recordType-meta.xml
<RecordType>
    <fullName>Anexo_IV</fullName>
    <active>true</active>
    <businessProcess>Circuito de Anexos</businessProcess>
    <label>Anexo IV</label>
</RecordType>

Salesforce/main/default/objects/Opportunity/recordTypes/AnexoI.recordType-meta.xml
<RecordType>
    <fullName>AnexoI</fullName>
    <active>true</active>
    <businessProcess>Docusign - Anexos</businessProcess>
    <description>Anexo I -Autorização para multiplicação</description>
    <label>Anexo I</label>
</RecordType>

Salesforce/main/default/main/default/objects/Opportunity/recordTypes/AnexoII.recordType-meta.xml
<RecordType>
    <fullName>AnexoII</fullName>
    <active>true</active>
    <businessProcess>Circuito de Anexos</businessProcess>
    <description>Anexo II - Relatório de produção de sementes</description>
    <label>Anexo II</label>
</RecordType>

Salesforce/main/default/objects/Opportunity/recordTypes/Aquisicion_Sementes_Terceiros.recordType-meta.xml
<RecordType>
    <fullName>Aquisicion_Sementes_Terceiros</fullName>
    <active>true</active>
    <businessProcess>Circuito de Anexos</businessProcess>
    <label>Aquisição Sementes Terceiros</label>
</RecordType>

Salesforce/main/default/objects/Opportunity/recordTypes/Autorizada.recordType-meta.xml
<RecordType>
    <fullName>Autorizada</fullName>
    <active>true</active>
    <businessProcess>Nota de Venta - Autorizada</businessProcess>
    <label>Autorizada</label>
</RecordType>

Salesforce/main/default/objects/Opportunity/recordTypes/Comercial.recordType-meta.xml
<RecordType>
    <fullName>Comercial</fullName>
    <active>true</active>
    <businessProcess>Control_Multiplicador</businessProcess>
    <description>Detalle de lo que el multiplicador va a vender: relatorio de venda</description>
    <label>Comercial</label>
</RecordType>

Salesforce/main/default/main/default/objects/Opportunity/recordTypes/CVB_Autorizada.recordType-meta.xml
<RecordType>
    <fullName>CVB_Autorizada</fullName>
    <active>true</active>
    <businessProcess>Prevision Venta Basica</businessProcess>
    <description>Confirmación de Venta de Básica bajada a SAP</description>
    <label>CVB Autorizada</label>
</RecordType>

Salesforce/main/default/main/default/objects/Opportunity/recordTypes/CVB_Pendiente.recordType-meta.xml
<RecordType>
    <fullName>CVB_Pendiente</fullName>
    <active>true</active>
    <businessProcess>Prevision Venta Basica</businessProcess>
    <description>Es la confirmación de la venta de básica antes de ser enviada a SAP como NV.</description>
    <label>CVB Pendiente</label>
</RecordType>

Salesforce/main/default/objects/Opportunity/recordTypes/Descarte.recordType-meta.xml
<RecordType>
    <fullName>Descarte</fullName>
    <active>true</active>
    <businessProcess>Circuito de Anexos</businessProcess>
    <label>Descarte</label>
</RecordType>

Salesforce/main/default/main/default/objects/Opportunity/recordTypes/Disponibilidade_da_Basica.recordType-meta.xml
<RecordType>
    <fullName>Disponibilidade_da_Basica</fullName>
    <active>true</active>
    <businessProcess>Controle de Estoque</businessProcess>
    <description>Oportunidad para ingresar el stock de Básica por Safra, Marca y Macroregión.</description>
    <label>Disponibilidade da Basica</label>
</RecordType>

Salesforce/main/default/main/default/objects/Opportunity/recordTypes/Exportacion.recordType-meta.xml
<RecordType>
    <fullName>Exportacion</fullName>
    <active>true</active>
    <businessProcess>Circuito de Anexos</businessProcess>
    <label>Exportacion</label>
</RecordType>

Salesforce/main/default/objects/Opportunity/recordTypes/Objetivo_Contrato_Royalties.recordType-meta.xml
<RecordType>
    <fullName>Objetivo_Contrato_Royalties</fullName>
    <active>true</active>
    <businessProcess>Objetivo Ventas</businessProcess>
    <label>Objetivo Contrato Royalties</label>
</RecordType>

Salesforce/main/default/main/default/objects/Opportunity/recordTypes/Objetivo_Ventas_Royalties.recordType-meta.xml
<RecordType>
    <fullName>Objetivo_Ventas_Royalties</fullName>
    <active>true</active>
    <businessProcess>Objetivo Ventas</businessProcess>
    <description>Se utiliza para indicar los objetivos tanto de Venta de Royalties</description>
    <label>Objetivo Ventas Royalties</label>
</RecordType>

Salesforce/main/default/main/default/objects/Opportunity/recordTypes/Objetivo_Ventas_Semilla.recordType-meta.xml
<RecordType>
    <fullName>Objetivo_Ventas_Semilla</fullName>
    <active>true</active>
    <businessProcess>Objetivo Ventas</businessProcess>
    <description>Se utiliza para indicar los objetivos tanto de Venta de Basica</description>
    <label>Objetivo Ventas Semilla</label>
</RecordType>

Salesforce/main/default/main/default/objects/Opportunity/recordTypes/Pendiente.recordType-meta.xml
<RecordType>
    <fullName>Pendiente</fullName>
    <active>true</active>
    <businessProcess>Nota de Venta - Pendiente</businessProcess>
    <label>Pendiente</label>
</RecordType>

Salesforce/main/default/main/default/objects/Opportunity/recordTypes/Previsao.recordType-meta.xml
<RecordType>
    <fullName>Previsao</fullName>
    <active>true</active>
    <businessProcess>Prevision Venta Basica</businessProcess>
    <description>Previsiones de Ventas de Bolsas de Básica</description>
    <label>Previsao</label>
</RecordType>

Salesforce/main/default/main/default/objects/Opportunity/recordTypes/Produccion.recordType-meta.xml
<RecordType>
    <fullName>Produccion</fullName>
    <active>true</active>
    <businessProcess>Control_Multiplicador</businessProcess>
    <description>Detalle de lo que el multiplicador va a sembrar: autorización correspondiente y relatorio de produccion</description>
    <label>Produccion</label>
</RecordType>

Salesforce/main/default/objects/Opportunity/recordTypes/Rechazada.recordType-meta.xml
<RecordType>
    <fullName>Rechazada</fullName>
    <active>true</active>
    <businessProcess>Fc de Brasmax</businessProcess>
    <label>Rechazada</label>
</RecordType>

Salesforce/main/default/main/default/objects/Opportunity/recordTypes/Reembalaje.recordType-meta.xml
<RecordType>
    <fullName>Reembalaje</fullName>
    <active>true</active>
    <businessProcess>Docusign - Anexos</businessProcess>
    <label>Reembalaje</label>
</RecordType>

Salesforce/main/default/main/default/objects/Opportunity/recordTypes/Stock_Multiplicadores.recordType-meta.xml
<RecordType>
    <fullName>Stock_Multiplicadores</fullName>
    <active>true</active>
    <businessProcess>Stock Multiplicadores</businessProcess>
    <label>Stock Multiplicadores</label>
</RecordType>

Salesforce/main/default/main/default/objects/Opportunity/recordTypes/Stock_Multiplicadores_Milho.recordType-meta.xml
<RecordType>
    <fullName>Stock_Multiplicadores_Milho</fullName>
    <active>true</active>
    <businessProcess>Stock Multiplicadores</businessProcess>
    <label>Stock Multiplicadores Milho</label>
</RecordType>

Salesforce/main/default/objects/OpportunityLineItem/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Categoria a ser licenciada</description>
    <inlineHelpText>Categoria a ser licenciada</inlineHelpText>
    <label>Categoria</label>
    <referenceTo>Categoria__c</referenceTo>
    <relationshipLabel>Producto de oportunidad</relationshipLabel>
    <relationshipName>Producto_de_oportunidad</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/OpportunityLineItem/fields/Estado_de_Produccion__c.field-meta.xml
<CustomField>
    <fullName>Estado_de_Produccion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Estado de Produccion</label>
    <referenceTo>Estado__c</referenceTo>
    <relationshipLabel>Producto de oportunidad</relationshipLabel>
    <relationshipName>Producto_de_oportunidad</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/OpportunityLineItem/fields/Estado_Facturacion__c.field-meta.xml
<CustomField>
    <fullName>Estado_Facturacion__c</fullName>
    <label>Estado Facturacion</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Facturado</fullName>
            </value>
            <value>
                <fullName>No facturado</fullName>
                <default>true</default>
                <label>No facturado</label>
            </value>
            <value>
                <fullName>Pasado Pedido</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/OpportunityLineItem/fields/Item_Rebajado__c.field-meta.xml
<CustomField>
    <fullName>Item_Rebajado__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indica si corresponde al ítem generado para restarle la cantidad a la categoría rebajada. Para la sumarizacion en reportes.</description>
    <label>Item Rebajado</label>
    <type>Checkbox</type>
</CustomField>

Salesforce/main/default/objects/OpportunityLineItem/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <formula>TEXT(Opportunity.Safra__c)</formula>
    <label>Safra</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/OpportunityLineItem/fields/Variedade_Prod__c.field-meta.xml
<CustomField>
    <fullName>Variedade_Prod__c</fullName>
    <formula>PricebookEntry.Product2.Variedade__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Nome Comercial</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/Order/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <label>Safra</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Safra</valueSetName>
    </valueSet>
</CustomField>

Salesforce/main/default/globalValueSets/Safra.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>14/15</fullName>
    </customValue>
    <customValue>
        <fullName>15/16</fullName>
    </customValue>
    <customValue>
        <fullName>16/17</fullName>
    </customValue>
    <customValue>
        <fullName>17/18</fullName>
    </customValue>
    <customValue>
        <fullName>18/19</fullName>
    </customValue>
    <customValue>
        <fullName>19/20</fullName>
    </customValue>
    <customValue>
        <fullName>20/21</fullName>
    </customValue>
    <customValue>
        <fullName>21/22</fullName>
    </customValue>
    <customValue>
        <fullName>22/23</fullName>
    </customValue>
    <customValue>
        <fullName>23/24</fullName>
    </customValue>
    <customValue>
        <fullName>08/09</fullName>
        <isActive>false</isActive>
        <label>08/09</label>
    </customValue>
    <customValue>
        <fullName>07/08</fullName>
        <isActive>false</isActive>
        <label>07/08</label>
    </customValue>
    <customValue>
        <fullName>10/11</fullName>
        <isActive>false</isActive>
        <label>10/11</label>
    </customValue>
    <customValue>
        <fullName>11/12</fullName>
        <isActive>false</isActive>
        <label>11/12</label>
    </customValue>
    <customValue>
        <fullName>12/13</fullName>
        <isActive>false</isActive>
        <label>12/13</label>
    </customValue>
    <customValue>
        <fullName>13/14</fullName>
        <isActive>false</isActive>
        <label>13/14</label>
    </customValue>
    <customValue>
        <fullName>09/10</fullName>
        <isActive>false</isActive>
        <label>09/10</label>
    </customValue>
    <masterLabel>Safra</masterLabel>
</GlobalValueSet>

Salesforce/main/default/classes/opportunityExtension.cls
Public class opportunityExtension{

   public opportunityExtension(ApexPages.StandardController controller) {

    Opportunity opp = [SELECT id,RecordType.DeveloperName FROM Opportunity WHERE id =:apexpages.currentpage().getparameters().get('id') ];
    this.recordTypeDevName = opp.RecordType.DeveloperName;
   }

   public String searchTextAnexo {get; set;}
   public List<Opportunity> resultAnexos = new List<Opportunity>();
   public String anexo {get; set;}
   public String etapaAnexo;

   private String rt_anexoI_opps;
   private String rt_anexoII_opps;
   private String rt_anexoIII_opps;
   private String rt_anexoIV_opps;
   private String rt_anexoV_opps;
   private String rt_Previsao_opps;
   private String rt_Previsao_Cerrada_opps;
   private String rt_VB_Fc_opps;
   private String rt_VB_Pe_opps;
   private String rt_VB_Au_opps;
   private String rt_VB_Re_opps;
   private String rt_DB_opps;
   private String rt_PBC_opps;
   private String rt_PBP_opps;
   private String rt_Exp_opps;
   private String rt_Reemb_opps;
   private String rt_Descarte_opps;
   public String recordTypeDevName {get;set;}

   public void setetapaAnexo(String arg){
       etapaAnexo = arg;
   }

   public String getetapaAnexo(){
       Profile pro = [Select Name From Profile Where Id = : UserInfo.getProfileId()];       
       if (pro.Name == 'Administrador del sistema' || pro.Name == 'Gerente Administrativo')
           etapaAnexo = 'PEAP';
       if (pro.Name == 'Comercial')
           etapaAnexo = 'PEAN';    
       if (pro.Name == 'Administrativo')
           etapaAnexo = 'APR';    
   
       return etapaAnexo;
   }
   
   public opportunityExtension(){    
       searchTextAnexo = '';        
       for (RecordType rt : [Select Id, Name From RecordType Where Name in ('Anexo I','Anexo II','Anexo III', 'Anexo IV', 'Anexo V', 'Previsao', 'Previsao Cerrada', 'VB - Pasada SAP', 'VB - Pendiente', 'VB - Autorizada', 'VB - Rechazada', 'Disponibilidade da Basica', 'Exportacion', 'PB-Comercial', 'PB-Produccion', 'Reembalaje', 'Descarte')]){
           if (rt.Name == 'Anexo I')
              rt_anexoI_opps = rt.Id;
           if (rt.Name == 'Anexo II')
              rt_anexoII_opps = rt.Id;
           if (rt.Name == 'Anexo III')
              rt_anexoIII_opps = rt.Id;
           if (rt.Name == 'Anexo IV')
              rt_anexoIV_opps = rt.Id;
           if (rt.Name == 'Anexo V')
              rt_anexoV_opps = rt.Id; 
           if (rt.Name == 'Previsao')
              rt_Previsao_opps = rt.Id;
           if (rt.Name == 'Previsao Cerrada')
              rt_Previsao_Cerrada_opps = rt.Id;              
           if (rt.Name == 'VB - Pasada SAP')
              rt_VB_Fc_opps = rt.Id;
           if (rt.Name == 'VB - Pendiente')
              rt_VB_Pe_opps = rt.Id;
           if (rt.Name == 'VB - Autorizada')
              rt_VB_Au_opps = rt.Id;
           if (rt.Name == 'VB - Rechazada')
              rt_VB_Re_opps = rt.Id;
           if (rt.Name == 'Disponibilidade da Basica')
              rt_DB_opps = rt.id;
           if (rt.Name == 'PB-Comercial')
              rt_PBC_opps = rt.Id;
           if (rt.Name == 'PB-Produccion')
              rt_PBP_opps = rt.Id;
           if (rt.Name == 'Exportacion')
              rt_Exp_opps = rt.Id;
           if (rt.Name == 'Reembalaje')
              rt_Reemb_opps = rt.Id;
           if(rt.Name == 'Descarte')
              rt_Descarte_opps = rt.Id;
       }
   }
       
   public List<Opportunity> getresultAnexos() {return resultAnexos;}    
   
   public List<SelectOption> getTiposAnexos() {
       List<SelectOption> options = new List<SelectOption>();
       options.add(new SelectOption('ALL','--Todos--'));
       options.add(new SelectOption('A1','Anexo I'));
       options.add(new SelectOption('A2','Anexo II'));
       options.add(new SelectOption('A3','Anexo III'));
       options.add(new SelectOption('A4','Anexo IV'));
       options.add(new SelectOption('A5','Anexo V'));
       return options;
   }
   
   public List<SelectOption> getEtapasAnexos() {        
       List<SelectOption> options = new List<SelectOption>();
       options.add(new SelectOption('ALL','--Todas--'));
       options.add(new SelectOption('PEAN','Pendiente de Analisis'));
       options.add(new SelectOption('PEAP','Pendiente de Aprobacion'));
       options.add(new SelectOption('APR','Aprobada'));      
       
       return options;
   }
   
   public Boolean getIsRebaixamento(){
      Boolean resultado = this.recordTypeDevName == 'Anexo_I_Rebaixamento_Ha' || this.recordTypeDevName == 'Anexo_II_Rebaixamento_Sacas';
      return resultado;      
   }
   
   public void listarAnexos(){
       resultAnexos = null;
       this.searchAnexos();       
   }
   
   public void searchAnexos(){
       String s = searchTextAnexo;
       
       String qry = 'select Id, Name, Mes__c, Regiao__r.Name, VB_Franqueado__c, VB_Franqueado__r.Name, StageName, Safra__c, Estado_Facturacion__c, CloseDate, Numero_del__c, Account.Id, Account.Name, Account.Responsavel__c, RecordType.Name, LastModifiedDate, Relatorio_Relacionado__c, Relatorio_Relacionado__r.Name, Nro_Pedido_SAP__c, VB_Cidade__c, Estado_de_Produccion__c From Opportunity ';
       
       qry += 'where OwnerId != null ';
       if (anexo == 'A1')
           qry += ' and RecordTypeId = : rt_anexoI_opps ';
       if (anexo == 'A2')
           qry += ' and RecordTypeId = : rt_anexoII_opps ';
       if (anexo == 'A3')
           qry += ' and RecordTypeId = : rt_anexoIII_opps ';
       if (anexo == 'A4')
           qry += ' and RecordTypeId = : rt_anexoIV_opps ';
       if (anexo == 'A5')
           qry += ' and RecordTypeId = : rt_anexoV_opps ';        
       if (anexo == 'ALL')
           qry += ' and (RecordTypeId = : rt_anexoI_opps OR RecordTypeId = : rt_anexoII_opps OR RecordTypeId = : rt_anexoIII_opps OR RecordTypeId = : rt_anexoIV_opps OR RecordTypeId = : rt_anexoV_opps) ';
           
       if (etapaAnexo == 'PEAN')
           qry += ' and StageName = \'Pendiente de Análisis\'';    
       if (etapaAnexo == 'PEAP')
           qry += ' and StageName = \'Pendiente de Aprobación\'';    
       if (etapaAnexo == 'APR')
           qry += ' and StageName = \'Aprobada\'';                   
                       
       if(s != ''){ s = '%' + s + '%'; qry += ' and Name like : s';}
       qry += ' Order by Nro_Pedido_SAP__c, Safra__c Desc, LastModifiedDate Desc';
       resultAnexos = Database.query(qry);
   }
      
   public List<OpportunityLineItem> getItems() {
       String query = 'SELECT ';
       for(Schema.FieldSetMember f : this.getFields()) {
           query += f.getFieldPath() + ', ';
       }
       query += 'Id FROM OpportunityLineItem Where OpportunityId = \'' + apexpages.currentpage().getparameters().get('id') + '\'';
       query += ' And Item_Rebajado__c = false Order by Variedade_Prod__c';
       return Database.query(query);
   }
   
   public List<Schema.FieldSetMember> getFields() {
        Opportunity opp = [SELECT RecordType.Name, Setor__c, Oportunidad_Relacionada__r.RecordType.Name,RecordType.DeveloperName FROM Opportunity WHERE Id =: apexpages.currentpage().getparameters().get('id')];

        if (opp.RecordType.Name == 'Anexo I')
            return SObjectType.OpportunityLineItem.FieldSets.AnexoI.getFields();
        if (opp.RecordType.Name == 'Anexo II')
            return SObjectType.OpportunityLineItem.FieldSets.AnexoII.getFields();
        if (opp.RecordType.Name == 'Anexo III')
            return SObjectType.OpportunityLineItem.FieldSets.Anexo_III.getFields();  
        if (opp.RecordType.Name == 'Anexo IV')
            return SObjectType.OpportunityLineItem.FieldSets.Anexo_IV.getFields();
        if (opp.RecordType.Name == 'Anexo V')
            return SObjectType.OpportunityLineItem.FieldSets.Anexo_V.getFields();        
        if (opp.RecordType.Name == 'Pendiente')
            return SObjectType.OpportunityLineItem.FieldSets.Pendiente.getFields();    
        if (opp.RecordType.Name == 'NC - Pendiente' || opp.RecordType.Name == 'NC - Autorizada' || opp.RecordType.Name == 'NC - Rechazada')
            return SObjectType.OpportunityLineItem.FieldSets.Nota_de_Credito.getFields();    
        if (opp.RecordType.Name == 'Autorizada')
            return SObjectType.OpportunityLineItem.FieldSets.Autorizada.getFields();    
        if (opp.RecordType.Name == 'Rechazada')
            return SObjectType.OpportunityLineItem.FieldSets.Rechazada.getFields();    
        if (opp.RecordType.Name == 'Anexo I Rebaixamento Ha')           
            return SObjectType.OpportunityLineItem.FieldSets.AnexoI_Rebaixamento.getFields();    
        if (opp.RecordType.Name == 'Anexo II Rebaixamento Sacas')             
            return SObjectType.OpportunityLineItem.FieldSets.Anexo_Rebajamiento_Bolsas.getFields();
        if (opp.RecordType.Name == 'Stock Multiplicadores')
            return SObjectType.OpportunityLineItem.FieldSets.Stock_Multiplicadores.getFields();
        if (opp.RecordType.Name == 'Stock Multiplicadores Milho')
            return SObjectType.OpportunityLineItem.FieldSets.Stock_Multiplicadores_Milho.getFields();           
        if (opp.RecordType.Name == 'Previsao' || opp.RecordType.Name == 'Previsao Cerrada')
            return SObjectType.OpportunityLineItem.FieldSets.Previsao.getFields();
        if (opp.RecordType.Name == 'VB - Pendiente' || opp.RecordType.Name == 'VB - Autorizada' || opp.RecordType.Name == 'VB - Rechazada')
            return SObjectType.OpportunityLineItem.FieldSets.VB_General.getFields();
        if (opp.RecordType.Name == 'VB - Pasada SAP')
            return SObjectType.OpportunityLineItem.FieldSets.VB_SAP.getFields();
        if (opp.RecordType.Name == 'CVB Pendiente') {
            if (opp.Oportunidad_Relacionada__r.RecordType.Name == 'Venda da Basica Completo') { // relacionado a una CVB Completa
                return SObjectType.OpportunityLineItem.FieldSets.CVB_Pendiente_VB_Completa.getFields();
            } else {
                return SObjectType.OpportunityLineItem.FieldSets.CVB_Pendiente.getFields();
            }
        }
        if (opp.RecordType.Name == 'CVB Rechazada' || opp.RecordType.Name == 'CVB Autorizada') {
            if (opp.Oportunidad_Relacionada__r.RecordType.Name == 'Venda da Basica Completo') { // relacionado a una CVB Completa
                return SObjectType.OpportunityLineItem.FieldSets.CVB_Autorizada_VB_Completa.getFields();
            } else {
                return SObjectType.OpportunityLineItem.FieldSets.CVB_Autorizada.getFields();
            }
        }
        if (opp.RecordType.Name == 'Disponibilidade da Basica')
            return SObjectType.OpportunityLineItem.FieldSets.Disponibilidade_da_Basica.getFields();
        if (opp.RecordType.Name == 'PB-Comercial')
            return SObjectType.OpportunityLineItem.FieldSets.Produccion_Basica.getFields();
        if (opp.RecordType.Name == 'Exportacion')
            return SObjectType.OpportunityLineItem.FieldSets.Exportacion.getFields();
        if (opp.RecordType.Name == 'Reembalaje')
            return SObjectType.OpportunityLineItem.FieldSets.Reembalaje.getFields();
        if (opp.RecordType.Name == 'Objetivo Ventas Semilla')
            return SObjectType.OpportunityLineItem.FieldSets.Objetivo_Ventas_Semilla.getFields();
        if (opp.RecordType.Name == 'PB-Desarrollo')
            return SObjectType.OpportunityLineItem.FieldSets.Produccion_Basica_Desarrollo.getFields();
        if (opp.RecordType.Name == 'PB-Produccion' && opp.Setor__c == 'Comercial')
            return SObjectType.OpportunityLineItem.FieldSets.Produccion_Basica.getFields();
        if (opp.RecordType.Name == 'PB-Produccion' && opp.Setor__c == 'Desarrollo')
            return SObjectType.OpportunityLineItem.FieldSets.Produccion_Basica_Desarrollo.getFields();  
        if (opp.RecordType.Name == 'PB-Oferta')
            return SObjectType.OpportunityLineItem.FieldSets.Produccion_Basica_Oferta.getFields();  
        if (opp.RecordType.Name == 'Objetivo Ventas Royalties')
            return SObjectType.OpportunityLineItem.FieldSets.Objetivo_Ventas_Royalties.getFields();
        if (opp.RecordType.Name == 'Estimativa de venda')
            return SObjectType.OpportunityLineItem.FieldSets.Estimativa.getFields();
        if (opp.RecordType.Name == 'Objetivo Contrato Royalties')
            return SObjectType.OpportunityLineItem.FieldSets.Objetivo_Contrato_Royalties.getFields();
        if (opp.RecordType.Name.contains('Antecipação'))
            return SObjectType.OpportunityLineItem.FieldSets.Anticipo.getFields();  
        if (opp.RecordType.Name.contains('Descarte'))
            return SObjectType.OpportunityLineItem.FieldSets.Anexo_Descarte.getFields(); 
        if (opp.RecordType.Name.contains('Aquisição Sementes Terceiros'))
            return SObjectType.OpportunityLineItem.FieldSets.Aquisicion_Sementes_Terceiros.getFields(); 
        if (opp.RecordType.Name == 'Estimativa de Faturamento')
            return SObjectType.OpportunityLineItem.FieldSets.Pendiente.getFields();
        if (opp.RecordType.Name == 'Venda da Basica Completo')
            return SObjectType.OpportunityLineItem.FieldSets.VB_Completa.getFields();
        
        return null;                      
    }
   
   @isTest(SeeAllData=true)
   static void test(){
 
        Map<String,Id> rt = New Map<String, Id>();
        for(RecordType reTy : [Select Id, Name From RecordType Where sObjectType = 'Opportunity'])
            rt.put(reTy.Name, reTy.Id);
     
       opportunityExtension anexos = New opportunityExtension();
       
       anexos.searchAnexos();  
       //anexos.listarAnexos();
       String a;
       anexos.setetapaAnexo(a);
       a = anexos.getetapaAnexo();
       List<SelectOption> op = New List<SelectOption>();
       op = anexos.getEtapasAnexos();
       op = anexos.getTiposAnexos(); 
       anexos.getResultAnexos();      
       List <OpportunityLineItem> items = New List<OpportunityLineItem>();
       
        Categoria__c cat = [SELECT Id, Name FROM Categoria__c WHERE Name = 'BASICA' limit 1];  
        
        Account cuenta = [Select Id From Account Where Name = 'ACME' limit 1];
        Pricebook2 pb = [Select Id, Name From Pricebook2 where Name = 'Lista de Básica BMX SUL' and isActive = true limit 1];
        Opportunity prevision = New Opportunity(RecordTypeId=rt.get('Previsao'), Name='Previsao', AccountId = cuenta.Id,Pricebook2Id=pb.Id, CloseDate=System.today(), Marca__c='BRMX',StageName='Aberta', Safra__c='12/13');
        //insert prevision;
        PricebookEntry pbe = [Select Id, Product2Id From PricebookEntry where Pricebook2Id = :pb.Id and isActive = true and Product2.Categ__c = :cat.Id limit 1];

        OpportunityLineItem oi2 = new OpportunityLineItem(OpportunityId=prevision.Id,Quantity=0.01,Previsao__c = 50,TotalPrice=10,PricebookEntryId=pbe.Id);
        //insert oi2;
       
   }

   @isTest(SeeAllData=true)
   static void test2(){
 
        Map<String,Id> rt = New Map<String, Id>();
        for(RecordType reTy : [Select Id, Name From RecordType Where sObjectType = 'Opportunity'])
            rt.put(reTy.Name, reTy.Id);
     
       opportunityExtension anexos = New opportunityExtension();
           
       List <OpportunityLineItem> items = New List<OpportunityLineItem>();
       
        Categoria__c cat = [SELECT Id, Name FROM Categoria__c WHERE Name = 'BASICA' limit 1];  
        
        Account cuenta = [Select Id From Account Where Name = 'ACME' limit 1];
        Pricebook2 pb = [Select Id, Name From Pricebook2 where Name = 'Lista de Básica BMX SUL' and isActive = true limit 1];
        Opportunity prevision = New Opportunity(RecordTypeId=rt.get('Previsao'), Name='Previsao', AccountId = cuenta.Id,Pricebook2Id=pb.Id, CloseDate=System.today(), Marca__c='BRMX',StageName='Aberta', Safra__c='12/13');
        insert prevision;
        PricebookEntry pbe = [Select Id, Product2Id From PricebookEntry where Pricebook2Id = :pb.Id and isActive = true and Product2.Categ__c = :cat.Id limit 1];

        OpportunityLineItem oi2 = new OpportunityLineItem(OpportunityId=prevision.Id,Quantity=0.01,Previsao__c = 50,TotalPrice=10,PricebookEntryId=pbe.Id);
        insert oi2;
       
       
       ApexPages.currentPage().getParameters().put('id',prevision.Id);
       items = anexos.getItems();
       List<Schema.FieldSetMember> b = anexos.getFields();
       
        Opportunity prueba1 = New Opportunity(RecordTypeId=rt.get('VB - Pendiente'), Name='Prueba1', AccountId = cuenta.Id,Pricebook2Id=pb.Id, CloseDate=System.today(), Marca__c='BRMX',StageName='Aberta', Safra__c='12/13');
        insert prueba1;

        OpportunityLineItem p1oi2 = new OpportunityLineItem(OpportunityId=prevision.Id,Quantity=0.01,Previsao__c = 50,TotalPrice=10,PricebookEntryId=pbe.Id);
        insert p1oi2;
       
       ApexPages.currentPage().getParameters().put('id',prueba1.Id);
        anexos.getFields();
       
        Opportunity prueba2 = New Opportunity(RecordTypeId=rt.get('Disponibilidade da Basica'), Name='Prueba2', AccountId = cuenta.Id,Pricebook2Id=pb.Id, CloseDate=System.today(), Marca__c='BRMX',StageName='Aberta', Safra__c='12/13');
        insert prueba2;

        OpportunityLineItem p2oi2 = new OpportunityLineItem(OpportunityId=prevision.Id,Quantity=0.01,Previsao__c = 50,TotalPrice=10,PricebookEntryId=pbe.Id);
        Test.StartTest();
        insert p2oi2;
        Test.StopTest();
       
       ApexPages.currentPage().getParameters().put('id',prueba2.Id);
        anexos.getFields();

        Opportunity prueba3 = New Opportunity(RecordTypeId=rt.get('Stock Multiplicadores'), Name='Prueba1', AccountId = cuenta.Id,Pricebook2Id=pb.Id, CloseDate=System.today(), Marca__c='BRMX',StageName='Aberta', Safra__c='12/13');
        insert prueba3;

       
       ApexPages.currentPage().getParameters().put('id',prueba3.Id);
       anexos.getFields();    
              
        Opportunity prueba4 = New Opportunity(RecordTypeId=rt.get('Rechazada'), Name='Prueba1', AccountId = cuenta.Id,Pricebook2Id=pb.Id, CloseDate=System.today(), Marca__c='BRMX',StageName='Aberta', Safra__c='12/13');
        insert prueba4;

       
       ApexPages.currentPage().getParameters().put('id',prueba4.Id);
       anexos.getFields();

   }
   
   @isTest(SeeAllData=true)
   static void test3(){
 
        Map<String,Id> rt = New Map<String, Id>();
        for(RecordType reTy : [Select Id, Name From RecordType Where sObjectType = 'Opportunity'])
            rt.put(reTy.Name, reTy.Id);
     
       opportunityExtension anexos = New opportunityExtension();
           
       List <OpportunityLineItem> items = New List<OpportunityLineItem>();
       
        Categoria__c cat = [SELECT Id, Name FROM Categoria__c WHERE Name = 'BASICA' limit 1];  
        
        Account cuenta = [Select Id From Account Where Name = 'ACME' limit 1];
        Pricebook2 pb = [Select Id, Name From Pricebook2 where Name = 'Lista de Básica BMX SUL' and isActive = true limit 1];
        Opportunity prevision = New Opportunity(RecordTypeId=rt.get('Previsao'), Name='Previsao', AccountId = cuenta.Id,Pricebook2Id=pb.Id, CloseDate=System.today(), Marca__c='BRMX',StageName='Aberta', Safra__c='12/13');
        insert prevision;
        PricebookEntry pbe = [Select Id, Product2Id From PricebookEntry where Pricebook2Id = :pb.Id and isActive = true and Product2.Categ__c = :cat.Id limit 1];

        OpportunityLineItem oi2 = new OpportunityLineItem(OpportunityId=prevision.Id,Quantity=0.01,Previsao__c = 50,TotalPrice=10,PricebookEntryId=pbe.Id);
        insert oi2;
       
       
       ApexPages.currentPage().getParameters().put('id',prevision.Id);
       items = anexos.getItems();
       List<Schema.FieldSetMember> b = anexos.getFields();
       
        Opportunity prueba5 = New Opportunity(RecordTypeId=rt.get('Pendiente'), Name='Prueba1', AccountId = cuenta.Id,Pricebook2Id=pb.Id, CloseDate=System.today(), Marca__c='BRMX',StageName='Aberta', Safra__c='12/13');
        insert prueba5;

       
       ApexPages.currentPage().getParameters().put('id',prueba5.Id);
       anexos.getFields();
       
        Opportunity prueba6 = New Opportunity(RecordTypeId=rt.get('Anexo V'), Name='Prueba1', AccountId = cuenta.Id,Pricebook2Id=pb.Id, CloseDate=System.today(), Marca__c='BRMX',StageName='Aberta', Safra__c='12/13');
        insert prueba6;

       
       ApexPages.currentPage().getParameters().put('id',prueba6.Id);
       anexos.getFields();       

         Opportunity prueba7 = New Opportunity(RecordTypeId=rt.get('Anexo IV'), Name='Prueba1', AccountId = cuenta.Id,Pricebook2Id=pb.Id, CloseDate=System.today(), Marca__c='BRMX',StageName='Aberta', Safra__c='12/13');
        Test.StartTest();
        insert prueba7;
        Test.StopTest();

       
       ApexPages.currentPage().getParameters().put('id',prueba7.Id);
       anexos.getFields();

         Opportunity prueba8 = New Opportunity(RecordTypeId=rt.get('Anexo III'), Name='Prueba1', AccountId = cuenta.Id,Pricebook2Id=pb.Id, CloseDate=System.today(), Marca__c='BRMX',StageName='Aberta', Safra__c='12/13');
        insert prueba8;

       
       ApexPages.currentPage().getParameters().put('id',prueba8.Id);
       anexos.getFields();
                  
       anexos.anexo = 'A1';
       anexos.searchAnexos();
       anexos.anexo = 'A2';
       anexos.searchAnexos();
       anexos.anexo = 'A3';
       anexos.searchAnexos();
       anexos.anexo = 'A4';
       anexos.searchAnexos();
       anexos.anexo = 'A5';
       anexos.searchAnexos();
       anexos.anexo = 'ALL';
       anexos.searchAnexos();
       
       anexos.etapaAnexo = 'PEAN';
       anexos.searchAnexos();
       anexos.etapaAnexo = 'PEAP';
       anexos.searchAnexos();
       anexos.etapaAnexo = 'APR';
       anexos.searchAnexos();
       
       for (AggregateResult ar : [Select Max(Id) id, RecordType.Name rt From Opportunity Where RecordType.Name In ('Anexo I', 'Anexo II', 'NC - Autorizada', 'Autorizada', 'Anexo I Rebaixamento Ha', 'Anexo II Rebaixamento Sacas', 'VB - Pasada SAP', 'CVB Autorizada', 'PB-Comercial', 'Exportacion', 'Objetivo Ventas Semilla', 'Objetivo Ventas Royalties', 'Objetivo Contrato Royalties') Group By RecordType.Name]){
           apexpages.currentpage().getparameters().put('Id', String.valueOf(ar.get('id')));
           anexos.getFields();
       }      
   }
   
}