Salesforce/main/default/objects/Account/fields/Responsavel__c.field-meta.xml
<CustomField>
    <fullName>Responsavel__c</fullName>
    <description>Qual dos funcionários da Brasmax que estará responsável pela conta</description>
    <inlineHelpText>Qual dos funcionários da Brasmax que estará responsável pela conta</inlineHelpText>
    <label>Responsável BRMX</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>061 - Fernando Frehner</fullName>
            </value>
            <value>
                <fullName>066 - Marcelo Steffen</fullName>
            </value>
            <value>
                <fullName>067 - Sergio Bertagnolli</fullName>
            </value>
            <value>
                <fullName>076 - Tiago Goulart</fullName>
            </value>
            <value>
                <fullName>083 - Jorge Cristiano Rosa</fullName>
            </value>
            <value>
                <fullName>010 - Brasmax</fullName>
            </value>
            <value>
                <fullName>101 - Fausto Tadeu Fanchin</fullName>
            </value>
            <value>
                <fullName>104 - Otavio Gorni</fullName>
            </value>
            <value>
                <fullName>150 - João Serrano</fullName>
            </value>
            <value>
                <fullName>012 - Anderson Weissheimer</fullName>
            </value>
            <value>
                <fullName>197 - Wagner Rank</fullName>
            </value>
            <value>
                <fullName>198 - Bernardo Zanardo</fullName>
            </value>
            <value>
                <fullName>199 - Lucas Costa</fullName>
            </value>
            <value>
                <fullName>231 - Willian Von Scharten</fullName>
            </value>
            <value>
                <fullName>234 - Julio Cesar Poletto</fullName>
            </value>
            <value>
                <fullName>017 - Luis Fernando Cecatto</fullName>
            </value>
            <value>
                <fullName>018 - Flávio Marçal dos Santos</fullName>
            </value>
            <value>
                <fullName>312 - Lucas Hilario Fantineli</fullName>
            </value>
            <value>
                <fullName>019 - Felipe Oliveira Costa</fullName>
            </value>
            <value>
                <fullName>379 - Diego F. Gonçalves</fullName>
            </value>
            <value>
                <fullName>031 - Guilherme Sousa</fullName>
            </value>
            <value>
                <fullName>023 - Gabriel V. Finatto</fullName>
            </value>
            <value>
                <fullName>464 - Ana Laura Fernandes</fullName>
            </value>
            <value>
                <fullName>467 - Natalie de Mattos</fullName>
            </value>
            <value>
                <fullName>474 - Guilherme Menezes Salau</fullName>
            </value>
            <value>
                <fullName>403 - Felipe Bianchessi</fullName>
            </value>
            <value>
                <fullName>380 - Lucas de Souza Furlan</fullName>
            </value>
            <value>
                <fullName>037 - Felipe Dias Louzada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Opportunity/fields/Estado_Facturacion__c.field-meta.xml
<CustomField>
    <fullName>Estado_Facturacion__c</fullName>
    <label>Estado Facturacion</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>PE Contabilizar</fullName>
            </value>
            <value>
                <fullName>Contabilizada</fullName>
            </value>
            <value>
                <fullName>Impresa</fullName>
            </value>
            <value>
                <fullName>Anulada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Opportunity/fields/Mes__c.field-meta.xml
<CustomField>
    <fullName>Mes__c</fullName>
    <description>Nombre del mes para identificar la oportunidad de control de stock.</description>
    <label>Mês</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Janeiro</fullName>
            </value>
            <value>
                <fullName>Fevereiro</fullName>
            </value>
            <value>
                <fullName>Março</fullName>
            </value>
            <value>
                <fullName>Abril</fullName>
            </value>
            <value>
                <fullName>Maio</fullName>
            </value>
            <value>
                <fullName>Junho</fullName>
            </value>
            <value>
                <fullName>Julho</fullName>
            </value>
            <value>
                <fullName>Agosto</fullName>
            </value>
            <value>
                <fullName>Setembro</fullName>
            </value>
            <value>
                <fullName>Outubro</fullName>
            </value>
            <value>
                <fullName>Novembro</fullName>
            </value>
            <value>
                <fullName>Dezembro</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Opportunity/fields/Nro_Pedido_SAP__c.field-meta.xml
<CustomField>
    <fullName>Nro_Pedido_SAP__c</fullName>
    <externalId>true</externalId>
    <label>Nro Pedido SAP</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/Opportunity/fields/Numero_del__c.field-meta.xml
<CustomField>
    <fullName>Numero_del__c</fullName>
    <label>Numero</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/Opportunity/fields/Regiao__c.field-meta.xml
<CustomField>
    <fullName>Regiao__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Região</label>
    <referenceTo>Regiao__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/Opportunity/fields/Relatorio_Relacionado__c.field-meta.xml
<CustomField>
    <fullName>Relatorio_Relacionado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Relatorio Relacionado</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Opportunity/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <description>Safra o Campania agricola</description>
    <label>Safra</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>06/07</fullName>
            </value>
            <value>
                <fullName>07/08</fullName>
            </value>
            <value>
                <fullName>08/09</fullName>
            </value>
            <value>
                <fullName>09/10</fullName>
            </value>
            <value>
                <fullName>09/09</fullName>
            </value>
            <value>
                <fullName>10/10</fullName>
            </value>
            <value>
                <fullName>10/11</fullName>
            </value>
            <value>
                <fullName>11/11</fullName>
            </value>
            <value>
                <fullName>11/12</fullName>
            </value>
            <value>
                <fullName>12/12</fullName>
            </value>
            <value>
                <fullName>12/13</fullName>
            </value>
            <value>
                <fullName>13/14</fullName>
            </value>
            <value>
                <fullName>14/15</fullName>
            </value>
            <value>
                <fullName>15/16</fullName>
            </value>
            <value>
                <fullName>16/17</fullName>
            </value>
            <value>
                <fullName>17/18</fullName>
            </value>
            <value>
                <fullName>18/19</fullName>
            </value>
            <value>
                <fullName>19/20</fullName>
            </value>
            <value>
                <fullName>20/21</fullName>
            </value>
            <value>
                <fullName>21/22</fullName>
                <default>true</default>
                <label>21/22</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Opportunity/fields/VB_Franqueado__c.field-meta.xml
<CustomField>
    <fullName>VB_Franqueado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Franqueado en la operacion donde el Franqueado le vende semilla basica al Multiplicador</description>
    <inlineHelpText>Franqueado en la operacion donde el Franqueado le vende semilla basica al Multiplicador</inlineHelpText>
    <label>Franqueado</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Oportunidades de Exportação</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/Opportunity/recordTypes/Autorizada.recordType-meta.xml
<RecordType>
    <fullName>Autorizada</fullName>
    <active>true</active>
    <businessProcess>Nota de Venta - Autorizada</businessProcess>
    <label>Autorizada</label>
</RecordType>

Salesforce/main/default/objects/Opportunity/recordTypes/Comercial.recordType-meta.xml
<RecordType>
    <fullName>Comercial</fullName>
    <active>true</active>
    <businessProcess>Control_Multiplicador</businessProcess>
    <description>Detalle de lo que el multiplicador va a vender: relatorio de venda</description>
    <label>Comercial</label>
</RecordType>

Salesforce/main/default/main/default/objects/Opportunity/recordTypes/Pendiente.recordType-meta.xml
<RecordType>
    <fullName>Pendiente</fullName>
    <active>true</active>
    <businessProcess>Nota de Venta - Pendiente</businessProcess>
    <label>Pendiente</label>
</RecordType>

Salesforce/main/default/objects/Opportunity/recordTypes/Rechazada.recordType-meta.xml
<RecordType>
    <fullName>Rechazada</fullName>
    <active>true</active>
    <businessProcess>Fc de Brasmax</businessProcess>
    <label>Rechazada</label>
</RecordType>

Salesforce/main/default/main/default/objects/Order/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <label>Safra</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Safra</valueSetName>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Regiao__c/Regiao__c.object-meta.xml
<CustomObject>
    <label>Región</label>
    <nameField>
        <label>Nome da Região</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regiones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/globalValueSets/Safra.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>14/15</fullName>
    </customValue>
    <customValue>
        <fullName>15/16</fullName>
    </customValue>
    <customValue>
        <fullName>16/17</fullName>
    </customValue>
    <customValue>
        <fullName>17/18</fullName>
    </customValue>
    <customValue>
        <fullName>18/19</fullName>
    </customValue>
    <customValue>
        <fullName>19/20</fullName>
    </customValue>
    <customValue>
        <fullName>20/21</fullName>
    </customValue>
    <customValue>
        <fullName>21/22</fullName>
    </customValue>
    <customValue>
        <fullName>22/23</fullName>
    </customValue>
    <customValue>
        <fullName>23/24</fullName>
    </customValue>
    <customValue>
        <fullName>08/09</fullName>
        <isActive>false</isActive>
        <label>08/09</label>
    </customValue>
    <customValue>
        <fullName>07/08</fullName>
        <isActive>false</isActive>
        <label>07/08</label>
    </customValue>
    <customValue>
        <fullName>10/11</fullName>
        <isActive>false</isActive>
        <label>10/11</label>
    </customValue>
    <customValue>
        <fullName>11/12</fullName>
        <isActive>false</isActive>
        <label>11/12</label>
    </customValue>
    <customValue>
        <fullName>12/13</fullName>
        <isActive>false</isActive>
        <label>12/13</label>
    </customValue>
    <customValue>
        <fullName>13/14</fullName>
        <isActive>false</isActive>
        <label>13/14</label>
    </customValue>
    <customValue>
        <fullName>09/10</fullName>
        <isActive>false</isActive>
        <label>09/10</label>
    </customValue>
    <masterLabel>Safra</masterLabel>
</GlobalValueSet>

Salesforce/main/default/main/default/classes/Opp_NV_tabListados.cls
public with sharing class Opp_NV_tabListados {

    private Integer pageNumber = 0;
    private Integer pageSize = 20;
    private Integer totalPageNumber = 0;
    
    private String safra = '';
    private static String rt_multi_opps = '0124000000010P5';
    private static String rt_comer_opps = '012400000009d91';
    private static String rt_franq_opps = '012400000000zQu';
    private static String rt_fact_opps = '012400000000zQt';
    private static String rt_fact_c_opps = '0124000000010pm';
    private static String rt_rebaja_opps = '012400000009d9B';
    private static String rt_estoque_opps = '01240000000M3D1'; //'012S00000004NSo';    
    private String rt_pendiente_opps;
    private String rt_autorizada_opps;
    private String rt_rechazada_opps;
    private String rt;
    private Account ac = New Account();
    
    private String rt_opp = '';
    private String searchText = '';
    public Opportunity opp {get; set;}
    public List<Opportunity> result = new List<Opportunity>();
    private List<Opportunity> pageResult;

    public Opp_NV_tabListados() {
        this.opp = new Opportunity();
        this.rt = 'PE';
        for (RecordType rt : [Select Id, Name From RecordType Where Name in ('Pendiente','Rechazada','Autorizada')]){
           if (rt.Name == 'Pendiente')
              rt_pendiente_opps = rt.Id;
           if (rt.Name == 'Autorizada')
              rt_autorizada_opps = rt.Id;
           if (rt.Name == 'Rechazada')
              rt_rechazada_opps = rt.Id;
        } 
    }
    
    public String getrt(){                
       return rt;    
    }
    
    public void setrt (String arg){    
       this.rt = arg;    
    }
    
    public List<SelectOption> getRTypes() {
       List<SelectOption> options = new List<SelectOption>();
       options.add(new SelectOption('ALL','--Todos--'));
       options.add(new SelectOption('PE','Pendiente'));
       options.add(new SelectOption('AU','Autorizada'));
       options.add(new SelectOption('RE','Rechazada'));
       return options;
    }
    
    public Account getac(){                
       return ac;    
    }
    
    public void setac (Account arg){    
       this.ac = arg;    
    }
        
    public void listar(){
        result = null;
        totalPageNumber = 0;
        this.search();
        BindData(1);
    }
         
    public String getSearchText() {return searchText;}
    public void setSearchText(String arg) {searchText = arg;}
    public List<Opportunity> getResult() {return pageResult;}
    
    public void search(){
        String qry = 'select Id, Name, Mes__c, Regiao__r.Name, VB_Franqueado__c, VB_Franqueado__r.Name, StageName, Safra__c, Estado_Facturacion__c, CloseDate, Numero_del__c, Account.Id, Account.Name, Account.Responsavel__c, RecordType.Name, LastModifiedDate, Relatorio_Relacionado__c, Relatorio_Relacionado__r.Name, Nro_Pedido_SAP__c From Opportunity ';
        String s = searchText;
        String resp = ac.Responsavel__c;
        String safra = opp.Safra__c;
        String mes = ''; String region;
        List<Id> propIds = new List<Id>();
        propIds = colaboracionOpp(UserInfo.getProfileId());

        //qry += 'where OwnerId in: propIds ';
        qry += 'where OwnerId != null ';
        if (rt == 'PE')
           qry += ' and RecordTypeId = : rt_pendiente_opps ';
        if (rt == 'AU')
           qry += ' and RecordTypeId = : rt_autorizada_opps ';   
        if (rt == 'RE')
           qry += ' and RecordTypeId = : rt_rechazada_opps ';
        if (rt == 'ALL')
           qry += ' and (RecordTypeId = : rt_rechazada_opps OR RecordTypeId = : rt_autorizada_opps OR RecordTypeId = : rt_pendiente_opps) ';
           
        if(s != ''){ s = '%' + s + '%'; qry += ' and Name like : s';}
        if(safra != null){qry += ' and Safra__c = :safra';}
        if(resp != null){qry += ' and Account.Responsavel__c = : resp';}
        //qry += ' Order by Nro_Pedido_SAP__c, Safra__c Desc, LastModifiedDate Desc';        
        qry += ' Order by LastModifiedDate Desc limit 50000';
        system.debug('@JERE ' + qry);
        
        result = Database.query(qry);
        
    }
    
    private List<Id> colaboracionOpp(String profileId){
        List<Id> Ids = new List<Id>();
        //Ids.add('00540000000zsNB');  //Usuario Lilianne
        Ids.add('00540000001RDF0');  //Usuario Deyse        
        Ids.add('00540000000zlzO');  //Usuario Mariano Goria
        if(profileId.substring(0,15) != '00e40000000rQsv')  //Perfil comercial
            Ids.add('00540000000zui4');   //Usuario Brasmax
            
        return Ids;
    }
    
    public Boolean getNewButtonEnabled(){               
        return (UserInfo.getProfileId() == '00e40000000rPTdAAM' || UserInfo.getProfileId() == '00e40000000rQiTAAU' || UserInfo.getProfileId() == '00e40000000rObQAAU');
    }
    
    //--------------------
    public Integer getPageNumber(){
        return pageNumber;
    }
    public Integer getPageSize(){
        return pageSize;
    }
    public Boolean getPreviousButtonEnabled(){
        return !(pageNumber > 1);
    }
    public Boolean getFirstButtonDisabled(){
        return !(pageNumber > 1);
    }
    public Boolean getLastButtonDisabled(){
        if (result == null) return true;
        else
            return ((pageNumber * pageSize) >= result.size());
    }
    public Boolean getNextButtonDisabled(){
        if (result == null) return true;
        else
            return ((pageNumber * pageSize) >= result.size());
    }
    public Integer getTotalPageNumber(){
        if (totalPageNumber == 0 && result != null){
            totalPageNumber = result.size() / pageSize;
            Integer mod = result.size() - (totalPageNumber * pageSize);
            if (mod > 0)
                totalPageNumber++;
        }
        return totalPageNumber;
    }
        
    //----------------------------
    public PageReference lastBtnClick(){
        pageNumber = totalPageNumber - 1;
        BindData(totalPageNumber);
        return null;
    }
    public PageReference nextBtnClick(){
        BindData(pageNumber + 1);
        return null;
    }
    public PageReference previousBtnClick(){
        BindData(pageNumber - 1);
        return null;
    }
    public PageReference firstBtnClick(){
        BindData(1);
        return null;
    }
       
    private void BindData(Integer newPageIndex){        
        if (result == null)
            result = getResult();
        pageResult = new List<Opportunity>();
        Transient Integer counter = 0;
        Transient Integer min = 0;
        Transient Integer max = 0;
        if (newPageIndex > pageNumber){
            min = pageNumber * pageSize;
            max = newPageIndex * pageSize;
        }
        else {
            max = newPageIndex * pageSize;
            min = max - pageSize;
        }
        for(Opportunity a : result){
            counter++;
            if (counter > min && counter <= max)
                pageResult.add(a);
        }
        pageNumber = newPageIndex;
    }
    
    //************************************************
    public static testMethod void testAll(){
        Opp_NV_tabListados c = new Opp_NV_tabListados();    
        
        c.Opp.Safra__c = '15/16';
        
        RecordType rt = [Select Id From RecordType Where Name = 'Pendiente' limit 1];
        
        c.setrt(rt.Id);
        String r = c.getrt();  
        
        Account acc = New Account (Name = 'Prueba');
        insert acc;
        
        c.setac(acc);
        Account a = c.getac();   
        
        c.listar();

        List<SelectOption> selOp = c.getRTypes();     
        
        Opportunity o = new Opportunity(Name='TMP',CloseDate=System.today(),StageName='Aberta',RecordTypeId=rt.Id);
        insert o;
        
        
        c.search();
        
        c.getTotalPageNumber();
        
        c.getResult();
        c.getPageNumber();
        c.getPageSize();
        c.getPreviousButtonEnabled();
        c.getNewButtonEnabled();
        c.getFirstButtonDisabled();
        c.getLastButtonDisabled();
        c.getNextButtonDisabled();        
        c.getTotalPageNumber();
        //c.BindData(1);
        c.firstBtnClick();
        c.getLastButtonDisabled();        
        c.getNextButtonDisabled();
        c.nextBtnClick();
        c.lastBtnClick();
        c.previousBtnClick();
        
        c.setSearchText('TMP');
        System.Assert(c.getSearchText() != null);
        
        c.result = null;
        c.getLastButtonDisabled();
        c.getNextButtonDisabled();
        //c.BindData(1);
        
    }
}