Salesforce/main/default/objects/Recomenda_o_de_variedade__c/Recomenda_o_de_variedade__c.object-meta.xml
<CustomObject>
    <label>Recomendação de variedade</label>
    <nameField>
        <label>Nombre de Recomendação de variedade</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recomendações de variedades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/Recomenda_o_de_variedade__c/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <formula>TEXT(Variedad__r.Marca__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Marca</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/Recomenda_o_de_variedade__c/fields/Regi_o__c.field-meta.xml
<CustomField>
    <fullName>Regi_o__c</fullName>
    <label>Região</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sul</fullName>
            </value>
            <value>
                <fullName>Cerrado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/classes/VariedadRecomendacionesController.cls
public with sharing class VariedadRecomendacionesController extends CultivarsTechnicalInformation {

    /**
     * Retorna el total de registros de Recomendaciones de Variedad según los filtros de Marca, Tecnología y Región ingresados.
     */
    @AuraEnabled
    public static AggregateResult countRecomendaciones(String brand, String technology, String region) {
        return countRecords('Recomenda_o_de_variedade__c',
            new List<List<String>>{
                new List<String>{'Marca__c', brand},
                new List<String>{'Tecnologia__c', technology},
                new List<String>{'Regi_o__c', region}
            }
        );
    }

    @AuraEnabled
    public static List<Recomenda_o_de_variedade__c> getRecomendaciones(Integer queryLimit, Integer queryOffset, String brand, String technology, String region) {
        return getData(Recomenda_o_de_variedade__c.SObjectType, queryLimit, queryOffset,
            new List<List<String>>{
                new List<String>{'Marca__c', brand},
                new List<String>{'Tecnologia__c', technology},
                new List<String>{'Regi_o__c', region}
            }
        );
    }
}