Salesforce/main/default/objects/Produto_de_Requisicao__c/Produto_de_Requisicao__c.object-meta.xml
<CustomObject>
    <label>Produto de Requisição</label>
    <nameField>
        <label>Nombre de Produto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Produtos de Requisição</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/Produto_de_Requisicao__c/fields/Embalagem__c.field-meta.xml
<CustomField>
    <fullName>Embalagem__c</fullName>
    <label>Embalagem</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Saca 60 Mil Sementes</fullName>
            </value>
            <value>
                <fullName>Bag 5 Milhões Sementes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Produto_de_Requisicao__c/fields/Quantidade_de_Sementes__c.field-meta.xml
<CustomField>
    <fullName>Quantidade_de_Sementes__c</fullName>
    <label>Quantidade de Sementes</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/main/default/objects/Produto_de_Requisicao__c/fields/Requisicao_de_compra__c.field-meta.xml
<CustomField>
    <fullName>Requisicao_de_compra__c</fullName>
    <label>Requisição de compra</label>
    <referenceTo>Requisicao_de_compra__c</referenceTo>
    <relationshipLabel>Produtos de Requisição</relationshipLabel>
    <relationshipName>Produtos_de_Requisicao</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Salesforce/main/default/main/default/objects/Produto_de_Requisicao__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <formula>TEXT(Requisicao_de_compra__r.Tipo__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tipo</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/Produto_de_Requisicao__c/fields/Tratamento__c.field-meta.xml
<CustomField>
    <fullName>Tratamento__c</fullName>
    <label>Tratamento</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Embalagem__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tratamento A</fullName>
            </value>
            <value>
                <fullName>Tratamento B</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Produto_de_Requisicao__c/fields/Variedad__c.field-meta.xml
<CustomField>
    <fullName>Variedad__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Variedad</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1 AND 2</booleanFilter>
        <filterItems>
            <field>Variedad__c.Disponivel_para_venda_basica__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Variedad__c.Cultura__c</field>
            <operation>equals</operation>
            <value>MILHO</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Variedad__c</referenceTo>
    <relationshipLabel>Produtos de Requisição</relationshipLabel>
    <relationshipName>Produtos_de_Requisicao</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/Produto_de_Requisicao__c/recordTypes/Milho.recordType-meta.xml
<RecordType>
    <fullName>Milho</fullName>
    <active>true</active>
    <label>Milho</label>
</RecordType>

Salesforce/main/default/objects/Requisicao_de_compra__c/Requisicao_de_compra__c.object-meta.xml
<CustomObject>
    <label>Estimativas</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Número de requisito</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Estimativas</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Salesforce/main/default/objects/Requisicao_de_compra__c/fields/Requisicao_de_compra__c.field-meta.xml
<CustomField>
    <fullName>Requisicao_de_compra__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Número da Estimativa Subsequente</label>
    <referenceTo>Requisicao_de_compra__c</referenceTo>
    <relationshipName>Requisitos_de_compra</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/Requisicao_de_compra__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Multiplicador</fullName>
            </value>
            <value>
                <fullName>Supervisor</fullName>
            </value>
            <value>
                <fullName>Gerente Comercial</fullName>
            </value>
            <value>
                <fullName>Gerente</fullName>
                <isActive>false</isActive>
                <label>Gerente</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Requisicao_de_compra__c/recordTypes/Milho.recordType-meta.xml
<RecordType>
    <fullName>Milho</fullName>
    <active>true</active>
    <label>Milho</label>
</RecordType>

Salesforce/main/default/main/default/objects/Variedad__c/Variedad__c.object-meta.xml
<CustomObject>
    <description>Variedades, disponibles para incluir en los Contratos de Multiplicación</description>
    <label>Variedad</label>
    <nameField>
        <label>Nome Comercial</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Variedades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/classes/ProductoDeRequisicaoHelper.cls
/**
* @name ProductoDeRequisicaoHelper
* @author Jhonny Peroza
* @since 28-06-2021
*/
public class ProductoDeRequisicaoHelper {
    public static void updateRequisitionProduct(Produto_de_Requisicao__c requisitionProduct) {
        Id milhoRecordType = Schema.SObjectType.Produto_de_Requisicao__c.getRecordTypeInfosByDeveloperName().get('Milho').getRecordTypeId();
        Produto_de_Requisicao__c queryProduct = [SELECT Id, Name, Tipo__c, RecordTypeId, Requisicao_de_compra__c, Variedad__r.Name, Embalagem__c, Tratamento__c, Quantidade__c, quantidade_de_sementes__c 
                                                    FROM Produto_de_Requisicao__c
                                                        WHERE Id =: requisitionProduct.Id LIMIT 1];
        
        if(queryProduct.RecordTypeId == milhoRecordType && queryProduct.Tipo__c == 'Multiplicador') {

            queryProduct.Name = queryProduct.Variedad__r.Name + '-' + queryProduct.Embalagem__c + '-' + queryProduct.Tratamento__c; 
            queryProduct.quantidade_de_sementes__c = queryProduct.Embalagem__c == 'Saca 60 Mil Sementes' ? queryProduct.Quantidade__c * 60000 : queryProduct.Quantidade__c * 5000000;

            try {
                update queryProduct;
            } catch (DmlException e) {
                System.debug('DML Error message: ' + e.getMessage());
            } 
        }

        if(queryProduct.RecordTypeId == milhoRecordType && queryProduct.Tipo__c != 'Multiplicador') {

            Requisicao_de_compra__c queryRequisicao = [SELECT Id, Tipo__c, RecordType.Name 
                                                          FROM Requisicao_de_compra__c 
                                                            WHERE Requisicao_de_compra__c =: queryProduct.Requisicao_de_compra__c LIMIT 1];

            Produto_de_Requisicao__c queryProductTwo = [SELECT Id, Name, Embalagem__c, Quantidade_de_Sementes__c, RecordTypeId 
                                                          FROM Produto_de_Requisicao__c 
                                                            WHERE Requisicao_de_compra__c =: queryRequisicao.Id LIMIT 1];

            queryProduct.Name = queryProductTwo.Name;
            queryProduct.RecordTypeId = queryProductTwo.RecordTypeId;
            queryProduct.Embalagem__c = queryProductTwo.Embalagem__c;
            queryProduct.Quantidade_de_Sementes__c = queryProductTwo.Embalagem__c == 'Saca 60 Mil Sementes' ? requisitionProduct.Quantidade__c * 60000 : requisitionProduct.Quantidade__c * 5000000;

            try {
                update queryProduct;
            } catch (DmlException e) {
                System.debug('DML Error message: ' + e.getMessage());
            } 
        } 
    }
}