Salesforce/main/default/objects/Contact/fields/Quantidade_KG_Total_DMValoriza__c.field-meta.xml
<CustomField>
    <fullName>Quantidade_KG_Total_DMValoriza__c</fullName>
    <label>Quantidade KG Total DMValoriza</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/main/default/objects/Contact/fields/Total_NFe__c.field-meta.xml
<CustomField>
    <fullName>Total_NFe__c</fullName>
    <label>Total NFe</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/main/default/objects/Contact/fields/Valor_Total_Bonificacao_DMValoriza__c.field-meta.xml
<CustomField>
    <fullName>Valor_Total_Bonificacao_DMValoriza__c</fullName>
    <label>Valor Total Bonificação DMValoriza</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/objects/Nota_Fiscal_Eletr_nica__c/Nota_Fiscal_Eletr_nica__c.object-meta.xml
<CustomObject>
    <label>Nota Fiscal Eletrônica</label>
    <nameField>
        <displayFormat>NFE-{00000}</displayFormat>
        <label>Numero de Nota Fiscal Eletrônica</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notas fiscais eletrônicas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/Nota_Fiscal_Eletr_nica__c/fields/Quantidade_KG_Total_NF__c.field-meta.xml
<CustomField>
    <fullName>Quantidade_KG_Total_NF__c</fullName>
    <description>Marca en tiempo real la cantidad total de Quantidade KG de productos asociados a la Nota Fiscal</description>
    <label>Quantidade KG Total NF</label>
    <summarizedField>Produto_da_nota_fiscal__c.Quantidade_KG__c</summarizedField>
    <summaryForeignKey>Produto_da_nota_fiscal__c.Nota_Fiscal_Eletr_nica__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

Salesforce/main/default/objects/Nota_Fiscal_Eletr_nica__c/fields/Valor_Total_Bonificacao_NF__c.field-meta.xml
<CustomField>
    <fullName>Valor_Total_Bonificacao_NF__c</fullName>
    <label>Valor Total Bonificação NF</label>
    <summarizedField>Produto_da_nota_fiscal__c.Valor_Bonificacao__c</summarizedField>
    <summaryForeignKey>Produto_da_nota_fiscal__c.Nota_Fiscal_Eletr_nica__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

Salesforce/main/default/main/default/objects/Nota_Fiscal_Eletr_nica__c/fields/Vendedor__c.field-meta.xml
<CustomField>
    <fullName>Vendedor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendedor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Notas fiscais eletrônicas</relationshipLabel>
    <relationshipName>Notas_fiscais_eletr_nicas</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/classes/NotaFiscalElectronicaHelper.cls
public class NotaFiscalElectronicaHelper {

    public static void updateVendedoresCounters(Set<Id> vendedoresIds) {
        Map<Id, Contact> vendedoresById = new Map<Id, Contact>();
        
        for(Contact vendedor : [ 
        	SELECT Id, Valor_Total_Bonificacao_DMValoriza__c, Quantidade_KG_Total_DMValoriza__c,
            	Total_NFe__c
        	FROM Contact
            WHERE Id IN :vendedoresIds
        ]) {
            // Reseteo los contadores ya que vamos a empezar a contar desde 0
            vendedor.Valor_Total_Bonificacao_DMValoriza__c = 0;
          	vendedor.Quantidade_KG_Total_DMValoriza__c = 0;
            vendedor.Total_NFe__c = 0;
            
            vendedoresById.put(vendedor.Id, vendedor);
        }
        
        if(vendedoresById.size() > 0) {
            for(Nota_Fiscal_Eletr_nica__c notaFiscal : [
                SELECT Id, Vendedor__c, Quantidade_KG_Total_NF__c, Valor_Total_Bonificacao_NF__c
                FROM Nota_Fiscal_Eletr_nica__c
                WHERE Vendedor__c IN :vendedoresIds
            ]) {
                if(vendedoresById.containsKey(notaFiscal.Vendedor__c)) {
                    Contact vendedor = vendedoresById.get(notaFiscal.Vendedor__c);
                                       
                    if(notaFiscal.Valor_Total_Bonificacao_NF__c != null) {
                        if(vendedor.Valor_Total_Bonificacao_DMValoriza__c == 0) {
                            vendedor.Valor_Total_Bonificacao_DMValoriza__c = notaFiscal.Valor_Total_Bonificacao_NF__c;
                        } else {
                            vendedor.Valor_Total_Bonificacao_DMValoriza__c += notaFiscal.Valor_Total_Bonificacao_NF__c;
                        }
                    }
                    
                    if(notaFiscal.Quantidade_KG_Total_NF__c != null) {
                        if(vendedor.Quantidade_KG_Total_DMValoriza__c == 0) {
                            vendedor.Quantidade_KG_Total_DMValoriza__c = notaFiscal.Quantidade_KG_Total_NF__c;
                        } else {
                            vendedor.Quantidade_KG_Total_DMValoriza__c += notaFiscal.Quantidade_KG_Total_NF__c;
                        }
                    }
                    
                    vendedor.Total_NFe__c++;
                    vendedoresById.put(vendedor.Id, vendedor);
                }
            }
            
            update vendedoresById.values();
        }
    }
    
}