Salesforce/main/default/objects/Docusign_Config__mdt/Docusign_Config__mdt.object-meta.xml
<CustomObject>
    <label>Docusign Config</label>
    <pluralLabel>Docusign Configs</pluralLabel>
</CustomObject>

Salesforce/main/default/objects/Docusign_Config__mdt/fields/Account_Id__c.field-meta.xml
<CustomField>
    <fullName>Account_Id__c</fullName>
    <label>Account Id</label>
    <length>36</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/Docusign_Config__mdt/fields/Authentication_URL__c.field-meta.xml
<CustomField>
    <fullName>Authentication_URL__c</fullName>
    <label>Authentication URL</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/Docusign_Config__mdt/fields/Certificate_Name__c.field-meta.xml
<CustomField>
    <fullName>Certificate_Name__c</fullName>
    <label>Certificate Name</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/Docusign_Config__mdt/fields/Integration_Key__c.field-meta.xml
<CustomField>
    <fullName>Integration_Key__c</fullName>
    <inlineHelpText>Alias: Client Id</inlineHelpText>
    <label>Integration Key</label>
    <length>36</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/Docusign_Config__mdt/fields/User_Id__c.field-meta.xml
<CustomField>
    <fullName>User_Id__c</fullName>
    <label>User Id</label>
    <length>36</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/classes/Docusign_Config.cls
public class Docusign_Config {

    public static String getValueByName(String fieldName) {
        String developerName = isProduction() ? 'PRODUCTION' : 'SANDBOX';
        Docusign_Config__mdt docusignConfigObject = [SELECT Account_Id__c, Authentication_URL__c, Certificate_Name__c, Integration_Key__c, User_Id__c FROM Docusign_Config__mdt WHERE DeveloperName = :developerName LIMIT 1];
        return ((String) docusignConfigObject.get(fieldName));

    }
    
    public static Boolean isProduction() {
        return ![SELECT Id, IsSandbox FROM Organization LIMIT 1].IsSandbox;
    }
}