Salesforce/main/default/main/default/objects/Variedad__c/Variedad__c.object-meta.xml
<CustomObject>
    <description>Variedades, disponibles para incluir en los Contratos de Multiplicación</description>
    <label>Variedad</label>
    <nameField>
        <label>Nome Comercial</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Variedades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/Votacion__c/Votacion__c.object-meta.xml
<CustomObject>
    <description>Registro de las votaciones de los Multiplicadores</description>
    <label>Votacion</label>
    <nameField>
        <label>Nombre de Votacion</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Votaciones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/objects/Votacion__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Votaciones</relationshipLabel>
    <relationshipName>Votaciones</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Votacion__c/fields/Producto__c.field-meta.xml
<CustomField>
    <fullName>Producto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Selecciona el producto que se facturó(básica) para obtener la Variedad</description>
    <inlineHelpText>Selecione o produto que foi anunciado (básico) para a variedade</inlineHelpText>
    <label>Producto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Votaciones</relationshipLabel>
    <relationshipName>Votaciones</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/Votacion__c/fields/Region_Comercial__c.field-meta.xml
<CustomField>
    <fullName>Region_Comercial__c</fullName>
    <label>Region Comercial</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SUL</fullName>
            </value>
            <value>
                <fullName>CERRADO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Votacion__c/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <label>Safra</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>20/21</fullName>
            </value>
            <value>
                <fullName>19/20</fullName>
            </value>
            <value>
                <fullName>18/19</fullName>
            </value>
            <value>
                <fullName>17/18</fullName>
            </value>
            <value>
                <fullName>15/16</fullName>
            </value>
            <value>
                <fullName>14/15</fullName>
            </value>
            <value>
                <fullName>13/14</fullName>
            </value>
            <value>
                <fullName>12/13</fullName>
            </value>
            <value>
                <fullName>11/12</fullName>
            </value>
            <value>
                <fullName>21/22</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Votacion__c/fields/Valor__c.field-meta.xml
<CustomField>
    <fullName>Valor__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Valor</label>
    <precision>15</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/main/default/objects/Votacion__c/fields/Variedad__c.field-meta.xml
<CustomField>
    <fullName>Variedad__c</fullName>
    <description>Variedade, como o valor inserido no produto</description>
    <formula>Producto__r.Variedade__r.Name</formula>
    <inlineHelpText>Variedade, como o valor inserido no produto</inlineHelpText>
    <label>Variedad</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/Votacion__c/fields/Vuelta__c.field-meta.xml
<CustomField>
    <fullName>Vuelta__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Vuelta</label>
    <precision>1</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/main/default/classes/votosRealizadosAPI.cls
@RestResource(urlMapping='/votosRealizadosAPI/*')
global with sharing class votosRealizadosAPI {

    @HttpGet
    global static void getMisVotos() {

        String regionCuenta = RestContext.request.params.get('regionCuenta');
        String accountId = RestContext.request.params.get('accountId');
        String safra = RestContext.request.params.get('safra');
        String vuelta = RestContext.request.params.get('vuelta');

        RestResponse response = RestContext.response;
        response.statusCode = 404;

        Response result = new Response();
        result.status = false;

        try {

            List<Votacion__c> votes = getVotacionesByAccount(accountId, safra, regionCuenta, Integer.valueOf(vuelta));
            List<VotoWrapper> voteList = new List<VotoWrapper>();

            if(!votes.isEmpty()) {

                VotoWrapper votacionData;

                for (Votacion__c vote : votes) {
                  
                    votacionData = new VotoWrapper();
                    votacionData.name = vote.Variedad__c;
                    votacionData.data = Double.valueOf(vote.Valor__c);
                    votacionData.productId = vote.Producto__c;
                    voteList.add(votacionData);
                }

                result.listaDeVotos = voteList;
                result.message = Label.votosRealizadosAPI_Success_Message;
                result.status = true;
                response.statusCode = 200;
                
            } else {

                result.message = Label.votosRealizadosAPI_Default_Error_Message;
                result.status = false;
                response.statusCode = 404;
            }

            response.responseBody = Blob.valueOf(JSON.serialize(result));

        } catch (Exception e) {

            result.message = e.getMessage();            
        }
    }

    public static List<Votacion__c> getVotacionesByAccount(String accId, String safra, String region, Integer vuelta){
                 
        return [Select Variedad__c, Valor__c, Producto__c From Votacion__c Where Cuenta__c = :accId And Safra__c = :safra And Region_Comercial__c = :region And Vuelta__c = :vuelta];
    }

    public class VotoWrapper {
        public String name {get;set;}
        public Double data {get;set;}
        public Id productId {get;set;}
    }

    public class Response {

        public String message;
        public Boolean status;
        public List<VotoWrapper> listaDeVotos;
    }
}