Salesforce/main/default/objects/Item_del_Contrato__c/Item_del_Contrato__c.object-meta.xml
<CustomObject>
    <description>Item de CONTRATO DE LICENCIAMENTO PARA MULTIPLICAÇÃO E COMERCIALIZAÇÃO</description>
    <label>Item del Contrato</label>
    <nameField>
        <label>Nombre de Item del Contrato</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items del Contrato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Salesforce/main/default/objects/Item_del_Contrato__c/fields/Cultivar__c.field-meta.xml
<CustomField>
    <fullName>Cultivar__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Cultivar por el/los que se confecciona el contrato</description>
    <inlineHelpText>Cultivar por el/los que se confecciona el contrato</inlineHelpText>
    <label>Cultivar</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Items del Contrato</relationshipLabel>
    <relationshipName>Items_del_Contrato</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/Item_del_Contrato__c/fields/Variedad__c.field-meta.xml
<CustomField>
    <fullName>Variedad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Variedade</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Marca__c</field>
            <operation>equals</operation>
            <valueField>Variedad__c.Sociedad__c</valueField>
        </filterItems>
        <filterItems>
            <field>Variedad__c.Ativa__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Variedad__c</referenceTo>
    <relationshipLabel>Items del Contrato</relationshipLabel>
    <relationshipName>Items_del_Contrato</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/Item_del_Contrato__c/fields/Variedade__c.field-meta.xml
<CustomField>
    <fullName>Variedade__c</fullName>
    <formula>Cultivar__r.Variedade__r.Name</formula>
    <label>Variedade do Cultivar</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/Product2/fields/Variedad__c.field-meta.xml
<CustomField>
    <fullName>Variedad__c</fullName>
    <label>Variedad</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Licenciada__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>BMX APOLO RR</fullName>
            </value>
            <value>
                <fullName>BMX IMPACTO RR</fullName>
            </value>
            <value>
                <fullName>BMX MAGNA RR</fullName>
            </value>
            <value>
                <fullName>BMX POTÊNCIA RR</fullName>
            </value>
            <value>
                <fullName>BMX TITAN RR</fullName>
            </value>
            <value>
                <fullName>BMX FORÇA RR</fullName>
            </value>
            <value>
                <fullName>BMX ENERGIA RR</fullName>
            </value>
            <value>
                <fullName>BMX ATIVA RR</fullName>
            </value>
            <value>
                <fullName>BMX TURBO RR</fullName>
            </value>
            <value>
                <fullName>BMX VELOZ RR</fullName>
            </value>
            <value>
                <fullName>BMX ALVO RR</fullName>
            </value>
            <value>
                <fullName>BMX TORNADO RR</fullName>
            </value>
            <value>
                <fullName>BMX CLASSE RR</fullName>
            </value>
            <value>
                <fullName>BMX DESAFIO RR</fullName>
            </value>
            <value>
                <fullName>BMX RAÇA RR</fullName>
            </value>
            <value>
                <fullName>BMX PROGRESSO RR</fullName>
            </value>
            <value>
                <fullName>BRASMAX ELITE IPRO</fullName>
            </value>
            <value>
                <fullName>BRASMAX FLECHA IPRO</fullName>
            </value>
            <value>
                <fullName>BRASMAX BONUS IPRO</fullName>
            </value>
            <value>
                <fullName>BRASMAX BRAVA</fullName>
            </value>
            <value>
                <fullName>BRASMAX CLASSE</fullName>
            </value>
            <value>
                <fullName>BRASMAX PRISMA</fullName>
            </value>
            <value>
                <fullName>BRASMAX OPUS IPRO</fullName>
            </value>
            <value>
                <fullName>BRASMAX LANÇA IPRO</fullName>
            </value>
            <value>
                <fullName>BRASMAX GARRA IPRO</fullName>
            </value>
            <value>
                <fullName>BRASMAX ÍCONE IPRO</fullName>
            </value>
            <value>
                <fullName>BRASMAX POWER IPRO</fullName>
            </value>
            <value>
                <fullName>68I69RSF IPRO</fullName>
            </value>
            <value>
                <fullName>75I76RSF IPRO</fullName>
            </value>
            <value>
                <fullName>81I84RSF IPRO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Product2/fields/Variedade__c.field-meta.xml
<CustomField>
    <fullName>Variedade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Variedade</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Variedad__c.Licenciada__c</field>
            <operation>equals</operation>
            <valueField>$Source.Licenciada__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Variedad__c</referenceTo>
    <relationshipLabel>Productos</relationshipLabel>
    <relationshipName>Productos</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/SiteUser__c/SiteUser__c.object-meta.xml
<CustomObject>
    <description>Forma parte del circuito del Sitio Portal Web.</description>
    <label>SiteUser</label>
    <nameField>
        <label>Nombre de Usuário</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SiteUsers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/SiteUserSession__c/SiteUserSession__c.object-meta.xml
<CustomObject>
    <label>SiteUserSession</label>
    <nameField>
        <displayFormat>S{00000000}</displayFormat>
        <label>Nombre de SiteUserSession</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SiteUserSessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/SiteUserSession__c/fields/SiteUser__c.field-meta.xml
<CustomField>
    <fullName>SiteUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SiteUser</label>
    <referenceTo>SiteUser__c</referenceTo>
    <relationshipLabel>SiteUserSessions</relationshipLabel>
    <relationshipName>SiteUserSessions</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Variedad__c/Variedad__c.object-meta.xml
<CustomObject>
    <description>Variedades, disponibles para incluir en los Contratos de Multiplicación</description>
    <label>Variedad</label>
    <nameField>
        <label>Nome Comercial</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Variedades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/Votacion__c/Votacion__c.object-meta.xml
<CustomObject>
    <description>Registro de las votaciones de los Multiplicadores</description>
    <label>Votacion</label>
    <nameField>
        <label>Nombre de Votacion</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Votaciones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/Votacion__c/fields/Producto__c.field-meta.xml
<CustomField>
    <fullName>Producto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Selecciona el producto que se facturó(básica) para obtener la Variedad</description>
    <inlineHelpText>Selecione o produto que foi anunciado (básico) para a variedade</inlineHelpText>
    <label>Producto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Votaciones</relationshipLabel>
    <relationshipName>Votaciones</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/Votacion__c/fields/Valor__c.field-meta.xml
<CustomField>
    <fullName>Valor__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Valor</label>
    <precision>15</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/main/default/objects/Votacion__c/fields/Variedad__c.field-meta.xml
<CustomField>
    <fullName>Variedad__c</fullName>
    <description>Variedade, como o valor inserido no produto</description>
    <formula>Producto__r.Variedade__r.Name</formula>
    <inlineHelpText>Variedade, como o valor inserido no produto</inlineHelpText>
    <label>Variedad</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/Votacion_balotage__c/Votacion_balotage__c.object-meta.xml
<CustomObject>
    <description>Tabla auxiliar para la segunda vuelta de votación. Con los 2 valores máximos para el caso en que participe de la segunda vuelta.</description>
    <label>Votacion_balotage</label>
    <nameField>
        <label>Votacion_balotage</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Valores de votacion</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/Votacion_balotage__c/fields/Producto__c.field-meta.xml
<CustomField>
    <fullName>Producto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Producto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Valores de votacion</relationshipLabel>
    <relationshipName>Valores_de_votacion</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/Votacion_balotage__c/fields/valor1__c.field-meta.xml
<CustomField>
    <fullName>valor1__c</fullName>
    <description>valor + votado en la primer vuelta</description>
    <inlineHelpText>valor + votado en la primer vuelta</inlineHelpText>
    <label>valor1</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/objects/Votacion_balotage__c/fields/valor2__c.field-meta.xml
<CustomField>
    <fullName>valor2__c</fullName>
    <description>2º más votado, el segundo valor en cantidad de votos</description>
    <inlineHelpText>2º más votado, el segundo valor en cantidad de votos</inlineHelpText>
    <label>valor2</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/objects/Votacion_balotage__c/fields/Variedad__c.field-meta.xml
<CustomField>
    <fullName>Variedad__c</fullName>
    <label>Variedad</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/classes/aSiteVotacionController.cls
global without sharing class aSiteVotacionController {

	private String token;
    private SiteUser__c logUser;
    private SiteUserSession__c activeSession;
    private Account activeAccount;
    private String safraActual;
    
    public List<SelectOption> optionVariedad {get; set;}
    public Map<String, String> mapVariedades {get; set;}
    public String variedad {get; set;}
    public String valor {get; set;}
    public Integer vuelta {get; set;}
    private Map<String, List<String>> preciosBalotage;
    public List<SelectOption> optionsPrecio {get; set;}
    public Boolean generaVoto {get;set;}
    
    public String language {get;set;}
    public String mensaje {get;set;}
    public String regionCuenta {get;set;}
    
    public Boolean habilitadoVotar {get;set;}
    
    public List<PieWedgeData> PieData {get;set;}
    public List<PieWedgeData> PieData2 {get;set;}
        
    public class PieWedgeData {
        public String name { get; set; }
        public Double data { get; set; }

        public PieWedgeData(String name, Double data) {
            this.name = name;
            this.data = data;
        }
    }
    
    global aSiteVotacionController () {
        try{
            language = [select id, LanguageLocaleKey from User where id =: UserInfo.getUserId()].LanguageLocaleKey;
            
            PieData = new List<PieWedgeData>();
            PieData2 = new List<PieWedgeData>();            											                                                                               	
        }
        catch(Exception e){
        }
    }
    
    public PageReference validate() {        
        token = System.currentPageReference().getParameters().get('token');

        if(token!=null){
            logUser = aSiteAuthManager.VerifyUserSession(token);
            if(logUser!=null){
                activeSession = aSiteAuthManager.getUserSession(token);
                activeAccount = aSiteAuthManager.getActiveAccount_byUser(logUser);
                safraActual = aVotacionManager.getSafraActualVotacion();  
                regionCuenta = aVotacionManager.getRegionCuenta(activeAccount.Id);
                habilitadoVotar = aVotacionManager.getHabilitadoVotacion(regionCuenta);
                vuelta = aVotacionManager.getNroVuelta(regionCuenta);
                cargarVariedades();  
                //cargarResumenVotos();                                          
                return null;  
            }          
        }
        
        PageReference p = new PageReference('/apex/aSiteLogin');
        String marca = aSiteAuthManager.getMarcaBySession(token);
        if (marca != null)
        	p.getParameters().put('comp',marca);
        p.setRedirect(true);
        return p;
    }    
    
    public void cargarVariedades(){
    	optionVariedad = New List<SelectOption>();
        optionVariedad.add(new SelectOption('--Nenhuma--', '--Nenhuma--'));
        mapVariedades = New Map <String, String>();
        if (vuelta == 1){
        	for (Item_del_Contrato__c i : aVotacionManager.getVariedadesHabilitadas(activeAccount.Id, safraActual)){
            	optionVariedad.add(new SelectOption(i.Cultivar__c, i.Cultivar__r.Variedade__r.Name));
            	mapVariedades.put(i.Cultivar__c, i.Cultivar__r.Variedade__r.Name);
        	}
        }
        if (vuelta == 2){
        	preciosBalotage = New Map<String, List<String>>();
        	for (Votacion_balotage__c i : aVotacionManager.getVariedadesBalotage(safraActual, regionCuenta)){
            	optionVariedad.add(new SelectOption(i.Producto__c, i.Variedad__c));
            	mapVariedades.put(i.Producto__c, i.Variedad__c);
            	List<String> precios = New List<String>();
            	precios.add(String.valueOf(i.valor1__c));
            	precios.add(String.valueOf(i.valor2__c));
            	preciosBalotage.put(i.Producto__c, precios);
        	}
        }
    }   
    
    public void changeVariedad(){
    	PieData = new List<PieWedgeData>();
    	for (AggregateResult ar : aVotacionManager.getVotacionVariedad(variedad, safraActual, regionCuenta, vuelta))
    		PieData.add(new PieWedgeData(String.valueOf(ar.get('valor')), Double.valueOf(ar.get('porc'))));    	
    	
    	if (vuelta == 2){
    		optionsPrecio = New List<SelectOption>();
    		List<String> precios = New List<String>();
    		precios = preciosBalotage.get(variedad);
    		if (precios != null && precios.size() > 0)
    			for (String s : precios)
    				optionsPrecio.add(new SelectOption(s,s));    		
    	}
    	
    	valor = null;
    } 
    
    public void cargarResumenVotos(){
    	PieData2 = new List<PieWedgeData>();
    	for (Votacion__c v : aVotacionManager.getVotacionesByAccount(activeAccount.Id, safraActual, regionCuenta, vuelta))
    		PieData2.add(new PieWedgeData(v.Variedad__c, Double.valueOf(v.Valor__c)));    	    	    
    } 
    
    public void generarVotacion(){
    	
    	generaVoto = false;
    	String valDatos = aVotacionManager.valDatos(variedad, valor);
    	if (valDatos == ''){
    		generaVoto = true;
    		mensaje = 'Deseja avançar com o valor ' + valor + ' para a votação da variedade ' + mapVariedades.get(variedad) + '? Apos confirmar, não será possível alteração do valor.';
    	}else{
    		mensaje = valDatos;
    	}
    }
    
    public PageReference saveVotacion(){                
        
        mensaje = '';
        
        try{                                               
            aSiteUtils.retorno ret = aVotacionManager.votar(activeAccount.Id, variedad, valor, safraActual, regionCuenta, vuelta);
                                                       
            if (ret.exito == true){
            	mensaje = 'Seu voto foi registrado com sucesso.';
            }else{
                mensaje = ret.mensaje;
                return null;
            } 
            
            changeVariedad();
                                    
        }catch(Exception e){          
            mensaje = e.getMessage();
            return null;
        }        
        
        aAppManager.updateSession(activeSession);
                
        return null;
        
    }		
    
}