Salesforce/main/default/main/default/objects/Attachment_Content__c/Attachment_Content__c.object-meta.xml
<CustomObject>
    <label>Attachment Content</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attachments Contents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/objects/Attachment_Content__c/fields/CRM_Calendario_de_Eventos__c.field-meta.xml
<CustomField>
    <fullName>CRM_Calendario_de_Eventos__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CRM Evento</label>
    <referenceTo>CRM_Calendario_de_Eventos__c</referenceTo>
    <relationshipLabel>Attachments Contents</relationshipLabel>
    <relationshipName>Attachments_Contents</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/Attachment_Content__c/fields/Show_File__c.field-meta.xml
<CustomField>
    <fullName>Show_File__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Para seleccionar los archivos que deben mostrarse o no (GetDocumentAPI)</description>
    <label>Show File</label>
    <type>Checkbox</type>
</CustomField>

Salesforce/main/default/main/default/objects/Categoria__c/Categoria__c.object-meta.xml
<CustomObject>
    <description>Categorías</description>
    <label>Categoria</label>
    <nameField>
        <label>Nombre de Categoría</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categorias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/objects/ContentVersion/fields/Show_File__c.field-meta.xml
<CustomField>
    <fullName>Show_File__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Para seleccionar los archivos que deben mostrarse o no (GetDocumentAPI)</description>
    <label>Show File</label>
    <type>Checkbox</type>
</CustomField>

Salesforce/main/default/objects/CRM_Calendario_de_Eventos__c/CRM_Calendario_de_Eventos__c.object-meta.xml
<CustomObject>
    <description>Registro de eventos programados pelo Multiplicador</description>
    <label>CRM Evento</label>
    <nameField>
        <label>Nome de CRM Evento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Eventos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/objects/Opportunity/fields/Regiao__c.field-meta.xml
<CustomField>
    <fullName>Regiao__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Região</label>
    <referenceTo>Regiao__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Product2/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <label>Categoria</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BREEDER</fullName>
            </value>
            <value>
                <fullName>FUNDADORA</fullName>
            </value>
            <value>
                <fullName>Genetica</fullName>
            </value>
            <value>
                <fullName>Pre Basica</fullName>
            </value>
            <value>
                <fullName>BASICA</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>C1</fullName>
            </value>
            <value>
                <fullName>C2</fullName>
            </value>
            <value>
                <fullName>R</fullName>
            </value>
            <value>
                <fullName>S1</fullName>
            </value>
            <value>
                <fullName>S2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Product2/fields/Variedad__c.field-meta.xml
<CustomField>
    <fullName>Variedad__c</fullName>
    <label>Variedad</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Licenciada__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>BMX APOLO RR</fullName>
            </value>
            <value>
                <fullName>BMX IMPACTO RR</fullName>
            </value>
            <value>
                <fullName>BMX MAGNA RR</fullName>
            </value>
            <value>
                <fullName>BMX POTÊNCIA RR</fullName>
            </value>
            <value>
                <fullName>BMX TITAN RR</fullName>
            </value>
            <value>
                <fullName>BMX FORÇA RR</fullName>
            </value>
            <value>
                <fullName>BMX ENERGIA RR</fullName>
            </value>
            <value>
                <fullName>BMX ATIVA RR</fullName>
            </value>
            <value>
                <fullName>BMX TURBO RR</fullName>
            </value>
            <value>
                <fullName>BMX VELOZ RR</fullName>
            </value>
            <value>
                <fullName>BMX ALVO RR</fullName>
            </value>
            <value>
                <fullName>BMX TORNADO RR</fullName>
            </value>
            <value>
                <fullName>BMX CLASSE RR</fullName>
            </value>
            <value>
                <fullName>BMX DESAFIO RR</fullName>
            </value>
            <value>
                <fullName>BMX RAÇA RR</fullName>
            </value>
            <value>
                <fullName>BMX PROGRESSO RR</fullName>
            </value>
            <value>
                <fullName>BRASMAX ELITE IPRO</fullName>
            </value>
            <value>
                <fullName>BRASMAX FLECHA IPRO</fullName>
            </value>
            <value>
                <fullName>BRASMAX BONUS IPRO</fullName>
            </value>
            <value>
                <fullName>BRASMAX BRAVA</fullName>
            </value>
            <value>
                <fullName>BRASMAX CLASSE</fullName>
            </value>
            <value>
                <fullName>BRASMAX PRISMA</fullName>
            </value>
            <value>
                <fullName>BRASMAX OPUS IPRO</fullName>
            </value>
            <value>
                <fullName>BRASMAX LANÇA IPRO</fullName>
            </value>
            <value>
                <fullName>BRASMAX GARRA IPRO</fullName>
            </value>
            <value>
                <fullName>BRASMAX ÍCONE IPRO</fullName>
            </value>
            <value>
                <fullName>BRASMAX POWER IPRO</fullName>
            </value>
            <value>
                <fullName>68I69RSF IPRO</fullName>
            </value>
            <value>
                <fullName>75I76RSF IPRO</fullName>
            </value>
            <value>
                <fullName>81I84RSF IPRO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Regiao__c/Regiao__c.object-meta.xml
<CustomObject>
    <label>Región</label>
    <nameField>
        <label>Nome da Região</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regiones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/Variedad__c/Variedad__c.object-meta.xml
<CustomObject>
    <description>Variedades, disponibles para incluir en los Contratos de Multiplicación</description>
    <label>Variedad</label>
    <nameField>
        <label>Nome Comercial</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Variedades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/classes/GetDocumentAPITest.cls
/**
* @name GetDocumentAPITest
* @author Jhonny Peroza
* updated 23-11-2021
*/
@isTest
public class GetDocumentAPITest {

    @TestSetup
    static void makeData(){

        List<Regiao__c> regionsList = TestDataFactory.createRegions(1);
        List<Account> accountsList = TestDataFactory.createAccounts(regionsList);
        List<Variedad__c> varietyList = TestDataFactory.createVariety(1);
        List<Categoria__c> categoriesList = TestDataFactory.createCategory(1);
        List<Variedad__c> varietiesList = TestDataFactory.createVariety(1);
        List<Product2> productList = TestDataFactory.createProduct(1, categoriesList, varietiesList);
        List<CRM_Calendario_de_Eventos__c> calendarioEventosList = TestDataFactory.createEventos(1, accountsList, 'Treinamento Tecnico');
        TestDataFactory.createOpportunities(accountsList, 1);
        TestDataFactory.createContentVersion(1);
        TestDataFactory.createAttachmentContent(1, calendarioEventosList);

    }

    @isTest
    public static void getDocumentInContentDocumentLink() {

        GetDocumentAPI.response result;

        List<Opportunity> opportunitiesList = [SELECT Id FROM Opportunity LIMIT 1];
        List<ContentVersion> documentsList = [SELECT Id, ContentDocumentId FROM ContentVersion LIMIT 1];

        ContentDocumentLink contentDocumentLinkInsert = new ContentDocumentLink();
        contentDocumentLinkInsert.LinkedEntityId = opportunitiesList[0].Id;
        contentDocumentLinkInsert.ContentDocumentId = documentsList[0].ContentDocumentId;
        contentDocumentLinkInsert.ShareType = 'V';
        contentDocumentLinkInsert.Visibility = 'InternalUsers';
        insert contentDocumentLinkInsert;
                                                                                                     
        RestRequest req = new RestRequest(); 
        req.requestURI = '/services/apexrest/GetDocumentAPI/'; 
        req.addParameter('Id', opportunitiesList[0].Id); 
        req.httpMethod = 'GET';

        RestResponse resp = new RestResponse();
        RestContext.request = req;
        RestContext.response = resp;

        test.startTest();
        GetDocumentAPI.getDocument();
        test.stopTest();

        result = (GetDocumentAPI.response)JSON.deserialize(resp.responseBody.toString(), GetDocumentAPI.response.class);

        System.assertEquals(true, result.status);
        System.assertEquals(result.message, Label.GetDocumentAPI_Success_Message);

    }

    @isTest
    public static void getDocumentInAttachment() {

        GetDocumentAPI.Response result;

        List<Attachment_Content__c> attachmentContentList = [SELECT Id, CRM_Calendario_de_Eventos__c FROM Attachment_Content__c LIMIT 1];
        List<CRM_Calendario_de_eventos__c> crmEventosList = [SELECT Id FROM CRM_Calendario_de_Eventos__c LIMIT 1];

        Blob bodyBlob = Blob.valueOf('Test Data');
        
        Attachment_Content__c contentInsert = new Attachment_Content__c();
        contentInsert.CRM_Calendario_de_Eventos__c = crmEventosList[0].Id;
        contentInsert.Show_File__c = true;
        insert contentInsert;
            
        Attachment attachmentInsert = new Attachment();
        attachmentInsert.ParentId = attachmentContentList[0].CRM_Calendario_de_Eventos__c;
        attachmentInsert.Name = 'CONTENT VERSION.txt';
        attachmentInsert.Body = bodyBlob;
        insert attachmentInsert;

        RestRequest req = new RestRequest(); 
        req.requestURI = '/services/apexrest/GetDocumentAPI/';  
        req.addParameter('Id', crmEventosList[0].Id); 
        req.httpMethod = 'GET';

        RestResponse resp = new RestResponse();
        RestContext.request = req;
        RestContext.response = resp;

        test.startTest();
        GetDocumentAPI.getDocument();
        test.stopTest();

        result = (GetDocumentAPI.response)JSON.deserialize(resp.responseBody.toString(), GetDocumentAPI.response.class);

        System.assertEquals(true, result.status);
        System.assertEquals(result.message, Label.GetDocumentAPI_Success_Message);

    }

    @isTest
    public static void documentNotFound() {

        GetDocumentAPI.response result;

        List<Opportunity> opportunitiesList = [SELECT Id FROM Opportunity LIMIT 1];

        RestRequest req = new RestRequest(); 
        req.requestURI = '/services/apexrest/GetDocumentAPI/';  
        req.addParameter('Id', opportunitiesList[0].Id); 
        req.httpMethod = 'GET';

        RestResponse resp = new RestResponse();
        RestContext.request = req;
        RestContext.response = resp;

        test.startTest();
        GetDocumentAPI.getDocument();
        test.stopTest();

        result = (GetDocumentAPI.response)JSON.deserialize(resp.responseBody.toString(), GetDocumentAPI.response.class);

        System.assertEquals(false, result.status);
        System.assertEquals(result.message, Label.GetDocumentAPI_Default_Error_Message);

    }

    @isTest
    public static void getDocumentInAttachmentContent() {

        GetDocumentAPI.Response result;
        Blob bodyBlob = Blob.valueOf('Test Data');
        
        List<Regiao__c> regionsList = TestDataFactory.createRegions(1);              

        List<Account> accountsList = TestDataFactory.createAccounts(regionsList);              

        List<CRM_Calendario_de_Eventos__c> calendarioEventosList = TestDataFactory.createEventos(1, accountsList, 'Treinamento Tecnico');

        Attachment_Content__c atachmentContent = new Attachment_Content__c();
        atachmentContent.CRM_Calendario_de_Eventos__c = calendarioEventosList[0].Id;
        atachmentContent.Show_File__c = true;
        insert atachmentContent;
            
        Attachment attachmentInsert = new Attachment();
        attachmentInsert.ParentId = atachmentContent.Id;
        attachmentInsert.Name = 'CONTENT VERSION.txt';
        attachmentInsert.Body = bodyBlob;
        insert attachmentInsert;

        RestRequest req = new RestRequest(); 
        req.requestURI = '/services/apexrest/GetDocumentAPI/';  
        req.addParameter('Id', calendarioEventosList[0].Id); 
        req.httpMethod = 'GET';

        RestResponse resp = new RestResponse();
        RestContext.request = req;
        RestContext.response = resp;

        test.startTest();
        GetDocumentAPI.getDocument();
        test.stopTest();

        result = (GetDocumentAPI.response)JSON.deserialize(resp.responseBody.toString(), GetDocumentAPI.response.class);

        System.assertEquals(true, result.status);
        System.assertEquals(result.message, Label.GetDocumentAPI_Success_Message);

    }

}