Salesforce/main/default/objects/Product2/fields/Obtentor__c.field-meta.xml
<CustomField>
    <fullName>Obtentor__c</fullName>
    <description>Lista de Obtentores que debemos mantener(admin)</description>
    <inlineHelpText>Lista de Obtentores que debemos mantener(admin)</inlineHelpText>
    <label>Obtentor</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ADVANTA</fullName>
            </value>
            <value>
                <fullName>Agrária</fullName>
            </value>
            <value>
                <fullName>Agroeste</fullName>
            </value>
            <value>
                <fullName>AGROMEN</fullName>
            </value>
            <value>
                <fullName>Agro Norte</fullName>
            </value>
            <value>
                <fullName>Avanti Seeds</fullName>
            </value>
            <value>
                <fullName>Basf</fullName>
            </value>
            <value>
                <fullName>Bayer</fullName>
            </value>
            <value>
                <fullName>Brasmax</fullName>
            </value>
            <value>
                <fullName>BREVANT</fullName>
            </value>
            <value>
                <fullName>Br Genetica</fullName>
            </value>
            <value>
                <fullName>CARAIBA</fullName>
            </value>
            <value>
                <fullName>CCGL Tecnología</fullName>
            </value>
            <value>
                <fullName>Coodetec</fullName>
            </value>
            <value>
                <fullName>CORDIUS</fullName>
            </value>
            <value>
                <fullName>CPTA</fullName>
            </value>
            <value>
                <fullName>Credenz</fullName>
            </value>
            <value>
                <fullName>CTP</fullName>
            </value>
            <value>
                <fullName>CTPA/Emgopa</fullName>
            </value>
            <value>
                <fullName>DM Licenças</fullName>
            </value>
            <value>
                <fullName>Don Mario</fullName>
            </value>
            <value>
                <fullName>Dow</fullName>
            </value>
            <value>
                <fullName>Embrapa</fullName>
            </value>
            <value>
                <fullName>FMT</fullName>
            </value>
            <value>
                <fullName>FPS</fullName>
            </value>
            <value>
                <fullName>FT</fullName>
            </value>
            <value>
                <fullName>Fundacep</fullName>
            </value>
            <value>
                <fullName>GDML</fullName>
            </value>
            <value>
                <fullName>Genetica Soy</fullName>
            </value>
            <value>
                <fullName>Geneze</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Product2/fields/Portal__c.field-meta.xml
<CustomField>
    <fullName>Portal__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indica si el producto está habilitado/deshabilitado para ser devuelto en las APIs creadas para el nuevo Portal. Creado para US #13082</description>
    <label>Portal</label>
    <type>Checkbox</type>
</CustomField>

Salesforce/main/default/main/default/classes/ProductsCRMAPI.cls
@RestResource(urlMapping='/ProductsCRMAPI/*')
global with sharing class ProductsCRMAPI {

    /**
     *  SUBCLASS:       Response
     *  DESCRIPTION:    wrapper class for CRM Products API response. Created for US #14317 
     *  AUTHOR:         irina.benitez@cloudgaia.com (18-nov-21)
     **/ 
    public class Response {
        public Boolean status;
        public String message;
        public Map<String, List<Producto>> productsCRM;
    }

    /**
     *  SUBCLASS:       Producto
     *  DESCRIPTION:    wrapper class for CRM Products. Created for US #14317 //! Ver con team de unificar JSON wrapper en una única clase 
     *  AUTHOR:         irina.benitez@cloudgaia.com (18-nov-21)
     **/ 
    public class Producto {
        public String id_producto;
        public String desc_producto;
    }

     /**
     *  METHOD:         getProductsCRM 
     *  PARAMETERS:     event: type of event 
     *  RETURN:         message: displays 'success' or error message  
     *                  status: boolean shows if operation was succesfull
     *                  productsCRM: list of records to return
     *  DESCRIPTION:    Return list of products for a CRM. Created for US #14317
     *  AUTHOR:         irina.benitez@cloudgaia.com (18-nov-21)
     **/ 
    @HttpGet
    global static void getProductsCRM() {

        String event = RestContext.request.params.get('event');

        RestResponse response = RestContext.response;
        response.statusCode = 404;

        ProductsCRMAPI.Response result = new ProductsCRMAPI.Response();
        result.status = false;
        result.message = Label.ProductsCRMAPI_Default_Error_Message;
        
        try {

            List<Product2> productList = [SELECT Id, Name, Obtentor__c FROM Product2 WHERE Obtentor__c != null AND Portal__c = TRUE ORDER BY Obtentor__c];

            if( productList != null && !productList.isEmpty() ){
                result.productsCRM = productJSONConverter(productList);
            }

        } catch (Exception exc) {
            response.statusCode = 400;
            result.message = exc.getMessage();
        }
                
        if(result.productsCRM != null && !result.productsCRM.isEmpty()) {
            result.status = true;
            result.message = Label.ProductsCRMAPI_Success_Message;
            response.statusCode = 200;
        }

        response.responseBody = Blob.valueOf(JSON.serialize(result));
        response.headers.put('Content-Type', 'application/json');
        response.headers.put('Content-Length', RestContext.response.responseBody.size()+'');
    }


    /**
     *  METHOD:         productJSONConverter 
     *  PARAMETERS:     products: List of Product2 items in sObject format
     *  RETURN:         List<aSiteEventosController.item>: list of records in JSON format to return
     *  DESCRIPTION:    Helper method converts Product2 sObject in aSiteEventosController.item JSON wrapper. Created for US #14317 
     *  AUTHOR:         irina.benitez@cloudgaia.com (18-nov-21)
     **/ 
    public static Map<String, List<Producto>> productJSONConverter(List<Product2> products) {
        
        Map<String, List<Producto>> result = new Map<String, List<Producto>>();

        for( Product2 product : products) {
            Producto item = new Producto();
            item.desc_producto = product.Name;
            item.id_producto = product.Id;

            if(!result.containsKey(product.Obtentor__c)) {
                List<Producto> itemList = new List<Producto>();
                itemList.add(item);
                result.put(product.Obtentor__c, itemList);
            } else {
                result.get(product.Obtentor__c).add(item);
            }
        }
        
        return result;
    }


}