Salesforce/main/default/main/default/objects/Account/fields/CEP__c.field-meta.xml
<CustomField>
    <fullName>CEP__c</fullName>
    <description>##.###-###</description>
    <label>CEP</label>
    <type>TextArea</type>
</CustomField>

Salesforce/main/default/objects/Account/fields/CNPJ_CPF__c.field-meta.xml
<CustomField>
    <fullName>CNPJ_CPF__c</fullName>
    <externalId>true</externalId>
    <label>CNPJ/CPF</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Salesforce/main/default/objects/Account/fields/IE__c.field-meta.xml
<CustomField>
    <fullName>IE__c</fullName>
    <label>IE</label>
    <type>TextArea</type>
</CustomField>

Salesforce/main/default/main/default/objects/Account/recordTypes/Cuenta.recordType-meta.xml
<RecordType>
    <fullName>Cuenta</fullName>
    <active>true</active>
    <label>Cuenta</label>
</RecordType>

Salesforce/main/default/main/default/objects/Opportunity/fields/Numero_del__c.field-meta.xml
<CustomField>
    <fullName>Numero_del__c</fullName>
    <label>Numero</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/Opportunity/fields/Numero_Legal__c.field-meta.xml
<CustomField>
    <fullName>Numero_Legal__c</fullName>
    <label>Numero Legal</label>
    <precision>15</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

Salesforce/main/default/main/default/objects/Opportunity/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <description>Safra o Campania agricola</description>
    <label>Safra</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>06/07</fullName>
            </value>
            <value>
                <fullName>07/08</fullName>
            </value>
            <value>
                <fullName>08/09</fullName>
            </value>
            <value>
                <fullName>09/10</fullName>
            </value>
            <value>
                <fullName>09/09</fullName>
            </value>
            <value>
                <fullName>10/10</fullName>
            </value>
            <value>
                <fullName>10/11</fullName>
            </value>
            <value>
                <fullName>11/11</fullName>
            </value>
            <value>
                <fullName>11/12</fullName>
            </value>
            <value>
                <fullName>12/12</fullName>
            </value>
            <value>
                <fullName>12/13</fullName>
            </value>
            <value>
                <fullName>13/14</fullName>
            </value>
            <value>
                <fullName>14/15</fullName>
            </value>
            <value>
                <fullName>15/16</fullName>
            </value>
            <value>
                <fullName>16/17</fullName>
            </value>
            <value>
                <fullName>17/18</fullName>
            </value>
            <value>
                <fullName>18/19</fullName>
            </value>
            <value>
                <fullName>19/20</fullName>
            </value>
            <value>
                <fullName>20/21</fullName>
            </value>
            <value>
                <fullName>21/22</fullName>
                <default>true</default>
                <label>21/22</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Opportunity/fields/Tipo_de_cambio__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_cambio__c</fullName>
    <description>Tipo de cambio al que sale impresa la factura</description>
    <inlineHelpText>Tipo de cambio al que sale impresa la factura</inlineHelpText>
    <label>Tipo de câmbio</label>
    <precision>16</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

Salesforce/main/default/objects/Opportunity/recordTypes/Comercial.recordType-meta.xml
<RecordType>
    <fullName>Comercial</fullName>
    <active>true</active>
    <businessProcess>Control_Multiplicador</businessProcess>
    <description>Detalle de lo que el multiplicador va a vender: relatorio de venda</description>
    <label>Comercial</label>
</RecordType>

Salesforce/main/default/objects/OpportunityLineItem/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <formula>TEXT(Opportunity.Safra__c)</formula>
    <label>Safra</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/OpportunityLineItem/fields/Tipo_de_cambio__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_cambio__c</fullName>
    <label>Tipo de câmbio</label>
    <precision>16</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

Salesforce/main/default/main/default/classes/Imprimir_Facturas_HTML.cls
Public class Imprimir_Facturas_HTML {
   
   Private String Fecha_Factura;
   Private Opportunity opp;
   Private Account cuenta;
   Private List<OpportunityLineItem> items;
   Private List<String> lineasRelleno=new List<String>();
   
   Public void setFecha_Factura(String arg) {
      Fecha_Factura=arg;
   }
   
   Public String getFecha_Factura() {
      return Fecha_Factura;
   }
   
   Public void setcuenta(Account arg) {
      cuenta=arg;
   }
   
   Public Account getcuenta() {
      return cuenta;
   }
   
   Public void setopp(Opportunity arg) {
      opp=arg;
   }
   
   Public Opportunity getopp() {
      return opp;
   }
   
   Public void setitems(List<OpportunityLineItem> arg) {
      items=arg;
   }
   
   Public List<OpportunityLineItem> getitems() {
      return items;
   }
   
   Public List<String> getlineasRelleno() {
      return lineasRelleno;
   }
   
   Public void setlineasRelleno(List<String> arg) {
      lineasRelleno=arg;
   }

       
   Public Imprimir_Facturas_HTML(){
                      
      Id oppId = System.currentPageReference().getParameters().get('id');
      
      opp = [Select Id, Type, Name, numero_legal__c, StageName, AccountId, CloseDate, Tipo_de_cambio__c, Numero_del__c, Amount, Safra__c From Opportunity Where Id = : oppId];
      cuenta = [Select Id, Name, BillingCity, BillingCountry, BillingPostalCode, BillingState, BillingStreet, CEP__c, CNPJ_CPF__c, IE__c From Account Where Id = : opp.accountId];  
      items = [Select Id, PricebookEntry.Product2.Name, PricebookEntry.Product2.Description ,UnitPrice, TotalPrice, Quantity From OpportunityLineItem Where OpportunityId = : oppId]; 
   
      Fecha_Factura=String.valueof(opp.CloseDate);
      Fecha_Factura=Fecha_Factura.substring(8,10) + '/' + Fecha_Factura.substring(5,7) + '/' + Fecha_Factura.substring(0,4); 
      
      for(Integer i=items.size();i<=31;i++)
         lineasRelleno.add('');
  
   }
   
   public static testMethod void testM() {

      Account acc = New Account (Name='a');
      insert acc;
      RecordType rt = [SELECT Id FROM RecordType WHERE Name = 'Comercial' limit 1];
      Opportunity opp = New Opportunity(Name='a', StageName='Abierta', AccountId= acc.Id, CloseDate=system.today(), RecordTypeId=rt.Id);                  
      insert opp;
      PriceBookEntry pbe = [Select Id From PriceBookEntry where isActive = true limit 1];
      OpportunityLineItem item = New OpportunityLineItem (OpportunityId = opp.Id, UnitPrice = 1, Quantity = 1, PricebookEntryId = pbe.Id);
      insert item; 
      System.currentPageReference().getParameters().put('id',opp.Id);
      Imprimir_Facturas_HTML a = New Imprimir_Facturas_HTML();
      a.setFecha_Factura('a');
      String b = a.getFecha_Factura();
      a.setcuenta(acc);
      acc=a.getcuenta();
      a.setOpp(opp);
      Opportunity o = a.getOpp();
      OpportunityLineItem i = New OpportunityLineItem(OpportunityId=opp.Id, Quantity=1, UnitPrice=1);
      List <OpportunityLineItem> items = New List<OpportunityLineItem>();
      items.add(i);
      a.setitems(items);
      List <OpportunityLineItem> it = a.getitems();
      List <String> g = a.getLineasRelleno();
      List <String> h = New List <String>();
      a.setLineasRelleno(h);
         
   }


}