Salesforce/main/default/main/default/objects/Account/fields/Codigo_SAP__c.field-meta.xml
<CustomField>
    <fullName>Codigo_SAP__c</fullName>
    <formula>CodigoSAP__c</formula>
    <label>Codigo_SAP</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/Account/fields/CodigoSAP__c.field-meta.xml
<CustomField>
    <fullName>CodigoSAP__c</fullName>
    <label>CodigoSAP</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/Account/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Estado</label>
    <referenceTo>Estado__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/Account/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Marca</valueSetName>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Account/recordTypes/Cuenta.recordType-meta.xml
<RecordType>
    <fullName>Cuenta</fullName>
    <active>true</active>
    <label>Cuenta</label>
</RecordType>

Salesforce/main/default/main/default/objects/Centro_Logistico__c/Centro_Logistico__c.object-meta.xml
<CustomObject>
    <description>Son los centros logísticos de Brasmax</description>
    <label>Centro Logístico</label>
    <nameField>
        <label>Nombre de Centro Logístico</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Centros Logísticos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/objects/Centro_Logistico__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Es el Estado del Centro de Origen</description>
    <label>Estado</label>
    <referenceTo>Estado__c</referenceTo>
    <relationshipLabel>Centros Logísticos</relationshipLabel>
    <relationshipName>Centros_Log_sticos</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Centro_Logistico__c/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BRMX</fullName>
            </value>
            <value>
                <fullName>DSEM</fullName>
            </value>
            <value>
                <fullName>NEOG</fullName>
            </value>
            <value>
                <fullName>DAGMA</fullName>
            </value>
            <value>
                <fullName>LICENÇAS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Opportunity/fields/Anexo_Relacionado__c.field-meta.xml
<CustomField>
    <fullName>Anexo_Relacionado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Anexo Relacionado</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Oportunidades (Anexo Relacionado)</relationshipLabel>
    <relationshipName>Oportunidades2</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/Opportunity/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <formula>IF(NOT(ISNULL(Inicio_Cargamento__c)),
			IF(NOT(ISNULL(Inicio_Transporte__c)),
						IF(NOT(ISNULL(Fin_Transporte__c)),
									IF(AND(Confirmado__c,NOT(Solicitacao_de_reembolso__c)),
											&apos;Confirmado&apos;,
											IF(AND(Solicitacao_de_reembolso__c,NOT(Confirmado__c)),
													&apos;Em Troca&apos;,
													&apos;Entregue&apos;)
											),
									&apos;Pedido em trânsito&apos;),
						&apos;Em carregamento&apos;),
			&apos;&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status de transporte</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/Opportunity/fields/Local_de_Entrega__c.field-meta.xml
<CustomField>
    <fullName>Local_de_Entrega__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Local de Entrega</label>
    <referenceTo>Local__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/Opportunity/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <description>Identifica la marca para las Oportunidades del Circuito de Anexos. Se selecciona la lista de precios en función de este campo</description>
    <inlineHelpText>Identificar a marca de Oportunidades Circuito Anexos. Você seleciona a lista de preços com base neste campo</inlineHelpText>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BRMX</fullName>
            </value>
            <value>
                <fullName>DSEM</fullName>
            </value>
            <value>
                <fullName>NEOG</fullName>
            </value>
            <value>
                <fullName>DAGMA</fullName>
            </value>
            <value>
                <fullName>LICENÇAS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Opportunity/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <description>Safra o Campania agricola</description>
    <label>Safra</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>06/07</fullName>
            </value>
            <value>
                <fullName>07/08</fullName>
            </value>
            <value>
                <fullName>08/09</fullName>
            </value>
            <value>
                <fullName>09/10</fullName>
            </value>
            <value>
                <fullName>09/09</fullName>
            </value>
            <value>
                <fullName>10/10</fullName>
            </value>
            <value>
                <fullName>10/11</fullName>
            </value>
            <value>
                <fullName>11/11</fullName>
            </value>
            <value>
                <fullName>11/12</fullName>
            </value>
            <value>
                <fullName>12/12</fullName>
            </value>
            <value>
                <fullName>12/13</fullName>
            </value>
            <value>
                <fullName>13/14</fullName>
            </value>
            <value>
                <fullName>14/15</fullName>
            </value>
            <value>
                <fullName>15/16</fullName>
            </value>
            <value>
                <fullName>16/17</fullName>
            </value>
            <value>
                <fullName>17/18</fullName>
            </value>
            <value>
                <fullName>18/19</fullName>
            </value>
            <value>
                <fullName>19/20</fullName>
            </value>
            <value>
                <fullName>20/21</fullName>
            </value>
            <value>
                <fullName>21/22</fullName>
                <default>true</default>
                <label>21/22</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Opportunity/recordTypes/Pendiente.recordType-meta.xml
<RecordType>
    <fullName>Pendiente</fullName>
    <active>true</active>
    <businessProcess>Nota de Venta - Pendiente</businessProcess>
    <label>Pendiente</label>
</RecordType>

Salesforce/main/default/main/default/objects/Opportunity/recordTypes/Previsao.recordType-meta.xml
<RecordType>
    <fullName>Previsao</fullName>
    <active>true</active>
    <businessProcess>Prevision Venta Basica</businessProcess>
    <description>Previsiones de Ventas de Bolsas de Básica</description>
    <label>Previsao</label>
</RecordType>

Salesforce/main/default/objects/OpportunityLineItem/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Ha. Autorizados</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/objects/OpportunityLineItem/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Categoria a ser licenciada</description>
    <inlineHelpText>Categoria a ser licenciada</inlineHelpText>
    <label>Categoria</label>
    <referenceTo>Categoria__c</referenceTo>
    <relationshipLabel>Producto de oportunidad</relationshipLabel>
    <relationshipName>Producto_de_oportunidad</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/OpportunityLineItem/fields/Categoria_a_Rebaixar__c.field-meta.xml
<CustomField>
    <fullName>Categoria_a_Rebaixar__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Categoria Plantada</label>
    <referenceTo>Categoria__c</referenceTo>
    <relationshipLabel>Producto de oportunidad (Categoria a Rebaixar)</relationshipLabel>
    <relationshipName>Producto_de_oportunidad1</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/OpportunityLineItem/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Estado</label>
    <referenceTo>Estado__c</referenceTo>
    <relationshipLabel>Producto de oportunidad (Estado)</relationshipLabel>
    <relationshipName>Producto_de_oportunidad2</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/OpportunityLineItem/fields/Id_Item_de_Oportunidad_Relacionado__c.field-meta.xml
<CustomField>
    <fullName>Id_Item_de_Oportunidad_Relacionado__c</fullName>
    <description>Id del OpportunityLineItem del relatorio de venta relacionado</description>
    <label>Id Item de Oportunidad Relacionado</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/OpportunityLineItem/fields/Local_de_Entrega__c.field-meta.xml
<CustomField>
    <fullName>Local_de_Entrega__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Local de Entrega</label>
    <referenceTo>Local__c</referenceTo>
    <relationshipLabel>Producto de oportunidad</relationshipLabel>
    <relationshipName>Producto_de_oportunidad</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/OpportunityLineItem/fields/Previsao__c.field-meta.xml
<CustomField>
    <fullName>Previsao__c</fullName>
    <label>Previsão</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/objects/OpportunityLineItem/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <formula>TEXT(Opportunity.Safra__c)</formula>
    <label>Safra</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/OpportunityLineItem/fields/Sem_Rebajada__c.field-meta.xml
<CustomField>
    <fullName>Sem_Rebajada__c</fullName>
    <label>Sem. Rebaixada (Sacas)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/main/default/objects/OpportunityLineItem/fields/Semente_bruta__c.field-meta.xml
<CustomField>
    <fullName>Semente_bruta__c</fullName>
    <label>Sem. Bruta (Sacas)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/main/default/objects/Product2/fields/Categ__c.field-meta.xml
<CustomField>
    <fullName>Categ__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Categ</label>
    <referenceTo>Categoria__c</referenceTo>
    <relationshipLabel>Productos</relationshipLabel>
    <relationshipName>Productos</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Product2/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <label>Categoria</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BREEDER</fullName>
            </value>
            <value>
                <fullName>FUNDADORA</fullName>
            </value>
            <value>
                <fullName>Genetica</fullName>
            </value>
            <value>
                <fullName>Pre Basica</fullName>
            </value>
            <value>
                <fullName>BASICA</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>C1</fullName>
            </value>
            <value>
                <fullName>C2</fullName>
            </value>
            <value>
                <fullName>R</fullName>
            </value>
            <value>
                <fullName>S1</fullName>
            </value>
            <value>
                <fullName>S2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Product2/fields/Semilla_Tratada__c.field-meta.xml
<CustomField>
    <fullName>Semilla_Tratada__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indica si la semilla tiene tratamiento o no.</description>
    <label>Semente Tratada</label>
    <type>Checkbox</type>
</CustomField>

Salesforce/main/default/objects/Product2/fields/Variedade__c.field-meta.xml
<CustomField>
    <fullName>Variedade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Variedade</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Variedad__c.Licenciada__c</field>
            <operation>equals</operation>
            <valueField>$Source.Licenciada__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Variedad__c</referenceTo>
    <relationshipLabel>Productos</relationshipLabel>
    <relationshipName>Productos</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/globalValueSets/Marca.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BRMX</fullName>
    </customValue>
    <customValue>
        <fullName>DSEM</fullName>
    </customValue>
    <customValue>
        <fullName>NEOG</fullName>
    </customValue>
    <customValue>
        <fullName>DAGMA</fullName>
    </customValue>
    <customValue>
        <fullName>LICENÇAS</fullName>
    </customValue>
    <masterLabel>Marca</masterLabel>
</GlobalValueSet>

Salesforce/main/default/main/default/classes/opportunityProductEntryTests.cls
@istest (seeAllData=true)
private class opportunityProductEntryTests {

    static testMethod void theTests(){              
        
        Test.startTest();
        
        // You really should create test data, but I'm going to query instead
        // It's my best shot of avoiding a test failure in most orgs
        // Once you've installed this package though, you might want to write your own tests
        // or at least customize these ones to make them more applicable to your org
        Pricebook2 pb = [SELECT Id FROM Pricebook2 where Name = 'Lista Canal Multiplicadores' limit 1];   
        OpportunityLineItem oli = [select Id, PricebookEntryId, PricebookEntry.Pricebook2Id, PricebookEntry.Name, PriceBookEntry.Product2Id, OpportunityId, Opportunity.AccountId from OpportunityLineItem WHERE PricebookEntry.Pricebook2Id = :pb.Id limit 1];
               
                
        ////////////////////////////////////////
        //  test opportunityProductEntry
        ////////////////////////////////////////
        
        // load the page       
        PageReference pageRef = Page.opportunityProductEntry;
        pageRef.getParameters().put('Id',oli.OpportunityId);
        Test.setCurrentPageReference(pageRef);
        
        // load the extension
        opportunityProductEntryExtension oPEE = new opportunityProductEntryExtension(new ApexPages.StandardController(oli.Opportunity));

        oPEE.searchString = 'michaelforce is a hip cat';
        oPEE.setforcePricebookSelection(false);
        oPEE.priceBookCheck();
        oPEE.updateAvailableList();
        oPEE.getOptionCategoria();
        oPEE.setforcePricebookSelection(true);
        oPEE.priceBookCheck();
        
        //test remove from shopping cart
        oPEE.toUnselect = oli.PricebookEntryId;
        oPEE.removeFromShoppingCart();
        //system.assert(oPEE.shoppingCart.size()==startCount-1);
        
        //test save and reload extension
        oPEE.onSave();
        oPEE = new opportunityProductEntryExtension(new ApexPages.StandardController(oli.Opportunity));
        //system.assert(oPEE.shoppingCart.size()==startCount-1);
        
        // test search again, this time we will find something
        oPEE.searchString = oli.PricebookEntry.Name;
        oPEE.updateAvailableList();
        //system.assert(oPEE.AvailableProducts.size()>0);       

        // test save method - WITHOUT quanitities and amounts entered and confirm that error message is displayed
        oPEE.onSave();
        
        // add required info and try save again
        for(OpportunityLineItem o : oPEE.ShoppingCart){
            o.quantity = 5;
            o.unitprice = 300;
        }
        oPEE.onSave();
        
        // query line items to confirm that the save worked
        opportunityLineItem[] oli2 = [select Id from opportunityLineItem where OpportunityId = :oli.OpportunityId];

        //oPEE.getDespachoItems();
        
        Test.stopTest();
        
    }
    @isTest(SeeAllData=true)
    public static void theTests2(){
        
                
        Pricebook2 pb = [SELECT Id FROM Pricebook2 where Name = 'Lista Canal Multiplicadores' limit 1];
        OpportunityLineItem oli = [select Id, PricebookEntryId, PricebookEntry.Pricebook2Id, PricebookEntry.Name, PriceBookEntry.Product2Id, OpportunityId, Opportunity.AccountId from OpportunityLineItem WHERE PricebookEntry.Pricebook2Id = :pb.Id limit 1];
        
        opportunityProductEntryExtension oPEE = new opportunityProductEntryExtension(new ApexPages.StandardController(oli.Opportunity));
        
        Map<String,Id> cat = New Map<String,Id>();
        for(Categoria__c cate : [SELECT Id, Name FROM Categoria__c])
            cat.put(cate.Name, cate.Id);
            
        Map<String,Id> rtype = New Map<String,Id>();
        for(RecordType reTy : [Select Id, Name From RecordType Where sObjectType = 'Opportunity'])
          rtype.put(reTy.Name, reTy.Id);
        
        Local__c l = new Local__c(Name='Locl2'); insert l;
        
        Account cuenta = [Select Id From Account Where Name = 'ACME' AND CodigoSAP__c = '6000000000' limit 1];
        Pricebook2 pb1 = [Select Id, Name From Pricebook2 where Name = 'Lista de Básica BMX SUL' and isActive = true limit 1];
        Opportunity prevision = New Opportunity(RecordTypeId=rtype.get('Previsao'), Name='Previsao', AccountId = cuenta.Id,Local_de_Entrega__c=l.Id, Pricebook2Id=pb1.Id, CloseDate=System.today(), Marca__c='BRMX',StageName='Aberta', Safra__c='12/13');
        insert prevision;
        PricebookEntry pbe = [Select Id, Product2Id From PricebookEntry where Pricebook2Id = :pb1.Id and isActive = true and Product2.Categ__c = :cat.get('BASICA') limit 1];

        OpportunityLineItem oi2 = new OpportunityLineItem(OpportunityId=prevision.Id,Local_de_Entrega__c=l.Id,Quantity=0.01,Previsao__c = 50,TotalPrice=10,PricebookEntryId=pbe.Id);
        insert oi2;
        
         oPEE = new opportunityProductEntryExtension(new ApexPages.StandardController(prevision));
        //System.assert(oPEE.priceBookCheck()!=null);
        //oPEE.getFields();
        oPEE.toSelect = oPEE.AvailableProducts[0].Id;
        oPEE.addToShoppingCart();
        oPEE.onSave();

        Opportunity prevision2 = New Opportunity(RecordTypeId=rtype.get('Previsao'), Name='Previsao2', AccountId = cuenta.Id, CloseDate=System.today(), Marca__c='DSEM',StageName='Aberta', Safra__c='12/13');
        insert prevision2;

       
        
         oPEE = new opportunityProductEntryExtension(new ApexPages.StandardController(prevision2));
        //oPEE.getFields();
        prevision2.RecordTypeId = rtype.get('Stock Multiplicadores');
        update prevision2;
        
        /*
        oPEE = new opportunityProductEntryExtension(new ApexPages.StandardController(prevision2));
        oPEE.getFields();
        prevision2.RecordTypeId = rtype.get('Anexo II');
        Test.startTest();
        update prevision2;
        
        prevision2.RecordTypeId = rtype.get('Anexo III');
        update prevision2;
        OpportunityLineItem oi32 = new OpportunityLineItem(OpportunityId=prevision2.Id,Quantity=0.01,Previsao__c = 50,TotalPrice=10,PricebookEntryId=pbe.Id);
        insert oi32;
        
        oPEE = new opportunityProductEntryExtension(new ApexPages.StandardController(prevision2));        
        oPEE.updateAvailableList();
        
        Test.stopTest();         
        */
     
    }
    static testMethod void theTests3(){
        
        Test.startTest();
        
        Map<String,Id> rtype = New Map<String,Id>();
        for(RecordType reTy : [Select Id, Name From RecordType Where sObjectType = 'Opportunity'])
          rtype.put(reTy.Name, reTy.Id);        
        
        Pricebook2 pb = [SELECT Id FROM Pricebook2 where Name = 'Lista Canal Multiplicadores' limit 1];
        OpportunityLineItem oli = [select Id, PricebookEntryId, PricebookEntry.Pricebook2Id, PricebookEntry.Name, PriceBookEntry.Product2Id, OpportunityId, Opportunity.AccountId from OpportunityLineItem WHERE PricebookEntry.Pricebook2Id = :pb.Id limit 1];
        
        opportunityProductEntryExtension oPEE = new opportunityProductEntryExtension(new ApexPages.StandardController(oli.Opportunity));
        
        
        Opportunity newOpp = new Opportunity(Name='New Opp',RecordTypeId=rtype.get('Anexo I'),stageName='Pipeline',Amount=10,closeDate=System.Today()+30,AccountId=oli.Opportunity.AccountId);
        insert(newOpp);
        oPEE = new opportunityProductEntryExtension(new ApexPages.StandardController(newOpp));

        System.assert(oPEE.onCancel()!=null);
        Map<String,Id> cat = New Map<String,Id>();
        for(Categoria__c cate : [SELECT Id, Name FROM Categoria__c])
            cat.put(cate.Name, cate.Id);            

        
        Account cuenta = [Select Id From Account Where Name = 'ACME' AND CodigoSAP__c = '6000000000' limit 1];
        Pricebook2 pb1 = [Select Id, Name From Pricebook2 where Name = 'Lista de Básica BMX SUL' and isActive = true limit 1];
        //Opportunity prevision = New Opportunity(RecordTypeId=rtype.get('Previsao'), Name='Previsao', AccountId = cuenta.Id,Pricebook2Id=pb1.Id, CloseDate=System.today(), Marca__c='BRMX',StageName='Aberta', Safra__c='12/13');
        //insert prevision;
        PricebookEntry pbe = [Select Id, Product2Id From PricebookEntry where Pricebook2Id = :pb1.Id and isActive = true and Product2.Categ__c = :cat.get('BASICA') limit 1];


        Opportunity prevision2 = New Opportunity(RecordTypeId=rtype.get('Anexo I Rebaixamento Ha'), Name='Previsao2', AccountId = cuenta.Id, CloseDate=System.today(), Marca__c='DSEM',StageName='Aberta', Safra__c='12/13', Anexo_Relacionado__c = newOpp.Id);
        insert prevision2;
        oPEE = new opportunityProductEntryExtension(new ApexPages.StandardController(prevision2));
        oPEE.getFields();
        oPEE.getTipoNecesidad();
                    
        Test.stopTest();
     
    }
    static testMethod void theTests4(){
        
        Test.startTest();
        
        Map<String,Id> rtype = New Map<String,Id>();
        for(RecordType reTy : [Select Id, Name From RecordType Where sObjectType = 'Opportunity'])
          rtype.put(reTy.Name, reTy.Id);        
        
        Pricebook2 pb1 = [SELECT Id FROM Pricebook2 where Name = 'Lista Canal Multiplicadores' limit 1];
        Account cuenta = [Select Id From Account Where Name = 'ACME' AND CodigoSAP__c = '6000000000' limit 1];
        
        Opportunity newOpp = new Opportunity(Name='New Opp',RecordTypeId=rtype.get('Anexo I'),StageName='Aprobada',Amount=10,closeDate=System.Today()+30,AccountId=cuenta.Id);
        insert(newOpp);
        opportunityProductEntryExtension oPEE = new opportunityProductEntryExtension(new ApexPages.StandardController(newOpp));

        System.assert(oPEE.onCancel()!=null);
        Map<String,Id> cat = New Map<String,Id>();
        for(Categoria__c cate : [SELECT Id, Name FROM Categoria__c])
            cat.put(cate.Name, cate.Id);
           

        
        
        //Pricebook2 pb1 = [Select Id, Name From Pricebook2 where Name = 'Lista de Básica BMX 2' and isActive = true limit 1];
        PricebookEntry pbe = [Select Id, Product2Id From PricebookEntry where Pricebook2Id = :pb1.Id and isActive = true and Product2.Categ__c = :cat.get('BASICA') limit 1];
        OpportunityLineItem oliNewOpp = new OpportunityLineItem(OpportunityId=newOpp.Id,Quantity=0.01,TotalPrice=10,PricebookEntryId=pbe.Id, Categoria__c = cat.get('C1'), Area__c=50.00);
        insert oliNewOpp;
        Opportunity prevision2 = New Opportunity(RecordTypeId=rtype.get('Anexo I Rebaixamento Ha'), Name='Previsao2', AccountId = cuenta.Id, CloseDate=System.today(), Marca__c='DSEM',StageName='Aberta', Safra__c='12/13', Anexo_Relacionado__c = newOpp.Id);
        insert prevision2;
        OpportunityLineItem anexoRoli2 = new OpportunityLineItem(OpportunityId=prevision2.Id,Quantity=0.01,Previsao__c = 50,TotalPrice=10,PricebookEntryId=pbe.Id, Categoria__c = cat.get('C1'), Categoria_a_Rebaixar__c = cat.get('C2'), Area__c=10.00);
        insert anexoRoli2;

        OpportunityLineItem oliprueba =  [SELECT Id, OpportunityId,PricebookEntry.Product2Id, PricebookEntry.Product2.Variedade__r.Name, Area__c, Categoria__c, Categoria_a_Rebaixar__c,Sem_Rebajada__c FROM OpportunityLineItem WHERE Id=:anexoRoli2.Id];
        
        oPEE.validarRebajaAnexoI(New List<OpportunityLineItem> {oliprueba});
        
        oliprueba.Area__c = 100;
        update oliprueba;
        
        OpportunityLineItem oliprueba2 =  [SELECT Id, OpportunityId,PricebookEntry.Product2Id, PricebookEntry.Product2.Variedade__r.Name, Area__c, Categoria__c, Categoria_a_Rebaixar__c,Sem_Rebajada__c FROM OpportunityLineItem WHERE Id=:anexoRoli2.Id];
        
        oPEE.validarRebajaAnexoI(New List<OpportunityLineItem> {oliprueba2});

        Test.stopTest();
     
    }
    
    static testMethod void theTests5(){    
        
        Map<String,Id> rtype = New Map<String,Id>();
        for(RecordType reTy : [Select Id, Name From RecordType Where sObjectType = 'Opportunity'])
          rtype.put(reTy.Name, reTy.Id);        
        
        Pricebook2 pb1 = [SELECT Id FROM Pricebook2 where Name = 'Lista Canal Multiplicadores' limit 1];
        Account cuenta = [Select Id From Account Where Name = 'ACME' AND CodigoSAP__c = '6000000000' limit 1];
        Opportunity newOpp1 = new Opportunity(Name='New Opp',RecordTypeId=rtype.get('Anexo I'),StageName='Aprobada',Amount=10,closeDate=System.Today()+30,AccountId=cuenta.Id);
        insert(newOpp1);
        
        Opportunity newOpp = new Opportunity(Name='New Opp',RecordTypeId=rtype.get('Anexo II'),StageName='Aprobada',Amount=10,closeDate=System.Today()+30,AccountId=cuenta.Id);
        insert(newOpp);
        //opportunityProductEntryExtension oPEE = new opportunityProductEntryExtension(new ApexPages.StandardController(newOpp));

        //System.assert(oPEE.onCancel()!=null);
        Map<String,Id> cat = New Map<String,Id>();
        for(Categoria__c cate : [SELECT Id, Name FROM Categoria__c])
            cat.put(cate.Name, cate.Id);
                  
        
        //Pricebook2 pb1 = [Select Id, Name From Pricebook2 where Name = 'Lista de Básica BMX 2' and isActive = true limit 1];
        PricebookEntry pbe = [Select Id, Product2Id From PricebookEntry where Pricebook2Id = :pb1.Id and isActive = true and Product2.Categ__c = :cat.get('BASICA') limit 1];
        OpportunityLineItem oliNewOpp1 = new OpportunityLineItem(OpportunityId=newOpp1.Id,Quantity=0.01,TotalPrice=10,PricebookEntryId=pbe.Id, Categoria__c = cat.get('C1'), Area__c=50.00);
        insert oliNewOpp1;
        
        OpportunityLineItem oliNewOpp = new OpportunityLineItem(OpportunityId=newOpp.Id,Quantity=0.01,TotalPrice=10,PricebookEntryId=pbe.Id, Categoria__c = cat.get('C1'), Semente_Bruta__c=50.00);
        insert oliNewOpp;
        Opportunity prevision2 = New Opportunity(RecordTypeId=rtype.get('Anexo II Rebaixamento Sacas'), Name='Previsao2', AccountId = cuenta.Id, CloseDate=System.today(), Marca__c='DSEM',StageName='Aberta', Safra__c='12/13', Anexo_Relacionado__c = newOpp.Id);
        insert prevision2;
        OpportunityLineItem anexoRoli2 = new OpportunityLineItem(OpportunityId=prevision2.Id,Quantity=0.01,Previsao__c = 50,TotalPrice=10,PricebookEntryId=pbe.Id, Categoria__c = cat.get('C1'), Categoria_a_Rebaixar__c = cat.get('C2'), Sem_Rebajada__c=10.00);
        insert anexoRoli2;

        OpportunityLineItem oliprueba =  [SELECT Id, OpportunityId,PricebookEntry.Product2Id, PricebookEntry.Product2.Variedade__r.Name,  Area__c, Sem_Rebajada__c, Semente_Bruta__c, Categoria__c, Categoria_a_Rebaixar__c FROM OpportunityLineItem WHERE Id=:anexoRoli2.Id];
        
        //opportunityProductEntryExtension oPEE = new opportunityProductEntryExtension(new ApexPages.StandardController(prevision2));
        
        /*
        oPEE.validarRebajaAnexoI(New List<OpportunityLineItem> {oliprueba});
        
        oliprueba.Categoria_a_Rebaixar__c = cat.get('S1');
        test.starttest();
        update oliprueba;
        
        
        OpportunityLineItem oliprueba2 =  [SELECT Id, OpportunityId,PricebookEntry.Product2Id, PricebookEntry.Product2.Variedade__r.Name, Area__c, Sem_Rebajada__c, Semente_Bruta__c, Categoria__c, Categoria_a_Rebaixar__c FROM OpportunityLineItem WHERE Id=:anexoRoli2.Id];
        
        oPEE.validarRebajaAnexoI(New List<OpportunityLineItem> {oliprueba2});                     
     
        Test.stopTest();
        */
     
    }
    static testMethod void theTests6(){
        
        Test.startTest();
        
        Map<String,Id> rtype = New Map<String,Id>();
        for(RecordType reTy : [Select Id, Name From RecordType Where sObjectType = 'Opportunity'])
          rtype.put(reTy.Name, reTy.Id);        
        
        Map<String,Id> cat = New Map<String,Id>();
        for(Categoria__c cate : [SELECT Id, Name FROM Categoria__c])
            cat.put(cate.Name, cate.Id);
            

        
        Account cuenta = [Select Id From Account Where Name = 'ACME' AND CodigoSAP__c = '6000000000' limit 1];
        Pricebook2 pb1 = [Select Id, Name From Pricebook2 where Name = 'Lista de Básica BMX SUL' and isActive = true limit 1];
        //Opportunity prevision = New Opportunity(RecordTypeId=rtype.get('Previsao'), Name='Previsao', AccountId = cuenta.Id,Pricebook2Id=pb1.Id, CloseDate=System.today(), Marca__c='BRMX',StageName='Aberta', Safra__c='12/13');
        //insert prevision;
        PricebookEntry pbe = [Select Id, Product2Id From PricebookEntry where Pricebook2Id = :pb1.Id and Product2.Semilla_Tratada__c = false AND isActive = true and Product2.Categ__c = :cat.get('BASICA') limit 1];
        
        Opportunity opVB = New Opportunity(RecordTypeId=rtype.get('VB - Pendiente'), Name='Prueba1', AccountId = cuenta.Id,Pricebook2Id=pb1.Id, CloseDate=System.today(), Marca__c='BRMX',StageName='Aberta', Safra__c='12/13');
        insert opVB;
        OpportunityLineItem oi4 = new OpportunityLineItem(OpportunityId=opVB.Id,Quantity=0.01,Previsao__c = 50,TotalPrice=10,PricebookEntryId=pbe.Id);
        insert oi4;
        opportunityProductEntryExtension oPEE = new opportunityProductEntryExtension(new ApexPages.StandardController(opVB));

        oPEE.shoppingCart[0].Categoria__c = cat.get('C1');
        oPEE.onSave();
              
     
        Test.stopTest();
        
        List<OpportunityLineItem> itms = [Select Id, Id_Item_de_Oportunidad_Relacionado__c From OpportunityLineItem Where Id_Item_de_Oportunidad_Relacionado__c != null limit 1];
        oPEE.validarOfertaSAP(itms);
     
    }
    
    static testMethod void theTestsPendiente(){    
        Estado__c estado = new Estado__c(Name='PR'); insert estado;
        Centro_Logistico__c centro = new Centro_Logistico__c(Codigo_SAP__c='20442',Name='Londrina', Estado__c=estado.Id); insert centro;
         
        Map<String,Id> rtype = New Map<String,Id>();
        for(RecordType reTy : [Select Id, Name From RecordType Where sObjectType = 'Opportunity'])
          rtype.put(reTy.Name, reTy.Id);        
        
        Pricebook2 pb1 = [SELECT Id FROM Pricebook2 where Name = 'Lista Canal Multiplicadores' limit 1];
        Account cuenta = [Select Id From Account Where Name = 'ACME' AND CodigoSAP__c = '6000000000' limit 1];
        Opportunity newOpp1 = new Opportunity(Name='New Opp',Origen__c=centro.Id,RecordTypeId=rtype.get('Pendiente'),StageName='Pendiente',Amount=10,closeDate=System.Today()+30,AccountId=cuenta.Id);
        insert(newOpp1);
        
        Opportunity newDSEM = new Opportunity(Name='New Opp',Marca__c='DSEM',Origen__c=centro.Id,RecordTypeId=rtype.get('Pendiente'),StageName='Pendiente',Amount=10,closeDate=System.Today()+30,AccountId=cuenta.Id);
        insert(newDSEM);
         
        Map<String,Id> cat = New Map<String,Id>();
        for(Categoria__c cate : [SELECT Id, Name FROM Categoria__c])
            cat.put(cate.Name, cate.Id);
           
        test.starttest();

        opportunityProductEntryExtension oPEE = new opportunityProductEntryExtension(new ApexPages.StandardController(newDSEM));
        oPEE = new opportunityProductEntryExtension(new ApexPages.StandardController(newOpp1));
         
        //Pricebook2 pb1 = [Select Id, Name From Pricebook2 where Name = 'Lista de Básica BMX 2' and isActive = true limit 1];
        PricebookEntry pbe = [Select Id, Product2Id From PricebookEntry where Pricebook2Id = :pb1.Id and isActive = true and Product2.Categ__c = :cat.get('BASICA') limit 1];
        OpportunityLineItem oliNewOpp1 = new OpportunityLineItem(OpportunityId=newOpp1.Id,Quantity=0.01,TotalPrice=10,PricebookEntryId=pbe.Id, Categoria__c = cat.get('C1'), Area__c=50.00);
        insert oliNewOpp1;
        
        oPEE = new opportunityProductEntryExtension(new ApexPages.StandardController(newOpp1));
      
        Test.stopTest();
     
    }
    
}