Salesforce/main/default/main/default/objects/Account/fields/CodigoSAP__c.field-meta.xml
<CustomField>
    <fullName>CodigoSAP__c</fullName>
    <label>CodigoSAP</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/Account/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Estado</label>
    <referenceTo>Estado__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Account/fields/Multiplicador__c.field-meta.xml
<CustomField>
    <fullName>Multiplicador__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Multiplicador</label>
    <type>Checkbox</type>
</CustomField>

Salesforce/main/default/objects/Account/fields/Responsavel__c.field-meta.xml
<CustomField>
    <fullName>Responsavel__c</fullName>
    <description>Qual dos funcionários da Brasmax que estará responsável pela conta</description>
    <inlineHelpText>Qual dos funcionários da Brasmax que estará responsável pela conta</inlineHelpText>
    <label>Responsável BRMX</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>061 - Fernando Frehner</fullName>
            </value>
            <value>
                <fullName>066 - Marcelo Steffen</fullName>
            </value>
            <value>
                <fullName>067 - Sergio Bertagnolli</fullName>
            </value>
            <value>
                <fullName>076 - Tiago Goulart</fullName>
            </value>
            <value>
                <fullName>083 - Jorge Cristiano Rosa</fullName>
            </value>
            <value>
                <fullName>010 - Brasmax</fullName>
            </value>
            <value>
                <fullName>101 - Fausto Tadeu Fanchin</fullName>
            </value>
            <value>
                <fullName>104 - Otavio Gorni</fullName>
            </value>
            <value>
                <fullName>150 - João Serrano</fullName>
            </value>
            <value>
                <fullName>012 - Anderson Weissheimer</fullName>
            </value>
            <value>
                <fullName>197 - Wagner Rank</fullName>
            </value>
            <value>
                <fullName>198 - Bernardo Zanardo</fullName>
            </value>
            <value>
                <fullName>199 - Lucas Costa</fullName>
            </value>
            <value>
                <fullName>231 - Willian Von Scharten</fullName>
            </value>
            <value>
                <fullName>234 - Julio Cesar Poletto</fullName>
            </value>
            <value>
                <fullName>017 - Luis Fernando Cecatto</fullName>
            </value>
            <value>
                <fullName>018 - Flávio Marçal dos Santos</fullName>
            </value>
            <value>
                <fullName>312 - Lucas Hilario Fantineli</fullName>
            </value>
            <value>
                <fullName>019 - Felipe Oliveira Costa</fullName>
            </value>
            <value>
                <fullName>379 - Diego F. Gonçalves</fullName>
            </value>
            <value>
                <fullName>031 - Guilherme Sousa</fullName>
            </value>
            <value>
                <fullName>023 - Gabriel V. Finatto</fullName>
            </value>
            <value>
                <fullName>464 - Ana Laura Fernandes</fullName>
            </value>
            <value>
                <fullName>467 - Natalie de Mattos</fullName>
            </value>
            <value>
                <fullName>474 - Guilherme Menezes Salau</fullName>
            </value>
            <value>
                <fullName>403 - Felipe Bianchessi</fullName>
            </value>
            <value>
                <fullName>380 - Lucas de Souza Furlan</fullName>
            </value>
            <value>
                <fullName>037 - Felipe Dias Louzada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Account/recordTypes/Cuenta.recordType-meta.xml
<RecordType>
    <fullName>Cuenta</fullName>
    <active>true</active>
    <label>Cuenta</label>
</RecordType>

Salesforce/main/default/main/default/objects/Contrato__c/Contrato__c.object-meta.xml
<CustomObject>
    <description>CONTRATO DE LICENCIAMENTO PARA MULTIPLICAÇÃO E COMERCIALIZAÇÃO</description>
    <label>Contrato de Multiplicação</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Numero do Contrato de Multiplicação</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contratos de Multiplicação</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Salesforce/main/default/objects/Contrato__c/fields/Cultivar__c.field-meta.xml
<CustomField>
    <fullName>Cultivar__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Se refere ao produto (cultivar) que será feito o contrato (um contrato para cada produto). É por este fato que todos possuem o número 1 nas cultivares que a conta vai multiplicar</description>
    <inlineHelpText>Se refere ao produto (cultivar) que será feito o contrato (um contrato para cada produto). É por este fato que todos possuem o número 1 nas cultivares que a conta vai multiplicar</inlineHelpText>
    <label>Cultivar</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Contrato_de_Multiplica_o</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Contrato__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Edição</fullName>
                <default>true</default>
                <label>Edição</label>
            </value>
            <value>
                <fullName>Pendente de Aprovação</fullName>
            </value>
            <value>
                <fullName>Aguardando Assinatura</fullName>
            </value>
            <value>
                <fullName>Pendente de Impressão</fullName>
            </value>
            <value>
                <fullName>Pendente de Envio</fullName>
            </value>
            <value>
                <fullName>Pendente de Postagem</fullName>
            </value>
            <value>
                <fullName>Aguarda Retorno</fullName>
            </value>
            <value>
                <fullName>Chegou</fullName>
            </value>
            <value>
                <fullName>Inutilizado</fullName>
            </value>
            <value>
                <fullName>Anulado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Contrato__c/fields/Responsavel__c.field-meta.xml
<CustomField>
    <fullName>Responsavel__c</fullName>
    <description>Qual dos funcionários da Brasmax que estará responsável pela conta</description>
    <inlineHelpText>Qual dos funcionários da Brasmax que estará responsável pela conta</inlineHelpText>
    <label>Responsável</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Jacques Müllich</fullName>
            </value>
            <value>
                <fullName>Marcelo Steffen</fullName>
            </value>
            <value>
                <fullName>Thiago Schwonka</fullName>
            </value>
            <value>
                <fullName>Lucas Pires</fullName>
            </value>
            <value>
                <fullName>Fernando Frehner</fullName>
            </value>
            <value>
                <fullName>Sergio Bertagnolli</fullName>
            </value>
            <value>
                <fullName>Fernando Gaspar</fullName>
            </value>
            <value>
                <fullName>Antonio Paiva</fullName>
            </value>
            <value>
                <fullName>Tiago Goulart</fullName>
            </value>
            <value>
                <fullName>Jorge Cristiano Rosa</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Contrato__c/fields/Sociedad__c.field-meta.xml
<CustomField>
    <fullName>Sociedad__c</fullName>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BRMX</fullName>
            </value>
            <value>
                <fullName>DSEM</fullName>
            </value>
            <value>
                <fullName>NEOG</fullName>
            </value>
            <value>
                <fullName>DAGMA</fullName>
            </value>
            <value>
                <fullName>LICENÇAS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Contrato__c/fields/Tipo_de_cambio__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_cambio__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Tipo de câmbio</label>
    <precision>16</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

Salesforce/main/default/main/default/objects/Contrato__c/recordTypes/BRMX.recordType-meta.xml
<RecordType>
    <fullName>BRMX</fullName>
    <active>true</active>
    <description>Contratos de la sociedad BRASMAX</description>
    <label>BRMX</label>
</RecordType>

Salesforce/main/default/main/default/objects/Opportunity/fields/Ejercicio__c.field-meta.xml
<CustomField>
    <fullName>Ejercicio__c</fullName>
    <label>Ejercicio</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/Opportunity/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <formula>IF(NOT(ISNULL(Inicio_Cargamento__c)),
			IF(NOT(ISNULL(Inicio_Transporte__c)),
						IF(NOT(ISNULL(Fin_Transporte__c)),
									IF(AND(Confirmado__c,NOT(Solicitacao_de_reembolso__c)),
											&apos;Confirmado&apos;,
											IF(AND(Solicitacao_de_reembolso__c,NOT(Confirmado__c)),
													&apos;Em Troca&apos;,
													&apos;Entregue&apos;)
											),
									&apos;Pedido em trânsito&apos;),
						&apos;Em carregamento&apos;),
			&apos;&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status de transporte</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/Opportunity/fields/Estado_Facturacion__c.field-meta.xml
<CustomField>
    <fullName>Estado_Facturacion__c</fullName>
    <label>Estado Facturacion</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>PE Contabilizar</fullName>
            </value>
            <value>
                <fullName>Contabilizada</fullName>
            </value>
            <value>
                <fullName>Impresa</fullName>
            </value>
            <value>
                <fullName>Anulada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Opportunity/fields/Numero_Documento_SAP__c.field-meta.xml
<CustomField>
    <fullName>Numero_Documento_SAP__c</fullName>
    <label>Numero Documento SAP</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/Opportunity/fields/Numero_Legal__c.field-meta.xml
<CustomField>
    <fullName>Numero_Legal__c</fullName>
    <label>Numero Legal</label>
    <precision>15</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

Salesforce/main/default/objects/Opportunity/fields/Observaciones_Paso_a_SAP__c.field-meta.xml
<CustomField>
    <fullName>Observaciones_Paso_a_SAP__c</fullName>
    <label>Observaciones Paso a SAP</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/Opportunity/fields/Sap_J1b1_N_Fiscal__c.field-meta.xml
<CustomField>
    <fullName>Sap_J1b1_N_Fiscal__c</fullName>
    <description>Valor devuelto por la interfaz al generar el asiento y la nota fiscal en FI. J1B3 para ver en SAP</description>
    <label>Sap J1b1 N Fiscal</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/Opportunity/fields/Sociedad__c.field-meta.xml
<CustomField>
    <fullName>Sociedad__c</fullName>
    <label>Sociedad</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/Opportunity/fields/Sucursal__c.field-meta.xml
<CustomField>
    <fullName>Sucursal__c</fullName>
    <label>Sucursal</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0094 Passo Fundo</fullName>
            </value>
            <value>
                <fullName>0095 Londrina</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Opportunity/fields/Tipo_de_cambio__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_cambio__c</fullName>
    <description>Tipo de cambio al que sale impresa la factura</description>
    <inlineHelpText>Tipo de cambio al que sale impresa la factura</inlineHelpText>
    <label>Tipo de câmbio</label>
    <precision>16</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

Salesforce/main/default/main/default/objects/OpportunityLineItem/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Estado</label>
    <referenceTo>Estado__c</referenceTo>
    <relationshipLabel>Producto de oportunidad (Estado)</relationshipLabel>
    <relationshipName>Producto_de_oportunidad2</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/OpportunityLineItem/fields/Estado_Facturacion__c.field-meta.xml
<CustomField>
    <fullName>Estado_Facturacion__c</fullName>
    <label>Estado Facturacion</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Facturado</fullName>
            </value>
            <value>
                <fullName>No facturado</fullName>
                <default>true</default>
                <label>No facturado</label>
            </value>
            <value>
                <fullName>Pasado Pedido</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/OpportunityLineItem/fields/Tipo_de_cambio__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_cambio__c</fullName>
    <label>Tipo de câmbio</label>
    <precision>16</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

Salesforce/main/default/main/default/objects/Product2/fields/Sociedad__c.field-meta.xml
<CustomField>
    <fullName>Sociedad__c</fullName>
    <label>Sociedad</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BRMX</fullName>
            </value>
            <value>
                <fullName>DSEM</fullName>
            </value>
            <value>
                <fullName>NEOG</fullName>
            </value>
            <value>
                <fullName>DAGMA</fullName>
            </value>
            <value>
                <fullName>LICENÇAS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/classes/BMX_Opp_fc_Alta.cls
global class BMX_Opp_fc_Alta {

    public static boolean isApexTest = false;
    //@future (callout=true)

    webservice static void altaFC(Id oppId, String target) {
        Opportunity op = [Select Id, Name, Numero_legal__c, Stagename, CloseDate, Tipo_de_cambio__c, Sucursal__c, Account.CodigoSAP__c, Account.Responsavel__c, Account.Estado__r.Name From Opportunity Where Id = :oppId];         
        enviarSAP(op, target);
    }
                
    static void enviarSAP(Opportunity op, String target){
    
    String linea = '12';
    try {
     
        sapSoapFunctionsMcS.Z_FI_CREA_FACTURACION_BR soap = new sapSoapFunctionsMcS.Z_FI_CREA_FACTURACION_BR();
        sapSoapFunctionsMcS.ZFiCreaFacturacionBrResponse_element retorno = new sapSoapFunctionsMcS.ZFiCreaFacturacionBrResponse_element();
        sapSoapFunctionsMcS.TableOfBapiret2 EtReturn = new sapSoapFunctionsMcS.TableOfBapiret2();

        sapSoapFunctionsMcS.ZfiesJ1b1nHead IHeader = new sapSoapFunctionsMcS.ZfiesJ1b1nHead();
        IHeader.Bukrs = 'BRMX'; //Sociedad
        IHeader.Brnch = op.Sucursal__c.substring(0,4); //Sucursal
        IHeader.Parid = op.Account.CodigoSAP__c; //cod sap cuenta '6000000002'; 
        IHeader.Nfnum = String.ValueOf(op.Numero_Legal__c); //'58'; //nro fact contador

        IHeader.Docdat = String.valueOf(op.CloseDate).substring(0,10); //closedate
        IHeader.Pstdat = String.valueOf(system.today()).substring(0,10); //fecha actual '2010-10-01'; //

        sapSoapFunctionsMcS.ZfittJ1b1n ItPos = new sapSoapFunctionsMcS.ZfittJ1b1n();        
        sapSoapFunctionsMcS.ZfiesJ1b1n[] ItPoss = new  List<sapSoapFunctionsMcS.ZfiesJ1b1n>();
                
        String Suc = '';
        if (op.Sucursal__c.substring(0,4) == '0094')
           Suc='RS';           
        if (op.Sucursal__c.substring(0,4) == '0095')
           Suc='PR';
        
        List<OpportunityLineItem> items =[SELECT Id, Quantity, PriceBookEntry.Product2.Name, UnitPrice FROM OpportunityLineItem WHERE OpportunityId= : op.Id];        
        if (items != null){
           for (OpportunityLineItem i:items){
              sapSoapFunctionsMcS.ZfiesJ1b1n ItPos1 = new sapSoapFunctionsMcS.ZfiesJ1b1n();
              
              Decimal ZPRN = 0.0; Decimal ZINI = 0.0; Decimal ZPRC = 0.0;
              Double unitp=i.UnitPrice;
              Double tipoc=op.Tipo_de_cambio__c;
              ZPRN = Decimal.valueOf(unitp * tipoc);
              ZPRN = ZPRN.divide(1, 4, System.RoundingMode.UP);
                
              ItPos1.Maktx = i.PriceBookEntry.Product2.Name.substring(0,10); //name del producto
              ItPos1.Menge = String.valueof(i.Quantity);
              ItPos1.Netpr = String.valueof(ZPRN);
              ItPos1.Zuonr = op.Account.Responsavel__c;

              if (Suc == op.Account.Estado__r.Name){ //estado cuenta contra estado sucursal
                 ItPos1.Cfop10 = '5933AA';
              }
              else{
                    ItPos1.Cfop10 = '6933AA';
              } 
              ItPoss.add(ItPos1);
           }
        }
        
        ItPos.Item = ItPoss; 
                
        soap.inputHttpHeaders_x = new Map<String, String>();
        String encodedusernameandpassword;
        
        String myData = 'donmario:donmario';
        Blob hash = Blob.valueOf(myData);
        encodedusernameandpassword = EncodingUtil.base64Encode(hash);        
        soap.inputHttpHeaders_x.put('Authorization', 'Basic '+ encodedusernameandpassword);

        String retornando = '';                
        sapSoapFunctionsMcS.Bapiret2[] item;
        
        if (!isApexTest){
            retorno = soap.ZFiCreaFacturacionBr(EtReturn, IHeader, ItPos, target);
            linea = '92';
        }
        else{
            retorno.EpFb07 = '1900000015BRMX2010';   //Solo para motivos de testing
            retorno.EpJ1b1n = '0000000254';
        }
       
        linea = '84';
               
        if (retorno.EpFb07 != null && retorno.EpFb07 != ''){
           op.Numero_Documento_SAP__c = retorno.EpFb07.substring(0,10);
           op.Sociedad__c = retorno.EpFb07.substring(10,14);
           op.Ejercicio__c = retorno.EpFb07.substring(14,18);
        }
        else{
            if (retorno.EpJ1b1n == '0000000000'){
                String errores = IHeader.Nfnum + '\n';
                if(retorno.EtReturn.item[0] != null)
                    errores = retorno.EtReturn.item[0].Message;
                op.Observaciones_Paso_a_SAP__c = errores;
      
                update op;                              
                return;
            }
        }   
        
        if (retorno.EpJ1b1n != null)
            op.Sap_J1b1_N_Fiscal__c = retorno.EpJ1b1n;
      
        List<RecordType> rt = [SELECT Id FROM RecordType WHERE Name = 'Fc de Brasmax Contabilizada'];
        if (rt != null)
           op.RecordTypeId = rt[0].Id;
        op.Estado_facturacion__c = 'Contabilizada';
        op.Observaciones_Paso_a_SAP__c = 'OK';
        update op;        
        
    }catch(Exception e){
        op.Observaciones_Paso_a_SAP__c = 'Linea: ' + linea + '\nError: ' + e.getMessage();
        update op;
    }   
    }
    
    WebService static void mainForTest(Id oppId){
        isApexTest = true;        
        altaFC(oppId, '110');
    }
    
    public static testMethod void test(){
        RecordType rt = [Select Id From RecordType Where Name = 'BRMX' And SObjectType = 'Contrato__c' limit 1];
        
        Pricebook2 pb2 = [select id,name from Pricebook2 where name like '%Multiplica%' limit 1];
        PricebookEntry pbe = [Select id, Product2Id From PricebookEntry where isActive = true and Pricebook2Id = :pb2.id limit 1];
        Account a = new Account(Name='TMP');
        insert a;
        Contrato__c c = new Contrato__c(Cultivar__c=pbe.Product2Id, Multiplicador__c=a.Id, Sociedad__c='BRMX', RecordTypeId=rt.Id);
        insert c;                   
        Opportunity opp = new Opportunity(Tipo_de_Cambio__c=2,Sucursal__c='0094',Pricebook2Id=pb2.Id,AccountId=a.Id,Name='TMP',Safra__c='08/09',StageName='Aberta',CloseDate=System.Today());
        insert opp;
        OpportunityLineItem i = new OpportunityLineItem(OpportunityId=opp.Id,PricebookEntryId=pbe.id,Quantity=1,UnitPrice=2);
        insert i;
        BMX_Opp_fc_Alta.mainForTest(opp.Id);
        
    }
}