Salesforce/main/default/main/default/objects/Account/fields/CodigoSAP__c.field-meta.xml
<CustomField>
    <fullName>CodigoSAP__c</fullName>
    <label>CodigoSAP</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Dirección de Correo Electrónico de la cuenta</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

Salesforce/main/default/main/default/objects/Account/fields/Grupo_de_Cuentas__c.field-meta.xml
<CustomField>
    <fullName>Grupo_de_Cuentas__c</fullName>
    <label>Grupo de Cuentas</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CMEX</fullName>
            </value>
            <value>
                <fullName>CPFI</fullName>
            </value>
            <value>
                <fullName>CPJU</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Account/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Marca</valueSetName>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Account/fields/Nome_fantasia__c.field-meta.xml
<CustomField>
    <fullName>Nome_fantasia__c</fullName>
    <label>Nome fantasia</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/Configuracion_BMX__c/Configuracion_BMX__c.object-meta.xml
<CustomObject>
    <description>Indicador de Parametros.</description>
    <label>Configuracion_BMX</label>
    <nameField>
        <label>Configuracion Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuraciones_BMX</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/Configuracion_BMX__c/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BRMX</fullName>
                <default>true</default>
                <label>BRMX</label>
            </value>
            <value>
                <fullName>DSEM</fullName>
            </value>
            <value>
                <fullName>NEOG</fullName>
            </value>
            <value>
                <fullName>DAGMA</fullName>
            </value>
            <value>
                <fullName>LICENÇAS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Configuracion_BMX__c/fields/PM_Contact_Send_Email__c.field-meta.xml
<CustomField>
    <fullName>PM_Contact_Send_Email__c</fullName>
    <label>PM Contact Send Email</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/Configuracion_BMX__c/fields/PM_Email_Sender__c.field-meta.xml
<CustomField>
    <fullName>PM_Email_Sender__c</fullName>
    <label>PM Email Sender</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/Configuracion_BMX__c/fields/PM_Template_Forgot_Password__c.field-meta.xml
<CustomField>
    <fullName>PM_Template_Forgot_Password__c</fullName>
    <label>PM Template Forgot Password</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/Order/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Marca</valueSetName>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Order/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <label>Safra</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Safra</valueSetName>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/SiteUser__c/SiteUser__c.object-meta.xml
<CustomObject>
    <description>Forma parte del circuito del Sitio Portal Web.</description>
    <label>SiteUser</label>
    <nameField>
        <label>Nombre de Usuário</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SiteUsers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/SiteUser__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ativo</label>
    <type>Checkbox</type>
</CustomField>

Salesforce/main/default/objects/SiteUser__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Endereço</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/SiteUser__c/fields/ativar_conta_corrente__c.field-meta.xml
<CustomField>
    <fullName>ativar_conta_corrente__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Habilitado Conta Corriente</label>
    <type>Checkbox</type>
</CustomField>

Salesforce/main/default/objects/SiteUser__c/fields/Cadastro_pela_primeira_vez__c.field-meta.xml
<CustomField>
    <fullName>Cadastro_pela_primeira_vez__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Cadastro pela primeira vez</label>
    <type>Checkbox</type>
</CustomField>

Salesforce/main/default/main/default/objects/SiteUser__c/fields/Habilitado_Anexos__c.field-meta.xml
<CustomField>
    <fullName>Habilitado_Anexos__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Habilitado Anexos</label>
    <type>Checkbox</type>
</CustomField>

Salesforce/main/default/main/default/objects/SiteUser__c/fields/Habilitado_Eventos__c.field-meta.xml
<CustomField>
    <fullName>Habilitado_Eventos__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Habilitado Eventos</label>
    <type>Checkbox</type>
</CustomField>

Salesforce/main/default/main/default/objects/SiteUser__c/fields/Habilitado_Votacion_DSEM__c.field-meta.xml
<CustomField>
    <fullName>Habilitado_Votacion_DSEM__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Habilitado Votacion DSEM</label>
    <type>Checkbox</type>
</CustomField>

Salesforce/main/default/objects/SiteUser__c/fields/Habilitar_Royalty__c.field-meta.xml
<CustomField>
    <fullName>Habilitar_Royalty__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Habilitado Royalty</label>
    <type>Checkbox</type>
</CustomField>

Salesforce/main/default/main/default/objects/SiteUser__c/fields/Habilitar_Venda_de_Basica__c.field-meta.xml
<CustomField>
    <fullName>Habilitar_Venda_de_Basica__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Habilitar Venda de Basica</label>
    <type>Checkbox</type>
</CustomField>

Salesforce/main/default/objects/SiteUser__c/fields/MobilePhone__c.field-meta.xml
<CustomField>
    <fullName>MobilePhone__c</fullName>
    <label>Celular</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/SiteUser__c/fields/Occupation__c.field-meta.xml
<CustomField>
    <fullName>Occupation__c</fullName>
    <label>Ocupação</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/SiteUser__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Senha</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/SiteUser__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <label>Telefone</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/SiteUser__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <label>Site</label>
    <type>Url</type>
</CustomField>

Salesforce/main/default/main/default/objects/SiteUserAccount__c/SiteUserAccount__c.object-meta.xml
<CustomObject>
    <label>SiteUserAccount</label>
    <nameField>
        <label>Nombre de SiteUserAccount</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SiteUserAccounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/SiteUserAccount__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SiteUserAccounts</relationshipLabel>
    <relationshipName>SiteUserAccounts</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/SiteUserAccount__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ativa</label>
    <type>Checkbox</type>
</CustomField>

Salesforce/main/default/main/default/objects/SiteUserAccount__c/fields/SiteUser__c.field-meta.xml
<CustomField>
    <fullName>SiteUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SiteUser</label>
    <referenceTo>SiteUser__c</referenceTo>
    <relationshipLabel>SiteUserAccounts</relationshipLabel>
    <relationshipName>SiteUserAccounts</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/SiteUserSession__c/SiteUserSession__c.object-meta.xml
<CustomObject>
    <label>SiteUserSession</label>
    <nameField>
        <displayFormat>S{00000000}</displayFormat>
        <label>Nombre de SiteUserSession</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SiteUserSessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/objects/SiteUserSession__c/fields/Close_Time__c.field-meta.xml
<CustomField>
    <fullName>Close_Time__c</fullName>
    <label>Close Time</label>
    <type>DateTime</type>
</CustomField>

Salesforce/main/default/main/default/objects/SiteUserSession__c/fields/SiteUser__c.field-meta.xml
<CustomField>
    <fullName>SiteUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SiteUser</label>
    <referenceTo>SiteUser__c</referenceTo>
    <relationshipLabel>SiteUserSessions</relationshipLabel>
    <relationshipName>SiteUserSessions</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/SiteUserSession__c/fields/Valid_Session__c.field-meta.xml
<CustomField>
    <fullName>Valid_Session__c</fullName>
    <formula>AND(NOW() &lt;= Valid_Date_Time__c, isnull(Close_Time__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Valid Session</label>
    <type>Checkbox</type>
</CustomField>

Salesforce/main/default/globalValueSets/Marca.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BRMX</fullName>
    </customValue>
    <customValue>
        <fullName>DSEM</fullName>
    </customValue>
    <customValue>
        <fullName>NEOG</fullName>
    </customValue>
    <customValue>
        <fullName>DAGMA</fullName>
    </customValue>
    <customValue>
        <fullName>LICENÇAS</fullName>
    </customValue>
    <masterLabel>Marca</masterLabel>
</GlobalValueSet>

Salesforce/main/default/globalValueSets/Safra.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>14/15</fullName>
    </customValue>
    <customValue>
        <fullName>15/16</fullName>
    </customValue>
    <customValue>
        <fullName>16/17</fullName>
    </customValue>
    <customValue>
        <fullName>17/18</fullName>
    </customValue>
    <customValue>
        <fullName>18/19</fullName>
    </customValue>
    <customValue>
        <fullName>19/20</fullName>
    </customValue>
    <customValue>
        <fullName>20/21</fullName>
    </customValue>
    <customValue>
        <fullName>21/22</fullName>
    </customValue>
    <customValue>
        <fullName>22/23</fullName>
    </customValue>
    <customValue>
        <fullName>23/24</fullName>
    </customValue>
    <customValue>
        <fullName>08/09</fullName>
        <isActive>false</isActive>
        <label>08/09</label>
    </customValue>
    <customValue>
        <fullName>07/08</fullName>
        <isActive>false</isActive>
        <label>07/08</label>
    </customValue>
    <customValue>
        <fullName>10/11</fullName>
        <isActive>false</isActive>
        <label>10/11</label>
    </customValue>
    <customValue>
        <fullName>11/12</fullName>
        <isActive>false</isActive>
        <label>11/12</label>
    </customValue>
    <customValue>
        <fullName>12/13</fullName>
        <isActive>false</isActive>
        <label>12/13</label>
    </customValue>
    <customValue>
        <fullName>13/14</fullName>
        <isActive>false</isActive>
        <label>13/14</label>
    </customValue>
    <customValue>
        <fullName>09/10</fullName>
        <isActive>false</isActive>
        <label>09/10</label>
    </customValue>
    <masterLabel>Safra</masterLabel>
</GlobalValueSet>

Salesforce/main/default/classes/aSiteAuthManager.cls
public without sharing class aSiteAuthManager {
    
    public aSiteAuthManager() {
    }

    public static SiteUser__c UserLogin(String us, String pass){

        SiteUser__c[] users = aSiteUtils.queryResults3(SiteUser__c.SObjectType, null, 'Password__c = :v1', pass, 'Email__c = :v2',us, 'Active__c = :v3', true);
        if(users.size() > 0)
            return users[0];
        else
            return null;
    }    
    
    public static Account getActiveAccount_byUser(SiteUser__c user){

        SiteUserAccount__c usacc = aSiteAuthManager.VerifyActiveAccount(user);
        Account[] accs = aSiteUtils.queryResults1(Account.SObjectType, null, 'Id = :v1', usacc.Account__c);        
        if(accs.size() > 0)
            return accs[0];
        else
            return null;
    }
    
    public static List<SiteUserAccount__c> getUserAccounts_byUser(SiteUser__c user){
        String queryPlus;            
        queryPlus = 'Account__r.Site, Account__r.AccountNumber, Account__r.Grupo_de_cuentas__c, Account__r.Name, Account__r.Nome_Fantasia__c, Account__r.CodigoSAP__c, Account__r.BillingCountry ';

        List<SiteUserAccount__c> lista = new List<SiteUserAccount__c>();
        SiteUserAccount__c[] lusers = aSiteUtils.queryResults1(SiteUserAccount__c.SObjectType, queryPlus,'SiteUser__c = :v1', user.Id);
            
        return lusers;       
    }

    public static SiteUserAccount__c VerifyActiveAccount(SiteUser__c user){
        try{
            List<SiteUserAccount__c> lista = new List<SiteUserAccount__c>();            
            lista = aSiteAuthManager.getUserAccounts_byUser(user);
            for (SiteUserAccount__c acc : lista){
                if(acc.Active__c)
                    return acc;
            }
            return null;
        }
        catch(Exception ex){
            return null;    
        }
    }

    public static SiteUserSession__c getUserSession(String token){
        try{

            SiteUserSession__c userSess = new SiteUserSession__c();
            String plus = ', SiteUser__r.Email__c, SiteUser__r.Password__c '+
                          ', SiteUser__r.Site__c, SiteUser__r.Address__c '+
                          ', SiteUser__r.Occupation__c, SiteUser__r.Name '+
                          ', SiteUser__r.Phone__c, SiteUser__r.MobilePhone__c '+
                          ', SiteUser__r.Habilitado_Votacion_DSEM__c '+
                          ', SiteUser__r.Habilitado_Anexos__c '+
                          ', SiteUser__r.Habilitado_Eventos__c '+
                          ', SiteUser__r.Habilitar_Royalty__c '+
                          ', SiteUser__r.ativar_conta_corrente__c '+
                          ', SiteUser__r.Habilitar_Venda_de_Basica__c';
            SiteUserSession__c[] ss = Database.query(aSiteUtils.querySelect(SiteUserSession__c.SObjectType) + plus + ' from SiteUserSession__c where Id = :token and valid_session__c = true order by LastModifiedDate desc limit 1');

            //SiteUserSession__c[] ss = [Select Id, Marca__c, Safra__c, SiteUser__c, Name,
            //SiteUser__r.Email__c, SiteUser__r.Password__c, SiteUser__r.Site__c, SiteUser__r.Address__c, SiteUser__r.Occupation__c, SiteUser__r.Name 
            //FROM SiteUserSession__c where Id = :token and valid_session__c = true order by LastModifiedDate desc limit 1];
            
            if(ss.size() > 0)
                return ss[0];
            else
                return null;
        }
        catch(Exception ex){
            return null;    
        }
    }

    public static SiteUser__c VerifyUserSession(String token){
        try{

            SiteUserSession__c userSess = getUserSession(token);
            if(userSess==null)
                return null;

            SiteUser__c user = new SiteUser__c(Name=userSess.SiteUser__r.Name,Email__c=userSess.SiteUser__r.Email__c,Password__c=userSess.SiteUser__r.Password__c);
            user.Site__c = userSess.SiteUser__r.Site__c;
            user.Address__c = userSess.SiteUser__r.Address__c;
            user.Occupation__c = userSess.SiteUser__r.Occupation__c;
            user.Phone__c = userSess.SiteUser__r.Phone__c;
            user.MobilePhone__c = userSess.SiteUser__r.MobilePhone__c;
            user.Habilitado_Votacion_DSEM__c = userSess.SiteUser__r.Habilitado_Votacion_DSEM__c;
            user.Habilitado_Anexos__c = userSess.SiteUser__r.Habilitado_Anexos__c;
            user.Habilitado_Eventos__c = userSess.SiteUser__r.Habilitado_Eventos__c;
            user.Habilitar_Royalty__c = userSess.SiteUser__r.Habilitar_Royalty__c;
            user.Habilitar_Venda_de_Basica__c = userSess.SiteUser__r.Habilitar_Venda_de_Basica__c;
            user.Id = userSess.SiteUser__c;

            return user;
        }
        catch(Exception ex){
            return null;    
        }
    }
    
    public static String OpenUserSession(String userId, String ip, String company){
        try{
            SiteUserSession__c s = new SiteUserSession__c();
            //buscar si vale la pena traer una session valida
            s.SiteUser__c = userId;
            if(company==null) company = 'BRMX';
            s.Safra__c = '15/16';  //traer la campaña de alguna configuracion
            s.Marca__c = company;
            s.IP__c = ip;
            insert s;
            return s.Id;
        }
        catch(Exception ex){
            return null;    
        }
    }
    
    public static String RefreshUserSession(String token){
        try{
            SiteUserSession__c userSess = getUserSession(token);
            if(userSess==null)
                return null;

            update userSess;

            return userSess.Id;
        }
        catch(Exception ex){
            return null;    
        }
    
    }
    
    public static String CloseUserSession(String token){
        try{
            SiteUserSession__c userSess = new SiteUserSession__c();
            //SiteUserSession__c[] ss = [Select Id, Close_Time__c From SiteUserSession__c where Id = :token limit 1];
            SiteUserSession__c[] ss = aSiteUtils.queryResults1(SiteUserSession__c.SObjectType, null, 'Id = :v1', token);            
            if(ss.size() > 0)
                userSess = ss[0];
            else
                return 'No active session. Token=' + token;
            
            userSess.Close_Time__c = system.now();           
            update userSess;
            return 'Ok';
        }
        catch(Exception ex){
            return ex.getMessage();
        }
    }
    
    public static aSiteUtils.retorno ForgotPassword(String us){
        SiteUser__c user;
        SiteUser__c[] users = aSiteUtils.queryResults1(SiteUser__c.SObjectType, null, 'Email__c = :v1', us);
        Configuracion_BMX__c[] conf = aSiteUtils.queryResults1(Configuracion_BMX__c.SObjectType, null, 'Id != :v1', null);
        aSiteUtils.retorno ret = New aSiteUtils.retorno();
                
        Savepoint sp;
        
        try{
            sp = Database.setSavepoint();
            if(users.size() > 0){
                user = users[0];
                user.Password__c = string.valueof(Math.abs(Crypto.getRandomLong())).substring(0,5);
                user.Cadastro_pela_primeira_vez__c = false;
                update user;
            
                String templateId = conf[0].PM_Template_Forgot_Password__c;
                Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
                message.setTemplateId(templateId);
                message.setWhatId(user.Id);
                message.setCcAddresses(new String[]{user.Email__c});
                message.setTargetObjectId(conf[0].PM_Contact_Send_Email__c);   
                message.setOrgWideEmailAddressId(conf[0].PM_Email_Sender__c);    
                message.setSaveAsActivity(false);
                if (!Test.isRunningTest())
                    Messaging.sendEmail(new Messaging.SingleEmailMessage[] { message });
            }else{
                ret.mensaje = Label.Unknown_User;
                ret.exito = false;
                return ret;
            }
         }catch(Exception e){
            Database.rollback(sp);            
            ret.mensaje = Label.Recover_Password_Error;
            ret.exito = false;
            return ret;
        }
            
        ret.exito = true;
           
        return ret;
    }

    public static boolean ChangePassword(String token, String newPassword, String verifyNewPassword, String oldpassword){
        
        SiteUser__c us = VerifyUserSession(token);
        if(us==null)        
            return false;

        if(us.Password__c != oldpassword)
            return false;
            
        try{
            us.Password__c = newPassword;
            us.Cadastro_pela_primeira_vez__c = true;
            update us;
        }
        catch(Exception ex){
            return false;
        }
            
        return true;
    }
    
    public static String getMarcaBySession(String token){
        try{

            SiteUserSession__c userSess = new SiteUserSession__c();            
            SiteUserSession__c[] ss = Database.query(aSiteUtils.querySelect(SiteUserSession__c.SObjectType) + ' from SiteUserSession__c where Id = :token order by LastModifiedDate desc limit 1');
            
            if(ss.size() > 0)
                return ss[0].Marca__c;
            else
                return null;
        }
        catch(Exception ex){
            return null;    
        }
    }

  }