Salesforce/main/default/main/default/objects/Account/fields/Codigo_SAP__c.field-meta.xml
<CustomField>
    <fullName>Codigo_SAP__c</fullName>
    <formula>CodigoSAP__c</formula>
    <label>Codigo_SAP</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/Account/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Estado</label>
    <referenceTo>Estado__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Categoria__c/Categoria__c.object-meta.xml
<CustomObject>
    <description>Categorías</description>
    <label>Categoria</label>
    <nameField>
        <label>Nombre de Categoría</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categorias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/Centro_Logistico__c/Centro_Logistico__c.object-meta.xml
<CustomObject>
    <description>Son los centros logísticos de Brasmax</description>
    <label>Centro Logístico</label>
    <nameField>
        <label>Nombre de Centro Logístico</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Centros Logísticos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/Centro_Logistico__c/fields/Codigo_SAP__c.field-meta.xml
<CustomField>
    <fullName>Codigo_SAP__c</fullName>
    <label>Código SAP</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/Centro_Logistico__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Es el Estado del Centro de Origen</description>
    <label>Estado</label>
    <referenceTo>Estado__c</referenceTo>
    <relationshipLabel>Centros Logísticos</relationshipLabel>
    <relationshipName>Centros_Log_sticos</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/Configuracion_BMX__c/Configuracion_BMX__c.object-meta.xml
<CustomObject>
    <description>Indicador de Parametros.</description>
    <label>Configuracion_BMX</label>
    <nameField>
        <label>Configuracion Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuraciones_BMX</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/Configuracion_BMX__c/fields/PM_Safra_Actual__c.field-meta.xml
<CustomField>
    <fullName>PM_Safra_Actual__c</fullName>
    <label>PM Safra Actual</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/Contact/fields/Codigo_SAP__c.field-meta.xml
<CustomField>
    <fullName>Codigo_SAP__c</fullName>
    <label>Código SAP</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/Contact/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Es el Estado en el que reside el Contacto</description>
    <label>Estado</label>
    <referenceTo>Estado__c</referenceTo>
    <relationshipLabel>Contactos</relationshipLabel>
    <relationshipName>Contactos</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Estado__c/Estado__c.object-meta.xml
<CustomObject>
    <label>Estado</label>
    <nameField>
        <label>Nome do Estado</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estados</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/objects/Opportunity/fields/Destinatario_de_Mercaderia__c.field-meta.xml
<CustomField>
    <fullName>Destinatario_de_Mercaderia__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Recebedor mercadoria</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND (2 OR 3)</booleanFilter>
        <errorMessage>Destinatario de Mercadorias no pertenece a la Cuenta de la Venda o no se encuentra en SAP</errorMessage>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.RecordType.Name</field>
            <operation>equals</operation>
            <value>Destinatario Bloqueado</value>
        </filterItems>
        <filterItems>
            <field>Contact.RecordType.Name</field>
            <operation>equals</operation>
            <value>Destinatario Desbloqueado</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/Opportunity/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <formula>IF(NOT(ISNULL(Inicio_Cargamento__c)),
			IF(NOT(ISNULL(Inicio_Transporte__c)),
						IF(NOT(ISNULL(Fin_Transporte__c)),
									IF(AND(Confirmado__c,NOT(Solicitacao_de_reembolso__c)),
											&apos;Confirmado&apos;,
											IF(AND(Solicitacao_de_reembolso__c,NOT(Confirmado__c)),
													&apos;Em Troca&apos;,
													&apos;Entregue&apos;)
											),
									&apos;Pedido em trânsito&apos;),
						&apos;Em carregamento&apos;),
			&apos;&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status de transporte</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/Opportunity/fields/Origen__c.field-meta.xml
<CustomField>
    <fullName>Origen__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Es el Centro logístico desde el cual se despachan los productos</description>
    <label>Origem</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>O valor não existe ou não coincidem os critérios de filtro.</errorMessage>
        <filterItems>
            <field>Centro_Logistico__c.Licencias__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Centro_Logistico__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/Opportunity/fields/Sucursal__c.field-meta.xml
<CustomField>
    <fullName>Sucursal__c</fullName>
    <label>Sucursal</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0094 Passo Fundo</fullName>
            </value>
            <value>
                <fullName>0095 Londrina</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Opportunity/recordTypes/CVB_Pendiente.recordType-meta.xml
<RecordType>
    <fullName>CVB_Pendiente</fullName>
    <active>true</active>
    <businessProcess>Prevision Venta Basica</businessProcess>
    <description>Es la confirmación de la venta de básica antes de ser enviada a SAP como NV.</description>
    <label>CVB Pendiente</label>
</RecordType>

Salesforce/main/default/objects/OpportunityLineItem/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Categoria a ser licenciada</description>
    <inlineHelpText>Categoria a ser licenciada</inlineHelpText>
    <label>Categoria</label>
    <referenceTo>Categoria__c</referenceTo>
    <relationshipLabel>Producto de oportunidad</relationshipLabel>
    <relationshipName>Producto_de_oportunidad</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/OpportunityLineItem/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Estado</label>
    <referenceTo>Estado__c</referenceTo>
    <relationshipLabel>Producto de oportunidad (Estado)</relationshipLabel>
    <relationshipName>Producto_de_oportunidad2</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Product2/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <label>Categoria</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BREEDER</fullName>
            </value>
            <value>
                <fullName>FUNDADORA</fullName>
            </value>
            <value>
                <fullName>Genetica</fullName>
            </value>
            <value>
                <fullName>Pre Basica</fullName>
            </value>
            <value>
                <fullName>BASICA</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>C1</fullName>
            </value>
            <value>
                <fullName>C2</fullName>
            </value>
            <value>
                <fullName>R</fullName>
            </value>
            <value>
                <fullName>S1</fullName>
            </value>
            <value>
                <fullName>S2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/classes/OpportunityAutorizationControllerTest.cls
@IsTest
private class OpportunityAutorizationControllerTest {

    @TestSetup
    static void setup() {
        Configuracion_BMX__c conf = new Configuracion_BMX__c(PM_Safra_Actual__c = '18/19');
        insert conf;

        Categoria__c category = Build.aCategoria().withName('BASICA').withShowPortal(true).build();
        insert category;

        Product2 product = Build.aProduct2()
            .withName('Test product2')
            .withCategoria('BASICA')
            .withFamily('Royalty x Basica')
            .withPrice(40)
            .withIsActive(true)
            .withCateg(category)       
            .build();

        insert product;

        PricebookEntry pricebookEntry = Build.aPricebookEntry()
            .withPricebook2Id(Test.getStandardPricebookId())
            .withUnitPrice(58)
            .withProduct2Id(product)
            .withIsActive(true)
            .build();

        insert pricebookEntry;

        Account account = Build.anAccount().build();
        insert account;

        Opportunity opportunity = Build.anOpportunityCVBPendiente()
            .withAccountId(account)
            .withPricebook2Id(Test.getStandardPricebookId())
            .withCloseDate(System.today())
            .withMarca('BRMX')
            .withStageName('Aberta')
            .withSafra('14/15')
            .withMes('Março')
            .build();

        insert opportunity;

        OpportunityLineItem opportunityLineItem = Build.anOpportunityLineItem() 
            .withOpportunityId(opportunity)
            .withQuantity(20)
            .withUnitPrice(10)
            .withPricebookEntryId(pricebookEntry)
            .withSementeaprovada(50)
            .withSementecomercializada(50)
            .withBasedeCalculo(40)
            .withTasas(12)
            .build();

        insert opportunityLineItem;
    }

    @IsTest static void hasOpportunityLineItem() {
        Estado__c state = new Estado__c(Name='PR');
        insert state;

        Centro_Logistico__c logisticCenter = new Centro_Logistico__c(Codigo_SAP__c='20442',Name='BA', Estado__c=state.Id); 
        insert logisticCenter;
        
        Opportunity opportunnityToValidate = [SELECT Id, Origen__c FROM Opportunity LIMIT 1];

        opportunnityToValidate.Origen__c = logisticCenter.Id;
        update opportunnityToValidate;

        delete [SELECT Id FROM OpportunityLineItem];

        opportunnityToValidate = [
            SELECT Id, RecordTypeId, StageName, HasOpportunityLineItem, Sucursal__c, Origen__c, Destinatario_de_Mercaderia__c FROM Opportunity LIMIT 1
        ];

        test.startTest();
        try {
            String result = OpportunityAutorizationController.sendAutorizationRequest(opportunnityToValidate);
        } catch (Exception e) {
            System.assertEquals('Opportunity sem Produtos', e.getMessage());
        }
        test.stopTest();
    }

    @IsTest static void oppAnulada() {
        Estado__c state = new Estado__c(Name='PR');
        insert state;

        Centro_Logistico__c logisticCenter = new Centro_Logistico__c(Codigo_SAP__c='20442',Name='BA', Estado__c=state.Id); 
        insert logisticCenter;

        Opportunity opportunnityToValidate = [
            SELECT Id, RecordTypeId, StageName, HasOpportunityLineItem, Sucursal__c, Origen__c, Destinatario_de_Mercaderia__c FROM Opportunity LIMIT 1
        ];

        opportunnityToValidate.StageName = 'AN - Anulada';
        opportunnityToValidate.Origen__c = logisticCenter.Id;
        update opportunnityToValidate;

        test.startTest();
        try {
            String result = OpportunityAutorizationController.sendAutorizationRequest(opportunnityToValidate);
        } catch (Exception e) {
            System.assertEquals('Venda da Basica Anulada', e.getMessage());
        }
        test.stopTest();
    }

    @IsTest static void originEmpty() {
        Opportunity opportunnityToValidate = [
            SELECT Id, RecordTypeId, StageName, HasOpportunityLineItem, Sucursal__c, Origen__c, Destinatario_de_Mercaderia__c FROM Opportunity LIMIT 1
        ];

        opportunnityToValidate.Origen__c = null;
        opportunnityToValidate.Sucursal__c = null;
        update opportunnityToValidate;

        test.startTest();
        try {
            String result = OpportunityAutorizationController.sendAutorizationRequest(opportunnityToValidate);
        } catch (Exception e) {
            System.assertEquals('Falta sucursal', e.getMessage());
        }
        test.stopTest();
    }

    @IsTest static void mercaderiaEmpty() {
        Estado__c state = new Estado__c(Name='PR');
        insert state;

        Centro_Logistico__c logisticCenter = new Centro_Logistico__c(Codigo_SAP__c='20442',Name='BA', Estado__c=state.Id); 
        insert logisticCenter;

        Opportunity opportunnityToValidate = [
            SELECT Id, RecordTypeId, StageName, HasOpportunityLineItem, Sucursal__c, Origen__c, Destinatario_de_Mercaderia__c FROM Opportunity LIMIT 1
        ];

        opportunnityToValidate.Origen__c = logisticCenter.Id;
        opportunnityToValidate.Destinatario_de_Mercaderia__c = null;
        update opportunnityToValidate;

        test.startTest();
        try {
            String result = OpportunityAutorizationController.sendAutorizationRequest(opportunnityToValidate);
        } catch (Exception e) {
            System.assertEquals('Falta Destinatario', e.getMessage());
        }
        test.stopTest();
    }

    @IsTest static void sendToValidarPasoVBSAP() {
        RecordType recordTypeCVBPendiente = XappiaHelper.getRecordType('Opportunity', 'CVB_Pendiente');

        Estado__c state = new Estado__c(Name='PR');
        insert state;

        Centro_Logistico__c logisticCenter = new Centro_Logistico__c(Codigo_SAP__c='20442',Name='BA', Estado__c=state.Id); 
        insert logisticCenter;

        Account anAccount = [SELECT Id FROM Account LIMIT 1];

        Contact aContact = Build.aContactDestinatarioBloqueado().withAccountId(anAccount).build();
        insert aContact;

        Opportunity opportunnityToValidate = [
            SELECT Id, RecordTypeId, StageName, HasOpportunityLineItem, Sucursal__c, Origen__c, Destinatario_de_Mercaderia__c FROM Opportunity LIMIT 1
        ];

        opportunnityToValidate.RecordTypeId = recordTypeCVBPendiente.Id;
        opportunnityToValidate.Origen__c = logisticCenter.Id;
        opportunnityToValidate.Destinatario_de_Mercaderia__c = aContact.Id;
        update opportunnityToValidate;

        test.startTest();
        String result = OpportunityAutorizationController.sendAutorizationRequest(opportunnityToValidate);
        test.stopTest();

        System.assertNotEquals(null, JSON.deserializeUntyped(result));
    }
}