Salesforce/main/default/main/default/objects/Account/fields/Codigo_SAP__c.field-meta.xml
<CustomField>
    <fullName>Codigo_SAP__c</fullName>
    <formula>CodigoSAP__c</formula>
    <label>Codigo_SAP</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/Account/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Marca</valueSetName>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Account/fields/Responsavel_NEOGEN__c.field-meta.xml
<CustomField>
    <fullName>Responsavel_NEOGEN__c</fullName>
    <label>Responsável NEOGEN</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>020 - Eduardo L. da Silva</fullName>
            </value>
            <value>
                <fullName>346 - Marco A. Marchioro</fullName>
            </value>
            <value>
                <fullName>022 - Josiane Dotto Dalla Corte</fullName>
            </value>
            <value>
                <fullName>485 - Felipe Biasi</fullName>
            </value>
            <value>
                <fullName>486 - Vagner Carvalho</fullName>
            </value>
            <value>
                <fullName>487 - Clevison Moraes</fullName>
            </value>
            <value>
                <fullName>319 - Felipe Oliveira Costa</fullName>
                <isActive>false</isActive>
                <label>319 - Felipe Oliveira Costa</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/CRM_Calendario_de_Eventos__c/CRM_Calendario_de_Eventos__c.object-meta.xml
<CustomObject>
    <description>Registro de eventos programados pelo Multiplicador</description>
    <label>CRM Evento</label>
    <nameField>
        <label>Nome de CRM Evento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Eventos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/objects/CRM_Calendario_de_Eventos__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Conta multiplicador, que realizou ou eventos agendados</description>
    <inlineHelpText>Conta multiplicador, que realizou ou eventos agendados</inlineHelpText>
    <label>Nome da conta</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Agricultor__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Eventos (Cuenta)</relationshipLabel>
    <relationshipName>CRM_Calend_rio_de_eventos</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/CRM_Calendario_de_Eventos__c/fields/Data_e_horario_inicio__c.field-meta.xml
<CustomField>
    <fullName>Data_e_horario_inicio__c</fullName>
    <label>Data e horario inicio</label>
    <type>DateTime</type>
</CustomField>

Salesforce/main/default/objects/CRM_Calendario_de_Eventos__c/fields/Evento__c.field-meta.xml
<CustomField>
    <fullName>Evento__c</fullName>
    <description>Tipo de evento</description>
    <inlineHelpText>Tipo de evento</inlineHelpText>
    <label>Evento</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Día de Campo</fullName>
            </value>
            <value>
                <fullName>Area comercial</fullName>
            </value>
            <value>
                <fullName>Emplacamento</fullName>
            </value>
            <value>
                <fullName>Encontro Técnico</fullName>
            </value>
            <value>
                <fullName>Estação DONMARIO MAS</fullName>
            </value>
            <value>
                <fullName>Feiras</fullName>
            </value>
            <value>
                <fullName>Jornada Técnica</fullName>
            </value>
            <value>
                <fullName>Lado a Lado</fullName>
            </value>
            <value>
                <fullName>Painel Técnico</fullName>
            </value>
            <value>
                <fullName>Palestra</fullName>
            </value>
            <value>
                <fullName>Strip Test</fullName>
            </value>
            <value>
                <fullName>Tour dos Máximos Rendimentos</fullName>
            </value>
            <value>
                <fullName>Treinamento</fullName>
            </value>
            <value>
                <fullName>CESB</fullName>
            </value>
            <value>
                <fullName>Outdoor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/CRM_Calendario_de_Eventos__c/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <label>Safra</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>11/12</fullName>
            </value>
            <value>
                <fullName>12/13</fullName>
            </value>
            <value>
                <fullName>17/18</fullName>
            </value>
            <value>
                <fullName>18/19</fullName>
            </value>
            <value>
                <fullName>19/20</fullName>
            </value>
            <value>
                <fullName>20/21</fullName>
            </value>
            <value>
                <fullName>21/22</fullName>
                <default>true</default>
                <label>21/22</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Opportunity/fields/Cultura__c.field-meta.xml
<CustomField>
    <fullName>Cultura__c</fullName>
    <label>Cultura</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Milho</fullName>
            </value>
            <value>
                <fullName>Soja</fullName>
                <default>true</default>
                <label>Soja</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Opportunity/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <description>Identifica la marca para las Oportunidades del Circuito de Anexos. Se selecciona la lista de precios en función de este campo</description>
    <inlineHelpText>Identificar a marca de Oportunidades Circuito Anexos. Você seleciona a lista de preços com base neste campo</inlineHelpText>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BRMX</fullName>
            </value>
            <value>
                <fullName>DSEM</fullName>
            </value>
            <value>
                <fullName>NEOG</fullName>
            </value>
            <value>
                <fullName>DAGMA</fullName>
            </value>
            <value>
                <fullName>LICENÇAS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Opportunity/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <description>Safra o Campania agricola</description>
    <label>Safra</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>06/07</fullName>
            </value>
            <value>
                <fullName>07/08</fullName>
            </value>
            <value>
                <fullName>08/09</fullName>
            </value>
            <value>
                <fullName>09/10</fullName>
            </value>
            <value>
                <fullName>09/09</fullName>
            </value>
            <value>
                <fullName>10/10</fullName>
            </value>
            <value>
                <fullName>10/11</fullName>
            </value>
            <value>
                <fullName>11/11</fullName>
            </value>
            <value>
                <fullName>11/12</fullName>
            </value>
            <value>
                <fullName>12/12</fullName>
            </value>
            <value>
                <fullName>12/13</fullName>
            </value>
            <value>
                <fullName>13/14</fullName>
            </value>
            <value>
                <fullName>14/15</fullName>
            </value>
            <value>
                <fullName>15/16</fullName>
            </value>
            <value>
                <fullName>16/17</fullName>
            </value>
            <value>
                <fullName>17/18</fullName>
            </value>
            <value>
                <fullName>18/19</fullName>
            </value>
            <value>
                <fullName>19/20</fullName>
            </value>
            <value>
                <fullName>20/21</fullName>
            </value>
            <value>
                <fullName>21/22</fullName>
                <default>true</default>
                <label>21/22</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/User/fields/Codigo_SAP__c.field-meta.xml
<CustomField>
    <fullName>Codigo_SAP__c</fullName>
    <description>Código SAP, que se utiliza para determinar el responsable de la cuenta a que usuario se refiere(para hacer la relación)</description>
    <inlineHelpText>Código SAP, que se utiliza para determinar el responsable de la cuenta a que usuario se refiere(para hacer la relación)</inlineHelpText>
    <label>Código SAP</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/globalValueSets/Marca.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BRMX</fullName>
    </customValue>
    <customValue>
        <fullName>DSEM</fullName>
    </customValue>
    <customValue>
        <fullName>NEOG</fullName>
    </customValue>
    <customValue>
        <fullName>DAGMA</fullName>
    </customValue>
    <customValue>
        <fullName>LICENÇAS</fullName>
    </customValue>
    <masterLabel>Marca</masterLabel>
</GlobalValueSet>

Salesforce/main/default/classes/ResetAPITest.cls
@isTest
public with sharing class ResetAPITest {

    public static final String TESTACCTNAME = 'Test Account';
    public static final String TESTMARCA = 'NEOG';
    public static final String TESTSAFRA = '16/17';
    public static final String TESTCULTURA = 'Soja';
    
    @TestSetup
    static void makeData(){
       
        //create an account with valid Responavel_Neogen
        Account account = new Account( Name = TESTACCTNAME );

        // search active users for responsible fields
        Set<String> activeUserSet = new Set<String>();
        List<User> activeUserList = [SELECT Id, Name, Codigo_Sap__c FROM User WHERE Codigo_Sap__c != null AND User.IsActive = true];
        for(User activeUser : activeUserList) {
            activeUserSet.add(activeUser.Name);
        }

        //get Responsavel_Neogen picklist
		DescribeFieldResult responsavelNeogenField = Schema.Account.Responsavel_NEOGEN__c.getDescribe();
		List<Schema.PicklistEntry> picklistValues = responsavelNeogenField.getPickListValues();
        
        //sap codes list
        List<String> sapCodeList = new List<String>();
		for (Schema.PicklistEntry value : picklistValues) {
            String userName = value.getValue().split('-')[1].trim();
            if(value.isActive() && activeUserSet.contains(userName)) {
                account.Responsavel_NEOGEN__c = value.getValue();
                System.debug('Responsavel_Neogen__c: ' + value.getValue());
                break;
            }
		}
        
        insert account;

        Id recordTypeIdA1 = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Anexo I').getRecordTypeId();
        Id recordTypeIdA2 = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Anexo II').getRecordTypeId();

        // Insert test Opportunities
        List<Opportunity> opportunities = new List<Opportunity>();
        opportunities.add( new Opportunity( Name = 'Test Opportunity A1',
                                            Accountid = account.Id,
                                            Cultura__C = TESTCULTURA,
                                            Marca__C = TESTMARCA,
                                            Safra__C = TESTSAFRA,
                                            RecordTypeId = recordTypeIdA1,
                                            StageName = 'Aprobada',
                                            CloseDate = system.Today()
                                        )
            );
        opportunities.add( new Opportunity( Name = 'Test Opportunity A2',
                                            Accountid = account.Id,
                                            Cultura__C = TESTCULTURA,
                                            Marca__C = TESTMARCA,
                                            Safra__C = TESTSAFRA,
                                            RecordTypeId = recordTypeIdA2,
                                            StageName = 'Aprobada',
                                            CloseDate = system.Today()
                                        )
            );

        insert opportunities;  
		
        // Insert Events
        List<CRM_Calendario_de_Eventos__c> events = new List<CRM_Calendario_de_Eventos__c>();
        events.add( new CRM_Calendario_de_Eventos__c(   Name = 'Test Event Palestra',
                                                        Cuenta__c = account.Id,
                                                        Marca__C = TESTMARCA,
                                                        Safra__C = TESTSAFRA,
                                                        Evento__c = 'Palestra',
                                                        Data_e_horario_inicio__c = System.today(),
                                                        Data_e_horario_termino__c = System.today().addDays(1)
                                                    )
            );
        events.add( new CRM_Calendario_de_Eventos__c(   Name = 'Test Event Treinamento',
                                                        Cuenta__c = account.Id,
                                                        Marca__C = TESTMARCA,
                                                        Safra__C = TESTSAFRA,
                                                        Evento__c = 'Treinamento',
                                                     	Data_e_horario_inicio__c = System.today(),
                                                        Data_e_horario_termino__c = System.today().addDays(1)
                                                    )
            );

        insert events;  


    }    
    
    @isTest
    public static void resetAccountOpportunitiesAndEventsTestPositive() {
        
        Account account = [SELECT Id FROM Account WHERE Name = :TESTACCTNAME LIMIT 1];

        RestRequest req = new RestRequest(); 
        req.requestURI = '/services/apexrest/ResetAPI/';
        req.addParameter('accountId', account.Id);
        req.addParameter('marca', TESTMARCA);
        req.addParameter('safra', TESTSAFRA);
        req.addParameter('cultura', TESTCULTURA);  
        req.httpMethod = 'DELETE';

        RestContext.request = req;

        RestResponse resp = new RestResponse();
        RestContext.response = resp;

        test.startTest();
        ResetAPI.resetAccountOpportunitiesAndEvents();
        test.stopTest();
        
        ResetAPI.Response result = (ResetAPI.response)JSON.deserialize(resp.responseBody.toString(), ResetAPI.response.class);
      
        System.assertEquals(true, result.status);
        System.assertEquals(2, result.deletedOppIds.size());
        System.assertEquals(2, result.deletedCRMEventsIds.size());
    }
    
    @isTest
    public static void resetAccountOpportunitiesAndEventsTestNegative() {

        Account account = [SELECT Id FROM Account WHERE Name = :TESTACCTNAME LIMIT 1];
        
        RestRequest req = new RestRequest(); 
        req.requestURI = '/services/apexrest/ResetAPI/';
        req.addParameter('accountId', account.Id);
        req.addParameter('marca', 'BRMX');
        req.addParameter('safra', '18/19');
        req.addParameter('cultura', 'Milho');  
        req.httpMethod = 'DELETE';

		RestResponse resp = new RestResponse();

        RestContext.request = req;
        RestContext.response = resp;

        test.startTest();
        ResetAPI.resetAccountOpportunitiesAndEvents();
        test.stopTest();
        
        ResetAPI.Response result = (ResetAPI.response)JSON.deserialize(resp.responseBody.toString(), ResetAPI.response.class);
      
        System.assertEquals(false, result.status);
    }
}