Salesforce/main/default/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Dirección de Correo Electrónico de la cuenta</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

Salesforce/main/default/objects/Account/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Estado</label>
    <referenceTo>Estado__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/Account/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Marca</valueSetName>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Categoria__c/Categoria__c.object-meta.xml
<CustomObject>
    <description>Categorías</description>
    <label>Categoria</label>
    <nameField>
        <label>Nombre de Categoría</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categorias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/objects/Categoria__c/fields/Mostrar_en_portal__c.field-meta.xml
<CustomField>
    <fullName>Mostrar_en_portal__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Mostrar en portal</label>
    <type>Checkbox</type>
</CustomField>

Salesforce/main/default/main/default/objects/Estado__c/Estado__c.object-meta.xml
<CustomObject>
    <label>Estado</label>
    <nameField>
        <label>Nome do Estado</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estados</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/objects/Estado__c/fields/Estado_de_Origem__c.field-meta.xml
<CustomField>
    <fullName>Estado_de_Origem__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Este campo indica si el estado es estado de Origen.</description>
    <label>Estado de Origem?</label>
    <type>Checkbox</type>
</CustomField>

Salesforce/main/default/objects/OpportunityLineItem/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Categoria a ser licenciada</description>
    <inlineHelpText>Categoria a ser licenciada</inlineHelpText>
    <label>Categoria</label>
    <referenceTo>Categoria__c</referenceTo>
    <relationshipLabel>Producto de oportunidad</relationshipLabel>
    <relationshipName>Producto_de_oportunidad</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/OpportunityLineItem/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Estado</label>
    <referenceTo>Estado__c</referenceTo>
    <relationshipLabel>Producto de oportunidad (Estado)</relationshipLabel>
    <relationshipName>Producto_de_oportunidad2</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/OpportunityLineItem/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <formula>TEXT(Opportunity.Safra__c)</formula>
    <label>Safra</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/OpportunityLineItem/fields/Semente_aprovada__c.field-meta.xml
<CustomField>
    <fullName>Semente_aprovada__c</fullName>
    <label>Sem. Aprovada (Sacas)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/objects/OpportunityLineItem/fields/Variedad__c.field-meta.xml
<CustomField>
    <fullName>Variedad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Variedades que pueden incluirse en el contrato de multiplicacion</description>
    <inlineHelpText>Variedades que pueden incluirse en el contrato de multiplicacion</inlineHelpText>
    <label>Variedad</label>
    <referenceTo>Variedad__c</referenceTo>
    <relationshipLabel>Producto de oportunidad</relationshipLabel>
    <relationshipName>Producto_de_oportunidad</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Product2/fields/CANTIDAD_SUB_UNIDAD__c.field-meta.xml
<CustomField>
    <fullName>CANTIDAD_SUB_UNIDAD__c</fullName>
    <label>CANTIDAD_SUB_UNIDAD</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/Product2/fields/Categ__c.field-meta.xml
<CustomField>
    <fullName>Categ__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Categ</label>
    <referenceTo>Categoria__c</referenceTo>
    <relationshipLabel>Productos</relationshipLabel>
    <relationshipName>Productos</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Product2/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <label>Categoria</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BREEDER</fullName>
            </value>
            <value>
                <fullName>FUNDADORA</fullName>
            </value>
            <value>
                <fullName>Genetica</fullName>
            </value>
            <value>
                <fullName>Pre Basica</fullName>
            </value>
            <value>
                <fullName>BASICA</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>C1</fullName>
            </value>
            <value>
                <fullName>C2</fullName>
            </value>
            <value>
                <fullName>R</fullName>
            </value>
            <value>
                <fullName>S1</fullName>
            </value>
            <value>
                <fullName>S2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Product2/fields/Semilla_Tratada__c.field-meta.xml
<CustomField>
    <fullName>Semilla_Tratada__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indica si la semilla tiene tratamiento o no.</description>
    <label>Semente Tratada</label>
    <type>Checkbox</type>
</CustomField>

Salesforce/main/default/objects/Product2/fields/Variedad__c.field-meta.xml
<CustomField>
    <fullName>Variedad__c</fullName>
    <label>Variedad</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Licenciada__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>BMX APOLO RR</fullName>
            </value>
            <value>
                <fullName>BMX IMPACTO RR</fullName>
            </value>
            <value>
                <fullName>BMX MAGNA RR</fullName>
            </value>
            <value>
                <fullName>BMX POTÊNCIA RR</fullName>
            </value>
            <value>
                <fullName>BMX TITAN RR</fullName>
            </value>
            <value>
                <fullName>BMX FORÇA RR</fullName>
            </value>
            <value>
                <fullName>BMX ENERGIA RR</fullName>
            </value>
            <value>
                <fullName>BMX ATIVA RR</fullName>
            </value>
            <value>
                <fullName>BMX TURBO RR</fullName>
            </value>
            <value>
                <fullName>BMX VELOZ RR</fullName>
            </value>
            <value>
                <fullName>BMX ALVO RR</fullName>
            </value>
            <value>
                <fullName>BMX TORNADO RR</fullName>
            </value>
            <value>
                <fullName>BMX CLASSE RR</fullName>
            </value>
            <value>
                <fullName>BMX DESAFIO RR</fullName>
            </value>
            <value>
                <fullName>BMX RAÇA RR</fullName>
            </value>
            <value>
                <fullName>BMX PROGRESSO RR</fullName>
            </value>
            <value>
                <fullName>BRASMAX ELITE IPRO</fullName>
            </value>
            <value>
                <fullName>BRASMAX FLECHA IPRO</fullName>
            </value>
            <value>
                <fullName>BRASMAX BONUS IPRO</fullName>
            </value>
            <value>
                <fullName>BRASMAX BRAVA</fullName>
            </value>
            <value>
                <fullName>BRASMAX CLASSE</fullName>
            </value>
            <value>
                <fullName>BRASMAX PRISMA</fullName>
            </value>
            <value>
                <fullName>BRASMAX OPUS IPRO</fullName>
            </value>
            <value>
                <fullName>BRASMAX LANÇA IPRO</fullName>
            </value>
            <value>
                <fullName>BRASMAX GARRA IPRO</fullName>
            </value>
            <value>
                <fullName>BRASMAX ÍCONE IPRO</fullName>
            </value>
            <value>
                <fullName>BRASMAX POWER IPRO</fullName>
            </value>
            <value>
                <fullName>68I69RSF IPRO</fullName>
            </value>
            <value>
                <fullName>75I76RSF IPRO</fullName>
            </value>
            <value>
                <fullName>81I84RSF IPRO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Product2/fields/Variedade__c.field-meta.xml
<CustomField>
    <fullName>Variedade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Variedade</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Variedad__c.Licenciada__c</field>
            <operation>equals</operation>
            <valueField>$Source.Licenciada__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Variedad__c</referenceTo>
    <relationshipLabel>Productos</relationshipLabel>
    <relationshipName>Productos</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/SiteUser__c/SiteUser__c.object-meta.xml
<CustomObject>
    <description>Forma parte del circuito del Sitio Portal Web.</description>
    <label>SiteUser</label>
    <nameField>
        <label>Nombre de Usuário</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SiteUsers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/SiteUser__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ativo</label>
    <type>Checkbox</type>
</CustomField>

Salesforce/main/default/main/default/objects/SiteUser__c/fields/Habilitado_BRMX__c.field-meta.xml
<CustomField>
    <fullName>Habilitado_BRMX__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Habilitado BRMX</label>
    <type>Checkbox</type>
</CustomField>

Salesforce/main/default/objects/SiteUser__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Senha</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/SiteUserAccount__c/SiteUserAccount__c.object-meta.xml
<CustomObject>
    <label>SiteUserAccount</label>
    <nameField>
        <label>Nombre de SiteUserAccount</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SiteUserAccounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/SiteUserAccount__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SiteUserAccounts</relationshipLabel>
    <relationshipName>SiteUserAccounts</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/SiteUserAccount__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ativa</label>
    <type>Checkbox</type>
</CustomField>

Salesforce/main/default/main/default/objects/SiteUserAccount__c/fields/SiteUser__c.field-meta.xml
<CustomField>
    <fullName>SiteUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SiteUser</label>
    <referenceTo>SiteUser__c</referenceTo>
    <relationshipLabel>SiteUserAccounts</relationshipLabel>
    <relationshipName>SiteUserAccounts</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/SiteUserSession__c/SiteUserSession__c.object-meta.xml
<CustomObject>
    <label>SiteUserSession</label>
    <nameField>
        <displayFormat>S{00000000}</displayFormat>
        <label>Nombre de SiteUserSession</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SiteUserSessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/SiteUserSession__c/fields/SiteUser__c.field-meta.xml
<CustomField>
    <fullName>SiteUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SiteUser</label>
    <referenceTo>SiteUser__c</referenceTo>
    <relationshipLabel>SiteUserSessions</relationshipLabel>
    <relationshipName>SiteUserSessions</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Variedad__c/Variedad__c.object-meta.xml
<CustomObject>
    <description>Variedades, disponibles para incluir en los Contratos de Multiplicación</description>
    <label>Variedad</label>
    <nameField>
        <label>Nome Comercial</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Variedades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/globalValueSets/Marca.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BRMX</fullName>
    </customValue>
    <customValue>
        <fullName>DSEM</fullName>
    </customValue>
    <customValue>
        <fullName>NEOG</fullName>
    </customValue>
    <customValue>
        <fullName>DAGMA</fullName>
    </customValue>
    <customValue>
        <fullName>LICENÇAS</fullName>
    </customValue>
    <masterLabel>Marca</masterLabel>
</GlobalValueSet>

Salesforce/main/default/classes/SalvarStockAPITest.cls
/**
* @name SalvarStockAPITest
* @author Jhonny Peroza
* updated 13-10-2021
*/
@isTest
public class SalvarStockAPITest {

    final static String TESTMARCA = 'BRMX';
    final static String TESTSAFRA = '20/21';
    final static String TESTCULTURA = 'Soja';
    final static String TESTACCTNAME = 'Test Account';
    final static String TESTCANTSEMAPROBADA = '3000.00';
    final static String TESTCATEGORIA = 'BASICA';
    final static String PRICEBOOKNAME = 'Lista de Básica BMX SUL';
    final static String STOCKRECTYPE = 'Stock Multiplicadores';

    
    @TestSetup
    static void makeData(){
        test.startTest();

        // Insert Categoria__c records
        List<Categoria__c> categoriaList = new List<Categoria__c>();
        categoriaList.add( new Categoria__c(Name = TESTCATEGORIA) );
        insert categoriaList;

        // Insert Variedad__c records
        List<Variedad__c> variedadList = new List<Variedad__c>();
        variedadList.add( new Variedad__c(Name = 'Variedad 1 Test', Ativa__c = true) );
        variedadList.add( new Variedad__c(Name = 'Variedad 2 Test', Ativa__c = true) );
        insert variedadList;

        // Insert Product2 records
        List<Product2> productList = new List<Product2>();
        productList.add( new Product2(Name = 'Product 1 Test', IsActive = true, Categ__c = categoriaList[0].Id, Family = 'Semilla', Variedade__c = variedadList[0].Id, CANTIDAD_SUB_UNIDAD__c = '40') );
        productList.add( new Product2(Name = 'Product 2 Test', IsActive = true, Categ__c = categoriaList[0].Id, Family = 'Semilla', Variedade__c = variedadList[1].Id, CANTIDAD_SUB_UNIDAD__c = '40') );
        insert productList;

        // Insert Standard Pricebook prices
        Id stdPriceBookId = Test.getStandardPricebookId();
        List<PricebookEntry> stdPrices = new List<PricebookEntry>();
        stdPrices.add( new PricebookEntry(Pricebook2Id = stdPriceBookId, Product2Id = productList[0].Id, UnitPrice = 10) );
        stdPrices.add( new PricebookEntry(Pricebook2Id = stdPriceBookId, Product2Id = productList[1].Id, UnitPrice = 20) );
        insert stdPrices;

        // Insert Pricebook
        Pricebook2 pbRecord = new Pricebook2(Name = PRICEBOOKNAME, IsActive = true);
        insert pbRecord;

        // Insert Pricebook Entries with Product2.Categ__c.Name = 'BASICA' && Product2.Family = 'Semilla'
        List<PricebookEntry> pbEntries = new List<PricebookEntry>();
        pbEntries.add( new PricebookEntry(Pricebook2Id = pbRecord.Id, Product2Id = productList[0].Id, UnitPrice = 10, IsActive = true) );
        pbEntries.add( new PricebookEntry(Pricebook2Id = pbRecord.Id, Product2Id = productList[1].Id, UnitPrice = 20, IsActive = true) );
        insert pbEntries;

        // Insert Estado
        Estado__c estado = new Estado__c(Name = 'AC', Estado_de_Origem__c = false,  Mostrar_en_portal__c =  true );
        insert estado;

        // Insert Account
        List<Account> accountList = new List<Account>();
        accountList.add( new Account(Name = TESTACCTNAME) );

        insert accountList;

        // Insert SiteUser__c
        SiteUser__c siteUser = new SiteUser__c( Email__c = 'test@cloudgaia.com', Password__c = 'test-pass-cg-01', Habilitado_BRMX__c = true );
        insert siteUser;

        // Insert SiteUserAccount__c
        SiteUserAccount__c siteUserAccount = new SiteUserAccount__c( Name = 'Test Site User Account', Account__c = accountList[0].Id, SiteUser__c = siteUser.Id, Active__c = true );
        insert siteUserAccount;

        // Insert SiteUserSession__c
        SiteUserSession__c siteUserSession = new SiteUserSession__c( Marca__c = TESTMARCA, Safra__c = TESTSAFRA );
        insert siteUserSession;

        test.stopTest();    
    }


    @isTest
    public static void saveStock() {

        SalvarStockAPI.response result;

		SalvarStockAPI.Request requestBody = createTestRequest(true);

		RestResponse resp = new RestResponse();
        RestRequest req = new RestRequest(); 
        
        req.requestURI = '/services/apexrest/SalvarStockAPI/';  
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueof(JSON.serialize(requestBody));

        RestContext.request = req;
        RestContext.response = resp;

        test.startTest();
        SalvarStockAPI.salvarStock();
        test.stopTest();
        
        result = (SalvarStockAPI.response)JSON.deserialize(resp.responseBody.toString(), SalvarStockAPI.response.class);
      	
        System.assertEquals(true, result.status);
        System.assertEquals(Label.SalvarStockAPI_Success_Message, result.message);

    }

    @isTest
    public static void couldNotSaveStock() {

        SalvarStockAPI.response result;

		SalvarStockAPI.Request requestBody = createTestRequest(false);

		RestResponse resp = new RestResponse();
        RestRequest req = new RestRequest(); 
        
        req.requestURI = '/services/apexrest/SalvarStockAPI/';  
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueof(JSON.serialize(requestBody));

        RestContext.request = req;
        RestContext.response = resp;

        test.startTest();
        SalvarStockAPI.salvarStock();
        test.stopTest();
        
        result = (SalvarStockAPI.response)JSON.deserialize(resp.responseBody.toString(), SalvarStockAPI.response.class);
      	
        System.assertEquals(false, result.status);

    }

    @isTest 
    public static void testSalvarStockPositiveMultipleItems() {

		SalvarStockAPI.Request requestBody = createTestRequest(true);

		RestResponse resp = new RestResponse();
        RestRequest req = new RestRequest(); 
        
        req.requestURI = '/services/apexrest/SalvarStockAPI/';  
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueof(JSON.serialize(requestBody));

        RestContext.request = req;
        RestContext.response = resp;

        test.startTest();
        SalvarStockAPI.salvarStock();
        test.stopTest();
        
        SalvarStockAPI.response result = (SalvarStockAPI.response)JSON.deserialize(resp.responseBody.toString(), SalvarStockAPI.response.class);
      	
        System.assertEquals(true, result.status);

        List<OpportunityLineItem> insertedStockItems = [SELECT Id, Semente_aprovada__c FROM OpportunityLineItem WHERE OpportunityId = :result.id];
        for(OpportunityLineItem item : insertedStockItems) {
            System.assertEquals(TESTCANTSEMAPROBADA, String.valueOf(item.Semente_aprovada__c));
        }

    }

    private static SalvarStockAPI.Request createTestRequest(Boolean validItems) {

        SalvarStockAPI.Request requestBody = new SalvarStockAPI.Request();

        Account testAccount = [SELECT Id FROM Account WHERE Name = :TESTACCTNAME LIMIT 1];
        SiteUser__c siteUser = [SELECT Id FROM SiteUser__c LIMIT 1];

        requestBody.accId = testAccount.Id;
        requestBody.safra = TESTSAFRA;
        requestBody.marca = TESTMARCA;
        requestBody.mes = 'Outubro';
        requestBody.userId = siteUser.Id;
        requestBody.aprobacion = 'true';

        if(validItems) {
            List<aAppendix.myOppItem> items = new List<aAppendix.myOppItem>();      

            Estado__c estado = [SELECT Id FROM Estado__c LIMIT 1];
            List<Product2> testProducts =   [SELECT Id, Variedade__c, Variedade__r.Name, Categ__c, Name 
                                            FROM Product2 
                                            WHERE Family = 'Semilla' 
                                                AND Categ__r.Name = :TESTCATEGORIA
                                                AND Semilla_Tratada__c = false 
                                                AND CANTIDAD_SUB_UNIDAD__c = '40' 
                                                AND isActive = true];

            for (Product2 product : testProducts) {
                aAppendix.myOppItem item = new aAppendix.myOppItem();

                item.amount = 1.00;
                item.categoria = product.Categ__c;
                item.sem_comer = '10';
                item.variedad = product.Variedade__c;
                item.estado_comer_id = estado.Id;
                if(testProducts.indexOf(product) == 0) {
                    item.sem_aprobada = TESTCANTSEMAPROBADA;
                }

                items.add(item);
            }

            requestBody.items = items;

        } 

        return requestBody;

    }

}