Salesforce/main/default/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Dirección de Correo Electrónico de la cuenta</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

Salesforce/main/default/objects/Account/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Marca</valueSetName>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Categoria__c/Categoria__c.object-meta.xml
<CustomObject>
    <description>Categorías</description>
    <label>Categoria</label>
    <nameField>
        <label>Nombre de Categoría</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categorias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/objects/Categoria__c/fields/Mostrar_en_portal__c.field-meta.xml
<CustomField>
    <fullName>Mostrar_en_portal__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Mostrar en portal</label>
    <type>Checkbox</type>
</CustomField>

Salesforce/main/default/objects/Configuracion_BMX__c/Configuracion_BMX__c.object-meta.xml
<CustomObject>
    <description>Indicador de Parametros.</description>
    <label>Configuracion_BMX</label>
    <nameField>
        <label>Configuracion Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuraciones_BMX</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/Configuracion_BMX__c/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BRMX</fullName>
                <default>true</default>
                <label>BRMX</label>
            </value>
            <value>
                <fullName>DSEM</fullName>
            </value>
            <value>
                <fullName>NEOG</fullName>
            </value>
            <value>
                <fullName>DAGMA</fullName>
            </value>
            <value>
                <fullName>LICENÇAS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Opportunity/fields/Cultura__c.field-meta.xml
<CustomField>
    <fullName>Cultura__c</fullName>
    <label>Cultura</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Milho</fullName>
            </value>
            <value>
                <fullName>Soja</fullName>
                <default>true</default>
                <label>Soja</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Opportunity/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <description>Identifica la marca para las Oportunidades del Circuito de Anexos. Se selecciona la lista de precios en función de este campo</description>
    <inlineHelpText>Identificar a marca de Oportunidades Circuito Anexos. Você seleciona a lista de preços com base neste campo</inlineHelpText>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BRMX</fullName>
            </value>
            <value>
                <fullName>DSEM</fullName>
            </value>
            <value>
                <fullName>NEOG</fullName>
            </value>
            <value>
                <fullName>DAGMA</fullName>
            </value>
            <value>
                <fullName>LICENÇAS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Opportunity/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <description>Safra o Campania agricola</description>
    <label>Safra</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>06/07</fullName>
            </value>
            <value>
                <fullName>07/08</fullName>
            </value>
            <value>
                <fullName>08/09</fullName>
            </value>
            <value>
                <fullName>09/10</fullName>
            </value>
            <value>
                <fullName>09/09</fullName>
            </value>
            <value>
                <fullName>10/10</fullName>
            </value>
            <value>
                <fullName>10/11</fullName>
            </value>
            <value>
                <fullName>11/11</fullName>
            </value>
            <value>
                <fullName>11/12</fullName>
            </value>
            <value>
                <fullName>12/12</fullName>
            </value>
            <value>
                <fullName>12/13</fullName>
            </value>
            <value>
                <fullName>13/14</fullName>
            </value>
            <value>
                <fullName>14/15</fullName>
            </value>
            <value>
                <fullName>15/16</fullName>
            </value>
            <value>
                <fullName>16/17</fullName>
            </value>
            <value>
                <fullName>17/18</fullName>
            </value>
            <value>
                <fullName>18/19</fullName>
            </value>
            <value>
                <fullName>19/20</fullName>
            </value>
            <value>
                <fullName>20/21</fullName>
            </value>
            <value>
                <fullName>21/22</fullName>
                <default>true</default>
                <label>21/22</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Opportunity/recordTypes/Descarte.recordType-meta.xml
<RecordType>
    <fullName>Descarte</fullName>
    <active>true</active>
    <businessProcess>Circuito de Anexos</businessProcess>
    <label>Descarte</label>
</RecordType>

Salesforce/main/default/objects/OpportunityLineItem/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Categoria a ser licenciada</description>
    <inlineHelpText>Categoria a ser licenciada</inlineHelpText>
    <label>Categoria</label>
    <referenceTo>Categoria__c</referenceTo>
    <relationshipLabel>Producto de oportunidad</relationshipLabel>
    <relationshipName>Producto_de_oportunidad</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/OpportunityLineItem/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <formula>TEXT(Opportunity.Safra__c)</formula>
    <label>Safra</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/OpportunityLineItem/fields/Variedad__c.field-meta.xml
<CustomField>
    <fullName>Variedad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Variedades que pueden incluirse en el contrato de multiplicacion</description>
    <inlineHelpText>Variedades que pueden incluirse en el contrato de multiplicacion</inlineHelpText>
    <label>Variedad</label>
    <referenceTo>Variedad__c</referenceTo>
    <relationshipLabel>Producto de oportunidad</relationshipLabel>
    <relationshipName>Producto_de_oportunidad</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Product2/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <label>Categoria</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BREEDER</fullName>
            </value>
            <value>
                <fullName>FUNDADORA</fullName>
            </value>
            <value>
                <fullName>Genetica</fullName>
            </value>
            <value>
                <fullName>Pre Basica</fullName>
            </value>
            <value>
                <fullName>BASICA</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>C1</fullName>
            </value>
            <value>
                <fullName>C2</fullName>
            </value>
            <value>
                <fullName>R</fullName>
            </value>
            <value>
                <fullName>S1</fullName>
            </value>
            <value>
                <fullName>S2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Product2/fields/Variedad__c.field-meta.xml
<CustomField>
    <fullName>Variedad__c</fullName>
    <label>Variedad</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Licenciada__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>BMX APOLO RR</fullName>
            </value>
            <value>
                <fullName>BMX IMPACTO RR</fullName>
            </value>
            <value>
                <fullName>BMX MAGNA RR</fullName>
            </value>
            <value>
                <fullName>BMX POTÊNCIA RR</fullName>
            </value>
            <value>
                <fullName>BMX TITAN RR</fullName>
            </value>
            <value>
                <fullName>BMX FORÇA RR</fullName>
            </value>
            <value>
                <fullName>BMX ENERGIA RR</fullName>
            </value>
            <value>
                <fullName>BMX ATIVA RR</fullName>
            </value>
            <value>
                <fullName>BMX TURBO RR</fullName>
            </value>
            <value>
                <fullName>BMX VELOZ RR</fullName>
            </value>
            <value>
                <fullName>BMX ALVO RR</fullName>
            </value>
            <value>
                <fullName>BMX TORNADO RR</fullName>
            </value>
            <value>
                <fullName>BMX CLASSE RR</fullName>
            </value>
            <value>
                <fullName>BMX DESAFIO RR</fullName>
            </value>
            <value>
                <fullName>BMX RAÇA RR</fullName>
            </value>
            <value>
                <fullName>BMX PROGRESSO RR</fullName>
            </value>
            <value>
                <fullName>BRASMAX ELITE IPRO</fullName>
            </value>
            <value>
                <fullName>BRASMAX FLECHA IPRO</fullName>
            </value>
            <value>
                <fullName>BRASMAX BONUS IPRO</fullName>
            </value>
            <value>
                <fullName>BRASMAX BRAVA</fullName>
            </value>
            <value>
                <fullName>BRASMAX CLASSE</fullName>
            </value>
            <value>
                <fullName>BRASMAX PRISMA</fullName>
            </value>
            <value>
                <fullName>BRASMAX OPUS IPRO</fullName>
            </value>
            <value>
                <fullName>BRASMAX LANÇA IPRO</fullName>
            </value>
            <value>
                <fullName>BRASMAX GARRA IPRO</fullName>
            </value>
            <value>
                <fullName>BRASMAX ÍCONE IPRO</fullName>
            </value>
            <value>
                <fullName>BRASMAX POWER IPRO</fullName>
            </value>
            <value>
                <fullName>68I69RSF IPRO</fullName>
            </value>
            <value>
                <fullName>75I76RSF IPRO</fullName>
            </value>
            <value>
                <fullName>81I84RSF IPRO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/SiteUser__c/SiteUser__c.object-meta.xml
<CustomObject>
    <description>Forma parte del circuito del Sitio Portal Web.</description>
    <label>SiteUser</label>
    <nameField>
        <label>Nombre de Usuário</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SiteUsers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/objects/SiteUser__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Senha</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/Variedad__c/Variedad__c.object-meta.xml
<CustomObject>
    <description>Variedades, disponibles para incluir en los Contratos de Multiplicación</description>
    <label>Variedad</label>
    <nameField>
        <label>Nome Comercial</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Variedades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/Variedad__c/fields/Cultura__c.field-meta.xml
<CustomField>
    <fullName>Cultura__c</fullName>
    <label>Cultura</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SOJA</fullName>
            </value>
            <value>
                <fullName>MILHO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Variedad__c/fields/Disponivel_para_venda_basica__c.field-meta.xml
<CustomField>
    <fullName>Disponivel_para_venda_basica__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Disponivel para venda basica</label>
    <type>Checkbox</type>
</CustomField>

Salesforce/main/default/main/default/objects/Variedad__c/fields/Regiao_disponivel_para_venda_basica__c.field-meta.xml
<CustomField>
    <fullName>Regiao_disponivel_para_venda_basica__c</fullName>
    <label>Região disponível para venda básica</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>REGION 1</fullName>
            </value>
            <value>
                <fullName>REGION 2</fullName>
            </value>
            <value>
                <fullName>CERRADO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/globalValueSets/Marca.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BRMX</fullName>
    </customValue>
    <customValue>
        <fullName>DSEM</fullName>
    </customValue>
    <customValue>
        <fullName>NEOG</fullName>
    </customValue>
    <customValue>
        <fullName>DAGMA</fullName>
    </customValue>
    <customValue>
        <fullName>LICENÇAS</fullName>
    </customValue>
    <masterLabel>Marca</masterLabel>
</GlobalValueSet>

Salesforce/main/default/main/default/classes/SalvarA2APITest.cls
@isTest
public with sharing class SalvarA2APITest {
    
    @TestSetup
    static void makeData(){

        Account account = new Account(Name='test');

        insert account;

        Id recordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Anexo II').getRecordTypeId();

        Opportunity opportunity = new Opportunity();
        opportunity.Name = 'test config';
        opportunity.Accountid = account.Id;
        opportunity.Cultura__C = 'Milho';
        opportunity.Marca__C = 'BRMX';
        opportunity.Safra__C = '19/20';
        opportunity.RecordTypeId = recordTypeId;
        opportunity.StageName = 'Aprobada';
        opportunity.CloseDate = system.Today();

        insert opportunity;
		
        SiteUser__c testUser = new SiteUser__c();
		testUser.Email__c = 'test@gdm.com';
		testUser.Password__c = '123456';
        
		insert testUser;
        
        Categoria__c categoria = new Categoria__c(Name = 'BASICA',
                                                  Mostrar_en_portal__c = true);
        
		insert categoria;
        
        Variedad__c variedad = new Variedad__c(Name = 'Variedad1',
                                               Ativa__c = true,
                                               Regiao_disponivel_para_venda_basica__c = 'REGION 1',
                                               Disponivel_para_venda_basica__c = true,
                                               Marca_comercial__c = 'Brasmax');
        
        insert variedad;
        
        Product2 px1 = new Product2(Name = 'Test1',
                                    Especie__c = 'SOJA',
                                    Family = 'Royalty x Basica',
                                    Categ__c = categoria.Id,
                                    Variedade__c = variedad.Id );
        
        insert px1;
   		
        Id pricebookId = Test.getStandardPricebookId();
        
        PricebookEntry standardPrice = new PricebookEntry(
                                        Pricebook2Id = pricebookId, Product2Id = px1.Id,
                                        UnitPrice = 10000, IsActive = true);
        insert standardPrice;
        
        Pricebook2 s = new Pricebook2(Name = 'Lista Canal Multiplicadores', IsActive = true);
      	insert s;
            
        PricebookEntry pbesx = new PricebookEntry(Pricebook2Id=s.ID,
                                                  	Product2Id=px1.ID,
                                                    UnitPrice=0.00,
                                                  	IsActive=TRUE,
                                                    UseStandardPrice=FALSE);
        
        insert pbesx;
        
        Configuracion_BMX__c configBMX = new Configuracion_BMX__c();
        configBMX.Name = '20/21';
        configBMX.PM_Safra_Actual_A1__c = '19/20';
        configBMX.PM_Safra_Actual_A2__c = '19/20';

        insert configBMX;

        Estado__c estado = new Estado__c(Name = 'Test Estado', Mostrar_en_portal__c = true);
        insert estado;

    }    
    
    @isTest
    public static void postSalvarA2APITest() {
        
        SalvarA2API.response result;
        Account account = [select Id from Account limit 1];
        SiteUser__c user = [select Id from SiteUser__c limit 1];
        Categoria__c categoria = [select Id from Categoria__c WHERE Mostrar_en_portal__c = true limit 1];
        Variedad__c variedad = [select Id FROM Variedad__c WHERE Name = 'Variedad1' limit 1];
        
        List<aAppendix.myOppItem> items = new List<aAppendix.myOppItem>();

        aAppendix.myOppItem item = new aAppendix.myOppItem();
            item.amount=1.00;
            item.area_autorizada='2';
            item.area_plantada='2';
            item.categoria=categoria.Id;
            item.categoria_a_rebajar=null;
            item.categoria_a_rebajar_id=null;
            item.categoria_id=null;
            item.categoria_nombre='BASICA';
            item.cnpj=null;
            item.descarte='1';
            item.epocaPlantio=null;
            item.error_lote=null;
            item.error_msg=null;
            item.estadoProduccion_id=null;
            item.estadoProduccion_nombre=null;
            item.estado_comer_id=null;
            item.haAutorizados=0.00;
            item.id='';
            item.indice=null;
            item.lote_rebajado=null;
            item.name=null;
            item.registro='8745 RSF';
            item.sem_aprobada='1';
            item.sem_beneficiada='2';
            item.sem_bruta='1';
            item.sem_comer='a';
            item.sem_bruta_A2=null;
            item.sem_comer_up_aIII=null;
            item.sem_rebajada='1';
            item.sem_uso_propio='1';
            item.unidadDescarte=null;
            item.unidade=null;
            item.unidade_nombre=null;
            item.variedad=variedad.Id;
            item.variedad_nombre='BMX DESAFIO RR';
            item.variedad_registro=null;

        items.add(item);
        
		SalvarA1API.Request requestBody = new SalvarA1API.Request();
        
        requestBody.accountId = account.Id;
        requestBody.marca = 'BRMX';
        requestBody.userId = user.Id;
        requestBody.aprobacion = '';
        requestBody.nuevosProductos = items;
        requestBody.idAnexoEditar = null;
        
		RestResponse resp = new RestResponse();
        RestRequest req = new RestRequest(); 
        
        req.requestURI = '/services/apexrest/SalvarA1API/';  
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueof(JSON.serialize(requestBody));

        RestContext.request = req;
        RestContext.response = resp;

        test.startTest();
        SalvarA2API.postSalvarA2API();
        test.stopTest();
        
        result = (SalvarA2API.response)JSON.deserialize(resp.responseBody.toString(), SalvarA2API.response.class);
      
        System.assertEquals(true, result.status);
    }
    
     @isTest
    public static void postSalvarA2APIAprovacionTest() {
        
    SalvarA2API.response result;
        Account account = [select Id from Account limit 1];
        SiteUser__c user = [select Id from SiteUser__c limit 1];
        Categoria__c categoria = [select Id from Categoria__c WHERE Mostrar_en_portal__c = true limit 1];
        Variedad__c variedad = [select Id FROM Variedad__c WHERE Name = 'Variedad1' limit 1];
        
         List<aAppendix.myOppItem> items = new List<aAppendix.myOppItem>();

        aAppendix.myOppItem item = new aAppendix.myOppItem();
            item.amount=1.00;
            item.area_autorizada='2';
            item.area_plantada='2';
            item.categoria=categoria.Id;
            item.categoria_a_rebajar=null;
            item.categoria_a_rebajar_id=null;
            item.categoria_id=null;
            item.categoria_nombre='BASICA';
            item.cnpj=null;
            item.descarte='1';
            item.epocaPlantio=null;
            item.error_lote=null;
            item.error_msg=null;
            item.estadoProduccion_id=null;
            item.estadoProduccion_nombre=null;
            item.estado_comer_id=null;
            item.haAutorizados=0.00;
            item.id='';
            item.indice=null;
            item.lote_rebajado=null;
            item.name=null;
            item.registro='8745 RSF';
            item.sem_aprobada='1';
            item.sem_beneficiada='2';
            item.sem_bruta='1';
            item.sem_comer='a';
            item.sem_bruta_A2=null;
            item.sem_comer_up_aIII=null;
            item.sem_rebajada='1';
            item.sem_uso_propio='1';
            item.unidadDescarte=null;
            item.unidade=null;
            item.unidade_nombre=null;
            item.variedad=variedad.Id;
            item.variedad_nombre='BMX DESAFIO RR';
            item.variedad_registro=null;

        items.add(item);
        
		SalvarA1API.Request requestBody = new SalvarA1API.Request();
        
        requestBody.accountId = account.Id;
        requestBody.marca = 'BRMX';
        requestBody.userId = user.Id;
        requestBody.aprobacion = 'true';
        requestBody.nuevosProductos = items;
        requestBody.idAnexoEditar = null;
        
		RestResponse resp = new RestResponse();
        RestRequest req = new RestRequest(); 
        
        req.requestURI = '/services/apexrest/SalvarA1API/';  
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueof(JSON.serialize(requestBody));

        RestContext.request = req;
        RestContext.response = resp;

        test.startTest();
        SalvarA2API.postSalvarA2API();
        test.stopTest();
        
        result = (SalvarA2API.response)JSON.deserialize(resp.responseBody.toString(), SalvarA2API.response.class);
      
        System.assertEquals(true, result.status);
    }

    @isTest
    public static void postSalvarA2APIEditA2Test() {
        
    SalvarA2API.response result;
        Account account = [select Id from Account limit 1];
        SiteUser__c user = [select Id from SiteUser__c limit 1];
        Categoria__c categoria = [select Id from Categoria__c WHERE Mostrar_en_portal__c = true limit 1];
        Variedad__c variedad = [select Id FROM Variedad__c WHERE Name = 'Variedad1' limit 1];
        Product2 product = [select Id from Product2 WHERE Name = 'Test1' limit 1];
        PricebookEntry prBEntry = [select Id from PricebookEntry where Product2Id = :product.Id limit 1];
        Estado__c estado = [select Id from Estado__c where Name = 'Test Estado'];

        Id recordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Anexo II').getRecordTypeId();
        Opportunity opportunity2 = new Opportunity();
        opportunity2.Name = 'test opp';
        opportunity2.Accountid = account.Id;
        opportunity2.Cultura__C = 'Milho';
        opportunity2.Marca__C = 'BRMX';
        opportunity2.Safra__C = '19/20';
        opportunity2.RecordTypeId = recordTypeId;
        opportunity2.StageName = 'Edición';
        opportunity2.CloseDate = system.Today();

        insert opportunity2;

        OpportunityLineItem oppLineItem = new OpportunityLineItem(OpportunityId = opportunity2.Id,
                                                                  Product2Id = product.Id,
                                                                  PricebookEntryId = prBEntry.Id,
                                                                  Categoria__c = categoria.Id,
                                                                  UnitPrice = 10,
                                                                  Quantity = 1000,
                                                                  Semente_bruta__c = 1000,
                                                                  Estado_de_Comercializacion__c = estado.Id
                                                                  );

        insert oppLineItem;

        List<aAppendix.myOppItem> items = new List<aAppendix.myOppItem>();

        aAppendix.myOppItem item = new aAppendix.myOppItem();
            item.amount=1.00;
            item.area_autorizada='2';
            item.area_plantada='2';
            item.categoria=categoria.Id;
            item.categoria_a_rebajar=null;
            item.categoria_a_rebajar_id=null;
            item.categoria_id=null;
            item.categoria_nombre='BASICA';
            item.cnpj=null;
            item.descarte='1';
            item.epocaPlantio=null;
            item.error_lote=null;
            item.error_msg=null;
            item.estadoProduccion_id=null;
            item.estadoProduccion_nombre=null;
            item.estado_comer_id=null;
            item.haAutorizados=0.00;
            item.id=oppLineItem.Id;
            item.indice=null;
            item.lote_rebajado=null;
            item.name=null;
            item.registro='8745 RSF';
            item.sem_aprobada='1';
            item.sem_beneficiada='2';
            item.sem_bruta='1';
            item.sem_comer='a';
            item.sem_bruta_A2=null;
            item.sem_comer_up_aIII=null;
            item.sem_rebajada='1';
            item.sem_uso_propio='1';
            item.unidadDescarte=null;
            item.unidade=null;
            item.unidade_nombre=null;
            item.variedad=variedad.Id;
            item.variedad_nombre='BMX DESAFIO RR';
            item.variedad_registro=null;

        items.add(item);
        
		SalvarA1API.Request requestBody = new SalvarA1API.Request();
        
        requestBody.accountId = account.Id;
        requestBody.marca = 'BRMX';
        requestBody.userId = user.Id;
        requestBody.aprobacion = 'true';
        requestBody.nuevosProductos = items;
        requestBody.idAnexoEditar = opportunity2.Id;
        
		RestResponse resp = new RestResponse();
        RestRequest req = new RestRequest(); 
        
        req.requestURI = '/services/apexrest/SalvarA1API/';  
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueof(JSON.serialize(requestBody));

        RestContext.request = req;
        RestContext.response = resp;

        test.startTest();
        SalvarA2API.postSalvarA2API();
        test.stopTest();
        
        result = (SalvarA2API.response)JSON.deserialize(resp.responseBody.toString(), SalvarA2API.response.class);
      
        System.assertEquals(true, result.status);
    }

    @isTest
    public static void postSalvarA2APIEditA2NegativeTest() {
        
    SalvarA2API.response result;
        Account account = [select Id from Account limit 1];
        SiteUser__c user = [select Id from SiteUser__c limit 1];
        Categoria__c categoria = [select Id from Categoria__c WHERE Mostrar_en_portal__c = true limit 1];
        Variedad__c variedad = [select Id FROM Variedad__c WHERE Name = 'Variedad1' limit 1];
        Product2 product = [select Id from Product2 WHERE Name = 'Test1' limit 1];
        PricebookEntry prBEntry = [select Id from PricebookEntry where Product2Id = :product.Id limit 1];
        Estado__c estado = [select Id from Estado__c where Name = 'Test Estado'];

        Id recordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Anexo II').getRecordTypeId();
        Opportunity opportunity2 = new Opportunity();
        opportunity2.Name = 'test opp';
        opportunity2.Accountid = account.Id;
        opportunity2.Cultura__C = 'Milho';
        opportunity2.Marca__C = 'BRMX';
        opportunity2.Safra__C = '19/20';
        opportunity2.RecordTypeId = recordTypeId;
        opportunity2.StageName = 'Aprobada';
        opportunity2.CloseDate = system.Today();

        insert opportunity2;

        OpportunityLineItem oppLineItem = new OpportunityLineItem(OpportunityId = opportunity2.Id,
                                                                  Product2Id = product.Id,
                                                                  PricebookEntryId = prBEntry.Id,
                                                                  Categoria__c = categoria.Id,
                                                                  UnitPrice = 10,
                                                                  Quantity = 1000,
                                                                  Semente_bruta__c = 1000,
                                                                  Estado_de_Comercializacion__c = estado.Id
                                                                  );

        insert oppLineItem;

        List<aAppendix.myOppItem> items = new List<aAppendix.myOppItem>();

        aAppendix.myOppItem item = new aAppendix.myOppItem();
            item.amount=1.00;
            item.area_autorizada='2';
            item.area_plantada='2';
            item.categoria=categoria.Id;
            item.categoria_a_rebajar=null;
            item.categoria_a_rebajar_id=null;
            item.categoria_id=null;
            item.categoria_nombre='BASICA';
            item.cnpj=null;
            item.descarte='1';
            item.epocaPlantio=null;
            item.error_lote=null;
            item.error_msg=null;
            item.estadoProduccion_id=null;
            item.estadoProduccion_nombre=null;
            item.estado_comer_id=null;
            item.haAutorizados=0.00;
            item.id=oppLineItem.Id;
            item.indice=null;
            item.lote_rebajado=null;
            item.name=null;
            item.registro='8745 RSF';
            item.sem_aprobada='1';
            item.sem_beneficiada='2';
            item.sem_bruta='1';
            item.sem_comer='a';
            item.sem_bruta_A2=null;
            item.sem_comer_up_aIII=null;
            item.sem_rebajada='1';
            item.sem_uso_propio='1';
            item.unidadDescarte=null;
            item.unidade=null;
            item.unidade_nombre=null;
            item.variedad=variedad.Id;
            item.variedad_nombre='BMX DESAFIO RR';
            item.variedad_registro=null;

        items.add(item);
        
		SalvarA1API.Request requestBody = new SalvarA1API.Request();
        
        requestBody.accountId = account.Id;
        requestBody.marca = 'BRMX';
        requestBody.userId = user.Id;
        requestBody.aprobacion = 'true';
        requestBody.nuevosProductos = items;
        requestBody.idAnexoEditar = opportunity2.Id;
        
		RestResponse resp = new RestResponse();
        RestRequest req = new RestRequest(); 
        
        req.requestURI = '/services/apexrest/SalvarA1API/';  
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueof(JSON.serialize(requestBody));

        RestContext.request = req;
        RestContext.response = resp;

        test.startTest();
        SalvarA2API.postSalvarA2API();
        test.stopTest();
        
        result = (SalvarA2API.response)JSON.deserialize(resp.responseBody.toString(), SalvarA2API.response.class);
      
        System.assertEquals(false, result.status);
    }
}