Salesforce/main/default/main/default/objects/Account/fields/Multiplicador__c.field-meta.xml
<CustomField>
    <fullName>Multiplicador__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Multiplicador</label>
    <type>Checkbox</type>
</CustomField>

Salesforce/main/default/main/default/objects/Contrato__c/Contrato__c.object-meta.xml
<CustomObject>
    <description>CONTRATO DE LICENCIAMENTO PARA MULTIPLICAÇÃO E COMERCIALIZAÇÃO</description>
    <label>Contrato de Multiplicação</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Numero do Contrato de Multiplicação</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contratos de Multiplicação</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Salesforce/main/default/objects/Contrato__c/fields/Comercializa_Paraguai__c.field-meta.xml
<CustomField>
    <fullName>Comercializa_Paraguai__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Se indica si es un contrato de Paraguay</description>
    <label>Comercializa Paraguai</label>
    <type>Checkbox</type>
</CustomField>

Salesforce/main/default/objects/Contrato__c/fields/Cultivar__c.field-meta.xml
<CustomField>
    <fullName>Cultivar__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Se refere ao produto (cultivar) que será feito o contrato (um contrato para cada produto). É por este fato que todos possuem o número 1 nas cultivares que a conta vai multiplicar</description>
    <inlineHelpText>Se refere ao produto (cultivar) que será feito o contrato (um contrato para cada produto). É por este fato que todos possuem o número 1 nas cultivares que a conta vai multiplicar</inlineHelpText>
    <label>Cultivar</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Contrato_de_Multiplica_o</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Contrato__c/fields/Multiplicador__c.field-meta.xml
<CustomField>
    <fullName>Multiplicador__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Conta do multiplicador</description>
    <label>Multiplicador</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Contrato_de_Multiplica_o</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/Contrato__c/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <label>Safra</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>17/18</fullName>
                <default>true</default>
                <label>17/18</label>
            </value>
            <value>
                <fullName>18/19</fullName>
            </value>
            <value>
                <fullName>19/20</fullName>
            </value>
            <value>
                <fullName>20/21</fullName>
            </value>
            <value>
                <fullName>21/22</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Contrato__c/fields/Sociedad__c.field-meta.xml
<CustomField>
    <fullName>Sociedad__c</fullName>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BRMX</fullName>
            </value>
            <value>
                <fullName>DSEM</fullName>
            </value>
            <value>
                <fullName>NEOG</fullName>
            </value>
            <value>
                <fullName>DAGMA</fullName>
            </value>
            <value>
                <fullName>LICENÇAS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Contrato__c/fields/Tipo_de_Cota_o__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Cota_o__c</fullName>
    <label>Tipo de Cotação</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sociedad__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>DOLAR</fullName>
            </value>
            <value>
                <fullName>SOJA</fullName>
            </value>
            <value>
                <fullName>FATURAMENTO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Contrato__c/recordTypes/BRMX.recordType-meta.xml
<RecordType>
    <fullName>BRMX</fullName>
    <active>true</active>
    <description>Contratos de la sociedad BRASMAX</description>
    <label>BRMX</label>
</RecordType>

Salesforce/main/default/objects/Contrato__c/recordTypes/DSEM.recordType-meta.xml
<RecordType>
    <fullName>DSEM</fullName>
    <active>true</active>
    <description>Contratos de la sociedad Don Mario</description>
    <label>DSEM</label>
</RecordType>

Salesforce/main/default/objects/Item_del_Contrato__c/Item_del_Contrato__c.object-meta.xml
<CustomObject>
    <description>Item de CONTRATO DE LICENCIAMENTO PARA MULTIPLICAÇÃO E COMERCIALIZAÇÃO</description>
    <label>Item del Contrato</label>
    <nameField>
        <label>Nombre de Item del Contrato</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items del Contrato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Salesforce/main/default/objects/Item_del_Contrato__c/fields/Contrato_de_Multiplicacion__c.field-meta.xml
<CustomField>
    <fullName>Contrato_de_Multiplicacion__c</fullName>
    <description>Relación entre la cabecera del Contrato con los items(información de la variedad, precio, etc)</description>
    <inlineHelpText>Relación entre la cabecera del Contrato con los items(información de la variedad, precio, etc)</inlineHelpText>
    <label>Contrato de Multiplicação</label>
    <referenceTo>Contrato__c</referenceTo>
    <relationshipLabel>Items del Contrato</relationshipLabel>
    <relationshipName>Items_del_Contrato</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Salesforce/main/default/objects/Item_del_Contrato__c/fields/Cultivar__c.field-meta.xml
<CustomField>
    <fullName>Cultivar__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Cultivar por el/los que se confecciona el contrato</description>
    <inlineHelpText>Cultivar por el/los que se confecciona el contrato</inlineHelpText>
    <label>Cultivar</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Items del Contrato</relationshipLabel>
    <relationshipName>Items_del_Contrato</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/Item_del_Contrato__c/fields/Variedad__c.field-meta.xml
<CustomField>
    <fullName>Variedad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Variedade</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Marca__c</field>
            <operation>equals</operation>
            <valueField>Variedad__c.Sociedad__c</valueField>
        </filterItems>
        <filterItems>
            <field>Variedad__c.Ativa__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Variedad__c</referenceTo>
    <relationshipLabel>Items del Contrato</relationshipLabel>
    <relationshipName>Items_del_Contrato</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/Item_del_Contrato__c/fields/Variedade__c.field-meta.xml
<CustomField>
    <fullName>Variedade__c</fullName>
    <formula>Cultivar__r.Variedade__r.Name</formula>
    <label>Variedade do Cultivar</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/Order/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <label>Safra</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Safra</valueSetName>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Product2/fields/Categ__c.field-meta.xml
<CustomField>
    <fullName>Categ__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Categ</label>
    <referenceTo>Categoria__c</referenceTo>
    <relationshipLabel>Productos</relationshipLabel>
    <relationshipName>Productos</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/Product2/fields/Licenciada__c.field-meta.xml
<CustomField>
    <fullName>Licenciada__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Marca un producto como licenciado</description>
    <label>Licenciada</label>
    <type>Checkbox</type>
</CustomField>

Salesforce/main/default/main/default/objects/Product2/fields/Sociedad__c.field-meta.xml
<CustomField>
    <fullName>Sociedad__c</fullName>
    <label>Sociedad</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BRMX</fullName>
            </value>
            <value>
                <fullName>DSEM</fullName>
            </value>
            <value>
                <fullName>NEOG</fullName>
            </value>
            <value>
                <fullName>DAGMA</fullName>
            </value>
            <value>
                <fullName>LICENÇAS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Product2/fields/Tipo_de_Cota_o_Contrato__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Cota_o_Contrato__c</fullName>
    <description>Tipo de Cotação para o contrato de multiplicação</description>
    <inlineHelpText>Tipo de Cotação para o contrato de multiplicação</inlineHelpText>
    <label>Tipo de Cotação (Contrato)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SOJA</fullName>
            </value>
            <value>
                <fullName>DOLAR</fullName>
            </value>
            <value>
                <fullName>FATURAMENTO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Product2/fields/Variedad__c.field-meta.xml
<CustomField>
    <fullName>Variedad__c</fullName>
    <label>Variedad</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Licenciada__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>BMX APOLO RR</fullName>
            </value>
            <value>
                <fullName>BMX IMPACTO RR</fullName>
            </value>
            <value>
                <fullName>BMX MAGNA RR</fullName>
            </value>
            <value>
                <fullName>BMX POTÊNCIA RR</fullName>
            </value>
            <value>
                <fullName>BMX TITAN RR</fullName>
            </value>
            <value>
                <fullName>BMX FORÇA RR</fullName>
            </value>
            <value>
                <fullName>BMX ENERGIA RR</fullName>
            </value>
            <value>
                <fullName>BMX ATIVA RR</fullName>
            </value>
            <value>
                <fullName>BMX TURBO RR</fullName>
            </value>
            <value>
                <fullName>BMX VELOZ RR</fullName>
            </value>
            <value>
                <fullName>BMX ALVO RR</fullName>
            </value>
            <value>
                <fullName>BMX TORNADO RR</fullName>
            </value>
            <value>
                <fullName>BMX CLASSE RR</fullName>
            </value>
            <value>
                <fullName>BMX DESAFIO RR</fullName>
            </value>
            <value>
                <fullName>BMX RAÇA RR</fullName>
            </value>
            <value>
                <fullName>BMX PROGRESSO RR</fullName>
            </value>
            <value>
                <fullName>BRASMAX ELITE IPRO</fullName>
            </value>
            <value>
                <fullName>BRASMAX FLECHA IPRO</fullName>
            </value>
            <value>
                <fullName>BRASMAX BONUS IPRO</fullName>
            </value>
            <value>
                <fullName>BRASMAX BRAVA</fullName>
            </value>
            <value>
                <fullName>BRASMAX CLASSE</fullName>
            </value>
            <value>
                <fullName>BRASMAX PRISMA</fullName>
            </value>
            <value>
                <fullName>BRASMAX OPUS IPRO</fullName>
            </value>
            <value>
                <fullName>BRASMAX LANÇA IPRO</fullName>
            </value>
            <value>
                <fullName>BRASMAX GARRA IPRO</fullName>
            </value>
            <value>
                <fullName>BRASMAX ÍCONE IPRO</fullName>
            </value>
            <value>
                <fullName>BRASMAX POWER IPRO</fullName>
            </value>
            <value>
                <fullName>68I69RSF IPRO</fullName>
            </value>
            <value>
                <fullName>75I76RSF IPRO</fullName>
            </value>
            <value>
                <fullName>81I84RSF IPRO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Product2/fields/Variedade__c.field-meta.xml
<CustomField>
    <fullName>Variedade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Variedade</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Variedad__c.Licenciada__c</field>
            <operation>equals</operation>
            <valueField>$Source.Licenciada__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Variedad__c</referenceTo>
    <relationshipLabel>Productos</relationshipLabel>
    <relationshipName>Productos</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Variedad__c/Variedad__c.object-meta.xml
<CustomObject>
    <description>Variedades, disponibles para incluir en los Contratos de Multiplicación</description>
    <label>Variedad</label>
    <nameField>
        <label>Nome Comercial</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Variedades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/Variedad__c/fields/Comercializa_Paraguai__c.field-meta.xml
<CustomField>
    <fullName>Comercializa_Paraguai__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Comercializa Paraguai</label>
    <type>Checkbox</type>
</CustomField>

Salesforce/main/default/objects/Variedad__c/fields/Licenciada__c.field-meta.xml
<CustomField>
    <fullName>Licenciada__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Licenciada</label>
    <type>Checkbox</type>
</CustomField>

Salesforce/main/default/objects/Variedad__c/fields/Sociedad__c.field-meta.xml
<CustomField>
    <fullName>Sociedad__c</fullName>
    <formula>CASE(Marca_comercial__c,&quot;Brasmax&quot;,&quot;BRMX&quot;,&quot;DM Sementes&quot;,&quot;DSEM&quot;,&quot;Neogen&quot;,&quot;NEOG&quot;,&quot;&quot;)</formula>
    <label>Sociedad</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/globalValueSets/Safra.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>14/15</fullName>
    </customValue>
    <customValue>
        <fullName>15/16</fullName>
    </customValue>
    <customValue>
        <fullName>16/17</fullName>
    </customValue>
    <customValue>
        <fullName>17/18</fullName>
    </customValue>
    <customValue>
        <fullName>18/19</fullName>
    </customValue>
    <customValue>
        <fullName>19/20</fullName>
    </customValue>
    <customValue>
        <fullName>20/21</fullName>
    </customValue>
    <customValue>
        <fullName>21/22</fullName>
    </customValue>
    <customValue>
        <fullName>22/23</fullName>
    </customValue>
    <customValue>
        <fullName>23/24</fullName>
    </customValue>
    <customValue>
        <fullName>08/09</fullName>
        <isActive>false</isActive>
        <label>08/09</label>
    </customValue>
    <customValue>
        <fullName>07/08</fullName>
        <isActive>false</isActive>
        <label>07/08</label>
    </customValue>
    <customValue>
        <fullName>10/11</fullName>
        <isActive>false</isActive>
        <label>10/11</label>
    </customValue>
    <customValue>
        <fullName>11/12</fullName>
        <isActive>false</isActive>
        <label>11/12</label>
    </customValue>
    <customValue>
        <fullName>12/13</fullName>
        <isActive>false</isActive>
        <label>12/13</label>
    </customValue>
    <customValue>
        <fullName>13/14</fullName>
        <isActive>false</isActive>
        <label>13/14</label>
    </customValue>
    <customValue>
        <fullName>09/10</fullName>
        <isActive>false</isActive>
        <label>09/10</label>
    </customValue>
    <masterLabel>Safra</masterLabel>
</GlobalValueSet>

Salesforce/main/default/classes/itemsContratoMultController.cls
public class itemsContratoMultController {

    public List<Item_del_Contrato__c> items {get; set;}  
    public List<Item_del_Contrato__c> nuevoItem {get; set;}
    public String query {get;set;}
    private Id idContrato;
    private String nombreContrato;
    private String recTypeContrato;
    private String sociedadContrato;
    private String safraContrato;
    private String accContrato;
    private Boolean comParaguai;
    public String tipoCot;
    public String Mensaje;
    private Id editItem;
    private Id eliminarItem;
    private Id saveEditItem;
    
    private String nuevoBasica;
    private String editBasica;
    public Set<Id> basicaSel = New Set<Id>();
    private List<SelectOption> prodsBasica;
    
    public void setprodsBasica (List<SelectOption> i){
        prodsBasica = i;
    }
    
    public List<SelectOption> getprodsBasica (){
        return prodsBasica;
    } 
    
    public void seteditBasica (String i){
        editBasica = i;
    }
    
    public String geteditBasica (){
        return editBasica;
    }
    
    public void setnuevoBasica (String i){
        nuevoBasica = i;
    }
    
    public String getnuevoBasica (){
        return nuevoBasica;
    } 
    
    public void setsociedadContrato (String i){
        sociedadContrato = i;
    }
    
    public String getsociedadContrato (){
        return sociedadContrato;
    }  
    
    public void setnombreContrato (String i){
        nombreContrato = i;
    }
    
    public String getnombreContrato (){
        return nombreContrato;
    }
    
    public void setrecTypeContrato (String i){
        recTypeContrato = i;
    }
    
    public String getrecTypeContrato (){
        return recTypeContrato;
    }
    
    public void setsaveEditItem (Id i){
        saveEditItem = i;
    }
    
    public Id getsaveEditItem (){
        return saveEditItem;
    }
    
    public void setidContrato (Id i){
        idContrato = i;
    }
    
    public Id getidContrato (){
        return idContrato;
    } 
    
    public void seteditItem (Id i){
        editItem = i;
    }
    
    public Id geteditItem (){
        return editItem;
    } 
    
    public void seteliminarItem (Id i){
        eliminarItem = i;
    }
    
    public Id geteliminarItem (){
        return eliminarItem;
    } 
        Public String getMensaje() {
       return Mensaje;      
    }

    Public void setMensaje(String arg) {
       Mensaje=arg;      
    }         
    
    public List<SelectOption> getProductosBasica() {
        Set<String> contrat = New Set<String>();
        List<Product2> prods = New List<Product2>();
        
        for(Item_del_Contrato__c i: [SELECT Cultivar__r.Id FROM Item_del_Contrato__c WHERE Contrato_de_Multiplicacion__r.Sociedad__c =: sociedadContrato AND Contrato_de_Multiplicacion__r.Safra__c = :safraContrato AND Contrato_de_Multiplicacion__r.RecordType.Name = :sociedadContrato AND Contrato_de_Multiplicacion__r.Multiplicador__c =: accContrato]) 
            contrat.add(i.Cultivar__r.Id);
        
       List<SelectOption> lista = new List<SelectOption>();
       
       String qString = 'Select Id, Name, Variedad__c, Variedade__c, Variedade__r.Name From Product2 Where Categ__r.Name = \'BASICA\' And Variedade__c != null And isActive = true And Family = \'Royalty x Basica\' AND Tipo_de_Cota_o_Contrato__c = \'' + tipoCot + '\'';
       if(comParaguai){
        qString+='  AND Variedade__r.Comercializa_Paraguai__c = :comParaguai ';
       }
       if(Userinfo.getUserRoleId() == '00E40000001C6eWEAS'){
        qString+=' and licenciada__c = true ';
       }
       if(contrat.Size() > 0 && (recTypeContrato == 'Aditivo BRMX' || recTypeContrato == 'Aditivo DSEM' || recTypeContrato == 'Aditivo % DSEM' || recTypeContrato == 'Aditivo % BRMX')){
        qString+= ' and Id In :contrat ';
       }
       qString+= ' Order By Variedade__r.Name ';
        
        system.debug('qString:' +qString);
        query = qString;
        prods = database.query(qString);
       
        for (Product2 p : prods)                               
           lista.add(new SelectOption(p.Id,p.Variedade__r.Name));             
                                           
       return lista;
    }
        
    public void init(){
    
        
        tipoCot = 'SOJA';
        idContrato = ApexPages.currentPage().getParameters().get('id');
        nombreContrato = ApexPages.currentPage().getParameters().get('nombre');
        sociedadContrato = ApexPages.currentPage().getParameters().get('sociedad');
        Contrato__c c = [SELECT Id, RecordType.Name, Safra__c, Multiplicador__c, Tipo_de_Cota_o__c, Comercializa_Paraguai__c, Multiplicador__r.Region__r.Region_Comercial__c, Region_Comercial__c FROM Contrato__c WHERE Id =: idContrato];
        safraContrato = c.Safra__c;
        accContrato = c.Multiplicador__c;
        recTypeContrato = c.RecordType.Name;
        tipoCot = c.Tipo_de_Cota_o__c;
        comParaguai = c.Comercializa_Paraguai__c;
        c.Region_Comercial__c = c.Multiplicador__r.Region__r.Region_Comercial__c;
        update c;

        items = New List <Item_del_Contrato__c>();
        items = [Select Id, Precio__c, Cultivar__c, Tipo_de_Cotizacion__c, Variedade__c, Categoria__c, Quantidade__c, Porcentaje__c, Contrato_de_Multiplicacion__r.Safra__c, Contrato_de_Multiplicacion__r.Multiplicador__c, Incidencia_para_Votar__c From Item_del_Contrato__c Where Contrato_de_Multiplicacion__c = : idContrato];
            try{
        for(Item_del_Contrato__c it: items) basicaSel.add(it.Cultivar__c);
        nuevoitem = New List<Item_del_Contrato__c>();
        Item_del_Contrato__c i = New Item_del_Contrato__c();
        this.nuevoItem.add(i);

        }catch (Exception e){
            ApexPages.Message msg = new ApexPages.Message(ApexPages.Severity.INFO, e.getMessage()); 
            ApexPages.addMessage(msg);  
                                
        } 
                
    }
    
    public PageReference editarItem(){
        editItem = ApexPages.currentPage().getParameters().get('edit_item');
        
        if (editItem != null)
            for (Item_del_Contrato__c i : items)
                if (i.Id == editItem)   
                    editBasica = i.Cultivar__c;
        
        return null;    
    }
    
    public PageReference cancelEditarItem(){
        editItem = null;                
        saveEditItem = null;
        nuevobasica = null;
        editBasica = null;
        
        return null;    
    }
    
    public PageReference addItem(){
        
        try{
            //if((recTypeContrato == 'Aditivo BRMX' || recTypeContrato == 'Aditivo DSEM') && (this.nuevoItem[0].Categoria__c == null || this.nuevoItem[0].Quantidade__c == 0)){
            if((recTypeContrato == 'Aditivo BRMX' || recTypeContrato == 'Aditivo DSEM') && this.nuevoItem[0].Quantidade__c == 0){
                ApexPages.Message msg = new ApexPages.Message(ApexPages.Severity.INFO, 'Deve ingressar a quantidade'); 
                ApexPages.addMessage(msg);  
                return null;
            }
            this.nuevoItem[0].Contrato_de_Multiplicacion__c = idContrato;
            this.nuevoItem[0].Cultivar__c = nuevoBasica;
            Product2 p = [Select Id, Name From Product2 Where Id = : nuevoBasica];
            this.nuevoItem[0].Name = p.Name;
            insert nuevoItem;
        
            this.nuevoitem.clear();
            Item_del_Contrato__c i = New Item_del_Contrato__c();
            this.nuevoItem.add(i);
            
            editItem = null;
            saveEditItem = null;
            nuevobasica = null;
            editBasica = null;
        
            PageReference pr = new PageReference('/apex/Items_Contrato_Multiplicacion');
            pr.getParameters().put('id',idContrato);
            pr.getParameters().put('nombre',nombreContrato);
            return pr;
            
        }catch (Exception e){
            ApexPages.Message msg = new ApexPages.Message(ApexPages.Severity.INFO, e.getMessage()); 
            ApexPages.addMessage(msg);  
            return null;                    
        }                       
        
    }
    
    public PageReference eliminarItem(){        
        eliminarItem = ApexPages.currentPage().getParameters().get('eliminar_item');
        if (eliminarItem != null){
            Item_del_Contrato__c eliminar = [Select Id From Item_del_Contrato__c Where Id = : eliminarItem];
            delete eliminar;
        }    
        
        PageReference pr = new PageReference('/apex/Items_Contrato_Multiplicacion');
        pr.getParameters().put('id',idContrato);
        pr.getParameters().put('nombre',nombreContrato);
        return pr;
            
    }
    
    public PageReference saveEditItem(){        
        
        try{
        
            saveEditItem = ApexPages.currentPage().getParameters().get('save_edit_item');
            if (saveEditItem != null){
                for (Item_del_Contrato__c i : items){
                    if (i.Id == saveEditItem){
                        i.Cultivar__c = editBasica;
                        Product2 p = [Select Id, Name From Product2 Where Id = : editBasica];
                        i.Name = p.Name;   
                    }       
                }   
                update items;
            }       
                        
            editItem = null;
            saveEditItem = null;
            nuevobasica = null;
            editBasica = null;
            
            PageReference pr = new PageReference('/apex/Items_Contrato_Multiplicacion');
            pr.getParameters().put('id',idContrato);
            pr.getParameters().put('nombre',nombreContrato);
            return pr;
            
        }catch (Exception e){
            ApexPages.Message msg = new ApexPages.Message(ApexPages.Severity.INFO, e.getMessage()); 
            ApexPages.addMessage(msg);  
            return null;                    
        }    
    }
    
    public PageReference volver(){
    
        PageReference pr = new PageReference('/' + String.valueOf(idContrato));     
        return pr;  
        
    }

}