Salesforce/main/default/main/default/objects/Account/fields/Plano_de_Auditoria__c.field-meta.xml
<CustomField>
    <fullName>Plano_de_Auditoria__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plano de Auditoria</label>
    <referenceTo>Plano_de_Auditoria__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/Account/fields/Responsavel__c.field-meta.xml
<CustomField>
    <fullName>Responsavel__c</fullName>
    <description>Qual dos funcionários da Brasmax que estará responsável pela conta</description>
    <inlineHelpText>Qual dos funcionários da Brasmax que estará responsável pela conta</inlineHelpText>
    <label>Responsável BRMX</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>061 - Fernando Frehner</fullName>
            </value>
            <value>
                <fullName>066 - Marcelo Steffen</fullName>
            </value>
            <value>
                <fullName>067 - Sergio Bertagnolli</fullName>
            </value>
            <value>
                <fullName>076 - Tiago Goulart</fullName>
            </value>
            <value>
                <fullName>083 - Jorge Cristiano Rosa</fullName>
            </value>
            <value>
                <fullName>010 - Brasmax</fullName>
            </value>
            <value>
                <fullName>101 - Fausto Tadeu Fanchin</fullName>
            </value>
            <value>
                <fullName>104 - Otavio Gorni</fullName>
            </value>
            <value>
                <fullName>150 - João Serrano</fullName>
            </value>
            <value>
                <fullName>012 - Anderson Weissheimer</fullName>
            </value>
            <value>
                <fullName>197 - Wagner Rank</fullName>
            </value>
            <value>
                <fullName>198 - Bernardo Zanardo</fullName>
            </value>
            <value>
                <fullName>199 - Lucas Costa</fullName>
            </value>
            <value>
                <fullName>231 - Willian Von Scharten</fullName>
            </value>
            <value>
                <fullName>234 - Julio Cesar Poletto</fullName>
            </value>
            <value>
                <fullName>017 - Luis Fernando Cecatto</fullName>
            </value>
            <value>
                <fullName>018 - Flávio Marçal dos Santos</fullName>
            </value>
            <value>
                <fullName>312 - Lucas Hilario Fantineli</fullName>
            </value>
            <value>
                <fullName>019 - Felipe Oliveira Costa</fullName>
            </value>
            <value>
                <fullName>379 - Diego F. Gonçalves</fullName>
            </value>
            <value>
                <fullName>031 - Guilherme Sousa</fullName>
            </value>
            <value>
                <fullName>023 - Gabriel V. Finatto</fullName>
            </value>
            <value>
                <fullName>464 - Ana Laura Fernandes</fullName>
            </value>
            <value>
                <fullName>467 - Natalie de Mattos</fullName>
            </value>
            <value>
                <fullName>474 - Guilherme Menezes Salau</fullName>
            </value>
            <value>
                <fullName>403 - Felipe Bianchessi</fullName>
            </value>
            <value>
                <fullName>380 - Lucas de Souza Furlan</fullName>
            </value>
            <value>
                <fullName>037 - Felipe Dias Louzada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IMAGE( CASE( Status_Base__c , &quot;Verde&quot;, &quot;/img/samples/light_green.gif&quot;, &quot;Amarelo&quot;, &quot;/img/samples/light_yellow.gif&quot;, &quot;Vermelho&quot;, &quot;/img/samples/light_red.gif&quot;, &quot;/s.gif&quot;), &quot;Status da conta&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status BMX</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/Calendar_Event__c/Calendar_Event__c.object-meta.xml
<CustomObject>
    <label>Calendar Event</label>
    <nameField>
        <label>Event Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Calendar Event</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/Calendar_Event__c/fields/Auditor__c.field-meta.xml
<CustomField>
    <fullName>Auditor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Auditor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Calendar Event</relationshipLabel>
    <relationshipName>Calendar_Event</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Calendar_Event__c/fields/Cidade__c.field-meta.xml
<CustomField>
    <fullName>Cidade__c</fullName>
    <label>Cidade</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/Calendar_Event__c/fields/Etapa__c.field-meta.xml
<CustomField>
    <fullName>Etapa__c</fullName>
    <label>Etapa</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inventário físico</fullName>
            </value>
            <value>
                <fullName>Descarte</fullName>
            </value>
            <value>
                <fullName>Inventário de sobras</fullName>
            </value>
            <value>
                <fullName>Documental</fullName>
            </value>
            <value>
                <fullName>Eventual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Calendar_Event__c/fields/Plano_de_Auditoria__c.field-meta.xml
<CustomField>
    <fullName>Plano_de_Auditoria__c</fullName>
    <label>Plano de Auditoria</label>
    <referenceTo>Plano_de_Auditoria__c</referenceTo>
    <relationshipLabel>Visita</relationshipLabel>
    <relationshipName>Visita</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Salesforce/main/default/main/default/objects/Calendar_Event__c/fields/Responsavel__c.field-meta.xml
<CustomField>
    <fullName>Responsavel__c</fullName>
    <label>Responsável</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Próprio</fullName>
            </value>
            <value>
                <fullName>Terceiro</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Calendar_Event__c/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <label>Safra</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Safra</valueSetName>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Calendar_Event__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pendente</fullName>
                <default>true</default>
                <label>Pendente</label>
            </value>
            <value>
                <fullName>Concluída</fullName>
            </value>
            <value>
                <fullName>Cancelada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Calendar_Event__c/fields/UF__c.field-meta.xml
<CustomField>
    <fullName>UF__c</fullName>
    <label>UF</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/Cidade__c/Cidade__c.object-meta.xml
<CustomObject>
    <label>Ciudad</label>
    <nameField>
        <label>Nome da Cidade</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ciudades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/Plano_de_Auditoria__c/Plano_de_Auditoria__c.object-meta.xml
<CustomObject>
    <label>Plano de Auditoria</label>
    <nameField>
        <displayFormat>PA-{0000}</displayFormat>
        <label>Nombre de Plano de Auditoria</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Planos de Auditoria</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/Plano_de_Auditoria__c/fields/Cuenta_Principal__c.field-meta.xml
<CustomField>
    <fullName>Cuenta_Principal__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Cuenta Principal</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Plano de Auditoria</relationshipLabel>
    <relationshipName>Plano_de_Auditoria</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Plano_de_Auditoria__c/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <label>Safra</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Safra</valueSetName>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Plano_de_Auditoria__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Não Iniciado</fullName>
                <default>true</default>
                <label>Não Iniciado</label>
            </value>
            <value>
                <fullName>Em andamento</fullName>
            </value>
            <value>
                <fullName>Concluido</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
            <value>
                <fullName>Auditado</fullName>
                <isActive>false</isActive>
                <label>Auditado</label>
            </value>
            <value>
                <fullName>Pendente</fullName>
                <isActive>false</isActive>
                <label>Pendente</label>
            </value>
            <value>
                <fullName>Rejeitado</fullName>
                <isActive>false</isActive>
                <label>Rejeitado</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Producto_Auditado__c/Producto_Auditado__c.object-meta.xml
<CustomObject>
    <label>Producto Auditado</label>
    <nameField>
        <label>Nombre de Producto Auditado</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Productos Auditados</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/objects/Producto_Auditado__c/fields/Plano_de_Auditoria__c.field-meta.xml
<CustomField>
    <fullName>Plano_de_Auditoria__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plano de Auditoria</label>
    <referenceTo>Plano_de_Auditoria__c</referenceTo>
    <relationshipLabel>Productos Auditados</relationshipLabel>
    <relationshipName>Productos_Auditados</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/globalValueSets/Safra.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>14/15</fullName>
    </customValue>
    <customValue>
        <fullName>15/16</fullName>
    </customValue>
    <customValue>
        <fullName>16/17</fullName>
    </customValue>
    <customValue>
        <fullName>17/18</fullName>
    </customValue>
    <customValue>
        <fullName>18/19</fullName>
    </customValue>
    <customValue>
        <fullName>19/20</fullName>
    </customValue>
    <customValue>
        <fullName>20/21</fullName>
    </customValue>
    <customValue>
        <fullName>21/22</fullName>
    </customValue>
    <customValue>
        <fullName>22/23</fullName>
    </customValue>
    <customValue>
        <fullName>23/24</fullName>
    </customValue>
    <customValue>
        <fullName>08/09</fullName>
        <isActive>false</isActive>
        <label>08/09</label>
    </customValue>
    <customValue>
        <fullName>07/08</fullName>
        <isActive>false</isActive>
        <label>07/08</label>
    </customValue>
    <customValue>
        <fullName>10/11</fullName>
        <isActive>false</isActive>
        <label>10/11</label>
    </customValue>
    <customValue>
        <fullName>11/12</fullName>
        <isActive>false</isActive>
        <label>11/12</label>
    </customValue>
    <customValue>
        <fullName>12/13</fullName>
        <isActive>false</isActive>
        <label>12/13</label>
    </customValue>
    <customValue>
        <fullName>13/14</fullName>
        <isActive>false</isActive>
        <label>13/14</label>
    </customValue>
    <customValue>
        <fullName>09/10</fullName>
        <isActive>false</isActive>
        <label>09/10</label>
    </customValue>
    <masterLabel>Safra</masterLabel>
</GlobalValueSet>

Salesforce/main/default/classes/AuditManagementControllerTest.cls
@isTest
private class AuditManagementControllerTest {

    @TestSetup static void setup() {
        Profile profileSupervisor = [SELECT Id FROM Profile WHERE Name = 'Comercial LE' LIMIT 1];
        Profile profileGerente = [SELECT Id FROM Profile WHERE Name = 'Gerente LE' LIMIT 1];

        User supervisor = Build.anUser()
            .withFirstName('Rosa')
            .withLastName('Jorge Cristiano')
            .withAlias('jcr')
            .withEmail('jorge.rosa@asdf.com')
            .withUsername('jorge.rosa@asdf.com')
            .withProfileId(profileSupervisor)
            .withCommunityNickname('jcr')
            .build();

        User gerente = Build.anUser()
            .withFirstName('Sergio Vieira')
            .withLastName('Bertagnolli')
            .withAlias('svb')
            .withEmail('sergio.bertagnolli@asdf.com')
            .withUsername('sergio.bertagnolli@asdf.com')
            .withProfileId(profileGerente)
            .withCommunityNickname('svb')
            .build();

        User[] users = new User[]{supervisor, gerente};
        insert users;

        Account[] accounts = new Account[2];

        accounts[0] = Build.anAccount()
            .withName('ACME INDUSTRY SRL')
            .withNomefantasia('ACME')
            .withType('Multiplicador')
            .withMultiplicador(true)
            .withAuditor(false)
            .withSupervisor(supervisor)
            .withGerenteComercial(gerente)
            .build();

        accounts[1] = Build.anAccount()
            .withName('RAPHAEL DE MATOS OLIVEIRA')
            .withMultiplicador(false)
            .withAuditor(true)
            .build();

        insert accounts;

        Plano_de_Auditoria__c plano = new Plano_de_Auditoria__c(
            Cuenta_Principal__c = accounts[0].Id,
            Safra__c = '18/19;19/20;20/21',
            Status__c = 'Não Iniciado'
        );

        insert plano;

        Calendar_Event__c[] visitas = new Calendar_Event__c[2];

        visitas[0] = new Calendar_event__c(
            Name = 'Visita sorpresa 1',
            Plano_de_Auditoria__c = plano.Id,
            Auditor__c = accounts[1].Id,
            Cidade__c = 'São Paulo',
            UF__c = 'SP',
            Etapa__c = 'Documental',
            Responsavel__c = 'Próprio',
            Start_Time__c = System.Today(),
            End_Time__c = System.today().addDays(1),
            Safra__c = '18/19;19/20'
        );

        visitas[1] = new Calendar_event__c(
            Name = 'Visita sorpresa 2',
            Plano_de_Auditoria__c = plano.Id,
            Auditor__c = accounts[1].Id,
            Cidade__c = 'São Vicente',
            UF__c = 'SP',
            Etapa__c = 'Eventual',
            Responsavel__c = 'Próprio',
            Start_Time__c = System.Today().addDays(2),
            End_Time__c = System.today().addDays(3),
            Safra__c = '20/21'
        );

        insert visitas;

		Producto_Auditado__c[] productos = new Producto_Auditado__c[3];

        productos[0] = new Producto_Auditado__c(Plano_de_Auditoria__c = plano.Id);
        productos[1] = new Producto_Auditado__c(Plano_de_Auditoria__c = plano.Id);
        productos[2] = new Producto_Auditado__c(Plano_de_Auditoria__c = plano.Id);

        insert productos;
    }

    @isTest static void getAuditorsTest() {
        Account account = null;
        List<Map<String, String>> auditors = null;

        Test.startTest();
        account = [SELECT Id, Name FROM Account WHERE Name = 'RAPHAEL DE MATOS OLIVEIRA' LIMIT 1];
        auditors = AuditManagementController.getAuditors();
        Test.stopTest();

        System.assert(!auditors.isEmpty(), 'La lista no contiene valores');

        Map<String, String> auditor = auditors[1];

        System.assert(auditor.containsKey('value'), 'El Object no contiene el campo value');
        System.assertEquals(account.Id, auditor.get('value'), 'El value no es el esperado');
        System.assert(auditor.containsKey('label'), 'El Object no contiene el campo label');
        System.assertEquals(account.Name, auditor.get('label'), 'El label no es el esperado');
    }

    @isTest static void getAuditPlansTest() {
        Plano_de_Auditoria__c plan = null;
        Map<Id, Plano_de_Auditoria__c> plans = null;

        Test.startTest();
        plan = [SELECT Id, Name FROM Plano_de_Auditoria__c LIMIT 1];
        plans = AuditManagementController.getAuditPlans();
        Test.stopTest();

        System.assert(!plans.isEmpty(), 'El mapa no contiene valores');
        System.assert(plans.containsKey(plan.Id), 'El mapa no contiene el plano insertado en la DB');
        System.assertEquals(plan.Name, plans.get(plan.Id).Name, 'El nombre del plano no coincide con el esperado');
    }

    @isTest static void getEventsTest() {
        List<Calendar_Event__c> events = null;

        Test.startTest();
        events = AuditManagementController.getEvents(
            new Map<String, List<String>>{
                'Cidade__c' => new String[]{'São Paulo'}, 'UF__c' => new String[]{'SP'}
            }
        );
        Test.stopTest();

        System.assertEquals(1, events.size(), 'La cantidad de registros retornados no coincide con la esperada');
        System.assertEquals('Visita sorpresa 1', events[0].Name, 'El evento retornado no es el esperado');
    }

    @isTest static void getFiltersTest() {
        Map<String, List<Map<String, String>>> filters = null;

        Test.startTest();
        filters = AuditManagementController.getFilters();
        Test.stopTest();

        Set<String> keys = new Set<String>{'Cidade__c','UF__c', 'Etapa__c', 'Responsavel__c'};

        for (String key : filters.keySet()) {
            System.assert(keys.contains(key), 'El mapa de filtros no posee la categoría ' + key);
        }

        List<Map<String, String>> auxList = new List<Map<String, String>>{
            new Map<String, String>{'value' => 'São Paulo', 'label' => 'São Paulo'},
            new Map<String, String>{'value' => 'São Vicente', 'label' => 'São Vicente'}
        };

        System.assert(auxList.equals(filters.get('Cidade__c')), 'La lista de filtros Cidade__c no es la esperada');

        auxList = new List<Map<String, String>>{new Map<String, String>{'value' => 'SP', 'label' => 'SP'}};

        System.assert(auxList.equals(filters.get('UF__c')), 'La lista de filtros UF__c no es la esperada');

        auxList = new List<Map<String, String>>{
            new Map<String, String>{'value' => 'Documental', 'label' => 'Documental'},
            new Map<String, String>{'value' => 'Eventual', 'label' => 'Eventual'}
        };

        System.assert(auxList.equals(filters.get('Etapa__c')), 'La lista de filtros Etapa__c no es la esperada');

        auxList = new List<Map<String, String>>{new Map<String, String>{'value' => 'Próprio', 'label' => 'Próprio'}};

        System.assert(auxList.equals(filters.get('Responsavel__c')), 'La lista de filtros Responsavel__c no es la esperada');
    }
}