Salesforce/main/default/main/default/objects/Account/fields/Plano_de_Auditoria__c.field-meta.xml
<CustomField>
    <fullName>Plano_de_Auditoria__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plano de Auditoria</label>
    <referenceTo>Plano_de_Auditoria__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Plano_de_Auditoria__c/Plano_de_Auditoria__c.object-meta.xml
<CustomObject>
    <label>Plano de Auditoria</label>
    <nameField>
        <displayFormat>PA-{0000}</displayFormat>
        <label>Nombre de Plano de Auditoria</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Planos de Auditoria</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/Plano_de_Auditoria__c/fields/Cuenta_Principal__c.field-meta.xml
<CustomField>
    <fullName>Cuenta_Principal__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Cuenta Principal</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Plano de Auditoria</relationshipLabel>
    <relationshipName>Plano_de_Auditoria</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/classes/PlanoDeAuditoriaTriggerHelper.cls
public class PlanoDeAuditoriaTriggerHelper {

    public static void relatedCuentaPrincipalwithPlano(List<Plano_de_Auditoria__c> planos) {
        List<Id> accs = new List<Id>();

        for (Plano_de_Auditoria__c plano : planos) {
            accs.add(plano.Cuenta_Principal__c);
        }

        List<Account> accounts = [SELECT Id, Name, Plano_de_Auditoria__c FROM Account WHERE Id IN :accs];

        for (Plano_de_Auditoria__c plano: planos) {
            for (Account acc : accounts) {
                if (plano.Cuenta_Principal__c == acc.Id) {
                    acc.Plano_de_Auditoria__c = plano.Id;
                }
            }
        }

        update accounts;
    }
}