Salesforce/main/default/main/default/objects/Account/fields/Plano_de_Auditoria__c.field-meta.xml
<CustomField>
    <fullName>Plano_de_Auditoria__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plano de Auditoria</label>
    <referenceTo>Plano_de_Auditoria__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IMAGE( CASE( Status_Base__c , &quot;Verde&quot;, &quot;/img/samples/light_green.gif&quot;, &quot;Amarelo&quot;, &quot;/img/samples/light_yellow.gif&quot;, &quot;Vermelho&quot;, &quot;/img/samples/light_red.gif&quot;, &quot;/s.gif&quot;), &quot;Status da conta&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status BMX</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/Account/recordTypes/Cuenta.recordType-meta.xml
<RecordType>
    <fullName>Cuenta</fullName>
    <active>true</active>
    <label>Cuenta</label>
</RecordType>

Salesforce/main/default/main/default/objects/Plano_de_Auditoria__c/Plano_de_Auditoria__c.object-meta.xml
<CustomObject>
    <label>Plano de Auditoria</label>
    <nameField>
        <displayFormat>PA-{0000}</displayFormat>
        <label>Nombre de Plano de Auditoria</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Planos de Auditoria</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/Plano_de_Auditoria__c/fields/Cuenta_Principal__c.field-meta.xml
<CustomField>
    <fullName>Cuenta_Principal__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Cuenta Principal</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Plano de Auditoria</relationshipLabel>
    <relationshipName>Plano_de_Auditoria</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Plano_de_Auditoria__c/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <label>Safra</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Safra</valueSetName>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Plano_de_Auditoria__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Não Iniciado</fullName>
                <default>true</default>
                <label>Não Iniciado</label>
            </value>
            <value>
                <fullName>Em andamento</fullName>
            </value>
            <value>
                <fullName>Concluido</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
            <value>
                <fullName>Auditado</fullName>
                <isActive>false</isActive>
                <label>Auditado</label>
            </value>
            <value>
                <fullName>Pendente</fullName>
                <isActive>false</isActive>
                <label>Pendente</label>
            </value>
            <value>
                <fullName>Rejeitado</fullName>
                <isActive>false</isActive>
                <label>Rejeitado</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/globalValueSets/Safra.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>14/15</fullName>
    </customValue>
    <customValue>
        <fullName>15/16</fullName>
    </customValue>
    <customValue>
        <fullName>16/17</fullName>
    </customValue>
    <customValue>
        <fullName>17/18</fullName>
    </customValue>
    <customValue>
        <fullName>18/19</fullName>
    </customValue>
    <customValue>
        <fullName>19/20</fullName>
    </customValue>
    <customValue>
        <fullName>20/21</fullName>
    </customValue>
    <customValue>
        <fullName>21/22</fullName>
    </customValue>
    <customValue>
        <fullName>22/23</fullName>
    </customValue>
    <customValue>
        <fullName>23/24</fullName>
    </customValue>
    <customValue>
        <fullName>08/09</fullName>
        <isActive>false</isActive>
        <label>08/09</label>
    </customValue>
    <customValue>
        <fullName>07/08</fullName>
        <isActive>false</isActive>
        <label>07/08</label>
    </customValue>
    <customValue>
        <fullName>10/11</fullName>
        <isActive>false</isActive>
        <label>10/11</label>
    </customValue>
    <customValue>
        <fullName>11/12</fullName>
        <isActive>false</isActive>
        <label>11/12</label>
    </customValue>
    <customValue>
        <fullName>12/13</fullName>
        <isActive>false</isActive>
        <label>12/13</label>
    </customValue>
    <customValue>
        <fullName>13/14</fullName>
        <isActive>false</isActive>
        <label>13/14</label>
    </customValue>
    <customValue>
        <fullName>09/10</fullName>
        <isActive>false</isActive>
        <label>09/10</label>
    </customValue>
    <masterLabel>Safra</masterLabel>
</GlobalValueSet>

Salesforce/main/default/classes/PlanoDeAuditoriaTriggerTest.cls
@isTest
private class PlanoDeAuditoriaTriggerTest {

    @TestSetup static void setup() {
        Profile profileSupervisor = [SELECT Id FROM Profile WHERE Name = 'Comercial LE' LIMIT 1];
        Profile profileGerente = [SELECT Id FROM Profile WHERE Name = 'Gerente LE' LIMIT 1];

        User supervisor = Build.anUser()
            .withFirstName('Rosa')
            .withLastName('Jorge Cristiano')
            .withAlias('jcr')
            .withEmail('jorge.rosa@asdf.com')
            .withUsername('jorge.rosa@asdf.com')
            .withProfileId(profileSupervisor)
            .withCommunityNickname('jcr')
            .build();

        User gerente = Build.anUser()
            .withFirstName('Sergio Vieira')
            .withLastName('Bertagnolli')
            .withAlias('svb')
            .withEmail('sergio.bertagnolli@asdf.com')
            .withUsername('sergio.bertagnolli@asdf.com')
            .withProfileId(profileGerente)
            .withCommunityNickname('svb')
            .build();

        User[] users = new User[]{supervisor, gerente};
        insert users;

        List<Account> accList = new List<Account>();

        for (Integer i = 0; i < 5; i++) {
            accList.add(Build.anAccount()
                .withName('Test Account ' + i)
                .withNomefantasia('Test Account ' + i)
                .withType('Multiplicador')
                .withMultiplicador(true)
                .withMarca('BRMX')
                .withSupervisor(supervisor)
                .withGerenteComercial(gerente)
                .build()
            );
        }

        insert accList;
    }

    @isTest static void siUnaCuentaTienePlanoPendiente_NodebePermitirInsertarElNuevoPlano() {
        List<Account> accList = [SELECT Id, Name FROM Account];
        List<Plano_de_Auditoria__c> auditPlanList = new List<Plano_de_Auditoria__c>();

        Plano_de_Auditoria__c planoOld = new Plano_de_Auditoria__c(
            Cuenta_Principal__c = accList[0].Id,
            safra__c = '19/20',
            status__c = 'Não Iniciado'
        );

        insert(planoOld);

        Plano_de_Auditoria__c planoNew = new Plano_de_Auditoria__c(
            Cuenta_Principal__c = accList[0].Id,
            safra__c = '19/20',
            status__c = 'Não Iniciado'
        );

        auditPlanList.add(planoNew);
    
        Test.startTest();
        Database.SaveResult[] sr = Database.Insert(auditPlanList, false);
        Test.stopTest();

        System.assertEquals(false, sr[0].isSuccess(),'Não deve haver plano de auditoria em estado pendente com a mesma safra selecionada como conta principal.');
    }

    @isTest static void siSeinsertaUnPlanoDebeRelacionarseEsePlanoConLaCuenta() {
        List<Account> accList = [SELECT Id, Name, Plano_de_Auditoria__c FROM Account];
        List<Plano_de_Auditoria__c> auditPlanList = new List<Plano_de_Auditoria__c>();

        Plano_de_Auditoria__c planoOld = new Plano_de_Auditoria__c (
            Cuenta_Principal__c = accList[0].Id, 
            safra__c = '19/20',
            status__c = 'Concluido'
        );

        insert(planoOld);

        Plano_de_Auditoria__c planoNew = new Plano_de_Auditoria__c (
            Cuenta_Principal__c = accList[0].Id, 
            safra__c = '19/20',
            status__c = 'Não Iniciado'
        );
    
        Test.startTest();
        insert(planoNew);
        Test.stopTest();

        List<Account> accListAControlar = [SELECT Id, Name, Plano_de_Auditoria__c FROM Account];
        System.assertEquals(planoNew.Id, accListAControlar[0].Plano_de_Auditoria__c,'No Se ha relacionado la cuenta con el plano Insertado');
    }
}