Salesforce/main/default/main/default/objects/Account/fields/Region_Comercial__c.field-meta.xml
<CustomField>
    <fullName>Region_Comercial__c</fullName>
    <formula>TEXT(Region__r.Region_Comercial__c)</formula>
    <label>Região Comercial</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/Case/fields/Variedade__c.field-meta.xml
<CustomField>
    <fullName>Variedade__c</fullName>
    <formula>Cultivar__r.Variedade__r.Name</formula>
    <label>Variedade</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/Categoria__c/Categoria__c.object-meta.xml
<CustomObject>
    <description>Categorías</description>
    <label>Categoria</label>
    <nameField>
        <label>Nombre de Categoría</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categorias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/objects/Categoria__c/fields/Mostrar_en_portal__c.field-meta.xml
<CustomField>
    <fullName>Mostrar_en_portal__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Mostrar en portal</label>
    <type>Checkbox</type>
</CustomField>

Salesforce/main/default/objects/Configuracion_BMX__c/Configuracion_BMX__c.object-meta.xml
<CustomObject>
    <description>Indicador de Parametros.</description>
    <label>Configuracion_BMX</label>
    <nameField>
        <label>Configuracion Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuraciones_BMX</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/Configuracion_BMX__c/fields/CRM_Safra_Actual__c.field-meta.xml
<CustomField>
    <fullName>CRM_Safra_Actual__c</fullName>
    <description>Indica la campaña actual con la que está trabajando CRM</description>
    <label>CRM_Safra_Actual</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/Configuracion_BMX__c/fields/PV_Safra_Actual__c.field-meta.xml
<CustomField>
    <fullName>PV_Safra_Actual__c</fullName>
    <description>Campo para indicar la Safra Actual en el Portal de Votación</description>
    <label>PV Safra Actual</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/Configuracion_BMX__c/fields/Votaci_n_fecha_hasta__c.field-meta.xml
<CustomField>
    <fullName>Votaci_n_fecha_hasta__c</fullName>
    <description>Fecha de cierre de la votación(según la vuelta, en Votacion Nro de Vuelta</description>
    <inlineHelpText>Fecha de cierre de la votación(según la vuelta, en Votacion Nro de Vuelta</inlineHelpText>
    <label>Votación Sul fecha hasta</label>
    <type>Date</type>
</CustomField>

Salesforce/main/default/main/default/objects/Configuracion_BMX__c/fields/Votacion_nro_de_vuelta__c.field-meta.xml
<CustomField>
    <fullName>Votacion_nro_de_vuelta__c</fullName>
    <description>Para la aplicación de votación</description>
    <inlineHelpText>Para a segunda rodada, as variedades, valores e região devem ser carregados no objeto &quot;Votaçao Balotagem&quot;.</inlineHelpText>
    <label>Votacion Sul Nro de vuelta</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/main/default/objects/Contrato__c/Contrato__c.object-meta.xml
<CustomObject>
    <description>CONTRATO DE LICENCIAMENTO PARA MULTIPLICAÇÃO E COMERCIALIZAÇÃO</description>
    <label>Contrato de Multiplicação</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Numero do Contrato de Multiplicação</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contratos de Multiplicação</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Salesforce/main/default/objects/Contrato__c/fields/Region_Comercial__c.field-meta.xml
<CustomField>
    <fullName>Region_Comercial__c</fullName>
    <label>Região Comercial</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>REGION 1</fullName>
            </value>
            <value>
                <fullName>REGION 2</fullName>
            </value>
            <value>
                <fullName>CERRADO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Contrato__c/recordTypes/DSEM.recordType-meta.xml
<RecordType>
    <fullName>DSEM</fullName>
    <active>true</active>
    <description>Contratos de la sociedad Don Mario</description>
    <label>DSEM</label>
</RecordType>

Salesforce/main/default/main/default/objects/Contrato__c/recordTypes/Termo_Aditivo.recordType-meta.xml
<RecordType>
    <fullName>Termo_Aditivo</fullName>
    <active>true</active>
    <description>Termo Aditivos de Contrato de multiplicação - a partir de 2018</description>
    <label>Termo Aditivo Comerciais</label>
</RecordType>

Salesforce/main/default/objects/Item_del_Contrato__c/Item_del_Contrato__c.object-meta.xml
<CustomObject>
    <description>Item de CONTRATO DE LICENCIAMENTO PARA MULTIPLICAÇÃO E COMERCIALIZAÇÃO</description>
    <label>Item del Contrato</label>
    <nameField>
        <label>Nombre de Item del Contrato</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items del Contrato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/Item_del_Contrato__c/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Indica la categoría del ítem</description>
    <label>Categoria</label>
    <referenceTo>Categoria__c</referenceTo>
    <relationshipLabel>Items del Contrato</relationshipLabel>
    <relationshipName>Items_del_Contrato</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/Item_del_Contrato__c/fields/Variedad__c.field-meta.xml
<CustomField>
    <fullName>Variedad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Variedade</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Marca__c</field>
            <operation>equals</operation>
            <valueField>Variedad__c.Sociedad__c</valueField>
        </filterItems>
        <filterItems>
            <field>Variedad__c.Ativa__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Variedad__c</referenceTo>
    <relationshipLabel>Items del Contrato</relationshipLabel>
    <relationshipName>Items_del_Contrato</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/Item_del_Contrato__c/fields/Variedade__c.field-meta.xml
<CustomField>
    <fullName>Variedade__c</fullName>
    <formula>Cultivar__r.Variedade__r.Name</formula>
    <label>Variedade do Cultivar</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/Item_del_Contrato__c/recordTypes/Volumen.recordType-meta.xml
<RecordType>
    <fullName>Volumen</fullName>
    <active>true</active>
    <label>Volumen</label>
</RecordType>

Salesforce/main/default/main/default/objects/Product2/fields/Categ__c.field-meta.xml
<CustomField>
    <fullName>Categ__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Categ</label>
    <referenceTo>Categoria__c</referenceTo>
    <relationshipLabel>Productos</relationshipLabel>
    <relationshipName>Productos</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Product2/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <label>Categoria</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BREEDER</fullName>
            </value>
            <value>
                <fullName>FUNDADORA</fullName>
            </value>
            <value>
                <fullName>Genetica</fullName>
            </value>
            <value>
                <fullName>Pre Basica</fullName>
            </value>
            <value>
                <fullName>BASICA</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>C1</fullName>
            </value>
            <value>
                <fullName>C2</fullName>
            </value>
            <value>
                <fullName>R</fullName>
            </value>
            <value>
                <fullName>S1</fullName>
            </value>
            <value>
                <fullName>S2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Product2/fields/Variedad__c.field-meta.xml
<CustomField>
    <fullName>Variedad__c</fullName>
    <label>Variedad</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Licenciada__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>BMX APOLO RR</fullName>
            </value>
            <value>
                <fullName>BMX IMPACTO RR</fullName>
            </value>
            <value>
                <fullName>BMX MAGNA RR</fullName>
            </value>
            <value>
                <fullName>BMX POTÊNCIA RR</fullName>
            </value>
            <value>
                <fullName>BMX TITAN RR</fullName>
            </value>
            <value>
                <fullName>BMX FORÇA RR</fullName>
            </value>
            <value>
                <fullName>BMX ENERGIA RR</fullName>
            </value>
            <value>
                <fullName>BMX ATIVA RR</fullName>
            </value>
            <value>
                <fullName>BMX TURBO RR</fullName>
            </value>
            <value>
                <fullName>BMX VELOZ RR</fullName>
            </value>
            <value>
                <fullName>BMX ALVO RR</fullName>
            </value>
            <value>
                <fullName>BMX TORNADO RR</fullName>
            </value>
            <value>
                <fullName>BMX CLASSE RR</fullName>
            </value>
            <value>
                <fullName>BMX DESAFIO RR</fullName>
            </value>
            <value>
                <fullName>BMX RAÇA RR</fullName>
            </value>
            <value>
                <fullName>BMX PROGRESSO RR</fullName>
            </value>
            <value>
                <fullName>BRASMAX ELITE IPRO</fullName>
            </value>
            <value>
                <fullName>BRASMAX FLECHA IPRO</fullName>
            </value>
            <value>
                <fullName>BRASMAX BONUS IPRO</fullName>
            </value>
            <value>
                <fullName>BRASMAX BRAVA</fullName>
            </value>
            <value>
                <fullName>BRASMAX CLASSE</fullName>
            </value>
            <value>
                <fullName>BRASMAX PRISMA</fullName>
            </value>
            <value>
                <fullName>BRASMAX OPUS IPRO</fullName>
            </value>
            <value>
                <fullName>BRASMAX LANÇA IPRO</fullName>
            </value>
            <value>
                <fullName>BRASMAX GARRA IPRO</fullName>
            </value>
            <value>
                <fullName>BRASMAX ÍCONE IPRO</fullName>
            </value>
            <value>
                <fullName>BRASMAX POWER IPRO</fullName>
            </value>
            <value>
                <fullName>68I69RSF IPRO</fullName>
            </value>
            <value>
                <fullName>75I76RSF IPRO</fullName>
            </value>
            <value>
                <fullName>81I84RSF IPRO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Product2/fields/Variedade__c.field-meta.xml
<CustomField>
    <fullName>Variedade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Variedade</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Variedad__c.Licenciada__c</field>
            <operation>equals</operation>
            <valueField>$Source.Licenciada__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Variedad__c</referenceTo>
    <relationshipLabel>Productos</relationshipLabel>
    <relationshipName>Productos</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Regiao__c/Regiao__c.object-meta.xml
<CustomObject>
    <label>Región</label>
    <nameField>
        <label>Nome da Região</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regiones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/objects/Regiao__c/fields/Region_Comercial__c.field-meta.xml
<CustomField>
    <fullName>Region_Comercial__c</fullName>
    <label>Region Comercial</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>REGION 1</fullName>
            </value>
            <value>
                <fullName>REGION 2</fullName>
            </value>
            <value>
                <fullName>CERRADO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Votacion_balotage__c/Votacion_balotage__c.object-meta.xml
<CustomObject>
    <description>Tabla auxiliar para la segunda vuelta de votación. Con los 2 valores máximos para el caso en que participe de la segunda vuelta.</description>
    <label>Votacion_balotage</label>
    <nameField>
        <label>Votacion_balotage</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Valores de votacion</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/Votacion_balotage__c/fields/Region_Comercial__c.field-meta.xml
<CustomField>
    <fullName>Region_Comercial__c</fullName>
    <label>Region Comercial</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SUL</fullName>
            </value>
            <value>
                <fullName>CERRADO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Votacion_balotage__c/fields/Variedad__c.field-meta.xml
<CustomField>
    <fullName>Variedad__c</fullName>
    <label>Variedad</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/Votacion_balotage__c/fields/Vuelta__c.field-meta.xml
<CustomField>
    <fullName>Vuelta__c</fullName>
    <description>indica si está disponible para votar(que vuelta)  o está cerrado.</description>
    <inlineHelpText>indica si está disponible para votar(que vuelta)  o está cerrado.</inlineHelpText>
    <label>Vuelta</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>cerrado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/classes/ProductsVotacionAPITest.cls
@isTest
public class ProductsVotacionAPITest {

    final static String TESTMARCA = 'DSEM';
    final static String TESTSAFRA = '20/21';
    final static String TESTACCTNAME = 'Test Account';
    final static String EMPTYACCTNAME = 'Empty Account';

    /**
     *  METHOD:         makeData 
     *  DESCRIPTION:    Test Setup for Class. Created for US #13225 
     *  AUTHOR:         irina.benitez@cloudgaia.com (4-nov-21)
     * 
     *  UPDATE:         pablo.fraquia@cloudgaia.com (12-jan-22)
     *  DESCRIPTION:    Configuracion_BMX__c and Votacion_balotage__c added for show products when vuelta == 2. Updated for US #19251
     *                  parameter marca removed
     **/ 

    @TestSetup
    static void makeData(){

        test.startTest();

        // Insert Configuracion_BMX__c
        Configuracion_BMX__c testConfiguracionBMX = new Configuracion_BMX__c(Name = 'TestFacturación',
                                                                             CRM_Safra_Actual__c = TESTSAFRA,
                                                                             Votacion_nro_de_vuelta__c = 1,
                                                                             Votaci_n_fecha_hasta__c = System.today(),
                                                                             PV_Safra_Actual__c = TESTSAFRA
                                                                             );

        insert testConfiguracionBMX;
        
        // Insert Categoria__c
        Categoria__c categoria = new Categoria__c(Name = 'BASICA', Mostrar_en_portal__c = true);
        insert categoria;

        // Insert Variedad__c records
        List<Variedad__c> variedadList = new List<Variedad__c>();
        variedadList.add( new Variedad__c(Name = 'Variedad 1 Test', Ativa__c = true) );
        variedadList.add( new Variedad__c(Name = 'Variedad 2 Test', Ativa__c = true) );
        insert variedadList;

        // Insert Product2 records
        List<Product2> productList = new List<Product2>();
        productList.add( new Product2(Name = 'Product 1 Test', IsActive = true, Categ__c = categoria.Id, Family = 'Royalty x Basica', Variedade__c = variedadList[0].Id) );
        productList.add( new Product2(Name = 'Product 2 Test', IsActive = true, Categ__c = categoria.Id, Family = 'Royalty x Basica', Variedade__c = variedadList[1].Id) );
        insert productList;

        // Insert Standard Pricebook prices
        Id stdPriceBookId = Test.getStandardPricebookId();
        List<PricebookEntry> stdPrices = new List<PricebookEntry>();
        stdPrices.add( new PricebookEntry(Pricebook2Id = stdPriceBookId, Product2Id = productList[0].Id, UnitPrice = 10) );
        stdPrices.add( new PricebookEntry(Pricebook2Id = stdPriceBookId, Product2Id = productList[1].Id, UnitPrice = 20) );
        insert stdPrices;

        // Insert Pricebook
        Pricebook2 pbRecord = new Pricebook2(Name = 'Pricebook Test', IsActive = true);
        insert pbRecord;

        // Insert Pricebook Entries with Product2.Categ__c.Name = 'BASICA' && Product2.Family = 'Royalty x Basica'
        List<PricebookEntry> pbEntries = new List<PricebookEntry>();
        pbEntries.add( new PricebookEntry(Pricebook2Id = pbRecord.Id, Product2Id = productList[0].Id, UnitPrice = 10, IsActive = true) );
        pbEntries.add( new PricebookEntry(Pricebook2Id = pbRecord.Id, Product2Id = productList[1].Id, UnitPrice = 20, IsActive = true) );
        insert pbEntries;

        // Insert Account
        Regiao__c testRegion = new Regiao__c(Name = 'REGION 1', Region_Comercial__c = 'REGION 1');
        insert testRegion;

        List<Account> accList = new List<Account>();
        accList.Add(new Account(Name = TESTACCTNAME, Region__c = testRegion.Id));
        accList.Add(new Account(Name = EMPTYACCTNAME, Region__c = testRegion.Id));
        insert accList;

        // Insert Contrato__c
        Id contractRecordType =  Schema.SObjectType.Contrato__c.getRecordTypeInfosByDeveloperName().get('Termo_Aditivo').getRecordTypeId();
        Contrato__c contratoMultip = new Contrato__c(   Multiplicador__c = accList[0].Id,
                                                        Sociedad__c = TESTMARCA, 
                                                        Safra__c = TESTSAFRA, 
                                                        RecordTypeId = contractRecordType, 
                                                        Chegou_na_Brasmax__c = true, 
                                                        Estado__c = 'Chegou' );
        insert contratoMultip;

        // Insert Item_del_Contrato__c
        Id contractItemRecordType =  Schema.SObjectType.Item_del_Contrato__c.getRecordTypeInfosByName().get('Volumen').getRecordTypeId();
        List<Item_del_Contrato__c> contractItemList = new List<Item_del_Contrato__c>();
        contractItemList.add( new Item_del_Contrato__c( RecordTypeId = contractItemRecordType, Contrato_de_Multiplicacion__c = contratoMultip.Id, Cultivar__c = productList[0].Id) );
        contractItemList.add( new Item_del_Contrato__c( RecordTypeId = contractItemRecordType, Contrato_de_Multiplicacion__c = contratoMultip.Id, Cultivar__c = productList[1].Id) );
        insert contractItemList;

        test.stopTest();    
    }        

    /**
     *  METHOD:         getProductsVotacionTestPositive 
     *  DESCRIPTION:    Test class for ProductsVotacionAPI.getProductsVotacion. Created for US #13225 
     *  AUTHOR:         irina.benitez@cloudgaia.com (4-nov-21)
     *  TEST CASE:      call method with valid accountId, marca and safra ==> success, returns products and maps
     * 
     *  UPDATE:         pablo.fraquia@cloudgaia.com (12-jan-22)
     *  DESCRIPTION:    parameter marca removed
     **/ 

    @isTest
    public static void getProductsVotacionTestPositive() {

        String accountId = [SELECT Id FROM Account WHERE Name = :TESTACCTNAME LIMIT 1].Id;

        ProductsVotacionAPI.Response result;

        RestRequest req = new RestRequest(); 
        req.requestURI = '/services/apexrest/ProductsVotacionAPI/';  
        req.addParameter('accountId', accountId);
        req.addParameter('safra', TESTSAFRA);
        req.httpMethod = 'GET';

        RestResponse resp = new RestResponse();
        RestContext.request = req;
        RestContext.response = resp;

        test.startTest();
        ProductsVotacionAPI.getProductsVotacion();
        test.stopTest();

        result = (ProductsVotacionAPI.Response)JSON.deserialize(resp.responseBody.toString(), ProductsVotacionAPI.Response.class);
        System.debug('result: ' + result);
        
        System.assert(result.status);
        System.assertEquals(Label.ProductsVotacionAPI_Success_Message, result.message);
        System.assertEquals(2, result.productsVotacion.size());

    }

    /**
     *  METHOD:         getProductsVotacionTestNegative
     *  DESCRIPTION:    Test class for ProductsVotacionAPI.getProductsVotacion. Created for US #13225 
     *  AUTHOR:         irina.benitez@cloudgaia.com (4-nov-21)
     *  TEST CASE:      call method with invalid accountId  ==> returns error message with failed data
     * 
     *  UPDATE:         pablo.fraquia@cloudgaia.com (12-jan-22)
     *  DESCRIPTION:    parameter marca removed
     **/ 

    @isTest
    public static void getProductsVotacionTestNegative() {

        String emptyAccId = [SELECT Id FROM Account WHERE Name = :EMPTYACCTNAME LIMIT 1].Id;

        ProductsVotacionAPI.Response result;

        RestRequest req = new RestRequest(); 
        req.requestURI = '/services/apexrest/ProductsVotacionAPI/';  
        req.addParameter('accountId', emptyAccId);
        req.addParameter('safra', TESTSAFRA);
        req.httpMethod = 'GET';

        RestResponse resp = new RestResponse();
        RestContext.request = req;
        RestContext.response = resp;

        test.startTest();
        ProductsVotacionAPI.getProductsVotacion();
        test.stopTest();

        result = (ProductsVotacionAPI.Response)JSON.deserialize(resp.responseBody.toString(), ProductsVotacionAPI.Response.class);
        System.debug('result: ' + result);
        
        System.assertEquals(false, result.status);
        System.assertEquals(404, resp.statusCode);
    }

    /**
     *  METHOD:         getProductsVotacionBalotageTestPositive
     *  DESCRIPTION:    Test class for ProductsVotacionAPI.getProductsVotacion. Created for US #19251
     *  AUTHOR:         pablo.fraquia@cloudgaia.com (12-jan-22)
     *  TEST CASE:      call method to show prodcuts available for second round (Balotage)  ==> returns success message, products and maps
     **/ 

    @isTest
    public static void getProductsVotacionBalotageTestPositive() {

        String accountId = [SELECT Id FROM Account WHERE Name = :TESTACCTNAME LIMIT 1].Id;

        List<Product2> testProductList = [SELECT Id FROM Product2 WHERE Name IN ('Product 1 Test','Product 2 Test') LIMIT 2];

        List<Votacion_balotage__c> productsForBalotage = new List<Votacion_balotage__c>();

        productsForBalotage.add(new Votacion_balotage__c(Name = 'Product 1', 
                                                         Producto__c = testProductList[0].Id, 
                                                         Variedad__c = 'Product 1', 
                                                         Variable__c = 'precio', 
                                                         valor1__c = 20, 
                                                         valor2__c = 10, 
                                                         Vuelta__c = '2',
                                                         Region_Comercial__c = 'SUL'));

        productsForBalotage.add(new Votacion_balotage__c(Name = 'Product 2', 
                                                         Producto__c = testProductList[1].Id, 
                                                         Variedad__c = 'Product 2', 
                                                         Variable__c = 'precio', 
                                                         valor1__c = 35, 
                                                         valor2__c = 15, 
                                                         Vuelta__c = '2',
                                                         Region_Comercial__c = 'SUL'));                                                 

        insert productsForBalotage;

        Configuracion_BMX__c testConfig = [SELECT Id, CRM_Safra_Actual__c, Votacion_nro_de_vuelta__c, Votaci_n_fecha_hasta__c, PV_Safra_Actual__c 
                                                     FROM Configuracion_BMX__c
                                                     WHERE Name = 'TestFacturación'
                                                     LIMIT 1];

        testConfig.Votacion_nro_de_vuelta__c = 2;
        testConfig.Votaci_n_fecha_hasta__c = System.today();
        
        update testConfig;

        ProductsVotacionAPI.Response result;

        RestRequest req = new RestRequest(); 
        req.requestURI = '/services/apexrest/ProductsVotacionAPI/';  
        req.addParameter('accountId', accountId);
        req.addParameter('safra', TESTSAFRA);
        req.httpMethod = 'GET';

        RestResponse resp = new RestResponse();
        RestContext.request = req;
        RestContext.response = resp;

        test.startTest();
        ProductsVotacionAPI.getProductsVotacion();
        test.stopTest();

        result = (ProductsVotacionAPI.Response)JSON.deserialize(resp.responseBody.toString(), ProductsVotacionAPI.Response.class);
        System.debug('result: ' + result);
        
        System.assert(result.status);
        System.assertEquals(Label.ProductsVotacionAPI_Success_Message, result.message);
        System.assertEquals(2, result.productsVotacionBalotage.size());
    }
}