Salesforce/main/default/objects/Analitica_DemandaVsVenta__c/Analitica_DemandaVsVenta__c.object-meta.xml
<CustomObject>
    <description>Creado por Jere para programar instantaneas analiticas de Ventas contra demanda.</description>
    <label>Analitica_DemandaVsVenta</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Nombre de Analitica_DemandaVsVenta</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Analiticas_DemandaVsVenta</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/Analitica_DemandaVsVenta__c/fields/ProductName__c.field-meta.xml
<CustomField>
    <fullName>ProductName__c</fullName>
    <label>ProductName</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/Analitica_DemandaVsVenta__c/fields/Producto__c.field-meta.xml
<CustomField>
    <fullName>Producto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Producto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Analiticas_DemandaVsVenta</relationshipLabel>
    <relationshipName>Analiticas_DemandaVsVenta</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/classes/ScheduActualizarIADemanda.cls
global class ScheduActualizarIADemanda implements Schedulable {
	
	//Global execute, este método es ejecutado en la fecha y horario configurado para tal trabajo	
	global void execute(SchedulableContext ctx){		
        actualizarIA();
	}		
	
	@future(callout=true)
	public static void actualizarIA(){
		List<Product2> prods = [Select Id, Name From Product2 where isActive = true];
		Map<String, Product2> mapProds = New Map <String, Product2>();
		for(Product2 p : prods){
			mapProds.put(p.Name,p);		
		}
		
		List<Analitica_DemandaVsVenta__c> ias = [Select Id, ProductName__c from Analitica_DemandaVsVenta__c where ProductName__c != null and Producto__c = null];
		for(Analitica_DemandaVsVenta__c i_a : ias)
		{
			Product2 p = mapProds.get(i_a.ProductName__c);
			if(p != null)
				i_a.Producto__c = p.Id;	
		}
		update ias;
	}

}