Salesforce/main/default/objects/Analitica_DemandaVsVenta__c/Analitica_DemandaVsVenta__c.object-meta.xml
<CustomObject>
    <description>Creado por Jere para programar instantaneas analiticas de Ventas contra demanda.</description>
    <label>Analitica_DemandaVsVenta</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Nombre de Analitica_DemandaVsVenta</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Analiticas_DemandaVsVenta</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/Analitica_DemandaVsVenta__c/fields/ProductName__c.field-meta.xml
<CustomField>
    <fullName>ProductName__c</fullName>
    <label>ProductName</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/classes/ScheduActualizarIATest.cls
@isTest
private class ScheduActualizarIATest {

   	static testmethod void test(){
		
		Product2 p = new Product2(Name='PROD',isActive=true); insert p;
		Analitica_DemandaVsVenta__c a = new Analitica_DemandaVsVenta__c(ProductName__c='PROD');
		insert a;
		
		Test.startTest();
		ScheduActualizarIADemanda act = new ScheduActualizarIADemanda();		
		String sche = '0 0 23 * * ?';
		System.schedule('Update', sche, act);
		Test.stopTest();
		
	}
	
}