Salesforce/main/default/objects/Bitacora_NC__c/Bitacora_NC__c.object-meta.xml
<CustomObject>
    <description>Tendrá información del estado que surge de cada actualización diaria de las notas de crédito obtenidas directamente de SAP. Aquí se podrá analizar que ocurro en cada caso.</description>
    <label>Bitacora_NC</label>
    <nameField>
        <label>Nombre de Bitacora_NC</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bitacora_NCs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/objects/Bitacora_NC__c/fields/Fecha_Desde__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Desde__c</fullName>
    <label>Fecha Desde</label>
    <type>Date</type>
</CustomField>

Salesforce/main/default/objects/Bitacora_NC__c/fields/fkart__c.field-meta.xml
<CustomField>
    <fullName>fkart__c</fullName>
    <label>fkart</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/Bitacora_NC__c/fields/Iniciar_AcItems__c.field-meta.xml
<CustomField>
    <fullName>Iniciar_AcItems__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Iniciar AcItems</label>
    <type>Checkbox</type>
</CustomField>

Salesforce/main/default/main/default/objects/Bitacora_NC__c/fields/numero_lote__c.field-meta.xml
<CustomField>
    <fullName>numero_lote__c</fullName>
    <label>numero_lote</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/main/default/objects/Bitacora_NC__c/fields/Orden__c.field-meta.xml
<CustomField>
    <fullName>Orden__c</fullName>
    <label>Orden</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/main/default/objects/Bitacora_NC__c/fields/sociedad__c.field-meta.xml
<CustomField>
    <fullName>sociedad__c</fullName>
    <label>sociedad</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/Bitacora_NC__c/fields/vbtyp__c.field-meta.xml
<CustomField>
    <fullName>vbtyp__c</fullName>
    <label>vbtyp</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/Configuracion_BMX__c/Configuracion_BMX__c.object-meta.xml
<CustomObject>
    <description>Indicador de Parametros.</description>
    <label>Configuracion_BMX</label>
    <nameField>
        <label>Configuracion Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuraciones_BMX</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/Configuracion_BMX__c/fields/FC_Mandante_SAP__c.field-meta.xml
<CustomField>
    <fullName>FC_Mandante_SAP__c</fullName>
    <label>FC Mandante SAP</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/Flujo_Doc_tmp__c/Flujo_Doc_tmp__c.object-meta.xml
<CustomObject>
    <label>Flujo_Doc_tmp</label>
    <nameField>
        <label>Nombre de Flujo_Doc_tmp</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flujos_Doc_tmp</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/Flujo_Doc_tmp__c/fields/FKART__c.field-meta.xml
<CustomField>
    <fullName>FKART__c</fullName>
    <label>FKART</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/Flujo_Doc_tmp__c/fields/FKIMG__c.field-meta.xml
<CustomField>
    <fullName>FKIMG__c</fullName>
    <label>FKIMG</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/main/default/objects/Flujo_Doc_tmp__c/fields/NETWR__c.field-meta.xml
<CustomField>
    <fullName>NETWR__c</fullName>
    <label>NETWR</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/main/default/objects/Flujo_Doc_tmp__c/fields/NUMERO_LOTE__c.field-meta.xml
<CustomField>
    <fullName>NUMERO_LOTE__c</fullName>
    <label>NUMERO_LOTE</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/main/default/objects/Flujo_Doc_tmp__c/fields/VBTYP__c.field-meta.xml
<CustomField>
    <fullName>VBTYP__c</fullName>
    <label>VBTYP</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/Flujo_Doc_tmp__c/fields/ZZPOSSF__c.field-meta.xml
<CustomField>
    <fullName>ZZPOSSF__c</fullName>
    <label>ZZPOSSF</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/Opportunity/fields/Estado_Facturacion__c.field-meta.xml
<CustomField>
    <fullName>Estado_Facturacion__c</fullName>
    <label>Estado Facturacion</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>PE Contabilizar</fullName>
            </value>
            <value>
                <fullName>Contabilizada</fullName>
            </value>
            <value>
                <fullName>Impresa</fullName>
            </value>
            <value>
                <fullName>Anulada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Opportunity/fields/Sociedad__c.field-meta.xml
<CustomField>
    <fullName>Sociedad__c</fullName>
    <label>Sociedad</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/OpportunityLineItem/fields/Bls_devolucion__c.field-meta.xml
<CustomField>
    <fullName>Bls_devolucion__c</fullName>
    <label>Bls devolucion</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/main/default/objects/OpportunityLineItem/fields/Estado_Facturacion__c.field-meta.xml
<CustomField>
    <fullName>Estado_Facturacion__c</fullName>
    <label>Estado Facturacion</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Facturado</fullName>
            </value>
            <value>
                <fullName>No facturado</fullName>
                <default>true</default>
                <label>No facturado</label>
            </value>
            <value>
                <fullName>Pasado Pedido</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/OpportunityLineItem/fields/Orden__c.field-meta.xml
<CustomField>
    <fullName>Orden__c</fullName>
    <label>Orden</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/objects/OpportunityLineItem/fields/Variedad__c.field-meta.xml
<CustomField>
    <fullName>Variedad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Variedades que pueden incluirse en el contrato de multiplicacion</description>
    <inlineHelpText>Variedades que pueden incluirse en el contrato de multiplicacion</inlineHelpText>
    <label>Variedad</label>
    <referenceTo>Variedad__c</referenceTo>
    <relationshipLabel>Producto de oportunidad</relationshipLabel>
    <relationshipName>Producto_de_oportunidad</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/OpportunityLineItem/fields/ZZPOSSF__c.field-meta.xml
<CustomField>
    <fullName>ZZPOSSF__c</fullName>
    <label>_ZZPOSSF</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/Product2/fields/Sociedad__c.field-meta.xml
<CustomField>
    <fullName>Sociedad__c</fullName>
    <label>Sociedad</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BRMX</fullName>
            </value>
            <value>
                <fullName>DSEM</fullName>
            </value>
            <value>
                <fullName>NEOG</fullName>
            </value>
            <value>
                <fullName>DAGMA</fullName>
            </value>
            <value>
                <fullName>LICENÇAS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Product2/fields/Variedad__c.field-meta.xml
<CustomField>
    <fullName>Variedad__c</fullName>
    <label>Variedad</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Licenciada__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>BMX APOLO RR</fullName>
            </value>
            <value>
                <fullName>BMX IMPACTO RR</fullName>
            </value>
            <value>
                <fullName>BMX MAGNA RR</fullName>
            </value>
            <value>
                <fullName>BMX POTÊNCIA RR</fullName>
            </value>
            <value>
                <fullName>BMX TITAN RR</fullName>
            </value>
            <value>
                <fullName>BMX FORÇA RR</fullName>
            </value>
            <value>
                <fullName>BMX ENERGIA RR</fullName>
            </value>
            <value>
                <fullName>BMX ATIVA RR</fullName>
            </value>
            <value>
                <fullName>BMX TURBO RR</fullName>
            </value>
            <value>
                <fullName>BMX VELOZ RR</fullName>
            </value>
            <value>
                <fullName>BMX ALVO RR</fullName>
            </value>
            <value>
                <fullName>BMX TORNADO RR</fullName>
            </value>
            <value>
                <fullName>BMX CLASSE RR</fullName>
            </value>
            <value>
                <fullName>BMX DESAFIO RR</fullName>
            </value>
            <value>
                <fullName>BMX RAÇA RR</fullName>
            </value>
            <value>
                <fullName>BMX PROGRESSO RR</fullName>
            </value>
            <value>
                <fullName>BRASMAX ELITE IPRO</fullName>
            </value>
            <value>
                <fullName>BRASMAX FLECHA IPRO</fullName>
            </value>
            <value>
                <fullName>BRASMAX BONUS IPRO</fullName>
            </value>
            <value>
                <fullName>BRASMAX BRAVA</fullName>
            </value>
            <value>
                <fullName>BRASMAX CLASSE</fullName>
            </value>
            <value>
                <fullName>BRASMAX PRISMA</fullName>
            </value>
            <value>
                <fullName>BRASMAX OPUS IPRO</fullName>
            </value>
            <value>
                <fullName>BRASMAX LANÇA IPRO</fullName>
            </value>
            <value>
                <fullName>BRASMAX GARRA IPRO</fullName>
            </value>
            <value>
                <fullName>BRASMAX ÍCONE IPRO</fullName>
            </value>
            <value>
                <fullName>BRASMAX POWER IPRO</fullName>
            </value>
            <value>
                <fullName>68I69RSF IPRO</fullName>
            </value>
            <value>
                <fullName>75I76RSF IPRO</fullName>
            </value>
            <value>
                <fullName>81I84RSF IPRO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Variedad__c/Variedad__c.object-meta.xml
<CustomObject>
    <description>Variedades, disponibles para incluir en los Contratos de Multiplicación</description>
    <label>Variedad</label>
    <nameField>
        <label>Nome Comercial</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Variedades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/objects/Variedad__c/fields/Sociedad__c.field-meta.xml
<CustomField>
    <fullName>Sociedad__c</fullName>
    <formula>CASE(Marca_comercial__c,&quot;Brasmax&quot;,&quot;BRMX&quot;,&quot;DM Sementes&quot;,&quot;DSEM&quot;,&quot;Neogen&quot;,&quot;NEOG&quot;,&quot;&quot;)</formula>
    <label>Sociedad</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/classes/TEST_sapFlujoDoc_caller.cls
@isTest
private class TEST_sapFlujoDoc_caller {
	

	@isTest(SeeAllData=false)
	static void test_procesos() {
	
		Configuracion_BMX__c c = new Configuracion_BMX__c (FC_Mandante_SAP__c = '110', Name = 'Facturacion');insert c;
		Bitacora_NC__c b1 = new Bitacora_NC__c(vbtyp__c='S',fkart__c='S2',Fecha_Desde__c= system.today().addDays(-200), numero_lote__c=1, sociedad__c='BRMX',orden__c=1);
        Bitacora_NC__c b2 = new Bitacora_NC__c(vbtyp__c='O',fkart__c='ZBDF',Fecha_Desde__c=system.today().addDays(-200), numero_lote__c=1, sociedad__c='BRMX',orden__c=2);
        Bitacora_NC__c b3 = new Bitacora_NC__c(vbtyp__c='O',fkart__c='ZBDG',Fecha_Desde__c=system.today().addDays(-200), numero_lote__c=1, sociedad__c='BRMX',orden__c=3);
        Bitacora_NC__c b4 = new Bitacora_NC__c(vbtyp__c='O',fkart__c='ZBDP',Fecha_Desde__c=system.today().addDays(-200), numero_lote__c=1, sociedad__c='BRMX',orden__c=4);
        Bitacora_NC__c b5 = new Bitacora_NC__c(vbtyp__c='O',fkart__c='ZBDR',Fecha_Desde__c=system.today().addDays(-200), numero_lote__c=1, sociedad__c='BRMX',orden__c=5);
        Bitacora_NC__c b6 = new Bitacora_NC__c(vbtyp__c='O',fkart__c='ZBDS',Fecha_Desde__c=system.today().addDays(-200), numero_lote__c=1, sociedad__c='BRMX',orden__c=6);
        Bitacora_NC__c b7 = new Bitacora_NC__c(vbtyp__c='O',fkart__c='ZBDE',Fecha_Desde__c=system.today().addDays(-200), numero_lote__c=1, sociedad__c='BRMX',orden__c=7,Iniciar_AcItems__c=true);
        
        List<Bitacora_NC__c> regBitacora = new List<Bitacora_NC__c>();
        regBitacora.add(b1);
        regBitacora.add(b2);
        regBitacora.add(b3);
        regBitacora.add(b4);
        regBitacora.add(b5);
        regBitacora.add(b6);
        regBitacora.add(b7);
        insert regbitacora;
        sapFlujoDoc_caller.consultarFlujoDoc();
	}
	

	@isTest(SeeAllData=false)
	static void test_actItems_O_ZBDE_BRMX() {
		Product2 prod = new Product2(Name='Producto',Sociedad__c='BRMX',Variedad__c='BRMX ALVO'); insert prod;
                
        Pricebook2 pb = new Pricebook2(Name='local'); insert pb;
        PricebookEntry pbe_st = new PricebookEntry(Product2Id=prod.Id,UnitPrice=2,Pricebook2Id=Test.getStandardPricebookId(),isActive=true); insert pbe_st;
        PricebookEntry pbe = new PricebookEntry(Product2Id=prod.Id,UnitPrice=2,Pricebook2Id=pb.Id,isActive=true); insert pbe;
		Opportunity opp = new Opportunity(Name='OppTest',Stagename='Aprobada',CloseDate=System.today()); insert opp;
        OpportunityLineItem oItem = new OpportunityLineItem(Estado_facturacion__c='PE',OpportunityId=opp.Id,Quantity=100,PricebookEntryId=pbe.id, TotalPrice=1000,Bls_devolucion__c=0);insert oItem;
		
		Flujo_Doc_tmp__c doc = new Flujo_Doc_tmp__c();
		doc.FKIMG__c = decimal.valueOf(1);
		doc.NETWR__c = decimal.valueOf(1);
		doc.VBTYP__c = 'O';
		doc.FKART__c = 'ZBDE';
		doc.ZZPOSSF__c = oItem.id;
		insert doc;
		String arg_vbtyp = 'O';
		String arg_fkart = 'ZBDE';
		String sociedad = 'BRMX';
		//sapFlujoDoc_caller.actItems(arg_vbtyp,arg_fkart,sociedad);

		doc = new Flujo_Doc_tmp__c();
		doc.FKIMG__c = decimal.valueOf(1);
		doc.NETWR__c = decimal.valueOf(1);
		doc.VBTYP__c = 'O';
		doc.FKART__c = 'ZBDF';
		doc.ZZPOSSF__c =  oItem.id;
		insert doc;
		arg_fkart = 'ZBDF';
		sociedad = 'BRMX';
		arg_vbtyp = 'O';
		//sapFlujoDoc_caller.actItems(arg_vbtyp,arg_fkart,sociedad);
		
		doc = new Flujo_Doc_tmp__c();
		doc.FKIMG__c = decimal.valueOf(1);
		doc.NETWR__c = decimal.valueOf(1);
		doc.VBTYP__c = 'O';
		doc.FKART__c = 'ZBDG';
		doc.ZZPOSSF__c = oItem.id;
		insert doc;
		arg_vbtyp = 'O';
		arg_fkart = 'ZBDG';
		sociedad = 'BRMX';
		//sapFlujoDoc_caller.actItems(arg_vbtyp,arg_fkart,sociedad);
		
		doc = new Flujo_Doc_tmp__c();
		doc.FKIMG__c = decimal.valueOf(1);
		doc.NETWR__c = decimal.valueOf(1);
		doc.VBTYP__c = 'O';
		doc.FKART__c = 'ZBDP';
		doc.ZZPOSSF__c = oItem.id;
		insert doc;
		arg_vbtyp = 'O';
		arg_fkart = 'ZBDP';
		sociedad = 'BRMX';
		//sapFlujoDoc_caller.actItems(arg_vbtyp,arg_fkart,sociedad);
		
		doc = new Flujo_Doc_tmp__c();
		doc.FKIMG__c = decimal.valueOf(1);
		doc.NETWR__c = decimal.valueOf(1);
		doc.VBTYP__c = 'O';
		doc.FKART__c = 'ZBDR';
		doc.ZZPOSSF__c = oItem.id;
		insert doc;
		arg_vbtyp = 'O';
		arg_fkart = 'ZBDR';
		sociedad = 'BRMX';
		//sapFlujoDoc_caller.actItems(arg_vbtyp,arg_fkart,sociedad);
		
		doc = new Flujo_Doc_tmp__c();
		doc.FKIMG__c = decimal.valueOf(1);
		doc.NETWR__c = decimal.valueOf(1);
		doc.VBTYP__c = 'O';
		doc.FKART__c = 'ZBDS';
		doc.ZZPOSSF__c = oItem.id;
		insert doc;
		arg_vbtyp = 'O';
		arg_fkart = 'ZBDS';
		sociedad = 'BRMX';
		sapFlujoDoc_caller.actItems();
		
		
	}
	
// ANULACIONES
	@isTest(seeAllData=false)
	static void test_actItems_ANULACIONES() {
		Product2 prod = new Product2(Name='Producto',Sociedad__c='BRMX',Variedad__c='BRMX ALVO'); insert prod;
                
        Pricebook2 pb = new Pricebook2(Name='local'); insert pb;
        PricebookEntry pbe_st = new PricebookEntry(Product2Id=prod.Id,UnitPrice=2,Pricebook2Id=Test.getStandardPricebookId(),isActive=true); insert pbe_st;
        PricebookEntry pbe = new PricebookEntry(Product2Id=prod.Id,UnitPrice=2,Pricebook2Id=pb.Id,isActive=true); insert pbe;
		Opportunity opp = new Opportunity(Name='OppTest',Stagename='Aprobada',CloseDate=System.today()); insert opp;
        OpportunityLineItem oItem = new OpportunityLineItem(Estado_facturacion__c='PE',PricebookEntryId=pbe.id,OpportunityId=opp.Id,Quantity=100,TotalPrice=1000,Bls_devolucion__c=0);insert oItem;
		Flujo_Doc_tmp__c doc = new Flujo_Doc_tmp__c();
		doc.FKIMG__c = decimal.valueOf(1);
		doc.NETWR__c = decimal.valueOf(1);
		String arg_vbtyp = 'S';
		String arg_fkart = 'S2';
		doc.VBTYP__c = 'S';
		doc.FKART__c = 'S2';
		doc.ZZPOSSF__c = oItem.id;
		insert doc;
		String sociedad = 'BRMX';
		sapFlujoDoc_caller.actItems();

	}


}