Salesforce/main/default/main/default/objects/Case/fields/Variedade__c.field-meta.xml
<CustomField>
    <fullName>Variedade__c</fullName>
    <formula>Cultivar__r.Variedade__r.Name</formula>
    <label>Variedade</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/Categoria__c/Categoria__c.object-meta.xml
<CustomObject>
    <description>Categorías</description>
    <label>Categoria</label>
    <nameField>
        <label>Nombre de Categoría</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categorias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/Product2/fields/Categ__c.field-meta.xml
<CustomField>
    <fullName>Categ__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Categ</label>
    <referenceTo>Categoria__c</referenceTo>
    <relationshipLabel>Productos</relationshipLabel>
    <relationshipName>Productos</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Product2/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <label>Categoria</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BREEDER</fullName>
            </value>
            <value>
                <fullName>FUNDADORA</fullName>
            </value>
            <value>
                <fullName>Genetica</fullName>
            </value>
            <value>
                <fullName>Pre Basica</fullName>
            </value>
            <value>
                <fullName>BASICA</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>C1</fullName>
            </value>
            <value>
                <fullName>C2</fullName>
            </value>
            <value>
                <fullName>R</fullName>
            </value>
            <value>
                <fullName>S1</fullName>
            </value>
            <value>
                <fullName>S2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Product2/fields/Obtentor__c.field-meta.xml
<CustomField>
    <fullName>Obtentor__c</fullName>
    <description>Lista de Obtentores que debemos mantener(admin)</description>
    <inlineHelpText>Lista de Obtentores que debemos mantener(admin)</inlineHelpText>
    <label>Obtentor</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ADVANTA</fullName>
            </value>
            <value>
                <fullName>Agrária</fullName>
            </value>
            <value>
                <fullName>Agroeste</fullName>
            </value>
            <value>
                <fullName>AGROMEN</fullName>
            </value>
            <value>
                <fullName>Agro Norte</fullName>
            </value>
            <value>
                <fullName>Avanti Seeds</fullName>
            </value>
            <value>
                <fullName>Basf</fullName>
            </value>
            <value>
                <fullName>Bayer</fullName>
            </value>
            <value>
                <fullName>Brasmax</fullName>
            </value>
            <value>
                <fullName>BREVANT</fullName>
            </value>
            <value>
                <fullName>Br Genetica</fullName>
            </value>
            <value>
                <fullName>CARAIBA</fullName>
            </value>
            <value>
                <fullName>CCGL Tecnología</fullName>
            </value>
            <value>
                <fullName>Coodetec</fullName>
            </value>
            <value>
                <fullName>CORDIUS</fullName>
            </value>
            <value>
                <fullName>CPTA</fullName>
            </value>
            <value>
                <fullName>Credenz</fullName>
            </value>
            <value>
                <fullName>CTP</fullName>
            </value>
            <value>
                <fullName>CTPA/Emgopa</fullName>
            </value>
            <value>
                <fullName>DM Licenças</fullName>
            </value>
            <value>
                <fullName>Don Mario</fullName>
            </value>
            <value>
                <fullName>Dow</fullName>
            </value>
            <value>
                <fullName>Embrapa</fullName>
            </value>
            <value>
                <fullName>FMT</fullName>
            </value>
            <value>
                <fullName>FPS</fullName>
            </value>
            <value>
                <fullName>FT</fullName>
            </value>
            <value>
                <fullName>Fundacep</fullName>
            </value>
            <value>
                <fullName>GDML</fullName>
            </value>
            <value>
                <fullName>Genetica Soy</fullName>
            </value>
            <value>
                <fullName>Geneze</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Product2/fields/Portal__c.field-meta.xml
<CustomField>
    <fullName>Portal__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indica si el producto está habilitado/deshabilitado para ser devuelto en las APIs creadas para el nuevo Portal. Creado para US #13082</description>
    <label>Portal</label>
    <type>Checkbox</type>
</CustomField>

Salesforce/main/default/objects/Product2/fields/Variedad__c.field-meta.xml
<CustomField>
    <fullName>Variedad__c</fullName>
    <label>Variedad</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Licenciada__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>BMX APOLO RR</fullName>
            </value>
            <value>
                <fullName>BMX IMPACTO RR</fullName>
            </value>
            <value>
                <fullName>BMX MAGNA RR</fullName>
            </value>
            <value>
                <fullName>BMX POTÊNCIA RR</fullName>
            </value>
            <value>
                <fullName>BMX TITAN RR</fullName>
            </value>
            <value>
                <fullName>BMX FORÇA RR</fullName>
            </value>
            <value>
                <fullName>BMX ENERGIA RR</fullName>
            </value>
            <value>
                <fullName>BMX ATIVA RR</fullName>
            </value>
            <value>
                <fullName>BMX TURBO RR</fullName>
            </value>
            <value>
                <fullName>BMX VELOZ RR</fullName>
            </value>
            <value>
                <fullName>BMX ALVO RR</fullName>
            </value>
            <value>
                <fullName>BMX TORNADO RR</fullName>
            </value>
            <value>
                <fullName>BMX CLASSE RR</fullName>
            </value>
            <value>
                <fullName>BMX DESAFIO RR</fullName>
            </value>
            <value>
                <fullName>BMX RAÇA RR</fullName>
            </value>
            <value>
                <fullName>BMX PROGRESSO RR</fullName>
            </value>
            <value>
                <fullName>BRASMAX ELITE IPRO</fullName>
            </value>
            <value>
                <fullName>BRASMAX FLECHA IPRO</fullName>
            </value>
            <value>
                <fullName>BRASMAX BONUS IPRO</fullName>
            </value>
            <value>
                <fullName>BRASMAX BRAVA</fullName>
            </value>
            <value>
                <fullName>BRASMAX CLASSE</fullName>
            </value>
            <value>
                <fullName>BRASMAX PRISMA</fullName>
            </value>
            <value>
                <fullName>BRASMAX OPUS IPRO</fullName>
            </value>
            <value>
                <fullName>BRASMAX LANÇA IPRO</fullName>
            </value>
            <value>
                <fullName>BRASMAX GARRA IPRO</fullName>
            </value>
            <value>
                <fullName>BRASMAX ÍCONE IPRO</fullName>
            </value>
            <value>
                <fullName>BRASMAX POWER IPRO</fullName>
            </value>
            <value>
                <fullName>68I69RSF IPRO</fullName>
            </value>
            <value>
                <fullName>75I76RSF IPRO</fullName>
            </value>
            <value>
                <fullName>81I84RSF IPRO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Product2/fields/Variedade__c.field-meta.xml
<CustomField>
    <fullName>Variedade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Variedade</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Variedad__c.Licenciada__c</field>
            <operation>equals</operation>
            <valueField>$Source.Licenciada__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Variedad__c</referenceTo>
    <relationshipLabel>Productos</relationshipLabel>
    <relationshipName>Productos</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Variedad__c/Variedad__c.object-meta.xml
<CustomObject>
    <description>Variedades, disponibles para incluir en los Contratos de Multiplicación</description>
    <label>Variedad</label>
    <nameField>
        <label>Nome Comercial</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Variedades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/classes/ProductsCRMAPITest.cls
@isTest
public class ProductsCRMAPITest {

    final static String TESTOBTENTOR1 = 'Don Mario';
    final static String TESTOBTENTOR2 = 'Bayer';

    /**
     *  METHOD:         makeData 
     *  DESCRIPTION:    Test Setup for Class. Created for US #14317 
     *  AUTHOR:         irina.benitez@cloudgaia.com (18-nov-21)
     **/ 
    @TestSetup
    static void makeData(){
        test.startTest();
        // Insert Categoria__c
        Categoria__c categoria = new Categoria__c(Name = 'BASICA');
        insert categoria;

        // Insert Variedad__c records
        List<Variedad__c> variedadList = new List<Variedad__c>();
        variedadList.add( new Variedad__c(Name = 'Variedad 1 Test', Ativa__c = true) );
        variedadList.add( new Variedad__c(Name = 'Variedad 2 Test', Ativa__c = true) );
        insert variedadList;

        // Insert Product2 records
        List<Product2> productList = new List<Product2>();
        productList.add( new Product2(Name = 'Product 1 Test', IsActive = true, Categ__c = categoria.Id, Family = 'Royalty x Basica', Variedade__c = variedadList[0].Id, Portal__c = true, Obtentor__c = TESTOBTENTOR1) );
        productList.add( new Product2(Name = 'Product 2 Test', IsActive = true, Categ__c = categoria.Id, Family = 'Royalty x Basica', Variedade__c = variedadList[1].Id, Portal__c = true, Obtentor__c = TESTOBTENTOR2) );
        insert productList;

        test.stopTest();    
    }        

    /**
     *  METHOD:         getProductsCRMTestPositive 
     *  DESCRIPTION:    Test class for ProductsCRMAPI.getProductsCRM. Created for US #14317 
     *  AUTHOR:         irina.benitez@cloudgaia.com (18-nov-21)
     *  TEST CASE:      call method with available products ==> success, returns products
     **/ 
    @isTest
    public static void getProductsCRMTestPositive() {

        ProductsCRMAPI.Response result;

        RestRequest req = new RestRequest(); 
        req.requestURI = '/services/apexrest/ProductsCRMAPI/';  
        req.httpMethod = 'GET';

        RestResponse resp = new RestResponse();
        RestContext.request = req;
        RestContext.response = resp;

        test.startTest();
        ProductsCRMAPI.getProductsCRM();
        test.stopTest();

        result = (ProductsCRMAPI.Response)JSON.deserialize(resp.responseBody.toString(), ProductsCRMAPI.Response.class);
        System.debug('result: ' + result);
        
        System.assert(result.status);
        System.assertEquals(Label.ProductsCRMAPI_Success_Message, result.message);
        System.assertEquals(2, result.productsCRM.size());

    }

    /**
     *  METHOD:         getProductsCRMTestNegative
     *  DESCRIPTION:    Test class for ProductsCRMAPI.getProductsCRM. Created for US #14317 
     *  AUTHOR:         irina.benitez@cloudgaia.com (18-nov-21)
     *  TEST CASE:      call method with valid event but no products  ==> returns generic error message
     **/ 
    @isTest
    public static void getProductsCRMTestNegative() {

        List<Product2> products = [SELECT Id, Portal__c FROM Product2];
        for(Product2 product : products){
            product.Portal__c = false;
        }
        update products;

        ProductsCRMAPI.Response result;

        RestRequest req = new RestRequest(); 
        req.requestURI = '/services/apexrest/ProductsCRMAPI/';  
        req.httpMethod = 'GET';

        RestResponse resp = new RestResponse();
        RestContext.request = req;
        RestContext.response = resp;

        test.startTest();
        ProductsCRMAPI.getProductsCRM();
        test.stopTest();

        result = (ProductsCRMAPI.Response)JSON.deserialize(resp.responseBody.toString(), ProductsCRMAPI.Response.class);
        System.debug('result: ' + result);
        
        System.assertEquals(false, result.status);
        System.assertEquals(Label.ProductsCRMAPI_Default_Error_Message, result.message);
        System.assertEquals(404, resp.statusCode);
    }


    /**
     *  METHOD:         productJSONConverterTestPositive 
     *  DESCRIPTION:    Test class for ProductsCRMAPI.productJSONConverter. Created for US #14317 
     *  AUTHOR:         irina.benitez@cloudgaia.com (18-nov-21)
     *  TEST CASE:      call method with product list ==> success, returns products in JSON format
     **/ 
    @isTest
    public static void productJSONConverterTestPositive() {

        List<Product2> productList = [SELECT Id, Name, Obtentor__c FROM Product2 LIMIT 1];

        test.startTest();
        Map<String,List<ProductsCRMAPI.Producto>> resultMap = ProductsCRMAPI.productJSONConverter(productList);
        test.stopTest();

        System.assertEquals(productList.size(), resultMap.size());
        System.assert(resultMap.containsKey(productList[0].Obtentor__c));
        System.assertEquals(productList[0].Id, resultMap.get(productList[0].Obtentor__c)[0].id_producto);
        System.assertEquals(productList[0].Name, resultMap.get(productList[0].Obtentor__c)[0].desc_producto);
    }

    /**
     *  METHOD:         productJSONConverterTestNegative 
     *  DESCRIPTION:    Test class for ProductsCRMAPI.productJSONConverter. Created for US #14317 
     *  AUTHOR:         irina.benitez@cloudgaia.com (18-nov-21)
     *  TEST CASE:      call method with empty product list ==> returns empty list in JSON format
     **/ 
    @isTest
    public static void productJSONConverterTestNegative() {

        List<Product2> productList = new List<Product2>();

        test.startTest();
        Map<String,List<ProductsCRMAPI.Producto>> resultMap = ProductsCRMAPI.productJSONConverter(productList);
        test.stopTest();

        System.assert(resultMap.isEmpty());

    }

}