Salesforce/main/default/main/default/objects/Contrato__c/Contrato__c.object-meta.xml
<CustomObject>
    <description>CONTRATO DE LICENCIAMENTO PARA MULTIPLICAÇÃO E COMERCIALIZAÇÃO</description>
    <label>Contrato de Multiplicação</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Numero do Contrato de Multiplicação</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contratos de Multiplicação</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/Contrato__c/fields/Contrato_marco__c.field-meta.xml
<CustomField>
    <fullName>Contrato_marco__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contrato guarda chuva para 3 safras</description>
    <label>Contrato Macro</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Termos Aditivos</relationshipLabel>
    <relationshipName>Contratos_de_Multiplicacion</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Contrato__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Edição</fullName>
                <default>true</default>
                <label>Edição</label>
            </value>
            <value>
                <fullName>Pendente de Aprovação</fullName>
            </value>
            <value>
                <fullName>Aguardando Assinatura</fullName>
            </value>
            <value>
                <fullName>Pendente de Impressão</fullName>
            </value>
            <value>
                <fullName>Pendente de Envio</fullName>
            </value>
            <value>
                <fullName>Pendente de Postagem</fullName>
            </value>
            <value>
                <fullName>Aguarda Retorno</fullName>
            </value>
            <value>
                <fullName>Chegou</fullName>
            </value>
            <value>
                <fullName>Inutilizado</fullName>
            </value>
            <value>
                <fullName>Anulado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Contrato__c/fields/Estados_Comercializacao__c.field-meta.xml
<CustomField>
    <fullName>Estados_Comercializacao__c</fullName>
    <label>Estados de Comercialização</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AC</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AM</fullName>
            </value>
            <value>
                <fullName>AP</fullName>
            </value>
            <value>
                <fullName>BA</fullName>
            </value>
            <value>
                <fullName>CE</fullName>
            </value>
            <value>
                <fullName>DF</fullName>
            </value>
            <value>
                <fullName>ES</fullName>
            </value>
            <value>
                <fullName>GO</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MG</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>PA</fullName>
            </value>
            <value>
                <fullName>Paraguai</fullName>
            </value>
            <value>
                <fullName>PB</fullName>
            </value>
            <value>
                <fullName>PE</fullName>
            </value>
            <value>
                <fullName>PI</fullName>
            </value>
            <value>
                <fullName>PR</fullName>
            </value>
            <value>
                <fullName>RJ</fullName>
            </value>
            <value>
                <fullName>RN</fullName>
            </value>
            <value>
                <fullName>RO</fullName>
            </value>
            <value>
                <fullName>RR</fullName>
            </value>
            <value>
                <fullName>RS</fullName>
            </value>
            <value>
                <fullName>SC</fullName>
            </value>
            <value>
                <fullName>SE</fullName>
            </value>
            <value>
                <fullName>SP</fullName>
            </value>
            <value>
                <fullName>TO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Contrato__c/fields/Meta_Qde_comodato_de_area__c.field-meta.xml
<CustomField>
    <fullName>Meta_Qde_comodato_de_area__c</fullName>
    <label>Meta Qde Comodato de Área</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/main/default/objects/Contrato__c/fields/Meta_Qde_Dias_de_Campo__c.field-meta.xml
<CustomField>
    <fullName>Meta_Qde_Dias_de_Campo__c</fullName>
    <label>Meta Qde Días de Campo Sem Custo</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/main/default/objects/Contrato__c/fields/Multiplicador__c.field-meta.xml
<CustomField>
    <fullName>Multiplicador__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Conta do multiplicador</description>
    <label>Multiplicador</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Contrato_de_Multiplica_o</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Contrato__c/fields/Nome_Fantasia__c.field-meta.xml
<CustomField>
    <fullName>Nome_Fantasia__c</fullName>
    <formula>Multiplicador__r.Nome_fantasia__c</formula>
    <label>Nome Fantasia Multiplicador</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/Contrato__c/fields/Observacao__c.field-meta.xml
<CustomField>
    <fullName>Observacao__c</fullName>
    <description>Informações genéricas sobre o processo de recebimento dos contratos</description>
    <inlineHelpText>Informações genéricas sobre o processo de recebimento dos contratos</inlineHelpText>
    <label>Observação</label>
    <type>TextArea</type>
</CustomField>

Salesforce/main/default/objects/Contrato__c/fields/Region_Comercial__c.field-meta.xml
<CustomField>
    <fullName>Region_Comercial__c</fullName>
    <label>Região Comercial</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>REGION 1</fullName>
            </value>
            <value>
                <fullName>REGION 2</fullName>
            </value>
            <value>
                <fullName>CERRADO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Contrato__c/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <label>Safra</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>17/18</fullName>
                <default>true</default>
                <label>17/18</label>
            </value>
            <value>
                <fullName>18/19</fullName>
            </value>
            <value>
                <fullName>19/20</fullName>
            </value>
            <value>
                <fullName>20/21</fullName>
            </value>
            <value>
                <fullName>21/22</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Contrato__c/fields/Sociedad__c.field-meta.xml
<CustomField>
    <fullName>Sociedad__c</fullName>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BRMX</fullName>
            </value>
            <value>
                <fullName>DSEM</fullName>
            </value>
            <value>
                <fullName>NEOG</fullName>
            </value>
            <value>
                <fullName>DAGMA</fullName>
            </value>
            <value>
                <fullName>LICENÇAS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Contrato__c/fields/tieneItems__c.field-meta.xml
<CustomField>
    <fullName>tieneItems__c</fullName>
    <label>Cantidad de items</label>
    <summaryForeignKey>Item_del_Contrato__c.Contrato_de_Multiplicacion__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

Salesforce/main/default/main/default/objects/Contrato__c/fields/Tipo_de_registro__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_registro__c</fullName>
    <description>Tipo de registros para completar la Sociedad con este valor</description>
    <formula>$RecordType.DeveloperName</formula>
    <inlineHelpText>Tipo de registros para completar la Sociedad con este valor</inlineHelpText>
    <label>Tipo de registro</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/Contrato__c/fields/Volume_Total_Autorizado__c.field-meta.xml
<CustomField>
    <fullName>Volume_Total_Autorizado__c</fullName>
    <label>Volume Total Autorizado</label>
    <summarizedField>Item_del_Contrato__c.Volumen_Aut_Comercializacion__c</summarizedField>
    <summaryFilterItems>
        <field>Item_del_Contrato__c.RecordTypeId</field>
        <operation>equals</operation>
        <value>Volumen</value>
    </summaryFilterItems>
    <summaryForeignKey>Item_del_Contrato__c.Contrato_de_Multiplicacion__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

Salesforce/main/default/objects/Item_del_Contrato__c/Item_del_Contrato__c.object-meta.xml
<CustomObject>
    <description>Item de CONTRATO DE LICENCIAMENTO PARA MULTIPLICAÇÃO E COMERCIALIZAÇÃO</description>
    <label>Item del Contrato</label>
    <nameField>
        <label>Nombre de Item del Contrato</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items del Contrato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Salesforce/main/default/objects/Item_del_Contrato__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AC</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AM</fullName>
            </value>
            <value>
                <fullName>AP</fullName>
            </value>
            <value>
                <fullName>BA</fullName>
            </value>
            <value>
                <fullName>CE</fullName>
            </value>
            <value>
                <fullName>DF</fullName>
            </value>
            <value>
                <fullName>ES</fullName>
            </value>
            <value>
                <fullName>GO</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MG</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>PA</fullName>
            </value>
            <value>
                <fullName>Paraguai</fullName>
            </value>
            <value>
                <fullName>PB</fullName>
            </value>
            <value>
                <fullName>PE</fullName>
            </value>
            <value>
                <fullName>PI</fullName>
            </value>
            <value>
                <fullName>PR</fullName>
            </value>
            <value>
                <fullName>RJ</fullName>
            </value>
            <value>
                <fullName>RN</fullName>
            </value>
            <value>
                <fullName>RO</fullName>
            </value>
            <value>
                <fullName>RR</fullName>
            </value>
            <value>
                <fullName>RS</fullName>
            </value>
            <value>
                <fullName>SC</fullName>
            </value>
            <value>
                <fullName>SE</fullName>
            </value>
            <value>
                <fullName>SP</fullName>
            </value>
            <value>
                <fullName>TO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Variedad__c/Variedad__c.object-meta.xml
<CustomObject>
    <description>Variedades, disponibles para incluir en los Contratos de Multiplicación</description>
    <label>Variedad</label>
    <nameField>
        <label>Nome Comercial</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Variedades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/objects/Variedad__c/fields/Sociedad__c.field-meta.xml
<CustomField>
    <fullName>Sociedad__c</fullName>
    <formula>CASE(Marca_comercial__c,&quot;Brasmax&quot;,&quot;BRMX&quot;,&quot;DM Sementes&quot;,&quot;DSEM&quot;,&quot;Neogen&quot;,&quot;NEOG&quot;,&quot;&quot;)</formula>
    <label>Sociedad</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/classes/ClonarContratoLightningController.cls
public without sharing class ClonarContratoLightningController {
  
    @AuraEnabled
    public static String cloneContract(String recordId) {
        Savepoint sp = Database.setSavepoint();
        Contrato__c contrato = [SELECT Id, Estado__c FROM Contrato__c WHERE Id = :recordId ];
        Contrato__c nuevoContrato;

         try {
            contrato = [
                SELECT Id, Name, Multiplicador__c, Sociedad__c, Contrato_marco__c, Nome_Fantasia__c, Safra__c,
                Region_Comercial__c, RecordTypeId, Estados_Comercializacao__c, Observacao__c, Tipo_de_registro__c, Estado__c,
				Volume_Total_Autorizado__c, Meta_Qde_Dias_de_Campo__c, Meta_Qde_comodato_de_area__c, tieneItems__c, OwnerId
                FROM Contrato__c 
                WHERE Id = :recordId 
            ];

        }
        catch (Exception e) {
                throw new AuraHandledException('não há contrato');
        }
        
        if(contrato.Estado__c != 'Chegou') {
            throw new AuraHandledException('Erro: Para clonar o aditivo o status tem que ser "Chegou"');
        }
        else {
            try {
                
                nuevoContrato = contrato.clone(false, false);
                nuevoContrato.Contrato_ant__c = contrato.Id;
                nuevoContrato.Estado__c = 'Edição';
                nuevoContrato.RecordTypeId = contrato.RecordTypeId;
                contrato.Estado__c = 'Inutilizado';
                
                insert nuevoContrato;
                update contrato;
                
                List<Item_del_Contrato__c> itemsClonados = new List<Item_del_Contrato__c>();
                List<Item_del_Contrato__c> itemsOriginales = new List<Item_del_Contrato__c>();
                    
                itemsOriginales = [
                    SELECT Name, Cultivar__c, Precio__c, Variedad__c, Volumen_Aut_Comercializacion__c, Praca__c, Tipo_de_Referencia__c, Cotacao_de_soja__c,
                    Referencia_de_Praca__c, Referencia_de_Preco__c, Contrato_de_Multiplicacao__c, Contrato_de_Multiplicacao_vol__c, Contrato_de_Multiplicacion__c,
                    Quantidade__c, RecordTypeId, Tipo_de_Evento__c, Clonado__c, Estado__c
                    FROM Item_del_Contrato__c
                    WHERE Contrato_de_Multiplicacion__c =: contrato.id
                ];
                
                for (Item_del_Contrato__c pi : itemsOriginales) {
                    Item_del_Contrato__c nuevoItem = pi.clone(false, true);
					if(pi.Contrato_de_Multiplicacao__c != null) {
						nuevoItem.Contrato_de_Multiplicacao__c = nuevoContrato.Id;
					}
					if(pi.Contrato_de_Multiplicacao_vol__c != null) {
						nuevoItem.Contrato_de_Multiplicacao_vol__c = nuevoContrato.Id;
					}
					nuevoItem.Contrato_de_Multiplicacion__c = nuevoContrato.Id;
					nuevoItem.Clonado__c = true;
                    itemsClonados.add(nuevoItem);
                }
                insert itemsClonados;
            } catch (Exception e) {
                Database.rollback(sp);
                string message = e.getMessage();
                throw new AuraHandledException(message);
            }
        
        }
        
        return nuevoContrato.Id;        
    }
}