Salesforce/main/default/main/default/objects/Contrato__c/Contrato__c.object-meta.xml
<CustomObject>
    <description>CONTRATO DE LICENCIAMENTO PARA MULTIPLICAÇÃO E COMERCIALIZAÇÃO</description>
    <label>Contrato de Multiplicação</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Numero do Contrato de Multiplicação</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contratos de Multiplicação</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/Contrato__c/fields/Contrato_ant__c.field-meta.xml
<CustomField>
    <fullName>Contrato_ant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Este campo guarda una referencia al contrato original, en el caso de que el contrato sea resultado de una clonación</description>
    <label>Contrato Original</label>
    <referenceTo>Contrato__c</referenceTo>
    <relationshipLabel>Contratos de Multiplicação</relationshipLabel>
    <relationshipName>Contratos_de_Multiplica_o</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Contrato__c/fields/Contrato_marco__c.field-meta.xml
<CustomField>
    <fullName>Contrato_marco__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contrato guarda chuva para 3 safras</description>
    <label>Contrato Macro</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Termos Aditivos</relationshipLabel>
    <relationshipName>Contratos_de_Multiplicacion</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Contrato__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Edição</fullName>
                <default>true</default>
                <label>Edição</label>
            </value>
            <value>
                <fullName>Pendente de Aprovação</fullName>
            </value>
            <value>
                <fullName>Aguardando Assinatura</fullName>
            </value>
            <value>
                <fullName>Pendente de Impressão</fullName>
            </value>
            <value>
                <fullName>Pendente de Envio</fullName>
            </value>
            <value>
                <fullName>Pendente de Postagem</fullName>
            </value>
            <value>
                <fullName>Aguarda Retorno</fullName>
            </value>
            <value>
                <fullName>Chegou</fullName>
            </value>
            <value>
                <fullName>Inutilizado</fullName>
            </value>
            <value>
                <fullName>Anulado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Contrato__c/fields/Estados_Comercializacao__c.field-meta.xml
<CustomField>
    <fullName>Estados_Comercializacao__c</fullName>
    <label>Estados de Comercialização</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AC</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AM</fullName>
            </value>
            <value>
                <fullName>AP</fullName>
            </value>
            <value>
                <fullName>BA</fullName>
            </value>
            <value>
                <fullName>CE</fullName>
            </value>
            <value>
                <fullName>DF</fullName>
            </value>
            <value>
                <fullName>ES</fullName>
            </value>
            <value>
                <fullName>GO</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MG</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>PA</fullName>
            </value>
            <value>
                <fullName>Paraguai</fullName>
            </value>
            <value>
                <fullName>PB</fullName>
            </value>
            <value>
                <fullName>PE</fullName>
            </value>
            <value>
                <fullName>PI</fullName>
            </value>
            <value>
                <fullName>PR</fullName>
            </value>
            <value>
                <fullName>RJ</fullName>
            </value>
            <value>
                <fullName>RN</fullName>
            </value>
            <value>
                <fullName>RO</fullName>
            </value>
            <value>
                <fullName>RR</fullName>
            </value>
            <value>
                <fullName>RS</fullName>
            </value>
            <value>
                <fullName>SC</fullName>
            </value>
            <value>
                <fullName>SE</fullName>
            </value>
            <value>
                <fullName>SP</fullName>
            </value>
            <value>
                <fullName>TO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Contrato__c/fields/log_cambios__c.field-meta.xml
<CustomField>
    <fullName>log_cambios__c</fullName>
    <description>Campo para especificar los cambios que se hicieron en un contrato clonado a partir de la comparacion con el contrato original</description>
    <label>Log de alterações</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

Salesforce/main/default/main/default/objects/Contrato__c/fields/Meta_Qde_comodato_de_area__c.field-meta.xml
<CustomField>
    <fullName>Meta_Qde_comodato_de_area__c</fullName>
    <label>Meta Qde Comodato de Área</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/main/default/objects/Contrato__c/fields/Meta_Qde_Dias_de_Campo__c.field-meta.xml
<CustomField>
    <fullName>Meta_Qde_Dias_de_Campo__c</fullName>
    <label>Meta Qde Días de Campo Sem Custo</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/objects/Contrato__c/fields/Region_Comercial__c.field-meta.xml
<CustomField>
    <fullName>Region_Comercial__c</fullName>
    <label>Região Comercial</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>REGION 1</fullName>
            </value>
            <value>
                <fullName>REGION 2</fullName>
            </value>
            <value>
                <fullName>CERRADO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Contrato__c/fields/Sociedad__c.field-meta.xml
<CustomField>
    <fullName>Sociedad__c</fullName>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BRMX</fullName>
            </value>
            <value>
                <fullName>DSEM</fullName>
            </value>
            <value>
                <fullName>NEOG</fullName>
            </value>
            <value>
                <fullName>DAGMA</fullName>
            </value>
            <value>
                <fullName>LICENÇAS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Contrato__c/fields/Volume_Total_Autorizado__c.field-meta.xml
<CustomField>
    <fullName>Volume_Total_Autorizado__c</fullName>
    <label>Volume Total Autorizado</label>
    <summarizedField>Item_del_Contrato__c.Volumen_Aut_Comercializacion__c</summarizedField>
    <summaryFilterItems>
        <field>Item_del_Contrato__c.RecordTypeId</field>
        <operation>equals</operation>
        <value>Volumen</value>
    </summaryFilterItems>
    <summaryForeignKey>Item_del_Contrato__c.Contrato_de_Multiplicacion__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

Salesforce/main/default/main/default/objects/Estado__c/Estado__c.object-meta.xml
<CustomObject>
    <label>Estado</label>
    <nameField>
        <label>Nome do Estado</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estados</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/classes/Contrato_cTriggerHelper.cls
public  class Contrato_cTriggerHelper {

	public static void escribirLogCambios(List<Contrato__c> triggerNew, Map<Id, Contrato__c> triggerOld) {
		
		List<Id> idsContratosOriginales = new List<Id>();
		List<Contrato__c> listaContratosOriginales = new List<Contrato__c>();
		Map<String, Contrato__c> mapaContratosOriginales = new Map<String, Contrato__c>();
		for(Contrato__c contrato : triggerNew) {
			if(contrato.Contrato_ant__c != null ) {
				idsContratosOriginales.add(contrato.Contrato_ant__c);
			}
		}
		//Modificar la query para incluir los campos a revisar por cambios
		listaContratosOriginales = [
			SELECT Id, Sociedad__c, Estados_Comercializacao__c, Contrato_marco__c, Region_Comercial__c,
			Meta_Qde_comodato_de_area__c, Meta_Qde_Dias_de_Campo__c, Volume_Total_Autorizado__c, Estado__c
			FROM Contrato__c
			WHERE ID IN: idsContratosOriginales
		];
		if(listaContratosOriginales.size() == 0) {
			return;
		}
		for(Contrato__c contrato : listaContratosOriginales) {
			mapaContratosOriginales.put(contrato.Id, contrato);
		}
		
		for(Contrato__c contrato : triggerNew) {
			if(contrato.Contrato_ant__c != null ) {
				Contrato__c original = mapaContratosOriginales.get(contrato.Contrato_ant__c);
				Contrato__c antiguo = triggerOld.get(contrato.Id);
					if(antiguo.Estado__c == 'Edição' && (contrato.Estado__c != antiguo.Estado__c)) {
						if(contrato.log_cambios__c == null) {
							contrato.log_cambios__c = '';
						}
					//Chequeamos si cambiaron los campos
					if(original.Sociedad__c != contrato.Sociedad__c) {
						contrato.log_cambios__c += '\n\u2022Marca alterada de ' + original.Sociedad__c + ' para ' + contrato.Sociedad__c;
					}
					if(original.Estados_Comercializacao__c != contrato.Estados_Comercializacao__c) {
						contrato.log_cambios__c += '\n\u2022Estados de Comercialização alterado de ' + original.Estados_Comercializacao__c + ' para ' + contrato.Estados_Comercializacao__c;
					}

					if(original.Contrato_marco__c != contrato.Contrato_marco__c) {
						contrato.log_cambios__c += '\n\u2022Contrato Marco alterado de ' + original.Contrato_marco__c + ' para ' + contrato.Contrato_marco__c;
					}

					if(original.Region_Comercial__c != contrato.Region_Comercial__c) {
						contrato.log_cambios__c += '\n\u2022Region Comercial alterado de ' + original.Region_Comercial__c + ' para ' + contrato.Region_Comercial__c;
					}

					if(original.Meta_Qde_comodato_de_area__c != contrato.Meta_Qde_comodato_de_area__c) {
						contrato.log_cambios__c += '\n\u2022Meta Qde Comodato de Área alterado de ' 
                            + Integer.valueOf((original.Meta_Qde_comodato_de_area__c)  == null ? 0 : original.Meta_Qde_comodato_de_area__c)
                            + ' para ' 
                            +  Integer.valueOf((contrato.Meta_Qde_comodato_de_area__c)  == null ? 0 : contrato.Meta_Qde_comodato_de_area__c);

					}

					if(original.Meta_Qde_Dias_de_Campo__c != contrato.Meta_Qde_Dias_de_Campo__c) {
						contrato.log_cambios__c += '\n\u2022Meta Qde Días de Campo Sem Custo alterado de ' 
                            + Integer.valueOf((original.Meta_Qde_Dias_de_Campo__c)  == null ? 0 : original.Meta_Qde_Dias_de_Campo__c)
                            + ' para ' 
                            +  Integer.valueOf((contrato.Meta_Qde_Dias_de_Campo__c)  == null ? 0 : contrato.Meta_Qde_Dias_de_Campo__c);

					}

					if(original.Volume_Total_Autorizado__c != contrato.Volume_Total_Autorizado__c) {
						contrato.log_cambios__c += '\n\u2022Volume Total Autorizado alterado de ' 
                            + Integer.valueOf((original.Volume_Total_Autorizado__c)  == null ? 0 : original.Volume_Total_Autorizado__c)
                            + ' para ' 
                            +  Integer.valueOf((contrato.Volume_Total_Autorizado__c)  == null ? 0 : contrato.Volume_Total_Autorizado__c);
					}
				}
			}
		}

	}
}