Salesforce/main/default/main/default/objects/Contrato__c/Contrato__c.object-meta.xml
<CustomObject>
    <description>CONTRATO DE LICENCIAMENTO PARA MULTIPLICAÇÃO E COMERCIALIZAÇÃO</description>
    <label>Contrato de Multiplicação</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Numero do Contrato de Multiplicação</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contratos de Multiplicação</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/Contrato__c/fields/Contrato_ant__c.field-meta.xml
<CustomField>
    <fullName>Contrato_ant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Este campo guarda una referencia al contrato original, en el caso de que el contrato sea resultado de una clonación</description>
    <label>Contrato Original</label>
    <referenceTo>Contrato__c</referenceTo>
    <relationshipLabel>Contratos de Multiplicação</relationshipLabel>
    <relationshipName>Contratos_de_Multiplica_o</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Signatario__c/Signatario__c.object-meta.xml
<CustomObject>
    <label>Signatário</label>
    <nameField>
        <displayFormat>SI-{00000000}</displayFormat>
        <label>Número do signatário</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Signatário</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/Signatario__c/fields/Contrato_de_Multiplicacao__c.field-meta.xml
<CustomField>
    <fullName>Contrato_de_Multiplicacao__c</fullName>
    <label>Contrato de Multiplicação</label>
    <referenceTo>Contrato__c</referenceTo>
    <relationshipLabel>Signatário</relationshipLabel>
    <relationshipName>Signatario</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Salesforce/main/default/classes/ControladorAditivos.cls
Global with sharing class ControladorAditivos  {
    
    
    public id contratoId {get;set;}
    public List<Integer> numerosDeSignatarios{get;set;}

	public ControladorAditivos(ApexPages.StandardController controller) {
		contratoId = apexpages.currentpage().getparameters().get('id');
    	numerosDeSignatarios = new  List<Integer>();
        
        List<Signatario__c> signatarios = [
            SELECT Id, Contrato_de_Multiplicacao__c 
            FROM Signatario__c
            WHERE Contrato_de_Multiplicacao__c  = :contratoId
        ];
        
        for (integer i = 0; i < signatarios.size(); i++) {
            numerosDeSignatarios.add(i+2);
        }
	}
    public boolean getContratoClonado(){
         Contrato__c obj = [
            SELECT Id, Contrato_ant__c
            FROM Contrato__c
            WHERE id =: contratoId 
         ];
        
        return obj.Contrato_ant__c != null;
    }
}