Salesforce/main/default/main/default/objects/Contrato__c/Contrato__c.object-meta.xml
<CustomObject>
    <description>CONTRATO DE LICENCIAMENTO PARA MULTIPLICAÇÃO E COMERCIALIZAÇÃO</description>
    <label>Contrato de Multiplicação</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Numero do Contrato de Multiplicação</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contratos de Multiplicação</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/Contrato__c/fields/Contrato_ant__c.field-meta.xml
<CustomField>
    <fullName>Contrato_ant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Este campo guarda una referencia al contrato original, en el caso de que el contrato sea resultado de una clonación</description>
    <label>Contrato Original</label>
    <referenceTo>Contrato__c</referenceTo>
    <relationshipLabel>Contratos de Multiplicação</relationshipLabel>
    <relationshipName>Contratos_de_Multiplica_o</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/classes/ControladorAditivosTest.cls
@isTest
public class ControladorAditivosTest {
    
    @isTest
    static void llamarAGetContratoClonadoConUnContratoConContratoAnteriorDeberiaDevolverFalse() {
        Contrato__c contrato = new Contrato__c();
        insert contrato;
        
        ControladorAditivos controlador = new ControladorAditivos(new ApexPages.StandardController(contrato));
        controlador.contratoId = contrato.Id;
        
        Test.startTest();
        Boolean clonado = controlador.getContratoClonado();
        Test.stopTest();
        
        System.assertEquals(false, clonado);
    }
    
    @isTest
    static void llamarAGetContratoClonadoConUnContratoConContratoAnteriorDeberiaDevolverTrue() {
        Contrato__c contratoAnterior = new Contrato__c();
        insert contratoAnterior;
        
        Contrato__c contrato = new Contrato__c(
        	Contrato_ant__c = contratoAnterior.Id
        );
        insert contrato;
        
        ControladorAditivos controlador = new ControladorAditivos(new ApexPages.StandardController(contrato));
        controlador.contratoId = contrato.Id;
        
        Test.startTest();
        Boolean clonado = controlador.getContratoClonado();
        Test.stopTest();
        
        System.assertEquals(true, clonado);
    }
    
}