Salesforce/main/default/main/default/objects/Contrato__c/Contrato__c.object-meta.xml
<CustomObject>
    <description>CONTRATO DE LICENCIAMENTO PARA MULTIPLICAÇÃO E COMERCIALIZAÇÃO</description>
    <label>Contrato de Multiplicação</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Numero do Contrato de Multiplicação</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contratos de Multiplicação</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/Contrato__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Edição</fullName>
                <default>true</default>
                <label>Edição</label>
            </value>
            <value>
                <fullName>Pendente de Aprovação</fullName>
            </value>
            <value>
                <fullName>Aguardando Assinatura</fullName>
            </value>
            <value>
                <fullName>Pendente de Impressão</fullName>
            </value>
            <value>
                <fullName>Pendente de Envio</fullName>
            </value>
            <value>
                <fullName>Pendente de Postagem</fullName>
            </value>
            <value>
                <fullName>Aguarda Retorno</fullName>
            </value>
            <value>
                <fullName>Chegou</fullName>
            </value>
            <value>
                <fullName>Inutilizado</fullName>
            </value>
            <value>
                <fullName>Anulado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/dfsle__EnvelopeStatus__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>DocuSign Status</relationshipLabel>
    <relationshipName>DocuSign_Status</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/dfsle__EnvelopeStatus__c/fields/Contrato_de_Multiplicacao__c.field-meta.xml
<CustomField>
    <fullName>Contrato_de_Multiplicacao__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contrato de Multiplicação</label>
    <referenceTo>Contrato__c</referenceTo>
    <relationshipLabel>DocuSign Status</relationshipLabel>
    <relationshipName>DocuSign_Status</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/dfsle__EnvelopeStatus__c/fields/Oportunidade__c.field-meta.xml
<CustomField>
    <fullName>Oportunidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Oportunidade</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>DocuSign Status</relationshipLabel>
    <relationshipName>DocuSign_Status</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Estado__c/Estado__c.object-meta.xml
<CustomObject>
    <label>Estado</label>
    <nameField>
        <label>Nome do Estado</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estados</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/objects/Opportunity/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <formula>IF(NOT(ISNULL(Inicio_Cargamento__c)),
			IF(NOT(ISNULL(Inicio_Transporte__c)),
						IF(NOT(ISNULL(Fin_Transporte__c)),
									IF(AND(Confirmado__c,NOT(Solicitacao_de_reembolso__c)),
											&apos;Confirmado&apos;,
											IF(AND(Solicitacao_de_reembolso__c,NOT(Confirmado__c)),
													&apos;Em Troca&apos;,
													&apos;Entregue&apos;)
											),
									&apos;Pedido em trânsito&apos;),
						&apos;Em carregamento&apos;),
			&apos;&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status de transporte</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/Opportunity/recordTypes/Comercial.recordType-meta.xml
<RecordType>
    <fullName>Comercial</fullName>
    <active>true</active>
    <businessProcess>Control_Multiplicador</businessProcess>
    <description>Detalle de lo que el multiplicador va a vender: relatorio de venda</description>
    <label>Comercial</label>
</RecordType>

Salesforce/main/default/main/default/classes/Batch_Docusign_Approval_Process.cls
global class Batch_Docusign_Approval_Process implements Database.Batchable<sObject> {
    
    global List<dfsle__EnvelopeStatus__c> start(Database.BatchableContext bc){   
        return [SELECT Id, Oportunidade__c, Contrato_de_Multiplicacao__c, Contract__c FROM dfsle__EnvelopeStatus__c WHERE 
        	((Oportunidade__c != null AND Oportunidade__r.StageName = 'Aguardando Assinatura') 
			OR (Contrato_de_Multiplicacao__c != null AND Contrato_de_Multiplicacao__r.Estado__c = 'Aguardando Assinatura')
			OR (Contract__c != null AND Contract__r.Status = 'Pendente de Postagem')) 
            AND dfsle__Status__c = 'Completed'];
    }
    
    global void execute(Database.BatchableContext bc, List<dfsle__EnvelopeStatus__c> envelopeStatusList) {
        Set<Id> signedObjectIdList = new Set<Id>();
        for(dfsle__EnvelopeStatus__c envelopeStatusObject : envelopeStatusList) {
            if(envelopeStatusObject.Oportunidade__c != null) {
                signedObjectIdList.add(envelopeStatusObject.Oportunidade__c);
            } else if(envelopeStatusObject.Contrato_de_Multiplicacao__c != null) {
                signedObjectIdList.add(envelopeStatusObject.Contrato_de_Multiplicacao__c);
            }
			else if(envelopeStatusObject.Contract__c != null) {
                signedObjectIdList.add(envelopeStatusObject.Contract__c);
            }
        }
        System.debug(signedObjectIdList);
        if(signedObjectIdList.size() > 0) {
           	List<ProcessInstanceWorkitem> approvalProcessItemList = [SELECT Id, ProcessInstance.TargetObjectId FROM ProcessInstanceWorkitem WHERE ProcessInstance.TargetObjectId IN :signedObjectIdList ORDER BY CreatedDate DESC];
            System.debug(approvalProcessItemList);
            if(approvalProcessItemList.size() > 0) {
                for(ProcessInstanceWorkitem approvalProcessItem : approvalProcessItemList) {
                    Approval.ProcessWorkitemRequest approveProcess = new Approval.ProcessWorkitemRequest();
                    String approvalProcessComent = 'Assinado.';
                    if(approvalProcessItem.ProcessInstance.TargetObjectId.getSobjectType() == Schema.getGlobalDescribe().get('Opportunity')) {
                        approvalProcessComent = 'Oportunidade assinada pelo Gerente';
                    } else if(approvalProcessItem.ProcessInstance.TargetObjectId.getSobjectType() == Schema.getGlobalDescribe().get('Contrato__c')) {
                        approvalProcessComent = 'Termo Aditivo assinado pelo Diretor Comercial';
                    } else if(approvalProcessItem.ProcessInstance.TargetObjectId.getSobjectType() == Schema.getGlobalDescribe().get('Contract')) {
                        approvalProcessComent = 'Termo Juridico assinado pelo Diretor Comercial';
                    }
                    approveProcess.setComments(approvalProcessComent);
                    approveProcess.setAction('Approve');
                    approveProcess.setWorkitemId(approvalProcessItem.Id);
                    Approval.ProcessResult approvedProcess = Approval.Process(approveProcess); 
                }   
            }
		}
    }
    
    global void finish(Database.BatchableContext bc) {}
}