Salesforce/main/default/main/default/objects/Contrato__c/Contrato__c.object-meta.xml
<CustomObject>
    <description>CONTRATO DE LICENCIAMENTO PARA MULTIPLICAÇÃO E COMERCIALIZAÇÃO</description>
    <label>Contrato de Multiplicação</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Numero do Contrato de Multiplicação</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contratos de Multiplicação</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/Contrato__c/fields/Cotacao_de_soja__c.field-meta.xml
<CustomField>
    <fullName>Cotacao_de_soja__c</fullName>
    <description>No pagamento dos Royalties, usamos a cotação de soja de duas empresas, dependendo da região da conta</description>
    <inlineHelpText>No pagamento dos Royalties, usamos a cotação de soja de duas empresas, dependendo da região da conta</inlineHelpText>
    <label>Cotação de soja</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Tipo_de_Cota_o__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>COAMO</fullName>
            </value>
            <value>
                <fullName>COTRIJAL</fullName>
            </value>
            <value>
                <fullName>SAFRAS &amp; MERCADO</fullName>
            </value>
            <value>
                <fullName>CHICAGO</fullName>
            </value>
            <value>
                <fullName>C. VALE</fullName>
            </value>
            <value>
                <fullName>ADM</fullName>
            </value>
            <value>
                <fullName>ASUNCION</fullName>
            </value>
            <value>
                <fullName>S&amp;M - Campo Grande (MS)</fullName>
            </value>
            <value>
                <fullName>S&amp;M - Rio Verde (GO)</fullName>
            </value>
            <value>
                <fullName>S&amp;M - Sorriso (MT)</fullName>
            </value>
            <value>
                <fullName>S&amp;M - Passo Fundo (RS)</fullName>
            </value>
            <value>
                <fullName>S&amp;M - Londrina (PR)</fullName>
            </value>
            <value>
                <fullName>S&amp;M - Rondonópolis (MT)</fullName>
            </value>
            <value>
                <fullName>S&amp;M - Barreiras (BA)</fullName>
            </value>
            <value>
                <fullName>S&amp;M - Uberlandia (MG)</fullName>
            </value>
            <value>
                <fullName>S&amp;M - Diamantino (MT)</fullName>
            </value>
            <value>
                <fullName>S&amp;M - Pedro Afonso (TO)</fullName>
            </value>
            <value>
                <fullName>S&amp;M - Brasília (DF)</fullName>
            </value>
            <value>
                <fullName>S&amp;M - Primavera (MT)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Contrato__c/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <label>Safra</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>17/18</fullName>
                <default>true</default>
                <label>17/18</label>
            </value>
            <value>
                <fullName>18/19</fullName>
            </value>
            <value>
                <fullName>19/20</fullName>
            </value>
            <value>
                <fullName>20/21</fullName>
            </value>
            <value>
                <fullName>21/22</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Contrato__c/fields/Tipo_de_Cota_o__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Cota_o__c</fullName>
    <label>Tipo de Cotação</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sociedad__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>DOLAR</fullName>
            </value>
            <value>
                <fullName>SOJA</fullName>
            </value>
            <value>
                <fullName>FATURAMENTO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Cotizacion_Soja__c/Cotizacion_Soja__c.object-meta.xml
<CustomObject>
    <label>Cotizacion Soja</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Nombre de Cotizacion Soja</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cotizaciones Soja</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/Cotizacion_Soja__c/fields/Cotacao_de_soja__c.field-meta.xml
<CustomField>
    <fullName>Cotacao_de_soja__c</fullName>
    <description>Lista de Cotizaciones de Soja. Debe tener los mismos elementos que el campo Cotação de soja del objeto Contrato de Multiplicação.</description>
    <label>Cotação de soja</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ADM</fullName>
            </value>
            <value>
                <fullName>ASUNCION</fullName>
            </value>
            <value>
                <fullName>C. VALE</fullName>
            </value>
            <value>
                <fullName>C. VALE - Palotina (PR)</fullName>
            </value>
            <value>
                <fullName>CHICAGO</fullName>
            </value>
            <value>
                <fullName>COAMO</fullName>
            </value>
            <value>
                <fullName>COAMO - Campo Mourão (PR)</fullName>
            </value>
            <value>
                <fullName>COTRIJAL</fullName>
            </value>
            <value>
                <fullName>COTRIJAL - Não me Toque (RS)</fullName>
            </value>
            <value>
                <fullName>DOLAR</fullName>
            </value>
            <value>
                <fullName>S&amp;M - Barreiras (BA)</fullName>
            </value>
            <value>
                <fullName>S&amp;M - Brasília (DF)</fullName>
            </value>
            <value>
                <fullName>S&amp;M - Campo Grande (MS)</fullName>
            </value>
            <value>
                <fullName>S&amp;M - Diamantino (MT)</fullName>
            </value>
            <value>
                <fullName>S&amp;M - Londrina (PR)</fullName>
            </value>
            <value>
                <fullName>S&amp;M - Paragominas (PA)</fullName>
            </value>
            <value>
                <fullName>S&amp;M - Passo Fundo (RS)</fullName>
            </value>
            <value>
                <fullName>S&amp;M - Pedro Afonso (TO)</fullName>
            </value>
            <value>
                <fullName>S&amp;M - Primavera (MT)</fullName>
            </value>
            <value>
                <fullName>S&amp;M - Rio Verde (GO)</fullName>
            </value>
            <value>
                <fullName>S&amp;M - Rondonópolis (MT)</fullName>
            </value>
            <value>
                <fullName>S&amp;M - Sorriso (MT)</fullName>
            </value>
            <value>
                <fullName>S&amp;M - Uberlandia (MG)</fullName>
            </value>
            <value>
                <fullName>S&amp;M - Unaí (MG)</fullName>
            </value>
            <value>
                <fullName>S&amp;M - Uruçui (PI)</fullName>
            </value>
            <value>
                <fullName>SAFRAS &amp; MERCADO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Cotizacion_Soja__c/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <label>Safra</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>17/18</fullName>
            </value>
            <value>
                <fullName>18/19</fullName>
            </value>
            <value>
                <fullName>19/20</fullName>
            </value>
            <value>
                <fullName>20/21</fullName>
            </value>
            <value>
                <fullName>21/22</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Opportunity/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <description>Safra o Campania agricola</description>
    <label>Safra</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>06/07</fullName>
            </value>
            <value>
                <fullName>07/08</fullName>
            </value>
            <value>
                <fullName>08/09</fullName>
            </value>
            <value>
                <fullName>09/10</fullName>
            </value>
            <value>
                <fullName>09/09</fullName>
            </value>
            <value>
                <fullName>10/10</fullName>
            </value>
            <value>
                <fullName>10/11</fullName>
            </value>
            <value>
                <fullName>11/11</fullName>
            </value>
            <value>
                <fullName>11/12</fullName>
            </value>
            <value>
                <fullName>12/12</fullName>
            </value>
            <value>
                <fullName>12/13</fullName>
            </value>
            <value>
                <fullName>13/14</fullName>
            </value>
            <value>
                <fullName>14/15</fullName>
            </value>
            <value>
                <fullName>15/16</fullName>
            </value>
            <value>
                <fullName>16/17</fullName>
            </value>
            <value>
                <fullName>17/18</fullName>
            </value>
            <value>
                <fullName>18/19</fullName>
            </value>
            <value>
                <fullName>19/20</fullName>
            </value>
            <value>
                <fullName>20/21</fullName>
            </value>
            <value>
                <fullName>21/22</fullName>
                <default>true</default>
                <label>21/22</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Opportunity/fields/Tipo_de_Cota_o__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Cota_o__c</fullName>
    <label>Tipo de Cotação</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DOLAR</fullName>
            </value>
            <value>
                <fullName>SOJA</fullName>
            </value>
            <value>
                <fullName>FATURAMENTO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/OpportunityLineItem/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <formula>TEXT(Opportunity.Safra__c)</formula>
    <label>Safra</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/OpportunityLineItem/fields/Variedad__c.field-meta.xml
<CustomField>
    <fullName>Variedad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Variedades que pueden incluirse en el contrato de multiplicacion</description>
    <inlineHelpText>Variedades que pueden incluirse en el contrato de multiplicacion</inlineHelpText>
    <label>Variedad</label>
    <referenceTo>Variedad__c</referenceTo>
    <relationshipLabel>Producto de oportunidad</relationshipLabel>
    <relationshipName>Producto_de_oportunidad</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/classes/testFacturar_Controller.cls
@isTest
private class testFacturar_Controller{
    static testMethod void Inicio(){
    
    Facturar_Controller fc = new Facturar_Controller();
    
    fc.contrato.Tipo_de_Cota_o__c='SOJA';
    fc.contrato.Cotacao_de_soja__c='COAMO';
    
    fc.Buscar();  
    
    fc.contrato.Tipo_de_Cota_o__c='DOLAR';
    
    fc.Buscar();
    
    Opportunity o = new Opportunity(Name='TMP', StageName='Aberta', CloseDate=System.Today());
    
    fc.setFact_Param(o);
    o=fc.getFact_Param();
    fc.setOpp(o);
    o=fc.getOpp();
    insert o;
    Contrato__c c = new Contrato__c();
    fc.setContrato(c);
    c=fc.getContrato();
    
    OpportunityLineItem i = new OpportunityLineItem();
    fc.setItem(i);
    i=fc.getItem();
    
    Account cuenta = new Account();
    fc.setcuenta(cuenta);
    cuenta=fc.getcuenta();
    
    Product2 pro = new Product2();
    fc.setpro(pro);
    pro=fc.getpro();
    
    String a = fc.getVerDetalles(); 
    
    fc.getFacturar();

    boolean bln = fc.getVerDetallesDisabled();
    
    fc.CrearFacturas();
    
    fc.SelectAll();
    fc.QuitarSeleccion();
    
    fc.setMensaje(a);
    a=fc.getMensaje();
            
    Facturar_Controller.Opor op = new Facturar_Controller.Opor();
    op.oport=o;
    op.selected=true;        
    
    fc.listaOpp.add(op);
    
    List<Facturar_Controller.Opor> lop = new List<Facturar_Controller.Opor>();
    
    lop=fc.getlistaopp();
    fc.setlistaopp(lop);
    
    fc = new Facturar_Controller();
    
    c.Tipo_de_Cota_o__c='SOJA';
    c.Cotacao_de_soja__c='COAMO';
    fc.setContrato(c);
    fc.opp.safra__c='08/09';
    fc.pro.variedad__c='APOLO';
    
    Cotizacion_Soja__c cot_soja = new Cotizacion_Soja__c(Cotacao_de_soja__c='COAMO');
    insert cot_soja;
    fc.Buscar();

    fc.selectAll();
    String a1 = fc.getVerDetalles(); 

    fc.Fact_Param.Fecha_fijacion_T_de_cambio__c=System.today();    
    fc.Fact_Param.Amount=1;
    fc.Fact_Param.Sucursal__c='0095 - Londrina';
    fc.Fact_Param.Tipo_de_cambio__c = 2;
    
    fc.listaOpp.add(op);
    
    fc.CrearFacturas();
    
    Account cu = New Account();
    cu.Name = 'prueba';
    insert cu;
    
    Contact con = New Contact();
    con.AccountId = cu.Id;
    con.LastName = 'prueba';
    insert con;
    
    Regiao__c re = New Regiao__c();
    re.Name = 'prueba';
    insert re;
    
    Estado__c est = New Estado__c();
    est.Name = 'prueba';
    insert est;
    
    sapStatusPedido sapstatus = New sapStatusPedido();
    sapStatusPedido.Bapiret2 sapstatusBapiret2 = New sapStatusPedido.Bapiret2();
    
    sapSoapFunctionsAnulMcS.Bapiret2 anul = New sapSoapFunctionsAnulMcS.Bapiret2();
    sapSoapFunctionsMcS.Bapiret2 functionsMcs = New sapSoapFunctionsMcS.Bapiret2();
    
    
    }
    
           
}