Salesforce/main/default/objects/Variedad_Datos_Complementares__c/Variedad_Datos_Complementares__c.object-meta.xml
<CustomObject>
    <label>Variedad - Datos Complementares</label>
    <nameField>
        <label>Dato Complementar</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Variedades - Datos Complementares</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/objects/Variedad_Datos_Complementares__c/fields/Tecnologia__c.field-meta.xml
<CustomField>
    <fullName>Tecnologia__c</fullName>
    <formula>TEXT( Variedad__r.Tecnologia__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tecnología</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/classes/VariedadDatosComplementaresController.cls
public with sharing class VariedadDatosComplementaresController extends CultivarsTechnicalInformation {

    /**
     * Retorna el total de registros de Variedad Datos Complementares según los filtros de Marca y Tecnología ingresados.
     */
    @AuraEnabled
    public static AggregateResult countDatosComplementares(String brand, String technology) {
        return countRecords('Variedad_Datos_Complementares__c',
            new List<List<String>>{
                new List<String>{'Marca__c', brand},
                new List<String>{'Tecnologia__c', technology}
            }
        );
    }

    @AuraEnabled
    public static List<Variedad_Datos_Complementares__c> getDatosComplementares(Integer queryLimit, Integer queryOffset, String brand, String technology) {
        return getData(Variedad_Datos_Complementares__c.SObjectType, queryLimit, queryOffset,
            new List<List<String>>{
                new List<String>{'Marca__c', brand},
                new List<String>{'Tecnologia__c', technology}
            }
        );
    }
}