Salesforce/main/default/main/default/objects/Opportunity/fields/Estado_Anexos_Portal_Miltiplicadores__c.field-meta.xml
<CustomField>
    <fullName>Estado_Anexos_Portal_Miltiplicadores__c</fullName>
    <formula>CASE(StageName, &quot;Edición&quot;, &quot;Edição&quot;, &quot;Edición post Vencimiento&quot;, &quot;Edición&quot;, &quot;Edición Vencida&quot;, &quot;Edición&quot;, &quot;Pendiente de Análisis&quot;, &quot;Bloqueado&quot;, &quot;Pendiente de Aprobación&quot;, &quot;Bloqueado&quot;, &quot;Desaprobado x Gerente&quot;, &quot;Rechazado&quot;, &quot;Rechazada Supervisor&quot;, &quot;Rechazado&quot;, &quot;Aprobada&quot;, &quot;Aprovado&quot;, &quot;AN - Anulada&quot;, &quot;Anulado&quot;, &quot;&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Fase</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/Opportunity/fields/Estado_de_produccion__c.field-meta.xml
<CustomField>
    <fullName>Estado_de_produccion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Estado de produccion, para incluir en el contrato de multiplicacion</description>
    <inlineHelpText>Estado de produccion, para incluir en el contrato de multiplicacion</inlineHelpText>
    <label>Estado de produccion</label>
    <referenceTo>Estado__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/Opportunity/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <description>Identifica la marca para las Oportunidades del Circuito de Anexos. Se selecciona la lista de precios en función de este campo</description>
    <inlineHelpText>Identificar a marca de Oportunidades Circuito Anexos. Você seleciona a lista de preços com base neste campo</inlineHelpText>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BRMX</fullName>
            </value>
            <value>
                <fullName>DSEM</fullName>
            </value>
            <value>
                <fullName>NEOG</fullName>
            </value>
            <value>
                <fullName>DAGMA</fullName>
            </value>
            <value>
                <fullName>LICENÇAS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Opportunity/fields/pdf_descarte__c.field-meta.xml
<CustomField>
    <fullName>pdf_descarte__c</fullName>
    <label>pdf_descarte</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/Opportunity/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <description>Safra o Campania agricola</description>
    <label>Safra</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>06/07</fullName>
            </value>
            <value>
                <fullName>07/08</fullName>
            </value>
            <value>
                <fullName>08/09</fullName>
            </value>
            <value>
                <fullName>09/10</fullName>
            </value>
            <value>
                <fullName>09/09</fullName>
            </value>
            <value>
                <fullName>10/10</fullName>
            </value>
            <value>
                <fullName>10/11</fullName>
            </value>
            <value>
                <fullName>11/11</fullName>
            </value>
            <value>
                <fullName>11/12</fullName>
            </value>
            <value>
                <fullName>12/12</fullName>
            </value>
            <value>
                <fullName>12/13</fullName>
            </value>
            <value>
                <fullName>13/14</fullName>
            </value>
            <value>
                <fullName>14/15</fullName>
            </value>
            <value>
                <fullName>15/16</fullName>
            </value>
            <value>
                <fullName>16/17</fullName>
            </value>
            <value>
                <fullName>17/18</fullName>
            </value>
            <value>
                <fullName>18/19</fullName>
            </value>
            <value>
                <fullName>19/20</fullName>
            </value>
            <value>
                <fullName>20/21</fullName>
            </value>
            <value>
                <fullName>21/22</fullName>
                <default>true</default>
                <label>21/22</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Opportunity/fields/tienePdf__c.field-meta.xml
<CustomField>
    <fullName>tienePdf__c</fullName>
    <defaultValue>false</defaultValue>
    <label>tienePdf</label>
    <type>Checkbox</type>
</CustomField>

Salesforce/main/default/objects/Opportunity/fields/VB_Recebeu__c.field-meta.xml
<CustomField>
    <fullName>VB_Recebeu__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Recibio el cto de multiplicacion es para la venta de basica</description>
    <label>Recebeu?</label>
    <type>Checkbox</type>
</CustomField>

Salesforce/main/default/main/default/objects/Opportunity/recordTypes/Reembalaje.recordType-meta.xml
<RecordType>
    <fullName>Reembalaje</fullName>
    <active>true</active>
    <businessProcess>Docusign - Anexos</businessProcess>
    <label>Reembalaje</label>
</RecordType>

Salesforce/main/default/objects/OpportunityLineItem/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Ha. Autorizados</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/objects/OpportunityLineItem/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Categoria a ser licenciada</description>
    <inlineHelpText>Categoria a ser licenciada</inlineHelpText>
    <label>Categoria</label>
    <referenceTo>Categoria__c</referenceTo>
    <relationshipLabel>Producto de oportunidad</relationshipLabel>
    <relationshipName>Producto_de_oportunidad</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/OpportunityLineItem/fields/Categoria_Prod__c.field-meta.xml
<CustomField>
    <fullName>Categoria_Prod__c</fullName>
    <formula>PricebookEntry.Product2.Categ__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Categoria</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/OpportunityLineItem/fields/Estado_de_Produccion__c.field-meta.xml
<CustomField>
    <fullName>Estado_de_Produccion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Estado de Produccion</label>
    <referenceTo>Estado__c</referenceTo>
    <relationshipLabel>Producto de oportunidad</relationshipLabel>
    <relationshipName>Producto_de_oportunidad</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/OpportunityLineItem/fields/Lote_Rebajado__c.field-meta.xml
<CustomField>
    <fullName>Lote_Rebajado__c</fullName>
    <label>Lote</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/OpportunityLineItem/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <formula>TEXT(Opportunity.Safra__c)</formula>
    <label>Safra</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/OpportunityLineItem/fields/UNIDADE__c.field-meta.xml
<CustomField>
    <fullName>UNIDADE__c</fullName>
    <formula>PricebookEntry.Product2.UNIDADE__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unidade</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/OpportunityLineItem/fields/Unidade_descarte__c.field-meta.xml
<CustomField>
    <fullName>Unidade_descarte__c</fullName>
    <label>Unidade descarte</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/OpportunityLineItem/fields/Variedad__c.field-meta.xml
<CustomField>
    <fullName>Variedad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Variedades que pueden incluirse en el contrato de multiplicacion</description>
    <inlineHelpText>Variedades que pueden incluirse en el contrato de multiplicacion</inlineHelpText>
    <label>Variedad</label>
    <referenceTo>Variedad__c</referenceTo>
    <relationshipLabel>Producto de oportunidad</relationshipLabel>
    <relationshipName>Producto_de_oportunidad</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/OpportunityLineItem/fields/Variedad_de_Produto__c.field-meta.xml
<CustomField>
    <fullName>Variedad_de_Produto__c</fullName>
    <formula>PricebookEntry.Product2.Variedade__r.Nombre_de_Registro__c</formula>
    <label>Registro Cultivar</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/OpportunityLineItem/fields/Variedade_Prod__c.field-meta.xml
<CustomField>
    <fullName>Variedade_Prod__c</fullName>
    <formula>PricebookEntry.Product2.Variedade__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Nome Comercial</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/Order/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Marca</valueSetName>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Order/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <label>Safra</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Safra</valueSetName>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Product2/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <label>Categoria</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BREEDER</fullName>
            </value>
            <value>
                <fullName>FUNDADORA</fullName>
            </value>
            <value>
                <fullName>Genetica</fullName>
            </value>
            <value>
                <fullName>Pre Basica</fullName>
            </value>
            <value>
                <fullName>BASICA</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>C1</fullName>
            </value>
            <value>
                <fullName>C2</fullName>
            </value>
            <value>
                <fullName>R</fullName>
            </value>
            <value>
                <fullName>S1</fullName>
            </value>
            <value>
                <fullName>S2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Product2/fields/UNIDADE__c.field-meta.xml
<CustomField>
    <fullName>UNIDADE__c</fullName>
    <label>UNIDADE</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/Product2/fields/Variedade__c.field-meta.xml
<CustomField>
    <fullName>Variedade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Variedade</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Variedad__c.Licenciada__c</field>
            <operation>equals</operation>
            <valueField>$Source.Licenciada__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Variedad__c</referenceTo>
    <relationshipLabel>Productos</relationshipLabel>
    <relationshipName>Productos</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Variedad__c/Variedad__c.object-meta.xml
<CustomObject>
    <description>Variedades, disponibles para incluir en los Contratos de Multiplicación</description>
    <label>Variedad</label>
    <nameField>
        <label>Nome Comercial</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Variedades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/Variedad__c/fields/Nombre_de_Registro__c.field-meta.xml
<CustomField>
    <fullName>Nombre_de_Registro__c</fullName>
    <externalId>true</externalId>
    <label>Nombre de Registro</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/globalValueSets/Marca.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BRMX</fullName>
    </customValue>
    <customValue>
        <fullName>DSEM</fullName>
    </customValue>
    <customValue>
        <fullName>NEOG</fullName>
    </customValue>
    <customValue>
        <fullName>DAGMA</fullName>
    </customValue>
    <customValue>
        <fullName>LICENÇAS</fullName>
    </customValue>
    <masterLabel>Marca</masterLabel>
</GlobalValueSet>

Salesforce/main/default/globalValueSets/Safra.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>14/15</fullName>
    </customValue>
    <customValue>
        <fullName>15/16</fullName>
    </customValue>
    <customValue>
        <fullName>16/17</fullName>
    </customValue>
    <customValue>
        <fullName>17/18</fullName>
    </customValue>
    <customValue>
        <fullName>18/19</fullName>
    </customValue>
    <customValue>
        <fullName>19/20</fullName>
    </customValue>
    <customValue>
        <fullName>20/21</fullName>
    </customValue>
    <customValue>
        <fullName>21/22</fullName>
    </customValue>
    <customValue>
        <fullName>22/23</fullName>
    </customValue>
    <customValue>
        <fullName>23/24</fullName>
    </customValue>
    <customValue>
        <fullName>08/09</fullName>
        <isActive>false</isActive>
        <label>08/09</label>
    </customValue>
    <customValue>
        <fullName>07/08</fullName>
        <isActive>false</isActive>
        <label>07/08</label>
    </customValue>
    <customValue>
        <fullName>10/11</fullName>
        <isActive>false</isActive>
        <label>10/11</label>
    </customValue>
    <customValue>
        <fullName>11/12</fullName>
        <isActive>false</isActive>
        <label>11/12</label>
    </customValue>
    <customValue>
        <fullName>12/13</fullName>
        <isActive>false</isActive>
        <label>12/13</label>
    </customValue>
    <customValue>
        <fullName>13/14</fullName>
        <isActive>false</isActive>
        <label>13/14</label>
    </customValue>
    <customValue>
        <fullName>09/10</fullName>
        <isActive>false</isActive>
        <label>09/10</label>
    </customValue>
    <masterLabel>Safra</masterLabel>
</GlobalValueSet>

Salesforce/main/default/classes/aSiteReembalagemControlerHelper.cls
public class aSiteReembalagemControlerHelper  {

     public static List<Opportunity> obtenerOportunidadesReembalaje(Id idCuenta, String safra, String marca) {
        List<Opportunity> queryResult = [
            SELECT Id, Name, Safra__c, Marca__c, CloseDate, pdf_descarte__c, tienePdf__c, VB_Recebeu__c,
			Estado_Anexos_Portal_Miltiplicadores__c, StageName
            FROM  Opportunity
            WHERE RecordType.DeveloperName = 'Reembalaje'
            AND Safra__c =: safra
            AND Marca__c =: marca
            AND Estado_Anexos_Portal_Miltiplicadores__c != 'Anulado'
			AND AccountId =: idCuenta
			ORDER BY CloseDate DESC
        ];
        return queryResult;
    }

	public static List<OpportunityLineItem> obtenerProductosOportunidad(Id oppId) {
        List<OpportunityLineItem> queryResult = [
            SELECT Id, PricebookEntry.Product2.Variedade__c,
            PricebookEntry.Product2.Variedade__r.Name, 
            PricebookEntry.Product2.Variedade__r.Nombre_de_Registro__c, 
            PricebookEntry.Product2.UNIDADE__c, Area__c, Estado_de_Produccion__r.Name,
            Categoria__r.Name, Quantity, Lote_Rebajado__c, 
            Categoria__c, Categoria_Prod__c, Unidade_descarte__c,
            UNIDADE__c, Variedade_Prod__c, Variedad_de_Produto__c
            FROM   OpportunityLineItem d
            WHERE  OpportunityId = :oppId
        ];
        return queryResult; 
    }


	public static void actualizarReembalagem(List<aAppendix.myOppItem> nuevosProductos, Id idOportunidad, String marca, String comentarioNuevaOportunidad, String paraAprobacion) {
		Opportunity OpportunityBeingUpdated = [
			SELECT Id, Comentarios__c, Pricebook2Id, OwnerId
			FROM Opportunity
			WHERE Id = :idOportunidad 
			LIMIT 1
		];
		Pricebook2 preciosOportunidad = [
			SELECT Id, Name
			FROM Pricebook2
			WHERE Id =: OpportunityBeingUpdated.Pricebook2Id
		];
        
		Map<String, PricebookEntry> royalPriceBook = Opp_Utils2.cargarPricebookEntries(preciosOportunidad.Name);
		String queryPlus = 'PricebookEntry.Product2.Variedade__c,'
			+ 'PricebookEntry.Product2.Variedade__r.Name,'
			+ 'PricebookEntry.Product2.Variedade__r.Nombre_de_Registro__c,'
			+ 'PricebookEntry.Product2.UNIDADE__c,'
			+ 'Categoria__r.Name';
                
		List<OpportunityLineItem> listOlisOfOppBeingEdited = aSiteUtils.queryResults1(
			OpportunityLineItem.SObjectType, queryPlus,
			'Opportunity.Id = :v1', idOportunidad
		);
                
		delete listOlisOfOppBeingEdited;
                
		List<OpportunityLineItem> itemsToBeAdded = new List<OpportunityLineItem>();
		for (aAppendix.myOppItem tmpItem : nuevosProductos) {
			OpportunityLineItem producto = aAppendix.myOppItem.armarLineItem(tmpItem);
			producto.PricebookEntryId = royalPriceBook.get(producto.Variedad__c).Id;
			producto.Lote_Rebajado__c = tmpItem.lote_rebajado;
			producto.OpportunityId = idOportunidad;
			itemsToBeAdded.add(producto);
		}
		insert itemsToBeAdded; 
                
		if (OpportunityBeingUpdated.Comentarios__c != comentarioNuevaOportunidad) {
			OpportunityBeingUpdated.Comentarios__c = comentarioNuevaOportunidad;
			update OpportunityBeingUpdated;
		}

		if(paraAprobacion == '1') {
			aAppManager.enviarParaAprobacion(OpportunityBeingUpdated);
		}
	}

	public static void crearReembalagem(String opportunityComentario, String activeMarca,
                                                                String activeAccountId, String activeSafra, 
                                                                SiteUser__c activeSiteUser, List<aAppendix.myOppItem> olisToBeAdded, String paraAprobacion) {

		Map<String, String> ListaRecordTypes = Opp_Utils2.cargarRecordTypesOportunidades(); 
        String reembalagemRecordTypeId = ListaRecordTypes.get('Reembalaje');
        Opportunity reembalagemOpportunity = new Opportunity();
		Pricebook2 listaStandard = [
			SELECT Id, Name
			FROM Pricebook2
			WHERE Name = 'Lista de precios estándar'
		];

        reembalagemOpportunity.Name = 'Reembalaje'; 
        reembalagemOpportunity.StageName = 'Edición';
        reembalagemOpportunity.RecordTypeId = reembalagemRecordTypeId;
        reembalagemOpportunity.AccountId = activeAccountId;
        reembalagemOpportunity.Safra__c = activeSafra;
        reembalagemOpportunity.Marca__c = activeMarca;
        reembalagemOpportunity.Usuario__c = activeSiteUser.Id;
        reembalagemOpportunity.CloseDate = System.today();
        reembalagemOpportunity.Comentarios__c = opportunityComentario;
		reembalagemOpportunity.Pricebook2Id = listaStandard.Id;

		insert reembalagemOpportunity;

		List<PricebookEntry> precioItem = [
			SELECT Id, Product2.Variedade__c
			FROM PricebookEntry
			WHERE Pricebook2.Name  =: listaStandard.Name
		];

		Map<String, PricebookEntry> mapaVariedadPrecio = new Map<String, PricebookEntry>();

		for(PricebookEntry precio : precioItem) {
			mapaVariedadPrecio.put(precio.Product2.Variedade__c, precio);
		}
		
		List<OpportunityLineItem> itemsToBeAdded = new List<OpportunityLineItem>();
		for (aAppendix.myOppItem tmpItem : olisToBeAdded) {
			OpportunityLineItem producto = aAppendix.myOppItem.armarLineItem(tmpItem);
			producto.PricebookEntryId = mapaVariedadPrecio.get(producto.Variedad__c).Id;
			producto.Lote_Rebajado__c = tmpItem.lote_rebajado;
			producto.OpportunityId = reembalagemOpportunity.id;
			itemsToBeAdded.add(producto);
		}
		insert itemsToBeAdded;
		if(paraAprobacion == '1') {
			aAppManager.enviarParaAprobacion(reembalagemOpportunity);
		}
	}
}