Salesforce/main/default/main/default/objects/Opportunity/fields/Estado_Anexos_Portal_Miltiplicadores__c.field-meta.xml
<CustomField>
    <fullName>Estado_Anexos_Portal_Miltiplicadores__c</fullName>
    <formula>CASE(StageName, &quot;Edición&quot;, &quot;Edição&quot;, &quot;Edición post Vencimiento&quot;, &quot;Edición&quot;, &quot;Edición Vencida&quot;, &quot;Edición&quot;, &quot;Pendiente de Análisis&quot;, &quot;Bloqueado&quot;, &quot;Pendiente de Aprobación&quot;, &quot;Bloqueado&quot;, &quot;Desaprobado x Gerente&quot;, &quot;Rechazado&quot;, &quot;Rechazada Supervisor&quot;, &quot;Rechazado&quot;, &quot;Aprobada&quot;, &quot;Aprovado&quot;, &quot;AN - Anulada&quot;, &quot;Anulado&quot;, &quot;&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Fase</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/Opportunity/fields/Estado_de_produccion__c.field-meta.xml
<CustomField>
    <fullName>Estado_de_produccion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Estado de produccion, para incluir en el contrato de multiplicacion</description>
    <inlineHelpText>Estado de produccion, para incluir en el contrato de multiplicacion</inlineHelpText>
    <label>Estado de produccion</label>
    <referenceTo>Estado__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/Opportunity/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <description>Identifica la marca para las Oportunidades del Circuito de Anexos. Se selecciona la lista de precios en función de este campo</description>
    <inlineHelpText>Identificar a marca de Oportunidades Circuito Anexos. Você seleciona a lista de preços com base neste campo</inlineHelpText>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BRMX</fullName>
            </value>
            <value>
                <fullName>DSEM</fullName>
            </value>
            <value>
                <fullName>NEOG</fullName>
            </value>
            <value>
                <fullName>DAGMA</fullName>
            </value>
            <value>
                <fullName>LICENÇAS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Opportunity/fields/pdf_descarte__c.field-meta.xml
<CustomField>
    <fullName>pdf_descarte__c</fullName>
    <label>pdf_descarte</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/Opportunity/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <description>Safra o Campania agricola</description>
    <label>Safra</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>06/07</fullName>
            </value>
            <value>
                <fullName>07/08</fullName>
            </value>
            <value>
                <fullName>08/09</fullName>
            </value>
            <value>
                <fullName>09/10</fullName>
            </value>
            <value>
                <fullName>09/09</fullName>
            </value>
            <value>
                <fullName>10/10</fullName>
            </value>
            <value>
                <fullName>10/11</fullName>
            </value>
            <value>
                <fullName>11/11</fullName>
            </value>
            <value>
                <fullName>11/12</fullName>
            </value>
            <value>
                <fullName>12/12</fullName>
            </value>
            <value>
                <fullName>12/13</fullName>
            </value>
            <value>
                <fullName>13/14</fullName>
            </value>
            <value>
                <fullName>14/15</fullName>
            </value>
            <value>
                <fullName>15/16</fullName>
            </value>
            <value>
                <fullName>16/17</fullName>
            </value>
            <value>
                <fullName>17/18</fullName>
            </value>
            <value>
                <fullName>18/19</fullName>
            </value>
            <value>
                <fullName>19/20</fullName>
            </value>
            <value>
                <fullName>20/21</fullName>
            </value>
            <value>
                <fullName>21/22</fullName>
                <default>true</default>
                <label>21/22</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Opportunity/fields/tienePdf__c.field-meta.xml
<CustomField>
    <fullName>tienePdf__c</fullName>
    <defaultValue>false</defaultValue>
    <label>tienePdf</label>
    <type>Checkbox</type>
</CustomField>

Salesforce/main/default/main/default/objects/Opportunity/fields/TipoReg__c.field-meta.xml
<CustomField>
    <fullName>TipoReg__c</fullName>
    <formula>CASE($RecordType.Name, &quot;Comercial&quot;, &quot;Comercial&quot;, &quot;Produccion&quot;, &quot;Produccion&quot;,&quot;Pendiente&quot;,&quot;AU - Comercial&quot;,&quot;Autorizada&quot;,&quot;AU - SAP&quot;,&quot;Rebaja&quot;,&quot;Rebaja&quot;,$RecordType.Name)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>TipoReg</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/Opportunity/fields/VB_Recebeu__c.field-meta.xml
<CustomField>
    <fullName>VB_Recebeu__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Recibio el cto de multiplicacion es para la venta de basica</description>
    <label>Recebeu?</label>
    <type>Checkbox</type>
</CustomField>

Salesforce/main/default/main/default/objects/Opportunity/recordTypes/AnexoII.recordType-meta.xml
<RecordType>
    <fullName>AnexoII</fullName>
    <active>true</active>
    <businessProcess>Circuito de Anexos</businessProcess>
    <description>Anexo II - Relatório de produção de sementes</description>
    <label>Anexo II</label>
</RecordType>

Salesforce/main/default/objects/Opportunity/recordTypes/Descarte.recordType-meta.xml
<RecordType>
    <fullName>Descarte</fullName>
    <active>true</active>
    <businessProcess>Circuito de Anexos</businessProcess>
    <label>Descarte</label>
</RecordType>

Salesforce/main/default/objects/OpportunityLineItem/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Ha. Autorizados</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/objects/OpportunityLineItem/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Categoria a ser licenciada</description>
    <inlineHelpText>Categoria a ser licenciada</inlineHelpText>
    <label>Categoria</label>
    <referenceTo>Categoria__c</referenceTo>
    <relationshipLabel>Producto de oportunidad</relationshipLabel>
    <relationshipName>Producto_de_oportunidad</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/OpportunityLineItem/fields/Categoria_Prod__c.field-meta.xml
<CustomField>
    <fullName>Categoria_Prod__c</fullName>
    <formula>PricebookEntry.Product2.Categ__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Categoria</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/OpportunityLineItem/fields/Estado_de_Produccion__c.field-meta.xml
<CustomField>
    <fullName>Estado_de_Produccion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Estado de Produccion</label>
    <referenceTo>Estado__c</referenceTo>
    <relationshipLabel>Producto de oportunidad</relationshipLabel>
    <relationshipName>Producto_de_oportunidad</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/OpportunityLineItem/fields/Lote_Rebajado__c.field-meta.xml
<CustomField>
    <fullName>Lote_Rebajado__c</fullName>
    <label>Lote</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/OpportunityLineItem/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <formula>TEXT(Opportunity.Safra__c)</formula>
    <label>Safra</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/OpportunityLineItem/fields/Semente_bruta__c.field-meta.xml
<CustomField>
    <fullName>Semente_bruta__c</fullName>
    <label>Sem. Bruta (Sacas)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/main/default/objects/OpportunityLineItem/fields/UNIDADE__c.field-meta.xml
<CustomField>
    <fullName>UNIDADE__c</fullName>
    <formula>PricebookEntry.Product2.UNIDADE__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unidade</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/OpportunityLineItem/fields/Unidade_descarte__c.field-meta.xml
<CustomField>
    <fullName>Unidade_descarte__c</fullName>
    <label>Unidade descarte</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/OpportunityLineItem/fields/Variedad__c.field-meta.xml
<CustomField>
    <fullName>Variedad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Variedades que pueden incluirse en el contrato de multiplicacion</description>
    <inlineHelpText>Variedades que pueden incluirse en el contrato de multiplicacion</inlineHelpText>
    <label>Variedad</label>
    <referenceTo>Variedad__c</referenceTo>
    <relationshipLabel>Producto de oportunidad</relationshipLabel>
    <relationshipName>Producto_de_oportunidad</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/OpportunityLineItem/fields/Variedad_de_Produto__c.field-meta.xml
<CustomField>
    <fullName>Variedad_de_Produto__c</fullName>
    <formula>PricebookEntry.Product2.Variedade__r.Nombre_de_Registro__c</formula>
    <label>Registro Cultivar</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/OpportunityLineItem/fields/Variedade_Prod__c.field-meta.xml
<CustomField>
    <fullName>Variedade_Prod__c</fullName>
    <formula>PricebookEntry.Product2.Variedade__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Nome Comercial</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/Order/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Marca</valueSetName>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Order/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <label>Safra</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Safra</valueSetName>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Product2/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <label>Categoria</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BREEDER</fullName>
            </value>
            <value>
                <fullName>FUNDADORA</fullName>
            </value>
            <value>
                <fullName>Genetica</fullName>
            </value>
            <value>
                <fullName>Pre Basica</fullName>
            </value>
            <value>
                <fullName>BASICA</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>C1</fullName>
            </value>
            <value>
                <fullName>C2</fullName>
            </value>
            <value>
                <fullName>R</fullName>
            </value>
            <value>
                <fullName>S1</fullName>
            </value>
            <value>
                <fullName>S2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Product2/fields/UNIDADE__c.field-meta.xml
<CustomField>
    <fullName>UNIDADE__c</fullName>
    <label>UNIDADE</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/Product2/fields/Variedade__c.field-meta.xml
<CustomField>
    <fullName>Variedade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Variedade</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Variedad__c.Licenciada__c</field>
            <operation>equals</operation>
            <valueField>$Source.Licenciada__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Variedad__c</referenceTo>
    <relationshipLabel>Productos</relationshipLabel>
    <relationshipName>Productos</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Variedad__c/Variedad__c.object-meta.xml
<CustomObject>
    <description>Variedades, disponibles para incluir en los Contratos de Multiplicación</description>
    <label>Variedad</label>
    <nameField>
        <label>Nome Comercial</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Variedades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/Variedad__c/fields/Nombre_de_Registro__c.field-meta.xml
<CustomField>
    <fullName>Nombre_de_Registro__c</fullName>
    <externalId>true</externalId>
    <label>Nombre de Registro</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/globalValueSets/Marca.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BRMX</fullName>
    </customValue>
    <customValue>
        <fullName>DSEM</fullName>
    </customValue>
    <customValue>
        <fullName>NEOG</fullName>
    </customValue>
    <customValue>
        <fullName>DAGMA</fullName>
    </customValue>
    <customValue>
        <fullName>LICENÇAS</fullName>
    </customValue>
    <masterLabel>Marca</masterLabel>
</GlobalValueSet>

Salesforce/main/default/globalValueSets/Safra.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>14/15</fullName>
    </customValue>
    <customValue>
        <fullName>15/16</fullName>
    </customValue>
    <customValue>
        <fullName>16/17</fullName>
    </customValue>
    <customValue>
        <fullName>17/18</fullName>
    </customValue>
    <customValue>
        <fullName>18/19</fullName>
    </customValue>
    <customValue>
        <fullName>19/20</fullName>
    </customValue>
    <customValue>
        <fullName>20/21</fullName>
    </customValue>
    <customValue>
        <fullName>21/22</fullName>
    </customValue>
    <customValue>
        <fullName>22/23</fullName>
    </customValue>
    <customValue>
        <fullName>23/24</fullName>
    </customValue>
    <customValue>
        <fullName>08/09</fullName>
        <isActive>false</isActive>
        <label>08/09</label>
    </customValue>
    <customValue>
        <fullName>07/08</fullName>
        <isActive>false</isActive>
        <label>07/08</label>
    </customValue>
    <customValue>
        <fullName>10/11</fullName>
        <isActive>false</isActive>
        <label>10/11</label>
    </customValue>
    <customValue>
        <fullName>11/12</fullName>
        <isActive>false</isActive>
        <label>11/12</label>
    </customValue>
    <customValue>
        <fullName>12/13</fullName>
        <isActive>false</isActive>
        <label>12/13</label>
    </customValue>
    <customValue>
        <fullName>13/14</fullName>
        <isActive>false</isActive>
        <label>13/14</label>
    </customValue>
    <customValue>
        <fullName>09/10</fullName>
        <isActive>false</isActive>
        <label>09/10</label>
    </customValue>
    <masterLabel>Safra</masterLabel>
</GlobalValueSet>

Salesforce/main/default/main/default/classes/ManejadorDescarte.cls
public class ManejadorDescarte extends ManejadorProductos  {



	/**
	* @author 
		Gaston Doval
	* @description 
		Recorre cada una de las listas de OpportunityLineItems de los distintos tipos de Oportunidad y, por cada uno, calcula el stock disponible 
		según la Variedad y Categoría de cada Producto. Retorna un Map donde la primer key es el tipo de Variedad y el valor otro Map, donde se guarda
		la Categoría (key) y el volumen total disponible (value). Los volumenes son multiplican por 40 dado que esa es la unidad en la que están cargados
		los Productos (1 bolsa = 40 Kg), con la excepcion de los Productos de las Oportunidades de tipo Descarte.
	*/ 
	
	public Map<String, Map<String, Decimal>> calcularVolumenDisponible() {
		List<OpportunityLineItem> productosAnexoII = new List<OpportunityLineItem>();
		List<OpportunityLineItem> productosAnexoIIRebaja = new List<OpportunityLineItem>();
		List<OpportunityLineItem> productosDescarte = new List<OpportunityLineItem>();

		Map<String, Map<String, Decimal>> mapaVolumenDisponible = new Map<String, Map<String, Decimal>>();
		for(OpportunityLineItem producto : this.listaProductos) {
			System.debug( producto);
			if(producto.Opportunity.TipoReg__c == 'Descarte') {
				productosDescarte.add(producto);
			}
			if(producto.Opportunity.TipoReg__c == 'Anexo II') {
				productosAnexoII.add(producto);
			}
			if(producto.Opportunity.TipoReg__c == 'Anexo II Rebaixamento Sacas') {
				productosAnexoIIRebaja.add(producto);
			}
		}

		for(OpportunityLineItem anexoII : productosAnexoII) {
			String variedadId = String.valueOf(anexoII.PricebookEntry.Product2.Variedade__c);
			if(!mapaVolumenDisponible.containsKey(variedadId)) {
                Map<String, Decimal> tmpMapCategoriaAmount = new Map<String, Decimal>();
                String tmpCategoria = String.valueOf(anexoII.Categoria__c);
				Decimal tmpAmount = 0;
				if(anexoII.Semente_bruta__c != null) {
					  tmpAmount = anexoII.Semente_bruta__c * 40; 
				}
                tmpMapCategoriaAmount.put(tmpCategoria, tmpAmount);
				mapaVolumenDisponible.put(variedadId, tmpMapCategoriaAmount);

			} else { 
				if(!mapaVolumenDisponible.get(variedadId).containsKey(anexoII.Categoria__c)) {
					Map<String, Decimal> tmpMapCategoriaAmount = mapaVolumenDisponible.get(variedadId);
					String tmpCategoria = String.valueOf(anexoII.Categoria__c);
					Decimal tmpAmount = 0;
					if(anexoII.Semente_bruta__c != null) {
							tmpAmount = anexoII.Semente_bruta__c * 40;
					}
					tmpMapCategoriaAmount.put(tmpCategoria, tmpAmount);
				}else {
					Map<String, Decimal> tmpMapCategoriaAmount = mapaVolumenDisponible.get(variedadId);
					String tmpCategoria = String.valueOf(anexoII.Categoria__c);
					Decimal tmpAmount = tmpMapCategoriaAmount.get(tmpCategoria);
					if(anexoII.Semente_bruta__c != null) {
						tmpAmount += anexoII.Semente_bruta__c * 40;
					}
					tmpMapCategoriaAmount.put(tmpCategoria, tmpAmount);
				}
			}
		}

		this.procesarProductosAnexoIIRebaxa(mapaVolumenDisponible, productosAnexoIIRebaja);

		this.procesarProductosDescarte(mapaVolumenDisponible, productosDescarte);

		return mapaVolumenDisponible;
	}

    public  List<Opportunity> obtenerOportunidadesDescarte(Id idCuenta, String safra, String marca) {
        List<Opportunity> queryResult = [
            SELECT Id, Name, Safra__c, Marca__c, StageName,
            CloseDate, Estado_Anexos_Portal_Miltiplicadores__c, pdf_descarte__c, tienePdf__c, VB_Recebeu__c
            FROM  Opportunity
            WHERE AccountId = :idCuenta
            AND RecordType.DeveloperName = 'Descarte'
            AND Safra__c = :safra
            AND Marca__c = :marca
            AND Estado_Anexos_Portal_Miltiplicadores__c != 'Anulado'
			ORDER BY CloseDate DESC
        ];
        return queryResult;
    }

    public  List<OpportunityLineItem> obtenerProductosOportunidad(Id oppId) {
        List<OpportunityLineItem> queryResult = [
            SELECT Id, PricebookEntry.Product2.Variedade__c,
            PricebookEntry.Product2.Variedade__r.Name, 
            PricebookEntry.Product2.Variedade__r.Nombre_de_Registro__c, 
            PricebookEntry.Product2.UNIDADE__c, Area__c, Estado_de_Produccion__r.Name,
            Categoria__r.Name, Quantity, Lote_Rebajado__c, 
            Categoria__c, Categoria_Prod__c, Unidade_descarte__c,
            UNIDADE__c, Variedade_Prod__c, Variedad_de_Produto__c
            FROM   OpportunityLineItem d
            WHERE  OpportunityId = :oppId
        ];
        return queryResult; 
    }




    public void crearDescarte(String toApproval, String idOppBeingEdited,
                                     List<aAppendix.myOppItem> olisToBeAdded,
                                     String opportunityComentario, String activeMarca, 
                                     String activeAccountId, String activeSafra, SiteUser__c activeSiteUser,
									 List<aAppendix.myOppItem> listaProductosParaEliminar) {
                                         
        String lista = 'Lista Canal Multiplicadores';
                                         
        if (activeMarca == 'DSEM') {
            lista = 'Lista DSEM';
        }   

        Map<String, PricebookEntry> royalPriceBook = Opp_Utils2.cargarRoyaltyPricebookEntries(lista);
        
        if (toApproval == '1') {
            if (!String.isEmpty(idOppBeingEdited)) {
                Opportunity descarteOpportunityBeingUpdated = [
                    SELECT Id, Comentarios__c, OwnerId
                    FROM Opportunity
                    WHERE Id = :idOppBeingEdited 
                    LIMIT 1
                ];
                
                String queryPlus = 'PricebookEntry.Product2.Variedade__c,'
                    + 'PricebookEntry.Product2.Variedade__r.Name,'
                    + 'PricebookEntry.Product2.Variedade__r.Nombre_de_Registro__c,'
                    + 'PricebookEntry.Product2.UNIDADE__c,'
                    + 'Categoria__r.Name';
                
       			List<OpportunityLineItem> listOlisOfOppBeingEdited = aSiteUtils.queryResults1(
                    OpportunityLineItem.SObjectType, queryPlus,
                    'Opportunity.Id = :v1', idOppBeingEdited
                );
                
                delete listOlisOfOppBeingEdited;
                
                List<OpportunityLineItem> itemsToBeAdded = new List<OpportunityLineItem>();
                for (aAppendix.myOppItem tmpItem : olisToBeAdded) {
                    OpportunityLineItem newOli = new OpportunityLineItem();
                    newOli.Quantity = tmpItem.amount;
                    newOli.Categoria__c = tmpItem.categoria;
                    newOli.Variedad__c = tmpItem.variedad;

                    if (tmpItem.unidade == '1') {
                        newOli.Unidade_descarte__c = 'Quilograma';
                    }
                    if (tmpItem.unidade == '25') {
                        newOli.Unidade_descarte__c = 'Saca 25Kg';
                    }
                    if (tmpItem.unidade == '40') {
                        newOli.Unidade_descarte__c = 'Saca 40Kg';
                    }
                    if (tmpItem.unidade == '1000') {
                        newOli.Unidade_descarte__c = 'Tonelada';
                    }
                    newOli.PricebookEntryId = royalPricebook.get(tmpItem.variedad).id;
                    newOli.Lote_Rebajado__c = tmpItem.lote_rebajado;
                    newOli.OpportunityId = descarteOpportunityBeingUpdated.Id;
                    newOli.UnitPrice = 1;
                    itemsToBeAdded.add(newOli);
                }
                insert itemsToBeAdded; 
                
                if (descarteOpportunityBeingUpdated.Comentarios__c != opportunityComentario) {
                    descarteOpportunityBeingUpdated.Comentarios__c = opportunityComentario;
                    update descarteOpportunityBeingUpdated;
                }
                
                aAppManager.enviarParaAprobacion(descarteOpportunityBeingUpdated);
            }
            else {
                Opportunity newlyCreatedOpportunity = crearGuardarOportunidadDescarteEdicion(
                    opportunityComentario, activeMarca,
                    activeAccountId, activeSafra,
                    activeSiteUser
                );

                newlyCreatedOpportunity = [SELECT Id, OwnerId FROM Opportunity WHERE ID =: newlyCreatedOpportunity.Id];
                
				List<OpportunityLineItem> itemsToBeAdded = new List<OpportunityLineItem>();
                for (aAppendix.myOppItem tmpItem : olisToBeAdded) {
                    OpportunityLineItem newOli = new OpportunityLineItem();
                    newOli.Quantity = tmpItem.amount;
                    newOli.Categoria__c = tmpItem.categoria;
                    newOli.Variedad__c = tmpItem.variedad;
                    if (tmpItem.unidade == '1') {
                        newOli.Unidade_descarte__c = 'Quilograma';
                    }
                    if (tmpItem.unidade == '25') {
                        newOli.Unidade_descarte__c = 'Saca 25Kg';
                    }
                    if (tmpItem.unidade == '40') {
                        newOli.Unidade_descarte__c = 'Saca 40Kg';
                    }
                    if (tmpItem.unidade == '1000') {
                        newOli.Unidade_descarte__c = 'Tonelada';
                    }
                    newOli.PricebookEntryId = royalPricebook.get(tmpItem.variedad).id;
                    newOli.Lote_Rebajado__c = tmpItem.lote_rebajado;
                    newOli.OpportunityId = newlyCreatedOpportunity.Id;
                    newOli.UnitPrice = 1;
                    itemsToBeAdded.add(newOli);
                }
                insert itemsToBeAdded;  
                
                aAppManager.enviarParaAprobacion(newlyCreatedOpportunity);
            }         
        }
        else if (!String.isEmpty(idOppBeingEdited)) {
                Opportunity descarteOpportunityBeingUpdated = [
                    SELECT Id, Comentarios__c 
                    FROM Opportunity
                    WHERE Id = :idOppBeingEdited 
                    LIMIT 1
                ];
                String queryPlus = 'PricebookEntry.Product2.Variedade__c, PricebookEntry.Product2.Variedade__r.Name,'
                    + 'PricebookEntry.Product2.Variedade__r.Nombre_de_Registro__c,'
                    + 'PricebookEntry.Product2.UNIDADE__c, Categoria__r.Name';
                
       			List<OpportunityLineItem> listOlisOfOppBeingEdited = aSiteUtils.queryResults1(
                    OpportunityLineItem.SObjectType, queryPlus, 
                    'Opportunity.Id = :v1', idOppBeingEdited
                );
                delete listOlisOfOppBeingEdited;
                
                List<OpportunityLineItem> itemsToBeAdded = new List<OpportunityLineItem>();
                for (aAppendix.myOppItem tmpItem : olisToBeAdded) {
                    OpportunityLineItem newOli = new OpportunityLineItem();
                    newOli.Quantity = tmpItem.amount;
					newOli.Variedad__c = tmpItem.variedad;// Agregado Nuevo
                    newOli.Categoria__c = tmpItem.categoria;
                    
                    if (tmpItem.unidade == '1') {
                        newOli.Unidade_descarte__c = 'Quilograma';
                    }
                    
                    if (tmpItem.unidade == '25') {
                        newOli.Unidade_descarte__c = 'Saca 25Kg';
                    }
                    if (tmpItem.unidade == '40') {
                        newOli.Unidade_descarte__c = 'Saca 40Kg';
                    }
                    if (tmpItem.unidade == '1000') {
                        newOli.Unidade_descarte__c = 'Tonelada';
                    }
                    newOli.PricebookEntryId = royalPricebook.get(tmpItem.variedad).id;
                    newOli.Lote_Rebajado__c = tmpItem.lote_rebajado;
                    newOli.OpportunityId = descarteOpportunityBeingUpdated.Id;
                    newOli.UnitPrice = 1;
                    itemsToBeAdded.add(newOli);
                }
                insert itemsToBeAdded; 
                
                if (descarteOpportunityBeingUpdated.Comentarios__c != opportunityComentario) {
                    descarteOpportunityBeingUpdated.Comentarios__c = opportunityComentario;
                    update descarteOpportunityBeingUpdated;
                }
                
            } 
            else {
                Opportunity newlyCreatedOpportunity = crearGuardarOportunidadDescarteEdicion(
                    opportunityComentario, activeMarca, 
                    activeAccountId, activeSafra, 
                    activeSiteUser
                );
                    
                List<OpportunityLineItem> itemsToBeAdded = new List<OpportunityLineItem>();
                for (aAppendix.myOppItem tmpItem : olisToBeAdded) {
                    OpportunityLineItem newOli = new OpportunityLineItem();
                    newOli.Quantity = tmpItem.amount;
                    newOli.Variedad__c = tmpItem.variedad; // Agregado para Bug 18911
                    newOli.Categoria__c = tmpItem.categoria;
                    
                    if (tmpItem.unidade == '1') {
                        newOli.Unidade_descarte__c = 'Quilograma';
                    }
                    if (tmpItem.unidade == '25') {
                        newOli.Unidade_descarte__c = 'Saca 25Kg';
                    }
                    if (tmpItem.unidade == '40') {
                        newOli.Unidade_descarte__c = 'Saca 40Kg';
                    }
                    if (tmpItem.unidade == '1000') {
                        newOli.Unidade_descarte__c = 'Tonelada';
                    }
                    newOli.PricebookEntryId = royalPricebook.get(tmpItem.variedad).id;
                    newOli.Lote_Rebajado__c = tmpItem.lote_rebajado;
                    newOli.OpportunityId = newlyCreatedOpportunity.id;
                    newOli.UnitPrice = 1;
                    itemsToBeAdded.add(newOli);
                }
                insert itemsToBeAdded; 
            }

			List<Id> idsParaEliminar =new List<Id>();
			for(aAppendix.myOppItem oppItem : listaProductosParaEliminar) {
				idsParaEliminar.add(oppItem.id);
			}
			List<OpportunityLineItem> itemsParaEliminar = [
				SELECT Id
				FROM OpportunityLineItem
				WHERE ID IN :idsParaEliminar
			];
			Database.delete(itemsParaEliminar, false);
        }
    
    public Opportunity crearGuardarOportunidadDescarteEdicion(String opportunityComentario, String activeMarca,
                                                                String activeAccountId, String activeSafra, 
                                                                SiteUser__c activeSiteUser) { 
                                                                    
        Map<String, String> descarteRecordTypes = Opp_Utils2.cargarRecordTypesOportunidades(); 
        String descarteRecordTypeId = descarteRecordTypes.get('Descarte');
        
		String correoSiteUser = [
			SELECT Email__c 
			FROM SiteUser__c 
			WHERE Id =: activeSiteUser.id 
			LIMIT 1
		].Email__c;

        Opportunity descarteOpportunity = new Opportunity();
        descarteOpportunity.Name = 'DESCARTE';
        descarteOpportunity.StageName = 'Edición';
        descarteOpportunity.RecordTypeId = descarteRecordTypeId;
        descarteOpportunity.AccountId = activeAccountId;
        descarteOpportunity.Safra__c = activeSafra;
        descarteOpportunity.Marca__c = activeMarca;
        descarteOpportunity.Usuario__c = activeSiteUser.Id;
        descarteOpportunity.CloseDate = System.today();
        descarteOpportunity.Comentarios__c = opportunityComentario;
        descarteOpportunity.CorreoElectronicoSiteUser__c = correoSiteUser;
		                 
        insert descarteOpportunity;
        return descarteOpportunity;  
    }
}