Salesforce/main/default/objects/CRM_Multiplicador__c/CRM_Multiplicador__c.object-meta.xml
<CustomObject>
    <description>Información del perfil del Multiplicador</description>
    <label>CRM Multiplicador</label>
    <nameField>
        <label>Nombre de CRM Multiplicador</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CRM Multiplicador</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Salesforce/main/default/objects/CRM_Multiplicador__c/fields/BR_Estim_Cumple_CRM__c.field-meta.xml
<CustomField>
    <fullName>BR_Estim_Cumple_CRM__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Estim Cumple CRM</label>
    <type>Checkbox</type>
</CustomField>

Salesforce/main/default/objects/CRM_Multiplicador__c/fields/BR_Estim_Cumple_Emplacamentos__c.field-meta.xml
<CustomField>
    <fullName>BR_Estim_Cumple_Emplacamentos__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Estim Cumple Emplacamentos</label>
    <type>Checkbox</type>
</CustomField>

Salesforce/main/default/objects/CRM_Multiplicador__c/fields/BR_Estim_Cumple_LxL__c.field-meta.xml
<CustomField>
    <fullName>BR_Estim_Cumple_LxL__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Estim Cumple LxL</label>
    <type>Checkbox</type>
</CustomField>

Salesforce/main/default/objects/CRM_Multiplicador__c/fields/BR_Estim_Cumple_Palestras_Treinamentos__c.field-meta.xml
<CustomField>
    <fullName>BR_Estim_Cumple_Palestras_Treinamentos__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Estim Cumple Palestras e Treinamentos</label>
    <type>Checkbox</type>
</CustomField>

Salesforce/main/default/main/default/objects/CRM_Multiplicador__c/fields/BR_Estim_Cumple_Stock_Mult__c.field-meta.xml
<CustomField>
    <fullName>BR_Estim_Cumple_Stock_Mult__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Estim Cumple Stock Mult</label>
    <type>Checkbox</type>
</CustomField>

Salesforce/main/default/main/default/objects/CRM_Multiplicador__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>CRM Multiplicador</relationshipLabel>
    <relationshipName>CRM_Multiplicador</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/CRM_Multiplicador__c/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <label>Safra</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>11/12</fullName>
            </value>
            <value>
                <fullName>12/13</fullName>
            </value>
            <value>
                <fullName>13/14</fullName>
            </value>
            <value>
                <fullName>14/15</fullName>
            </value>
            <value>
                <fullName>15/16</fullName>
            </value>
            <value>
                <fullName>17/18</fullName>
            </value>
            <value>
                <fullName>16/17</fullName>
            </value>
            <value>
                <fullName>18/19</fullName>
            </value>
            <value>
                <fullName>19/20</fullName>
            </value>
            <value>
                <fullName>20/21</fullName>
            </value>
            <value>
                <fullName>21/22</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Opportunity/fields/Activa__c.field-meta.xml
<CustomField>
    <fullName>Activa__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Activa</label>
    <type>Checkbox</type>
</CustomField>

Salesforce/main/default/main/default/objects/Opportunity/fields/CRM_Multiplicador__c.field-meta.xml
<CustomField>
    <fullName>CRM_Multiplicador__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CRM Multiplicador</label>
    <referenceTo>CRM_Multiplicador__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/Opportunity/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <description>Identifica la marca para las Oportunidades del Circuito de Anexos. Se selecciona la lista de precios en función de este campo</description>
    <inlineHelpText>Identificar a marca de Oportunidades Circuito Anexos. Você seleciona a lista de preços com base neste campo</inlineHelpText>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BRMX</fullName>
            </value>
            <value>
                <fullName>DSEM</fullName>
            </value>
            <value>
                <fullName>NEOG</fullName>
            </value>
            <value>
                <fullName>DAGMA</fullName>
            </value>
            <value>
                <fullName>LICENÇAS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Opportunity/fields/Mes__c.field-meta.xml
<CustomField>
    <fullName>Mes__c</fullName>
    <description>Nombre del mes para identificar la oportunidad de control de stock.</description>
    <label>Mês</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Janeiro</fullName>
            </value>
            <value>
                <fullName>Fevereiro</fullName>
            </value>
            <value>
                <fullName>Março</fullName>
            </value>
            <value>
                <fullName>Abril</fullName>
            </value>
            <value>
                <fullName>Maio</fullName>
            </value>
            <value>
                <fullName>Junho</fullName>
            </value>
            <value>
                <fullName>Julho</fullName>
            </value>
            <value>
                <fullName>Agosto</fullName>
            </value>
            <value>
                <fullName>Setembro</fullName>
            </value>
            <value>
                <fullName>Outubro</fullName>
            </value>
            <value>
                <fullName>Novembro</fullName>
            </value>
            <value>
                <fullName>Dezembro</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Opportunity/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <description>Safra o Campania agricola</description>
    <label>Safra</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>06/07</fullName>
            </value>
            <value>
                <fullName>07/08</fullName>
            </value>
            <value>
                <fullName>08/09</fullName>
            </value>
            <value>
                <fullName>09/10</fullName>
            </value>
            <value>
                <fullName>09/09</fullName>
            </value>
            <value>
                <fullName>10/10</fullName>
            </value>
            <value>
                <fullName>10/11</fullName>
            </value>
            <value>
                <fullName>11/11</fullName>
            </value>
            <value>
                <fullName>11/12</fullName>
            </value>
            <value>
                <fullName>12/12</fullName>
            </value>
            <value>
                <fullName>12/13</fullName>
            </value>
            <value>
                <fullName>13/14</fullName>
            </value>
            <value>
                <fullName>14/15</fullName>
            </value>
            <value>
                <fullName>15/16</fullName>
            </value>
            <value>
                <fullName>16/17</fullName>
            </value>
            <value>
                <fullName>17/18</fullName>
            </value>
            <value>
                <fullName>18/19</fullName>
            </value>
            <value>
                <fullName>19/20</fullName>
            </value>
            <value>
                <fullName>20/21</fullName>
            </value>
            <value>
                <fullName>21/22</fullName>
                <default>true</default>
                <label>21/22</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/OpportunityLineItem/fields/Estimativa__c.field-meta.xml
<CustomField>
    <fullName>Estimativa__c</fullName>
    <description>Oferta VS Demanda. Se carga el campo ZR_PLEMVA q viene del WS de oferta de PI.</description>
    <label>Estimativa</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/objects/OpportunityLineItem/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <formula>TEXT(Opportunity.Safra__c)</formula>
    <label>Safra</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/OpportunityLineItem/fields/Tipo_Registro__c.field-meta.xml
<CustomField>
    <fullName>Tipo_Registro__c</fullName>
    <label>Tipo Registro</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/classes/CSVCreator.cls
public class CSVCreator  {

    public Opportunity opp = New Opportunity();

    private static List<String> separateCommas(String input){
        List<String> results = input.split(';');

        for(String result : results) {
            result = result.trim();
        }

        return results;
    }

    @AuraEnabled
    public static CSVObject getCSVObject(String csv_str) {
        List<String> lines_raw = csv_str.split('\n');
        List<String> headers_raw = separateCommas(lines_raw[0]);
        List<List<String>> lines = new List<List<String>>();
        List<CSVHeader> headers = new List<CSVHeader>();

        lines_raw.remove(0);

        //Handling fields with commas

        for(String line : lines_raw) {
            List<String> line_sep = separateCommas(line);
            List<String> fields = new List<String>();
            Boolean makeCompositeField = false;
            String compositeField;
            for(String field : line_sep) {
                if (field.startsWith('"') && field.endsWith('"')) {
                    fields.add(field.trim());
                } else if (field.startsWith('"')) {
                    makeCompositeField = true;
                    compositeField = field;
                } else if (field.endsWith('"')) {
                    compositeField += ',' + field;
                    fields.add(compositeField.trim());
                    makeCompositeField = false;
                } else if (makeCompositeField) {
                    compositeField +=  ',' + field;
                } else {
                    fields.add(field.trim());
                }
            }
            lines.add(fields);
        }

        for(String header : headers_raw) {
            headers.add(new CSVHeader(header));
        }

        return new CSVObject(headers, lines);        
    }
    
    @AuraEnabled
    public static String crearEstimativas(String jsonString, String safra, String mes) {
    
        //return 'a';
        
        Savepoint sp = Database.setSavepoint();
                
        try{
        
            CSVObject csv_obj = (CSVObject)JSON.deserialize(jsonString, CSVObject.class);
            safra = safra.replace('"','');
            mes = mes.replace('"','');

            for (List<String> s : csv_obj.lines){
                if (s[8] == null || s[8] == '' || s[9] == null || s[9] == '')
                    return 'Algumas contas e / ou variedades não foram encontradas.';
            }
            
            Map<String,PricebookEntry> rPb = Opp_Utils.cargarRoyaltyPricebookEntries('Lista Canal Multiplicadores');
            Map<String, Id> rty = Opp_Utils.cargarRecordTypesOportunidades();
            String rt_Estim = rty.get('Estimativa de faturamento');  
            
            Map<String,Opportunity> mapOpps = new Map<String,Opportunity>();                  
        
            /*
            List<Opportunity> registrosActuales = New List<Opportunity>();
            registrosActuales = [Select Id From Opportunity Where RecordType.Name = 'Estimativa de faturamento' And Safra__c =: safra And Mes__c =: mes];
            if (registrosActuales.size() > 0)
                delete registrosActuales;
                
                            
            List<Opportunity> registrosActivos = New List<Opportunity>();
            registrosActivos = [Select Id, Activa__c From Opportunity Where RecordType.Name = 'Estimativa de faturamento' And Safra__c =: safra And Activa__c = true];
            if (registrosActivos.size() > 0){
                for (Opportunity o: registrosActivos)
                    o.Activa__c = false;
                    
                update registrosActivos;
            }
            */
            
            List<Opportunity> createOpps = new List<Opportunity>();
            for (List<String> s : csv_obj.lines){
                String oppUnique = String.valueOf(s[0]);
                Opportunity o = mapOpps.get(oppUnique);
                if (o == null){                    
                    o = new Opportunity();
                    o.Name = 'TMP';
                    o.Stagename = 'Aprobada'; 
                    o.CloseDate = System.today(); 
                    o.RecordTypeId = rt_Estim; 
                    o.AccountId = String.valueOf(s[0]); 
                    o.Safra__c = safra; 
                    o.Marca__c = 'BRMX'; 
                    o.Mes__c = mes; 
                    o.Activa__c = true;
                    createOpps.add(o);
                    mapOpps.put(oppUnique, o);
                }                                    
            }
            
            insert createOpps;
            
            List<OpportunityLineItem> items = new List<OpportunityLineItem>();
            for (List<String> s : csv_obj.lines){
                String oppUnique = String.valueOf(s[0]);
                Opportunity o = mapOpps.get(oppUnique);
                OpportunityLineItem i = new OpportunityLineItem();
                i.opportunityId = o.id;
                i.quantity = Double.valueOf(s[2]);
                i.Estimativa__c = Double.valueOf(s[2]);
                i.pricebookentryid = rpb.get(String.valueOf(s[1])).Id;
                i.unitprice = 0.01;      
                i.Tipo_Registro__c = 'Estimativa de faturamento';          
                items.add(i);                                     
            }
            
            insert items;
            
            Map<String, CRM_Multiplicador__c> mapMultCRM = New Map<String, CRM_Multiplicador__c>();
            for (CRM_Multiplicador__c crm : [Select Id, Cuenta__c, BR_Estim_Cumple_CRM__c, BR_Estim_Cumple_Emplacamentos__c, BR_Estim_Cumple_LxL__c, BR_Estim_Cumple_Palestras_Treinamentos__c, BR_Estim_Cumple_Stock_Mult__c From CRM_Multiplicador__c Where Safra__c =: safra])
                mapMultCRM.put(crm.Cuenta__c, crm);
                
            for (List<String> s : csv_obj.lines){
                if (mapMultCRM.containsKey(String.valueOf(s[0]))){
                    CRM_Multiplicador__c crm2 = mapMultCRM.get(String.valueOf(s[0]));
                    crm2.BR_Estim_Cumple_LxL__c = false;
                    if (Integer.valueOf(s[3]) == 1)
                        crm2.BR_Estim_Cumple_LxL__c = true;
                    crm2.BR_Estim_Cumple_Emplacamentos__c = false;
                    if (Integer.valueOf(s[4]) == 1)
                        crm2.BR_Estim_Cumple_Emplacamentos__c = true;
                    crm2.BR_Estim_Cumple_Palestras_treinamentos__c = false;
                    if (Integer.valueOf(s[5]) == 1)
                        crm2.BR_Estim_Cumple_Palestras_treinamentos__c = true;
                    crm2.BR_Estim_Cumple_CRM__c = false;
                    if (Integer.valueOf(s[6]) == 1)
                        crm2.BR_Estim_Cumple_CRM__c = true;
                    crm2.BR_Estim_Cumple_Stock_Mult__c = false;
                    if (Integer.valueOf(s[7]) == 1)
                        crm2.BR_Estim_Cumple_Stock_Mult__c = true;
                }
            }
            
            if (mapMultCRM.size() > 0)
                update mapMultCRM.values();            
                            
         }catch(Exception e){  
            Database.rollback(sp);          
            return 'ERRO ' + e.getMessage() + e.getLineNumber();
         }
                
         return 'Dados importados com sucesso.';
        
    }

}