Salesforce/main/default/objects/Configuracion_BMX__c/Configuracion_BMX__c.object-meta.xml
<CustomObject>
    <description>Indicador de Parametros.</description>
    <label>Configuracion_BMX</label>
    <nameField>
        <label>Configuracion Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuraciones_BMX</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/Configuracion_BMX__c/fields/FC_Mandante_SAP__c.field-meta.xml
<CustomField>
    <fullName>FC_Mandante_SAP__c</fullName>
    <label>FC Mandante SAP</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/SAP_environment_variables__mdt/SAP_environment_variables__mdt.object-meta.xml
<CustomObject>
    <label>SAP_environment_variables</label>
    <pluralLabel>SAP_environment_variables</pluralLabel>
</CustomObject>

Salesforce/main/default/classes/Utils.cls
public with sharing class Utils {
    
    public static String getSAPCredentialsBase64Encoded() {

        SAP_environment_variables__mdt SAPEnviromentMtd = [
                SELECT
                Username__c,
                Password__c
            FROM
                SAP_environment_variables__mdt];

            String stringToBlob = SAPEnviromentMtd.Username__c + ':' + SAPEnviromentMtd.Password__c;
            Blob hash = Blob.valueOf(stringToBlob);
            String credentials = EncodingUtil.base64Encode(hash);

            return credentials;
    }

    public static String getSAPEnvTarget() {

        Configuracion_BMX__c configuracionBMX = [SELECT FC_Mandante_SAP__c FROM Configuracion_BMX__c LIMIT 1];

        return configuracionBMX.FC_Mandante_SAP__c;
    }

     /**
     *  METHOD:         getFieldValuesAura 
     *  PARAMETERS:     recordId: API Name of the object to query, 
     *                  fields: API Name of the fields to query, 
     *                  filter: WHERE clause condition (optional),
     *                  orderyBy: API Name of the field to Order by Asc
     *  DESCRIPTION:    Utility AuraEnabled method for queries
     *  AUTHOR:         irina.benitez@cloudgaia.com (26-ago-21)
     **/ 

    @AuraEnabled(cacheable=true)
    public static List<SObject> getFieldValuesAura(String recordId, List<String> fields, String filter, String orderBy) {
        return getFieldValues(recordId, fields, filter, orderBy);
    }


    /**
     *  METHOD:         getFieldValues 
     *  PARAMETERS:     recordId: API Name of the object to query, 
     *                  fields: API Name of the fields to query, 
     *                  filter: WHERE clause condition (optional),
     *                  orderyBy: API Name of the field to Order by Asc
     *  DESCRIPTION:    Utility method for queries
     *  AUTHOR:         irina.benitez@cloudgaia.com (26-ago-21)
     **/ 
    
    public static List<SObject> getFieldValues(String recordId, List<String> fields, String filter, String orderBy) {

        List<SObject> sObjList;
        String query = 'SELECT Id';

        for(String field : fields) {

            if( !query.contains(field) ) {

                query += ', ' + field;
            }
        }

        query += ' FROM ' + recordId;

        if(filter != null) {

            query += ' WHERE ' + filter;
        }

        if(orderBy != null) {

            query += ' ORDER BY ' + orderBy + ' ASC';
        }

        sObjList = Database.query(query);

        return sObjList;
    }
}