Salesforce/main/default/objects/Configuracion_BMX__c/Configuracion_BMX__c.object-meta.xml
<CustomObject>
    <description>Indicador de Parametros.</description>
    <label>Configuracion_BMX</label>
    <nameField>
        <label>Configuracion Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuraciones_BMX</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/Configuracion_BMX__c/fields/Londrina_Tasa_COFINS__c.field-meta.xml
<CustomField>
    <fullName>Londrina_Tasa_COFINS__c</fullName>
    <label>Londrina Tasa COFINS</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/objects/Configuracion_BMX__c/fields/Londrina_Tasa_ISS__c.field-meta.xml
<CustomField>
    <fullName>Londrina_Tasa_ISS__c</fullName>
    <label>Londrina Tasa ISS</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/main/default/objects/Configuracion_BMX__c/fields/Londrina_Tasa_PIS__c.field-meta.xml
<CustomField>
    <fullName>Londrina_Tasa_PIS__c</fullName>
    <label>Londrina Tasa PIS</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/main/default/objects/Configuracion_BMX__c/fields/Mes_Stock__c.field-meta.xml
<CustomField>
    <fullName>Mes_Stock__c</fullName>
    <label>Mes Stock</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Janeiro</fullName>
            </value>
            <value>
                <fullName>Fevereiro</fullName>
            </value>
            <value>
                <fullName>Março</fullName>
            </value>
            <value>
                <fullName>Abril</fullName>
            </value>
            <value>
                <fullName>Maio</fullName>
            </value>
            <value>
                <fullName>Junho</fullName>
            </value>
            <value>
                <fullName>Julho</fullName>
            </value>
            <value>
                <fullName>Agosto</fullName>
            </value>
            <value>
                <fullName>Setembro</fullName>
            </value>
            <value>
                <fullName>Outubro</fullName>
            </value>
            <value>
                <fullName>Novembro</fullName>
            </value>
            <value>
                <fullName>Dezembro</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Configuracion_BMX__c/fields/Passo_Fundo_Tasa_COFINS__c.field-meta.xml
<CustomField>
    <fullName>Passo_Fundo_Tasa_COFINS__c</fullName>
    <label>Passo Fundo Tasa COFINS</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/objects/Configuracion_BMX__c/fields/Passo_Fundo_Tasa_ISS__c.field-meta.xml
<CustomField>
    <fullName>Passo_Fundo_Tasa_ISS__c</fullName>
    <label>Passo Fundo Tasa ISS</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/main/default/objects/Configuracion_BMX__c/fields/Passo_Fundo_Tasa_PIS__c.field-meta.xml
<CustomField>
    <fullName>Passo_Fundo_Tasa_PIS__c</fullName>
    <label>Passo Fundo Tasa PIS</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/objects/Configuracion_BMX__c/fields/PM_Estoque_Dia_Desde__c.field-meta.xml
<CustomField>
    <fullName>PM_Estoque_Dia_Desde__c</fullName>
    <label>PM Estoque Dia Desde</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/objects/Configuracion_BMX__c/fields/PM_Estoque_Dia_Hasta__c.field-meta.xml
<CustomField>
    <fullName>PM_Estoque_Dia_Hasta__c</fullName>
    <label>PM Estoque Dia Hasta</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/main/default/objects/Configuracion_BMX__c/fields/PM_Safra_Actual__c.field-meta.xml
<CustomField>
    <fullName>PM_Safra_Actual__c</fullName>
    <label>PM Safra Actual</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/Configuracion_BMX__c/fields/PM_Safra_Actual_A1__c.field-meta.xml
<CustomField>
    <fullName>PM_Safra_Actual_A1__c</fullName>
    <label>PM Safra Actual A1</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/Configuracion_BMX__c/fields/PM_Safra_Actual_A2__c.field-meta.xml
<CustomField>
    <fullName>PM_Safra_Actual_A2__c</fullName>
    <label>PM Safra Actual A2</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/Configuracion_BMX__c/fields/PM_Safra_Actual_A3__c.field-meta.xml
<CustomField>
    <fullName>PM_Safra_Actual_A3__c</fullName>
    <label>PM Safra Actual A3</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/Configuracion_BMX__c/fields/PM_Safra_Actual_A4__c.field-meta.xml
<CustomField>
    <fullName>PM_Safra_Actual_A4__c</fullName>
    <label>PM Safra Actual A4</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/Configuracion_BMX__c/fields/PM_Safra_Actual_A5__c.field-meta.xml
<CustomField>
    <fullName>PM_Safra_Actual_A5__c</fullName>
    <label>PM Safra Actual A5</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/Configuracion_BMX__c/fields/PM_Safra_Actual_Contratos__c.field-meta.xml
<CustomField>
    <fullName>PM_Safra_Actual_Contratos__c</fullName>
    <label>PM Safra Actual Contratos</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/Configuracion_BMX__c/fields/PM_Safra_Actual_Descarte__c.field-meta.xml
<CustomField>
    <fullName>PM_Safra_Actual_Descarte__c</fullName>
    <label>PM Safra Actual Descarte</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/Configuracion_BMX__c/fields/PM_Safra_Actual_Estoque__c.field-meta.xml
<CustomField>
    <fullName>PM_Safra_Actual_Estoque__c</fullName>
    <label>PM Safra Actual Estoque</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/Configuracion_BMX__c/fields/PM_Safra_Actual_Eventos__c.field-meta.xml
<CustomField>
    <fullName>PM_Safra_Actual_Eventos__c</fullName>
    <label>PM Safra Actual Eventos</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/Configuracion_BMX__c/fields/PM_Safra_Actual_Reembalagem__c.field-meta.xml
<CustomField>
    <fullName>PM_Safra_Actual_Reembalagem__c</fullName>
    <label>PM Safra Actual Reembalagem</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/classes/DAOConfiguracionBMX.cls
public class DAOConfiguracionBMX {
    
    public static DAOIConfiguracionBMX getInstance(){
        return new DAOConfiguracionBMXWithSharing();
    }

    public static DAOIConfiguracionBMX getInstance(DTOUtils.SharingMode mode){
        switch on mode {
            when  with{
                return new DAOConfiguracionBMXWithSharing();
            }
            when without{
                return new DAOConfiguracionBMXWithoutSharing();
            }
            when inherit{
                return new DAOConfiguracionBMXInheritSharing();
            }
            when else {
                return new DAOConfiguracionBMXInheritSharing();                
            }
        }
    }

    //All methods must be declared here before implemented
    public interface DAOIConfiguracionBMX{
        Configuracion_BMX__c getFirst();
    }

    private with sharing class DAOConfiguracionBMXWithSharing implements DAOIConfiguracionBMX{
        DAOConfiguracionBMXInheritSharing base = new DAOConfiguracionBMXInheritSharing();

        public Configuracion_BMX__c getFirst(){
            return base.getFirst();
        }
    }
    private without sharing class DAOConfiguracionBMXWithoutSharing implements DAOIConfiguracionBMX{
        DAOConfiguracionBMXInheritSharing base = new DAOConfiguracionBMXInheritSharing();

        public Configuracion_BMX__c getFirst(){
            return base.getFirst();
        }
    }
    //This returns based on the parent sharing
    private inherited sharing class DAOConfiguracionBMXInheritSharing implements DAOIConfiguracionBMX{
        public Configuracion_BMX__c getFirst(){
            return [
                SELECT Id
                    ,Londrina_Tasa_COFINS__c
                    , Londrina_Tasa_ISS__c
                    , Londrina_Tasa_PIS__c
                    , Passo_Fundo_Tasa_COFINS__c
                    , Passo_Fundo_Tasa_ISS__c
                    , Passo_Fundo_Tasa_PIS__c
                    , PM_Safra_Actual__c
                    , PM_Safra_Actual_A1__c
                    , PM_Safra_Actual_A2__c
                    , PM_Safra_Actual_A3__c
                    , PM_Safra_Actual_A4__c
                    , PM_Safra_Actual_A5__c
                    , PM_Safra_Actual_Contratos__c
                    , PM_Safra_Actual_Descarte__c
                    , PM_Safra_Actual_Estoque__c
                    , PM_Safra_Actual_Eventos__c
                    , PM_Safra_Actual_Reembalagem__c
                    , PM_Estoque_Dia_Hasta__c 
                    , Mes_Stock__c 
                    , PM_Estoque_Dia_Desde__c 
                FROM Configuracion_BMX__c LIMIT 1
            ];
        }
        
    }    
}