Salesforce/main/default/objects/Configuracion_BMX__c/Configuracion_BMX__c.object-meta.xml
<CustomObject>
    <description>Indicador de Parametros.</description>
    <label>Configuracion_BMX</label>
    <nameField>
        <label>Configuracion Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuraciones_BMX</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/Configuracion_BMX__c/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BRMX</fullName>
                <default>true</default>
                <label>BRMX</label>
            </value>
            <value>
                <fullName>DSEM</fullName>
            </value>
            <value>
                <fullName>NEOG</fullName>
            </value>
            <value>
                <fullName>DAGMA</fullName>
            </value>
            <value>
                <fullName>LICENÇAS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Configuracion_BMX__c/fields/PM_Safra_Actual_VB_Estimativa_de_Compra__c.field-meta.xml
<CustomField>
    <fullName>PM_Safra_Actual_VB_Estimativa_de_Compra__c</fullName>
    <label>PM Safra Actual VB-Estimativa de Compra</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Safra</valueSetName>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Order/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Marca</valueSetName>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Order/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <label>Safra</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Safra</valueSetName>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Produto_de_Requisicao__c/Produto_de_Requisicao__c.object-meta.xml
<CustomObject>
    <label>Produto de Requisição</label>
    <nameField>
        <label>Nombre de Produto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Produtos de Requisição</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/Produto_de_Requisicao__c/fields/Multiplicador__c.field-meta.xml
<CustomField>
    <fullName>Multiplicador__c</fullName>
    <formula>Requisicao_de_compra__r.Multiplicador__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Multiplicador</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/Produto_de_Requisicao__c/fields/Requisicao_de_compra__c.field-meta.xml
<CustomField>
    <fullName>Requisicao_de_compra__c</fullName>
    <label>Requisição de compra</label>
    <referenceTo>Requisicao_de_compra__c</referenceTo>
    <relationshipLabel>Produtos de Requisição</relationshipLabel>
    <relationshipName>Produtos_de_Requisicao</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Salesforce/main/default/main/default/objects/Produto_de_Requisicao__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <formula>TEXT(Requisicao_de_compra__r.Tipo__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tipo</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/Produto_de_Requisicao__c/fields/Variedad__c.field-meta.xml
<CustomField>
    <fullName>Variedad__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Variedad</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1 AND 2</booleanFilter>
        <filterItems>
            <field>Variedad__c.Disponivel_para_venda_basica__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Variedad__c.Cultura__c</field>
            <operation>equals</operation>
            <value>MILHO</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Variedad__c</referenceTo>
    <relationshipLabel>Produtos de Requisição</relationshipLabel>
    <relationshipName>Produtos_de_Requisicao</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/Requisicao_de_compra__c/Requisicao_de_compra__c.object-meta.xml
<CustomObject>
    <label>Estimativas</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Número de requisito</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Estimativas</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Salesforce/main/default/objects/Requisicao_de_compra__c/fields/Cantidad_Productos__c.field-meta.xml
<CustomField>
    <fullName>Cantidad_Productos__c</fullName>
    <label>Cantidad Productos</label>
    <summaryForeignKey>Produto_de_Requisicao__c.Requisicao_de_compra__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

Salesforce/main/default/objects/Requisicao_de_compra__c/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BRMX</fullName>
            </value>
            <value>
                <fullName>DSEM</fullName>
            </value>
            <value>
                <fullName>NEOG</fullName>
            </value>
            <value>
                <fullName>DAGMA</fullName>
            </value>
            <value>
                <fullName>LICENÇAS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Requisicao_de_compra__c/fields/Multiplicador__c.field-meta.xml
<CustomField>
    <fullName>Multiplicador__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Multiplicador</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Requisitos_de_compra</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Requisicao_de_compra__c/fields/Regiao_comercial__c.field-meta.xml
<CustomField>
    <fullName>Regiao_comercial__c</fullName>
    <label>Região comercial</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BRASIL</fullName>
            </value>
            <value>
                <fullName>REGION 1</fullName>
            </value>
            <value>
                <fullName>REGION 2</fullName>
            </value>
            <value>
                <fullName>CERRADO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Requisicao_de_compra__c/fields/Requisicao_de_compra__c.field-meta.xml
<CustomField>
    <fullName>Requisicao_de_compra__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Número da Estimativa Subsequente</label>
    <referenceTo>Requisicao_de_compra__c</referenceTo>
    <relationshipName>Requisitos_de_compra</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/Requisicao_de_compra__c/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <label>Safra</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Safra</valueSetName>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Requisicao_de_compra__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Multiplicador</fullName>
            </value>
            <value>
                <fullName>Supervisor</fullName>
            </value>
            <value>
                <fullName>Gerente Comercial</fullName>
            </value>
            <value>
                <fullName>Gerente</fullName>
                <isActive>false</isActive>
                <label>Gerente</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Variedad__c/Variedad__c.object-meta.xml
<CustomObject>
    <description>Variedades, disponibles para incluir en los Contratos de Multiplicación</description>
    <label>Variedad</label>
    <nameField>
        <label>Nome Comercial</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Variedades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/globalValueSets/Marca.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BRMX</fullName>
    </customValue>
    <customValue>
        <fullName>DSEM</fullName>
    </customValue>
    <customValue>
        <fullName>NEOG</fullName>
    </customValue>
    <customValue>
        <fullName>DAGMA</fullName>
    </customValue>
    <customValue>
        <fullName>LICENÇAS</fullName>
    </customValue>
    <masterLabel>Marca</masterLabel>
</GlobalValueSet>

Salesforce/main/default/globalValueSets/Safra.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>14/15</fullName>
    </customValue>
    <customValue>
        <fullName>15/16</fullName>
    </customValue>
    <customValue>
        <fullName>16/17</fullName>
    </customValue>
    <customValue>
        <fullName>17/18</fullName>
    </customValue>
    <customValue>
        <fullName>18/19</fullName>
    </customValue>
    <customValue>
        <fullName>19/20</fullName>
    </customValue>
    <customValue>
        <fullName>20/21</fullName>
    </customValue>
    <customValue>
        <fullName>21/22</fullName>
    </customValue>
    <customValue>
        <fullName>22/23</fullName>
    </customValue>
    <customValue>
        <fullName>23/24</fullName>
    </customValue>
    <customValue>
        <fullName>08/09</fullName>
        <isActive>false</isActive>
        <label>08/09</label>
    </customValue>
    <customValue>
        <fullName>07/08</fullName>
        <isActive>false</isActive>
        <label>07/08</label>
    </customValue>
    <customValue>
        <fullName>10/11</fullName>
        <isActive>false</isActive>
        <label>10/11</label>
    </customValue>
    <customValue>
        <fullName>11/12</fullName>
        <isActive>false</isActive>
        <label>11/12</label>
    </customValue>
    <customValue>
        <fullName>12/13</fullName>
        <isActive>false</isActive>
        <label>12/13</label>
    </customValue>
    <customValue>
        <fullName>13/14</fullName>
        <isActive>false</isActive>
        <label>13/14</label>
    </customValue>
    <customValue>
        <fullName>09/10</fullName>
        <isActive>false</isActive>
        <label>09/10</label>
    </customValue>
    <masterLabel>Safra</masterLabel>
</GlobalValueSet>

Salesforce/main/default/classes/SalvarEstimativaAPI.cls
/**
* @name SalvarEstimativaAPI
* @author Jhonny Peroza
* updated 08-11-2021
*
* updated 04-jan-2022 pablo.fraquia@cloudgaia.com / Se le agrega un nuevo string al error message para aclarar el motivo del fallo en la llamada (from line 52 to 57)
*
* updated 25-jan-2022 pablo.fraquia@cloudgaia.com / Se cambia la logica de la API para que contemple los casos de editar e insertar una Requisicao_de_compra__c  (BUG 18829)
*/
@RestResource(urlMapping='/SalvarEstimativaAPI/*')
global with sharing class SalvarEstimativaAPI {

    @HttpPost
    global static void salvarEstimativa() {

        Response result = new Response();
        result.status = false;
		Savepoint savePoint = Database.setSavepoint(); 

        RestResponse response = RestContext.Response;
        response.headers.put('Content-Type', 'application/json');
        response.statusCode = 404;
            
        String requestString = RestContext.Request.requestBody.toString();
        Request requestParameters = (Request)JSON.deserialize(requestString, Request.class);

        String requisicaoId = requestParameters.requisicaoId;
        List<aSiteVendaDeBasicaController.ProductoRequisicion> items = requestParameters.items;
        List<aSiteVendaDeBasicaController.ProductoRequisicion> itemsToDelete = requestParameters.itemsToRemove;
        String multiplicadorId = requestParameters.multiplicadorId;
        String marca = requestParameters.marca;
        String tipo = requestParameters.tipo;
        String regiaoComercial = requestParameters.regiaoComercial;
        Boolean paraAprobacion = requestParameters.paraAprobacion;
        
        try {

            Configuracion_BMX__c config = [SELECT id, PM_Safra_Actual_VB_Estimativa_de_Compra__c 
                                                FROM Configuracion_BMX__c 
                                                    ORDER BY CreatedDate ASC 
                                                        LIMIT 1];

            String safraActualEstimativaCompra = config.PM_Safra_Actual_VB_Estimativa_de_Compra__c;
            String resultado = '';
            Boolean deleteStatus = true;

            if(!String.isEmpty(requisicaoId)) {

                List<Requisicao_de_compra__c> requisicao = [SELECT Id, Multiplicador__c, Marca__c, Safra__c, Tipo__c, Regiao_comercial__c, Cantidad_Productos__c  
                                                                FROM Requisicao_de_compra__c 
                                                                    WHERE Id =: requisicaoId 
                                                                        LIMIT 1];

                if(!requisicao.isEmpty()){

                    resultado = editCreateProduct(requisicaoId, items);
                    
                    if(!itemsToDelete.isEmpty()){

                        deleteStatus = removeProducts(requisicaoId, itemsToDelete); 
                    }
                    
                } else {

                    result.message = Label.SalvarEstimativaAPI_Clarification_Message;
                    DataBase.rollback(savePoint);
                }
            
            } else {
                
                resultado = saveRequisicao(multiplicadorId, marca, safraActualEstimativaCompra, tipo, regiaoComercial, items);
            }
            
            if(!deleteStatus){

                result.message = Label.SalvarEstimativaAPI_Products_Quantity_Error_Message;
                resultado = null;
                DataBase.rollback(savePoint);

            } else if(!String.isEmpty(resultado)){

                List<Requisicao_de_compra__c> testResult = [SELECT Id, Multiplicador__c, Marca__c, Safra__c, Tipo__c, Regiao_comercial__c, Cantidad_Productos__c  
                                                                FROM Requisicao_de_compra__c 
                                                                    WHERE Id =: resultado 
                                                                        LIMIT 1];
        
                if(paraAprobacion){

                    requisicaoSumbitForApproval(resultado);
                }

                result.Id = resultado;
                result.message = Label.SalvarEstimativaAPI_Success_Message;
                result.status = true;
                response.statusCode = 200;
            } 
            
        } catch (Exception e) {

            String error = e.getMessage();

            if(error.contains('ALREADY_IN_PROCESS,')){

                error = error.split('ALREADY_IN_PROCESS,')[1];
            }

            result.message = Label.SalvarEstimativaAPI_Default_Error_Message + ':  ' +error;
            result.status = false;  
            response.statusCode = 404;
            DataBase.rollback(savePoint);
        }

        response.responseBody = Blob.valueOf(JSON.serialize(result));
    }

    private static String saveRequisicao(String multiplicadorId, String marca, String safra, String tipo, String regionComercial, List<aSiteVendaDeBasicaController.ProductoRequisicion> products) {

        List<Produto_de_Requisicao__c> listProdutoDeRequisicao = new List<Produto_de_Requisicao__c>();
        
        Requisicao_de_compra__c requisicaoDeCompra = new Requisicao_de_compra__c();
        requisicaoDeCompra.Multiplicador__c = multiplicadorId;
        requisicaoDeCompra.Marca__c = marca;
        requisicaoDeCompra.Safra__c = safra;
        requisicaoDeCompra.Tipo__c = tipo;
        requisicaoDeCompra.Regiao_comercial__c = regionComercial;
        insert requisicaoDeCompra;

        for(aSiteVendaDeBasicaController.ProductoRequisicion pr : products) {

            Produto_de_Requisicao__c produtoDeRequisicao = new Produto_de_Requisicao__c();
            produtoDeRequisicao.Quantidade__c = pr.cantidad;
            produtoDeRequisicao.Variedad__c = pr.variedadId;
            produtoDeRequisicao.Requisicao_de_compra__c = requisicaoDeCompra.Id;
            listProdutoDeRequisicao.add(produtoDeRequisicao);
        }
        
        if(!listProdutoDeRequisicao.isEmpty()) {
            insert listProdutoDeRequisicao;
        }

        return requisicaoDeCompra.Id;
    }

    private static String editCreateProduct(String requisicaoId, List<aSiteVendaDeBasicaController.ProductoRequisicion> products){

        List<Produto_de_Requisicao__c> productList = new List<Produto_de_Requisicao__c>();
        Map<Id, Produto_de_Requisicao__c> productByVariedad = new  Map<Id, Produto_de_Requisicao__c>();

        List<Produto_de_Requisicao__c> existingProductsList = [SELECT Id, Variedad__c, Quantidade__c 
                                                                   FROM Produto_de_Requisicao__c 
                                                                       WHERE Requisicao_de_compra__c = :requisicaoId];
            
            for(Produto_de_Requisicao__c pr : existingProductsList) {
    
                productByVariedad.put(pr.Variedad__c, pr);
            }
    
            for(aSiteVendaDeBasicaController.ProductoRequisicion product :products){
                    
                if(productByVariedad.containsKey(product.variedadId)){
    
                    Produto_de_Requisicao__c editableProduct = productByVariedad.get(product.variedadId);
                    editableProduct.Quantidade__c = product.cantidad;
                    productList.add(editableProduct);
    
                } else {
    
                        Produto_de_Requisicao__c produtoDeRequisicao = new Produto_de_Requisicao__c();
                        produtoDeRequisicao.Quantidade__c = product.cantidad;
                        produtoDeRequisicao.Variedad__c = product.variedadId;
                        produtoDeRequisicao.Requisicao_de_compra__c = requisicaoId;
                        productList.add(produtoDeRequisicao);
                    }
            }

        upsert productList;
        return requisicaoId;
    }

    private static Boolean removeProducts(String requisicaoId, List<aSiteVendaDeBasicaController.ProductoRequisicion> productsToDelete){

        List<Produto_de_Requisicao__c> listProdutoDeRequisicaoForDelete = new List<Produto_de_Requisicao__c>();
        List<Produto_de_Requisicao__c> existingProductsList = [SELECT Id, Variedad__c, Quantidade__c, Requisicao_de_compra__r.Cantidad_Productos__c 
                                                                    FROM Produto_de_Requisicao__c 
                                                                        WHERE Requisicao_de_compra__c = :requisicaoId];
        
        Map<Id, Produto_de_Requisicao__c> productByVariedad = new  Map<Id, Produto_de_Requisicao__c>();
        Boolean status = true;
 
        for(Produto_de_Requisicao__c pr : existingProductsList) {

            productByVariedad.put(pr.Variedad__c, pr);
        }
  
        if(productsToDelete.size() < existingProductsList[0].Requisicao_de_compra__r.Cantidad_Productos__c){

            for(aSiteVendaDeBasicaController.ProductoRequisicion productToDelete :productsToDelete){

                if(productByVariedad.containsKey(productToDelete.variedadId)){
                    Produto_de_Requisicao__c productToRemove = productByVariedad.get(productToDelete.variedadId);
                    listProdutoDeRequisicaoForDelete.add(productToRemove);
                }
            }

            delete listProdutoDeRequisicaoForDelete;

        } else{

            status = false;
        }

        return status;
    }

    private static void requisicaoSumbitForApproval(String reqId) {     
            Approval.ProcessSubmitRequest req = new Approval.ProcessSubmitRequest();
            req.setObjectId(reqId);
            Approval.ProcessResult result = Approval.process(req);
        }

    public class Response {
        public String id;
        public Boolean status;
        public String message;
    }
    
    public class Request {
        public List<aSiteVendaDeBasicaController.ProductoRequisicion> items;
        public List<aSiteVendaDeBasicaController.ProductoRequisicion> itemsToRemove;
        public String requisicaoId;
        public String multiplicadorId;
        public String marca;
        public String tipo;
        public String regiaoComercial;
        public Boolean paraAprobacion;
    }
}