Salesforce/main/default/objects/Configuracion_BMX__c/Configuracion_BMX__c.object-meta.xml
<CustomObject>
    <description>Indicador de Parametros.</description>
    <label>Configuracion_BMX</label>
    <nameField>
        <label>Configuracion Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuraciones_BMX</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/Configuracion_BMX__c/fields/FC_Mandante_SAP__c.field-meta.xml
<CustomField>
    <fullName>FC_Mandante_SAP__c</fullName>
    <label>FC Mandante SAP</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/SAP_environment_variables__mdt/SAP_environment_variables__mdt.object-meta.xml
<CustomObject>
    <label>SAP_environment_variables</label>
    <pluralLabel>SAP_environment_variables</pluralLabel>
</CustomObject>

Salesforce/main/default/classes/UtilsTest.cls
@isTest
public with sharing class UtilsTest {

    @testSetup static void setup() {
        Configuracion_BMX__c configuracionBMX = new Configuracion_BMX__c();
        configuracionBMX.FC_Mandante_SAP__c = 'TEST';

        insert configuracionBMX;
    }

    @isTest static void testGetSAPCredentialsBase64Encoded() {
        SAP_environment_variables__mdt SAPEnviromentMtd = [
                SELECT
                Username__c,
                Password__c
            FROM
                SAP_environment_variables__mdt];

        String stringToBlob = SAPEnviromentMtd.Username__c + ':' + SAPEnviromentMtd.Password__c;
        Blob hash = Blob.valueOf(stringToBlob);
        String expectedCredentials = EncodingUtil.base64Encode(hash);

        Test.startTest();
        String result = Utils.getSAPCredentialsBase64Encoded();
        Test.stopTest();

        system.assertequals(expectedCredentials, result, 'The result doesnt match the expected result');
    }

    @isTest static void testGetSAPEnvTarget() {
        String expectedResult = 'TEST';

        Test.startTest();
        String result = Utils.getSAPEnvTarget();
        Test.stopTest();

        system.assertequals(expectedResult, result, 'The result doesnt match the expected result');
    }

    
    /**
     *  METHOD:         testGetFieldValues 
     *  DESCRIPTION:    test method for Utils.getFieldValues
     *  AUTHOR:         irina.benitez@cloudgaia.com (26-ago-21)
     **/ 
    @isTest
    static void testGetFieldValues() {

        String targetObject = 'Configuracion_BMX__c';
        List<String> listOfFields = new List<String>{'Id', 'FC_Mandante_SAP__c'};
        List<SObject> result;

        test.startTest();
        result = Utils.getFieldValues(targetObject, listOfFields, null, null);
        test.stopTest();

        System.assertEquals('TEST', result[0].get(listOfFields[1]), 'The result doesnt match the expected result');

    }

    /**
     *  METHOD:         testGetFieldValuesAura 
     *  DESCRIPTION:    test method for Utils.getFieldValuesAura
     *  AUTHOR:         irina.benitez@cloudgaia.com (26-ago-21)
     **/ 
    @isTest
    static void testGetFieldValuesAura() {

        String targetObject = 'Configuracion_BMX__c';
        List<String> listOfFields = new List<String>{'Id', 'FC_Mandante_SAP__c'};
        List<SObject> result;

        test.startTest();
        result = Utils.getFieldValuesAura(targetObject, listOfFields, null, null);
        test.stopTest();

        System.assertEquals('TEST', result[0].get(listOfFields[1]), 'The result doesnt match the expected result');

    }

    /**
     *  METHOD:         testGetFieldValuesFullAura 
     *  DESCRIPTION:    test method for Utils.getFieldValuesAura w/ all parameters
     *  AUTHOR:         irina.benitez@cloudgaia.com (1-sep-21)
     **/ 
    @isTest
    static void testGetFieldValuesFullAura() {

        String targetObject = 'Configuracion_BMX__c';
        List<String> listOfFields = new List<String>{'Id', 'FC_Mandante_SAP__c'};
        String filter = 'FC_Mandante_SAP__c = \'TEST\'';
        String orderBy = 'Id';
        List<SObject> result;

        test.startTest();
        result = Utils.getFieldValuesAura(targetObject, listOfFields, filter, orderBy);
        test.stopTest();

        System.assertEquals('TEST', result[0].get(listOfFields[1]), 'The result doesnt match the expected result');

    }
}