Salesforce/main/default/main/default/objects/Cidade__c/Cidade__c.object-meta.xml
<CustomObject>
    <label>Ciudad</label>
    <nameField>
        <label>Nome da Cidade</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ciudades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/Cidade__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Estado</label>
    <referenceTo>Estado__c</referenceTo>
    <relationshipName>Cidades</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/Cidade__c/fields/Nombre_Estado__c.field-meta.xml
<CustomField>
    <fullName>Nombre_Estado__c</fullName>
    <formula>Estado__r.Name</formula>
    <label>Nombre Estado</label>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/Estado__c/Estado__c.object-meta.xml
<CustomObject>
    <label>Estado</label>
    <nameField>
        <label>Nome do Estado</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estados</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/classes/CidadesAPI.cls
@RestResource(urlMapping='/CidadesAPI/*')
global with sharing class CidadesAPI {

    /**
     *  SUBCLASS:       Response
     *  DESCRIPTION:    wrapper class for Cidades API response. Created for US #13357
     *  AUTHOR:         irina.benitez@cloudgaia.com (21-oct-21)
     **/ 
    public class Response {
        public Boolean status;
        public String message;
        public List<Cidade__c> cidades;
    }

     /**
     *  METHOD:         getCidades 
     *  PARAMETERS:     -
     *  RETURN:         message: displays 'success' or error message  
     *                  status: boolean shows if operation was succesfull
     *                  cidades: list of records to return
     *  DESCRIPTION:    Return list of Cidades for an Event type. Created for US #13082
     *  AUTHOR:         irina.benitez@cloudgaia.com (21-oct-21)
     **/ 
    @HttpGet
    global static void getCidades() {

        RestResponse resp = RestContext.response;
        resp.statusCode = 404;

        CidadesAPI.Response result = new CidadesAPI.Response();
        result.status = false;
        result.message = Label.CidadesAPI_Default_Error_Message;
        
        try {

            List<Cidade__c> cidadeList = [SELECT Id, Name, Estado__c, Nombre_Estado__c FROM Cidade__c];

            if( cidadeList != null && !cidadeList.isEmpty() ){
                result.cidades = cidadeList;
            }

        } catch (Exception exc) {
            resp.statusCode = 400;
            result.message = exc.getMessage();
        }
                
        if(result.cidades != null && !result.cidades.isEmpty()) {
            result.status = true;
            result.message = Label.CidadesAPI_Success_Message;
            resp.statusCode = 200;
        }

        resp.responseBody = Blob.valueOf(JSON.serialize(result));
        resp.headers.put('Content-Type', 'application/json');
        resp.headers.put('Content-Length', RestContext.response.responseBody.size()+'');
    }


}