Salesforce/main/default/main/default/objects/Contract/fields/Cultura__c.field-meta.xml
<CustomField>
    <fullName>Cultura__c</fullName>
    <defaultValue>&quot;SOJA&quot;</defaultValue>
    <label>Cultura</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/Contract/fields/Gerenciador__c.field-meta.xml
<CustomField>
    <fullName>Gerenciador__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Gerenciador</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contratos</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Contract/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Marca</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/main/default/objects/Contract/fields/Negocio__c.field-meta.xml
<CustomField>
    <fullName>Negocio__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Negocio</label>
    <referenceTo>Negocio_por_Conta__c</referenceTo>
    <relationshipLabel>Contratos</relationshipLabel>
    <relationshipName>Contratos</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/Contract/fields/Region_Comercial__c.field-meta.xml
<CustomField>
    <fullName>Region_Comercial__c</fullName>
    <label>Regiao Comercial</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

Salesforce/main/default/objects/Contract/fields/Supervidor__c.field-meta.xml
<CustomField>
    <fullName>Supervidor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supervidor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contratos1</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Contract/fields/Tipo_de_Assinatura__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Assinatura__c</fullName>
    <label>Tipo de Assinatura</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Manual</fullName>
            </value>
            <value>
                <fullName>Eletronica</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Contract/recordTypes/Macro_Milho.recordType-meta.xml
<RecordType>
    <fullName>Macro_Milho</fullName>
    <active>true</active>
    <label>Macro Milho</label>
</RecordType>

Salesforce/main/default/objects/Negocio_por_Conta__c/Negocio_por_Conta__c.object-meta.xml
<CustomObject>
    <label>Negocio por Conta</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Negocios por Contas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/objects/Negocio_por_Conta__c/fields/Cultura__c.field-meta.xml
<CustomField>
    <fullName>Cultura__c</fullName>
    <label>Cultura</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SOJA</fullName>
                <default>true</default>
                <label>SOJA</label>
            </value>
            <value>
                <fullName>MILHO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Negocio_por_Conta__c/fields/Gerenciador__c.field-meta.xml
<CustomField>
    <fullName>Gerenciador__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Gerenciador</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Negocios_por_Contas1</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Negocio_por_Conta__c/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Marca</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Marca</valueSetName>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Negocio_por_Conta__c/fields/Region_Comercial__c.field-meta.xml
<CustomField>
    <fullName>Region_Comercial__c</fullName>
    <label>Região Comercial</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BRASIL</fullName>
            </value>
            <value>
                <fullName>REGION 1</fullName>
            </value>
            <value>
                <fullName>REGION 2</fullName>
            </value>
            <value>
                <fullName>CERRADO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/objects/Negocio_por_Conta__c/fields/Supervidor__c.field-meta.xml
<CustomField>
    <fullName>Supervidor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supervidor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Negocios_por_Contas</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/globalValueSets/Marca.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BRMX</fullName>
    </customValue>
    <customValue>
        <fullName>DSEM</fullName>
    </customValue>
    <customValue>
        <fullName>NEOG</fullName>
    </customValue>
    <customValue>
        <fullName>DAGMA</fullName>
    </customValue>
    <customValue>
        <fullName>LICENÇAS</fullName>
    </customValue>
    <masterLabel>Marca</masterLabel>
</GlobalValueSet>

Salesforce/main/default/classes/ContractHelper.cls
/**
* @name ContractHelper
* @author Jhonny Peroza
* updated 07-09-2021
*/
public class ContractHelper {

    public static Id milhoRecordType = Schema.SObjectType.Contract.getRecordTypeInfosByDeveloperName().get('Macro_Milho').getRecordTypeId();

    public static void afterInsert(List<Contract> contractList) {

        List<Negocio_por_Conta__c> businessList = new List<Negocio_por_Conta__c>();
        businessList=getBusinessData(contractList); 
        updateContract(contractList, businessList); 

    }

    public static List<Negocio_por_Conta__c> getBusinessData(List<Contract> contractList) {

        List<String> businessId = new List<String>();

		for (Contract contract : contractList){
			businessId.add(contract.Negocio__c);
		}

        List<Negocio_por_Conta__c> businessList = [SELECT Id, Marca__c, Cultura__c, Region_Comercial__c, Supervidor__c, Gerenciador__c, Supervidor__r.ManagerId
                                                        FROM Negocio_por_Conta__c 
                                                            WHERE Id IN : businessId];                                     
        return businessList;
    }

    public static void updateContract(List<Contract> contractList, List<Negocio_por_Conta__c> businessList) {
    
        List<Contract> contratoList = new List<Contract>();

        for(Contract contract : contractList) {
            for(Negocio_por_Conta__c business : businessList) {
                if(business.Id == contract.Negocio__c && contract.RecordTypeId == milhoRecordType) {
                    Contract contractMap = new Contract();
                    contractMap.Id = contract.Id;
                    contractMap.Region_Comercial__c = business.Region_Comercial__c;
                    contractMap.Marca__c = business.Marca__c;
                    contractMap.Cultura__c = business.Cultura__c;
                    contractMap.Supervidor__c = business.Supervidor__c;
                    contractMap.OwnerId = business.Supervidor__c;
                    contractMap.Tipo_de_Assinatura__c = contract.Tipo_de_Assinatura__c != null ? contract.Tipo_de_Assinatura__c : 'Manual';
                    if(business.Supervidor__r.ManagerId == null) {
                        contract.addError('Verifique o campo ManagerId, aparentemente o supervisor deste negocio não possui um superior designado');
                    } else {
                        contractMap.Gerenciador__c = business.Supervidor__r.ManagerId;
                    }
                    contratoList.add(contractMap);
                }
            }
        }

        try {                       
            update contratoList;
        } catch (DmlException e) {
            System.debug('DML Error message: ' + e.getMessage());
        }
    }

    public static void generateContractPDF(Contract contract) {

        if(contract.RecordTypeId == milhoRecordType && contract.Status == 'Aguardando Asignatura') {
            if(!Test.isRunningTest()) {
                    PdfGeneratorController.generateContratoMacroDocusignPDF(contract.Id);   
            }
        }
    }

    public static void beforeUpdate (List<Contract> contractNew, Map<Id, Contract> contractOld) {
        validateContractStatus(contractNew, contractOld);
    }

    private static void validateContractStatus (List<Contract> contractNew, Map<Id, Contract> contractOld) {
        for(Contract contract : contractNew) {
            if(contract.RecordTypeId == milhoRecordType && contract.Status == 'Edição' && contract.Tipo_de_Assinatura__c != contractOld.get(contract.Id).Tipo_de_Assinatura__c) {
                contract.addError('O contrato está no estado de Edição, por favor, aguarde até que ele esteja no estado Pendente de impressão');
            }
            if(contract.RecordTypeId == milhoRecordType && contract.Status == 'Pendente de Aprovação' && contract.Tipo_de_Assinatura__c != contractOld.get(contract.Id).Tipo_de_Assinatura__c) {
                contract.addError('O contrato está no estado de Pendente de Aprovação, por favor, aguarde até que ele esteja no estado Pendente de impressão');
            }
        }
    }
}