Salesforce/main/default/objects/Nota_Fiscal_Eletr_nica__c/Nota_Fiscal_Eletr_nica__c.object-meta.xml
<CustomObject>
    <label>Nota Fiscal Eletrônica</label>
    <nameField>
        <displayFormat>NFE-{00000}</displayFormat>
        <label>Numero de Nota Fiscal Eletrônica</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notas fiscais eletrônicas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/objects/Nota_Fiscal_Eletr_nica__c/fields/Consulta_de_Datos_Realizada__c.field-meta.xml
<CustomField>
    <fullName>Consulta_de_Datos_Realizada__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Consulta de Datos Realizada</label>
    <type>Checkbox</type>
</CustomField>

Salesforce/main/default/objects/Nota_Fiscal_Eletr_nica__c/fields/NFe__c.field-meta.xml
<CustomField>
    <fullName>NFe__c</fullName>
    <externalId>true</externalId>
    <label>N° de Nota fiscal Electronica</label>
    <length>44</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Salesforce/main/default/main/default/objects/Nota_Fiscal_Eletr_nica__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pendente</fullName>
            </value>
            <value>
                <fullName>Em Análise</fullName>
            </value>
            <value>
                <fullName>Inválida</fullName>
            </value>
            <value>
                <fullName>Aprovada</fullName>
            </value>
            <value>
                <fullName>Reprovada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/Nota_Fiscal_Eletr_nica__c/fields/Vendedor__c.field-meta.xml
<CustomField>
    <fullName>Vendedor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendedor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Notas fiscais eletrônicas</relationshipLabel>
    <relationshipName>Notas_fiscais_eletr_nicas</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/classes/ActualizarNFEsNuevasBatchTest.cls
@isTest
public class ActualizarNFEsNuevasBatchTest {
    
    @testSetup static void setup() {
        Product2 prod = new Product2(Name='Generico Nota Fiscal');
        insert prod;
        
        PricebookEntry sPBE = new PricebookEntry(Pricebook2Id = test.getStandardPricebookId(), Product2Id = prod.id, UnitPrice = 1000);
        insert sPBE;
    }

    @isTest
    static void test1() {
        Contact cont = new Contact(
        	LastName = 'Test'
        );
        insert cont;
        
        Nota_Fiscal_Eletr_nica__c nfe = new Nota_Fiscal_Eletr_nica__c(
        	NFe__c = '35161147508411011603551000077959551093041003',
            Consulta_de_Datos_Realizada__c = false,
            Vendedor__c = cont.Id
        );
        insert nfe;
        
        integer status = 200;
        string mock = WSNFeTest.MockNFe();
        Test.setMock(HttpCalloutMock.class, new WSNFeMock(status, mock)); 
        
        Test.startTest();        
        Database.executeBatch(new ActualizarNFEsNuevasBatch());
        Test.stopTest();
        
        nfe = [
            SELECT Consulta_de_Datos_Realizada__c, Status__c
            FROM Nota_Fiscal_Eletr_nica__c 
            WHERE Id = :nfe.Id
        ];
        
        System.assertEquals(true, nfe.Consulta_de_Datos_Realizada__c);
        System.assertEquals('Em Análise', nfe.Status__c);
    }
}