Salesforce/main/default/main/default/objects/Regiao__c/Regiao__c.object-meta.xml
<CustomObject>
    <label>Región</label>
    <nameField>
        <label>Nome da Região</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regiones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/objects/SiteUser__c/SiteUser__c.object-meta.xml
<CustomObject>
    <description>Forma parte del circuito del Sitio Portal Web.</description>
    <label>SiteUser</label>
    <nameField>
        <label>Nombre de Usuário</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SiteUsers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/SiteUserSession__c/SiteUserSession__c.object-meta.xml
<CustomObject>
    <label>SiteUserSession</label>
    <nameField>
        <displayFormat>S{00000000}</displayFormat>
        <label>Nombre de SiteUserSession</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SiteUserSessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/SiteUserSession__c/fields/SiteUser__c.field-meta.xml
<CustomField>
    <fullName>SiteUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SiteUser</label>
    <referenceTo>SiteUser__c</referenceTo>
    <relationshipLabel>SiteUserSessions</relationshipLabel>
    <relationshipName>SiteUserSessions</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/main/default/objects/Variedad__c/Variedad__c.object-meta.xml
<CustomObject>
    <description>Variedades, disponibles para incluir en los Contratos de Multiplicación</description>
    <label>Variedad</label>
    <nameField>
        <label>Nome Comercial</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Variedades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/classes/EstimativaProductAPITest.cls
/**
* @name EstimativaProductAPITest
* @author Jhonny Peroza
* updated 04-11-2021
*/
@isTest
public class EstimativaProductAPITest {

    @isTest
    public static void estimativaProducts() {

        EstimativaProductAPI.response result;

        List<Regiao__c> regionsList = TestDataFactory.createRegions(1);
        List<Account> accountsList = TestDataFactory.createAccounts(regionsList);
        List<Variedad__c> varietyList = TestDataFactory.createVariety(1);
        List<User> userList = TestDataFactory.createUser(1);
        List<SiteUser__c> siteList = TestDataFactory.createSiteUser(1);
        List<SiteUserSession__c> sessionList = TestDataFactory.createSessionUser(1, siteList);

        RestRequest req = new RestRequest(); 
        req.requestURI = '/services/apexrest/EstimativaProductAPI/';
        req.addParameter('marca', 'BRMX');
        req.addParameter('accountId', accountsList[0].Id);
        req.httpMethod = 'GET';

        RestResponse resp = new RestResponse();
        RestContext.request = req;
        RestContext.response = resp;

        test.startTest();
        EstimativaProductAPI.getEstimativaProducts();
        test.stopTest();

        result = (EstimativaProductAPI.response)JSON.deserialize(resp.responseBody.toString(), EstimativaProductAPI.response.class);

        System.assertEquals(true, result.status);
        System.assertEquals(result.message, 'Existem produtos de estimativa');

    }

    @isTest
    public static void estimativaProductsNotFound() {

        EstimativaProductAPI.response result;

        List<Regiao__c> regionsList = TestDataFactory.createRegions(1);
        List<Account> accountsList = TestDataFactory.createAccounts(regionsList);
        List<Variedad__c> varietyList = TestDataFactory.createVariety(4);
        List<User> userList = TestDataFactory.createUser(1);
        List<SiteUser__c> siteList = TestDataFactory.createSiteUser(1);
        List<SiteUserSession__c> sessionList = TestDataFactory.createSessionUser(1, siteList);

        RestRequest req = new RestRequest(); 
        req.requestURI = '/services/apexrest/EstimativaProductAPI/';
        req.addParameter('marca', 'NEOG');
        req.addParameter('accountId', accountsList[0].Id);
        req.httpMethod = 'GET';

        RestResponse resp = new RestResponse();
        RestContext.request = req;
        RestContext.response = resp;

        test.startTest();
        EstimativaProductAPI.getEstimativaProducts();
        test.stopTest();

        result = (EstimativaProductAPI.response)JSON.deserialize(resp.responseBody.toString(), EstimativaProductAPI.response.class);

        System.assertEquals(false, result.status);
        System.assertEquals(result.message, 'Nenhum produto encontrado');

    }

}