Salesforce/main/default/objects/CRM_Calendario_de_Eventos__c/CRM_Calendario_de_Eventos__c.object-meta.xml
<CustomObject>
    <description>Registro de eventos programados pelo Multiplicador</description>
    <label>CRM Evento</label>
    <nameField>
        <label>Nome de CRM Evento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Eventos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce/main/default/main/default/objects/CRM_Calendario_de_Eventos__c/fields/Arquivos_cont__c.field-meta.xml
<CustomField>
    <fullName>Arquivos_cont__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Qde. Arquivos</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Salesforce/main/default/objects/CRM_Calendario_de_Eventos__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Conta multiplicador, que realizou ou eventos agendados</description>
    <inlineHelpText>Conta multiplicador, que realizou ou eventos agendados</inlineHelpText>
    <label>Nome da conta</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Agricultor__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Eventos (Cuenta)</relationshipLabel>
    <relationshipName>CRM_Calend_rio_de_eventos</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce/main/default/objects/CRM_Calendario_de_Eventos__c/fields/Evento__c.field-meta.xml
<CustomField>
    <fullName>Evento__c</fullName>
    <description>Tipo de evento</description>
    <inlineHelpText>Tipo de evento</inlineHelpText>
    <label>Evento</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Día de Campo</fullName>
            </value>
            <value>
                <fullName>Area comercial</fullName>
            </value>
            <value>
                <fullName>Emplacamento</fullName>
            </value>
            <value>
                <fullName>Encontro Técnico</fullName>
            </value>
            <value>
                <fullName>Estação DONMARIO MAS</fullName>
            </value>
            <value>
                <fullName>Feiras</fullName>
            </value>
            <value>
                <fullName>Jornada Técnica</fullName>
            </value>
            <value>
                <fullName>Lado a Lado</fullName>
            </value>
            <value>
                <fullName>Painel Técnico</fullName>
            </value>
            <value>
                <fullName>Palestra</fullName>
            </value>
            <value>
                <fullName>Strip Test</fullName>
            </value>
            <value>
                <fullName>Tour dos Máximos Rendimentos</fullName>
            </value>
            <value>
                <fullName>Treinamento</fullName>
            </value>
            <value>
                <fullName>CESB</fullName>
            </value>
            <value>
                <fullName>Outdoor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/main/default/objects/CRM_Calendario_de_Eventos__c/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <label>Safra</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>11/12</fullName>
            </value>
            <value>
                <fullName>12/13</fullName>
            </value>
            <value>
                <fullName>17/18</fullName>
            </value>
            <value>
                <fullName>18/19</fullName>
            </value>
            <value>
                <fullName>19/20</fullName>
            </value>
            <value>
                <fullName>20/21</fullName>
            </value>
            <value>
                <fullName>21/22</fullName>
                <default>true</default>
                <label>21/22</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce/main/default/classes/CRMEventosUpdaterBatchTest.cls
@isTest
public class CRMEventosUpdaterBatchTest {

    @isTest
    static void testBatch() {
                Account acc = new Account(
        	Name = 'Test'
        );
        
        CRM_Calendario_de_Eventos__c crmEvento = new CRM_Calendario_de_Eventos__c(
        	Name = 'Test',
            Evento__c = 'Día de Campo',
            Cuenta__c = acc.Id,
            Safra__c = '19/20'
        );
        insert crmEvento;
        
        ContentVersion cv = new ContentVersion(
            Title = 'Test',
            PathOnClient = 'Test.jpg',
            VersionData = Blob.valueOf('Test Content Data'),
            IsMajorVersion = true
        );
        insert cv;
        
        ContentDocumentLink cdl = new ContentDocumentLink(
        	ContentDocumentId = [SELECT ContentDocumentId FROM ContentVersion].ContentDocumentId,
        	LinkedEntityId = crmEvento.Id
        );
        insert cdl;
        
        crmEvento.Arquivos_cont__c = 0;
        update crmEvento;
        
        Test.startTest();
        Database.executeBatch(new CRMEventosUpdaterBatch());
        Test.stopTest();
        
        crmEvento = [
            SELECT Arquivos_cont__c
            FROM CRM_Calendario_de_Eventos__c
        ];
        
        System.assertEquals(1, crmEvento.Arquivos_cont__c);
    }
    
}